' Gambas module file

Public Sub AlterMySQLSpecCollationTable($con As Connection, hTabName As String)

  Dim acol As String
  Dim astx As String[]

  If $con.Type = "mysql" Then
    acol = modGeneralMain.$SysCollation
    If acol Then
      astx = Split(acol, "_")
      modDatabase.ChangeTableCOllation($con, astx[0], acol, hTabName)
    Endif
  Endif

End

Public Sub MySQLSpecificCollation($con As Connection)

  Dim acol As String
  Dim astx As String[]
  Dim hTable As Table

  If $con.Type = "mysql" Then
    acol = modGeneralMain.$SysCollation
    If acol Then
      astx = Split(acol, "_")
      For Each hTable In $con.Tables
        modDatabase.ChangeTableCOllation($con, astx[0], acol, hTable.Name)
      Next
    Endif

    modDatabase.ChangeSingleCOlumnCOllation($con, "tbllabel", "fldopinfo", "VARCHAR( 255 )", "utf8mb4", "utf8mb4_unicode_ci")
    modDatabase.ChangeSingleCOlumnCOllation($con, "tbllocallabel", "fldlocaldire", "VARCHAR( 255 )", "utf8mb4", "utf8mb4_unicode_ci")
  Endif

End

Public Sub CreateIRDTriggerLockEvent(sConn As Connection)

  Try sConn.MySQL.Trigger.Add("tblpatbilldetail_LockUpdate", "tblpatbilldetail", "BEFORE", "UPDATE", "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Custom Error'")
  Try sConn.MySQL.Trigger.Add("tblpatbilldetail_LockDelete", "tblpatbilldetail", "BEFORE", "DELETE", "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Custom Error'")

End

Public Sub CreateIRDTriggerBilling(sConn As Connection)

  Dim tblst As String[] = ["tblpatientinfo", "tblencounter", "tblservicecost"]
  Dim xtable As String

  For Each xtable In tblst
    Try CreateTrigger(sConn, xtable & "_" & "UPDATE", xtable, "BEFORE", "UPDATE")
    Try CreateTrigger(sConn, xtable & "_" & "DELETE", xtable, "BEFORE", "DELETE")
  Next

End

Private Sub CreateTrigger(sConn As Connection, sName As String, sTable As String, sTime As String, sEvent As String)

  Dim xstat As String
  Dim tabList As String[]
  Dim nwTblst As String[]
  Dim xx As String

  tabList = modDatabase.GetFIeldsinTable(sTable, True, sConn)
  modDatabase.CreateLogTable(sConn, sTable)
  If sConn.Type = "mysql" Then
    nwTblst = New String[]
    For Each xx In tabList
      nwTblst.Add("OLD." & xx)
    Next
    xstat = "INSERT INTO " & modDatabase.GetBackTableName(sTable) & "(" & tabList.Join(",") & ") VALUES (" & nwTblst.Join(",") & ")"
    sConn.MySQL.Trigger.Add(sName, sTable, sTime, sEvent, xstat)
    modDatabase.CHnageUniFIeldDefaultDateTime(sConn, modDatabase.GetBackTableName(sTable), "fldcurrtime")
  Endif

End
