' Gambas module file

''====================== FIXED TABLES: CAN BE PUT REMOTELY ============================
''---------------------------- For CreateDatabaseForSish_Medicine( ----------------------------
Public Sub CREATEtblmedcategory($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedcategory") Then
    hTable = $con.Tables.Add("tblmedcategory")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flclass", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsensidrugs($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsensidrugs") Then
    hTable = $con.Tables.Add("tblsensidrugs")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flclass", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblchemclass($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblchemclass") Then
    hTable = $con.Tables.Add("tblchemclass")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flclass", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcode($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcode") Then
    hTable = $con.Tables.Add("tblcode")
    hTable.Fields.Add("fldcodename", db.String, 150)
    hTable.Fields.Add("fldrecaddose", db.Float)
    hTable.Fields.Add("fldrecaddoseunit", db.String, 25)
    hTable.Fields.Add("fldrecadfreq", db.Integer)
    hTable.Fields.Add("fldrecpeddose", db.Float)
    hTable.Fields.Add("fldrecpeddoseunit", db.String, 25)
    hTable.Fields.Add("fldrecpedfreq", db.Integer)
    hTable.Fields.Add("fldchemclass", db.String, 150)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldprn", db.String, 25)
    hTable.Fields.Add("flddrugdetail", db.String, 255)
    hTable.Fields.Add("fldhelppage", db.String, 100)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("fldplasmaprotein", db.Float)
    hTable.Fields.Add("fldeliminhalflife", db.Float)
    hTable.Fields.Add("fldvoldistribution", db.Float)
    hTable.Fields.Add("fldeliminhepatic", db.Float)
    hTable.Fields.Add("fldeliminrenal", db.Float)
    hTable.Fields.Add("fldmechaction", db.String, 255)
    hTable.Fields.Add("fldsensname", db.String, 250)
    hTable.Fields.Add("fldrisklevel", db.String, 100)
    hTable.PrimaryKey = ["fldcodename"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcodelimit($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcodelimit") Then
    hTable = $con.Tables.Add("tblcodelimit")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcodename", db.String, 200)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldmaxfreq", db.Integer)
    hTable.Fields.Add("fldmaxundose", db.Float)
    hTable.Fields.Add("fldmaxundoseunit", db.String, 25)
    hTable.Fields.Add("fldmaxdaladdose", db.Float)
    hTable.Fields.Add("fldmaxdaladdoseunit", db.String, 25)
    hTable.Fields.Add("fldmindaladdose", db.Float)
    hTable.Fields.Add("fldmindaladdoseunit", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcompatdrug($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcompatdrug") Then
    hTable = $con.Tables.Add("tblcompatdrug")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcompatfluid($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcompatfluid") Then
    hTable = $con.Tables.Add("tblcompatfluid")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldilutionfluid($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldilutionfluid") Then
    hTable = $con.Tables.Add("tbldilutionfluid")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblincompatdrug($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblincompatdrug") Then
    hTable = $con.Tables.Add("tblincompatdrug")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblincompatfluid($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblincompatfluid") Then
    hTable = $con.Tables.Add("tblincompatfluid")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblreconstfluid($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblreconstfluid") Then
    hTable = $con.Tables.Add("tblreconstfluid")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldosageforms($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldosageforms") Then
    hTable = $con.Tables.Add("tbldosageforms")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flforms", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldrug($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldrug") Then
    hTable = $con.Tables.Add("tbldrug")
    hTable.Fields.Add("flddrug", db.String, 200)
    hTable.Fields.Add("fldcodename", db.String, 150)
    hTable.Fields.Add("fldstrength", db.Float)
    hTable.Fields.Add("fldstrunit", db.String, 25)
    hTable.Fields.Add("fldroute", db.String, 20)
    hTable.Fields.Add("fldhelppage", db.String, 100)
    hTable.Fields.Add("fldciyear", db.Float)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flddrug"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblinjection($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblinjection") Then
    hTable = $con.Tables.Add("tblinjection")
    hTable.Fields.Add("fldinjection", db.String, 255)
    hTable.Fields.Add("fldlabel", db.String, 250)
    hTable.Fields.Add("fldreconst", db.String, 255)
    hTable.Fields.Add("fldreconstroom", db.Float)
    hTable.Fields.Add("fldreconstcool", db.Float)
    hTable.Fields.Add("flddilution", db.String, 255)
    hTable.Fields.Add("flddilutionroom", db.Float)
    hTable.Fields.Add("flddilutioncool", db.Float)
    hTable.Fields.Add("fldrateadmin", db.String, 250)
    hTable.Fields.Add("fldsiteadmin", db.String, 250)
    hTable.Fields.Add("fldrouteadmin", db.String, 50)
    hTable.PrimaryKey = ["fldinjection"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbllabel($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbllabel") Then
    hTable = $con.Tables.Add("tbllabel")
    hTable.Fields.Add("fldlabel", db.String, 225)
    hTable.Fields.Add("flddrug", db.String, 200)
    hTable.Fields.Add("fldroute", db.String, 20)
    hTable.Fields.Add("fldopinfo", db.String, 255)
    hTable.Fields.Add("fldipinfo", db.String, 255)
    hTable.Fields.Add("fldasepinfo", db.String, 255)
    hTable.Fields.Add("fldmedinfo", db.String)
    hTable.Fields.Add("fldsubroute", db.String, 50)
    hTable.Fields.Add("fldfinalstr", db.Float)
    hTable.Fields.Add("fldopfont", db.String, 200)
    hTable.Fields.Add("fldosmolality", db.Float)
    hTable.Fields.Add("fldenergy", db.Float)
    hTable.PrimaryKey = ["fldlabel"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
    modDatabase.ChangeSingleCOlumnCOllation($con, "tbllabel", "fldopinfo", "VARCHAR( 255 )", "utf8mb4", "utf8mb4_unicode_ci")
  Endif

End

Public Sub CREATEtblmedbrand($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedbrand") Then
    hTable = $con.Tables.Add("tblmedbrand")
    hTable.Fields.Add("fldbrandid", db.String, 250)
    hTable.Fields.Add("flddrug", db.String, 200)
    hTable.Fields.Add("flddosageform", db.String, 50)
    hTable.Fields.Add("fldbrand", db.String, 50)
    hTable.Fields.Add("fldmanufacturer", db.String, 200)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.Fields.Add("fldstandard", db.String, 25)
    hTable.Fields.Add("fldpackvol", db.Float)
    hTable.Fields.Add("fldvolunit", db.String, 25)
    hTable.Fields.Add("fldmaxqty", db.Float)
    hTable.Fields.Add("fldminqty", db.Float)
    hTable.Fields.Add("fldleadtime", db.Integer)
    hTable.Fields.Add("fldpreservative", db.String, 250)
    hTable.Fields.Add("fldnarcotic", db.String, 10)
    hTable.Fields.Add("fldtabbreak", db.String, 10)
    hTable.Fields.Add("flddeflabel", db.String, 10)
    hTable.Fields.Add("fldactive", db.String, 10)
    hTable.Fields.Add("fldtaxcode", db.String, 150)
    hTable.PrimaryKey = ["fldbrandid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmedhepatic($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedhepatic") Then
    hTable = $con.Tables.Add("tblmedhepatic")
    hTable.Fields.Add("medid", db.Serial)
    hTable.Fields.Add("fldcodename", db.String, 150)
    hTable.Fields.Add("fldcondition", db.String, 50)
    hTable.Fields.Add("fldoutput", db.String, 255)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["medid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldcodename_fldcondition", ["fldcodename", "fldcondition"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmedinteraction($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedinteraction") Then
    hTable = $con.Tables.Add("tblmedinteraction")
    hTable.Fields.Add("medid", db.Serial)
    hTable.Fields.Add("fldcodename", db.String, 150)
    hTable.Fields.Add("fldcondition", db.String, 150)
    hTable.Fields.Add("fldoutput", db.String, 255)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["medid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldcodename_fldcondition", ["fldcodename", "fldcondition"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmedpregnancy($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedpregnancy") Then
    hTable = $con.Tables.Add("tblmedpregnancy")
    hTable.Fields.Add("medid", db.Serial)
    hTable.Fields.Add("fldcodename", db.String, 150)
    hTable.Fields.Add("fldcondition", db.String, 50)
    hTable.Fields.Add("fldoutput", db.String, 255)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["medid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldcodename_fldcondition", ["fldcodename", "fldcondition"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmedrenal($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedrenal") Then
    hTable = $con.Tables.Add("tblmedrenal")
    hTable.Fields.Add("medid", db.Serial)
    hTable.Fields.Add("fldcodename", db.String, 150)
    hTable.Fields.Add("fldgfrfrom", db.Float)
    hTable.Fields.Add("fldgfrto", db.Float)
    hTable.Fields.Add("fldoutput", db.String, 255)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["medid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldcodename_fldgfrfrom", ["fldcodename", "fldgfrfrom"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmedcontraindication($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedcontraindication") Then
    hTable = $con.Tables.Add("tblmedcontraindication")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 25)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmedadveffect($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedadveffect") Then
    hTable = $con.Tables.Add("tblmedadveffect")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 25)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmedmonitor($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedmonitor") Then
    hTable = $con.Tables.Add("tblmedmonitor")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 25)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblregimen($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblregimen") Then
    hTable = $con.Tables.Add("tblregimen")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldroute", db.String, 25)
    hTable.Fields.Add("fldcodename", db.String, 150)
    hTable.Fields.Add("flddisease", db.String, 255)
    hTable.Fields.Add("flddosetype", db.String, 25)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldgender", db.String, 25)
    hTable.Fields.Add("flddose", db.Float)
    hTable.Fields.Add("flddoseunit", db.String, 25)
    hTable.Fields.Add("fldfreq", db.String, 50)
    hTable.Fields.Add("fldday", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbllocallabel($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbllocallabel") Then
    hTable = $con.Tables.Add("tbllocallabel")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldengcode", db.String, 150)
    hTable.Fields.Add("fldengdire", db.String, 255)
    hTable.Fields.Add("fldfont", db.String, 255)
    hTable.Fields.Add("fldlocaldire", db.String, 255)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
    modDatabase.ChangeSingleCOlumnCOllation($con, "tbllocallabel", "fldlocaldire", "VARCHAR( 255 )", "utf8mb4", "utf8mb4_unicode_ci")
  Endif

End

Public Sub CREATEtblmedgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedgroup") Then
    hTable = $con.Tables.Add("tblmedgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldmedgroup", db.String, 200)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblproductgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblproductgroup") Then
    hTable = $con.Tables.Add("tblproductgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldmedgroup", db.String, 150)
    hTable.Fields.Add("fldroute", db.String, 25)
    hTable.Fields.Add("flditem", db.String, 255)
    hTable.Fields.Add("flddose", db.Float)
    hTable.Fields.Add("flddoseunit", db.String, 25)
    hTable.Fields.Add("fldfreq", db.String, 50)
    hTable.Fields.Add("fldday", db.Integer)
    hTable.Fields.Add("fldqty", db.Float)
    hTable.Fields.Add("fldstart", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsurgicalname($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsurgicalname") Then
    hTable = $con.Tables.Add("tblsurgicalname")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldsurgcateg", db.String, 25)
    hTable.Fields.Add("fldsurgname", db.String, 125)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsuturetype($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsuturetype") Then
    hTable = $con.Tables.Add("tblsuturetype")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldsuturetype", db.String, 250)
    hTable.Fields.Add("fldsuturecode", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsurgicals($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsurgicals") Then
    hTable = $con.Tables.Add("tblsurgicals")
    hTable.Fields.Add("fldsurgid", db.String, 200)
    hTable.Fields.Add("fldsurgname", db.String, 125)
    hTable.Fields.Add("fldsurgcateg", db.String, 25)
    hTable.Fields.Add("fldsurgsize", db.String, 25)
    hTable.Fields.Add("fldsurgtype", db.String, 25)
    hTable.Fields.Add("fldsurgcode", db.String, 25)
    hTable.Fields.Add("fldsurgdetail", db.String, 250)
    hTable.PrimaryKey = ["fldsurgid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsurgbrand($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsurgbrand") Then
    hTable = $con.Tables.Add("tblsurgbrand")
    hTable.Fields.Add("fldbrandid", db.String, 250)
    hTable.Fields.Add("fldsurgid", db.String, 200)
    hTable.Fields.Add("fldbrand", db.String, 50)
    hTable.Fields.Add("fldmanufacturer", db.String, 200)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.Fields.Add("fldstandard", db.String, 25)
    hTable.Fields.Add("fldmaxqty", db.Float)
    hTable.Fields.Add("fldminqty", db.Float)
    hTable.Fields.Add("fldleadtime", db.Integer)
    hTable.Fields.Add("fldtaxcode", db.String, 150)
    hTable.Fields.Add("fldactive", db.String, 10)
    hTable.PrimaryKey = ["fldbrandid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblextra($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblextra") Then
    hTable = $con.Tables.Add("tblextra")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldextraid", db.String, 200)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblextrabrand($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblextrabrand") Then
    hTable = $con.Tables.Add("tblextrabrand")
    hTable.Fields.Add("fldbrandid", db.String, 250)
    hTable.Fields.Add("fldextraid", db.String, 200)
    hTable.Fields.Add("fldbrand", db.String, 50)
    hTable.Fields.Add("fldpackvol", db.Float)
    hTable.Fields.Add("fldvolunit", db.String, 25)
    hTable.Fields.Add("fldmanufacturer", db.String, 200)
    hTable.Fields.Add("flddepart", db.String, 200)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.Fields.Add("fldstandard", db.String, 25)
    hTable.Fields.Add("fldmaxqty", db.Float)
    hTable.Fields.Add("fldminqty", db.Float)
    hTable.Fields.Add("fldleadtime", db.Integer)
    hTable.Fields.Add("fldtaxcode", db.String, 150)
    hTable.Fields.Add("fldactive", db.String, 10)
    hTable.PrimaryKey = ["fldbrandid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblfoodlist($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblfoodlist") Then
    hTable = $con.Tables.Add("tblfoodlist")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldfood", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblfoodtype($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblfoodtype") Then
    hTable = $con.Tables.Add("tblfoodtype")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldfoodtype", db.String, 200)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblfoodcontent($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblfoodcontent") Then
    hTable = $con.Tables.Add("tblfoodcontent")
    hTable.Fields.Add("fldfoodid", db.String, 250)
    hTable.Fields.Add("fldfood", db.String, 150)
    hTable.Fields.Add("fldsource", db.String, 250)
    hTable.Fields.Add("fldformat", db.String, 150)
    hTable.Fields.Add("fldfoodtype", db.String, 50)
    hTable.Fields.Add("fldfoodcode", db.String, 100)
    hTable.Fields.Add("fldfluid", db.Float)
    hTable.Fields.Add("fldenergy", db.Float)
    hTable.Fields.Add("fldprotein", db.Float)
    hTable.Fields.Add("fldproteincont", db.String, 250)
    hTable.Fields.Add("fldsugar", db.Float)
    hTable.Fields.Add("fldsugarcont", db.String, 250)
    hTable.Fields.Add("fldlipid", db.Float)
    hTable.Fields.Add("fldlipidcont", db.String, 250)
    hTable.Fields.Add("fldmineral", db.Float)
    hTable.Fields.Add("fldfibre", db.Float)

    hTable.Fields.Add("fldcalcium", db.Float)
    hTable.Fields.Add("fldphosphorous", db.Float)
    hTable.Fields.Add("fldiron", db.Float)
    hTable.Fields.Add("fldcarotene", db.Float)
    hTable.Fields.Add("fldthiamine", db.Float)
    hTable.Fields.Add("fldriboflavin", db.Float)
    hTable.Fields.Add("fldniacin", db.Float)
    hTable.Fields.Add("fldpyridoxine", db.Float)
    hTable.Fields.Add("fldfreefolic", db.Float)
    hTable.Fields.Add("fldtotalfolic", db.Float)
    hTable.Fields.Add("fldvitaminc", db.Float)

    hTable.Fields.Add("fldprep", db.String, 255)
    hTable.PrimaryKey = ["fldfoodid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblfoodgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblfoodgroup") Then
    hTable = $con.Tables.Add("tblfoodgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroup", db.String, 200)
    hTable.Fields.Add("flditemname", db.String, 200)
    hTable.Fields.Add("flditemamt", db.Float)
    hTable.Fields.Add("fldprep", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldietgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldietgroup") Then
    hTable = $con.Tables.Add("tbldietgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroup", db.String, 200)
    hTable.Fields.Add("flditemtype", db.String, 100)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flditemqty", db.Float)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblnutrition($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblnutrition") Then
    hTable = $con.Tables.Add("tblnutrition")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldfluid", db.Float)
    hTable.Fields.Add("fldprotein", db.Float)
    hTable.Fields.Add("fldlipid", db.Float)
    hTable.Fields.Add("flddextrose", db.Float)
    hTable.Fields.Add("fldnne", db.Float)
    hTable.Fields.Add("fldsodium", db.Float)
    hTable.Fields.Add("fldpotassium", db.Float)
    hTable.Fields.Add("fldvitamin", db.Float)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''----------------------------FOR CreateDatabaseForSish_Pathology---------------------------
Public Sub CREATEtblpathocategory($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpathocategory") Then
    hTable = $con.Tables.Add("tblpathocategory")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flclass", db.String, 150)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblbodyfluid($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblbodyfluid") Then
    hTable = $con.Tables.Add("tblbodyfluid")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldfluid", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsurveillance($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsurveillance") Then
    hTable = $con.Tables.Add("tblsurveillance")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flddisease", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblethnicgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblethnicgroup") Then
    hTable = $con.Tables.Add("tblethnicgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroupname", db.String, 250)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldiagnogroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldiagnogroup") Then
    hTable = $con.Tables.Add("tbldiagnogroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroupname", db.String, 250)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("fldcodeid", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsymptoms($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsymptoms") Then
    hTable = $con.Tables.Add("tblsymptoms")
    hTable.Fields.Add("fldsymptom", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldsymdetail", db.String, 250)
    hTable.PrimaryKey = ["fldsymptom"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsubsymptoms($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsubsymptoms") Then
    hTable = $con.Tables.Add("tblsubsymptoms")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldsymptom", db.String, 250)
    hTable.Fields.Add("fldsubsymptom", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpathosymp($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpathosymp") Then
    hTable = $con.Tables.Add("tblpathosymp")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldparenttype", db.String, 25)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldrelation", db.String, 25)
    hTable.Fields.Add("fldvalquali", db.String, 250)
    hTable.Fields.Add("fldvalquanti", db.Float)
    hTable.Fields.Add("fldsympfreq", db.String, 25)
    hTable.Fields.Add("fldbaserate", db.Float)
    hTable.Fields.Add("fldhitrate", db.Float)
    hTable.Fields.Add("fldfalserate", db.Float)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsyndromes($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsyndromes") Then
    hTable = $con.Tables.Add("tblsyndromes")
    hTable.Fields.Add("fldsyndrome", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldsymcode", db.String, 250)
    hTable.PrimaryKey = ["fldsyndrome"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpathotest($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpathotest") Then
    hTable = $con.Tables.Add("tblpathotest")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldparenttype", db.String, 25)
    hTable.Fields.Add("fldtestcategory", db.String, 100)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldrelation", db.String, 25)
    hTable.Fields.Add("fldvalquali", db.String, 250)
    hTable.Fields.Add("fldvalquanti", db.Float)
    hTable.Fields.Add("fldtesttype", db.String, 50)
    hTable.Fields.Add("fldtestunit", db.String, 25)
    hTable.Fields.Add("fldbaserate", db.Float)
    hTable.Fields.Add("fldhitrate", db.Float)
    hTable.Fields.Add("fldfalserate", db.Float)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpathoexam($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpathoexam") Then
    hTable = $con.Tables.Add("tblpathoexam")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldparenttype", db.String, 25)
    hTable.Fields.Add("fldexamcategory", db.String, 100)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldrelation", db.String, 25)
    hTable.Fields.Add("fldvalquali", db.String, 250)
    hTable.Fields.Add("fldvalquanti", db.Float)
    hTable.Fields.Add("fldexamtype", db.String, 50)
    hTable.Fields.Add("fldbaserate", db.Float)
    hTable.Fields.Add("fldhitrate", db.Float)
    hTable.Fields.Add("fldfalserate", db.Float)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltriage($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltriage") Then
    hTable = $con.Tables.Add("tbltriage")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("flddiagnotype", db.String, 25)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldrelation", db.String, 25)
    hTable.Fields.Add("fldvalquali", db.String, 250)
    hTable.Fields.Add("fldvalquanti", db.Float)
    hTable.Fields.Add("flddiagnounit", db.String, 100)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldbaserate", db.Float)
    hTable.Fields.Add("fldhitrate", db.Float)
    hTable.Fields.Add("fldfalserate", db.Float)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''----------------------------FOR CreateDatabaseForSish_Diagnostic---------------------------
Public Sub CREATEtblsysconst($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsysconst") Then
    hTable = $con.Tables.Add("tblsysconst")
    hTable.Fields.Add("fldsysconst", db.String, 150)
    hTable.Fields.Add("fldcategory", db.String, 50)
    hTable.PrimaryKey = ["fldsysconst"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltestmethod($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltestmethod") Then
    hTable = $con.Tables.Add("tbltestmethod")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldmethod", db.String, 150)
    hTable.Fields.Add("fldcateg", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsampletype($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsampletype") Then
    hTable = $con.Tables.Add("tblsampletype")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldsampletype", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltestcondition($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltestcondition") Then
    hTable = $con.Tables.Add("tbltestcondition")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtestcondition", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbllabchemical($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbllabchemical") Then
    hTable = $con.Tables.Add("tbllabchemical")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("flditemtype", db.String, 150)
    hTable.Fields.Add("flditem", db.String, 255)
    hTable.Fields.Add("fldamt", db.Float)
    hTable.Fields.Add("fldunit", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltest($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltest") Then
    hTable = $con.Tables.Add("tbltest")
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldsysconst", db.String, 100)
    hTable.Fields.Add("fldspecimen", db.String, 250)
    hTable.Fields.Add("fldcollection", db.String, 250)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldsensitivity", db.Float)
    hTable.Fields.Add("fldspecificity", db.Float)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldoption", db.String, 50)
    hTable.Fields.Add("fldcritical", db.Float)
    hTable.PrimaryKey = ["fldtestid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltestoption($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltestoption") Then
    hTable = $con.Tables.Add("tbltestoption")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldscale", db.Float)
    hTable.Fields.Add("fldscalegroup", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltestlimit($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltestlimit") Then
    hTable = $con.Tables.Add("tbltestlimit")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldmethod", db.String, 250)
    hTable.Fields.Add("fldminimum", db.Float)
    hTable.Fields.Add("fldmaximum", db.Float)
    hTable.Fields.Add("fldsensitivity", db.Float)
    hTable.Fields.Add("fldspecificity", db.Float)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldconvfactor", db.Float)
    hTable.Fields.Add("fldsinormal", db.Float)
    hTable.Fields.Add("fldsihigh", db.Float)
    hTable.Fields.Add("fldsilow", db.Float)
    hTable.Fields.Add("fldsiunit", db.String, 25)
    hTable.Fields.Add("fldmetnormal", db.Float)
    hTable.Fields.Add("fldmethigh", db.Float)
    hTable.Fields.Add("fldmetlow", db.Float)
    hTable.Fields.Add("fldmetunit", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltestcomment($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltestcomment") Then
    hTable = $con.Tables.Add("tbltestcomment")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldmax", db.Float)
    hTable.Fields.Add("fldmin", db.Float)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldunit", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcodehypo($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcodehypo") Then
    hTable = $con.Tables.Add("tblcodehypo")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcodehyper($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcodehyper") Then
    hTable = $con.Tables.Add("tblcodehyper")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsyndrohypo($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsyndrohypo") Then
    hTable = $con.Tables.Add("tblsyndrohypo")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 25)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsyndrohyper($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsyndrohyper") Then
    hTable = $con.Tables.Add("tblsyndrohyper")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 25)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltestquali($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltestquali") Then
    hTable = $con.Tables.Add("tbltestquali")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldsubtest", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsubtestquali($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsubtestquali") Then
    hTable = $con.Tables.Add("tblsubtestquali")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldsubtest", db.String, 200)
    hTable.Fields.Add("fldanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldscale", db.Float)
    hTable.Fields.Add("fldscalegroup", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblantipanel($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblantipanel") Then
    hTable = $con.Tables.Add("tblantipanel")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroup", db.String, 200)
    hTable.Fields.Add("flditemtype", db.String, 200)
    hTable.Fields.Add("flditemname", db.String, 200)
    hTable.Fields.Add("fldactive", db.String, 50)

    hTable.Fields.Add("fldsensimax", db.Float)
    hTable.Fields.Add("fldsensimin", db.Float)
    hTable.Fields.Add("fldintermax", db.Float)
    hTable.Fields.Add("fldintermin", db.Float)
    hTable.Fields.Add("fldresismax", db.Float)
    hTable.Fields.Add("fldresismin", db.Float)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblgrouptest($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblgrouptest") Then
    hTable = $con.Tables.Add("tblgrouptest")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroupname", db.String, 200)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldtesttype", db.String, 50)
    hTable.Fields.Add("fldactive", db.String, 100)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblstructexam($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblstructexam") Then
    hTable = $con.Tables.Add("tblstructexam")
    hTable.Fields.Add("fldheadcode", db.String, 250)
    ' hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldclass", db.String, 250)
    hTable.Fields.Add("fldsubclass", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 250)
    hTable.Fields.Add("flditemid", db.Integer)
    hTable.Fields.Add("flditem", db.String, 250)
    hTable.Fields.Add("fldheadid", db.Integer)
    hTable.Fields.Add("fldhead", db.String, 250)
    hTable.Fields.Add("fldsysconst", db.String, 100)
    hTable.Fields.Add("fldtesttype", db.String, 50)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("fldreferencee", db.String, 150)
    hTable.Fields.Add("fldclininfo", db.String, 255)
    hTable.PrimaryKey = ["fldheadcode"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblstructexamoption($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblstructexamoption") Then
    hTable = $con.Tables.Add("tblstructexamoption")
    hTable.Fields.Add("fldid", db.Serial)
    ' hTable.Fields.Add("fldclass", db.String, 250)
    ' hTable.Fields.Add("fldsubclass", db.String, 250)
    ' hTable.Fields.Add("fldcategory", db.String, 250)
    ' hTable.Fields.Add("flditem", db.String, 250)
    hTable.Fields.Add("fldhead", db.String, 250)
    hTable.Fields.Add("fldheadcode", db.String, 250)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcompexam($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcompexam") Then
    hTable = $con.Tables.Add("tblcompexam")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldsysconst", db.String, 100)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldeptexam($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldeptexam") Then
    hTable = $con.Tables.Add("tbldeptexam")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldsysconst", db.String, 100)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("flddept", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldeptexamoption($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldeptexamoption") Then
    hTable = $con.Tables.Add("tbldeptexamoption")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("flddept", db.String, 200)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblgroupexam($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblgroupexam") Then
    hTable = $con.Tables.Add("tblgroupexam")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroupname", db.String, 200)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblexam($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblexam") Then
    hTable = $con.Tables.Add("tblexam")
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldsysconst", db.String, 100)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldsensitivity", db.Float)
    hTable.Fields.Add("fldspecificity", db.Float)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldoption", db.String, 50)
    hTable.Fields.Add("fldcritical", db.Float)
    hTable.Fields.Add("fldstatus", db.String, 50)
    hTable.PrimaryKey = ["fldexamid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblexamoption($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblexamoption") Then
    hTable = $con.Tables.Add("tblexamoption")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldscale", db.Float)
    hTable.Fields.Add("fldscalegroup", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblexamlimit($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblexamlimit") Then
    hTable = $con.Tables.Add("tblexamlimit")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldmethod", db.String, 250)
    hTable.Fields.Add("fldminimum", db.Float)
    hTable.Fields.Add("fldmaximum", db.Float)
    hTable.Fields.Add("fldsensitivity", db.Float)
    hTable.Fields.Add("fldspecificity", db.Float)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldnormal", db.Float)
    hTable.Fields.Add("fldhigh", db.Float)
    hTable.Fields.Add("fldlow", db.Float)
    hTable.Fields.Add("fldunit", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblexamcomment($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblexamcomment") Then
    hTable = $con.Tables.Add("tblexamcomment")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldmax", db.Float)
    hTable.Fields.Add("fldmin", db.Float)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcodebrady($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcodebrady") Then
    hTable = $con.Tables.Add("tblcodebrady")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcodetachy($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcodetachy") Then
    hTable = $con.Tables.Add("tblcodetachy")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsyndrobrady($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsyndrobrady") Then
    hTable = $con.Tables.Add("tblsyndrobrady")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 25)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsyndrotachy($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsyndrotachy") Then
    hTable = $con.Tables.Add("tblsyndrotachy")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldparent", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 25)
    hTable.Fields.Add("fldchild", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldparent_fldchild", ["fldparent", "fldchild"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblexamquali($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblexamquali") Then
    hTable = $con.Tables.Add("tblexamquali")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldsubexam", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsubexamquali($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsubexamquali") Then
    hTable = $con.Tables.Add("tblsubexamquali")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldsubexam", db.String, 200)
    hTable.Fields.Add("fldanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldscale", db.Float)
    hTable.Fields.Add("fldscalegroup", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblradio($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblradio") Then
    hTable = $con.Tables.Add("tblradio")
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldsysconst", db.String, 100)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldsensitivity", db.Float)
    hTable.Fields.Add("fldspecificity", db.Float)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldoption", db.String, 50)
    hTable.Fields.Add("fldcritical", db.Float)
    hTable.PrimaryKey = ["fldexamid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblradiooption($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblradiooption") Then
    hTable = $con.Tables.Add("tblradiooption")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldscale", db.Float)
    hTable.Fields.Add("fldscalegroup", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblradiolimit($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblradiolimit") Then
    hTable = $con.Tables.Add("tblradiolimit")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldmethod", db.String, 250)
    hTable.Fields.Add("fldminimum", db.Float)
    hTable.Fields.Add("fldmaximum", db.Float)
    hTable.Fields.Add("fldsensitivity", db.Float)
    hTable.Fields.Add("fldspecificity", db.Float)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldnormal", db.Float)
    hTable.Fields.Add("fldhigh", db.Float)
    hTable.Fields.Add("fldlow", db.Float)
    hTable.Fields.Add("fldunit", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblradiocomment($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblradiocomment") Then
    hTable = $con.Tables.Add("tblradiocomment")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldagegroup", db.String, 25)
    hTable.Fields.Add("fldmax", db.Float)
    hTable.Fields.Add("fldmin", db.Float)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblradioquali($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblradioquali") Then
    hTable = $con.Tables.Add("tblradioquali")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldsubexam", db.String, 200)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("flddetail", db.String, 255)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsubradioquali($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsubradioquali") Then
    hTable = $con.Tables.Add("tblsubradioquali")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.String, 200)
    hTable.Fields.Add("fldsubexam", db.String, 200)
    hTable.Fields.Add("fldanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldscale", db.Float)
    hTable.Fields.Add("fldscalegroup", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblgroupradio($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblgroupradio") Then
    hTable = $con.Tables.Add("tblgroupradio")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroupname", db.String, 200)
    hTable.Fields.Add("fldtestid", db.String, 200)
    hTable.Fields.Add("fldtesttype", db.String, 50)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldactive", db.String, 100)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblprocname($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblprocname") Then
    hTable = $con.Tables.Add("tblprocname")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldprocname", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblgroupproc($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblgroupproc") Then
    hTable = $con.Tables.Add("tblgroupproc")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroupname", db.String, 200)
    hTable.Fields.Add("fldprocname", db.String, 200)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldemographic($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldemographic") Then
    hTable = $con.Tables.Add("tbldemographic")
    hTable.Fields.Add("flddemoid", db.String, 200)
    hTable.Fields.Add("fldoption", db.String, 50)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["flddemoid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldemogoption($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldemogoption") Then
    hTable = $con.Tables.Add("tbldemogoption")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flddemoid", db.String, 200)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcomplaints($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcomplaints") Then
    hTable = $con.Tables.Add("tblcomplaints")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldsymptom", db.String, 250)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldelivery($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldelivery") Then
    hTable = $con.Tables.Add("tbldelivery")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldelcomplication($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldelcomplication") Then
    hTable = $con.Tables.Add("tbldelcomplication")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblreferlist($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblreferlist") Then
    hTable = $con.Tables.Add("tblreferlist")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldlocation", db.String, 250)
    hTable.Fields.Add("fldcode", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblprocedure($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblprocedure") Then
    hTable = $con.Tables.Add("tblprocedure")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblanaesthesia($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblanaesthesia") Then
    hTable = $con.Tables.Add("tblanaesthesia")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblevents($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblevents") Then
    hTable = $con.Tables.Add("tblevents")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''----------------------------FOR CreateDatabaseForSish_Data---------------------------
Public Sub CREATEtblmedimage($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedimage") Then
    hTable = $con.Tables.Add("tblmedimage")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcateg", db.String, 250)
    hTable.Fields.Add("fldname", db.String, 250)
    hTable.Fields.Add("fldpic", db.Blob)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("flddet", db.String, 255)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblelectrolyte($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblelectrolyte") Then
    hTable = $con.Tables.Add("tblelectrolyte")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcategory", db.String, 50)
    hTable.Fields.Add("fldsalt", db.String, 250)
    hTable.Fields.Add("fldmg", db.Float)
    hTable.Fields.Add("fldmmol", db.Float)
    hTable.Fields.Add("fldmeq", db.Float)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblresearch($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblresearch") Then
    hTable = $con.Tables.Add("tblresearch")
    hTable.Fields.Add("fldstudycode", db.String, 150)
    hTable.Fields.Add("fldstudyname", db.String, 250)
    hTable.Fields.Add("fldstudylocat", db.String, 250)
    hTable.Fields.Add("fldsamplesize", db.Integer)
    hTable.Fields.Add("fldstudystart", db.Date)
    hTable.Fields.Add("fldstudyend", db.Date)
    hTable.Fields.Add("fldstudysample", db.String)
    hTable.Fields.Add("fldstudycriteria", db.String)
    hTable.Fields.Add("fldircconsentpic", db.Blob)
    hTable.Fields.Add("fldircconsentlink", db.String, 250)
    hTable.Fields.Add("fldconsentformpic", db.Blob)
    hTable.Fields.Add("fldconsentformlink", db.String, 250)
    hTable.Fields.Add("fldiintervireformpic", db.Blob)
    hTable.Fields.Add("fldinterviewformlink", db.String, 250)
    hTable.Fields.Add("fldstatus", db.String, 50)
    hTable.PrimaryKey = ["fldstudycode"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''========================== PATIENT DATA: LOCAL STORAGE ===============================
''----------------------------FOR CreateDatabaseForSish_System---------------------------
' ''to remove
' Public Sub CREATEtblid($con As Connection)
'
'   Dim hTable As Table
'
'   If Not $con.Tables.Exist("tblid") Then
'     hTable = $con.Tables.Add("tblid")
'     hTable.Fields.Add("fldid", db.Serial)
'     hTable.Fields.Add("fldpatientdno", db.Long)
'     hTable.Fields.Add("fldencounterid", db.Long)
'     hTable.Fields.Add("fldstockno", db.Long)
'     hTable.Fields.Add("fldreferenceno", db.Long)
'     hTable.Fields.Add("fldinvoiceno", db.Long)
'     hTable.Fields.Add("fldjournalno", db.Long)
'     hTable.Fields.Add("fldevoucherno", db.Long)
'     hTable.PrimaryKey = ["fldid"]
'     hTable.Update
'   Endif
'
' End
'
' Public Sub CREATEtblextid($con As Connection)
'
'   Dim hTable As Table
'
'   If Not $con.Tables.Exist("tblextid") Then
'     hTable = $con.Tables.Add("tblextid")
'     hTable.Fields.Add("fldid", db.Serial)
'     hTable.Fields.Add("fldadmitfile", db.Long)
'     hTable.Fields.Add("fldsampleid", db.Long)
'     hTable.PrimaryKey = ["fldid"]
'     hTable.Update
'   Endif
'
' End

Public Sub CREATEtblautoid($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblautoid") Then
    hTable = $con.Tables.Add("tblautoid")
    hTable.Fields.Add("fldtype", db.String, 25)
    hTable.Fields.Add("fldvalue", db.Long)
    hTable.PrimaryKey = ["fldtype"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblinvid($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblinvid") Then
    hTable = $con.Tables.Add("tblinvid")
    hTable.Fields.Add("fldinvcode", db.String, 25)
    hTable.Fields.Add("fldinvsub", db.String, 25)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.PrimaryKey = ["fldinvcode"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatsubs($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatsubs") Then
    hTable = $con.Tables.Add("tblpatsubs")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpatno", db.String, 50)
    hTable.Fields.Add("fldpatlen", db.Integer)
    hTable.Fields.Add("fldencid", db.String, 50)
    hTable.Fields.Add("fldenclen", db.Integer)
    hTable.Fields.Add("fldbooking", db.String, 50)
    hTable.Fields.Add("fldbooklen", db.Integer)
    hTable.Fields.Add("fldhospcode", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbllock($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbllock") Then
    hTable = $con.Tables.Add("tbllock")
    hTable.Fields.Add("fldlock", db.String, 50)
    hTable.PrimaryKey = ["fldlock"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblenclock($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblenclock") Then
    hTable = $con.Tables.Add("tblenclock")
    hTable.Fields.Add("fldid", db.Serial)
    ' hTable.Fields.Add("fldencounterval", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldlocktype", db.String, 250)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltabsettings($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltabsettings") Then
    hTable = $con.Tables.Add("tbltabsettings")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcategory", db.String, 250)
    hTable.Fields.Add("fldvalue", db.String, 250)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsettings($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsettings") Then
    hTable = $con.Tables.Add("tblsettings")
    hTable.Fields.Add("fldindex", db.String, 250)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcategory", db.String, 250)
    hTable.Fields.Add("fldvalue", db.String, 250)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.PrimaryKey = ["fldindex"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblgnupg($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblgnupg") Then
    hTable = $con.Tables.Add("tblgnupg")
    hTable.Fields.Add("fldkeyid", db.String, 250)
    hTable.Fields.Add("fldkeyname", db.String, 250)
    hTable.Fields.Add("fldfingerprint", db.String, 255)
    hTable.Fields.Add("fldpublic", db.Blob)
    hTable.Fields.Add("fldprivate", db.Blob)
    hTable.Fields.Add("fldpublink", db.String, 250)
    hTable.Fields.Add("fldprilink", db.String, 250)
    hTable.PrimaryKey = ["fldkeyid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblautoemail($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblautoemail") Then
    hTable = $con.Tables.Add("tblautoemail")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtousers", db.String, 250)
    hTable.Fields.Add("fldcctype", db.String, 50)
    hTable.Fields.Add("fldccusers", db.String, 250)
    hTable.Fields.Add("fldfromhost", db.String, 150)
    hTable.Fields.Add("fldfromuser", db.String, 150)
    hTable.Fields.Add("fldfrompass", db.String, 150)
    hTable.Fields.Add("fldsender", db.String, 150)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("fldsubject", db.String, 250)
    hTable.Fields.Add("fldcontent", db.String, 250)
    hTable.Fields.Add("fldreport", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcronjob($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcronjob") Then
    hTable = $con.Tables.Add("tblcronjob")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcategory", db.String, 50)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("fldscript", db.String)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldstatus", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblirdactivity($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblirdactivity") Then
    hTable = $con.Tables.Add("tblirdactivity")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldfrmname", db.String, 100)
    hTable.Fields.Add("fldcategory", db.String, 250)
    hTable.Fields.Add("fldactivity", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblactivity($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblactivity") Then
    hTable = $con.Tables.Add("tblactivity")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldfrmname", db.String, 100)
    hTable.Fields.Add("fldcategory", db.String, 250)
    hTable.Fields.Add("fldactivity", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbljobrecord($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbljobrecord") Then
    hTable = $con.Tables.Add("tbljobrecord")
    hTable.Fields.Add("fldindex", db.String, 250)
    hTable.Fields.Add("fldfrmname", db.String, 100)
    hTable.Fields.Add("fldfrmlabel", db.String, 250)
    hTable.Fields.Add("flduser", db.String, 25)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldentrytime", db.Date)
    hTable.Fields.Add("fldexittime", db.Date)
    hTable.Fields.Add("fldpresent", db.Boolean)
    hTable.Fields.Add("fldhostuser", db.String, 250)
    hTable.Fields.Add("fldhostip", db.String, 250)
    hTable.Fields.Add("fldhostname", db.String, 250)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.PrimaryKey = ["fldindex"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsystemlog($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsystemlog") Then
    hTable = $con.Tables.Add("tblsystemlog")
    hTable.Fields.Add("fldindex", db.String, 250)
    hTable.Fields.Add("flduser", db.String, 25)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldlogin", db.String, 50)
    hTable.Fields.Add("fldentrytime", db.Date)
    hTable.Fields.Add("fldhostuser", db.String, 250)
    hTable.Fields.Add("fldhostip", db.String, 250)
    hTable.Fields.Add("fldhostname", db.String, 250)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("flddevicepath", db.String, 250)
    hTable.Fields.Add("fldversion", db.String, 100)
    hTable.Fields.Add("fldmainserver", db.String, 250)
    hTable.Fields.Add("fldreadserver", db.String, 250)
    hTable.Fields.Add("fldfallserver", db.String, 250)
    hTable.Fields.Add("fldftpserver", db.String, 250)
    hTable.PrimaryKey = ["fldindex"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblreportlog($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblreportlog") Then
    hTable = $con.Tables.Add("tblreportlog")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldwindow", db.String, 50)
    hTable.Fields.Add("fldfile", db.Blob)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("fldhostuser", db.String, 250)
    hTable.Fields.Add("fldhostip", db.String, 250)
    hTable.Fields.Add("fldhostname", db.String, 250)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmessagelog($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmessagelog") Then
    hTable = $con.Tables.Add("tblmessagelog")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldwindow", db.String, 50)
    hTable.Fields.Add("fldtarget", db.String, 150)
    hTable.Fields.Add("fldmesstext", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)

    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("fldhostuser", db.String, 250)
    hTable.Fields.Add("fldhostip", db.String, 250)
    hTable.Fields.Add("fldhostname", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsmslog($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsmslog") Then
    hTable = $con.Tables.Add("tblsmslog")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldwindow", db.String, 50)
    hTable.Fields.Add("fldtarget", db.String, 150)
    hTable.Fields.Add("fldsmstext", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldstatus", db.String, 50)
    hTable.Fields.Add("fldsmsdate", db.Date)

    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("fldhostuser", db.String, 250)
    hTable.Fields.Add("fldhostip", db.String, 250)
    hTable.Fields.Add("fldhostname", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblstafflist($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblstafflist") Then
    hTable = $con.Tables.Add("tblstafflist")
    hTable.Fields.Add("fldptcode", db.String, 250)
    hTable.Fields.Add("fldptnamefir", db.String, 150)
    hTable.Fields.Add("fldptnamelast", db.String, 150)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldptaddvill", db.String, 150)
    hTable.Fields.Add("fldptadddist", db.String, 150)
    hTable.Fields.Add("fldptcontact", db.String, 150)
    hTable.Fields.Add("fldptbirday", db.Date)
    hTable.Fields.Add("fldemail", db.String, 250)
    hTable.Fields.Add("fldcitizen", db.String, 250)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("flddept", db.String, 250)
    hTable.Fields.Add("fldjoindate", db.Date)
    hTable.Fields.Add("fldenddate", db.Date)
    hTable.Fields.Add("fldcontype", db.String, 200)
    hTable.Fields.Add("fldpost", db.String, 200)  ''designation
    hTable.Fields.Add("fldstatus", db.String, 50)

    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldrank", db.String, 250)
    hTable.Fields.Add("fldunit", db.String, 250)
    hTable.Fields.Add("fldidentify", db.String, 250)
    hTable.Fields.Add("fldremark", db.String, 250)
    hTable.Fields.Add("fldreligion", db.String, 250)

    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldptcode"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbluser($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbluser") Then
    hTable = $con.Tables.Add("tbluser")
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldusername", db.String, 250)
    hTable.Fields.Add("fldpass", db.String, 250)
    hTable.Fields.Add("fldroot", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldcode", db.Integer)
    hTable.Fields.Add("fldfromdate", db.Date)
    hTable.Fields.Add("fldtodate", db.Date)
    hTable.Fields.Add("fldusercode", db.String, 250)
    hTable.Fields.Add("fldstatus", db.String, 50)

    hTable.Fields.Add("fldfaculty", db.Boolean)
    hTable.Fields.Add("fldpayable", db.Boolean)
    hTable.Fields.Add("fldreferral", db.Boolean)
    hTable.Fields.Add("fldopconsult", db.Boolean)
    hTable.Fields.Add("fldipconsult", db.Boolean)
    hTable.Fields.Add("fldsigna", db.Boolean)
    hTable.Fields.Add("fldreport", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["flduserid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblusercategory($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblusercategory") Then
    hTable = $con.Tables.Add("tblusercategory")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbluserimage($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbluserimage") Then
    hTable = $con.Tables.Add("tbluserimage")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldpic", db.Blob)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("fldhostuser", db.String, 250)
    hTable.Fields.Add("fldhostip", db.String, 250)
    hTable.Fields.Add("fldhostname", db.String, 250)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblreportuser($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblreportuser") Then
    hTable = $con.Tables.Add("tblreportuser")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldname", db.String, 150)
    hTable.Fields.Add("fldnamefont", db.String, 250)
    hTable.Fields.Add("fldsigimage", db.Blob)
    hTable.Fields.Add("fldtitle", db.String, 150)
    hTable.Fields.Add("flddetail", db.String, 250)
    hTable.Fields.Add("flddefault", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblkey($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblkey") Then
    hTable = $con.Tables.Add("tblkey")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("key1", db.String, 250)
    hTable.Fields.Add("key2", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblnewkey($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblnewkey") Then
    hTable = $con.Tables.Add("tblnewkey")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("key1", db.String, 250)
    hTable.Fields.Add("key2", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbluseraccess($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbluseraccess") Then
    hTable = $con.Tables.Add("tbluseraccess")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldaccess", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcompaccess($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcompaccess") Then
    hTable = $con.Tables.Add("tblcompaccess")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmacaccess($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmacaccess") Then
    hTable = $con.Tables.Add("tblmacaccess")
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("fldhostuser", db.String, 250)
    hTable.Fields.Add("fldhostpass", db.String, 250)
    hTable.Fields.Add("fldhostip", db.String, 250)
    hTable.Fields.Add("fldhostname", db.String, 250)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcompname", db.String, 250)
    hTable.Fields.Add("fldaccess", db.String, 50)
    hTable.Fields.Add("fldiptype", db.String, 50)
    hTable.Fields.Add("fldcode", db.Integer)
    hTable.PrimaryKey = ["fldhostmac"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbluserformaccess($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbluserformaccess") Then
    hTable = $con.Tables.Add("tbluserformaccess")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldcategory", db.String, 50)
    hTable.Fields.Add("fldformname", db.String, 250)
    hTable.Fields.Add("fldstatus", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblclinicentry($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblclinicentry") Then
    hTable = $con.Tables.Add("tblclinicentry")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldaccess", db.String, 250)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldstatus", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpersonal($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpersonal") Then
    hTable = $con.Tables.Add("tblpersonal")
    hTable.Fields.Add("perid", db.Serial)
    hTable.Fields.Add("fldcateg", db.String, 50)
    hTable.Fields.Add("fldthumb", db.Blob)
    hTable.Fields.Add("fldblob", db.Blob)
    hTable.Fields.Add("flddetail", db.String, 250)
    hTable.Fields.Add("fldextension", db.String, 10)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.PrimaryKey = ["perid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblfileshare($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblfileshare") Then
    hTable = $con.Tables.Add("tblfileshare")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldshared", db.String, 25)
    hTable.Fields.Add("fldperid", db.Long)
    hTable.Fields.Add("fldstatus", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''----------------------------FOR CreateDatabaseForSish_Finance---------------------------
Public Sub CREATEtblsurname($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsurname") Then
    hTable = $con.Tables.Add("tblsurname")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblhospitals($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblhospitals") Then
    hTable = $con.Tables.Add("tblhospitals")
    hTable.Fields.Add("fldhospcode", db.String, 50)
    hTable.Fields.Add("fldhospname", db.String, 250)
    hTable.Fields.Add("fldaddress", db.String, 250)
    hTable.Fields.Add("fldpality", db.String, 250)
    hTable.Fields.Add("fldprovince", db.String, 250)
    hTable.Fields.Add("flddistrict", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldlatitude", db.Float)
    hTable.Fields.Add("fldlongitude", db.Float)
    hTable.PrimaryKey = ["fldhospcode"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldistrict($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldistrict") Then
    hTable = $con.Tables.Add("tbldistrict")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmunicipals($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmunicipals") Then
    hTable = $con.Tables.Add("tblmunicipals")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpality", db.String, 250)
    hTable.Fields.Add("flddistrict", db.String, 250)
    hTable.Fields.Add("fldprovince", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblrelations($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblrelations") Then
    hTable = $con.Tables.Add("tblrelations")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldepartment($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldepartment") Then
    hTable = $con.Tables.Add("tbldepartment")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flddept", db.String, 50)
    hTable.Fields.Add("fldroom", db.String, 50)
    ' hTable.Fields.Add("fldhead", db.String, 250)
    hTable.Fields.Add("fldbedcharge", db.String, 250)
    hTable.Fields.Add("fldround", db.String, 250)

    hTable.Fields.Add("fldcateg", db.String, 150)
    hTable.Fields.Add("fldactive", db.String, 10)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldeptgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldeptgroup") Then
    hTable = $con.Tables.Add("tbldeptgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroupname", db.String, 250)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldepartmentbed($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldepartmentbed") Then
    hTable = $con.Tables.Add("tbldepartmentbed")
    hTable.Fields.Add("fldbed", db.String, 50)
    hTable.Fields.Add("flddept", db.String, 50)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.PrimaryKey = ["fldbed"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldiscount($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldiscount") Then
    hTable = $con.Tables.Add("tbldiscount")
    hTable.Fields.Add("fldtype", db.String, 100)
    hTable.Fields.Add("fldmode", db.String, 100)
    hTable.Fields.Add("fldpercent", db.Float)
    hTable.Fields.Add("fldamount", db.Float)
    hTable.Fields.Add("fldcredit", db.Float)
    hTable.Fields.Add("fldlab", db.Float)
    hTable.Fields.Add("fldradio", db.Float)
    hTable.Fields.Add("fldproc", db.Float)
    hTable.Fields.Add("fldequip", db.Float)
    hTable.Fields.Add("fldservice", db.Float)
    hTable.Fields.Add("fldother", db.Float)
    hTable.Fields.Add("fldmedicine", db.Float)
    hTable.Fields.Add("fldsurgical", db.Float)
    hTable.Fields.Add("fldextra", db.Float)
    hTable.Fields.Add("fldregist", db.Float)
    hTable.Fields.Add("fldyear", db.Date)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.PrimaryKey = ["fldtype"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblnodiscount($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblnodiscount") Then
    hTable = $con.Tables.Add("tblnodiscount")
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flditemtype", db.String, 200)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["flditemname"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcustdiscount($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcustdiscount") Then
    hTable = $con.Tables.Add("tblcustdiscount")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtype", db.String, 100)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flditemtype", db.String, 200)
    hTable.Fields.Add("fldpercent", db.Float)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblaccdemograp($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblaccdemograp") Then
    hTable = $con.Tables.Add("tblaccdemograp")
    hTable.Fields.Add("flddemoid", db.String, 200)
    hTable.Fields.Add("fldoption", db.String, 50)
    hTable.PrimaryKey = ["flddemoid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblaccdemogoption($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblaccdemogoption") Then
    hTable = $con.Tables.Add("tblaccdemogoption")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flddemoid", db.String, 200)
    hTable.Fields.Add("fldanswertype", db.String, 50)
    hTable.Fields.Add("fldanswer", db.String, 250)
    hTable.Fields.Add("fldindex", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblbillingset($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblbillingset") Then
    hTable = $con.Tables.Add("tblbillingset")
    hTable.Fields.Add("fldsetname", db.String, 50)
    hTable.PrimaryKey = ["fldsetname"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblschedule($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblschedule") Then
    hTable = $con.Tables.Add("tblschedule")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldbillingmode", db.String, 50)
    hTable.Fields.Add("fldtime", db.String, 50)
    hTable.Fields.Add("fldfromtime", db.Date)
    hTable.Fields.Add("fldtotime", db.Date)
    hTable.Fields.Add("fldday", db.String, 50)
    hTable.Fields.Add("flddaysvalue", db.String, 250)
    hTable.Fields.Add("fldmonth", db.String, 50)
    hTable.Fields.Add("fldmonthsvalue", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblbillitem($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblbillitem") Then
    hTable = $con.Tables.Add("tblbillitem")
    hTable.Fields.Add("fldbillitem", db.String, 200)
    hTable.Fields.Add("flditemcateg", db.String, 25)
    hTable.PrimaryKey = ["fldbillitem"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblbillsection($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblbillsection") Then
    hTable = $con.Tables.Add("tblbillsection")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldsection", db.String, 200)
    hTable.Fields.Add("fldcateg", db.String, 100)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcurrency($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcurrency") Then
    hTable = $con.Tables.Add("tblcurrency")
    hTable.Fields.Add("flditemunit", db.String, 50)
    hTable.Fields.Add("fldconversion", db.Float)
    hTable.PrimaryKey = ["flditemunit"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblservicecost($con As Connection)

  Dim hTable As Table

  ' If Not $con.Tables.Exist("tbltestcost") Then ''old name
  If Not $con.Tables.Exist("tblservicecost") Then
    hTable = $con.Tables.Add("tblservicecost")
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("fldcode", db.String, 50)
    hTable.Fields.Add("fldid", db.Integer)
    hTable.Fields.Add("fldbillitem", db.String, 200)
    hTable.Fields.Add("flditemtype", db.String, 200)
    hTable.Fields.Add("flditemcost", db.Float)
    hTable.Fields.Add("flditemunit", db.String, 50)
    hTable.Fields.Add("fldtarget", db.String, 50)  ''Target Comp or rate For
    hTable.Fields.Add("fldstatus", db.String, 50)  ''current status

    hTable.Fields.Add("fldgroup", db.String, 50)  ''Billing Mode
    hTable.Fields.Add("fldreport", db.String, 200)  ''Section
    hTable.Fields.Add("fldtaxcode", db.String, 150)
    hTable.Fields.Add("fldeditrate", db.Boolean)
    hTable.Fields.Add("fldeditdisc", db.Boolean)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["flditemname"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblreportgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblreportgroup") Then
    hTable = $con.Tables.Add("tblreportgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroup", db.String, 250)
    hTable.Fields.Add("flditemtype", db.String, 200)
    hTable.Fields.Add("flditemname", db.String, 200)
    hTable.Fields.Add("fldactive", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblcostgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblcostgroup") Then
    hTable = $con.Tables.Add("tblcostgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroup", db.String, 200)
    hTable.Fields.Add("flditemtype", db.String, 100)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblextrasetting($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblextrasetting") Then
    hTable = $con.Tables.Add("tblextrasetting")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcateg", db.String, 250)
    hTable.Fields.Add("flddiscpercent", db.Float)
    hTable.Fields.Add("fldcashmode", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldepconsult($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldepconsult") Then
    hTable = $con.Tables.Add("tbldepconsult")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flddept", db.String, 50)
    hTable.Fields.Add("fldbillingmode", db.String, 150)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldselect", db.String, 25)
    hTable.Fields.Add("fldmethod", db.String, 25)
    hTable.Fields.Add("flddate", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    ' hTable.Fields.Add("fldfromtime", db.Date)
    ' hTable.Fields.Add("fldtotime", db.Date)
    hTable.Fields.Add("fldquota", db.Integer)
    hTable.Fields.Add("fldreason", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbluserpay($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbluserpay") Then
    hTable = $con.Tables.Add("tbluserpay")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flditemtype", db.String, 200)
    hTable.Fields.Add("flditemshare", db.Float)
    hTable.Fields.Add("flditemtax", db.Float)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblservicegroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblservicegroup") Then
    hTable = $con.Tables.Add("tblservicegroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroup", db.String, 200)
    hTable.Fields.Add("flditemtype", db.String, 100)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flditemqty", db.Float)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblautogroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblautogroup") Then
    hTable = $con.Tables.Add("tblautogroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroup", db.String, 200)
    hTable.Fields.Add("flditemtype", db.String, 100)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flditemqty", db.Float)
    hTable.Fields.Add("fldbillingmode", db.String, 50)
    hTable.Fields.Add("fldexitemtype", db.String, 100)
    hTable.Fields.Add("fldcutoff", db.Date)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltaxgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltaxgroup") Then
    hTable = $con.Tables.Add("tbltaxgroup")
    hTable.Fields.Add("fldgroup", db.String, 150)
    hTable.Fields.Add("fldtaxper", db.Float)
    hTable.PrimaryKey = ["fldgroup"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldiscgroup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldiscgroup") Then
    hTable = $con.Tables.Add("tbldiscgroup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldgroup", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbljournal($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbljournal") Then
    hTable = $con.Tables.Add("tbljournal")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flddebitcateg", db.String, 250)
    hTable.Fields.Add("flddebitlfno", db.String, 250)
    hTable.Fields.Add("fldcreditcateg", db.String, 250)
    hTable.Fields.Add("fldcreditlfno", db.String, 250)
    hTable.Fields.Add("fldamt", db.Float)
    hTable.Fields.Add("flddate", db.Date)
    hTable.Fields.Add("flduser", db.String, 25)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldreference", db.String, 50)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblbanks($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblbanks") Then
    hTable = $con.Tables.Add("tblbanks")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldbankname", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblextrapayers($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblextrapayers") Then
    hTable = $con.Tables.Add("tblextrapayers")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpayername", db.String, 250)
    hTable.Fields.Add("fldpayeradd", db.String, 25)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblextrapayitems($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblextrapayitems") Then
    hTable = $con.Tables.Add("tblextrapayitems")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblassetsname($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblassetsname") Then
    hTable = $con.Tables.Add("tblassetsname")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("fldgroup", db.String, 250)
    hTable.Fields.Add("fldledger", db.String, 250)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblassetsentry($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblassetsentry") Then
    hTable = $con.Tables.Add("tblassetsentry")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("fldgroup", db.String, 250)
    hTable.Fields.Add("fldspecs", db.String, 250)
    hTable.Fields.Add("fldcode", db.String, 250)
    hTable.Fields.Add("fldmanufacturer", db.String, 250)
    hTable.Fields.Add("fldmodel", db.String, 250)
    hTable.Fields.Add("fldserial", db.String, 250)

    hTable.Fields.Add("fldledger", db.String, 250)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldpurdate", db.Date)
    hTable.Fields.Add("fldqty", db.Integer)
    hTable.Fields.Add("fldunit", db.String, 50)
    hTable.Fields.Add("flditemrate", db.Float)
    hTable.Fields.Add("fldtaxamt", db.Float)
    hTable.Fields.Add("flddiscamt", db.Float)
    hTable.Fields.Add("fldditemamt", db.Float)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcondition", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldrepairdate", db.Date)
    hTable.Fields.Add("flduser", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''---------------------------- For CreateDatabaseForSish_Inventory ----------------------------
Public Sub CREATEtblentry($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblentry") Then
    hTable = $con.Tables.Add("tblentry")
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldbatch", db.String, 50)
    hTable.Fields.Add("fldexpiry", db.Date)
    hTable.Fields.Add("fldqty", db.Float)
    hTable.Fields.Add("fldstatus", db.Integer)
    hTable.Fields.Add("fldsellpr", db.Float)
    hTable.Fields.Add("fldsav", db.Boolean)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcode", db.String, 50)    ''used for serial port
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldstockno"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldstockid", ["fldstockid"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblentrybackup($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblentrybackup") Then
    hTable = $con.Tables.Add("tblentrybackup")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldbatch", db.String, 50)
    hTable.Fields.Add("fldexpiry", db.Date)
    hTable.Fields.Add("fldqty", db.Float)
    hTable.Fields.Add("fldstatus", db.Integer)
    hTable.Fields.Add("fldsellpr", db.Float)
    hTable.Fields.Add("fldsav", db.Boolean)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcode", db.String, 50)

    hTable.Fields.Add("fldentrytime", db.Date)
    hTable.Fields.Add("flduser", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbladjustment($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbladjustment") Then
    hTable = $con.Tables.Add("tbladjustment")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldnetcost", db.Float)
    hTable.Fields.Add("fldsellpr", db.Float)
    hTable.Fields.Add("fldcompqty", db.Float)
    hTable.Fields.Add("fldcurrqty", db.Float)
    hTable.Fields.Add("fldreason", db.String, 255)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldsav", db.Boolean)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpurchase($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpurchase") Then
    hTable = $con.Tables.Add("tblpurchase")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpurtype", db.String, 25)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldmrp", db.Float)
    hTable.Fields.Add("flsuppcost", db.Float)
    hTable.Fields.Add("fldcasdisc", db.Float)
    hTable.Fields.Add("fldcasbonus", db.Float)
    hTable.Fields.Add("fldqtybonus", db.Float)
    hTable.Fields.Add("fldcarcost", db.Float)
    hTable.Fields.Add("fldnetcost", db.Float)
    hTable.Fields.Add("fldmargin", db.Float)
    hTable.Fields.Add("fldsellprice", db.Float)
    hTable.Fields.Add("fldtotalqty", db.Float)
    hTable.Fields.Add("fldreturnqty", db.Float)
    hTable.Fields.Add("fldtotalcost", db.Float)
    hTable.Fields.Add("fldpurdate", db.Date)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsav", db.Boolean)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("fldchk", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpurchasebill($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpurchasebill") Then
    hTable = $con.Tables.Add("tblpurchasebill")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldpurtype", db.String, 25)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("flddebit", db.Float)
    hTable.Fields.Add("fldcredit", db.Float)
    hTable.Fields.Add("fldtotaltax", db.Float)
    hTable.Fields.Add("fldlastdisc", db.Float)
    hTable.Fields.Add("fldpurdate", db.Date)
    hTable.Fields.Add("flduser", db.String, 25)
    hTable.Fields.Add("fldsav", db.Boolean)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblstockreturn($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblstockreturn") Then
    hTable = $con.Tables.Add("tblstockreturn")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldqty", db.Float)
    hTable.Fields.Add("fldcost", db.Float)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldnewreference", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblsupplier($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblsupplier") Then
    hTable = $con.Tables.Add("tblsupplier")
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldsuppaddress", db.String, 250)
    hTable.Fields.Add("fldsuppphone", db.String, 250)
    hTable.Fields.Add("fldcontactname", db.String, 250)
    hTable.Fields.Add("fldcontactphone", db.String, 250)
    hTable.Fields.Add("fldstartdate", db.Date)
    hTable.Fields.Add("fldpaymentmode", db.String, 25)
    hTable.Fields.Add("fldcreditday", db.Float)
    hTable.Fields.Add("fldactive", db.String, 10)
    hTable.Fields.Add("fldpaiddebit", db.Float)
    hTable.Fields.Add("fldleftcredit", db.Float)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldsuppname"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltenderlist($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltenderlist") Then
    hTable = $con.Tables.Add("tbltenderlist")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("flditemtype", db.String, 25)
    hTable.Fields.Add("fldfromdate", db.Date)
    hTable.Fields.Add("fldtodate", db.Date)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldtotalqty", db.Float)
    hTable.Fields.Add("fldmaxcost", db.Float)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsav", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpayment($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpayment") Then
    hTable = $con.Tables.Add("tblpayment")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldpayamount", db.Float)
    hTable.Fields.Add("fldpaytype", db.String, 50)
    hTable.Fields.Add("fldchequeno", db.String, 250)
    hTable.Fields.Add("fldbankname", db.String, 250)
    hTable.Fields.Add("fldpaidby", db.String, 250)
    hTable.Fields.Add("fldpaidbypost", db.String, 250)
    hTable.Fields.Add("fldrecvby", db.String, 250)
    hTable.Fields.Add("fldrecvbypost", db.String, 250)
    hTable.Fields.Add("fldrecvbycontact", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblrequest($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblrequest") Then
    hTable = $con.Tables.Add("tblrequest")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldqty", db.Float)
    hTable.Fields.Add("fldstatus", db.String, 25)

    hTable.Fields.Add("fldorduserid", db.String, 25)
    hTable.Fields.Add("fldordtime", db.Date)
    hTable.Fields.Add("fldordcomp", db.String, 50)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)

    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltransfer($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltransfer") Then
    hTable = $con.Tables.Add("tbltransfer")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldoldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldqty", db.Float)
    hTable.Fields.Add("fldnetcost", db.Float)
    hTable.Fields.Add("fldsellpr", db.Float)
    hTable.Fields.Add("fldsav", db.Boolean)

    hTable.Fields.Add("fldfromentrytime", db.Date)
    hTable.Fields.Add("fldfromuser", db.String, 25)
    hTable.Fields.Add("fldfromcomp", db.String, 50)
    hTable.Fields.Add("fldfromsav", db.Boolean)
    hTable.Fields.Add("fldtoentrytime", db.Date)
    hTable.Fields.Add("fldtouser", db.String, 25)
    hTable.Fields.Add("fldtocomp", db.String, 50)
    hTable.Fields.Add("fldtosav", db.Boolean)

    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldtoentrytime", ["fldtoentrytime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltarget($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltarget") Then
    hTable = $con.Tables.Add("tbltarget")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblbulksale($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblbulksale") Then
    hTable = $con.Tables.Add("tblbulksale")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtarget", db.String, 250)
    hTable.Fields.Add("fldbulktime", db.Date)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldnetcost", db.Float)
    hTable.Fields.Add("fldqtydisp", db.Float)
    hTable.Fields.Add("fldqtyret", db.Float)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''----------- blood/other products inventory
Public Sub CREATEtblmedinventory($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmedinventory") Then
    hTable = $con.Tables.Add("tblmedinventory")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldcode", db.String, 250)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldencname", db.String, 250)
    hTable.Fields.Add("fldcollect", db.Date)
    hTable.Fields.Add("fldexpiry", db.Date)
    hTable.Fields.Add("fldstatus", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldcode", ["fldcode"], True)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''----------------------------FOR CreateDatabaseForSish_Patient---------------------------
Public Sub CREATEtblpatientbook($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientbook") Then
    hTable = $con.Tables.Add("tblpatientbook")
    hTable.Fields.Add("fldbookingval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldptnamefir", db.String, 150)
    hTable.Fields.Add("fldptnamelast", db.String, 150)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldptaddvill", db.String, 150)
    hTable.Fields.Add("fldptadddist", db.String, 150)
    hTable.Fields.Add("fldptcontact", db.String, 150)
    hTable.Fields.Add("fldptguardian", db.String, 250)
    hTable.Fields.Add("fldrelation", db.String, 250)
    hTable.Fields.Add("fldptbirday", db.Date)
    hTable.Fields.Add("fldptadmindate", db.Date)
    hTable.Fields.Add("fldemail", db.String, 250)
    hTable.Fields.Add("fldptcode", db.String, 250)
    hTable.Fields.Add("fldconsultdate", db.Date)
    hTable.Fields.Add("fldadmitlocat", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldstate", db.String, 25)
    hTable.Fields.Add("fldbillingmode", db.String, 150)
    hTable.Fields.Add("fldorduserid", db.String, 25)
    hTable.Fields.Add("fldcomment", db.String, 255)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldbookingval"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatientinfo($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientinfo") Then
    hTable = $con.Tables.Add("tblpatientinfo")
    '     hTable.Fields.Add("fldpatientno", db.Long)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldptnamefir", db.String, 150)
    hTable.Fields.Add("fldptnamelast", db.String, 150)
    hTable.Fields.Add("fldethniccode", db.String, 250)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldptaddvill", db.String, 150)
    hTable.Fields.Add("fldptadddist", db.String, 150)
    hTable.Fields.Add("fldptaddward", db.String, 150)
    hTable.Fields.Add("fldptcontact", db.String, 150)
    hTable.Fields.Add("fldptguardian", db.String, 250)
    hTable.Fields.Add("fldrelation", db.String, 250)
    hTable.Fields.Add("fldptbirday", db.Date)
    hTable.Fields.Add("fldptadmindate", db.Date)
    hTable.Fields.Add("fldemail", db.String, 250)
    hTable.Fields.Add("fldptcode", db.String, 250)
    hTable.Fields.Add("flddiscount", db.String, 150)
    hTable.Fields.Add("fldadmitfile", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldencrypt", db.Boolean)
    hTable.Fields.Add("fldpassword", db.String, 250)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldupuser", db.String, 25)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldpatientval"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblencounter($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblencounter") Then
    hTable = $con.Tables.Add("tblencounter")
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    '     hTable.Fields.Add("fldpatientval", db.Long)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldadmitlocat", db.String, 100)
    hTable.Fields.Add("fldcurrlocat", db.String, 100)
    hTable.Fields.Add("flddoa", db.Date)
    hTable.Fields.Add("flddod", db.Date)
    hTable.Fields.Add("fldheight", db.String, 10)
    hTable.Fields.Add("fldcashdeposit", db.Float)
    hTable.Fields.Add("flddisctype", db.String, 150)
    hTable.Fields.Add("fldcashcredit", db.Float)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldadmission", db.String, 25)
    hTable.Fields.Add("fldfollowdate", db.Date)
    hTable.Fields.Add("fldreferto", db.String, 250)
    hTable.Fields.Add("fldregdate", db.Date)
    '     hTable.Fields.Add("fldadmitfile", db.Float) ''not used anywhere
    hTable.Fields.Add("fldcharity", db.Float)
    hTable.Fields.Add("fldbillingmode", db.String, 50)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldvisit", db.String, 50)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldencounterval"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldregdate", ["fldregdate"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpataccgeneral($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpataccgeneral") Then
    hTable = $con.Tables.Add("tblpataccgeneral")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldinput", db.String, 250) '''type ("Procedure")
    hTable.Fields.Add("fldtype", db.String, 250)  '''quali or quanti
    hTable.Fields.Add("flditem", db.String, 250)
    hTable.Fields.Add("fldreportquali", db.String, 250)
    hTable.Fields.Add("fldreportquanti", db.Float)
    hTable.Fields.Add("flddetail", db.String)
    hTable.Fields.Add("fldnewdate", db.Date)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatdevice($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatdevice") Then
    hTable = $con.Tables.Add("tblpatdevice")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("flddevicetype", db.String, 250)
    hTable.Fields.Add("flddevicepath", db.String, 250)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("fldhostuser", db.String, 250)
    hTable.Fields.Add("fldhostip", db.String, 250)
    hTable.Fields.Add("fldhostname", db.String, 250)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatientdate($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientdate") Then
    hTable = $con.Tables.Add("tblpatientdate")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldhead", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatientexam($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientexam") Then
    hTable = $con.Tables.Add("tblpatientexam")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldserial", db.Integer) ''''NOT Required: Kept only for mobile compatibility
    hTable.Fields.Add("fldserialval", db.String, 250)
    hTable.Fields.Add("fldinput", db.String, 250) '''type (ClinExam,Exam,Test)
    hTable.Fields.Add("fldtype", db.String, 250)  '''quali or quanti
    hTable.Fields.Add("fldhead", db.String, 250)
    hTable.Fields.Add("fldsysconst", db.String, 100)
    hTable.Fields.Add("fldoption", db.String, 50)
    hTable.Fields.Add("fldmethod", db.String, 250)
    hTable.Fields.Add("fldrepquali", db.String)
    hTable.Fields.Add("fldrepquanti", db.Float)
    hTable.Fields.Add("fldfilepath", db.String, 250)
    hTable.Fields.Add("fldrepdate", db.Date)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldabnormal", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatientsubexam($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientsubexam") Then
    hTable = $con.Tables.Add("tblpatientsubexam")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldheadid", db.Long)
    hTable.Fields.Add("fldsubtexam", db.String, 200)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("fldreport", db.String)
    hTable.Fields.Add("fldabnormal", db.Boolean)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldchk", db.Boolean)
    hTable.Fields.Add("fldfilepath", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldheadid", ["fldheadid"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatexamsubtable($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatexamsubtable") Then
    hTable = $con.Tables.Add("tblpatexamsubtable")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.Long)
    hTable.Fields.Add("fldsubexamid", db.Long)
    hTable.Fields.Add("fldtype", db.String, 150)
    hTable.Fields.Add("fldvariable", db.String, 200)
    hTable.Fields.Add("fldvalue", db.String, 250)
    hTable.Fields.Add("fldcolm2", db.String, 250)
    hTable.Fields.Add("fldcolm3", db.String, 250)
    hTable.Fields.Add("fldcolm4", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldsubexamid", ["fldsubexamid"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatlabtest($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatlabtest") Then
    hTable = $con.Tables.Add("tblpatlabtest")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtestid", db.String, 250)
    hTable.Fields.Add("fldmethod", db.String, 250)
    hTable.Fields.Add("fldgroupid", db.Long)
    hTable.Fields.Add("fldsampleid", db.String, 250)
    hTable.Fields.Add("fldsampletype", db.String, 250)
    hTable.Fields.Add("fldreportquali", db.String)
    hTable.Fields.Add("fldreportquanti", db.Float)
    hTable.Fields.Add("fldfilepath", db.String, 250)
    hTable.Fields.Add("fldtestunit", db.String, 25)
    hTable.Fields.Add("fldstatus", db.String, 250)
    hTable.Fields.Add("fldprint", db.Boolean)
    hTable.Fields.Add("fldabnormal", db.Boolean)
    hTable.Fields.Add("fldrefername", db.String, 250)
    hTable.Fields.Add("fldcondition", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 255)
    hTable.Fields.Add("flvisible", db.String, 50)

    hTable.Fields.Add("fldtest_type", db.String, 50)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldchk", db.Boolean)
    hTable.Fields.Add("fldorder", db.Integer)

    hTable.Fields.Add("flduserid_sample", db.String, 25)
    hTable.Fields.Add("fldtime_sample", db.Date)
    hTable.Fields.Add("fldcomp_sample", db.String, 50)
    hTable.Fields.Add("fldsave_sample", db.Boolean)
    hTable.Fields.Add("flduptime_sample", db.Date)

    hTable.Fields.Add("flduserid_start", db.String, 25)
    hTable.Fields.Add("fldtime_start", db.Date)
    hTable.Fields.Add("fldcomp_start", db.String, 50)
    hTable.Fields.Add("fldsave_start", db.Boolean)
    hTable.Fields.Add("flduptime_start", db.Date)

    hTable.Fields.Add("flduserid_report", db.String, 25)
    hTable.Fields.Add("fldtime_report", db.Date)
    hTable.Fields.Add("fldcomp_report", db.String, 50)
    hTable.Fields.Add("fldsave_report", db.Boolean)
    hTable.Fields.Add("flduptime_report", db.Date)

    hTable.Fields.Add("flduserid_verify", db.String, 25)
    hTable.Fields.Add("fldtime_verify", db.Date)
    hTable.Fields.Add("fldcomp_verify", db.String, 50)
    hTable.Fields.Add("fldsave_verify", db.Boolean)
    hTable.Fields.Add("flduptime_verify", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldsampleid", ["fldsampleid"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime_sample", ["fldtime_sample"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatlabsubtest($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatlabsubtest") Then
    hTable = $con.Tables.Add("tblpatlabsubtest")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtestid", db.Long)
    hTable.Fields.Add("fldsubtest", db.String, 200)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("fldreport", db.String)
    hTable.Fields.Add("fldabnormal", db.Boolean)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldchk", db.Boolean)
    hTable.Fields.Add("fldorder", db.Integer)
    hTable.Fields.Add("fldfilepath", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldtestid", ["fldtestid"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatlabsubtable($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatlabsubtable") Then
    hTable = $con.Tables.Add("tblpatlabsubtable")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldtestid", db.Long)
    hTable.Fields.Add("fldsubtestid", db.Long)
    hTable.Fields.Add("fldtype", db.String, 150)
    hTable.Fields.Add("fldvariable", db.String, 200)
    hTable.Fields.Add("fldvalue", db.String, 250)
    hTable.Fields.Add("fldcolm2", db.String, 250)
    hTable.Fields.Add("fldcolm3", db.String, 250)
    hTable.Fields.Add("fldcolm4", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldsubtestid", ["fldsubtestid"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatfindings($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatfindings") Then
    hTable = $con.Tables.Add("tblpatfindings")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtype", db.String, 50)
    hTable.Fields.Add("fldcode", db.String, 255)
    hTable.Fields.Add("fldcodeid", db.String, 255)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblexamgeneral($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblexamgeneral") Then
    hTable = $con.Tables.Add("tblexamgeneral")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldinput", db.String, 250) '''type
    hTable.Fields.Add("fldtype", db.String, 250)  '''quali or quanti
    hTable.Fields.Add("flditem", db.String, 250)
    hTable.Fields.Add("fldreportquali", db.String, 250)
    hTable.Fields.Add("fldreportquanti", db.Float)
    hTable.Fields.Add("flddetail", db.String)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatgeneral($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatgeneral") Then
    hTable = $con.Tables.Add("tblpatgeneral")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldinput", db.String, 250) '''type ("Procedure")
    ' hTable.Fields.Add("fldtype", db.String, 250)  '''quali or quanti
    hTable.Fields.Add("flditem", db.String, 250)
    hTable.Fields.Add("fldreportquali", db.String, 250)
    hTable.Fields.Add("fldstatus", db.String, 25)
    '     hTable.Fields.Add("fldreportquanti", db.Float)
    hTable.Fields.Add("flddetail", db.String)
    hTable.Fields.Add("fldnewdate", db.Date)
    hTable.Fields.Add("fldbillingmode", db.String, 150)
    hTable.Fields.Add("fldorduserid", db.String, 25)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatsubgeneral($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatsubgeneral") Then
    hTable = $con.Tables.Add("tblpatsubgeneral")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("flditemid", db.Long)
    hTable.Fields.Add("fldchapter", db.String, 200)
    hTable.Fields.Add("fldreportquali", db.String, 250)
    hTable.Fields.Add("fldreportquanti", db.Float)
    hTable.Fields.Add("fldreport", db.String)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_flditemid", ["flditemid"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatplanning($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatplanning") Then
    hTable = $con.Tables.Add("tblpatplanning")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldplancategory", db.String, 150)
    hTable.Fields.Add("fldproblem", db.String, 250)
    hTable.Fields.Add("fldsubjective", db.String)
    hTable.Fields.Add("fldobjective", db.String)
    hTable.Fields.Add("fldassess", db.String)
    hTable.Fields.Add("fldplan", db.String)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpattiming($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpattiming") Then
    hTable = $con.Tables.Add("tblpattiming")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtype", db.String, 250)
    hTable.Fields.Add("flditem", db.String, 250)

    hTable.Fields.Add("fldfirstreport", db.String, 250)
    hTable.Fields.Add("fldfirstuserid", db.String, 25)
    hTable.Fields.Add("fldfirsttime", db.Date)
    hTable.Fields.Add("fldfirstcomp", db.String, 50)
    hTable.Fields.Add("fldfirstsave", db.Boolean)

    hTable.Fields.Add("fldsecondreport", db.String, 250)
    hTable.Fields.Add("fldseconduserid", db.String, 25)
    hTable.Fields.Add("fldsecondtime", db.Date)
    hTable.Fields.Add("fldsecondcomp", db.String, 50)
    hTable.Fields.Add("fldsecondsave", db.Boolean)

    hTable.Fields.Add("fldcomment", db.String, 255)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldfirsttime", ["fldfirsttime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblconsult($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblconsult") Then
    hTable = $con.Tables.Add("tblconsult")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldconsultname", db.String, 250)
    hTable.Fields.Add("fldconsulttime", db.Date)
    hTable.Fields.Add("fldcomment", db.String, 255)
    hTable.Fields.Add("fldstatus", db.String, 25)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldbillingmode", db.String, 150)
    hTable.Fields.Add("fldorduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldconsulttime", ["fldconsulttime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblconfinement($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblconfinement") Then
    hTable = $con.Tables.Add("tblconfinement")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("flddeltime", db.Date)
    hTable.Fields.Add("flddeltype", db.String, 250)
    hTable.Fields.Add("flddelresult", db.String, 250)
    hTable.Fields.Add("flddelphysician", db.String, 25)
    hTable.Fields.Add("flddelnurse", db.String, 250)
    hTable.Fields.Add("fldcomplication", db.String, 250)
    hTable.Fields.Add("fldbloodloss", db.Float)
    hTable.Fields.Add("flddelwt", db.Float)
    hTable.Fields.Add("fldbabypatno", db.String, 150)
    hTable.Fields.Add("fldcomment", db.String)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_flddeltime", ["flddeltime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatradiotest($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatradiotest") Then
    hTable = $con.Tables.Add("tblpatradiotest")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtestid", db.String, 250)
    hTable.Fields.Add("fldmethod", db.String, 250)
    hTable.Fields.Add("fldgroupid", db.Long)
    hTable.Fields.Add("fldsampletype", db.String, 250)
    hTable.Fields.Add("fldreportquali", db.String)
    hTable.Fields.Add("fldreportquanti", db.Float)
    hTable.Fields.Add("fldfilepath", db.String, 250)
    hTable.Fields.Add("fldstatus", db.String, 250)
    hTable.Fields.Add("fldprint", db.Boolean)
    hTable.Fields.Add("fldabnormal", db.Boolean)
    hTable.Fields.Add("fldrefername", db.String, 250)
    hTable.Fields.Add("fldcondition", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 255)
    hTable.Fields.Add("flvisible", db.String, 50)
    hTable.Fields.Add("fldnewdate", db.Date)
    hTable.Fields.Add("fldpacstudy", db.String, 255)

    hTable.Fields.Add("fldtest_type", db.String, 50)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldchk", db.Boolean)
    hTable.Fields.Add("fldorder", db.Integer)

    hTable.Fields.Add("flduserid_report", db.String, 25)
    hTable.Fields.Add("fldtime_report", db.Date)
    hTable.Fields.Add("fldcomp_report", db.String, 50)
    hTable.Fields.Add("fldsave_report", db.Boolean)
    hTable.Fields.Add("flduptime_report", db.Date)

    hTable.Fields.Add("flduserid_verify", db.String, 25)
    hTable.Fields.Add("fldtime_verify", db.Date)
    hTable.Fields.Add("fldcomp_verify", db.String, 50)
    hTable.Fields.Add("fldsave_verify", db.Boolean)
    hTable.Fields.Add("flduptime_verify", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime_report", ["fldtime_report"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatradiosubtest($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatradiosubtest") Then
    hTable = $con.Tables.Add("tblpatradiosubtest")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtestid", db.Long)
    hTable.Fields.Add("fldsubtest", db.String, 200)
    hTable.Fields.Add("fldtanswertype", db.String, 50)
    hTable.Fields.Add("fldreport", db.String)
    hTable.Fields.Add("fldabnormal", db.Boolean)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldchk", db.Boolean)
    hTable.Fields.Add("fldorder", db.Integer)
    hTable.Fields.Add("fldfilepath", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldtestid", ["fldtestid"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatradiosubtable($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatradiosubtable") Then
    hTable = $con.Tables.Add("tblpatradiosubtable")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldexamid", db.Long)
    hTable.Fields.Add("fldsubexamid", db.Long)
    hTable.Fields.Add("fldtype", db.String, 150)
    hTable.Fields.Add("fldvariable", db.String, 200)
    hTable.Fields.Add("fldvalue", db.String, 250)
    hTable.Fields.Add("fldcolm2", db.String, 250)
    hTable.Fields.Add("fldcolm3", db.String, 250)
    hTable.Fields.Add("fldcolm4", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldsubexamid", ["fldsubexamid"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblmonitor($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblmonitor") Then
    hTable = $con.Tables.Add("tblmonitor")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldcategory", db.String, 25)
    hTable.Fields.Add("flditem", db.String, 250)
    hTable.Fields.Add("fldevery", db.Integer)
    hTable.Fields.Add("fldunit", db.String, 25)
    hTable.Fields.Add("fldtype", db.String, 150)
    hTable.Fields.Add("fldstatus", db.String, 25)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblextradosing($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblextradosing") Then
    hTable = $con.Tables.Add("tblextradosing")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldcategory", db.String, 25)
    hTable.Fields.Add("flditem", db.String, 250)
    hTable.Fields.Add("flddose", db.Float)
    hTable.Fields.Add("fldfreq", db.String, 25)
    hTable.Fields.Add("fldtype", db.String, 150)
    hTable.Fields.Add("flddosetime", db.Date)
    hTable.Fields.Add("flddosecode", db.String, 250)
    hTable.Fields.Add("fldstatus", db.String, 25)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblusercollection($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblusercollection") Then
    hTable = $con.Tables.Add("tblusercollection")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcashier", db.String, 150)
    hTable.Fields.Add("fldfrominvoice", db.String, 250)
    hTable.Fields.Add("fldtoinvoice", db.String, 250)
    hTable.Fields.Add("fldbillamt", db.Float)
    hTable.Fields.Add("fldretinvoice", db.String, 250)
    hTable.Fields.Add("fldretamt", db.Float)
    hTable.Fields.Add("fldrecvamt", db.Float)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldcashier", ["fldcashier"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatcharity($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatcharity") Then
    hTable = $con.Tables.Add("tblpatcharity")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldcharitytype", db.String, 150)
    hTable.Fields.Add("fldcharityamt", db.Float)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblextrareceipt($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblextrareceipt") Then
    hTable = $con.Tables.Add("tblextrareceipt")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpayername", db.String, 250)
    hTable.Fields.Add("fldpayeradd", db.String, 250)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("fldpayamount", db.Float)
    hTable.Fields.Add("fldpaytype", db.String, 50)
    hTable.Fields.Add("fldchequeno", db.String, 250)
    hTable.Fields.Add("fldbankname", db.String, 250)
    hTable.Fields.Add("fldusername", db.String, 250)
    hTable.Fields.Add("flduserpost", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldreference", ["fldreference"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblfiscal($con As Connection) '''required by IRD

  Dim hTable As Table

  If Not $con.Tables.Exist("tblfiscal") Then
    hTable = $con.Tables.Add("tblfiscal")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldfiscal", db.String, 250)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldpatname", db.String, 250)
    hTable.Fields.Add("fldpan", db.String, 250)
    hTable.Fields.Add("flddate", db.Date)
    hTable.Fields.Add("flditemamt", db.Float)
    hTable.Fields.Add("flddiscountamt", db.Float)
    hTable.Fields.Add("fldtaxable", db.Float)
    hTable.Fields.Add("fldtaxamt", db.Float)
    hTable.Fields.Add("fldtotamt", db.Float)
    hTable.Fields.Add("fldsync", db.String, 50)
    hTable.Fields.Add("fldprinted", db.String, 50)
    hTable.Fields.Add("fldactive", db.String, 50)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldpunch", db.String, 250)
    hTable.Fields.Add("fldprint", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatbilling($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatbilling") Then
    hTable = $con.Tables.Add("tblpatbilling")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldbillingmode", db.String, 50)
    hTable.Fields.Add("flditemtype", db.String, 150)
    hTable.Fields.Add("flditemno", db.Long)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flditemrate", db.Float)
    hTable.Fields.Add("flditemqty", db.Float)
    hTable.Fields.Add("fldtaxper", db.Float)
    hTable.Fields.Add("flddiscper", db.Float)
    hTable.Fields.Add("fldtaxamt", db.Float)
    hTable.Fields.Add("flddiscamt", db.Float)
    hTable.Fields.Add("fldditemamt", db.Float)
    hTable.Fields.Add("fldorduserid", db.String, 25)
    hTable.Fields.Add("fldordtime", db.Date)
    hTable.Fields.Add("fldordcomp", db.String, 50)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldbillno", db.String, 250) ''multiple same bill no
    hTable.Fields.Add("fldparent", db.Long)
    hTable.Fields.Add("fldprint", db.Boolean)
    hTable.Fields.Add("fldstatus", db.String, 25)
    hTable.Fields.Add("fldalert", db.Boolean)
    hTable.Fields.Add("fldtarget", db.String, 50)
    hTable.Fields.Add("fldpayto", db.String, 25)
    hTable.Fields.Add("fldrefer", db.String, 25)
    hTable.Fields.Add("fldreason", db.String, 250)
    hTable.Fields.Add("fldretbill", db.String, 250)
    hTable.Fields.Add("fldretqty", db.Float)
    hTable.Fields.Add("fldsample", db.String, 50)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], False)
    hTable.Indexes.Add(hTable.Name & "_fldretbill", ["fldretbill"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatbilldetail($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatbilldetail") Then
    hTable = $con.Tables.Add("tblpatbilldetail")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldprevdeposit", db.Float)
    hTable.Fields.Add("flditemamt", db.Float)
    hTable.Fields.Add("fldtaxamt", db.Float)
    hTable.Fields.Add("fldtaxgroup", db.String, 150)
    hTable.Fields.Add("flddiscountamt", db.Float)
    hTable.Fields.Add("flddiscountgroup", db.String, 150)
    hTable.Fields.Add("fldchargedamt", db.Float)
    hTable.Fields.Add("fldreceivedamt", db.Float)
    hTable.Fields.Add("fldcurdeposit", db.Float)
    hTable.Fields.Add("fldbilltype", db.String, 25)
    hTable.Fields.Add("fldchequeno", db.String, 250)
    hTable.Fields.Add("fldbankname", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldbillno", ["fldbillno"], True)
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatusershare($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatusershare") Then
    hTable = $con.Tables.Add("tblpatusershare")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldbillid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtotper", db.Float)
    hTable.Fields.Add("flduserper", db.Float)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatbillcount($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatbillcount") Then
    hTable = $con.Tables.Add("tblpatbillcount")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldcount", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatmeditem($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatmeditem") Then
    hTable = $con.Tables.Add("tblpatmeditem")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldcode", db.String, 150)
    hTable.Fields.Add("flditem", db.String, 255)
    hTable.Fields.Add("fldpatinfo", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 150)

    hTable.Fields.Add("flduserid_order", db.String, 25)
    hTable.Fields.Add("fldtime_order", db.Date)
    hTable.Fields.Add("fldcomp_order", db.String, 50)
    hTable.Fields.Add("fldsave_order", db.Boolean)
    hTable.Fields.Add("fldorder", db.String, 50)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldstatus", db.String, 50)

    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbldrugproblems($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbldrugproblems") Then
    hTable = $con.Tables.Add("tbldrugproblems")
    hTable.Fields.Add("flid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldcategory", db.String, 100)
    hTable.Fields.Add("fldmedicine", db.String, 250)
    hTable.Fields.Add("fldcondition", db.String, 250)
    hTable.Fields.Add("fldrecommend", db.String, 250)
    hTable.Fields.Add("fldlevel", db.String, 50)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.PrimaryKey = ["flid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatdosing($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatdosing") Then
    hTable = $con.Tables.Add("tblpatdosing")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("flditemtype", db.String, 150)
    hTable.Fields.Add("fldroute", db.String, 150)
    hTable.Fields.Add("flditem", db.String, 255)
    hTable.Fields.Add("flddose", db.Float)
    hTable.Fields.Add("fldfreq", db.String, 25)
    hTable.Fields.Add("flddays", db.Float)
    hTable.Fields.Add("fldqtydisp", db.Float)
    hTable.Fields.Add("fldqtyret", db.Float)
    hTable.Fields.Add("fldprescriber", db.String, 255)
    hTable.Fields.Add("fldregno", db.String, 255)
    hTable.Fields.Add("fldlevel", db.String, 50)

    hTable.Fields.Add("flddispmode", db.String, 150)
    hTable.Fields.Add("fldorder", db.String, 50)
    hTable.Fields.Add("fldcurval", db.String, 50)
    hTable.Fields.Add("fldstarttime", db.Date)
    hTable.Fields.Add("fldendtime", db.Date)
    hTable.Fields.Add("fldtaxper", db.Float)
    hTable.Fields.Add("flddiscper", db.Float)

    hTable.Fields.Add("flduserid_order", db.String, 25)
    hTable.Fields.Add("fldtime_order", db.Date)
    hTable.Fields.Add("fldcomp_order", db.String, 50)
    hTable.Fields.Add("fldsave_order", db.Boolean)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)

    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldlabel", db.Boolean)
    hTable.Fields.Add("fldstatus", db.String, 50)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtbltaperdose($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tbltaperdose") Then
    hTable = $con.Tables.Add("tbltaperdose")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flddoseno", db.Long)
    hTable.Fields.Add("flddose", db.Float)
    hTable.Fields.Add("fldfreq", db.String, 25)
    hTable.Fields.Add("flddays", db.Float)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_flddoseno", ["flddoseno"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblnurdosing($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblnurdosing") Then
    hTable = $con.Tables.Add("tblnurdosing")
    hTable.Fields.Add("fldid", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("flddoseno", db.Long)
    hTable.Fields.Add("fldvalue", db.Float)
    hTable.Fields.Add("fldunit", db.String, 150)
    hTable.Fields.Add("fldfromtime", db.Date)
    hTable.Fields.Add("fldtotime", db.Date)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblvaccdosing($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblvaccdosing") Then
    hTable = $con.Tables.Add("tblvaccdosing")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("flditem", db.String, 250)
    hTable.Fields.Add("fldtype", db.String, 100)
    hTable.Fields.Add("fldvalue", db.Float)
    hTable.Fields.Add("fldunit", db.String, 150)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpersonimage($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpersonimage") Then
    hTable = $con.Tables.Add("tblpersonimage")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcateg", db.String, 250)
    hTable.Fields.Add("fldname", db.String, 250)
    hTable.Fields.Add("fldpic", db.Blob)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatimagedata($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatimagedata") Then
    hTable = $con.Tables.Add("tblpatimagedata")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldcateg", db.String, 250)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtitle", db.String, 250)
    hTable.Fields.Add("fldpic", db.Blob)
    hTable.Fields.Add("fldkeyword", db.String, 250)
    hTable.Fields.Add("flddetail", db.String, 250)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatientimage($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientimage") Then
    hTable = $con.Tables.Add("tblpatientimage")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtestid", db.Long)
    hTable.Fields.Add("fldpic", db.Blob)
    hTable.Fields.Add("fldtitle", db.String, 250)
    hTable.Fields.Add("fldkeyword", db.String, 250)
    hTable.Fields.Add("flddetail", db.String, 250)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatientdicom($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientdicom") Then
    hTable = $con.Tables.Add("tblpatientdicom")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldtestid", db.Long)
    hTable.Fields.Add("fldpic", db.Blob)
    hTable.Fields.Add("fldtitle", db.String, 250)
    hTable.Fields.Add("fldkeyword", db.String, 250)
    hTable.Fields.Add("flddetail", db.String, 250)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatreport($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatreport") Then
    hTable = $con.Tables.Add("tblpatreport")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldcateg", db.String, 250)
    hTable.Fields.Add("fldtitle", db.String, 250)
    hTable.Fields.Add("flddetail", db.String, 250)
    hTable.Fields.Add("fldpic", db.Blob)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblofficedocs($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblofficedocs") Then
    hTable = $con.Tables.Add("tblofficedocs")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldreference", db.Long)
    hTable.Fields.Add("fldcateg", db.String, 250)
    hTable.Fields.Add("fldtitle", db.String, 250)
    hTable.Fields.Add("flddetail", db.String, 250)
    hTable.Fields.Add("fldextension", db.String, 10)
    hTable.Fields.Add("fldpic", db.Blob)
    hTable.Fields.Add("fldlink", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatientstudy($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientstudy") Then
    hTable = $con.Tables.Add("tblpatientstudy")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatcode", db.String, 250)
    hTable.Fields.Add("fldstudycode", db.String, 150)
    hTable.Fields.Add("fldconsentautodata", db.String, 50)
    hTable.Fields.Add("fldstatusautodata", db.String, 50)
    hTable.Fields.Add("fldconsentinterview", db.String, 50)
    hTable.Fields.Add("fldstatusinterview", db.String, 50)
    hTable.Fields.Add("fldconsentformpic", db.Blob)
    hTable.Fields.Add("fldconsentformlink", db.String, 250)
    hTable.Fields.Add("fldiintervireformpic", db.Blob)
    hTable.Fields.Add("fldinterviewformlink", db.String, 250)
    hTable.Fields.Add("fldstatus", db.String, 50)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

''----------------------------- For Blood/Other Products ---------------------------------------
Public Sub CREATEtblblood($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblblood") Then
    hTable = $con.Tables.Add("tblblood")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblbloodstore($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblbloodstore") Then
    hTable = $con.Tables.Add("tblbloodstore")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.Fields.Add("fldtemp", db.String, 150)
    hTable.Fields.Add("fldshelf", db.Integer)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblvaccine($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblvaccine") Then
    hTable = $con.Tables.Add("tblvaccine")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("flditem", db.String, 150)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

'
''
'''

''NOTE: ------------------------------------------- for trigger ----------------------------------
Public Sub CREATEtblpatbilling_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatbilling_log") Then
    hTable = $con.Tables.Add("tblpatbilling_log")
    hTable.Fields.Add("fldsno", db.Serial)
    hTable.Fields.Add("fldid", db.Long)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldbillingmode", db.String, 50)
    hTable.Fields.Add("flditemtype", db.String, 150)
    hTable.Fields.Add("flditemno", db.Long)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("flditemrate", db.Float)
    hTable.Fields.Add("flditemqty", db.Float)
    hTable.Fields.Add("fldtaxper", db.Float)
    hTable.Fields.Add("flddiscper", db.Float)
    hTable.Fields.Add("fldtaxamt", db.Float)
    hTable.Fields.Add("flddiscamt", db.Float)
    hTable.Fields.Add("fldditemamt", db.Float)
    hTable.Fields.Add("fldorduserid", db.String, 25)
    hTable.Fields.Add("fldordtime", db.Date)
    hTable.Fields.Add("fldordcomp", db.String, 50)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldbillno", db.String, 250) ''multiple same bill no
    hTable.Fields.Add("fldparent", db.Long)
    hTable.Fields.Add("fldprint", db.Boolean)
    hTable.Fields.Add("fldstatus", db.String, 25)
    hTable.Fields.Add("fldalert", db.Boolean)
    hTable.Fields.Add("fldtarget", db.String, 50)
    hTable.Fields.Add("fldpayto", db.String, 25)
    hTable.Fields.Add("fldrefer", db.String, 25)
    hTable.Fields.Add("fldreason", db.String, 250)
    hTable.Fields.Add("fldretbill", db.String, 250)
    hTable.Fields.Add("fldretqty", db.Float)
    hTable.Fields.Add("fldsample", db.String, 50)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatbilldetail_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatbilldetail_log") Then
    hTable = $con.Tables.Add("tblpatbilldetail_log")
    hTable.Fields.Add("fldsno", db.Serial)
    hTable.Fields.Add("fldid", db.Long)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldprevdeposit", db.Float)
    hTable.Fields.Add("flditemamt", db.Float)
    hTable.Fields.Add("fldtaxamt", db.Float)
    hTable.Fields.Add("fldtaxgroup", db.String, 150)
    hTable.Fields.Add("flddiscountamt", db.Float)
    hTable.Fields.Add("flddiscountgroup", db.String, 150)
    hTable.Fields.Add("fldchargedamt", db.Float)
    hTable.Fields.Add("fldreceivedamt", db.Float)
    hTable.Fields.Add("fldcurdeposit", db.Float)
    hTable.Fields.Add("fldbilltype", db.String, 25)
    hTable.Fields.Add("fldchequeno", db.String, 250)
    hTable.Fields.Add("fldbankname", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldhostmac", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpurchase_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpurchase_log") Then
    hTable = $con.Tables.Add("tblpurchase_log")
    hTable.Fields.Add("fldsno", db.Serial)
    hTable.Fields.Add("fldid", db.Long)
    hTable.Fields.Add("fldpurtype", db.String, 25)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldmrp", db.Float)
    hTable.Fields.Add("flsuppcost", db.Float)
    hTable.Fields.Add("fldcasdisc", db.Float)
    hTable.Fields.Add("fldcasbonus", db.Float)
    hTable.Fields.Add("fldqtybonus", db.Float)
    hTable.Fields.Add("fldcarcost", db.Float)
    hTable.Fields.Add("fldnetcost", db.Float)
    hTable.Fields.Add("fldmargin", db.Float)
    hTable.Fields.Add("fldsellprice", db.Float)
    hTable.Fields.Add("fldtotalqty", db.Float)
    hTable.Fields.Add("fldreturnqty", db.Float)
    hTable.Fields.Add("fldtotalcost", db.Float)
    hTable.Fields.Add("fldpurdate", db.Date)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsav", db.Boolean)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("fldchk", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpurchasebill_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpurchasebill_log") Then
    hTable = $con.Tables.Add("tblpurchasebill_log")
    hTable.Fields.Add("fldsno", db.Serial)
    hTable.Fields.Add("fldid", db.Long)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldpurtype", db.String, 25)
    hTable.Fields.Add("fldbillno", db.String, 250)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("flddebit", db.Float)
    hTable.Fields.Add("fldcredit", db.Float)
    hTable.Fields.Add("fldtotaltax", db.Float)
    hTable.Fields.Add("fldlastdisc", db.Float)
    hTable.Fields.Add("fldpurdate", db.Date)
    hTable.Fields.Add("flduser", db.String, 25)
    hTable.Fields.Add("fldsav", db.Boolean)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblbulksale_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblbulksale_log") Then
    hTable = $con.Tables.Add("tblbulksale_log")
    hTable.Fields.Add("fldsno", db.Serial)
    hTable.Fields.Add("fldid", db.Long)
    hTable.Fields.Add("fldtarget", db.String, 250)
    hTable.Fields.Add("fldbulktime", db.Date)
    hTable.Fields.Add("fldcategory", db.String, 150)
    hTable.Fields.Add("fldstockno", db.Long)
    hTable.Fields.Add("fldstockid", db.String, 250)
    hTable.Fields.Add("fldnetcost", db.Float)
    hTable.Fields.Add("fldqtydisp", db.Float)
    hTable.Fields.Add("fldqtyret", db.Float)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblextrareceipt_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblextrareceipt_log") Then
    hTable = $con.Tables.Add("tblextrareceipt_log")
    hTable.Fields.Add("fldsno", db.Serial)
    hTable.Fields.Add("fldid", db.Long)
    hTable.Fields.Add("fldpayername", db.String, 250)
    hTable.Fields.Add("fldpayeradd", db.String, 250)
    hTable.Fields.Add("fldreference", db.String, 250)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("fldpayamount", db.Float)
    hTable.Fields.Add("fldpaytype", db.String, 50)
    hTable.Fields.Add("fldchequeno", db.String, 250)
    hTable.Fields.Add("fldbankname", db.String, 250)
    hTable.Fields.Add("fldusername", db.String, 250)
    hTable.Fields.Add("flduserpost", db.String, 250)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
    hTable.Update
  Endif

End

Public Sub CREATEtblservicecost_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblservicecost_log") Then
    hTable = $con.Tables.Add("tblservicecost_log")
    hTable.Fields.Add("fldsno", db.Serial)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("fldbillitem", db.String, 200)
    hTable.Fields.Add("flditemtype", db.String, 200)
    hTable.Fields.Add("flditemcost", db.Float)
    hTable.Fields.Add("flditemunit", db.String, 50)
    hTable.Fields.Add("fldcode", db.String, 50)
    hTable.Fields.Add("fldgroup", db.String, 50)
    hTable.Fields.Add("fldreport", db.String, 200)
    hTable.Fields.Add("fldstatus", db.String, 50)
    hTable.Fields.Add("fldtarget", db.String, 50)
    hTable.Fields.Add("fldtaxcode", db.String, 150)
    hTable.Fields.Add("fldeditrate", db.Boolean)
    hTable.Fields.Add("fldeditdisc", db.Boolean)
    hTable.Fields.Add("fldid", db.Integer)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblpatientinfo_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblpatientinfo_log") Then
    hTable = $con.Tables.Add("tblpatientinfo_log")
    hTable.Fields.Add("fldsno", db.Serial)
    '     hTable.Fields.Add("fldpatientno", db.Long)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldptnamefir", db.String, 150)
    hTable.Fields.Add("fldptnamelast", db.String, 150)
    hTable.Fields.Add("fldethniccode", db.String, 250)
    hTable.Fields.Add("fldptsex", db.String, 10)
    hTable.Fields.Add("fldptaddvill", db.String, 150)
    hTable.Fields.Add("fldptadddist", db.String, 150)
    hTable.Fields.Add("fldptcontact", db.String, 150)
    hTable.Fields.Add("fldptguardian", db.String, 250)
    hTable.Fields.Add("fldrelation", db.String, 250)
    hTable.Fields.Add("fldptbirday", db.Date)
    hTable.Fields.Add("fldptadmindate", db.Date)
    hTable.Fields.Add("fldemail", db.String, 250)
    hTable.Fields.Add("fldptcode", db.String, 250)
    hTable.Fields.Add("flddiscount", db.String, 150)
    hTable.Fields.Add("fldadmitfile", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldencrypt", db.Boolean)
    hTable.Fields.Add("fldpassword", db.String, 250)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldupuser", db.String, 25)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblencounter_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblencounter_log") Then
    hTable = $con.Tables.Add("tblencounter_log")
    hTable.Fields.Add("fldsno", db.Serial)
    '     hTable.Fields.Add("fldencounterid", db.Long)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    '     hTable.Fields.Add("fldpatientval", db.Long)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldadmitlocat", db.String, 100)
    hTable.Fields.Add("fldcurrlocat", db.String, 100)
    hTable.Fields.Add("flddoa", db.Date)
    hTable.Fields.Add("flddod", db.Date)
    hTable.Fields.Add("fldheight", db.String, 10)
    hTable.Fields.Add("fldcashdeposit", db.Float)
    hTable.Fields.Add("flddisctype", db.String, 150)
    hTable.Fields.Add("fldcashcredit", db.Float)
    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldadmission", db.String, 25)
    hTable.Fields.Add("fldfollowdate", db.Date)
    hTable.Fields.Add("fldreferto", db.String, 250)
    hTable.Fields.Add("fldregdate", db.Date)
    '     hTable.Fields.Add("fldadmitfile", db.Float) ''not used anywhere
    hTable.Fields.Add("fldcharity", db.Float)
    hTable.Fields.Add("fldbillingmode", db.String, 50)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldvisit", db.String, 50)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblassetsentry_log($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblassetsentry_log") Then
    hTable = $con.Tables.Add("tblassetsentry_log")
    hTable.Fields.Add("fldsno", db.Serial)
    hTable.Fields.Add("fldid", db.Long)
    hTable.Fields.Add("flditemname", db.String, 250)
    hTable.Fields.Add("fldgroup", db.String, 250)
    hTable.Fields.Add("fldspecs", db.String, 250)
    hTable.Fields.Add("fldcode", db.String, 250)
    hTable.Fields.Add("fldmanufacturer", db.String, 250)
    hTable.Fields.Add("fldmodel", db.String, 250)
    hTable.Fields.Add("fldserial", db.String, 250)

    hTable.Fields.Add("fldledger", db.String, 250)
    hTable.Fields.Add("fldsuppname", db.String, 250)
    hTable.Fields.Add("fldpurdate", db.Date)
    hTable.Fields.Add("fldqty", db.Integer)
    hTable.Fields.Add("fldunit", db.String, 50)
    hTable.Fields.Add("flditemrate", db.Float)
    hTable.Fields.Add("fldtaxamt", db.Float)
    hTable.Fields.Add("flddiscamt", db.Float)
    hTable.Fields.Add("fldditemamt", db.Float)
    hTable.Fields.Add("fldcomp", db.String, 50)
    hTable.Fields.Add("fldcondition", db.String, 250)
    hTable.Fields.Add("fldcomment", db.String, 250)
    hTable.Fields.Add("fldrepairdate", db.Date)
    hTable.Fields.Add("flduser", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)

    hTable.Fields.Add("fldcurrtime", db.Date)
    hTable.PrimaryKey = ["fldsno"]
    hTable.Update
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End
