' Gambas module file

Public Sub CreateSQliteDB(sPath As String)

  Dim qlit As Connection
  Dim dbname As String

  dbname = File.Name(sPath)
  qlit = modDatabase.OpenConnection("sqlite3", File.Dir(sPath), "", "", "")
  If qlit.Opened = True Then
    If Not qlit.Databases.Exist(dbname) Then
      qlit.Databases.Add(dbname)
    Endif
    qlit.Close()
  Endif

End

'NOTE: ---------------------------------Sqlite functions ---------------------------------
Public Sub ExportGridToSqlite(GridView1 As GridView)

  Dim $qlitConn As Connection
  Dim sFile As String
  Dim hTable As Table
  Dim Row As Integer
  Dim Column As Integer
  Dim res As Result

  Inc Application.Busy
  sFile = User.Home & "/selected"
  If Exist(sFile) Then Kill sFile
  CreateSQliteDB(sFile)
  $qlitConn = modDatabase.OpenConnection("sqlite3", File.Dir(sFile), File.Name(sFile), "", "")
  If Not $qlitConn.Tables.Exist("tblselected") Then
    hTable = $qlitConn.Tables.Add("tblselected")
    hTable.Fields.Add("_id", db.Serial)
    For Column = 0 To GridView1.Columns.Count - 1
      If GridView1.Columns[Column].Text Then
        hTable.Fields.Add(GridView1.Columns[Column].Text, db.String, 250)
      Else
        hTable.Fields.Add("Column" & CStr(column), db.String, 250)
      Endif
    Next
    hTable.PrimaryKey = ["_id"]
    hTable.Update
  Endif

  For Row = 0 To GridView1.Rows.Count - 1
    res = $qlitConn.Create("tblselected")
    For Column = 0 To GridView1.Columns.Count - 1
      If GridView1.Columns[Column].Text Then
        res[GridView1.Columns[Column].Text] = GridView1[Row, Column].Text
      Else
        res["Column" & CStr(column)] = GridView1[Row, Column].Text
      Endif
    Next
    res.Update
    res.Delete
  Next
  Dec Application.Busy
  Message.Info(("Data exported to ") & sFile, ("OK"))

End
