' Gambas module file

Public $LocalDateData As Collection

'NOTE: ---------------------------------- Start and End Time --------------------------------
'----------Day
Public Function StartSqlDate(dt As Date) As Date

  Dim xx As Date

  xx = Date(Year(dt), Month(dt), Day(dt), 0, 0, 0, 0)
  Return xx

End

Public Function EndSqlDate(dt As Date) As Date

  Dim xx As Date
  Dim yy As Date

  xx = DateAdd(StartSqlDate(dt), gb.day, 1)
  yy = DateAdd(xx, gb.Millisecond, -1)
  Return yy

End

'----------------Hour
Public Function StartSqlHour(dt As Date) As Date

  Dim xx As Date

  xx = Date(Year(dt), Month(dt), Day(dt), Hour(dt), 0, 0, 0)
  Return xx

End

Public Function EndSqlHour(dt As Date) As Date

  Dim xx As Date
  Dim yy As Date

  xx = DateAdd(StartSqlHour(dt), gb.Hour, 1)
  yy = DateAdd(xx, gb.Millisecond, -1)
  Return yy

End

'----------------------minute
Public Function StartSqlMinute(dt As Date) As Date

  Dim xx As Date

  xx = Date(Year(dt), Month(dt), Day(dt), Hour(dt), Minute(dt), 0, 0)
  Return xx

End

Public Function EndSqlMinute(dt As Date) As Date

  Dim xx As Date
  Dim yy As Date

  xx = DateAdd(StartSqlMinute(dt), gb.Minute, 1)
  yy = DateAdd(xx, gb.Millisecond, -1)
  Return yy

End

'------------------------------------ year
Public Function StartSqlYear(dt As Date) As Date

  Dim xx As Date

  xx = Date(Year(dt), 1, 1, 0, 0, 0, 0)
  Return xx

End

Public Function EndSqlYear(dt As Date) As Date

  Dim xx As Date
  Dim yy As Date

  xx = DateAdd(StartSqlYear(dt), gb.Year, 1)
  yy = DateAdd(xx, gb.Millisecond, -1)
  Return yy

End

'---------------------------- month
Public Function StartSqlMonth(dt As Date) As Date

  Dim xx As Date

  xx = Date(Year(dt), Month(dt), 1, 0, 0, 0, 0)
  Return xx

End

Public Function EndSqlMonth(dt As Date) As Date

  Dim xx As Date
  Dim yy As Date

  xx = DateAdd(StartSqlMonth(dt), gb.Month, 1)
  yy = DateAdd(xx, gb.Millisecond, -1)
  Return yy

End
'
''
'''
''''

Public Function ConvertToLocaldate(dt As Date) As String

  Dim res As Result
  Dim xdate As Date
  Dim xx As String

  xdate = Date(dt)
  xx = modHelpVariable.GetCollectionValue($LocalDateData, Format(xdate, gb.ShortDate))
  If Not xx Then
    res = modDatabase.$calConn.Exec("select BS_DATE from tblbsdate where AD_DATE=&1", xdate)
    If res.Available = True Then
      If res!BS_DATE Then
        xx = res!BS_DATE
        If modBasic.$LocalCache = "Yes" Then
          $LocalDateData.Add(xx, Format(xdate, gb.ShortDate))
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function ConvertToEnglishdate(dt As String) As Date

  Dim res As Result
  Dim xx As Date

  res = modDatabase.$calConn.Exec("select AD_DATE from tblbsdate where BS_DATE=&1", dt)
  If res.Available = True Then
    If res!AD_DATE Then
      xx = res!AD_DATE
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetNepaliFiscalYear(sDate As Date) As String

  Dim xnepdate As String
  Dim asx As String[]
  Dim xval As String

  xnepdate = ConvertToLocaldate(Date(sDate))
  asx = Split(xnepdate, "/")
  Select asx[1]
    Case "04", "05", "06", "07", "08", "09", "10", "11", "12"
      xval = asx[0] & "/" & CStr(CInt(asx[0]) + 1)
    Case "01", "02", "03"
      xval = CStr(CInt(asx[0]) - 1) & "/" & asx[0]
  End Select
  Return xval

End

Public Function GetNepaliFiscalYarStart(curDate As Date) As Date

  Dim sFiscal As String
  Dim asx As String[]
  Dim xdate As String
  Dim sDate As Date

  sFiscal = GetNepaliFiscalYear(curDate)
  asx = Split(sFiscal, "/")
  xdate = asx[0] & "/04/01"
  sDate = ConvertToEnglishdate(xdate)
  Return sDate

End

''formatting dates
Public Function ConvertLocalDateWithMonth(dt As Date) As String

  Dim xx As String
  Dim sAff As String[]
  Dim sVal As String
  Dim xdate As String

  xdate = ConvertToLocaldate(dt)
  If xdate Then
    sAff = Split(xdate, "/")
    If sAff[1] = "01" Then
      sVal = modBasic.LocalJan
    Else If sAff[1] = "02" Then
      sVal = modBasic.LocalFeb
    Else If sAff[1] = "03" Then
      sVal = modBasic.LocalMar
    Else If sAff[1] = "04" Then
      sVal = modBasic.LocalApr
    Else If sAff[1] = "05" Then
      sVal = modBasic.LocalMay
    Else If sAff[1] = "06" Then
      sVal = modBasic.LocalJun
    Else If sAff[1] = "07" Then
      sVal = modBasic.LocalJul
    Else If sAff[1] = "08" Then
      sVal = modBasic.LocalAug
    Else If sAff[1] = "09" Then
      sVal = modBasic.LocalSep
    Else If sAff[1] = "10" Then
      sVal = modBasic.LocalOct
    Else If sAff[1] = "11" Then
      sVal = modBasic.LocalNov
    Else If sAff[1] = "12" Then
      sVal = modBasic.LocalDec
    Endif
    xx = sAff[0] & Space(1) & sVal & Space(1) & sAff[2]

  Else
    xx = ""
  Endif
  Return xx

End

'##DATE FUNCTION##
Public Function GetDateOnlyInFormatForAll(strDate As Date, strFormat As String, sType As String) As String

  Dim xx As String

  If strFormat = "BS Date" Then
    If sType = "MediumDate" Then
      xx = ConvertLocalDateWithMonth(strDate)
    Else If sType = "ShortDate" Then
      xx = ConvertToLocaldate(strDate)
    Else If sType = "LongDate" Then
      xx = ConvertToLocaldate(strDate) & Space(1) & GetWeekDay(strDate)
    Else
      xx = ConvertToLocaldate(strDate)
    Endif

  Else If strFormat = "AD Date" Then
    If sType = "MediumDate" Then
      xx = Format(strDate, gb.MediumDate)
    Else If sType = "ShortDate" Then
      xx = Format(strDate, gb.ShortDate)
    Else If sType = "LongDate" Then
      xx = Format(strDate, gb.LongDate)
    Else
      xx = Format(strDate, gb.ShortDate)
    Endif

  Else
    If sType = "MediumDate" Then
      xx = Format(strDate, gb.MediumDate)
    Else If sType = "ShortDate" Then
      xx = Format(strDate, gb.ShortDate)
    Else If sType = "LongDate" Then
      xx = Format(strDate, gb.LongDate)
    Else
      xx = Format(strDate, gb.ShortDate)
    Endif

  Endif

  Return xx

End

'##DATE FUNCTION##
Public Function GetTimeOnlyForAll(strDate As Date, sType As String) As String

  Dim xx As String

  If sType = "MediumDate" Then
    xx = Format(strDate, gb.MediumTime)
  Else If sType = "ShortDate" Then
    xx = Format(strDate, gb.ShortTime)
  Else If sType = "LongDate" Then
    xx = Format(strDate, gb.LongTime)
  Else
    xx = Format(strDate, gb.ShortTime)
  Endif
  Return xx

End

Public Function GetDateTimeInFormatForAll(strDate As Date, strFormat As String, sType As String) As String

  Dim xx As String

  xx = GetDateOnlyInFormatForAll(strDate, strFormat, sType) & Space(1) & GetTimeOnlyForAll(strDate, sType)
  Return xx

End

Public Function GetMonthName(sdate As Date) As String

  Dim xx As String
  Dim monName As String[]

  monName = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
  xx = monName[Month(sdate) - 1]
  Return xx

End

Public Function GetWeekDay(sdate As Date) As String

  Dim xx As String
  Dim DayNames As String[]

  DayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
  xx = DayNames[WeekDay(sdate)]
  Return xx

End

Public Function GetDayCode(sDay As String) As Integer

  Dim xx As Integer

  If sDay = "Sunday" Then
    xx = gb.Sunday
  Else If sDay = "Monday" Then
    xx = gb.Monday
  Else If sDay = "Tuesday" Then
    xx = gb.Tuesday
  Else If sDay = "Wednesday" Then
    xx = gb.Wednesday
  Else If sDay = "Thursday" Then
    xx = gb.Thursday
  Else If sDay = "Friday" Then
    xx = gb.Friday
  Else If sDay = "Saturday" Then
    xx = gb.Saturday
  Endif

  Return xx

End

'
''
'''
''''

''
'''

Public Sub GetAgeControlFromDate(sDate As Date, txtval As ValueBox, cmbunit As ComboBox)

  Dim xdiff As Integer
  Dim xval As Float
  Dim xunit As String

  If sDate Then
    xdiff = DateDiff(sDate, Now(), gb.Minute)
    If xdiff < (60 * 24) Then
      xval = xdiff / 60
      xunit = "Hours"
    Else If xdiff >= (60 * 24) And If xdiff < 60 * 24 * 30 Then
      xval = xdiff / (60 * 24)
      xunit = "Days"
    Else If xdiff >= (60 * 24 * 30) And If xdiff < (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 30)
      xunit = "Months"
    Else If xdiff >= (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 365)
      xunit = "Years"
    Endif
    cmbunit.Text = xunit
    txtval.Value = Round(xval, -1)
  Else
    txtval.Value = 0
    cmbunit.Text = ""
  Endif

End

Public Function ConvertHoursToString(xHour As Float) As String

  Dim xval As Float
  Dim xunit As String
  Dim xx As String

  If xHour < 24 Then
    xval = xHour
    xunit = "Hours"
  Else If xHour >= 24 And If xHour < 24 * 30 Then
    xval = xHour / 24
    xunit = "Days"
  Else If xHour >= (24 * 30) And If xHour < (24 * 365) Then
    xval = xHour / (24 * 30)
    xunit = "Months"
  Else If xHour >= (24 * 365) Then
    xval = xHour / (24 * 365)
    xunit = "Years"
  Endif

  xx = CStr(Round(xval, -3)) & Space(1) & xunit
  Return xx

End

Public Function GetAgeString(dtfir As Date, dtnow As Date) As String

  Dim xdiff As Integer
  Dim xval As Float
  Dim txtyear As Float
  Dim txtmonth As Float
  Dim btnyear As String
  Dim btnmon As String
  Dim xage As String
  Dim xx As String

  If dtfir And If dtnow Then
    xdiff = DateDiff(dtfir, dtnow, gb.Minute)
    If xdiff < (60 * 24) Then
      xval = xdiff / 60
      txtyear = Fix(xval)
      txtmonth = Floor(Frac(xval) * 60)
      btnyear = "Hr"
      btnmon = "Min"
    Else If xdiff >= (60 * 24) And If xdiff < 60 * 24 * 30 Then
      xval = xdiff / (60 * 24)
      txtyear = Fix(xval)
      txtmonth = Floor(Frac(xval) * 24)
      btnyear = "Day"
      btnmon = "Hr"
    Else If xdiff >= (60 * 24 * 30) And If xdiff < (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 30)
      txtyear = Fix(xval)
      txtmonth = Floor(Frac(xval) * 30)
      btnyear = "Mon"
      btnmon = "Day"
    Else If xdiff >= (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 365)
      txtyear = Fix(xval)
      txtmonth = Floor(Frac(xval) * 12)
      btnyear = "Yr"
      btnmon = "Mon"
    Endif

    If modBasic.$PatAgeFormat = "YearMonth" Then
      If txtmonth > 0 Then
        xage = CStr(txtyear) & btnyear & Space(1) & CStr(txtmonth) & btnmon
      Else
        xage = CStr(txtyear) & btnyear
      Endif
    Else If modBasic.$PatAgeFormat = "AgeInYears" Then
      xage = CStr(Round(xdiff / (60 * 24 * 365), -3))
    Else
      xage = CStr(Round(xval, -1)) & btnyear
    Endif

    If modBasic.$NumFont Then
      xx = modString.GetLocalNumber(xage)
    Else
      xx = xage
    Endif
  Endif

  Return xx

End

Public Sub DateToYearandMonth(dob As Date, txtyear As ValueBox, txtmonth As ValueBox, btnyear As ToolButton, btnmon As ToolButton)

  Dim xdiff As Integer
  Dim xval As Float

  If dob Then
    xdiff = DateDiff(dob, Now(), gb.Minute)
    If xdiff < (60 * 24) Then
      xval = xdiff / 60
      txtyear.Value = 0
      txtmonth.Value = Round(xval, -1)
      btnyear.Text = "Day"
      btnmon.Text = "Hour"
    Else If xdiff >= (60 * 24) And If xdiff < 60 * 24 * 30 Then
      xval = xdiff / (60 * 24)
      txtyear.Value = Fix(xval)
      txtmonth.Value = Round(Frac(xval) * 24, -1)
      btnyear.Text = "Day"
      btnmon.Text = "Hour"
    Else If xdiff >= (60 * 24 * 30) And If xdiff < (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 30)
      txtyear.Value = Fix(xval)
      txtmonth.Value = Round(Frac(xval) * 30, -1)
      btnyear.Text = "Mon"
      btnmon.Text = "Day"
    Else If xdiff >= (60 * 24 * 365) Then
      xval = xdiff / (60 * 24 * 365)
      txtyear.Value = Fix(xval)
      txtmonth.Value = Round(Frac(xval) * 12, -1)
      btnyear.Text = "Year"
      btnmon.Text = "Mon"
    Endif
  Endif

End

Public Function GetYearDate(sYear As Integer) As Date

  Dim xx As Date

  xx = Date(sYear, 1, 1, 0, 0, 0, 0)
  Return xx

End

Public Function GetDateArrayBetween(dt1 As Date, dt2 As Date) As Date[]

  Dim xxx As Date[]
  Dim xdt As Date

  xxx = New Date[]
  xdt = dt1
  While xdt <= dt2
    xxx.Add(StartSqlDate(xdt))
    xdt = DateAdd(xdt, gb.Day, 1)
  Wend
  xxx.Sort()
  Return xxx

End

'
''
'''
''''

Private Function ConvertIntervalToString(xhour As Integer, xminute As Integer, xsecond As Integer) As String

  Dim shour As String
  Dim smin As String
  Dim ssec As String
  Dim xval As String

  If xhour Then
    shour = CStr(xhour)
  Else
    shour = "0"
  Endif

  If xminute Then
    If xminute >= 10 Then
      smin = CStr(xminute)
    Else
      smin = "0" & CStr(xminute)
    Endif
  Else
    smin = "00"
  Endif

  If xsecond Then
    If xsecond >= 10 Then
      ssec = CStr(xsecond)
    Else
      ssec = "0" & CStr(xsecond)
    Endif
  Else
    ssec = "00"
  Endif

  xval = shour & " : " & smin & " : " & ssec
  Return xval

End

Public Function GetSecondToTimeForm(xSecond As Integer) As String

  Dim xnewsec As Integer
  Dim xhour As Integer
  Dim xmin As Integer
  Dim xsec As Integer
  Dim xval As String

  If xSecond >= 3600 Then
    xhour = Fix(xSecond / 3600)
    xnewsec = xSecond - (xhour * 3600)
    If xnewsec >= 60 Then
      xmin = Fix(xnewsec / 60)
      xsec = xnewsec - (xmin * 60)
    Else
      xmin = 0
      xsec = xnewsec
    Endif

  Else If xSecond >= 60 Then
    xhour = 0
    xmin = Fix(xSecond / 60)
    xsec = xSecond - (xmin * 60)
  Else
    xhour = 0
    xmin = 0
    xsec = xSecond
  Endif

  xval = ConvertIntervalToString(xhour, xmin, xsec)
  Return xval

End

Public Function GetHoursValue(sUnit As String) As Integer

  Dim xval As Float

  If sUnit = "Hours" Then
    xval = 1
  Else If sUnit = "Days" Then
    xval = 24
  Else If sUnit = "Weeks" Then
    xval = 24 * 7
  Else If sUnit = "Months" Then
    xval = 24 * 30
  Else If sUnit = "Years" Then
    xval = 24 * 365
  Else
    xval = 0
  Endif
  Return xval

End
