' Gambas module file

Public $virtualQuery As String

''---------------------------- Speaking ----------------------------------
Public Sub SpeakString(sText As String)

  Dim arcmd As String[]
  Dim xcmd As String

  If System.Exist("espeak") Then
    xcmd = modSettings.ShowSettingFromFIle("TextToSpeech/CustomCommand")
    If xcmd Then
      modBasic.DebugString("Execute " & xcmd & Space(1) & sText)
      Shell xcmd & Space(1) & Quote(sText) Wait
    Else
      arcmd = ["espeak", Quote(sText)]
      modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
      Exec arcmd Wait
    Endif
  Endif

End

''NOTE: ------------------------- 7z compression with password -----------------------------
Public Sub Get7ZCompression(UnCompressedPath As String, sPassword As String, CompressedPath As String)

  Dim xcmd As String

  xcmd = "7z -mhc=on -mhe=on -p" & sPassword & " a " & CompressedPath & Space(1) & UnCompressedPath
  modBasic.DebugString("Execute " & Replace(xcmd, sPassword, "***"))
  Shell xcmd Wait

End

Public Sub Get7ZExtraction(CompressedPath As String, sPassword As String, UnCompressedPath As String)

  Dim xcmd As String

  xcmd = "7z x " & CompressedPath & " -p" & sPassword & " -o" & File.Dir(UnCompressedPath)
  modBasic.DebugString("Execute " & Replace(xcmd, sPassword, "***"))
  Shell xcmd Wait

End

''------------------------------------- PDF Encryption --------------------------------
Public Sub GetEncryptPDF(sInput As String, sOutput As String, sPass As String)

  Dim arcmd As String[]

  If System.Exist("qpdf") Then
    arcmd = ["qpdf", "--encrypt", sPass, sPass, 40, "--", sInput, sOutput]
    modBasic.DebugString("Execute " & Replace(arcmd.Join(Space(1)), sPass, "***"))
    Exec arcmd Wait
  Else
    sOutput = sInput
  Endif

End

Public Sub GetDecryptPDF(sInput As String, sOutput As String, sPass As String)

  Dim arcmd As String[]

  If System.Exist("qpdf") Then
    arcmd = ["qpdf", "--password=" & sPass, "--decrypt", sInput, sOutput]
    modBasic.DebugString("Execute " & Replace(arcmd.Join(Space(1)), sPass, "***"))
    Exec arcmd Wait
  Else
    sOutput = sInput
  Endif

End

'NOTE: ----------------------------- BAR CODE PROCEDURES ----------------------------------------
Private Function GetZintCode(sName As String) As String

  Dim xx As String
  Dim xfile As String

  xfile = modHelpVariable.$localesDirectory &/ "zint"
  If Exist(xfile) Then
    xx = modString.GetValueFromCSV(sName, xfile, 1, 0, ";")
  Endif
  Return xx

End

Public Function MakeBarQREncid(encid As String) As String

  Dim xform As String
  Dim xpath As String

  If modBasic.$BarCodeFormatString Then
    xform = modBasic.$BarCodeFormatString
  Else
    xform = "QR Code"
  Endif

  If xform = "QR Code" Then
    xpath = MakeQRCode(encid)
  Else
    xpath = MakeBarCodeZint(encid)
  Endif
  Return xpath

End

Public Function MakeQRCode(encid As String) As String

  Dim hFil As String
  Dim arcmd As String[]

  If System.Exist("qrencode") = True Then
    hFil = Temp() & ".png"
    arcmd = New String[]
    arcmd.Add("qrencode")
    arcmd.Add("--casesensitive")
    If modBasic.$BarCodePixelSize Then
      arcmd.Add("-s")
      arcmd.Add(CStr(modBasic.$BarCodePixelSize))
    Endif
    If modBasic.$BarCodeImageDPI Then
      arcmd.Add("-d")
      arcmd.Add(CStr(modBasic.$BarCodeImageDPI))
    Endif
    If modBasic.$BarCodeMarginWidth Then
      arcmd.Add("-m")
      arcmd.Add(CStr(modBasic.$BarCodeMarginWidth))
    Endif
    If modBasic.$BarCodeForeGround Then
      arcmd.Add("--foreground=" & Hex(modBasic.$BarCodeForeGround))
    Endif
    If modBasic.$BarCodeBackGround Then
      arcmd.Add("--background=" & Hex(modBasic.$BarCodeBackGround))
    Endif
    arcmd.Add("-o")
    arcmd.Add(hFil)
    arcmd.Add(encid)
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd Wait
  Endif
  Return hFil

End

Private Function MakeBarCodeZint(encid As String) As String

  Dim hFil As String
  Dim arcmd As String[]
  Dim xcode As String

  If System.Exist("zint") = True Then
    hFil = Temp() & ".png"
    arcmd = New String[]
    arcmd.Add("zint")
    If modBasic.$BarCodeFormatString Then
      xcode = Trim(GetZintCode(modBasic.$BarCodeFormatString))
      If xcode Then
        arcmd.Add("-b")
        arcmd.Add(xcode)
      Endif
    Endif
    If modBasic.$BarCodeDisplayText = "No" Then
      arcmd.Add("--notext")
    Else
      arcmd.Add("--small")
    Endif
    If modBasic.$BarCodeWidth Then
      arcmd.Add("--scale=" & CStr(modBasic.$BarCodeWidth))
    Endif
    If modBasic.$BarCodeWhiteSpace Then
      arcmd.Add("-w")
      arcmd.Add(CStr(modBasic.$BarCodeWhiteSpace))
    Endif
    If modBasic.$BarCodeForeGround Then
      arcmd.Add("--fg=" & Hex(modBasic.$BarCodeForeGround))
    Endif
    If modBasic.$BarCodeBackGround Then
      arcmd.Add("--bg=" & Hex(modBasic.$BarCodeBackGround))
    Endif
    arcmd.Add("-o")
    arcmd.Add(hFil)
    arcmd.Add("-d")
    arcmd.Add(encid)
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd Wait
  Endif
  Return hFil

End

Public Function GetBarCodeSample(encid As String) As String

  Dim hFil As String
  Dim arcmd As String[]

  If System.Exist("zint") = True Then
    hFil = Temp() & ".png"
    arcmd = New String[]
    arcmd.Add("zint")
    arcmd.Add("--notext")
    arcmd.Add("-o")
    arcmd.Add(hFil)
    arcmd.Add("-d")
    arcmd.Add(encid)
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd Wait
  Endif
  Return hFil

End

Public Function ChooseBarCodeSource() As String

  Dim device As String
  Dim xsource As String
  Dim sPath As String
  Dim enc As String

  device = modSettings.ShowSettingFromFIle("BarCodeSettings/Device")
  xsource = modSettings.ShowSettingFromFIle("BarCodeSettings/Source")
  If Not device Then
    device = "/dev/video0"
  Endif

  If device Then
    If xsource = "Video" Then
      enc = modCodeRead.GetBarCodeFromVideo(device)
    Else If xsource = "Image" Then
      sPath = modImage.GetWebCamValue(device)
      If sPath Then
        enc = modCodeRead.GetBarCodeString(sPath)
      Endif
    Else
      enc = InputBox(("Get Bar Code Device output here"), "Bar Code", "")
    Endif
  Endif
  Return enc

End
'

Public Sub PrintBarCodeEnc(encid As String)

  modPrint.DefaultPrinting(MakeBarQREncid(encid), "LabelSize")

End

''
'''
''''

'NOTE: ------------------------------ Webcam Procedures -----------------------------------------------
Public Function WebCamDevice() As String

  Dim xx As String
  Dim xdevice As String

  xdevice = modSettings.ShowSettingFromFIle("WebCamSettings/Device")
  If xdevice Then
    xx = xdevice
  Else
    xx = "/dev/video0"
  Endif
  Return xx

End

Public Sub GetWebCamSnapShot(strPath As String)

  Dim arcmd As String[]

  If System.Exist("streamer") = True Then
    arcmd = ["streamer", "-c", WebCamDevice(), "-o", strPath]
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd Wait
  Endif

End

Public Function GetWebCamVideo(dura As Integer) As String

  Dim aa As String
  Dim bb As String
  Dim cc As String
  Dim yy As String
  Dim arcmd As String[]
  Dim sTemp As String

  aa = modSettings.ShowSettingFromFIle("WebCamSettings/ImageQuality")
  bb = modSettings.ShowSettingFromFIle("WebCamSettings/ImageFormat")
  cc = modSettings.ShowSettingFromFIle("WebCamSettings/FrameRate")

  yy = modString.ConvertSecondToDurationString(dura)
  sTemp = Temp() & ".avi"

  If System.Exist("streamer") = True Then
    If aa And If bb And If cc Then
      arcmd = ["streamer", "-q", "-c", WebCamDevice(), "-f", bb, "-j", aa, "-r", cc, "-t", yy, "-o", sTemp]
    Else
      arcmd = ["streamer", "-q", "-c", WebCamDevice(), "-t", yy, "-o", sTemp]
    Endif
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd Wait
  Endif
  Return sTemp

End

Public Sub CamOnStart()

  Dim stpath As String

  If modGlobalSetting.ShowSettingFromDB("WebcamShot/Start") = "Yes" Then
    stpath = Temp() & ".jpeg"
    GetWebCamSnapShot(stpath)
    modImage.AddUserImageToDB("Start", stpath)
  Endif

End

Public Sub CamOnError()

  Dim stpath As String

  If modGlobalSetting.ShowSettingFromDB("WebcamShot/Error") = "Yes" Then
    stpath = Temp() & ".jpeg"
    GetWebCamSnapShot(stpath)
    modImage.AddUserImageToDB("Error", stpath)
  Endif

End

Public Sub CamOnClose()

  Dim stpath As String

  If modGlobalSetting.ShowSettingFromDB("WebcamShot/Close") = "Yes" Then
    stpath = Temp() & ".jpeg"
    GetWebCamSnapShot(stpath)
    modImage.AddUserImageToDB("Close", stpath)
  Endif

End

'
''
'''
''''

'NOTE: ---------------------------------------- TRANSLATE ---------------------------------------------
Public Function TranslateTextToNewLanguage(langcode As String, txtcontent As String) As String

  Dim xx As String
  Dim code As String
  Dim yy As String
  Dim arcmd As String[]

  code = ":" & langcode
  arcmd = ["trans", "-brief", code, txtcontent]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xx

  If xx Then
    yy = Replace(xx, "null", "")
  Else
    yy = ""
  Endif
  Return yy

End
'
''
'''
''''

'NOTE: ---------------------------------- SYSTEM LOCK --------------------------------------
Public Function GetSystemIdleTime() As Long

  Dim xx As String
  Dim yy As Long

  If System.Exist("xprintidle") = True Then
    modBasic.DebugString("Execute " & "xprintidle")
    Exec ["xprintidle"] To xx
    If xx Then
      yy = Val(xx)
    Else
      yy = 0
    Endif
  Endif
  Return yy

End

Public Function GetLockOnIdleTime() As Boolean

  Dim xx As Boolean
  Dim xLock As Float

  If modBasic.$LockInTime Then
    xLock = CFloat(modBasic.$LockInTime)
    If xLock Then
      If GetSystemIdleTime() > xLock * 60000 Then
        xx = True
      Endif
    Endif
  Endif
  Return xx

End

'
''
'''
''''

'NOTE: ----------------------------------------------- FTP Server ----------------------------------------------
Public Function SendFileToFTP(ftpHost As String, ftpFolder As String, ftpUser As String, ftpPassword As String, sTargFile As String, sFile As String) As String

  Dim xx As String
  Dim arcmd As String[]
  Dim sOut As String
  Dim xmsg As String

  xx = "ftp://" & ftpUser & ":" & ftpPassword & "@" & ftpHost &/ ftpFolder &/ sTargFile
  arcmd = ["wput", sFile, xx]
  modBasic.DebugString("Execute " & Replace(arcmd.Join(Space(1)), ftpPassword, "***"))
  Exec arcmd To sOut

  If InStr(sOut, "failed") > 0 Then
    xmsg = sOut
  Else
    xmsg = ""
  Endif
  Return xmsg

End

''send file to Remote FTP to upload Laboratory and Radiology Report and send sms
Public Sub SendFileToRemoteFTP(sPath As String)

  Dim sHost As String
  Dim sFolder As String
  Dim sUser As String
  Dim sPass As String
  Dim xx As String

  modWeb.GetRemoteFTPValues()
  sHost = modWeb.$webFTPHost
  If sHost Then
    sFolder = modWeb.$webFTPDir
    sUser = modWeb.$webFTPUser
    sPass = modWeb.$webFTPPass
  Endif

  If sHost Then
    xx = SendFileToFTP(sHost, sFolder &/ modGeneralMain.$SysDataBase, sUser, sPass, File.Name(sPath), sPath)
  Endif
  If xx Then
    Message.Warning(xx, ("OK"))
  Endif

End

''Send Image/Blob to Local FTP Server for all types of internal file storage (acc to General Setting)
Public Sub SendBlobToFTP(hFile As String, sType As String, sFolder As String) As String

  Dim sPath As String
  Dim sHost As String
  Dim sTarget As String
  Dim sUser As String
  Dim sPass As String
  Dim xx As String

  sHost = modGeneralMain.$SysFTPHost
  sTarget = modGeneralMain.$SysFTPFolder &/ sFolder &/ sType
  sUser = modGeneralMain.$SysFTPUser
  sPass = modGeneralMain.$SysFTPPass

  If sHost Then
    sPath = sFolder &/ sType &/ modString.GetNowString()
    xx = SendFileToFTP(sHost, sTarget, sUser, sPass, modString.GetNowString(), hFile)
    If xx Then
      Message.Warning(xx, ("OK"))
    Else
      Return sPath
    Endif
  Endif

End

''Download File from Local FTP server
Public Function GetFileFromLocalFTP(sLink As String) As String

  Dim sHost As String
  Dim sFTP As String
  Dim sUser As String
  Dim sPass As String
  Dim sPath As String
  Dim sTarget As String
  Dim xcmd As String

  sHost = modGeneralMain.$SysFTPHost
  If sHost Then
    sFTP = modGeneralMain.$SysFTPFolder
    sUser = modGeneralMain.$SysFTPUser
    sPass = modGeneralMain.$SysFTPPass
    sPath = "ftp://" & sHost &/ sFTP &/ sLink
    sTarget = "/tmp/" &/ modString.GetNowString()
    If Not Exist(sTarget) Then
      Mkdir sTarget
    Endif

    xcmd = "wget --ftp-user=" & Quote(sUser) & " --ftp-password=" & Quote(sPass) & Space(1) & Quote(sPath) & " -P " & sTarget
    modBasic.DebugString("Execute " & Replace(xcmd, sPass, "***"))
    Shell xcmd Wait
    If Exist(sTarget &/ File.Name(sLink)) Then
      Return sTarget &/ File.Name(sLink)
    Endif
  Endif

End

'''
'''---------------------------------- deleting FTP file -----------------------------------------
Public Sub DeleteFTPFIle(ftpHost As String, ftpFolder As String, ftpUser As String, ftpPassword As String, sTargFile As String)

  Dim xx As String
  Dim arcmd As String[]

  xx = "ftp://" & ftpUser & ":" & ftpPassword & "@" & ftpHost &/ ftpFolder &/ sTargFile
  arcmd = ["wdel", xx]
  modBasic.DebugString("Execute " & Replace(arcmd.Join(Space(1)), ftpPassword, "***"))
  Exec arcmd Wait
  ''delete folder if folder is blank now

End

''Delete Image/Blob file present in Local FTP
Public Function DeleteBlobFIleFTP(sLink As String)

  Dim sHost As String
  Dim sFolder As String
  Dim sUser As String
  Dim sPass As String

  sHost = modGeneralMain.$SysFTPHost
  sFolder = modGeneralMain.$SysFTPFolder
  sUser = modGeneralMain.$SysFTPUser
  sPass = modGeneralMain.$SysFTPPass

  If sHost Then
    DeleteFTPFIle(sHost, sFolder, sUser, sPass, sLink)
  Endif

End

'
''
'''
''''

''------------------------------- SMTP E mail ------------------------------
Public Sub SendSMTPEmail(lstsendto As String[], xlstcc As String[], xlstbcc As String[], sSubject As String, sMessage As String, sAttacPath As String)

  Dim hClient As New SmtpClient
  Dim xsend As String
  Dim xcc As String
  Dim xbcc As String

  With hClient
    .Host = modBasic.$emailSMTPHost
    .Encrypt = Net.TLS
    .User = modBasic.$emailSMTPUser
    .Password = modBasic.$emailSMTPPass
    If modBasic.$DebugMode = True Then
      .Debug = True
    Endif

    .Subject = sSubject
    .From = modBasic.$emailSMTPFrom
    For Each xsend In lstsendto
      .To.Add(xsend)
    Next
    For Each xcc In xlstcc
      .Cc.Add(xcc)
    Next
    For Each xbcc In xlstbcc
      .Bcc.Add(xbcc)
    Next
    .Body = sMessage
    If sAttacPath Then
      .Add(File.Load(sAttacPath), "application/pdf", "Attachment")
    Endif
    modBasic.DebugString("Sending SMTP E-mail to " & lstsendto.Join(";"))
    .Send()
  End With

End

''--------------------------- Socket Transfer --------------------------
Public Sub TransferTextSocket(sHost As String, sPort As String, xline As String)

  Dim MySock As Socket

  MySock = New Socket As "MySock"
  MySock.Host = sHost
  MySock.Port = sPort
  modBasic.DebugString("Connect to Port " & sPort & " on Host " & sHost)
  MySock.Connect()

  While (MySock.Status <> 7) And (MySock.Status > 0)
    Wait 0.1
  Wend

  Write #MySock, xline, Len(xline)
  Close #MySock

End

Public Function HTTPPostCollectionVal(sURL As String, sPort As String, xuser As String, xpass As String, sColl As JSONCollection) As String

  Dim xauth As String
  Dim xcontent As String
  Dim arcmd As String
  Dim xval As String

  xauth = xuser & ":" & xpass
  xcontent = "Content-Type: application/json"
  arcmd = "curl -u " & xauth & " -d '" & JSON.Encode(sColl) & "' -H " & Quote(xcontent) & "  -X POST " & sURL & ":" & sPort
  modBasic.DebugString("Execute " & Replace(arcmd, xpass, "***"))
  Shell arcmd To xval
  Return Trim(xval)

End

Public Function GetCurlDownload(sLink As String) As String

  Dim arcmd As String[]
  Dim xval As String

  arcmd = ["curl", sLink]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xval
  Return xval

End

Public Function GetCurlGetDownload(sLink As String) As String

  Dim arcmd As String[]
  Dim xval As String

  arcmd = ["curl", "--request", "GET", "--url", sLink]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xval
  Return xval

End

Public Sub GetWgetDownload(sLink As String, sOutFile As String)

  Dim arcmd As String[]

  arcmd = ["wget", sLink, "-O", sOutFile]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd Wait

End
