' Gambas module file

Public Function GetLastWordPosition(sText As String) As Integer

  Dim sWord As String[]
  Dim i As Integer
  Dim iPos As Integer

  sWord = Split(sText, Space(1))
  iPos = 0
  For i = 0 To sWord.Count - 2
    iPos = iPos + Len(sWord[i]) + 1
  Next

  Return iPos + 1

End

Public Function GetLastWordText(sText As String) As String

  Dim sWord As String[]
  Dim xx As String

  sWord = Split(sText, Space(1))
  xx = sWord[sWord.Count - 1]
  Return xx

End

Public Function GetSelectedText(sText As String, StartWord As String, EndWord As String) As String ''include start/end text

  Dim aa As Integer
  Dim bb As Integer
  Dim xx As String

  aa = InStr(sText, StartWord)
  bb = InStr(sText, EndWord, aa)
  If aa And If bb Then
    xx = Mid(sText, aa, (bb - aa) + Len(EndWord))
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetBodyRichText(sText As String) As String

  Dim xx As String
  Dim aa As Integer
  Dim yy As String

  xx = GetSelectedText(sText, "<body", "</body>")
  aa = String.InStr(xx, ">")
  yy = Mid(xx, aa + 1)
  yy = Replace(yy, "</body>", "")

  Return Trim(yy)

End '

Public Function IsRichTextMode(sText As String) As Boolean

  Dim xx As Boolean

  If (String.InStr(sText, "<p") > 0) Then
    xx = True
  Else If (String.InStr(sText, "<span") > 0) Then
    xx = True
  Else If (String.InStr(sText, "<table") > 0) Then
    xx = True
  Else
    xx = False
  Endif
  Return xx

End
