' Gambas module file

Public $webFTPHost As String
Public $webFTPDir As String
Public $webFTPUser As String
Public $webFTPPass As String

Public Function GetWebConfigFile() As String

  Dim xdir As String
  Dim xpath As String

  If Exist(modHelpVariable.AppDirectory &/ "weblink.conf.7z") Then
    xdir = modHelpVariable.AppCacheDir
    If Exist(xdir &/ "weblink.conf") Then
      Kill xdir &/ "weblink.conf"
    Endif
    If Not Exist(xdir) Then
      Mkdir xdir
    Endif
    modDevice.Get7ZExtraction(modHelpVariable.AppDirectory &/ "weblink.conf.7z", modGeneralMain.$CryptZip, xdir &/ "weblink.conf")
    xpath = xdir &/ "weblink.conf"
  Endif
  Return xpath

End

''Det Remote FTP values
Public Sub GetRemoteFTPValues()

  Dim xpath As String

  If Not $webFTPHost Then
    xpath = GetWebConfigFile()
    $webFTPHost = modSettings.ShowSettingValue(xpath, "RemoteFTP/Host")
    $webFTPDir = modSettings.ShowSettingValue(xpath, "RemoteFTP/FTPFolder")
    $webFTPUser = UnBase64(modSettings.ShowSettingValue(xpath, "RemoteFTP/User"))
    $webFTPPass = UnBase64(modSettings.ShowSettingValue(xpath, "RemoteFTP/Password"))
    Try Kill xpath
  Endif

End
