' Gambas module file

Public Sub AddClinicExam(encid As String, strSerial As String, strHead As String, strQuali As String, strQuanti As Float, abn As Boolean, strType As String, sysCons As String, xmethod As String)

  Dim res As Result
  Dim xType As String

  If sysCons Then
    xType = modFixClinic.GetExamSysOptionType(sysCons)
  Else
    xType = modFixClinic.GetExamtOptionType(strHead)
  Endif

  res = modDatabase.$myConn.Create("tblpatientexam")
  res["fldencounterval"] = encid
  res["fldserialval"] = strSerial
  res["fldinput"] = strType
  res["fldhead"] = strHead
  res["fldsysconst"] = sysCons
  res["fldoption"] = xType
  res["fldmethod"] = xmethod

  If Not strQuali And If strQuanti Then
    res["fldtype"] = "Quantitative"
    res["fldrepquali"] = CStr(strQuanti)
    res["fldrepquanti"] = strQuanti

  Else
    If xType = "Clinical Scale" Then
      res["fldtype"] = "Qualitative"
      res["fldrepquali"] = strQuali
      res["fldrepquanti"] = strQuanti
    Else
      res["fldtype"] = "Qualitative"
      res["fldrepquali"] = strQuali
      res["fldrepquanti"] = 0
    Endif

  Endif

  res["fldfilepath"] = ""
  If IsDate(strQuali) Then
    res["fldrepdate"] = CDate(strQuali)
  Endif
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["fldabnormal"] = abn
  res["xyz"] = False
  res["flduptime"] = ""
  res.Update()
  'don't catch error

End

''--for fmEnterMultiExams and local  procedures
Public Sub AddQualiData(encid As String, strSerial As String, strHead As String, strReport As String, abn As Boolean, strType As String, Optional sysCons As String)

  Dim xsys As String

  If sysCons Then
    xsys = sysCons
  Else
    xsys = ""
  Endif
  AddClinicExam(encid, strSerial, strHead, strReport, 0, abn, strType, xsys, "Regular")

End

Public Sub AddQuantiData(encid As String, strSerial As String, strHead As String, strReport As Float, abn As Boolean, strType As String, Optional sysCons As String)

  Dim xsys As String
  Dim metList As String[]
  Dim xmethod As String

  If sysCons Then
    xsys = sysCons
  Else
    xsys = ""
  Endif

  metList = modFixClinic.MethodsForClinExam(strHead)
  If metList.Count = 0 Then
    xmethod = "Regular"
  Else If metList.Count = 1 Then
    xmethod = metList[0]
  Else
    xmethod = InputCombo("Select Method of Examination", strHead, metList, "", True)
  Endif
  AddClinicExam(encid, strSerial, strHead, "", strReport, abn, strType, xsys, xmethod)

End

Public Sub AddQuantiDataCheck(encid As String, strSerial As String, strHead As String, strReport As Float, strType As String, Optional sysCons As String)

  Dim xlimit As Float[]
  Dim xbool As Boolean

  xlimit = modClinic.GetBothQuantiExamVal(strHead, encid)
  If xlimit[0] = 0 And If xlimit[1] = 0 Then
    xbool = False
  Else
    If strReport < xlimit[0] Or If strReport > xlimit[1] Then
      xbool = True
    Else
      xbool = False
    Endif
  Endif
  If sysCons Then
    AddQuantiData(encid, strSerial, strHead, strReport, xbool, strType, sysCons)
  Else
    AddQuantiData(encid, strSerial, strHead, strReport, xbool, strType)
  Endif

End

Public Sub UpdateQualiQuantiData(xfldid As Long, strQuali As String, strQuanti As Float, abn As Boolean, Optional KeyList As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientexam", "fldid=&1", xfldid)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["fldsave"] = True

    If Not strQuanti Then
      res["fldrepquali"] = strQuali
      If IsFloat(strQuali) = True Then
        res["fldrepquanti"] = CFloat(strQuali)
      Else
        res["fldrepquanti"] = 0
      Endif
    Else
      res["fldrepquali"] = strQuali
      res["fldrepquanti"] = strQuanti
    Endif

    If KeyList Then
      res["fldfilepath"] = KeyList
    Endif
    res["fldabnormal"] = abn
    res["flduserid"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

Public Sub UpdateQualiData(xfldid As Long, strReport As String, abn As Boolean, Optional KeyList As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientexam", "fldid=&1", xfldid)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["fldsave"] = True
    res["fldrepquali"] = strReport
    If IsFloat(strReport) = True Then
      res["fldrepquanti"] = CFloat(strReport)
    Else
      res["fldrepquanti"] = 0
    Endif
    If KeyList Then
      res["fldfilepath"] = KeyList
    Endif
    res["fldabnormal"] = abn
    res["flduserid"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

Public Sub UpdateQuantiData($fldid As Long, strReport As Float, abn As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientexam", "fldid=&1", $fldid)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["fldsave"] = True
    res["fldrepquali"] = CStr(strReport)
    res["fldrepquanti"] = strReport
    res["fldabnormal"] = abn
    res["flduserid"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

Public Sub UpdateExamFlag(sid As Long, xFlag As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientexam", "fldid=&1", sid)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    If xFlag = "Abnormal" Then
      res["fldabnormal"] = True
    Else
      res["fldabnormal"] = False
    Endif
    res["flduserid"] = modGeneralMain.$lbluser
    res["xyz"] = False
    res.Update
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif

End

'''-------------------------------- General Parameters -------------------------------------------
Public Sub AddGeneralParametersQuali(encid As String, sParameter As String, sValue As String)

  AddQualiData(encid, "", sParameter, sValue, False, "General Parameters")

End

Public Sub AddGeneralParametersQuanti(encid As String, sParameter As String, sValue As Float)

  AddQuantiData(encid, "", sParameter, sValue, False, "General Parameters")

End

''---only for fmEnterMultiExam
Public Sub AddClinicQualiData(encid As String, strSerial As String, strHead As String, strReport As String, abn As Boolean, sysCons As String)

  Dim xsys As String

  If sysCons Then
    xsys = sysCons
  Else
    xsys = ""
  Endif
  AddQualiData(encid, strSerial, strHead, strReport, abn, "Rec Examination", xsys)

End

Public Sub AddClinicQuantiData(encid As String, strSerial As String, strHead As String, strReport As Float, abn As Boolean, sysCons As String)

  Dim xsys As String

  If sysCons Then
    xsys = sysCons
  Else
    xsys = ""
  Endif
  AddQuantiData(encid, strSerial, strHead, strReport, abn, "Rec Examination", xsys)

End

Public Sub UpdateClinicQualiData($fldid As Long, strReport As String, abn As Boolean, Optional KeyList As String)

  If KeyList Then
    UpdateQualiData($fldid, strReport, abn, KeyList)
  Else
    UpdateQualiData($fldid, strReport, abn)
  Endif

End

Public Sub UpdateClinicQuantiData($fldid As Long, strReport As Float, abn As Boolean)

  UpdateQuantiData($fldid, strReport, abn)

End

'''-------------------------------------------General exam ------------------------------------------------------------
Public Sub AddExamQualiData(encid As String, strSerial As String, strHead As String, strReport As String, abn As Boolean)

  AddQualiData(encid, strSerial, strHead, strReport, abn, "Examination")

End

Public Sub AddExamQuantiData(encid As String, strSerial As String, strHead As String, strReport As Float, abn As Boolean)

  AddQuantiData(encid, strSerial, strHead, strReport, abn, "Examination")

End

''---------------------------------------- Sub exam ------------------------------------------------------------------
Public Function GetSubExamBool(pttestid As Long) As Boolean

  Dim rs As Result
  Dim xx As Boolean

  rs = modDatabase.$myConn.Exec("select fldid,fldsubtexam from tblpatientsubexam where fldheadid=&1", pttestid)
  xx = rs.Available
  Return xx

End

Public Sub InsertExamSubExam(encid As String, pttestid As Long, subexamList As String[])

  Dim res2 As Result
  Dim xx As String

  For Each xx In subexamList
    res2 = modDatabase.$myConn.Create("tblpatientsubexam")
    res2["fldencounterval"] = encid
    res2["fldheadid"] = pttestid
    res2["fldsubtexam"] = xx
    res2["fldtanswertype"] = modFixClinic.GetSubExamOption(GetExamNameFromExamID(pttestid), xx)
    res2["fldreport"] = ""
    res2["fldsave"] = False
    res2["fldabnormal"] = False
    res2["fldchk"] = False
    res2["fldfilepath"] = ""
    res2["xyz"] = False
    res2.Update()
  Next

  'don't catch error

End

''--------------------------------- BOTH GENERAL AND RECOMMENDED EXAMINATION  -----------------------------------------------------
Public Function GetExamNameFromExamID(id As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldhead from tblpatientexam where fldid=&1", id)
  If res.Available Then
    If res!fldhead Then
      xx = res!fldhead
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetEncidFromExamID(id As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldencounterval from tblpatientexam where fldid=&1", id)
  If res.Available Then
    If res!fldencounterval Then
      xx = res!fldencounterval
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetExamTimeFromExamID(id As Long) As Date

  Dim res As Result
  Dim xx As Date

  res = modDatabase.$myConn.Exec("select fldtime from tblpatientexam where fldid=&1", id)
  If res.Available Then
    If res!fldtime Then
      xx = res!fldtime
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetExamValueByID(id As Long) As Float

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select fldrepquanti from tblpatientexam where fldid=&1", id)
  If res.Available Then
    If res!fldrepquanti Then
      xx = res!fldrepquanti
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

''X-------------------------------------------- GENERAL EXAMINATION -------------------------------------------------------------------------
Public Function PaientAllExamNameArray(encid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select distinct(fldhead) as col from tblpatientexam where fldencounterval=&1 and fldsave=&2", encid, True)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function PaientSelExamNameArray(encid As String, sType As String) As String[]

  Dim res As Result
  Dim xx As String[]

  If sType = "Vital" Then
    res = modDatabase.$myConn.Exec("select distinct(fldhead) as col from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldhead in(select fldexamid from tblcompexam where fldcomp=&3 and fldcategory=&4)", encid, True, modGeneralMain.compID, "Essential Examinations")
  Else If sType = "Non-Vital" Then
    res = modDatabase.$myConn.Exec("select distinct(fldhead) as col from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldhead not in(select fldexamid from tblcompexam where fldcomp=&3 and fldcategory=&4)", encid, True, modGeneralMain.compID, "Essential Examinations")
  Endif
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function UniExamValueList(encid As String, sExam As String) As String[]

  Dim res As Result
  Dim xx As String[]

  xx = New String[]
  res = modDatabase.$myConn.Exec("select fldtime,fldrepquali from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldsave=&3", encid, sExam, True)
  If res.Available Then
    For Each res
      If res!fldrepquali Then
        xx.Add(modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " : " & res!fldrepquali)
      Endif
    Next
  Endif

  Return xx

End

''--------------------------------- EXAM FIXED VALUES ---------------------------------------------------------------------
Public Function GetBothQuantiExamVal(txtexam As String, encid As String, Optional sMethod As String) As Float[]

  Dim res As Result
  Dim xlow As Float
  Dim xhigh As Float
  Dim sqstr As String
  Dim xlimit As Float[]

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  res = modDatabase.$medConn.Exec("select fldlow,fldhigh from tblexamlimit where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr, txtexam, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)                                                               ''
  If res.Available = True Then
    res.MoveFirst
    If res!fldlow Then
      xlow = res!fldlow
    Else
      xlow = 0
    Endif
    If res!fldhigh Then
      xhigh = res!fldhigh
    Else
      xhigh = 0
    Endif
  Else
    xlow = 0
    xhigh = 0
  Endif
  xlimit = [xlow, xhigh]

  Return xlimit

End

Public Function GetExamBothLimits(id As Long) As Float[]

  Dim res As Result
  Dim sql As String
  Dim xlimit As Float[]

  Dim LwLimit As Float
  Dim UpLimit As Float
  Dim xval As Float[]

  sql = "select fldencounterval,fldhead from tblpatientexam where fldid=&1 and fldtype=&2 and fldsave=&3"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative", True)
  If res.Available = True Then
    xlimit = GetBothQuantiExamVal(res!fldhead, res!fldencounterval)
    LwLimit = xlimit[0]
    UpLimit = xlimit[1]
  Else
    LwLimit = 0
    UpLimit = 0
  Endif
  xval = [LwLimit, UpLimit]

  Return xval

End

Public Function GetExamLimitSrtings(id As Long) As String

  Dim xx As String
  Dim res As Result
  Dim xmax As Float
  Dim xmin As Float
  Dim xlimit As Float[]

  res = modDatabase.$myConn.Exec("select fldencounterval,fldtype from tblpatientexam where fldid=&1", id)
  If res!fldtype = "Quantitative" Then
    xlimit = GetExamBothLimits(id)
    xmin = xlimit[0]
    xmax = xlimit[1]
    If xmin < xmax Then
      xx = CStr(xmin) & "  -  " & CStr(xmax) & Space(1) & GetExamUnitString(res!fldencounterval, id)
    Else
      xx = ""
    Endif
  Else
    xx = modFixClinic.GetExamQualiTextReference(GetExamNameFromExamID(id))
  Endif

  Return xx

End

Public Function GetNormalQuantiExamVal(txtexam As String, encid As String, Optional sMethod As String) As Float

  Dim res As Result
  Dim xx As Float
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  res = modDatabase.$medConn.Exec("select fldnormal from tblexamlimit where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr, txtexam, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)                                                               ''
  If res.Available = True Then
    res.MoveFirst
    If res!fldnormal Then
      xx = res!fldnormal
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End

Public Function GetExamUnit(txtexam As String, encid As String, Optional sMethod As String) As String

  Dim res As Result
  Dim xx As String
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  res = modDatabase.$medConn.Exec("select fldunit from tblexamlimit where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr, txtexam, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)                                                               ''
  If res.Available = True Then
    res.MoveFirst
    If res!fldunit Then
      xx = res!fldunit
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Private Function GetExamUnitString(encid As String, id As Long) As String

  Dim res As Result
  Dim sql As String
  Dim LabUnit As String

  sql = "select fldencounterval,fldhead from tblpatientexam where fldid=&1 and fldtype=&2 and fldencounterval=&3 and fldsave=&4"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative", encid, True)
  If res.Available = True Then
    LabUnit = GetExamUnit(res!fldhead, res!fldencounterval)
  Else
    LabUnit = ""
  Endif

  Return LabUnit

End

Public Function ExamQuantiTableValue(sField As String, txtexam As String, encid As String, Optional sMethod As String) As Float

  Dim res As Result
  Dim xx As Float
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  res = modDatabase.$medConn.Exec(Subst("select &1 as fld from tblexamlimit", sField) & " where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr, txtexam, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)                                                               ''
  If res.Available = True Then
    res.MoveFirst
    If res!fld Then
      xx = res!fld
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  If xx = 0 Then
    xx = modFixClinic.ExamTableValue(sField, txtexam)
  Endif

  Return xx

End

Public Function GetExamSensiSpecArray(id As Long) As Float[]

  Dim xxx As Float[]
  Dim res As Result
  Dim sql As String

  xxx = New Float[]
  sql = "select fldencounterval,fldhead,fldmethod,fldtype from tblpatientexam where fldid=&1"
  res = modDatabase.$myConn.Exec(sql, id)
  If res.Available Then
    If res!fldtype = "Quantitative" Then
      If res!fldmethod Then
        xxx.Add(ExamQuantiTableValue("fldsensitivity", res!fldhead, res!fldencounterval, res!fldmethod))
        xxx.Add(ExamQuantiTableValue("fldspecificity", res!fldhead, res!fldencounterval, res!fldmethod))
      Else
        xxx.Add(ExamQuantiTableValue("fldsensitivity", res!fldhead, res!fldencounterval))
        xxx.Add(ExamQuantiTableValue("fldspecificity", res!fldhead, res!fldencounterval))
      Endif

    Else
      xxx.Add(modFixClinic.ExamTableValue("fldsensitivity", res!fldhead))
      xxx.Add(modFixClinic.ExamTableValue("fldspecificity", res!fldhead))

    Endif
  Endif

  Return xxx

End

''------------------------------------OBSERVATION--------------------------------------
Public Function GetExamValueSubString(id As Variant) As Variant

  Dim res As Result
  Dim res1 As Result
  Dim sql As String
  Dim xx As Variant
  Dim xquali As String
  Dim xType As String

  sql = "select fldid,fldencounterval,fldhead,fldrepquali,fldrepquanti,fldtype,fldabnormal,fldoption from tblpatientexam where fldid=&1"
  res = modDatabase.$myConn.Exec(sql, id)
  If res.Available = True Then
    If res!fldtype = "Quantitative" Then
      xx = res!fldrepquanti
    Else
      If res!fldrepquali Then

        xType = res["fldoption"]
        If xType = "Clinical Scale" Then
          If modBasic.$ShowScaleMedFormat = "GroupWise" Then
            xx = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
          Else
            xx = res!fldrepquanti
          Endif
        Else If xType = "Left and Right" Then
          xx = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
        Else
          xx = Trim(res!fldrepquali)
        Endif
      Else
        xx = ""
      Endif

      res1 = modDatabase.$myConn.Exec("select fldsubtexam,fldreport,fldid,fldheadid,fldtanswertype from tblpatientsubexam where fldheadid=&1 and fldencounterval=&2", res!fldid, res!fldencounterval)
      If res1.Available = True Then
        xquali = ""
        For Each res1
          If res1!fldtanswertype = "Multiple Selection" Or If res1!fldtanswertype = "Single Column" Then
            xquali = xquali & res1!fldsubtexam & " : " & gb.NewLine & GetSubExamTableReportString(res1!fldheadid, res1!fldid) & gb.NewLine & gb.NewLine
          Else If res1!fldtanswertype = "Text Table" Then
            xquali = xquali & res1!fldsubtexam & " : " & gb.NewLine & GetSubExamTableReportString(res1!fldheadid, res1!fldid) & gb.NewLine & gb.NewLine
          Else If res1!fldtanswertype = "Dual Columns" Then
            xquali = xquali & res1!fldsubtexam & " : " & gb.NewLine & GetSubExamDualTableString(res1!fldheadid, res1!fldid) & gb.NewLine & gb.NewLine
          Else
            If res1!fldreport Then
              xquali = xquali & res1!fldsubtexam & " : " & res1!fldreport & gb.NewLine
            Endif
          Endif
        Next
        xx = xx & gb.NewLine & xquali
      Endif

    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetExamValueString(encid As String, id As Long, Report As Boolean) As String

  Dim res As Result
  Dim xx As String
  Dim xType As String
  Dim xval As String

  res = modDatabase.$myConn.Exec("select fldhead,fldrepquanti,fldrepquali,fldtype,fldoption,fldinput,fldabnormal from tblpatientexam where fldid=&1 and fldencounterval=&2", id, encid)
  If res.Available Then
    If res!fldtype = "Quantitative" Then
      If res!fldrepquanti Then
        xval = CStr(res!fldrepquanti) & Space(1) & GetExamUnitString(encid, id)
      Else
        xval = ""
      Endif
    Else
      If res!fldrepquali Then

        xType = res["fldoption"]
        If xType = "Clinical Scale" Then
          If modBasic.$ShowScaleMedFormat = "GroupWise" Then
            If Report = True Then
              xval = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
            Else
              xval = Trim(res!fldrepquali)
            Endif
          Else
            xval = CStr(res!fldrepquanti)
          Endif

        Else If xType = "Left and Right" Then
          If Report = True Then
            xval = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
          Else
            xval = Trim(res!fldrepquali)
          Endif

        Else
          xval = Trim(res!fldrepquali)
        Endif

      Else
        xval = ""
      Endif
    Endif

    If xval And If Report = True Then
      xx = modReportVar.GetReportWithAbnormalStatus(xval, res!fldabnormal)
    Else
      xx = xval
    Endif

  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetSubExamQualiList(encid As String, pttestid As Long) As String[]

  Dim res As Result
  Dim xx As String[]
  Dim xquali As String

  xx = New String[]
  res = modDatabase.$myConn.Exec("select fldsubtexam,fldreport,fldtanswertype,fldid,fldheadid from tblpatientsubexam where fldheadid=&1 and fldencounterval=&2", pttestid, encid)
  If res.Available = True Then
    For Each res
      If res!fldtanswertype = "Multiple Selection" Or If res!fldtanswertype = "Single Column" Then
        xquali = gb.NewLine & GetSubExamTableReportString(res!fldheadid, res!fldid)
      Else If res!fldtanswertype = "Text Table" Then
        xquali = gb.NewLine & GetSubExamTableReportString(res!fldheadid, res!fldid)
      Else If res!fldtanswertype = "Dual Columns" Then
        xquali = gb.NewLine & GetSubExamDualTableString(res!fldheadid, res!fldid)
      Else
        xquali = Trim(res!fldreport)
      Endif
      If res!fldsubtexam Then
        xx.Add(res!fldsubtexam & " : " & xquali)
      Endif
    Next
  Endif

  Return xx

End

Public Function GetSubExamTableReportString(testid As Long, subtestid As Long, Optional sHospCode As String) As String

  Dim res As Result
  Dim xx As String[]
  Dim xstr As String
  Dim xval As String

  If sHospCode Then
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2,fldcolm3,fldcolm4 from tblpatexamsubtable where fldexamid=&1 and fldsubexamid=&2 and fldhospcode=&3", testid, subtestid, sHospCode)
  Else
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2,fldcolm3,fldcolm4 from tblpatexamsubtable where fldexamid=&1 and fldsubexamid=&2", testid, subtestid)
  Endif
  xx = New String[]
  If res.Available Then
    For Each res
      xstr = res!fldvariable
      If res!fldvalue Then
        xstr = xstr & " : " & res!fldvalue
      Endif
      If res!fldcolm2 Then
        xstr = xstr & " : " & res!fldcolm2
      Endif
      If res!fldcolm3 Then
        xstr = xstr & " : " & res!fldcolm3
      Endif
      If res!fldcolm4 Then
        xstr = xstr & " : " & res!fldcolm4
      Endif
      xx.Add(xstr)
    Next
    xval = xx.Join(gb.NewLine)
  Else
    xval = ""
  Endif
  Return xval

End

Public Function GetSubExamDualTableString(testid As Long, subtestid As Long, Optional sHospCode As String) As String

  Dim res As Result
  Dim xx As String
  Dim aa As String
  Dim bb As String

  If sHospCode Then
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2 from tblpatexamsubtable where fldexamid=&1 and fldsubexamid=&2 and fldhospcode=&3", testid, subtestid, sHospCode)
  Else
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2 from tblpatexamsubtable where fldexamid=&1 and fldsubexamid=&2", testid, subtestid)
  Endif
  If res.Available Then
    xx = modRepoTemplete.HTMLTableSyntax()
    xx = xx & "<tr>" & gb.NewLine
    xx = xx & "<td class='report_table_h'>PARAMETER</td>" & gb.NewLine
    xx = xx & "<td class='report_table_h'>LEFT</td>" & gb.NewLine
    xx = xx & "<td class='report_table_h'>RIGHT</td>" & gb.NewLine
    xx = xx & "</tr>" & gb.NewLine
    For Each res
      If res!fldvalue Then
        aa = res!fldvalue
      Else
        aa = ""
      Endif
      If res!fldcolm2 Then
        bb = res!fldcolm2
      Else
        bb = ""
      Endif
      xx = xx & "<tr>" & gb.NewLine
      xx = xx & "<td>" & res!fldvariable & "</td>" & gb.NewLine
      xx = xx & "<td>" & aa & "</td>" & gb.NewLine
      xx = xx & "<td>" & bb & "</td>" & gb.NewLine
      xx = xx & "</tr>" & gb.NewLine
    Next
    xx = xx & "</table>" & gb.NewLine
  Else
    xx = ""
  Endif
  Return xx

End

''------------------------------------ EXAM VALUES ALTERATION -------------------------------------------------------------------------

Public Function ExamInterpretByExamID(labid As Long) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String

  sql = "select fldcomment from tblexamcomment where fldexamid=&1 and fldmin<=&2 and fldmax>=&3 and (fldptsex=&4 or fldptsex=&5) and (fldagegroup=&6 or fldagegroup=&7)"
  res = modDatabase.$medConn.Exec(sql, GetExamNameFromExamID(labid), GetExamValueByID(labid), GetExamValueByID(labid), modPatient.GetPatientSex(GetEncidFromExamID(labid)), "Both Sex", modPatient.GetAgeGroupFIxed(GetEncidFromExamID(labid), Now()), "All Age")
  If res.Available = True Then
    If res!fldcomment Then
      xx = res!fldcomment
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetALLReportExamSelString(encid As String, exam As String, sDate As Date) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String
  Dim yy As String[]
  Dim xList As String[]

  xList = New String[]
  sql = "select fldid,fldtime,fldrepquali,fldrepquanti,fldtype from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldsave=&3 and fldinput=&4 and fldtime>=&5 and fldtime<=&6"
  res = modDatabase.$syConn.Exec(sql, encid, exam, True, "Examination", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate))
  If res.Available = True Then
    For Each res

      xx = ""
      If res!fldtype = "Quantitative" Then
        If res!fldrepquanti Then

          xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime) & " ] " & " : " & CStr(res!fldrepquanti) & Space(1) & modClinic.GetExamUnit(exam, encid)
        Else
          xx = ""
        Endif

      Else
        xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime) & " ] " & " : " & Trim(res!fldrepquali)
        yy = modClinic.GetSubExamQualiList(encid, res!fldid)
        If yy.Count Then
          xx = xx & modString.GetHTMLListFormat(yy)
        Endif

      Endif
      xList.Add(xx)

    Next
  Endif
  Return xList

End

'NOTE: --------------------------- Current Exam Values ---------------------------------------
Public Function GetBradyExamList(encid As String) As String[]

  Dim res As Result
  Dim xx As String[]
  Dim xval As Float
  Dim xlimit As Float[]

  xx = New String[]
  res = modDatabase.$myConn.Exec("select distinct(fldhead) as col from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldtype=&3", encid, True, "Quantitative")
  For Each res
    xval = GetCurrExamValueFromID("Last", encid, res!col)
    If xval Then
      xlimit = GetBothQuantiExamVal(res!col, encid)
      If xval < xlimit[0] Then
        xx.Add(res!col)
      Endif
    Endif
  Next
  xx.Sort(gb.Ascent)
  Return xx

End

Public Function GetTachyExamList(encid As String) As String[]

  Dim res As Result
  Dim xx As String[]
  Dim xval As Float
  Dim xlimit As Float[]

  xx = New String[]
  res = modDatabase.$myConn.Exec("select distinct(fldhead) as col from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldtype=&3", encid, True, "Quantitative")
  For Each res
    xval = GetCurrExamValueFromID("Last", encid, res!col)
    If xval Then
      xlimit = GetBothQuantiExamVal(res!col, encid)
      If xval > xlimit[1] Then
        xx.Add(res!col)
      Endif
    Endif
  Next
  xx.Sort(gb.Ascent)
  Return xx

End

Public Function GetCurrExamValueFromID(sPos As String, encid As String, strExam As String) As Float

  Dim sql As String
  Dim res As Result
  Dim xx As Float

  sql = "select fldrepquanti from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldhead=&3"
  res = modDatabase.$myConn.Exec(sql, encid, True, strExam)
  If res.Available = True Then
    If sPos = "First" Then
      res.MoveFirst
    Else
      res.MoveLast
    Endif

    If res!fldrepquanti Then
      xx = res!fldrepquanti
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

''only for last quantitative exam (used in calculation)
Public Function GetCurrExamValueSysConst(encid As String, xSysConst As String, sPos As String) As String

  Dim xx As String
  Dim res As Result
  Dim xType As String

  res = modDatabase.$myConn.Exec("select fldid,fldhead,fldrepquanti,fldrepquali,fldtype from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldhead in(select fldexamid from tblexam where fldsysconst=&3) and fldrepquali IS NOT &4", encid, True, xSysConst, Null)
  If res.Available Then
    If sPos = "First" Then
      res.MoveFirst
    Else
      res.MoveLast
    Endif

    If res["fldtype"] = "Quantitative" Then
      If res!fldrepquanti Then
        xx = CStr(res!fldrepquanti)
      Else
        xx = ""
      Endif
    Else
      If res["fldrepquali"] Then
        xType = modFixClinic.GetExamtOptionType(res["fldhead"])
        If xType = "Clinical Scale" Then
          xx = CStr(res!fldrepquanti)
        Else
          xx = Trim(res!fldrepquali)
        Endif
      Else
        xx = ""
      Endif
    Endif

  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetCurrExamTimeValueSysConst(encid As String, xSysConst As String, sType As String) As String

  Dim xx As String
  Dim res As Result
  Dim xType As String

  res = modDatabase.$myConn.Exec("select fldid,fldhead,fldrepquanti,fldrepquali,fldtype from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldinput=&3 and fldhead in(select fldexamid from tblexam where fldsysconst=&4) and fldrepquali IS NOT &5", encid, True, sType, xSysConst, Null)
  If res.Available Then
    res.MoveLast
    If res["fldtype"] = "Quantitative" Then
      If res!fldrepquanti Then
        xx = CStr(res!fldrepquanti)
      Else
        xx = ""
      Endif
    Else
      If res["fldrepquali"] Then
        xType = modFixClinic.GetExamtOptionType(res["fldhead"])
        If xType = "Clinical Scale" Then
          xx = CStr(res!fldrepquanti)
        Else
          xx = Trim(res!fldrepquali)
        Endif
      Else
        xx = ""
      Endif
    Endif

  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetCurrLeftRightExamValue(encid As String, xSysConst As String, sType As String) As String

  Dim res As Result
  Dim xxx As Variant
  Dim xcoll As JSONCollection
  Dim xval As String

  res = modDatabase.$myConn.Exec("select fldrepquali from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldhead in(select fldexamid from tblexam where fldsysconst=&3 and fldoption=&4) and fldrepquali IS NOT &5", encid, True, xSysConst, "Left and Right", Null)
  If res.Available Then
    res.MoveLast
    If IsNumber(res["fldrepquali"]) Then
      xval = ""
    Else

      Try xxx = JSON.Decode(res["fldrepquali"], True)
      If xxx Then
        If xxx Is JSONCollection Then
          xcoll = xxx
          xval = CStr(xcoll[sType])
        Else
          xval = ""
        Endif
      Else
        xval = ""
      Endif

    Endif
  Else
    xval = ""
  Endif
  Return xval

End

''--------------------------------------- Height
Public Function GetPatientHeightinCm(encid As String) As Float

  Dim sql As String
  Dim res As Result
  Dim wt As Float

  sql = "select fldrepquanti from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldtype=&3 and fldsave=&4"
  res = modDatabase.$myConn.Exec(sql, encid, "Body Height", "Quantitative", True)
  If res.Available = True Then
    res.MoveLast
    If res!fldrepquanti Then
      wt = res!fldrepquanti
    Else
      wt = 0
    Endif
  Else
    wt = 0
  Endif

  Return wt

End

Public Sub GetPatientHeight(encid As String, txtht As ValueBox, cmbunit As ComboBox)

  txtht.Value = GetPatientHeightinCm(encid)
  cmbunit.Text = "cm"

End

''update body height in tblencounter
Public Sub UpdatePatientHeight(encid As String, txtht As Float, unit As String)

  Dim ht As Float

  If unit = "cm" Then
    ht = txtht
  Else If unit = "inch" Then
    ht = txtht * 2.54
  Endif
  modClinic.AddGeneralParametersQuanti(encid, "Body Height", ht)

End

''XXXXXXXXXXXXXXXXX Body weight
Public Function GetBodyWeight(encid As String) As Float

  Dim sql As String
  Dim res As Result
  Dim wt As Float

  sql = "select fldrepquanti from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldtype=&3 and fldsave=&4"
  res = modDatabase.$myConn.Exec(sql, encid, "Body Weight", "Quantitative", True)
  If res.Available = True Then
    res.MoveLast
    If res!fldrepquanti Then
      wt = res!fldrepquanti
    Else
      wt = 0
    Endif
  Else
    wt = 0
  Endif

  Return wt

End

Public Function GetHepaticStatus(encid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldrepquali from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldtype=&3 and fldsave=&4", encid, "Hepatic Status", "Qualitative", True)
  If res.Available = True Then
    res.MoveLast
    If res!fldrepquali Then
      xx = res!fldrepquali
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Sub GetPregnancyStatus(encid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldrepquali from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldtype=&3 and fldsave=&4", encid, "Pregnancy Status", "Qualitative", True)
  If res.Available = True Then
    res.MoveLast
    If res!fldrepquali Then
      xx = res!fldrepquali
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetExamSelFieldType(sField As String) As String[]

  Dim res As Result
  Dim sql As String
  Dim xx As String[]

  sql = Subst("select distinct(&1) as col from tblpatientexam", sField)
  res = modDatabase.$myConn.Exec(sql)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

''--------------------------------------- Chart --------------------------------
''generate chart
Public Sub FillQuantiExamChart(drw As PictureBox, encid As String, strHead As String)

  Dim maxval As Float
  Dim minval As Float
  Dim normval As Float
  Dim sql As String
  Dim rData As Result
  Dim xpath As String
  Dim xlimit As Float[]

  Dim pointsArr_x As Date[]
  Dim pointsArr_y As Float[]

  pointsArr_x = New Date[]
  pointsArr_y = New Float[]

  xlimit = GetBothQuantiExamVal(strHead, encid)
  minval = xlimit[0]
  maxval = xlimit[1]
  normval = GetNormalQuantiExamVal(strHead, encid)

  sql = "select fldrepquanti,fldtime from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldtype=&3 and fldsave=&4"
  rData = modDatabase.$myConn.Exec(sql, encid, strHead, "Quantitative", True)
  If rData.Count Then
    For Each rData
      pointsArr_x.Add(rData!fldtime)
      pointsArr_y.Add(rData!fldrepquanti)
    Next
    xpath = modChart.ClinicalChart(drw.Height, encid, pointsArr_x, pointsArr_y, maxval, minval, normval)
    drw.Picture = Picture.Load(xpath)
  Endif

End

''-----------------------------------------------------------------------------------------------------------
Public Sub DrawClinicalCharts_SetA(drw As PictureBox, encid As String, strItem As String)

  Dim sql As String
  Dim res As Result
  Dim xage As Integer
  Dim xwt As Float
  Dim xht As Float

  Dim pointsArr_x As Float[]
  Dim pointsArr_y As Float[]

  pointsArr_x = New Float[]
  pointsArr_y = New Float[]

  sql = "select fldid,fldtime,fldrepquanti from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldtype=&3 and fldsave=&4"
  res = modDatabase.$myConn.Exec(sql, encid, "Body Weight", "Quantitative", True)
  If res.Available = True Then

    For Each res
      If strItem = "Wt" Then
        pointsArr_x.Add(res!fldtime)
        pointsArr_y.Add(res!fldrepquanti)
      Else If strItem = "Body_Surface_Area" Or strItem = "Ideal_Body_Weight" Or strItem = "Body_Mass_Index" Then
        xage = DateDiff(modPatient.GetPatientBirthDay(encid), res!fldtime, gb.Year)
        xwt = res!fldrepquanti
        xht = GetPatientHeightinCm(encid)
        If xage And If xwt And If xht Then
          pointsArr_x.Add(res!fldtime)
          pointsArr_y.Add(Abs(CFloat(modSysCons.GetCalculationForSetA(strItem, modPatient.GetPatientSex(encid), xage, xwt, xht, "0"))))
        Endif
      Endif
    Next

    If pointsArr_x.Count And If pointsArr_y Then
      drw.Picture = Picture.Load(modChart.ClinicalChart(drw.Height, encid, pointsArr_x, pointsArr_y, 0, 0, 0))
    Endif
  Endif

End
