' Gambas module file

'''----------------------------- Procedures for test ------------------------------------------------------------
Public Sub InsertLabTestOrder(encid As String, strTest As String, strType As String, strMethod As String, grpid As Long, sRefer As String, sBillNo As String, sComment As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatlabtest")
  res["fldencounterval"] = encid
  res["fldtestid"] = strTest
  res["fldmethod"] = strMethod
  res["fldgroupid"] = grpid
  res["fldsampleid"] = ""
  res["fldsampletype"] = ""
  res["fldreportquali"] = ""
  res["fldreportquanti"] = 0
  res["fldfilepath"] = ""
  res["fldstatus"] = "Ordered"
  res["fldprint"] = False
  res["fldabnormal"] = False
  res["xyz"] = False
  res["fldrefername"] = sRefer
  res["fldcondition"] = ""
  res["fldcomment"] = sComment
  res["fldbillno"] = sBillNo
  res["flvisible"] = "Visible"

  res["fldtestunit"] = ""
  res["fldtest_type"] = strType
  res["fldchk"] = False
  res["fldorder"] = 0

  res["flduserid_sample"] = ""
  res["fldtime_sample"] = ""
  res["fldcomp_sample"] = modGeneralMain.compID
  res["fldsave_sample"] = False
  res["flduptime_sample"] = ""

  res["flduserid_start"] = ""
  res["fldtime_start"] = ""
  res["fldcomp_start"] = ""
  res["fldsave_start"] = False
  res["flduptime_start"] = ""

  res["flduserid_report"] = ""
  res["fldtime_report"] = ""
  res["fldcomp_report"] = ""
  res["fldsave_report"] = False
  res["flduptime_report"] = ""

  res["flduserid_verify"] = ""
  res["fldtime_verify"] = ""
  res["fldcomp_verify"] = ""
  res["fldsave_verify"] = False
  res["flduptime_verify"] = ""

  res.Update()
  'don't catch error

End

Public Sub UpdateLabTestSample(id As Long, sampleID As String, strTampleType As String, strRefer As String, strCondi As String, strComment As String, sBillNo As String, Optional sDate As Date)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldsampleid"] = sampleID
  res["fldsampletype"] = strTampleType
  res["fldstatus"] = "Sampled"
  If strRefer Then
    res["fldrefername"] = strRefer
  Endif
  If strCondi Then
    res["fldcondition"] = strCondi
  Endif
  If strComment Then
    res["fldcomment"] = strComment
  Endif
  If sBillNo Then
    res["fldbillno"] = sBillNo
  Endif

  res["flduserid_sample"] = modGeneralMain.$lbluser
  If sDate Then
    res["fldtime_sample"] = sDate
    res["flduptime_sample"] = Now()
  Else
    If res!fldtime_sample Then
      res["flduptime_sample"] = Now()
    Else
      res["fldtime_sample"] = Now()
    Endif
  Endif
  res["fldcomp_sample"] = modGeneralMain.compID
  res["fldsave_sample"] = True
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub InsertLabSubTest(encid As String, pttestid As Long, subtestList As String[])

  Dim res2 As Result
  Dim xx As String

  For Each xx In subtestList
    res2 = modDatabase.$myConn.Create("tblpatlabsubtest")
    res2["fldencounterval"] = encid
    res2["fldtestid"] = pttestid
    res2["fldsubtest"] = xx
    res2["fldtanswertype"] = modFixLab.GetSubTestOption(GetTestnameFromTestID(pttestid), xx)
    res2["fldreport"] = ""
    res2["fldsave"] = False
    res2["fldabnormal"] = False
    res2["fldchk"] = False
    res2["fldorder"] = 0
    res2["fldfilepath"] = ""
    res2["xyz"] = False
    res2.Update()
  Next
  'don't catch error

End

Public Sub UpdateLabTestReportQuali(id As Long, strReport As String, abn As Boolean, Optional KeyList As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldreportquali"] = strReport
  If IsFloat(strReport) = True Then
    res["fldreportquanti"] = CFloat(strReport)
  Else
    res["fldreportquanti"] = 0
  Endif
  If KeyList Then
    res["fldfilepath"] = KeyList
  Endif
  res["fldstatus"] = "Reported"
  res["flduserid_report"] = modGeneralMain.$lbluser
  If res!fldtime_report Then
    res["flduptime_report"] = Now()
  Else
    res["fldtime_report"] = Now()
  Endif
  res["fldcomp_report"] = modGeneralMain.compID
  res["fldsave_report"] = True
  res["fldabnormal"] = abn
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateLabTestReportQuanti(id As Long, strReport As Float, abn As Boolean, strUnit As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldreportquali"] = CStr(strReport)
  res["fldreportquanti"] = strReport
  res["fldstatus"] = "Reported"
  res["flduserid_report"] = modGeneralMain.$lbluser
  If res!fldtime_report Then
    res["flduptime_report"] = Now()
  Else
    res["fldtime_report"] = Now()
  Endif
  res["fldcomp_report"] = modGeneralMain.compID
  res["fldsave_report"] = True
  res["fldabnormal"] = abn
  res["fldtestunit"] = strUnit
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateLabQualiQuanti(id As Long, strReport As String, strValue As Float, abn As Boolean, Optional KeyList As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldreportquali"] = strReport
  res["fldreportquanti"] = strValue
  If KeyList Then
    res["fldfilepath"] = KeyList
  Endif
  res["fldstatus"] = "Reported"
  res["flduserid_report"] = modGeneralMain.$lbluser
  If res!fldtime_report Then
    res["flduptime_report"] = Now()
  Else
    res["fldtime_report"] = Now()
  Endif
  res["fldcomp_report"] = modGeneralMain.compID
  res["fldsave_report"] = True
  res["fldabnormal"] = abn
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateVerifyTestReport(id As Long)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldstatus"] = "Verified"
  res["flduserid_verify"] = modGeneralMain.$lbluser
  If res["fldtime_verify"] Then
    res["flduptime_verify"] = Now()
  Else
    res["fldtime_verify"] = Now()
  Endif
  res["fldcomp_verify"] = modGeneralMain.compID
  res["fldsave_verify"] = True
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub CancelVerifyTestReport(id As Long)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldstatus"] = "Reported"
  res["flduserid_verify"] = modGeneralMain.$lbluser
  If res["fldtime_verify"] Then
    res["flduptime_verify"] = Now()
  Else
    res["fldtime_verify"] = Now()
  Endif
  res["fldcomp_verify"] = modGeneralMain.compID
  res["fldsave_verify"] = True
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub MarkAsChecked(id As Long)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["flduserid_verify"] = modGeneralMain.$lbluser
  If res["fldtime_verify"] Then
    res["flduptime_verify"] = Now()
  Else
    res["fldtime_verify"] = Now()
  Endif
  res["fldcomp_verify"] = modGeneralMain.compID
  res["fldsave_verify"] = True
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateEquipmentMethod(id As Long, sMethod As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldmethod"] = sMethod
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateSpecimenTest(id As Long, specimen As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldsampletype"] = specimen
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateConditionTest(id As Long, condition As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldcondition"] = condition
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateLabTestOrder(id As Long, sOrder As Integer)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabtest", "fldid=&1", id)
  res["fldorder"] = sOrder
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub UpdateLabSubTestOrder(id As Long, sOrder As Integer)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatlabsubtest", "fldid=&1", id)
  res["fldorder"] = sOrder
  res["xyz"] = False
  res.Update
  'don't catch error

End

'NOTE: -------------------------------- LAB SETTINGS ---------------------------------------
Public Sub DisplayDefaultTestUnit(rbSI As Radiobutton, rbMetric As Radiobutton)

  Dim def As String

  def = modSettings.ShowSettingFromFIle("TestUnit/Default")
  If def Then
    If def = "SI" Then
      rbSI.Value = True
    Else If def = "Metric" Then
      rbMetric.Value = True
    Endif
  Else
    rbMetric.Value = True
  Endif

End

Public Function GetTestUnitFromButton(rbsi As RadioButton, rbmetric As RadioButton) As String

  Dim unt As String

  If rbsi.Value = True Then
    unt = "SI"
  Else If rbmetric.Value = True Then
    unt = "Metric"
  Else
    unt = "Metric"
  Endif
  Return unt

End

Public Function GetAutoIncreasingNo() As String

  Dim xsampauto As String
  Dim xprefix As String

  xprefix = modBasic.$LabSamplePrefix
  If modBasic.$LabAutoSampNo = "Yes" Then
    xsampauto = xprefix & CStr(modNonMedical.CurrentLabNo())
  Else
    xsampauto = xprefix
  Endif
  Return xsampauto

End

Public Function ListFooterNoteList() As String[]

  Dim i As Integer
  Dim xx As String
  Dim xval As String[]

  xval = New String[]
  For i = 1 To 50
    xx = modSettings.ShowSettingFromFIle("FooterNote/Name_" & CStr(i))
    If xx Then
      xval.Add(xx)
    Endif
  Next
  Return xval

End

''------------------------------------- Procedure by patient ----------------------------------------------------------
Public Function PaientAllTestNameArray(encid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select distinct(fldtestid) as col from tblpatlabtest where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3)", encid, "Reported", "Verified")
  xx = modFillContainer.GetListFromResult(res)

  Return xx.Sort()

End

Public Sub GetQualiTestListByPatient(encid As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]

  sql = "select distinct(fldtestid) as col from tblpatlabtest where fldencounterval=&1 and fldtest_type=&2 and flvisible=&3 and (fldstatus=&4 or fldstatus=&5)"
  res = modDatabase.$myConn.Exec(sql, encid, "Qualitative", "Visible", "Reported", "Verified")
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Sub GetQuantiTestListByPatient(encid As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]

  sql = "select distinct(fldtestid) as col from tblpatlabtest where fldencounterval=&1 and fldtest_type=&2 and flvisible=&3 and (fldstatus=&4 or fldstatus=&5)"
  res = modDatabase.$myConn.Exec(sql, encid, "Quantitative", "Visible", "Reported", "Verified")
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function AllowSampleID(encid As String, sLabNo As String) As Boolean

  Dim res As Result
  Dim xval As Boolean

  res = modDatabase.$myConn.Exec("select distinct(fldencounterval) as col from tblpatlabtest where fldsampleid=&1", sLabNo)
  If res.Available Then
    res.MoveLast
    If res!col = encid Then
      xval = True
    Else
      xval = False
    Endif
  Else
    xval = True
  Endif
  Return xval

End

Public Function GetSampleTimeFromLabID(id As Long) As Date

  Dim res As Result
  Dim xx As Date

  res = modDatabase.$myConn.Exec("select fldtime_sample from tblpatlabtest where fldid=&1", id)
  If res.Available Then
    If res!fldtime_sample Then
      xx = res!fldtime_sample
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetEncIDFromLabID(id As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldencounterval from tblpatlabtest where fldid=&1", id)
  If res.Available Then
    If res!fldencounterval Then
      xx = res!fldencounterval
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetSampSpecimenFromLabID(id As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldsampletype from tblpatlabtest where fldid=&1", id)
  If res.Available Then
    If res!fldsampletype Then
      xx = res!fldsampletype
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetTestnameFromTestID(id As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldtestid from tblpatlabtest where fldid=&1", id)
  If res.Available Then
    If res!fldtestid Then
      xx = res!fldtestid
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetTestMethodLabID(id As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldmethod from tblpatlabtest where fldid=&1", id)
  If res.Available Then
    If res!fldmethod Then
      xx = res!fldmethod
      If xx = "Regular" Then
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetEncounterFromLabSerial(txtserial As Long) As String

  Dim encid As String

  encid = modPatient.GetPatientEncFromID("tblpatlabtest", txtserial)
  Return encid

End

Public Function GetEncounterFromSampleID(txtsampleid As String) As String

  Dim res As Result
  Dim encid As String

  res = modDatabase.$myConn.Exec("select fldencounterval from tblpatlabtest where fldsampleid=&1", txtsampleid)
  If res.Available = True Then
    res.MoveLast
    If res!fldencounterval Then
      encid = res!fldencounterval
    Else
      encid = 0
    Endif
  Endif

  Return encid

End

''------------------------------------------------- TEST FIXED VALUES  for Quanti Test--------------------------------------------------------------
Public Function LabBothLimitValue(strTest As String, encid As String, strUnit As String, Optional sMethod As String) As Float[]

  Dim ssl As String
  Dim rs As Result
  Dim LowerLimit As Float
  Dim UpperLimit As Float
  Dim sqstr As String
  Dim xval As Float[]

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  If strUnit = "Metric" Then
    ssl = "select fldmetlow as low,fldmethigh as high from tbltestlimit where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  Else If strUnit = "SI" Then
    ssl = "select fldsilow as low,fldsihigh as high from tbltestlimit where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  Endif
  rs = modDatabase.$medConn.Exec(ssl, strTest, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)
  If rs.Available = True Then
    rs.MoveFirst
    If rs!low Then
      LowerLimit = rs!low
    Else
      LowerLimit = 0
    Endif
    If rs!high Then
      UpperLimit = rs!high
    Else
      UpperLimit = 0
    Endif
  Else
    LowerLimit = 0
    UpperLimit = 0
  Endif

  xval = [LowerLimit, UpperLimit]
  Return xval

End

Public Function GetTestBothLimits(id As Long, strUnit As String) As Float[]

  Dim res As Result
  Dim sql As String
  Dim LwLimit As Float
  Dim UpLimit As Float
  Dim xlimit As Float[]
  Dim xval As Float[]

  sql = "select fldencounterval,fldtestid,fldmethod from tblpatlabtest where fldid=&1 and fldtest_type=&2"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative")
  If res.Available = True Then
    If res!fldmethod Then
      xlimit = LabBothLimitValue(res!fldtestid, res!fldencounterval, strUnit, res!fldmethod)
      LwLimit = xlimit[0]
      UpLimit = xlimit[1]
    Else
      xlimit = LabBothLimitValue(res!fldtestid, res!fldencounterval, strUnit)
      LwLimit = xlimit[0]
      UpLimit = xlimit[1]
    Endif
  Else
    LwLimit = 0
    UpLimit = 0
  Endif

  xval = [LwLimit, UpLimit]
  Return xval

End

Public Function GetTestLimitSrting(id As Long, strUnit As String) As String

  Dim xx As String
  Dim res As Result
  Dim sql As String
  Dim xmax As Float
  Dim xmin As Float
  Dim xlimit As Float[]

  sql = "select fldencounterval,fldtest_type from tblpatlabtest where fldid=&1"
  res = modDatabase.$myConn.Exec(sql, id)
  If res!fldtest_type = "Quantitative" Then
    xlimit = GetTestBothLimits(id, strUnit)
    xmin = xlimit[0]
    xmax = xlimit[1]

    If xmin < xmax Then
      xx = CStr(xmin) & "  -  " & CStr(xmax) & Space(1) & GetTestLabUnit(res!fldencounterval, id, strUnit)
    Else
      xx = ""
    Endif
  Else
    xx = modFixLab.GetLabQualiTestTextReference(GetTestnameFromTestID(id))   ''only for text reference
  Endif

  Return xx

End

Public Function LabNormalValue(strTest As String, encid As String, strUnit As String, Optional sMethod As String) As Float

  Dim ssl As String
  Dim rs As Result
  Dim NormalLimit As Float
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  If strUnit = "Metric" Then
    ssl = "select fldmetnormal as normal from tbltestlimit where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  Else If strUnit = "SI" Then
    ssl = "select fldsinormal as normal from tbltestlimit where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  Endif
  rs = modDatabase.$medConn.Exec(ssl, strTest, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)
  If rs.Available = True Then
    rs.MoveFirst
    If rs!normal Then
      NormalLimit = rs!normal
    Else
      NormalLimit = 0
    Endif
  Else
    NormalLimit = 0
  Endif

  Return NormalLimit

End

Private Function LabConversionValue(strTest As String, encid As String, Optional sMethod As String) As Float

  Dim ssl As String
  Dim rs As Result
  Dim ConvFactor As Float
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  ssl = "select fldconvfactor as conv from tbltestlimit where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  rs = modDatabase.$medConn.Exec(ssl, strTest, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)
  If rs.Available = True Then
    rs.MoveFirst
    If rs!conv Then
      ConvFactor = rs!conv
    Else
      ConvFactor = 1
    Endif
  Else
    ConvFactor = 1
  Endif

  Return ConvFactor

End

Private Function GetTestConversionFactor(id As Long, encid As String) As Float

  Dim res As Result
  Dim sql As String
  Dim ConvFact As Float

  sql = "select fldencounterval,fldtestid,fldmethod from tblpatlabtest where fldid=&1 and fldtest_type=&2 and fldencounterval=&3"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative", encid)
  If res.Available = True Then
    If res!fldmethod Then
      ConvFact = LabConversionValue(res!fldtestid, res!fldencounterval, res!fldmethod)
    Else
      ConvFact = LabConversionValue(res!fldtestid, res!fldencounterval)
    Endif
  Else
    ConvFact = 1
  Endif

  Return ConvFact

End

Public Function LabTestUnit(strTest As String, encid As String, strUnit As String, Optional sMethod As String) As String

  Dim ssl As String
  Dim rs As Result
  Dim LabUnit As String
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  If strUnit = "Metric" Then
    ssl = "select fldmetunit as unit from tbltestlimit where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  Else If strUnit = "SI" Then
    ssl = "select fldsiunit as unit from tbltestlimit where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  Endif
  rs = modDatabase.$medConn.Exec(ssl, strTest, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)
  If rs.Available = True Then
    rs.MoveFirst
    If rs!unit Then
      LabUnit = rs!unit
    Else
      LabUnit = ""
    Endif
  Else
    LabUnit = ""
  Endif

  Return LabUnit

End

Public Function GetTestLabUnit(encid As String, id As Long, strUnit As String) As String

  Dim res As Result
  Dim sql As String
  Dim LabUnit As String

  sql = "select fldencounterval,fldtestid,fldmethod from tblpatlabtest where fldid=&1 and fldtest_type=&2 and fldencounterval=&3"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative", encid)
  If res.Available = True Then
    If res!fldmethod Then
      LabUnit = LabTestUnit(res!fldtestid, res!fldencounterval, strUnit, res!fldmethod)
    Else
      LabUnit = LabTestUnit(res!fldtestid, res!fldencounterval, strUnit)
    Endif
  Else
    LabUnit = ""
  Endif

  Return LabUnit

End

Private Function GetLabAcceptableRange(strTest As String, encid As String, strUnit As String, Optional sMethod As String) As Float[]

  Dim ssl As String
  Dim rs As Result
  Dim LowerLimit As Float
  Dim UpperLimit As Float
  Dim sqstr As String
  Dim xval As Float[]
  Dim xconv As Float

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  ssl = "select fldminimum,fldmaximum from tbltestlimit where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  rs = modDatabase.$medConn.Exec(ssl, strTest, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)
  If rs.Available = True Then
    rs.MoveFirst
    If rs!fldminimum Then
      LowerLimit = rs!fldminimum
    Else
      LowerLimit = 0
    Endif
    If rs!fldmaximum Then
      UpperLimit = rs!fldmaximum
    Else
      UpperLimit = 0
    Endif
  Else
    LowerLimit = 0
    UpperLimit = 0
  Endif

  If strUnit = "Metric" Then
    xval = [LowerLimit, UpperLimit]
  Else If strUnit = "SI" Then
    If sMethod Then
      xconv = LabConversionValue(strTest, encid, sMethod)
    Else
      xconv = LabConversionValue(strTest, encid)
    Endif
    xval = [LowerLimit * xconv, UpperLimit * xconv]
  Endif
  Return xval

End

Public Function GetLabAcceptableLimits(id As Long, strUnit As String) As Float[]

  Dim res As Result
  Dim sql As String
  Dim LwLimit As Float
  Dim UpLimit As Float
  Dim xlimit As Float[]
  Dim xval As Float[]

  sql = "select fldencounterval,fldtestid,fldmethod from tblpatlabtest where fldid=&1 and fldtest_type=&2"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative")
  If res.Available = True Then
    If res!fldmethod Then
      xlimit = GetLabAcceptableRange(res!fldtestid, res!fldencounterval, strUnit, res!fldmethod)
      LwLimit = xlimit[0]
      UpLimit = xlimit[1]
    Else
      xlimit = GetLabAcceptableRange(res!fldtestid, res!fldencounterval, strUnit)
      LwLimit = xlimit[0]
      UpLimit = xlimit[1]
    Endif
  Else
    LwLimit = 0
    UpLimit = 0
  Endif

  xval = [LwLimit, UpLimit]
  Return xval

End

Private Function LabQuantiTableValue(sField As String, strTest As String, encid As String, Optional sMethod As String) As Float

  Dim ssl As String
  Dim rs As Result
  Dim svalue As Float
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  ssl = Subst("select &1 as fld from tbltestlimit", sField) & " where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  rs = modDatabase.$medConn.Exec(ssl, strTest, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)
  If rs.Available = True Then
    rs.MoveFirst
    If rs!fld Then
      svalue = rs!fld
    Else
      svalue = 0
    Endif
  Else
    svalue = 0
  Endif

  If svalue = 0 Then
    svalue = modFixLab.LabFieldValue(sField, strTest)
  Endif

  Return svalue

End

Public Function GetTestSensiSpecArray(id As Long) As Float[]

  Dim xxx As Float[]
  Dim res As Result
  Dim sql As String

  xxx = New Float[]
  sql = "select fldencounterval,fldtestid,fldmethod,fldtest_type from tblpatlabtest where fldid=&1"
  res = modDatabase.$myConn.Exec(sql, id)
  If res.Available Then
    If res!fldtest_type = "Quantitative" Then
      If res!fldmethod Then
        xxx.Add(LabQuantiTableValue("fldsensitivity", res!fldtestid, res!fldencounterval, res!fldmethod))
        xxx.Add(LabQuantiTableValue("fldspecificity", res!fldtestid, res!fldencounterval, res!fldmethod))
      Else
        xxx.Add(LabQuantiTableValue("fldsensitivity", res!fldtestid, res!fldencounterval))
        xxx.Add(LabQuantiTableValue("fldspecificity", res!fldtestid, res!fldencounterval))
      Endif

    Else
      xxx.Add(modFixLab.LabFieldValue("fldsensitivity", res!fldtestid))
      xxx.Add(modFixLab.LabFieldValue("fldspecificity", res!fldtestid))

    Endif
  Endif

  Return xxx

End

''------------------------------------ OBSERVATIONS -----------------------------------
Public Function GetTestQuantiValue(encid As String, id As Long, strUnit As String) As Float

  Dim res As Result
  Dim sql As String
  Dim confact As Float
  Dim LabVal As Float

  sql = "select fldencounterval,fldreportquanti,fldtestunit from tblpatlabtest where fldid=&1 and fldencounterval=&2"
  res = modDatabase.$myConn.Exec(sql, id, encid)
  If res.Available = True Then

    If strUnit = "Metric" Then
      If res!fldtestunit = "Metric" Then
        LabVal = res!fldreportquanti
      Else If res!fldtestunit = "SI" Then
        confact = GetTestConversionFactor(id, res!fldencounterval)
        If confact = 0 Then
          confact = 1
        Endif
        LabVal = Round(res!fldreportquanti / confact, -3)
      Endif

    Else If strUnit = "SI" Then
      If res!fldtestunit = "Metric" Then
        confact = GetTestConversionFactor(id, res!fldencounterval)
        If confact = 0 Then
          confact = 1
        Endif
        LabVal = Round(res!fldreportquanti * confact, -3)
      Else If res!fldtestunit = "SI" Then
        LabVal = res!fldreportquanti
      Endif

    Endif

  Else
    LabVal = 0
  Endif
  Return LabVal

End

Public Function GetLabTestValueString(encid As String, id As Long, strUnit As String, Report As Boolean) As String

  Dim xx As String
  Dim res As Result
  Dim sql As String
  Dim xval As String
  Dim xlab As Float
  Dim xType As String

  sql = "select fldencounterval,fldtestid,fldreportquali,fldreportquanti,fldtest_type,fldabnormal from tblpatlabtest where fldid=&1 and fldencounterval=&2"
  res = modDatabase.$myConn.Exec(sql, id, encid)
  If res.Available = True Then
    If res!fldtest_type = "Quantitative" Then
      xlab = GetTestQuantiValue(res!fldencounterval, id, strUnit)
      If xlab Then
        xval = modReportVar.GetLocaleNumberFormat(xlab, 0) & Space(1) & GetTestLabUnit(res!fldencounterval, id, strUnit)
      Else
        xval = ""
      Endif
    Else
      If res!fldreportquali Then

        xType = modExamOption.GetVariableOptionType("Test", res["fldtestid"])
        If xType = "Clinical Scale" Then
          If modBasic.$ShowScaleMedFormat = "GroupWise" Then
            If Report = True Then
              xval = modString.GetJSONToDualHTMLTable(Trim(res!fldreportquali))
            Else
              xval = Trim(res!fldreportquali)
            Endif
          Else
            xval = CStr(res!fldreportquanti)
          Endif

        Else If xType = "Left and Right" Then
          If Report = True Then
            xval = modString.GetJSONToDualHTMLTable(Trim(res!fldreportquali))
          Else
            xval = Trim(res!fldreportquali)
          Endif

        Else
          xval = Trim(res!fldreportquali)
        Endif

      Else
        xval = ""
      Endif
    Endif

    If xval And If Report = True Then
      xx = modReportVar.GetReportWithAbnormalStatus(xval, res!fldabnormal)
    Else
      xx = xval
    Endif

  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetLabTestValueGridString(id As Long, strUnit As String, flag As Boolean) As String

  Dim xx As String
  Dim xval As Float
  Dim newval As String
  Dim res As Result
  Dim sql As String
  Dim accval As Float[]
  Dim astr As String
  Dim xType As String

  sql = "select fldencounterval,fldtestid,fldreportquali,fldreportquanti,fldtest_type,fldabnormal from tblpatlabtest where fldid=&1"
  res = modDatabase.$myConn.Exec(sql, id)
  If res.Available = True Then
    If res!fldtest_type = "Quantitative" Then
      xval = GetTestQuantiValue(res!fldencounterval, id, strUnit)
      If xval Then
        newval = modReportVar.GetLocaleNumberFormat(xval, 0)
        accval = GetLabAcceptableLimits(id, strUnit)
        If accval Then
          If accval[0] Then
            If xval And If xval < accval[0] Then
              newval = "&lt;" & modString.HTMLBlankSpace(1) & modReportVar.GetLocaleNumberFormat(accval[0], 0)
            Endif
          Endif
          If accval[1] Then
            If xval > accval[1] Then
              newval = "&gt;" & modString.HTMLBlankSpace(1) & modReportVar.GetLocaleNumberFormat(accval[1], 0)
            Endif
          Endif
        Endif
        xx = newval & Space(1) & GetTestLabUnit(res!fldencounterval, id, strUnit)
      Else
        newval = modReportVar.GetLocaleNumberFormat(xval, 0)
        xx = newval & Space(1) & GetTestLabUnit(res!fldencounterval, id, strUnit)
      Endif
    Else
      If res!fldreportquali Then
        xType = modExamOption.GetVariableOptionType("Test", res["fldtestid"])
        If xType = "Clinical Scale" Then
          If modBasic.$ShowScaleMedFormat = "GroupWise" Then
            xx = modString.GetJSONToDualHTMLTable(Trim(res!fldreportquali))
          Else
            xx = res!fldreportquanti
          Endif
        Else If xType = "Left and Right" Then
          xx = modString.GetJSONToDualHTMLTable(Trim(res!fldreportquali))
        Else
          xx = Trim(res!fldreportquali)
        Endif
      Else
        xx = ""
      Endif
    Endif

    If xx And If flag = True Then
      astr = modReportVar.GetReportWithAbnormalStatus(xx, res!fldabnormal)
    Else
      astr = xx
    Endif

  Else
    astr = ""
  Endif

  Return astr

End

Public Function GetLabTestValueSubString(id As Variant, strUnit As String) As Variant

  Dim res As Result
  Dim res1 As Result
  Dim sql As String
  Dim xx As Variant
  Dim xquali As String
  Dim xType As String

  sql = "select fldid,fldencounterval,fldtestid,fldreportquali,fldreportquanti,fldtest_type,fldabnormal from tblpatlabtest where fldid=&1"

  res = modDatabase.$myConn.Exec(sql, id)
  If res.Available = True Then
    If res!fldtest_type = "Quantitative" Then
      xx = GetTestQuantiValue(res!fldencounterval, res!fldid, strUnit)
    Else
      If res!fldreportquali Then
        xType = modExamOption.GetVariableOptionType("Test", res["fldtestid"])
        If xType = "Clinical Scale" Then
          If modBasic.$ShowScaleMedFormat = "GroupWise" Then
            xx = modString.GetJSONToDualHTMLTable(Trim(res!fldreportquali))
          Else
            xx = res!fldreportquanti
          Endif
        Else If xType = "Left and Right" Then
          xx = modString.GetJSONToDualHTMLTable(Trim(res!fldreportquali))
        Else
          xx = Trim(res!fldreportquali)
        Endif
      Else
        xx = ""
      Endif

      res1 = modDatabase.$myConn.Exec("select fldsubtest,fldreport,fldid,fldtestid,fldtanswertype from tblpatlabsubtest where fldtestid=&1 and fldencounterval=&2", res!fldid, res!fldencounterval)
      If res1.Available = True Then
        xquali = ""
        For Each res1
          If res1!fldtanswertype = "Multiple Selection" Or If res1!fldtanswertype = "Single Column" Then
            xquali = xquali & res1!fldsubtest & " : " & gb.NewLine & GetSubTestTableReportString(res1!fldtestid, res1!fldid, False) & gb.NewLine & gb.NewLine
          Else If res1!fldtanswertype = "Drug Sensitivity" Then
            xquali = xquali & res1!fldsubtest & " : " & gb.NewLine & GetSubSensiTableReportString(res1!fldtanswertype, res1!fldtestid, res1!fldid, False) & gb.NewLine & gb.NewLine
          Else If res1!fldtanswertype = "Text Table" Then
            xquali = xquali & res1!fldsubtest & " : " & gb.NewLine & GetSubTestTableReportString(res1!fldtestid, res1!fldid, False) & gb.NewLine & gb.NewLine
          Else If res1!fldtanswertype = "Dual Columns" Then
            xquali = xquali & res1!fldsubtest & " : " & gb.NewLine & GetSubTestDualTableString(res1!fldtestid, res1!fldid, False) & gb.NewLine & gb.NewLine
          Else
            If res1!fldreport Then
              xquali = xquali & res1!fldsubtest & " : " & res1!fldreport & gb.NewLine
            Endif
          Endif
        Next
        xx = xx & gb.NewLine & xquali
      Endif

    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetLabSubTestQuali(encid As String, pttestid As Long) As String[]

  Dim res As Result
  Dim xx As String[]
  Dim xquali As String

  xx = New String[]
  res = modDatabase.$myConn.Exec("select fldsubtest,fldreport,fldid,fldtestid,fldtanswertype from tblpatlabsubtest where fldtestid=&1 and fldsave=&2 and fldencounterval=&3", pttestid, True, encid)
  If res.Available = True Then
    For Each res
      If res!fldtanswertype = "Multiple Selection" Or If res!fldtanswertype = "Single Column" Then
        xquali = gb.NewLine & GetSubTestTableReportString(res!fldtestid, res!fldid, False)
      Else If res!fldtanswertype = "Drug Sensitivity" Then
        xquali = gb.NewLine & GetSubSensiTableReportString(res!fldtanswertype, res!fldtestid, res!fldid, False)
      Else If res!fldtanswertype = "Text Table" Then
        xquali = gb.NewLine & GetSubTestTableReportString(res!fldtestid, res!fldid, False)
      Else If res!fldtanswertype = "Dual Columns" Then
        xquali = gb.NewLine & GetSubTestDualTableString(res!fldtestid, res!fldid, False)
      Else
        xquali = Trim(res!fldreport)
      Endif
      If res!fldsubtest Then
        xx.Add(res!fldsubtest & " : " & xquali)
      Endif
    Next
  Endif

  Return xx

End

Public Function GetSubSensiTableReportString(sType As String, testid As Long, subtestid As Long, sTable As Boolean, Optional sHospCode As String) As String

  Dim res As Result
  Dim xx As String[]
  Dim xstr As String[]
  Dim xval As String

  Dim aa As String[]
  Dim bb As String[]

  Dim arDisk As String[]
  Dim arMIC As String[]
  Dim arETest As String[]
  Dim arBiology As String[]
  Dim bsx As String
  Dim asx As String
  Dim alst As String[]

  If sHospCode Then
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2 from tblpatlabsubtable where fldtestid=&1 and fldsubtestid=&2 and fldvalue<>&3 and fldhospcode=&4 ORDER BY fldcolm2 DESC", testid, subtestid, "Cancelled", sHospCode)
  Else
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2 from tblpatlabsubtable where fldtestid=&1 and fldsubtestid=&2 and fldvalue<>&3 ORDER BY fldcolm2 DESC", testid, subtestid, "Cancelled")
  Endif
  If res.Available = False Then
    xval = ""
  Else

    If sTable = True Then
      aa = New String[]
      bb = New String[]
      If res.Available Then
        For Each res
          If res!fldvariable Then
            aa.Add(res!fldvariable)
            If res!fldvalue Then
              bb.Add(res!fldvalue)
            Else
              bb.Add("")
            Endif
          Endif
        Next
      Endif
      xval = modString.GetDualTableFormat(["", ""], aa, bb)
    Else
      xx = New String[]
      If res.Available Then
        For Each res
          xstr = New String[]
          xstr.Add(res!fldvariable)
          If res!fldvalue Then
            xstr.Add(res!fldvalue)
          Endif
          xx.Add(xstr.Join(" : "))
        Next
      Endif
      xval = xx.Join(gb.NewLine)
    Endif

  Endif

  Return xval

End

Public Function GetSubTestTableReportString(testid As Long, subtestid As Long, sTable As Boolean, Optional sHospCode As String) As String

  Dim res As Result
  Dim xx As String[]
  Dim xstr As String[]
  Dim xval As String

  If sHospCode Then
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2,fldcolm3,fldcolm4 from tblpatlabsubtable where fldtestid=&1 and fldsubtestid=&2 and fldvalue<>&3 and fldhospcode=&4", testid, subtestid, "Cancelled", sHospCode)
  Else
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2,fldcolm3,fldcolm4 from tblpatlabsubtable where fldtestid=&1 and fldsubtestid=&2 and fldvalue<>&3", testid, subtestid, "Cancelled")
  Endif
  If res.Available Then
    If sTable = True Then
      xval = modRepoTemplete.HTMLTableSyntax()
      For Each res
        xval = xval & "<tr>" & gb.NewLine

        xstr = New String[]
        xstr.Add("<td>" & res!fldvariable & "</td>" & gb.NewLine)
        If res!fldvalue Then
          xstr.Add("<td>" & res!fldvalue & "</td>" & gb.NewLine)
        Else
          xstr.Add("<td>" & "</td>" & gb.NewLine)
        Endif
        If res!fldcolm2 Then
          xstr.Add("<td>" & res!fldcolm2 & "</td>" & gb.NewLine)
        Else
          xstr.Add("<td>" & "</td>" & gb.NewLine)
        Endif
        If res!fldcolm3 Then
          xstr.Add("<td>" & res!fldcolm3 & "</td>" & gb.NewLine)
        Else
          xstr.Add("<td>" & "</td>" & gb.NewLine)
        Endif
        If res!fldcolm4 Then
          xstr.Add("<td>" & res!fldcolm4 & "</td>" & gb.NewLine)
        Else
          xstr.Add("<td>" & "</td>" & gb.NewLine)
        Endif
        xval = xval & xstr.Join(gb.NewLine)

        xval = xval & "</tr>" & gb.NewLine
      Next
      xval = xval & "</table>" & gb.NewLine

    Else
      xx = New String[]
      For Each res
        xstr = New String[]
        xstr.Add(res!fldvariable)
        If res!fldvalue Then
          xstr.Add(res!fldvalue)
        Endif
        If res!fldcolm2 Then
          xstr.Add(res!fldcolm2)
        Endif
        If res!fldcolm3 Then
          xstr.Add(res!fldcolm3)
        Endif
        If res!fldcolm4 Then
          xstr.Add(res!fldcolm4)
        Endif
        xx.Add(xstr.Join(" : "))
      Next
      xval = xx.Join(gb.NewLine)

    Endif
  Else
    xval = ""
  Endif
  Return xval

End

Public Function GetSubTestDualTableString(testid As Long, subtestid As Long, sTable As Boolean, sHospCode As String) As String

  Dim res As Result
  Dim xx As String
  Dim aa As String
  Dim bb As String

  If sHospCode Then
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2 from tblpatlabsubtable where fldtestid=&1 and fldsubtestid=&2 and fldvalue<>&3 and fldhospcode=&4", testid, subtestid, "Cancelled", sHospCode)
  Else
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2 from tblpatlabsubtable where fldtestid=&1 and fldsubtestid=&2 and fldvalue<>&3", testid, subtestid, "Cancelled")
  Endif
  If res.Available Then
    If sTable = True Then
      xx = modRepoTemplete.HTMLTableSyntax()
      xx = xx & "<tr>" & gb.NewLine
      xx = xx & "<td class='report_table_h'>PARAMETER</td>" & gb.NewLine
      xx = xx & "<td class='report_table_h'>LEFT</td>" & gb.NewLine
      xx = xx & "<td class='report_table_h'>RIGHT</td>" & gb.NewLine
      xx = xx & "</tr>" & gb.NewLine
      For Each res
        If res!fldvalue Then
          aa = res!fldvalue
        Else
          aa = ""
        Endif
        If res!fldcolm2 Then
          bb = res!fldcolm2
        Else
          bb = ""
        Endif
        xx = xx & "<tr>" & gb.NewLine
        xx = xx & "<td>" & res!fldvariable & "</td>" & gb.NewLine
        xx = xx & "<td>" & aa & "</td>" & gb.NewLine
        xx = xx & "<td>" & bb & "</td>" & gb.NewLine
        xx = xx & "</tr>" & gb.NewLine
      Next
      xx = xx & "</table>" & gb.NewLine

    Else
      xx = ""
      For Each res
        If res!fldvalue Then
          aa = res!fldvalue
        Else
          aa = ""
        Endif
        If res!fldcolm2 Then
          bb = res!fldcolm2
        Else
          bb = ""
        Endif
        xx = xx & res!fldvariable & " [LEFT: " & aa & "][RIGHT: " & bb & "]" & gb.NewLine
      Next

    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function UniLabValueList(encid As String, sTest As String) As String[]

  Dim res As Result
  Dim xx As String[]

  xx = New String[]
  res = modDatabase.$myConn.Exec("select fldtime_sample,fldreportquali from tblpatlabtest where fldencounterval=&1 and fldtestid=&2", encid, sTest)
  If res.Available Then
    For Each res
      If res!fldreportquali Then
        xx.Add(modReportVar.GetDateTimeReport(res!fldtime_sample, gb.GeneralDate) & " : " & res!fldreportquali)
      Endif
    Next
  Endif

  Return xx

End

'''---------------------------------CHART --------------------------------------------------------------------------
Public Sub FillQuantiTestChart(drw As PictureBox, encid As String, strHead As String, strUnit As String)

  Dim maxval As Float
  Dim minval As Float
  Dim normval As Float
  Dim sql As String
  Dim rData As Result
  Dim xpath As String
  Dim xlimit As Float[]

  Dim pointsArr_x As Date[]
  Dim pointsArr_y As Float[]

  pointsArr_x = New Date[]
  pointsArr_y = New Float[]

  xlimit = LabBothLimitValue(strHead, encid, strUnit)
  minval = xlimit[0]
  maxval = xlimit[1]
  normval = LabNormalValue(strHead, encid, strUnit)

  sql = "select fldid,fldencounterval,fldtime_sample from tblpatlabtest where fldencounterval=&1 and fldtestid=&2 and fldtest_type=&3 and (fldstatus=&4 or fldstatus=&5)"
  rData = modDatabase.$myConn.Exec(sql, encid, strHead, "Quantitative", "Reported", "Verified")
  If rData.Count Then
    For Each rData
      pointsArr_x.Add(rData!fldtime_sample)
      pointsArr_y.Add(GetTestQuantiValue(rData!fldencounterval, rData!fldid, strUnit))
    Next
    xpath = modChart.ClinicalChart(drw.Height, encid, pointsArr_x, pointsArr_y, maxval, minval, normval)
    drw.Picture = Picture.Load(xpath)
  Endif

End

Public Function TestInterpretByTestID(labid As Long) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String
  Dim xval As Float
  Dim encid As String

  encid = GetEncIDFromLabID(labid)
  sql = "select fldcomment,fldmax,fldmin,fldunit from tbltestcomment where fldtestid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)"
  res = modDatabase.$medConn.Exec(sql, GetTestnameFromTestID(labid), modPatient.GetPatientSex(GetEncounterFromLabSerial(labid)), "Both Sex", modPatient.GetAgeGroupFIxed(GetEncounterFromLabSerial(labid), Now()), "All Age")
  If res.Available = True Then
    For Each res
      If res!fldcomment And If res!fldunit Then
        xval = GetTestQuantiValue(encid, labid, res!fldunit)
        If xval >= res!fldmin And If xval <= res!fldmax Then
          xx = res!fldcomment
          Break
        Endif
      Else
        xx = ""
      Endif
    Next
  Else
    xx = ""
  Endif

  Return xx

End

''--------------------------------------------------Individual Test --------------------------------------------------
Public Function GetConvFactorTest(encid As String, strTest As String) As Float

  Dim sql As String
  Dim res As Result
  Dim crconv As Float

  sql = "select fldconvfactor from tbltestlimit where (fldptsex=&1 or fldptsex=&2) and (fldagegroup=&3 or fldagegroup=&4) and fldtestid in(select fldtestid from tbltest where fldsysconst=&5)"
  res = modDatabase.$medConn.Exec(sql, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", strTest)
  If res.Available = True Then
    If res!fldconvfactor Then
      crconv = res!fldconvfactor
    Else
      crconv = 1
    Endif
  Else
    crconv = 1
  Endif
  Return crconv

End

Public Function GetNormalValueTestMetric(encid As String, strTest As String) As Float

  Dim sql As String
  Dim res As Result
  Dim crconv As Float

  sql = "select fldmetnormal from tbltestlimit where (fldptsex=&1 or fldptsex=&2) and (fldagegroup=&3 or fldagegroup=&4) and fldtestid in(select fldtestid from tbltest where fldsysconst=&5)"
  res = modDatabase.$medConn.Exec(sql, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", strTest)
  If res.Available = True Then
    If res!fldmetnormal Then
      crconv = res!fldmetnormal
    Else
      crconv = 0
    Endif
  Else
    crconv = 0
  Endif
  Return crconv

End

Public Function GetCurrTesValueFromID(sPos As String, encid As String, strTest As String, Optional sUnit As String) As Float

  Dim sql As String
  Dim res As Result
  Dim metr As Float
  Dim unt As String

  If sUnit Then
    unt = sUnit
  Else
    unt = "Metric"
  Endif

  sql = "select fldreportquanti,fldtestunit from tblpatlabtest where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3) and fldtestid=&4"
  res = modDatabase.$myConn.Exec(sql, encid, "Reported", "Verified", strTest)
  If res.Available = True Then
    If sPos = "First" Then
      res.MoveFirst
    Else
      res.MoveLast
    Endif

    If res!fldreportquanti Then
      If unt = "Metric" Then
        If res!fldtestunit = "Metric" Then
          metr = res!fldreportquanti
        Else If res!fldtestunit = "SI" Then
          metr = Round(res!fldreportquanti / GetConvFactorTest(encid, strTest), -3)
        Endif
      Else If unt = "SI" Then
        If res!fldtestunit = "Metric" Then
          metr = Round(res!fldreportquanti * GetConvFactorTest(encid, strTest), -3)
        Else If res!fldtestunit = "SI" Then
          metr = res!fldreportquanti
        Endif
      Endif
    Else
      metr = 0
    Endif
  Else
    metr = 0
  Endif

  Return metr

End

''only for last quantitative test in metric unit (used in calculation)
Public Function GetCurrTesValueMetric(encid As String, xSysConst As String, sPos As String) As String

  Dim metr As String
  Dim sql As String
  Dim res As Result
  Dim xType As String
  Dim xval As Float

  sql = "select fldid,fldtestid,fldreportquali,fldreportquanti,fldtest_type from tblpatlabtest where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3) and fldtestid in(select fldtestid from tbltest where fldsysconst=&4) and fldreportquali IS NOT &5"
  res = modDatabase.$myConn.Exec(sql, encid, "Reported", "Verified", xSysConst, Null)
  If res.Available = True Then
    If sPos = "First" Then
      res.MoveFirst
    Else
      res.MoveLast
    Endif

    If res["fldtest_type"] = "Quantitative" Then
      xval = GetTestQuantiValue(encid, res["fldid"], "Metric")
      If xval Then
        metr = CStr(xval)
      Else
        metr = ""
      Endif
    Else
      If res["fldreportquali"] Then
        xType = modExamOption.GetVariableOptionType("Test", res["fldtestid"])
        If xType = "Clinical Scale" Then
          metr = CStr(res!fldreportquanti)
        Else
          metr = Trim(res!fldreportquali)
        Endif
      Else
        metr = ""
      Endif
    Endif

  Else
    metr = ""
  Endif

  Return metr

End

''---------------------- List for sampling -------------------------------
Public Function GetColumnName(sItem As String) As String

  Dim xx As String
  Dim i As Integer

  For i = 1 To 6
    If modSettings.ShowSettingFromFIle("Laboratory/EXTRA" & CStr(i)) = sItem Then
      xx = "EXTRA" & CStr(i)
      Break
    Endif
  Next
  Return xx

End

Public Sub PrintBarCodeSampling(encid As String, sampleNo As String, specimen As String, xSection As String)

  Dim hBarPage As CBarCode
  Dim xpath As String
  Dim sPath As String
  Dim xcount As Integer
  Dim i As Integer
  Dim xset As String
  Dim arcmd As String[]
  Dim xval As String

  xcount = InputValue("Number of Print copies", "Bar Code:" & xSection, 1)
  If xcount Then
    If modBasic.$LabBarCode Then
      If modBasic.$LabBarCode = "SampleNo" Then
        xpath = modDevice.GetBarCodeSample(sampleNo)
      Else If modBasic.$LabBarCode = "SampleNo@EncID" Then
        xpath = modDevice.GetBarCodeSample(sampleNo & "@" & encid)
      Else If modBasic.$LabBarCode = "EncounterID" Then
        xpath = modDevice.GetBarCodeSample(encid)
      Else
        xval = modBasic.$LabBarCode
        xval = Replace(xval, "{SampleID}", sampleNo)
        xval = Replace(xval, "{Encounter}", encid)
        xval = Replace(xval, "{Specimen}", specimen)
        xpath = modDevice.GetBarCodeSample(xval)
      Endif
    Else
      xpath = modDevice.GetBarCodeSample(encid)
    Endif
    hBarPage = New CBarCode(encid, sampleNo, specimen, xSection, xpath)
    sPath = modPrint.ConvertHTMLToPDFString(hBarPage.LabelPath(), "LabelSize")

    If xcount = 1 Then
      modPrint.DefaultPrinting(sPath, "LabelSize")

    Else If xcount > 1 Then
      xset = modSettings.ShowSettingFromFIle("Label/PDF_MultiPage")
      If xset = "Continuous" Then
        arcmd = New String[]
        For i = 1 To xcount
          arcmd.Add(sPath)
        Next
        modPrint.DefaultPrinting(modPrint.GetPDFUnion(arcmd), "LabelSize")

      Else
        For i = 1 To xcount
          modPrint.DefaultPrinting(sPath, "LabelSize")
        Next

      Endif
    Endif

  Endif  ''if count >=1

End

''=========================================== Drug Sensitivity Table ===========================================
Public Function GetSensitivityTable(encid As String, testid As Long) As String

  Dim res As Result
  Dim restab As Result
  Dim xtable As String

  res = modDatabase.$myConn.Exec("select fldsubtest,fldreport,fldid,fldtestid,fldtanswertype from tblpatlabsubtest where fldencounterval=&1 and fldtestid=&2 and fldchk=&3 and fldsave=&4 and (fldtanswertype=&5 or fldtanswertype=&6)", encid, testid, True, True, "Drug Sensitivity")
  If res.Available = True Then

    xtable = modRepoTemplete.HTMLTableSyntax()
    xtable = xtable & "<tr>" & gb.NewLine
    xtable = xtable & "<td class='report_table_h'>" & "Antibiotics" & "</td>" & gb.NewLine
    For Each res
      xtable = xtable & "<td class='report_table_h'>" & res!fldsubtest & "</td>" & gb.NewLine
    Next
    xtable = xtable & "</tr>" & gb.NewLine

    restab = modDatabase.$myConn.Exec("select distinct(fldvariable) as antibiotic from tblpatlabsubtable where fldtestid=&1 and fldvalue<>&2 ORDER BY fldvariable ASC", testid, "Cancelled")
    If restab.Available Then
      For Each restab
        xtable = xtable & "<tr>" & gb.NewLine
        xtable = xtable & "<td>" & restab!antibiotic & "</td>" & gb.NewLine
        For Each res
          xtable = xtable & "<td>" & GetSensiValue(res!fldtestid, res!fldid, restab!antibiotic) & "</td>" & gb.NewLine
        Next
        xtable = xtable & "</tr>" & gb.NewLine
      Next
    Endif
    xtable = xtable & "</table>" & gb.NewLine
  Endif

  Return xtable

End

Private Function GetSensiValue(testid As Long, subtestid As Long, antibiotic As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select distinct(fldvalue) from tblpatlabsubtable where fldtestid=&1 and fldsubtestid=&2 and fldvariable=&3 and fldvalue<>&4", testid, subtestid, antibiotic, "Cancelled")
  If res.Available Then
    If res!fldvalue Then
      xx = res!fldvalue
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End
