' Gambas module file

Public $PatNumData As Collection
Public $PatNameData As Collection
Public $PatGenderData As Collection
Public $PatDOBData As Collection
Public $PatContactData As Collection
Public $PatAddressData As Collection
Public $PatDistrictData As Collection

Public $PatCodeData As Collection
Public $PatRelationData As Collection
Public $PatGuardData As Collection
Public $PatEMailData As Collection

Public $PatDORegData As Collection
Public $PatDOAData As Collection
Public $PatBillMode As Collection
Public $PatVisType As Collection

Public $PatRegDepartData As Collection
Public $PatDODData As Collection
Public $PatDOFollData As Collection

'''--------------------------------------------- PATIENT PARAMETERS --------------------------------------------------------------------------
Public Sub RemovePatientCache(patno As String)

  Dim res As Result
  Dim encid As String

  If modBasic.$LocalCache = "Yes" Then
    res = modDatabase.$myConn.Exec("select fldencounterval from tblencounter where fldpatientval=&1", patno)
    If res.Available Then
      For Each res
        encid = res!fldencounterval
        $PatNumData.Remove(encid)
        $PatNameData.Remove(encid)
        $PatGenderData.Remove(encid)
        $PatDOBData.Remove(encid)
        $PatContactData.Remove(encid)
        $PatAddressData.Remove(encid)
        $PatDistrictData.Remove(encid)
        $PatCodeData.Remove(encid)
        $PatRelationData.Remove(encid)
        $PatGuardData.Remove(encid)
        $PatEMailData.Remove(encid)
      Next
    Endif
  Endif

End

''get Patient Status
Public Function GetPatientHMISStattus(sPatNo As String) As String

  Dim xval As String
  Dim res As Result
  Dim xDate As Date

  If sPatNo Then
    xDate = modDate.GetNepaliFiscalYarStart(Now())
    If xDate Then
      res = modDatabase.$myConn.Limit(1).Exec("select fldencounterval from tblencounter where fldpatientval=&1 and fldregdate>=&2", sPatNo, xDate)
      If res.Available Then
        xval = "OLD"
      Else
        xval = "NEW"
      Endif
    Else
      res = modDatabase.$myConn.Limit(1).Exec("select fldencounterval from tblencounter where fldpatientval=&1", sPatNo)
      If res.Available Then
        xval = "OLD"
      Else
        xval = "NEW"
      Endif
    Endif
  Else
    xval = "NEW"
  Endif
  Return xval

End

''fet patient locked to user
Public Function GetPatientLockMacAdd(encid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldhostmac from tblactivity where fldcategory=&1 and fldactivity=&2 and fldcomment=&3", "Patient Lock", "EncounterID", encid)
  If res.Available Then
    If res!fldhostmac Then
      xx = res!fldhostmac
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''get patient color
Public Function GetPatientColor(encid As String) As Integer

  Dim xint As Integer

  If modBasic.$TriageMode = "Dynamic" Then
    xint = modPathology.GetPatientColorDynamic(encid)
  Else
    xint = GetPatientColorStatic(encid)
  Endif
  Return xint

End

Public Function GetPatientColorStatic(encid As String) As Integer

  Dim xint As Integer
  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldheight from tblencounter where fldencounterval=&1", encid)
  If res.Available Then
    If res["fldheight"] Then
      xint = CInt(res["fldheight"])
    Else
      xint = Color.Transparent
    Endif
  Else
    xint = Color.Transparent
  Endif
  Return xint

End

Public Sub SetPatientColor(encid As String, xColor As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldheight"] = xColor
  res["xyz"] = False
  res.Update

End

''get patient files and comment
Public Function GetPatientFileByEnc(encid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldadmitfile from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
  If res.Available Then
    If res!fldadmitfile Then
      xx = res!fldadmitfile
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetPatientFileByPatNo(patno As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldadmitfile from tblpatientinfo where fldpatientval=&1", patno)
  If res.Available Then
    If res!fldadmitfile Then
      xx = res!fldadmitfile
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Sub UpdatePatFile(encid As String, ptfile As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientinfo", "fldpatientval=&1", GetPatientNoByEnc(encid))
  res["fldadmitfile"] = ptfile
  res["fldupuser"] = modGeneralMain.$lbluser
  res["flduptime"] = Now()
  res["xyz"] = False
  res.Update

End

Public Function GetPatientCommentByEnc(encid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldcomment from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
  If res.Available Then
    If res!fldcomment Then
      xx = res!fldcomment
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Sub UpdatePatComment(encid As String, sComm As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientinfo", "fldpatientval=&1", GetPatientNoByEnc(encid))
  res["fldcomment"] = sComm
  res["fldupuser"] = modGeneralMain.$lbluser
  res["flduptime"] = Now()
  res["xyz"] = False
  res.Update

End

''if patn o exist
Public Function SearchPatNo(ptno As String) As Boolean

  Dim res As Result
  Dim xx As Boolean

  res = modDatabase.$myConn.Exec("select fldpatientval from tblpatientinfo where fldpatientval=&1", ptno)
  xx = res.Available
  Return xx

End

''Last Encounter
Public Function GetLastEncoutnerFromPatNo(ptno As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldencounterval as col from tblencounter where fldpatientval=&1 ORDER BY fldregdate DESC", ptno)
  If res.Available Then
    res.MoveFirst
    xx = res!col
  Endif
  Return xx

End

Public Function GetEncListFromPatNo(ptno As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select fldencounterval as col from tblencounter where fldpatientval=&1 ORDER BY fldregdate DESC", ptno)
  xx = modFillContainer.GetListFromResult(res)
  Return xx

End

Public Function GetEncoutnerCountFromPatNo(ptno As String) As Integer

  Dim res As Result
  Dim xx As Integer

  res = modDatabase.$myConn.Exec("select COUNT(fldencounterval) as col from tblencounter where fldpatientval=&1", ptno)
  If res.Available Then
    If res!col Then
      xx = res!col
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetPatientVisitStatus(ptno As String) As String

  Dim xval As Integer
  Dim xx As String

  xval = GetEncoutnerCountFromPatNo(ptno)
  If xval Then
    xx = "OLD"
  Else
    xx = "NEW"
  Endif
  Return xx

End

Public Function GetPatientEncFromID(tbl As String, id As Variant) As String

  Dim sql As String
  Dim res As Result
  Dim xenc As String
  Dim sid As String
  Dim sencid As String

  If tbl = "tblpatfindings" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblpatlabtest" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblpatradiotest" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblpatientexam" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblpatdosing" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblexamgeneral" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblpatgeneral" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblpatsubgeneral" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblencounter" Then
    sid = "fldencounterval"
    sencid = "fldencounterval"
  Else If tbl = "tblpatplanning" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblconfinement" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Else If tbl = "tblpatientdate" Then
    sid = "fldid"
    sencid = "fldencounterval"
  Endif

  sql = Subst("select &1 as fldencid from &2 where &3", sencid, tbl, sid)
  res = modDatabase.$myConn.Exec(sql & "=&1", id)
  If res.Available Then
    If res!fldencid Then
      xenc = res!fldencid
    Else
      xenc = ""
    Endif
  Else
    xenc = ""
  Endif
  Return xenc

End

Public Function GetPatPassCheck(sCon As Connection, patno As String) As Boolean

  Dim res As Result
  Dim xx As Boolean
  Dim xval As String
  Dim xpass As String

  res = sCon.Exec("select fldpassword from tblpatientinfo where fldpatientval=&1", patno)
  If res.Available Then
    If res!fldpassword Then
      xval = InputPassword(("Provide Patient Password"), "Password", "")
      If xval Then
        xpass = modPassword.EncryptSimple(xval)
        If res!fldpassword = xpass Then
          xx = True
        Else
          xx = False
        Endif
      Else
        xx = False
      Endif
    Else
      xx = True
    Endif
  Else
    xx = False
  Endif
  Return xx

End

''------------------------ Billing Mode
Public Function GetPatBillingMode(encid As String) As String

  Dim res As Result
  Dim bilmode As String

  bilmode = modHelpVariable.GetCollectionValue($PatBillMode, encid)
  If Not bilmode Then
    res = modDatabase.$myConn.Exec("select fldbillingmode from tblencounter where fldencounterval=&1", encid)
    If res.Available Then
      If res!fldbillingmode Then
        bilmode = res!fldbillingmode
        If modBasic.$LocalCache = "Yes" Then
          $PatBillMode.Add(bilmode, encid)
        Endif
      Else
        bilmode = ""
      Endif
    Else
      bilmode = ""
    Endif
  Endif
  Return bilmode

End

''--------------------------------- Visit Type
Public Function GetPatVisitType(encid As String) As String

  Dim res As Result
  Dim vistype As String

  vistype = modHelpVariable.GetCollectionValue($PatVisType, encid)
  If Not vistype Then
    res = modDatabase.$myConn.Exec("select fldvisit from tblencounter where fldencounterval=&1", encid)
    If res.Available Then
      If res!fldvisit Then
        vistype = res!fldvisit
        If modBasic.$LocalCache = "Yes" Then
          $PatVisType.Add(vistype, encid)
        Endif
      Else
        vistype = ""
      Endif
    Else
      vistype = ""
    Endif
  Endif
  Return vistype

End

'''----------------------Current location (Bed)
Public Function GetAdmitLocation(encid As String) As String

  Dim res As Result
  Dim bedno As String

  bedno = modHelpVariable.GetCollectionValue($PatRegDepartData, encid)
  If Not bedno Then
    res = modDatabase.$myConn.Exec("select fldadmitlocat from tblencounter where fldencounterval=&1", encid)
    If res.Available Then
      If res!fldadmitlocat Then
        bedno = res!fldadmitlocat
        If modBasic.$LocalCache = "Yes" Then
          $PatRegDepartData.Add(bedno, encid)
        Endif
      Else
        bedno = ""
      Endif
    Else
      bedno = ""
    Endif
  Endif

  Return bedno

End

Public Function GetPatientLocation(encid As String) As String

  Dim res As Result
  Dim bedno As String

  res = modDatabase.$myConn.Exec("select fldcurrlocat from tblencounter where fldencounterval=&1", encid)
  If res.Available Then
    If res!fldcurrlocat Then
      bedno = res!fldcurrlocat
    Else
      bedno = ""
    Endif
  Else
    bedno = ""
  Endif
  Return bedno

End

Public Sub UpdatePatLocation(encid As String, bedno As String)

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldcurrlocat"] = bedno
  res["xyz"] = False
  res.Update()

  res2 = modDatabase.$myConn.Edit("tbldepartmentbed", "fldencounterval=&1", encid)
  If res2.Available Then
    res2["fldencounterval"] = ""
    res2.Update
  Endif

  res1 = modDatabase.$myConn.Edit("tbldepartmentbed", "fldbed=&1", bedno)
  If res1.Available Then
    res1["fldencounterval"] = encid
    res1.Update
  Endif

  If bedno Then
    EnterPatientImpDate(encid, "Location Update", bedno)
  Endif

End

Public Function GetPatientDepartment(encid As String) As String

  Dim res As Result
  Dim bedno As String

  res = modDatabase.$myConn.Exec("select flddept from tbldepartmentbed where fldbed in(select fldcurrlocat from tblencounter where fldencounterval=&1)", encid)
  If res.Available Then
    If res!flddept Then
      bedno = res!flddept
    Else
      bedno = ""
    Endif
  Else
    bedno = ""
  Endif
  Return bedno

End

'''--------------------------- Admission Date and other dates
Public Function GetRecordDate(encid As String) As Date

  Dim res As Result
  Dim dt As Date

  dt = modHelpVariable.GetCollectionValue($PatDORegData, encid)
  If Not dt Then
    res = modDatabase.$myConn.Exec("select fldregdate from tblencounter where fldencounterval=&1", encid)
    If res.Available Then
      If res!fldregdate Then
        dt = res!fldregdate
        If modBasic.$LocalCache = "Yes" Then
          $PatDORegData.Add(dt, encid)
        Endif
      Else
        dt = ""
      Endif
    Else
      dt = ""
    Endif
  Endif
  Return dt

End

Public Function GetFollowUpDate(encid As String) As Date

  Dim res As Result
  Dim dt As Date

  dt = modHelpVariable.GetCollectionValue($PatDOFollData, encid)
  If Not dt Then
    res = modDatabase.$myConn.Exec("select fldfollowdate from tblencounter where fldencounterval=&1", encid)
    If res.Available Then
      If res!fldfollowdate Then
        dt = res!fldfollowdate
        If modBasic.$LocalCache = "Yes" Then
          $PatDOFollData.Add(dt, encid)
        Endif
      Else
        dt = ""
      Endif
    Else
      dt = ""
    Endif
  Endif

  Return dt

End

Public Function GetDischargeDate(encid As String) As Date

  Dim res As Result
  Dim dt As Date

  dt = modHelpVariable.GetCollectionValue($PatDODData, encid)
  If Not dt Then
    res = modDatabase.$myConn.Exec("select flddod from tblencounter where fldencounterval=&1", encid)
    If res.Available Then
      If res!flddod Then
        dt = res!flddod
        If modBasic.$LocalCache = "Yes" Then
          $PatDODData.Add(dt, encid)
        Endif
      Else
        dt = ""
      Endif
    Else
      dt = ""
    Endif
  Endif

  Return dt

End

Public Function GetAdmissionDate(encid As String) As Date

  Dim dt As Date
  Dim res As Result

  dt = modHelpVariable.GetCollectionValue($PatDOAData, encid)
  If Not dt Then
    res = modDatabase.$myConn.Exec("select flddoa from tblencounter where fldencounterval=&1", encid)
    If res.Available Then
      If res!flddoa Then
        dt = res!flddoa
        If modBasic.$LocalCache = "Yes" Then
          $PatDOAData.Add(dt, encid)
        Endif
      Else
        dt = ""
      Endif
    Else
      dt = ""
    Endif
  Endif
  Return dt

End

Public Function GetDayDiffAdmission(encid As String, dt As Date) As String

  Dim xx As String
  Dim xadmis As Date

  xadmis = GetAdmissionDate(encid)
  If xadmis Then
    xx = "Day " & CStr(Floor(DateDiff(modDate.StartSqlDate(xadmis), dt, gb.Minute) / 1440) + 1)
  Endif
  Return xx

End

Public Function GetDayTimeFromAdmission(encid As String, fldnow As Date) As String

  Dim xx As String

  xx = GetDayDiffAdmission(encid, fldnow) & "::" & Format(fldnow, "hh:nn")
  Return xx

End

''----------------------------- Basic  Profile
Public Function GetPatientNoByEnc(encid As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($PatNumData, encid)
  If Not xx Then
    res = modDatabase.$myConn.Exec("select fldpatientval from tblencounter where fldencounterval=&1", encid)
    If res.Available Then
      If res!fldpatientval Then
        xx = res!fldpatientval
        If modBasic.$LocalCache = "Yes" Then
          $PatNumData.Add(xx, encid)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetPatientExtCOdebyEnc(encid As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($PatCodeData, encid)
  If Not xx Then
    res = modDatabase.$myConn.Exec("select fldptcode from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldptcode Then
        xx = res!fldptcode
        If modBasic.$LocalCache = "Yes" Then
          $PatCodeData.Add(xx, encid)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetPatientNoByHospCode(hospcode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldpatientval from tblpatientinfo where fldptcode=&1", hospcode)
  If res.Available Then
    res.MoveFirst
    If res!fldpatientval Then
      xx = res!fldpatientval
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetPatientNoByFileNo(fileno As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldpatientval from tblpatientinfo where fldadmitfile=&1", fileno)
  If res.Available Then
    res.MoveFirst
    If res!fldpatientval Then
      xx = res!fldpatientval
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''------------------------------- Ethnicity ---------------------------
'NOTE:TWO CON
Public Function GetPatientEthnicity(encid As String) As String

  Dim xx As String
  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldethniccode from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
  If res.Available Then
    If res!fldethniccode Then
      xx = res!fldethniccode
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''----------------------------------- Patient specific ---------------------------------------
Public Function PatientFullNameByPatID(patno As String) As String

  Dim res As Result
  Dim xx As String
  Dim firname As String
  Dim lstname As String

  res = modDatabase.$myConn.Exec("select fldptnamefir,fldptnamelast,fldencrypt from tblpatientinfo where fldpatientval=&1", patno)
  If res.Available Then
    If res!fldptnamefir Then
      If res["fldencrypt"] = True Then
        firname = modPassword.DecryptPatSimple(res!fldptnamefir)
      Else
        firname = res!fldptnamefir
      Endif
    Else
      firname = ""
    Endif

    If res!fldptnamelast Then
      If res["fldencrypt"] = True Then
        lstname = modPassword.DecryptPatSimple(res!fldptnamelast)
      Else
        lstname = res!fldptnamelast
      Endif
    Else
      lstname = ""
    Endif

    If modBasic.$PatNameFormat = "FirstName+SurName" Then
      xx = firname & Space(1) & lstname
    Else If modBasic.$PatNameFormat = "SurName+FirstName" Then
      xx = lstname & Space(1) & firname
    Else If modBasic.$PatNameFormat = "FirstName+SURNAME" Then
      xx = firname & Space(1) & UCase(lstname)
    Else If modBasic.$PatNameFormat = "SURNAME+FirstName" Then
      xx = UCase(lstname) & Space(1) & firname
    Else If modBasic.$PatNameFormat = "FirstName Only" Then
      xx = firname
    Else If modBasic.$PatNameFormat = "***SurName" Then
      xx = "*** " & lstname
    Else
      xx = firname & Space(1) & lstname
    Endif

  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetPatientNameByEnc(encid As String, Optional sCon As Connection) As String

  Dim res As Result
  Dim xx As String
  Dim firname As String
  Dim lstname As String
  Dim $con As Connection

  If sCon Then
    $con = sCon
  Else
    $con = modDatabase.$myConn
  Endif

  xx = modHelpVariable.GetCollectionValue($PatNameData, encid)
  If Not xx Then
    res = $con.Exec("select fldptnamefir,fldptnamelast,fldencrypt from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldptnamefir Then
        If res["fldencrypt"] = True Then
          firname = modPassword.DecryptPatSimple(res!fldptnamefir)
        Else
          firname = res!fldptnamefir
        Endif
      Else
        firname = ""
      Endif

      If res!fldptnamelast Then
        If res["fldencrypt"] = True Then
          lstname = modPassword.DecryptPatSimple(res!fldptnamelast)
        Else
          lstname = res!fldptnamelast
        Endif
      Else
        lstname = ""
      Endif

      If modBasic.$PatNameFormat = "FirstName+SurName" Then
        xx = firname & Space(1) & lstname
      Else If modBasic.$PatNameFormat = "SurName+FirstName" Then
        xx = lstname & Space(1) & firname
      Else If modBasic.$PatNameFormat = "FirstName+SURNAME" Then
        xx = firname & Space(1) & UCase(lstname)
      Else If modBasic.$PatNameFormat = "SURNAME+FirstName" Then
        xx = UCase(lstname) & Space(1) & firname
      Else If modBasic.$PatNameFormat = "FirstName Only" Then
        xx = firname
      Else If modBasic.$PatNameFormat = "***SurName" Then
        xx = "*** " & lstname
      Else
        xx = firname & Space(1) & lstname
      Endif

      If firname Or If lstname Then
        If modBasic.$LocalCache = "Yes" Then
          $PatNameData.Add(xx, encid)
        Endif
      Endif

    Else
      xx = ""
    Endif
  Endif

  Return xx

End

Public Function GetPatFirAddressByEnc(encid As String, $con As Connection) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($PatAddressData, encid)
  If Not xx Then
    res = $con.Exec("select fldptaddvill from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldptaddvill Then
        xx = res!fldptaddvill
        If modBasic.$LocalCache = "Yes" Then
          $PatAddressData.Add(xx, encid)
        Endif
      Else
        xx = ""
      Endif
    Endif
  Endif
  Return xx

End

Public Function GetPatDistrictByEnc(encid As String, $con As Connection) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($PatDistrictData, encid)
  If Not xx Then
    res = $con.Exec("select fldptadddist from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldptadddist Then
        xx = res!fldptadddist
        If modBasic.$LocalCache = "Yes" Then
          $PatDistrictData.Add(xx, encid)
        Endif
      Else
        xx = ""
      Endif
    Endif
  Endif
  Return xx

End

Public Function GetPatientAddressByEnc(encid As String, Optional sCon As Connection) As String

  Dim adfir As String
  Dim addist As String
  Dim xx As String
  Dim $con As Connection

  If sCon Then
    $con = sCon
  Else
    $con = modDatabase.$myConn
  Endif
  adfir = GetPatFirAddressByEnc(encid, $con)
  addist = GetPatDistrictByEnc(encid, $con)

  If modBasic.$PatAddressFormat Then
    xx = modBasic.$PatAddressFormat
    xx = Replace(xx, "{Address}", adfir)
    xx = Replace(xx, "{District}", addist)
  Else
    xx = adfir & ", " & addist
  Endif

  Return xx

End

Public Function GetPatientDistrictOnly(encid As String, Optional sCon As Connection) As String

  Dim xx As String

  If sCon Then
    xx = GetPatDistrictByEnc(encid, sCon)
  Else
    xx = GetPatDistrictByEnc(encid, modDatabase.$myConn)
  Endif
  Return xx

End

''sex
Public Function PatientGenderByPatNo(patno As String) As String

  Dim res As Result
  Dim sex As String

  res = modDatabase.$myConn.Exec("select fldptsex from tblpatientinfo where fldpatientval=&1", patno)
  If res.Available Then
    If res!fldptsex Then
      sex = res!fldptsex
    Else
      sex = ""
    Endif
  Else
    sex = ""
  Endif
  Return sex

End

Public Function GetPatientSex(encid As String, Optional sCon As Connection) As String

  Dim res As Result
  Dim sex As String
  Dim $con As Connection

  If sCon Then
    $con = sCon
  Else
    $con = modDatabase.$myConn
  Endif

  sex = modHelpVariable.GetCollectionValue($PatGenderData, encid)
  If Not sex Then
    res = $con.Exec("select fldptsex from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldptsex Then
        sex = res!fldptsex
        If modBasic.$LocalCache = "Yes" Then
          $PatGenderData.Add(sex, encid)
        Endif
      Else
        sex = ""
      Endif
    Else
      sex = ""
    Endif
  Endif
  Return sex

End

''--------------------------------------Contact
Public Function GetPatientContactByEnc(encid As String, Optional sCon As Connection) As String

  Dim res As Result
  Dim xx As String
  Dim $con As Connection

  If sCon Then
    $con = sCon
  Else
    $con = modDatabase.$myConn
  Endif

  xx = modHelpVariable.GetCollectionValue($PatContactData, encid)
  If Not xx Then
    res = $con.Exec("select fldptcontact,fldencrypt from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldptcontact Then
        If res["fldencrypt"] = True Then
          xx = modPassword.DecryptPatSimple(res!fldptcontact)
        Else
          xx = res!fldptcontact
        Endif

        If modBasic.$LocalCache = "Yes" Then
          $PatContactData.Add(xx, encid)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetPatientEmail(encid As String) As String

  Dim smail As String
  Dim res As Result

  smail = modHelpVariable.GetCollectionValue($PatEMailData, encid)
  If Not smail Then
    res = modDatabase.$myConn.Exec("select fldemail,fldencrypt from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))                                                     ''
    If res.Available Then
      If res!fldemail Then
        If res["fldencrypt"] = True Then
          smail = modPassword.DecryptPatSimple(res!fldemail)
        Else
          smail = res!fldemail
        Endif

        If modBasic.$LocalCache = "Yes" Then
          $PatEMailData.Add(smail, encid)
        Endif
      Else
        smail = ""
      Endif
    Else
      smail = ""
    Endif
  Endif

  Return smail

End

Public Function GetPatientGuardianByEnc(encid As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($PatGuardData, encid)
  If Not xx Then
    res = modDatabase.$myConn.Exec("select fldptguardian from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldptguardian Then
        xx = res!fldptguardian
        If modBasic.$LocalCache = "Yes" Then
          $PatGuardData.Add(xx, encid)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif

  Return xx

End

Public Function GetPatientReltionByEnc(encid As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($PatRelationData, encid)
  If Not xx Then
    res = modDatabase.$myConn.Exec("select fldrelation from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldrelation Then
        xx = res!fldrelation
        If modBasic.$LocalCache = "Yes" Then
          $PatRelationData.Add(xx, encid)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif

  Return xx

End

''----------------------- Other ------------------------------
Public Function GetLocationSetting(encid As String) As String

  Dim xx As String
  Dim txtlocation As String

  xx = CurrentAdmissionStatus(encid)
  If xx = "Registered" Or If xx = "Admitted" Then
    txtlocation = GetPatientLocation(encid)
  Else If xx = "Discharged" Or If xx = "LAMA" Or If xx = "Death" Or If xx = "Refer" Or If xx = "Absconder" Then
    txtlocation = xx
  Else If xx = "Recorded" Or If xx = "FollowUp" Then
    txtlocation = xx
  Endif
  Return txtlocation

End

''-------------------------------- Birthday and age
Public Function GetPatientBirthDay(encid As String, Optional sCon As Connection) As Date

  Dim res As Result
  Dim xx As Date
  Dim $con As Connection

  If sCon Then
    $con = sCon
  Else
    $con = modDatabase.$myConn
  Endif

  xx = modHelpVariable.GetCollectionValue($PatDOBData, encid)
  If Not xx Then
    res = $con.Exec("select fldptbirday from tblpatientinfo where fldpatientval=&1", GetPatientNoByEnc(encid))
    If res.Available Then
      If res!fldptbirday Then
        xx = res!fldptbirday
        If modBasic.$LocalCache = "Yes" Then
          $PatDOBData.Add(xx, encid)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

''update age in tblpatientinfo
Public Sub UpdatePatDOB(encid As String, dob As Date)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientinfo", "fldpatientval=&1", GetPatientNoByEnc(encid))
  res["fldptbirday"] = dob
  res["xyz"] = False
  res.Update()

End

Public Sub UpdateDateOfBirth(encid As String, age As Float, unit As String)

  Dim xsec As Integer
  Dim dt As Date

  If unit = "Hours" Then
    xsec = age * 60
  Else If unit = "Days" Then
    xsec = age * 60 * 24
  Else If unit = "Months" Then
    xsec = age * 60 * 24 * 30
  Else If unit = "Years" Then
    xsec = age * 60 * 24 * 365
  Endif
  xsec = 0 - xsec
  dt = DateAdd(Now(), gb.Minute, CInt(xsec))
  UpdatePatDOB(encid, dt)

End

Public Function GetAgeGroup(encid As String, Optional NowDate As Date) As String

  Dim xx As String
  Dim xnow As String

  If NowDate Then
    xnow = NowDate
  Else
    xnow = Now()
  Endif
  xx = GetAgeGroupFIxed(encid, xnow)
  Return xx

End

Public Function GetAgeGroupFIxed(encid As String, xnow As Date) As String

  Dim agrgrp As String
  Dim age As Float
  Dim xdate As Date

  xdate = GetPatientBirthDay(encid)
  If xdate Then
    age = DateDiff(xdate, xnow, gb.Day)
    If age >= 60 * 365 Then
      agrgrp = "Elderly"
    Else If age >= 20 * 365 And If age < 60 * 365 Then
      agrgrp = "Adult"
    Else If age >= 12 * 365 And If age < 20 * 365 Then
      agrgrp = "Adolescent"
    Else If age >= 2 * 365 And If age < 12 * 365 Then
      agrgrp = "Children"
    Else If age >= 365 And If age < 2 * 365 Then
      agrgrp = "Toddler"
    Else If age >= 30 And If age < 365 Then
      agrgrp = "Infant"
    Else If age < 30 Then
      agrgrp = "Neonate"
    Endif
  Else
    agrgrp = ""
  Endif

  Return agrgrp

End

Public Function GetAgeGroupCustom(encid As String, Optional NowDate As Date) As String

  Dim xx As String
  Dim age As Float
  Dim xdate As Date
  Dim xnow As Date

  Dim hFile As File
  Dim sline As String
  Dim agegrp As String[]

  If NowDate Then
    xnow = NowDate
  Else
    xnow = Now()
  Endif

  If Exist(modHelpVariable.AppDirectory &/ "agegrouping") Then
    xdate = GetPatientBirthDay(encid)
    If xdate Then
      age = DateDiff(xdate, xnow, gb.Day)
      hFile = Open modHelpVariable.AppDirectory &/ "agegrouping"
      For Each sline In hFile.Lines
        If Len(sline) Then
          agegrp = Split(sline, ";")
          If age >= CInt(agegrp[1]) And If age < CInt(agegrp[2]) Then
            xx = agegrp[0]
            Break
          Endif
        Endif
      Next
      hFile.Close()
    Endif

  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetPatientAgeString(encid As String, dtnow As Date) As String

  Dim xage As String
  Dim xdate As Date

  xdate = GetPatientBirthDay(encid)
  If xdate Then
    xage = modDate.GetAgeString(xdate, dtnow)
  Else
    xage = "?"
  Endif

  Return xage

End

Public Function GetPatientPastAgeString(tbl As String, id As Variant) As String

  Dim sql As String
  Dim res As Result
  Dim xage As String
  Dim sid As String
  Dim stime As String
  Dim sencid As String
  Dim xdate As Date

  sid = "fldid"
  sencid = "fldencounterval"

  If tbl = "tblpatfindings" Then
    stime = "fldtime"
  Else If tbl = "tblpatlabtest" Then
    stime = "fldtime_sample"
  Else If tbl = "tblpatradiotest" Then
    stime = "fldtime_report"
  Else If tbl = "tblpatientexam" Then
    stime = "fldtime"
  Else If tbl = "tblpatdosing" Then
    stime = "fldtime"
  Else If tbl = "tblexamgeneral" Then
    stime = "fldtime"
  Else If tbl = "tblpatgeneral" Then
    stime = "fldtime"
  Else If tbl = "tblpatsubgeneral" Then
    stime = "fldtime"
  Else If tbl = "tblpataccgeneral" Then
    stime = "fldtime"
  Else If tbl = "tblpatplanning" Then
    stime = "fldtime"
  Else If tbl = "tblpattiming" Then
    stime = "fldfirsttime"
  Else If tbl = "tblpatientdate" Then
    stime = "fldtime"
  Else If tbl = "tblconsult" Then
    stime = "fldconsulttime"
  Else If tbl = "tblconfinement" Then
    stime = "flddeltime"
  Endif

  sql = Subst("select &1 as fldencid,&2 as fldtime from &3 where &4", sencid, stime, tbl, sid)
  res = modDatabase.$syConn.Exec(sql & "=&1", id)
  If res.Available Then
    xdate = GetPatientBirthDay(res!fldencid, modDatabase.$syConn)
    If xdate Then
      xage = modDate.GetAgeString(xdate, res!fldtime)
    Else
      xage = "?"
    Endif
  Else
    xage = ""
  Endif
  Return xage

End

''------------------------------ Admission status
Public Function CurrentAdmissionStatus(encid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldadmission from tblencounter where fldencounterval=&1", encid)
  If res.Available Then
    If res!fldadmission Then
      xx = res!fldadmission
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function EnableClinicForm(xStatus As String) As Boolean

  Dim fme As Boolean

  If xStatus = "Registered" Or If xStatus = "Admitted" Then
    fme = True
  Else If xStatus = "Discharged" Or If xStatus = "LAMA" Or If xStatus = "Death" Or If xStatus = "Refer" Or If xStatus = "Absconder" Then
    fme = False
  Else If xStatus = "Recorded" Or If xStatus = "FollowUp" Then
    If modGlobalSetting.ShowSettingFromDB("GeneralSettings/Clinic_LockNonRegistered") = "Yes" Then
      fme = False
    Else
      fme = True
    Endif
  Endif
  Return fme

End

Public Function AllowEncIDHistory(encid As String, sCon As Connection) As Boolean

  Dim xval As Boolean
  Dim xx As String

  xx = CurrentAdmissionStatus(encid)
  If xx = "Discharged" Or If xx = "LAMA" Or If xx = "Death" Or If xx = "Refer" Or If xx = "Absconder" Then
    If GetPatPassCheck(sCon, GetPatientNoByEnc(encid)) = True Then
      xval = True
    Else
      xval = False
    Endif
  Else
    xval = True
  Endif
  Return xval

End

Public Function UpdateCurrentStatus(encid As String, status As String, sComment As String)

  Dim res As Result
  Dim res1 As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldadmission"] = status
  If status = "Discharged" Or If status = "LAMA" Or If status = "Death" Or If status = "Refer" Or If status = "Absconder" Then
    res["flddod"] = Now()
  Endif
  res["xyz"] = False
  res.Update

  If status = "Discharged" Or If status = "LAMA" Or If status = "Death" Or If status = "Refer" Or If status = "Absconder" Then
    res1 = modDatabase.$myConn.Edit("tbldepartmentbed", "fldencounterval=&1", encid)
    If res1.Available Then
      res1["fldencounterval"] = ""
      res1.Update
    Endif
  Endif

  EnterPatientImpDate(encid, status, sComment)

End

''---------------------------- Mother Info---------------------
Public Function GetMotherEncounter(encid As String) As String

  Dim xenc As String
  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldencounterval from tblconfinement where fldbabypatno=&1", GetPatientNoByEnc(encid))
  If res.Available Then
    If res!fldencounterval Then
      xenc = res!fldencounterval
    Else
      xenc = ""
    Endif
  Else
    xenc = ""
  Endif
  Return xenc

End

''----------------------------- attending consultant --------------------------------
Public Function GetAttendingConsultant(encid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flduserid from tblencounter where fldencounterval=&1", encid)
  If res.Available Then
    If res!flduserid Then
      xx = res!flduserid
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Sub UpdateAttendingConsultant(encid As String, sUserID As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["flduserid"] = sUserID
  res["xyz"] = False
  res.Update
  EnterPatientImpDate(encid, "Consultant", modGeneral.GetUserFullName(sUserID))

End

'''------------------------------------- ENCOUNTER SPECIFIC ---------------------------------------------------------------------------
Public Function PatientFindingList(encid As String, strType As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]

  xx = New String[]
  sql = "select fldcode,fldcodeid from tblpatfindings where fldencounterval=&1 and fldtype=&2 and fldsave=&3"
  res = modDatabase.$myConn.Exec(sql, encid, strType, True) '("Allergic Drugs","Final Diagnosis","Provisional Diagnosis")
  If res.Available = True Then
    For Each res
      If res!fldcodeid Then
        xx.Add("[" & res!fldcodeid & "] " & res!fldcode)
      Else
        xx.Add(res!fldcode)
      Endif
    Next
    xx.Sort(gb.Ascent)
  Else
    If strType = "Allergic Drugs" Then
      xx.Add("None")
    Endif
  Endif

  Return xx

End

Public Function PatientDiagnoCurrentList(encid As String) As String[]

  Dim xx As String[]

  xx = PatientFindingList(encid, "Final Diagnosis")
  If xx.Count = 0 Then
    xx = PatientFindingList(encid, "Provisional Diagnosis")
  Endif
  Return xx

End

Public Function PatientDiagnoClassList(encid As String, strType As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]

  xx = New String[]
  sql = "select distinct(fldcodeid) as col from tblpatfindings where fldencounterval=&1 and fldtype=&2 and fldsave=&3"
  res = modDatabase.$myConn.Exec(sql, encid, strType, True) '("Final Diagnosis","Provisional Diagnosis")
  If res.Available = True Then
    For Each res
      If res!col Then
        xx.Add(res!col)
      Endif
    Next
    xx.Sort(gb.Ascent)
  Endif

  Return xx

End

Public Function PatientDiagnoCurClassList(encid As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]
  Dim res1 As Result

  xx = New String[]
  sql = "select distinct(fldcodeid) as col from tblpatfindings where fldencounterval=&1 and fldtype=&2 and fldsave=&3"
  res = modDatabase.$myConn.Exec(sql, encid, "Final Diagnosis", True)
  If res.Available = True Then
    For Each res
      If res!col Then
        xx.Add(res!col)
      Endif
    Next
    xx.Sort(gb.Ascent)
  Else
    res1 = modDatabase.$myConn.Exec(sql, encid, "Provisional Diagnosis", True)
    If res1.Available Then
      For Each res1
        If res1!col Then
          xx.Add(res1!col)
        Endif
      Next
      xx.Sort(gb.Ascent)
    Endif
  Endif

  Return xx

End

'NOTE: -------------------BLANK REGISTRATION -------------------------------------
Public Sub RegistBlankPatient()

  Dim res As Result
  Dim dt As Date
  Dim yr As Integer

  yr = 0 - 25
  dt = DateAdd(Now(), gb.Year, yr)
  res = modDatabase.$myConn.Create("tblpatientinfo")
  res["fldpatientval"] = "1"
  res["fldptnamefir"] = "General"
  res["fldptnamelast"] = "Patient"
  res["fldethniccode"] = ""
  res["fldptaddvill"] = "Hospital"
  res["fldptadddist"] = "Hospital"
  res["fldptsex"] = "Male"
  res["fldptcontact"] = ""
  res["fldptguardian"] = ""
  res["fldrelation"] = ""
  res["fldptbirday"] = dt
  res["fldptadmindate"] = Now()
  res["fldemail"] = ""
  res["fldptcode"] = ""
  res["flddiscount"] = ""
  res["fldadmitfile"] = ""
  res["fldcomment"] = ""
  res["fldencrypt"] = False
  res["fldpassword"] = ""

  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldupuser"] = ""
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update()

Catch

End

Public Sub RegistBlankEncounter()

  Dim res As Result

  res = modDatabase.$myConn.Create("tblencounter")
  res["fldencounterval"] = "1"
  res["fldpatientval"] = "1"
  res["fldadmitlocat"] = modGeneral.GetCompNameFromCompID(modGeneralMain.compID)
  res["fldcurrlocat"] = ""
  res["flddoa"] = ""
  res["flddod"] = ""
  res["fldheight"] = ""
  res["fldcashdeposit"] = 0
  res["flddisctype"] = ""
  res["fldcashcredit"] = 0
  res["flduserid"] = ""
  res["fldadmission"] = "Recorded"
  res["fldfollowdate"] = ""
  res["fldreferto"] = ""
  res["fldregdate"] = Now()
  res["fldcharity"] = 0
  res["fldbillingmode"] = ""
  res["fldcomp"] = modGeneralMain.compID
  res["fldvisit"] = "NEW"
  res["xyz"] = False
  res.Update()

Catch
  Message.Warning(("Encounter No: 1 already exist"), ("OK"))

End

''--------------------------------------------------------- Patient Date -------------------------------------
Public Sub EnterPatientImpDate(encid As String, sType As String, sComment As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatientdate")
  res["fldencounterval"] = encid
  res["fldhead"] = sType
  res["fldcomment"] = sComment
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub AddConsultData(encid As String, consultname As String, consulttime As Date, Optional sComment As String, Optional sUser As String, Optional sBillMode As String)

  Dim res As Result
  Dim rs As Result
  Dim xx As String
  Dim sbill As String

  If sUser Then
    xx = sUser
  Else
    xx = ""
  Endif
  If sBillMode Then
    sbill = sBillMode
  Else
    sbill = ""
  Endif

  res = modDatabase.$myConn.Create("tblconsult")
  res["fldencounterval"] = encid
  res["fldconsultname"] = consultname
  res["fldconsulttime"] = consulttime
  res["fldcomment"] = sComment
  res["fldstatus"] = "Planned"
  res["flduserid"] = xx
  res["fldbillingmode"] = sbill
  res["fldorduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = False
  res["xyz"] = False
  res.Update

  EnterPatientImpDate(encid, "Registered", "")
  rs = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  If Not rs["fldcurrlocat"] Then
    rs["fldcurrlocat"] = consultname
  Endif
  If rs["fldadmission"] <> "Admitted" Then
    rs["fldadmission"] = "Registered"
  Endif
  rs["xyz"] = False
  rs.Update
  'don't catch error

End

Public Sub UpdateConsultData(id As Long, status As String, comment As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblconsult", "fldid=&1", id)
  res["fldcomment"] = comment
  res["fldstatus"] = status
  res["fldsave"] = True
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Function GetPatientCOnsultList(encid As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  xxx = New String[]
  res = modDatabase.$myConn.Exec("select fldconsultname,fldconsulttime,fldstatus from tblconsult where fldencounterval=&1", encid)
  If res.Available Then
    For Each res
      If modBasic.$ShowDayMedReport = "Yes" Then
        xxx.Add(modReportVar.GetDateTimeReport(res!fldconsulttime, gb.GeneralDate) & " : " & res!fldconsultname & " (" & res!fldstatus & ")")
      Else
        xxx.Add(res!fldconsultname & " (" & res!fldstatus & ")")
      Endif
    Next
  Endif
  Return xxx

End

Public Sub GetPatientAdmission(encid As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldadmission"] = "Admitted"
  If Not res["flddoa"] Then
    res["flddoa"] = Now()
  Endif
  res["xyz"] = False
  res.Update
  modPatient.EnterPatientImpDate(encid, "Admitted", "")

End

''-------------------------- Encounter Lock ---------------------------------------
Public Function LockEncounterTable(encid As String, sType As String) As Boolean

  Dim res As Result
  Dim rs As Result
  Dim xx As Boolean

  rs = modDatabase.$myConn.Exec("select fldid from tblenclock where fldencounterval=&1 and fldlocktype=&2 and fldhostmac<>&3", encid, sType, modGeneralMain.$MACAddress)
  If rs.Available = False Then
    res = modDatabase.$myConn.Create("tblenclock")
    res["fldencounterval"] = encid
    res["fldlocktype"] = sType
    res["fldhostmac"] = modGeneralMain.$MACAddress
    res.Update
    xx = True
  Else
    xx = False
  Endif

  Return xx

End

Public Function LockEncounterDesk(encid As String) As Boolean

  Dim xx As Boolean

  If modBasic.$PatientEncLock = "Yes" Then
    xx = LockEncounterTable(encid, modHelpVariable.$LogInCategory)
  Else
    xx = True
  Endif
  Return xx
  ''dont catch error. Allow roll back

End

Public Sub ReleaseLockEncounter(encid As String, sType As String)

  modDatabase.$myConn.Delete("tblenclock", "fldencounterval=&1 and fldlocktype=&2 and fldhostmac=&3", encid, sType, modGeneralMain.$MACAddress)

End

Public Sub CLearAllEncounterLocks(sType As String)

  modDatabase.$myConn.Delete("tblenclock", "fldlocktype=&1", sType)
  Message.Info(("Locks Cleared"), ("OK"))

End

''---------------------------------------------- demographics -----------------------------
Public Function GetAccDemographicType(sItem As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldoption from tblaccdemograp where flddemoid=&1", sItem)
  If res.Available Then
    If res!fldoption Then
      xx = res!fldoption
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetAccDemographicOptionList(sName As String, sType As String) As String[]

  Dim res As Result
  Dim opt As String[]

  res = modDatabase.$myConn.Exec("select fldanswer from tblaccdemogoption where flddemoid=&1 and fldanswertype like &2 ORDER BY fldindex", sName, sType)
  opt = modFillContainer.GetListFromResult(res)

  Return opt

End

''------------------------------ Patient SUbscripts --------------------------------
Public Sub GetPatientNoPrefixes()

  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldid,fldpatno,fldpatlen,fldencid,fldenclen,fldbooking,fldbooklen,fldhospcode from tblpatsubs")
  If res.Available Then
    res.MoveLast
    If res!fldhospcode Then
      modBasic.$HospCode = res!fldhospcode
    Else
      modBasic.$HospCode = ""
    Endif
    If res!fldpatno Then
      modBasic.$PatNoPrefix = res!fldpatno
    Else
      modBasic.$PatNoPrefix = ""
    Endif
    If res!fldencid Then
      modBasic.$EncIdPrefix = res!fldencid
    Else
      modBasic.$EncIdPrefix = ""
    Endif
    If res!fldbooking Then
      modBasic.$BookNoPrefix = res!fldbooking
    Else
      modBasic.$BookNoPrefix = ""
    Endif

    If res!fldpatlen Then
      modBasic.$PatNoLen = res!fldpatlen
    Else
      modBasic.$PatNoLen = 0
    Endif
    If res!fldenclen Then
      modBasic.$EncIdLen = res!fldenclen
    Else
      modBasic.$EncIdLen = 0
    Endif
    If res!fldbooklen Then
      modBasic.$BookNoLen = res!fldbooklen
    Else
      modBasic.$BookNoLen = 0
    Endif

  Else
    modBasic.$HospCode = ""
    modBasic.$PatNoPrefix = ""
    modBasic.$EncIdPrefix = ""
    modBasic.$BookNoPrefix = ""
    modBasic.$PatNoLen = 0
    modBasic.$EncIdLen = 0
    modBasic.$BookNoLen = 0
  Endif

End

''----------------------------------- BOOKING ------------------------------------------
Public Function GetPatFullNameBooking(bookid As String) As String

  Dim res As Result
  Dim xx As String
  Dim firname As String
  Dim lstname As String

  res = modDatabase.$myConn.Exec("select fldptnamefir,fldptnamelast from tblpatientbook where fldbookingval=&1", bookid)
  If res.Available Then
    If res!fldptnamefir Then
      firname = res!fldptnamefir
    Else
      firname = ""
    Endif
    If res!fldptnamelast Then
      lstname = res!fldptnamelast
    Else
      lstname = ""
    Endif

    If modBasic.$PatNameFormat = "Name+Surname" Then
      xx = firname & Space(1) & lstname
    Else If modBasic.$PatNameFormat = "Surname+Name" Then
      xx = lstname & Space(1) & firname
    Else
      xx = firname & Space(1) & lstname
    Endif

  Else
    xx = ""
  Endif

  Return xx

End

Public Sub UpdateBookingTable(bookid As String, patno As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatientbook", "fldbookingval=&1", bookid)
  res["fldpatientval"] = patno
  res["fldstate"] = "Done"
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub PrintRegistExtraReport(encid As String)

  Dim hCls As CReportCustom
  Dim res As Result
  Dim xregist As String
  Dim xlateregist As String

  res = modDatabase.$myConn.Exec("select fldvisit from tblencounter where fldencounterval=&1", encid)
  xregist = modSettings.ShowSettingFromFIle("RegistrationForm/Template")
  xlateregist = modSettings.ShowSettingFromFIle("RegistrationLaterForm/Template")
  If res!fldvisit Then
    If res!fldvisit = "NEW" Then
      If xregist Then
        hCls = New CReportCustom(encid, xregist)
        hCls.Preview()
      Endif
    Else If res!fldvisit = "OLD" Then
      If xregist Then
        hCls = New CReportCustom(encid, xregist)
        hCls.Preview()
      Endif
    Endif

  Else
    If xregist Then
      hCls = New CReportCustom(encid, xregist)
      hCls.Preview()
    Endif
  Endif

End

Public Sub PrintExtraReport(encid As String, sType As String)

  Dim hCls As CReportCustom
  Dim xval As String

  xval = modSettings.ShowSettingFromFIle("ExtraPrint/" & sType)
  If xval Then
    hCls = New CReportCustom(encid, xval, modSettings.ShowSettingFromFIle("ExtraPrintMode/" & sType))
    hCls.Preview()
  Endif

End

Public Function PatientParameterPresent(patno As String) As Boolean

  Dim sql As String
  Dim res As Result
  Dim xx As Boolean

  sql = "select fldptaddvill,fldptadddist,fldptcontact,fldptguardian,fldptbirday,fldptadmindate,fldemail,fldrelation,fldptcode from tblpatientinfo where fldpatientval = &1 "                                    ''"
  res = modDatabase.$myConn.Exec(sql, patno)

  xx = True
  If res.Available Then
    If modBasic.$RegistEssAddress = "Yes" Then
      If Not res!fldptaddvill Then
        xx = False
      Endif
    Endif

    If modBasic.$RegistEssDistrict = "Yes" Then
      If Not res!fldptadddist Then
        xx = False
      Endif
    Endif

    If modBasic.$RegistEssAge = "Yes" Then
      If Not res!fldptbirday Then
        xx = False
      Endif
    Endif

    If modBasic.$RegistEssGuardian = "Yes" Then
      If Not res!fldptguardian Then
        xx = False
      Endif
    Endif

    If modBasic.$RegistEssRelation = "Yes" Then
      If Not res!fldrelation Then
        xx = False
      Endif
    Endif

    If modBasic.$RegistEssContact = "Yes" Then
      If Not res!fldptcontact Then
        xx = False
      Endif
    Endif

    If modBasic.$RegistEssEMail = "Yes" Then
      If Not res!fldemail Then
        xx = False
      Endif
    Endif

    If modBasic.$RegistEssCode = "Yes" Then
      If Not res!fldptcode Then
        xx = False
      Endif
    Endif
  Endif
  Return xx

End

Public Sub PopUpPatientForm(encid As String, sTag As String)

  Dim hForm As FmIndexForm
  Dim patno As String
  Dim xset As String

  xset = modGlobalSetting.ShowSettingFromDB("PatientFormPopUp/" & sTag)
  If xset = "Yes" Then
    patno = GetPatientNoByEnc(encid)
    If PatientParameterPresent(patno) = False Then
      hForm = New FmIndexForm(patno, False)
      hForm.Show()
    Endif
  Endif

End

''------------------------------------ Assign device -------------------------------------------
Public Sub SetPatientDevice(encid As String, sType As String, sDevice As String)

  Dim rs As Result
  Dim res As Result

  modBasic.DebugString("Setting webcam device for patient")
  rs = modDatabase.$myConn.Exec("select flddevicepath from tblpatdevice where flddevicetype=&1 and fldencounterval=&2", sType, encid)
  If rs.Available = False Then
    res = modDatabase.$myConn.Create("tblpatdevice")
    res["fldencounterval"] = encid
    res["flddevicetype"] = sType
    res["flddevicepath"] = sDevice
    res["fldhostmac"] = modGeneralMain.$MACAddress
    res["fldhostuser"] = System.User.Name
    res["fldhostip"] = modGeneralMain.$localIP
    res["fldhostname"] = System.Host
    res["fldcomp"] = modGeneralMain.compID
    res.Update

  Else
    res = modDatabase.$myConn.Edit("tblpatdevice", "flddevicetype=&1 and fldencounterval=&2", sType, encid)
    res["flddevicepath"] = sDevice
    res["fldhostmac"] = modGeneralMain.$MACAddress
    res["fldhostuser"] = System.User.Name
    res["fldhostip"] = modGeneralMain.$localIP
    res["fldhostname"] = System.Host
    res["fldcomp"] = modGeneralMain.compID
    res.Update

  Endif

End

''---------------------------------------------- QUOTA (fixed parameters) ---------------------------------------------------------------
Public Function GetPatientQuota(sDept As String, sDate As Date, sBillMode As String, sUserid As String) As Integer

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim xx As Integer

  If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
    res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and flduserid=&4 and fldcomp like &5 and fldmethod=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sUserid, modGeneralMain.compID, "ConsultOnly")
    If res!tot Then
      xx = res!tot
    Else
      res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and flduserid=&2 and fldcomp like &3 and fldmethod=&4", modDate.GetWeekDay(sDate), sUserid, modGeneralMain.compID, "ConsultOnly")
      If res1!tot Then
        xx = res1!tot
      Else
        res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and flduserid=&2 and fldcomp like &3 and fldmethod=&4", "AllDays", sUserid, modGeneralMain.compID, "ConsultOnly")
        If res2!tot Then
          xx = res2!tot
        Else
          xx = 0
        Endif
      Endif
    Endif

  Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
    res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and fldbillingmode like &4 and flduserid=&5 and fldcomp like &6 and fldmethod=&7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sBillMode, sUserid, modGeneralMain.compID, "Consult+Mode")
    If res!tot Then
      xx = res!tot
    Else
      res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and flduserid=&3 and fldcomp like &4 and fldmethod=&5", modDate.GetWeekDay(sDate), sBillMode, sUserid, modGeneralMain.compID, "Consult+Mode")
      If res1!tot Then
        xx = res1!tot
      Else
        res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and flduserid=&3 and fldcomp like &4 and fldmethod=&5", "AllDays", sBillMode, sUserid, modGeneralMain.compID, "Consult+Mode")
        If res2!tot Then
          xx = res2!tot
        Else
          xx = 0
        Endif
      Endif
    Endif

  Else
    If sUserid Then
      res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and (flddept like &3 or flddept=&7) and fldselect=&4 and fldbillingmode like &5 and flduserid=&6 and fldcomp like &8 and fldmethod=&9", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, sUserid, "%", modGeneralMain.compID, "AllParam")
    Else
      res = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddate>=&1 and flddate<=&2 and (flddept like &3 or flddept=&6) and fldselect=&4 and fldbillingmode like &5 and fldcomp like &7 and fldmethod=&8", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, "%", modGeneralMain.compID, "AllParam")
    Endif
    If res!tot Then
      xx = res!tot
    Else
      If sUserid Then
        res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and flduserid=&4 and fldcomp like &5 and fldmethod=&6", sDept, modDate.GetWeekDay(sDate), sBillMode, sUserid, modGeneralMain.compID, "AllParam")
      Else
        res1 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, modDate.GetWeekDay(sDate), sBillMode, modGeneralMain.compID, "AllParam")
      Endif
      If res1!tot Then
        xx = res1!tot
      Else
        If sUserid Then
          res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and flduserid=&4 and fldcomp like &5 and fldmethod=&6", sDept, "AllDays", sBillMode, sUserid, modGeneralMain.compID, "AllParam")
        Else
          res2 = modDatabase.$myConn.Exec("select SUM(fldquota) as tot from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, "AllDays", sBillMode, modGeneralMain.compID, "AllParam")
        Endif
        If res2!tot Then
          xx = res2!tot
        Else
          xx = 0
        Endif
      Endif
    Endif

  Endif
  Return xx

End

Public Function GetUserPostingList(sDept As String, sDate As Date, sBillMode As String) As String[]

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim xx As String[]
  Dim yy As String[]

  xx = New String[]
  If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
    res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and fldcomp like &4 and fldmethod=&5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", modGeneralMain.compID, "ConsultOnly")
    If res.Available Then
      For Each res
        If res!doc Then
          xx.Add(res!doc)
        Endif
      Next
    Endif
    res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldcomp like &2 and fldmethod=&3", modDate.GetWeekDay(sDate), modGeneralMain.compID, "ConsultOnly")
    If res1.Available Then
      For Each res1
        If res1!doc Then
          xx.Add(res1!doc)
        Endif
      Next
    Endif
    res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldcomp like &2 and fldmethod=&3", "AllDays", modGeneralMain.compID, "ConsultOnly")
    If res2.Available Then
      For Each res2
        If res2!doc Then
          xx.Add(res2!doc)
        Endif
      Next
    Endif

  Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
    res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and fldselect=&3 and fldbillingmode like &4 and fldcomp like &5 and fldmethod=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), "Specific", sBillMode, modGeneralMain.compID, "Consult+Mode")
    If res.Available Then
      For Each res
        If res!doc Then
          xx.Add(res!doc)
        Endif
      Next
    Endif
    res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and fldcomp like &3 and fldmethod=&4", modDate.GetWeekDay(sDate), sBillMode, modGeneralMain.compID, "Consult+Mode")
    If res1.Available Then
      For Each res1
        If res1!doc Then
          xx.Add(res1!doc)
        Endif
      Next
    Endif
    res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where fldselect=&1 and fldbillingmode like &2 and fldcomp like &3 and fldmethod=&4", "AllDays", sBillMode, modGeneralMain.compID, "Consult+Mode")
    If res2.Available Then
      For Each res2
        If res2!doc Then
          xx.Add(res2!doc)
        Endif
      Next
    Endif

  Else
    res = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddate>=&1 and flddate<=&2 and flddept like &3 and fldselect=&4 and fldbillingmode like &5 and fldcomp like &6 and fldmethod=&7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, modGeneralMain.compID, "AllParam")
    If res.Available Then
      For Each res
        If res!doc Then
          xx.Add(res!doc)
        Endif
      Next
    Endif
    res1 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, modDate.GetWeekDay(sDate), sBillMode, modGeneralMain.compID, "AllParam")
    If res1.Available Then
      For Each res1
        If res1!doc Then
          xx.Add(res1!doc)
        Endif
      Next
    Endif
    res2 = modDatabase.$myConn.Exec("select distinct(flduserid) as doc from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4 and fldmethod=&5", sDept, "AllDays", sBillMode, modGeneralMain.compID, "AllParam")
    If res2.Available Then
      For Each res2
        If res2!doc Then
          xx.Add(res2!doc)
        Endif
      Next
    Endif

  Endif

  If xx.Count Then
    yy = modString.GetDistinctStringArray(xx)
  Else
    yy = xx
  Endif

  Return yy

End

''------------------------------------ Quota (patient parameters)
Public Function GetPatientBooked(sType As String, sDept As String, sDate As Date, sBillMode As String, sUserid As String) As Integer

  Dim res As Result
  Dim xx As Integer

  If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and flduserid=&3 and fldstate like &4 and fldcomp=&5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, sType, modGeneralMain.compID)

  Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and fldbillingmode like &3 and flduserid=&4 and fldstate like &5 and fldcomp=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, sUserid, sType, modGeneralMain.compID)

  Else
    If sUserid Then
      res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and fldadmitlocat like &3 and fldbillingmode like &4 and flduserid=&5 and fldstate like &6 and fldcomp=&7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, sUserid, sType, modGeneralMain.compID)                                                  ''
    Else
      res = modDatabase.$myConn.Exec("select COUNT(fldbookingval) as tot from tblpatientbook where fldconsultdate>=&1 and fldconsultdate<=&2 and fldadmitlocat like &3 and fldbillingmode like &4 and fldstate like &5 and fldcomp=&6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, sType, modGeneralMain.compID)                                                  ''
    Endif

  Endif
  If res!tot Then
    xx = res!tot
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetPatientRegisteredValid(sDept As String, sDate As Date, sBillMode As String, sUserid As String) As Integer

  Dim res As Result
  Dim xx As Integer

  If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and flduserid=&3 and fldstatus<>&4 and fldcomp like &5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, "Cancelled", modGeneralMain.compID)

  Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldbillingmode like &3 and flduserid=&4 and fldstatus<>&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, sUserid, "Cancelled", modGeneralMain.compID)

  Else
    If sUserid Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and flduserid=&5 and fldstatus<>&6 and fldcomp like &7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, sUserid, "Cancelled", modGeneralMain.compID)
    Else
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and fldstatus<>&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, "Cancelled", modGeneralMain.compID)                                                  ''
    Endif

  Endif

  If res!tot Then
    xx = res!tot
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetPatientRegisteredCancel(sDept As String, sDate As Date, sBillMode As String, sUserid As String) As Integer

  Dim res As Result
  Dim xx As Integer

  If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and flduserid=&3 and fldstatus=&4 and fldcomp like &5", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, "Cancelled", modGeneralMain.compID)

  Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
    res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldbillingmode like &3 and flduserid=&4 and fldstatus=&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, sUserid, "Cancelled", modGeneralMain.compID)

  Else
    If sUserid Then
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and flduserid=&5 and fldstatus=&6 and fldcomp like &7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, sUserid, "Cancelled", modGeneralMain.compID)
    Else
      res = modDatabase.$myConn.Exec("select COUNT(fldid) as tot from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and fldconsultname like &3 and fldbillingmode like &4 and fldstatus=&5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, sBillMode, "Cancelled", modGeneralMain.compID)                                                  ''
    Endif

  Endif

  If res!tot Then
    xx = res!tot
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetQueNumber(sDept As String, sDate As Date, encid As String, sBillMode As String, sUserid As String) As String

  Dim res As Result
  Dim xx As String

  If sUserid Then
    If modBasic.$RegistQuotaQueMode = "ConsultOnly" Then
      res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and flduserid=&3 and fldcomp like &4 ORDER BY fldid ASC", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, modGeneralMain.compID)                    ''
    Else If modBasic.$RegistQuotaQueMode = "Consult+Mode" Then
      res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsulttime>=&1 and fldconsulttime<=&2 and flduserid=&3 and fldbillingmode=&4 and fldcomp like &5 ORDER BY fldid ASC", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sUserid, sBillMode, modGeneralMain.compID)                    ''
    Else
      res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldbillingmode=&4 and flduserid=&5 and fldcomp like &6 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, sUserid, modGeneralMain.compID)                    ''
    Endif
  Else
    res = modDatabase.$myConn.Exec("select fldencounterval from tblconsult where fldconsultname=&1 and fldconsulttime>=&2 and fldconsulttime<=&3 and fldbillingmode=&4 and fldcomp like &5 ORDER BY fldid ASC", sDept, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sBillMode, modGeneralMain.compID)                    ''
  Endif

  If res.Available Then
    For Each res
      If res!fldencounterval = encid Then
        xx = CStr(res.Index + 1)
      Endif
    Next
  Else
    xx = ""
  Endif

  Return xx

End
