' Gambas module file

''--------------------------------------- PATIENT FINDINGS -------------------------------------
Public Sub AddPatientFindings(sType As String, encid As String, txtvalue As String, codeid As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatfindings")
  res["fldtype"] = sType
  res["fldencounterval"] = encid
  res["fldcode"] = txtvalue
  res["fldcodeid"] = codeid
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["xyz"] = False
  res.Update()
  'don't catch error

End

''----------------------------------------- INSERT/UPDATE CLINICAL PLANNING --------------------------------------------------------------------
Public Sub AddPatientPlan(encid As String, strCategory As String, strProblem As String, strSubjective As String, strObjective As String, strAssess As String, strPlan As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatplanning")
  res["fldencounterval"] = encid
  res["fldplancategory"] = strCategory
  res["fldproblem"] = strProblem
  res["fldsubjective"] = strSubjective
  res["fldobjective"] = strObjective
  res["fldassess"] = strAssess
  res["fldplan"] = strPlan
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdatePatientPlan(id As Long, strProblem As String, strSubjective As String, strObjective As String, strAssess As String, strPlan As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatplanning", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["fldproblem"] = strProblem
    res["fldsubjective"] = strSubjective
    res["fldobjective"] = strObjective
    res["fldassess"] = strAssess
    res["fldplan"] = strPlan
    res["flduserid"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

''-----------------------------------INSERT/UPDATE tblpattiming--------------------------------------------------------------------
Public Sub AddPatientTableFirstTime(encid As String, txtcateg As String, txtitem As String, txtval As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpattiming")
  res["fldencounterval"] = encid
  res["fldtype"] = txtcateg
  res["flditem"] = txtitem

  res["fldfirstreport"] = txtval
  res["fldfirstuserid"] = modGeneralMain.$lbluser
  res["fldfirsttime"] = Now()
  res["fldfirstcomp"] = modGeneralMain.compID
  res["fldfirstsave"] = True

  res["fldsecondreport"] = ""
  res["fldseconduserid"] = ""
  res["fldsecondtime"] = ""
  res["fldsecondcomp"] = ""
  res["fldsecondsave"] = False

  res["fldcomment"] = ""
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub UpdatePatientTableSecondTime(id As Long, txtval As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpattiming", "fldid=&1", id)
  res["fldsecondreport"] = txtval
  res["fldseconduserid"] = modGeneralMain.$lbluser
  res["fldsecondtime"] = Now()
  res["fldsecondcomp"] = modGeneralMain.compID
  res["fldsecondsave"] = True
  res["xyz"] = False
  res.Update
  'Dont catch error. Used in billing

End

Public Sub UpdatePatientTableEndTime(encid As String, txtcateg As String, txtitem As String, txtval As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpattiming", "fldencounterval=&1 and fldtype=&2 and flditem=&3 and fldfirstsave=&4", encid, txtcateg, txtitem, True)
  res["fldsecondreport"] = txtval
  res["fldseconduserid"] = modGeneralMain.$lbluser
  res["fldsecondtime"] = Now()
  res["fldsecondcomp"] = modGeneralMain.compID
  res["fldsecondsave"] = True
  res["xyz"] = False
  res.Update
  'dont catch error. used with billing

End

''----------------------------- for exam general ----------------------------------------
Public Sub AddExamGeneralQuantiData(encid As String, strInput As String, strItem As String, strReport As Float, strDetail As String, Optional sUnique As Boolean)

  Dim res As Result
  Dim rsx As Result
  Dim suniq As Boolean

  If sUnique Then
    If sUnique = True Then
      rsx = modDatabase.$myConn.Exec("select fldid from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Quantitative", strItem)
      If rsx.Available Then
        suniq = True
      Else
        suniq = False
      Endif
    Else
      suniq = False
    Endif
  Else
    suniq = False
  Endif

  If suniq = True Then
    res = modDatabase.$myConn.Edit("tblexamgeneral", "fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Quantitative", strItem)
    If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
      res["fldreportquali"] = CStr(strReport)
      res["fldreportquanti"] = strReport
      res["flddetail"] = strDetail
      res["flduserid"] = modGeneralMain.$lbluser
      res["fldcomp"] = modGeneralMain.compID
      res["fldsave"] = True
      res["flduptime"] = Now()
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid"], ("OK"))
    Endif
  Else If suniq = False Then
    res = modDatabase.$myConn.Create("tblexamgeneral")
    res["fldencounterval"] = encid
    res["fldinput"] = strInput
    res["fldtype"] = "Quantitative"
    res["flditem"] = strItem
    res["fldreportquali"] = CStr(strReport)
    res["fldreportquanti"] = strReport
    res["flddetail"] = strDetail
    res["flduserid"] = modGeneralMain.$lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["fldsave"] = True
    res["flduptime"] = ""
    res["xyz"] = False
    res.Update()
    'don't catch error
  Endif

End

Public Sub AddExamGeneralQualiData(encid As String, strInput As String, strItem As String, strReport As String, strDetail As String, Optional sUnique As Boolean)

  Dim res As Result
  Dim rsx As Result
  Dim suniq As Boolean

  If sUnique Then
    If sUnique = True Then
      rsx = modDatabase.$myConn.Exec("select fldid from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Qualitative", strItem)
      If rsx.Available Then
        suniq = True
      Else
        suniq = False
      Endif
    Else
      suniq = False
    Endif
  Else
    suniq = False
  Endif

  If suniq = True Then
    res = modDatabase.$myConn.Edit("tblexamgeneral", "fldencounterval=&1 and fldinput=&2 and fldtype=&3 and flditem=&4", encid, strInput, "Qualitative", strItem)
    If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
      res["fldreportquali"] = strReport
      res["fldreportquanti"] = 0
      res["flddetail"] = strDetail
      res["flduserid"] = modGeneralMain.$lbluser
      res["fldcomp"] = modGeneralMain.compID
      res["fldsave"] = True
      res["flduptime"] = Now()
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid"], ("OK"))
    Endif
  Else If suniq = False Then
    res = modDatabase.$myConn.Create("tblexamgeneral")
    res["fldencounterval"] = encid
    res["fldinput"] = strInput
    res["fldtype"] = "Qualitative"
    res["flditem"] = strItem
    res["fldreportquali"] = strReport
    res["fldreportquanti"] = 0
    res["flddetail"] = strDetail
    res["flduserid"] = modGeneralMain.$lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["fldsave"] = True
    res["flduptime"] = ""
    res["xyz"] = False
    res.Update()
    'don't catch error
  Endif

End

Public Sub AddExamGeneralQualiQuantiData(encid As String, strInput As String, strItem As String, strReport As String, strValue As Float, strDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblexamgeneral")
  res["fldencounterval"] = encid
  res["fldinput"] = strInput
  res["fldtype"] = "Qualitative"
  res["flditem"] = strItem
  res["fldreportquali"] = strReport
  res["fldreportquanti"] = strValue
  res["flddetail"] = strDetail
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update()
  'don't catch error

End

''Update
Public Sub UpdateExamGeneralQualiData(id As Long, strItem As String, strReport As String, strDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblexamgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["flditem"] = strItem
    res["fldreportquali"] = strReport
    res["flddetail"] = strDetail
    res["flduserid"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

Public Sub UpdateExamGeneralQuantiData(id As Long, strItem As String, strReport As Float, strDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblexamgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["flditem"] = strItem
    res["fldreportquali"] = CStr(strReport)
    res["fldreportquanti"] = strReport
    res["flddetail"] = strDetail
    res["flduserid"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

''-------------------------------- INSERT/UPDATE  tblpatgeneral----------------------------------------------------------------
Public Sub AddProcedureData(encid As String, strInput As String, strItem As String, strReport As String, sMode As String, dt As Date, sStatus As String, sSummary As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatgeneral")
  res["fldencounterval"] = encid
  res["fldinput"] = strInput
  res["flditem"] = strItem
  res["fldreportquali"] = strReport
  res["flddetail"] = sSummary
  res["fldnewdate"] = dt
  res["fldbillingmode"] = sMode
  res["fldorduserid"] = modGeneralMain.$lbluser
  res["flduserid"] = ""
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = False
  res["fldstatus"] = sStatus
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update()
  'don't catch error

End

''------------------------------------- sub General --------------------------------------------------------
Public Sub AddSubGeneralQualiData(sID As Long, encid As String, sCategory As String, sValue As String, sDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatsubgeneral")
  res["flditemid"] = sID
  res["fldencounterval"] = encid
  res["fldchapter"] = sCategory
  res["fldreportquali"] = sValue
  res["fldreportquanti"] = 0
  res["fldreport"] = sDetail
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub AddSubGeneralQuantiData(sID As Long, encid As String, sCategory As String, sValue As Float, sDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatsubgeneral")
  res["flditemid"] = sID
  res["fldencounterval"] = encid
  res["fldchapter"] = sCategory
  res["fldreportquali"] = ""
  res["fldreportquanti"] = sValue
  res["fldreport"] = sDetail
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update
  'don't catch error

End

Public Sub EditSUbGeneralDetail(id As Long, sDetail As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatsubgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["fldreport"] = sDetail
    res["flduptime"] = Now()
    res["flduserid"] = modGeneralMain.$lbluser
    res["xyz"] = False
    res.Update
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

''---------------------------------- Monitoring ------------------------------------
Public Sub AddMonitoringData(encid As String, sCategory As String, sItem As String, sEvery As Integer, sUnit As String, sType As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblmonitor")
  res["fldencounterval"] = encid
  res["fldcategory"] = sCategory
  res["flditem"] = sItem
  res["fldevery"] = sEvery
  res["fldunit"] = sUnit
  res["fldtype"] = sType
  res["fldstatus"] = "Continue"
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["xyz"] = False
  res.Update

End

Public Function GetNutritionValue(sType As String, sItem As String, sAmt As Float, sField As String) As Float

  Dim totfld As Float
  Dim res1 As Result
  Dim totpor As Float

  If sType = "Mixture" Then
    totfld = 0
    res1 = modDatabase.$medConn.Exec("select flditemname,flditemamt from tblfoodgroup where fldgroup=&1", sItem)
    totpor = 0
    If res1.Available Then
      For Each res1
        If res1!flditemamt Then
          totpor = totpor + res1!flditemamt
        Endif
      Next
      If totpor Then
        For Each res1
          totfld = totfld + (res1!flditemamt / totpor) * (modFixPatho.GetFoodTableValue(res1!flditemname, sField) * sAmt) / 100
        Next
      Else
        totfld = 0
      Endif
    Endif

  Else
    totfld = (modFixPatho.GetFoodTableValue(sItem, sField) * sAmt) / 100
  Endif
  Return totfld

End

Public Function GetTotalCoponentFood(id As Long, sField As String) As Float

  Dim res As Result
  Dim totfld As Float

  res = modDatabase.$myConn.Exec("select flditem,fldreportquanti,fldreportquali from tblexamgeneral where fldid=&1", id)
  If res.Available Then
    If res!fldreportquanti Then
      totfld = GetNutritionValue(res!fldreportquali, res!flditem, res!fldreportquanti, sField)
    Else
      totfld = 0
    Endif
  Else
    totfld = 0
  Endif
  Return Round(totfld, -3)

End

Public Function GetFrequencyValue(sFreq As String) As Integer

  Dim xx As Integer

  If sFreq = "1 Hourly" Then
    xx = 1
  Else If sFreq = "2 Hourly" Then
    xx = 2
  Else If sFreq = "3 Hourly" Then
    xx = 3
  Else If sFreq = "4 Hourly" Then
    xx = 4
  Else If sFreq = "6 Hourly" Then
    xx = 6
  Else If sFreq = "12 Hourly" Then
    xx = 12
  Else If sFreq = "24 Hourly" Then
    xx = 24
  Endif
  Return xx

End

Public Function GetALLReportFoodSelString(encid As String, sFood As String, sDate As Date) As String[]

  Dim sql As String
  Dim res As Result
  Dim xList As String[]

  xList = New String[]
  sql = "select fldreportquali,fldreportquanti,fldtime from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and flditem=&3 and fldtime>=&4 and fldtime<=&5"
  res = modDatabase.$syConn.Exec(sql, encid, "Input Food/Fluid", sFood, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate))
  If res.Available = True Then
    For Each res
      If res!fldreportquanti Then
        xList.Add("[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime) & " ] " & " : " & CStr(res!fldreportquanti) & Space(1) & "GRAMS")
      Endif
    Next
  Endif
  Return xList

End

'''---------------------------------------History -----------------------------------------
Public Function ShowSelectedHistory(encid As String, sType As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flddetail from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and flditem=&3", encid, "History", sType)
  If res.Available Then
    res.MoveLast
    If res!flddetail Then
      xx = res!flddetail
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function ShowSelectedNotes(encid As String, sType As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flddetail from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and flditem=&3", encid, "Notes", sType)
  If res.Available Then
    res.MoveLast
    If res!flddetail Then
      xx = res!flddetail
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''''------------------------------------------------ SYMPTOMS --------------------------------------------------------------
Public Function GetSymptomFromSymID(symid As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flditem from tblexamgeneral where fldid=&1", symid)
  If res.Available Then
    If res!flditem Then
      xx = res!flditem
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetEncIDFromSymID(symid As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldencounterval from tblexamgeneral where fldid=&1", symid)
  If res.Available Then
    If res!fldencounterval Then
      xx = res!fldencounterval
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetSymptomTypePatient(symid As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldreportquali from tblexamgeneral where fldid=&1", symid)

  If res.Available Then
    If res!fldreportqual Then
      xx = res!fldreportquali
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetComplaintsPatient(symid As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldreportquanti,fldreportquali from tblexamgeneral where fldid=&1", symid)

  If res.Available Then
    If res!fldreportquanti Then
      xx = CStr(res!fldreportquanti) & Space(1) & res!fldreportquali
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetComplainDayByID(symid As Long) As Float

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select fldreportquanti,fldreportquali from tblexamgeneral where fldid=&1", symid)
  If res.Available Then
    If res!fldreportquanti Then
      If res!fldreportquali = "Hours"
        xx = Round(res!fldreportquanti / 24, -2)
      Else If res!fldreportquali = "Days"
        xx = res!fldreportquanti
      Else If res!fldreportquali = "Weeks"
        xx = res!fldreportquanti * 7
      Else If res!fldreportquali = "Months"
        xx = res!fldreportquanti * 30
      Else If res!fldreportquali = "Years"
        xx = res!fldreportquanti * 365
      Endif
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

'NOTE:TWO CON
Public Function GetPatientDrugSymptom(sympid As Long) As String

  Dim xxx As String
  Dim res As Result

  xxx = ""
  res = modDatabase.$myConn.Exec("select distinct(fldparent) from tblmedadveffect where fldchild=&1 and fldparent in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid in(select flditem from tblpatdosing where fldencounterval=&2)))", GetSymptomFromSymID(sympid), GetEncIDFromSymID(sympid))                                                       ''
  If res.Available = True Then
    xxx = "Drugs causing: " & modFillContainer.GetListFromResult(res).Join(";")
  Endif

  Return xxx

End

'NOTE:TWO CON
Public Function GetPatientDiseaseSymptom(sympid As Long) As String

  Dim xxx As String
  Dim res As Result

  xxx = ""
  res = modDatabase.$myConn.Exec("select distinct(fldparent) from tblpathosymp where fldchild=&1 and fldparent in(select fldcode from tblpatfindings where fldencounterval=&2 and fldsave=&3)", GetSymptomFromSymID(sympid), GetEncIDFromSymID(sympid), True)                                                       ''
  If res.Available = True Then
    xxx = "Disease causing: " & modFillContainer.GetListFromResult(res).Join(";")
  Endif

  Return xxx

End

''---------------------------------------------------equipment/service duration----------------------------------------------------------------------------
Public Function GetEquiDurationSetting(sType As String, sMode As String, dt1 As Date, dt2 As Date, xbol As Boolean) As Float

  Dim hr As Float
  Dim xequip As String
  Dim xservice As String

  If sType = "Equipment" Then
    xequip = modGlobalSetting.ShowSettingFromDB("EquipmentDurationRounding/Method")

    If sMode = "Minute" Then
      If modGlobalSetting.ShowSettingFromDB("EquipmentDurationRounding/Minute") = "Yes" Then
        If xequip = "Smart" Then
          If xbol = True Then
            hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 60)
          Else If xbol = False Then
            hr = 0
          Endif
        Else
          hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 60)
        Endif
      Else
        hr = Round(DateDiff(dt1, dt2, gb.Second) / 60, -2)
      Endif

    Else If sMode = "Hour" Then
      If modGlobalSetting.ShowSettingFromDB("EquipmentDurationRounding/Hour") = "Yes" Then
        If xequip = "Smart" Then
          If xbol = True Then
            hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 3660)
          Else If xbol = False Then
            hr = 0
          Endif
        Else
          hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 3660)
        Endif
      Else
        hr = Round(DateDiff(dt1, dt2, gb.Second) / 3660, -2)
      Endif

    Else If sMode = "Day" Then
      If modGlobalSetting.ShowSettingFromDB("EquipmentDurationRounding/Day") = "Yes" Then
        If xequip = "Smart" Then
          If xbol = True Then
            hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 86400)
          Else If xbol = False Then
            hr = 0
          Endif
        Else
          hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 86400)
        Endif
      Else
        hr = Round(DateDiff(dt1, dt2, gb.Second) / 86400, -2)
      Endif
    Endif

  Else If sType = "General Services" Then
    xservice = modGlobalSetting.ShowSettingFromDB("ServiceDurationRounding/Method")

    If sMode = "Minute" Then
      If modGlobalSetting.ShowSettingFromDB("ServiceDurationRounding/Minute") = "Yes" Then
        If xservice = "Smart" Then
          If xbol = True Then
            hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 60)
          Else If xbol = False Then
            hr = 0
          Endif
        Else
          hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 60)
        Endif
      Else
        hr = Round(DateDiff(dt1, dt2, gb.Second) / 60, -2)
      Endif
    Else If sMode = "Hour" Then
      If modGlobalSetting.ShowSettingFromDB("ServiceDurationRounding/Hour") = "Yes" Then
        If xservice = "Smart" Then
          If xbol = True Then
            hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 3660)
          Else If xbol = False Then
            hr = 0
          Endif
        Else
          hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 3660)
        Endif
      Else
        hr = Round(DateDiff(dt1, dt2, gb.Second) / 3660, -2)
      Endif
    Else If sMode = "Day" Then
      If modGlobalSetting.ShowSettingFromDB("ServiceDurationRounding/Day") = "Yes" Then
        If xservice = "Smart" Then
          If xbol = True Then
            hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 86400)
          Else If xbol = False Then
            hr = 0
          Endif
        Else
          hr = Ceil(DateDiff(dt1, dt2, gb.Second) / 86400)
        Endif
      Else
        hr = Round(DateDiff(dt1, dt2, gb.Second) / 86400, -2)
      Endif
    Endif

  Endif   ''service or equipment

  Return hr
  'don't catch error. used for billing

End

Public Function GetServiceUseDuration(encid As String, sType As String, txtitem As String, sMode As String, dt1 As Date, dt2 As Date) As Float

  Dim hr As Float
  Dim sql As String
  Dim res As Result
  Dim xbol As Boolean

  If sMode = "Unit" Then
    hr = 1
  Else

    sql = "select fldfirsttime,fldsecondtime from tblpattiming where fldencounterval=&1 and fldtype=&2 and flditem=&3 and fldfirstsave=&4 and fldsecondsave=&5 and fldsecondtime>=&6 and fldsecondtime<=&7"
    If sMode = "Minute" Then
      res = modDatabase.$myConn.Exec(sql, encid, sType, txtitem, True, True, modDate.StartSqlMinute(Now()), modDate.EndSqlMinute(Now()))
    Else If sMode = "Hour" Then
      res = modDatabase.$myConn.Exec(sql, encid, sType, txtitem, True, True, modDate.StartSqlHour(Now()), modDate.EndSqlHour(Now()))
    Else
      res = modDatabase.$myConn.Exec(sql, encid, sType, txtitem, True, True, modDate.StartSqlDate(Now()), modDate.EndSqlDate(Now()))
    Endif
    If res.Available Then
      If res.Count = 1 Then
        xbol = True
      Else If res.Count > 1 Then
        xbol = False
      Endif
      hr = GetEquiDurationSetting(sType, sMode, dt1, dt2, xbol)
    Else
      hr = 0
    Endif

  Endif ''unit or time

  Return hr
  'don't catch error. used for billing

End

Public Function GetEquipServiceInterval(sdid As Long) As String

  Dim res As Result
  Dim xdura As String
  Dim sMode As String
  Dim xhr As Float

  res = modDatabase.$myConn.Exec("select fldencounterval,fldtype,flditem,fldfirsttime,fldsecondtime from tblpattiming where fldfirstsave=&1 and fldsecondsave=&2 and fldid=&3", True, True, sdid)
  If res.Available Then
    sMode = modNonMedical.GetBillingTargeDept(res!flditem, res!fldtype)
    If sMode Then
      If sMode = "Unit" Then
        xdura = "1 Unit"
      Else
        xhr = GetEquiDurationSetting(res!fldtype, sMode, res!fldfirsttime, res!fldsecondtime, True)
        xdura = CStr(xhr) & Space(1) & sMode
      Endif
    Else
      xdura = CStr(DateDiff(res!fldfirsttime, res!fldsecondtime, gb.Hour)) & Space(1) & "Hours"
    Endif
  Endif

  Return xdura

End

''
Public Function GetBedTransitionInterval(sdid As Long) As String

  Dim res As Result
  Dim xdura As String
  Dim sMode As String
  Dim xhr As Float

  res = modDatabase.$myConn.Exec("select fldencounterval,fldtype,flditem,fldfirsttime,fldsecondtime from tblpattiming where fldfirstsave=&1 and fldsecondsave=&2 and fldid=&3", True, True, sdid)
  If res.Available Then
    sMode = modNonMedical.GetBillingTargeDept(modNonMedical.GetDepartmentChargeMode(res!flditem), res!fldtype)
    If sMode Then
      If sMode = "Unit" Then
        xdura = "1 Unit"
      Else
        xhr = GetEquiDurationSetting(res!fldtype, sMode, res!fldfirsttime, res!fldsecondtime, True)
        xdura = CStr(xhr) & Space(1) & sMode
      Endif
    Else
      xdura = CStr(DateDiff(res!fldfirsttime, res!fldsecondtime, gb.Hour)) & Space(1) & "Hours"
    Endif
  Endif

  Return xdura

End

Public Function GetPatientTransition(encid As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  xxx = New String[]
  res = modDatabase.$myConn.Exec("select fldid,flditem,fldfirsttime,fldsecondtime,fldsecondreport from tblpattiming where fldencounterval=&1 and fldtype=&2 and fldfirstreport=&3", encid, "General Services", "Bed")
  If res.Available Then
    For Each res
      If res!fldsecondreport Then
        xxx.Add(res!flditem & " [" & res!fldsecondreport & "] : " & modReportVar.GetDateTimeReport(res!fldfirsttime, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(res!fldsecondtime, gb.GeneralDate) & " :: " & Format(DateDiff(res!fldfirsttime, res!fldsecondtime, gb.Minute) / 1440, gb.Fixed) & " Day")
      Endif
    Next
  Endif
  Return xxx

End

Public Function GetPatientEquipmentUse(encid As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  xxx = New String[]
  res = modDatabase.$myConn.Exec("select flditem,fldfirsttime,fldsecondtime,fldsecondreport from tblpattiming where fldencounterval=&1 and fldtype=&2", encid, "Equipment")
  If res.Available Then
    For Each res
      xxx.Add(res!flditem & " : " & modReportVar.GetDateTimeReport(res!fldfirsttime, gb.GeneralDate) & " TO " & modReportVar.GetDateTimeReport(res!fldsecondtime, gb.GeneralDate))
    Next
  Endif
  Return xxx

End

''----------------------------------------- PROCEDURE ---------------------------------------------------------
Public Sub GetProcedureListByPatient(lstbx As ListBox, encid As String)

  Dim sql As String
  Dim res As Result

  sql = "select distinct(flditem) as col from tblpatgeneral where fldencounterval=&1 and fldinput=&2"
  res = modDatabase.$myConn.Exec(sql, encid, "Procedures")
  modFillContainer.FillListBox(lstbx, res, False)

End

Public Function PatSelectProcedureString(encid As String, strType As String, sCondi As String) As String

  Dim res As Result
  Dim xx As String

  xx = ""
  res = modDatabase.$myConn.Exec("select fldid,fldencounterval,fldnewdate,flditem,flddetail from tblpatgeneral where fldencounterval=&1 and fldinput=&2 and fldreportquali=&3", encid, strType, sCondi)
  If res.Available = True Then
    For Each res
      If res!flditem And If res!flddetail Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx = xx & "[" & modReportVar.GetDateTimeReport(res!fldnewdate, gb.GeneralDate) & "] " & res!flditem & " :: " & gb.NewLine
          xx = xx & Space(5) & GetComponentProcedure(res!fldencounterval, res!fldid).Join(gb.NewLine & Space(5)) & gb.NewLine
          xx = xx & "SUMMARY : " & gb.NewLine & res!flddetail & gb.NewLine
        Else
          xx = xx & res!flditem & " :: " & gb.NewLine
          xx = xx & Space(5) & GetComponentProcedure(res!fldencounterval, res!fldid).Join(gb.NewLine & Space(5)) & gb.NewLine
          xx = xx & "SUMMARY : " & gb.NewLine & res!flddetail & gb.NewLine
        Endif
      Else If res!flditem Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx = xx & "[" & modReportVar.GetDateTimeReport(res!fldnewdate, gb.GeneralDate) & "] " & res!flditem & gb.NewLine
          xx = xx & Space(5) & GetComponentProcedure(res!fldencounterval, res!fldid).Join(gb.NewLine & Space(5)) & gb.NewLine
        Else
          xx = xx & res!flditem & gb.NewLine
          xx = xx & Space(5) & GetComponentProcedure(res!fldencounterval, res!fldid).Join(gb.NewLine & Space(5)) & gb.NewLine
        Endif
      Endif
    Next
  Endif

  Return xx

End

Public Function GetComponentProcedure(encid As String, itemid As Long) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select fldreportquali from tblpatsubgeneral where flditemid=&1 and fldchapter=&2 and fldencounterval=&3", itemid, "Components", encid)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function GetDiscusPanels(encid As String, itemid As Long) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select fldreportquali from tblpatsubgeneral where flditemid=&1 and fldchapter=&2 and fldencounterval=&3", itemid, "Discussion Panel", encid)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function GetProcedureItemValue(encid As String, itemid As Long, sType As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldreportquali from tblpatsubgeneral where flditemid=&1 and fldchapter=&2 and fldencounterval=&3", itemid, sType, encid)
  If res.Available Then
    res.MoveLast
    If res!fldreportquali Then
      xx = res!fldreportquali
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetUniProcedureDetail(encid As String, itemid As Long, sType As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldreport from tblpatsubgeneral where flditemid=&1 and fldchapter=&2 and fldencounterval=&3", itemid, sType, encid)
  If res.Available Then
    res.MoveLast
    If res!fldreport Then
      xx = res!fldreport
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetUniProcedureUserList(encid As String, itemid As Long, sType As String) As String[]

  Dim res As Result
  Dim xx As String[]

  xx = New String[]
  res = modDatabase.$myConn.Exec("select fldreportquali from tblpatsubgeneral where flditemid=&1 and fldchapter=&2 and fldencounterval=&3", itemid, sType, encid)
  If res.Available Then
    xx.Add(modGeneral.GetUserFullName(res!fldreportquali))
  Endif
  Return xx

End

Public Function GetUserAllUniProcedure(encid As String, itemid As Long) As String

  Dim xx As String

  xx = ""
  xx = xx & "Surgeon: " & GetUniProcedureUserList(encid, itemid, "Surgeon").Join(",") & gb.NewLine
  xx = xx & "Anaesthetist: " & GetUniProcedureUserList(encid, itemid, "Anaesthetist").Join(",") & gb.NewLine
  xx = xx & "Scrub Nurse: " & GetUniProcedureUserList(encid, itemid, "Scrub Nurse").Join(",") & gb.NewLine
  xx = xx & "Count Nurse: " & GetUniProcedureUserList(encid, itemid, "Count Nurse").Join(",") & gb.NewLine
  xx = xx & "Assistant: " & GetUniProcedureUserList(encid, itemid, "Assistant").Join(",") & gb.NewLine
  Return xx

End

''------------------------------- Particular values --------------------------------
Public Function GetDemographicValue(encid As String, sDemographic As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldreportquali from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and flditem=&3", encid, "Demographics", sDemographic)
  If res.Available Then
    If res!fldreportquali Then
      xx = res!fldreportquali
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetQuantiObstetricValue(encid As String, sHead As String) As Float

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select fldreportquanti from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and flditem=&3 and fldtype=&4", encid, "Obstetrics", sHead, "Quantitative")
  If res.Available Then
    res.MoveLast
    If res!fldreportquanti Then
      xx = res!fldreportquanti
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetQualiiObstetricValue(encid As String, sHead As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldreportquali from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and flditem=&3 and fldtype=&4", encid, "Obstetrics", sHead, "Qualitative")
  If res.Available Then
    res.MoveLast
    If res!fldreportquali Then
      xx = res!fldreportquali
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

'''---------------------------------------------- Monitoring -------------------------------
Public Function GetMonitorList(encid As String, sCategory As String, sStatus As String, sType As String) As String[]

  Dim xx As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select flditem from tblmonitor where fldencounterval=&1 and fldcategory=&2 and fldstatus like &3 and fldtype like &4", encid, sCategory, sStatus, sType)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

''---------------------- Extra Procedure ----------------------------
Public Function GetExtProcId(encid As String, xinput As String, xhead As String) As Long

  Dim res As Result
  Dim xval As Long

  res = modDatabase.$myConn.Exec("select fldid from tblpatientexam where fldencounterval=&1 and fldinput like &2 and fldsave=&3 and fldhead=&4", encid, xinput, True, xhead)
  If res.Available Then
    res.MoveLast
    xval = res!fldid
  Endif
  Return xval

End

Public Function GetExtProcedTable(xid As Long, encid As String, sProcName As String) As String

  Dim xval As String
  Dim xstr As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select distinct(fldhead) as col from tblpatientexam where fldencounterval=&1 and fldinput like &2 and fldsave=&3", encid, "%:" & sProcName & ":" & CStr(xid), True)
  If res.Available Then
    xval = modRepoTemplete.HTMLTableSyntax()

    xval = xval & "<tr>" & gb.NewLine
    xstr = New String[]
    xstr.Add("<td>" & "Examination" & "</td>" & gb.NewLine)
    xstr.Add("<td>" & "Pre-Procedure" & "</td>" & gb.NewLine)
    xstr.Add("<td>" & "On-Procedure" & "</td>" & gb.NewLine)
    xstr.Add("<td>" & "Post-Procedure" & "</td>" & gb.NewLine)
    xval = xval & xstr.Join(gb.NewLine)
    xval = xval & "</tr>" & gb.NewLine

    For Each res
      xval = xval & "<tr>" & gb.NewLine
      xstr = New String[]
      xstr.Add("<td>" & res!col & "</td>" & gb.NewLine)
      xstr.Add("<td>" & modClinic.GetExamValueSubString(modPatientGeneral.GetExtProcId(encid, "Pre:" & sProcName & ":" & CStr(xid), res!col)) & "</td>" & gb.NewLine)
      xstr.Add("<td>" & modClinic.GetExamValueSubString(modPatientGeneral.GetExtProcId(encid, "On:" & sProcName & ":" & CStr(xid), res!col)) & "</td>" & gb.NewLine)
      xstr.Add("<td>" & modClinic.GetExamValueSubString(modPatientGeneral.GetExtProcId(encid, "Post:" & sProcName & ":" & CStr(xid), res!col)) & "</td>" & gb.NewLine)
      xval = xval & xstr.Join(gb.NewLine)
      xval = xval & "</tr>" & gb.NewLine
    Next

    xval = xval & "</table>" & gb.NewLine
    xval = xval & "<br>"
  Endif
  Return xval

End
