' Gambas module file

'Note:----------------------- Insert/Update Dosing Table ---------------------------------
Public Sub InsertDosingEntry(encid As String, txtroute As String, txtitem As String, txtdose As Float, txtfreq As String, txtday As Float, txtqty As Float, PatStatus As String, txtprescriber As String, txtregno As String, startDay As Integer, taxper As Float, discper As Float, Optional OrderType As String, Optional DeptID As String)

  Dim res As Result
  Dim order As String
  Dim disptype As String
  Dim xstart As Date

  If DeptID Then
    disptype = DeptID
  Else
    disptype = "OPD"
  Endif
  If OrderType Then
    order = OrderType
  Else
    order = "UseOwn"
  Endif
  If startDay Then
    xstart = DateAdd(Now(), gb.Hour, startDay)
  Else
    xstart = Now()
  Endif

  res = modDatabase.$myConn.Create("tblpatdosing")
  res["fldencounterval"] = encid
  res["flditemtype"] = "Medicines"
  res["fldroute"] = txtroute
  res["flditem"] = txtitem
  res["flddose"] = txtdose
  res["fldfreq"] = txtfreq
  res["flddays"] = txtday
  res["fldqtydisp"] = txtqty
  res["fldqtyret"] = 0
  res["fldprescriber"] = txtprescriber
  res["fldregno"] = txtregno
  res["fldlevel"] = "Requested" ''changes to Dispensed (Only used to indicate dispensing when cash billing done before real dispensing)

  res["flddispmode"] = disptype  ''Requesting Dept (OPD/IPD/Aseptic/Delivery/Pre-Operative:<val> etc)
  res["fldorder"] = order     ''whether request or useown stock
  res["fldcurval"] = "Continue"    ''clinician order to continue to Hold
  res["fldstarttime"] = xstart
  res["fldendtime"] = ""     ''when dosing regimen expires
  res["fldtaxper"] = taxper
  res["flddiscper"] = discper

  res["flduserid_order"] = modGeneralMain.$lbluser  ''on insert record
  res["fldtime_order"] = Now()
  res["fldcomp_order"] = modGeneralMain.compID
  res["fldsave_order"] = False
  res["flduserid"] = ""    ''on dispensing
  res["fldtime"] = ""
  res["fldcomp"] = ""

  res["fldsave"] = True  ''if data appears online in pharmacy on pressing F2 for Reuested only
  If modPharmLabel.ForceLabelPrint(txtitem) = True Then
    res["fldlabel"] = True
  Else
    res["fldlabel"] = False   ''if label is printed
  Endif
  res["fldstatus"] = PatStatus   ''status of patient (admitted or discharged
  res["flduptime"] = ""    ''date of data update
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub InsertNonMedDosingEntry(encid As String, txtroute As String, txtitem As String, txtqty As Float, PatStatus As String, startDay As Integer, taxper As Float, discper As Float, Optional OrderType As String, Optional DeptID As String)

  Dim res As Result
  Dim order As String
  Dim disptype As String
  Dim xstart As Date

  If DeptID Then
    disptype = DeptID
  Else
    disptype = "OPD"
  Endif
  If OrderType Then
    order = OrderType
  Else
    order = "UseOwn"
  Endif
  If startDay Then
    xstart = DateAdd(Now(), gb.Hour, startDay)
  Else
    xstart = Now()
  Endif

  res = modDatabase.$myConn.Create("tblpatdosing")
  res["fldencounterval"] = encid
  res["flditemtype"] = modNonMedical.GetBillItemCategoryFromCombo(txtroute)
  res["fldroute"] = txtroute
  res["flditem"] = txtitem
  res["flddose"] = 0
  res["fldfreq"] = ""
  res["flddays"] = 0
  res["fldqtydisp"] = txtqty
  res["fldqtyret"] = 0
  res["fldprescriber"] = ""
  res["fldregno"] = ""
  res["fldlevel"] = "Requested"

  res["flddispmode"] = disptype
  res["fldorder"] = order
  res["fldcurval"] = "Continue"
  res["fldstarttime"] = xstart
  res["fldendtime"] = ""
  res["fldtaxper"] = taxper
  res["flddiscper"] = discper

  res["flduserid_order"] = modGeneralMain.$lbluser
  res["fldtime_order"] = Now()
  res["fldcomp_order"] = modGeneralMain.compID
  res["fldsave_order"] = False
  res["flduserid"] = ""
  res["fldtime"] = ""
  res["fldcomp"] = ""

  res["fldsave"] = True
  res["fldlabel"] = False
  res["fldstatus"] = PatStatus
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateDispensing(did As Long, dispensed As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  res["fldsave_order"] = True
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldendtime"] = DateAdd(res["fldstarttime"], gb.Day, CInt(res["flddays"]))
  If dispensed = True Then
    res["fldlevel"] = "Dispensed"
  Endif
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Function DisableDispOnline(did As Long)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    res["fldsave"] = False
    res["xyz"] = False
    res.Update()
  Endif
  'don't catch error

End

Public Sub UpdateStartBefDispensing(did As Long, Value As Date)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    If modGeneral.AllowClinicalEdit(res["flduserid_order"]) = True Then
      res["fldstarttime"] = Value
      res["flduptime"] = Now()
      res["fldcomp_order"] = modGeneralMain.compID
      res["flduserid_order"] = modGeneralMain.$lbluser
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid_order"], ("OK"))
    Endif
  Endif
  'don't catch error

End

Public Sub UpdateStartAfterDispensing(did As Long, Value As Date)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    If modGeneral.AllowClinicalEdit(res["flduserid_order"]) = True Then
      res["fldstarttime"] = Value
      res["flduptime"] = Now()
      res["fldendtime"] = DateAdd(Value, gb.Day, CInt(res["flddays"]))
      res["flduserid_order"] = modGeneralMain.$lbluser
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid_order"], ("OK"))
    Endif
  Endif
  'don't catch error

End

Public Sub UpdateDoseBefDispensing(did As Long, Value As Float)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    If modGeneral.AllowClinicalEdit(res["flduserid_order"]) = True Then
      res["flddose"] = Value
      res["flduptime"] = Now()
      res["fldcomp_order"] = modGeneralMain.compID
      res["flduserid_order"] = modGeneralMain.$lbluser
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid_order"], ("OK"))
    Endif
  Endif
  'don't catch error

End

Public Sub UpdateFreqBefDispensing(did As Long, Value As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    If modGeneral.AllowClinicalEdit(res["flduserid_order"]) = True Then
      res["fldfreq"] = Value
      res["flduptime"] = Now()
      res["fldcomp_order"] = modGeneralMain.compID
      res["flduserid_order"] = modGeneralMain.$lbluser
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid_order"], ("OK"))
    Endif
  Endif
  'don't catch error

End

Public Sub UpdateDaysBefDispensing(did As Long, Value As Float)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    If modGeneral.AllowClinicalEdit(res["flduserid_order"]) = True Then
      res["flddays"] = Value
      res["flduptime"] = Now()
      res["fldcomp_order"] = modGeneralMain.compID
      res["flduserid_order"] = modGeneralMain.$lbluser
      res["xyz"] = False
      res.Update()
    Else
      Message.Warning("Authorization with " & res["flduserid_order"], ("OK"))
    Endif
  Endif
  'don't catch error

End

Public Sub UpdateQTYBefDispensing(did As Long, Value As Float)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    res["fldqtydisp"] = Value
    res["flduserid_order"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp_order"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Endif
  'don't catch error

End

Public Sub UpdateDiscPerDispensing(did As Long, Value As Float)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    res["flddiscper"] = Value
    res["flduserid_order"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp_order"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Endif
  'don't catch error

End

Public Sub UpdateTaxPerDispensing(did As Long, Value As Float)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatdosing", "fldid=&1", did)
  If res.Available Then
    res["fldtaxper"] = Value
    res["flduserid_order"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp_order"] = modGeneralMain.compID
    res["xyz"] = False
    res.Update()
  Endif
  'don't catch error

End

Public Sub DuplicateRecordWithQTY(did As Long, qty As Float)

  Dim rs As Result
  Dim hField As ResultField
  Dim res As Result

  rs = modDatabase.$myConn.Exec("select *from tblpatdosing where fldid=&1", did)
  res = modDatabase.$myConn.Create("tblpatdosing")
  For Each hField In rs.Fields
    If hField.Name = "fldqtydisp" Then
      res[hField.Name] = qty
    Else If hField.Name = "fldqtyret" Then
      res[hField.Name] = 0
    Else
      res[hField.Name] = rs[hField.Name]
    Endif
  Next
  res.Update
  'don't catch error

End

Public Sub InsertNurDosing(dosid As Long, encid As String, Value As Float, sUnit As String, sStart As Date)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblnurdosing")
  res["fldencounterval"] = encid
  res["flddoseno"] = dosid
  res["fldvalue"] = Value
  res["fldunit"] = sUnit
  res["fldfromtime"] = sStart
  res["fldtotime"] = ""
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["xyz"] = False
  res.Update
  'don't catch error

End

'NOTE:------------------------------- PHARMACY FUNCTIONS --------------------------------------
Public Function GetStockIDFromDosing(dosid As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flditem from tblpatdosing where fldid=&1", dosid)
  If res.Available Then
    If res!flditem Then
      xx = res!flditem
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetRouteFromDosing(dosid As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldroute from tblpatdosing where fldid=&1", dosid)
  If res.Available Then
    If res!fldroute Then
      xx = res!fldroute
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetDailyDoseFromDosing(dosid As Long) As Float

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select flddose,fldfreq from tblpatdosing where fldid=&1", dosid)
  If res.Available Then
    If res!flddose Then
      xx = res!flddose * modPharmLabel.ConvertFrequencyToNumber(res!fldfreq)
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

'NOTE:----------------------------------------- Dosing Record --------------------------------------------
Public Function GetMedFormatForMedReport(txtitemname As String, txtroute As String) As String

  Dim bch As String
  Dim xform As String

  xform = modSettings.ShowSettingFromFIle("ClinicalReport/MedicineName_Format")
  If xform Then
    If txtroute <> "suture" And If txtroute <> "msurg" And If txtroute <> "ortho" And If txtroute <> "extra" Then
      bch = modPharmLabel.GetMedicineNameOptionType(txtitemname, xform)
    Else
      bch = txtitemname
    Endif
  Else
    bch = txtitemname
  Endif

  Return bch

End

Public Function GetMedicineDoseInFormat(sid As Long, sFormat As String) As Variant

  Dim res As Result
  Dim xx As Variant

  res = modDatabase.$myConn.Exec("select flditemtype,fldroute,flditem,flddose from tblpatdosing where fldid=&1", sid)
  If res.Available Then
    If res["flditemtype"] = "Medicines" Then
      If sFormat = "Label" Then
        xx = modPharmLabel.ConvertDoseToPrintNum(res["flddose"] / modMedConstant.GetDrugInitialStrength(res["flditem"])) & Space(1) & modPharmLabel.GetPackVolUnit(res["flditem"])
      Else
        xx = res["flddose"]
      Endif
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function TotalDoseNumner(dosid As Long) As Integer

  Dim xx As Integer
  Dim res As Result

  res = modDatabase.$myConn.Exec("select COUNT(fldid) as cnt from tblnurdosing where flddoseno=&1", dosid)
  If res.Available Then
    If res!cnt Then
      xx = res!cnt
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End

Public Function TodayDoseNumner(dosid As Long) As Integer

  Dim xx As Integer
  Dim res As Result

  res = modDatabase.$myConn.Exec("select COUNT(fldid) as cnt from tblnurdosing where flddoseno=&1 and fldtime<=&2 and fldtime>=&3", dosid, modDate.EndSqlDate(Now()), modDate.StartSqlDate(Now()))
  If res.Available Then
    If res!cnt Then
      xx = res!cnt
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End

Public Function GetTaperingRegimen(id As Long, Optional sHospCode As String) As String[]

  Dim res As Result
  Dim xx As String[]

  xx = New String[]
  If sHospCode Then
    res = modDatabase.$myConn.Exec("select fldid,flddose,fldfreq,flddays from tbltaperdose where flddoseno=&1 and fldhospcode=&2", id, sHospCode)
  Else
    res = modDatabase.$myConn.Exec("select fldid,flddose,fldfreq,flddays from tbltaperdose where flddoseno=&1", id)
  Endif
  If res.Available Then
    For Each res
      xx.Add(res!flddose & " mg X " & res!fldfreq & " X " & res!flddays)
    Next
  Endif
  Return xx

End

Public Function GetDoseRegimenString(id As Long, Route As Boolean, Optional MedName As Boolean) As String

  Dim xx As String
  Dim rs As Result
  Dim reg As String
  Dim taper As String[]

  xx = ""

  rs = modDatabase.$myConn.Exec("select fldid,fldroute,flditem,flddose,fldfreq,flddays from tblpatdosing where fldid=&1", id)

  If rs.Available = True Then
    If rs!flddose Then

      If rs!fldfreq = "Tapering" Then

        taper = GetTaperingRegimen(rs!fldid)

        If taper Then
          reg = taper.Join(gb.NewLine)
        Else
          If rs["fldroute"] = "fluid" Then
            reg = rs!flddose & " mL X " & rs!fldfreq & " X " & rs!flddays
          Else
            reg = rs!flddose & " mg X " & rs!fldfreq & " X " & rs!flddays
          Endif
        Endif
      Else
        If rs["fldroute"] = "fluid" Then
          reg = rs!flddose & " mL X " & rs!fldfreq & " X " & rs!flddays
        Else
          reg = rs!flddose & " mg X " & rs!fldfreq & " X " & rs!flddays
        Endif
      Endif

      If MedName = True Then
        reg = rs!flditem & Space(1) & reg
      Endif

      If Route = True Then
        xx = rs!fldroute & Space(1) & reg
      Else
        xx = reg
      Endif

    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function NurDosingString(encid As String) As String

  Dim rs As Result
  Dim res As Result
  Dim xx As String
  Dim yy As String
  Dim regm As String[]
  Dim sPt As String[]
  Dim tot As Integer
  Dim xval As String

  xx = ""
  regm = New String[]
  rs = modDatabase.$myConn.Exec("select fldid,fldroute,flditem,flddose,fldfreq,flddays,flditemtype from tblpatdosing where fldencounterval=&1 and flditemtype=&2 and (fldstatus=&3 or fldstatus=&4 or fldstatus=&5)", encid, "Medicines", "Registered", "Admitted", "Recorded")
  If rs.Available Then
    For Each rs
      xval = GetMedFormatForMedReport(rs!flditem, rs!fldroute) & "|" & rs!fldroute & "|" & rs!flddose & "|" & rs!fldfreq
      If regm.Count = 0 Then
        regm.Add(xval)
      Else
        If regm.Exist(xval) = False
          regm.Add(xval)
        Endif
      Endif
    Next
    regm.Sort()

    yy = ""
    For Each xx In regm
      sPt = Split(xx, "|")
      res = modDatabase.$myConn.Exec("select fldid,fldroute,flditem,flddose,fldfreq,flddays from tblpatdosing where fldencounterval=&1 and flditemtype=&2 and (fldstatus=&3 or fldstatus=&4 or fldstatus=&5) and fldroute=&6 and flditem=&7 and flddose=&8 and fldfreq=&9", encid, "Medicines", "Registered", "Admitted", "Recorded", sPt[1], sPt[0], sPt[2], sPt[3])                          ''
      tot = 0
      For Each res
        tot = tot + TotalDoseNumner(res!fldid)
      Next
      If sPt[1] = "fluid" Then
        yy = yy & sPt[0] & Space(1) & sPt[1] & Space(1) & sPt[2] & " mL X " & sPt[3] & " (" & CStr(tot) & " dose)" & gb.NewLine
      Else
        yy = yy & sPt[0] & Space(1) & sPt[1] & Space(1) & sPt[2] & " mg X " & sPt[3] & " (" & CStr(tot) & " dose)" & gb.NewLine
      Endif
      sPt.Clear
    Next
  Endif

  Return yy

End

Public Function DischargeMedString(encid As String) As String

  Dim rs As Result
  Dim xx As String

  xx = ""
  rs = modDatabase.$myConn.Exec("select fldid,fldroute,flditem,flddose,fldfreq,flddays,flditemtype from tblpatdosing where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3 or fldstatus=&4 or fldstatus=&5 or fldstatus=&6)", encid, "Discharged", "LAMA", "Death", "Refer", "Absconder")
  If rs.Available = True Then
    For Each rs
      If rs!flditemtype = "Medicines" Then
        xx = xx & GetMedFormatForMedReport(rs!flditem, rs!fldroute) & Space(1) & GetDoseRegimenString(rs!fldid, True) & gb.NewLine     ''
      Endif
    Next
  Endif

  Return xx

End

Public Function GetMedicineFollowPatient(sToDate As Date) As String[]

  Dim res As Result
  Dim xx As String[]
  Dim yy As String[]

  xx = New String[]
  res = modDatabase.$myConn.Exec("select fldstarttime,fldencounterval,flditem,flddose,fldfreq,flddays,fldqtydisp,flditemtype from tblpatdosing where fldsave_order=&1 and fldendtime>&2", True, sToDate)
  If res.Available Then
    For Each res
      If res!flditemtype = "Medicines" Then
        If Ceil(modMedConstant.GetQuantityDosing(res!flditem, res!flddose, res!fldfreq, res!flddays)) > res!fldqtydisp And If DateDiff(res!fldstarttime, sToDate, gb.Day) > modMedConstant.GetDrugUseDurationDosing(res!flditem, res!flddose, res!fldfreq, res!fldqtydisp) Then

          If xx.Count = 0 Then
            xx.Add(res!fldencounterval)
          Else
            If xx.Exist(res!fldencounterval) = False Then
              xx.Add(res!fldencounterval)
            Endif
          Endif

        Endif
      Endif
    Next

    xx.Sort()
    yy = xx
  Endif

  Return yy

End

Public Function PatientTakingMed(dtfir As Date, dtlast As Date) As String[]

  Dim xx As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select distinct(fldencounterval) from tblpatdosing where fldstarttime>=&1 and fldendtime<=&2 and flditemtype=&3", modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Medicines")
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function PatientDoseIDByDate(encid As String, dtfir As Date, dtlast As Date) As Long[]

  Dim xid As Long
  Dim xx As Long[]
  Dim res As Result
  Dim dd As Integer
  Dim res1 As Result
  Dim res2 As Result

  xx = New Long[]
  res = modDatabase.$myConn.Exec("select fldid from tblpatdosing where fldstarttime>=&1 and fldstarttime<=&2 and flditemtype=&3 and fldencounterval=&4", modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "Medicines", encid)
  If res.Available Then
    For Each res
      If xx.Count = 0 Then
        xx.Add(res!fldid)

      Else If xx.Count > 0 Then
        dd = 0
        For Each xid In xx
          res1 = modDatabase.$myConn.Exec("select fldencounterval,fldroute,flditem,flddose,fldfreq from tblpatdosing where fldid=&1", xid)
          res2 = modDatabase.$myConn.Exec("select fldencounterval,fldroute,flditem,flddose,fldfreq from tblpatdosing where fldid=&1", res!fldid)
          If res1!fldroute = res2!fldroute And If res1!flditem = res2!flditem And If res1!flddose = res2!flddose And If res1!fldfreq = res2!fldfreq Then
            dd = dd + 1
          Else
            dd = dd + 0
          Endif
        Next
        If dd = 0 Then
          xx.Add(res!fldid)
        Endif

      Endif
    Next
  Endif
  Return xx

End

Public Function GetMedicinesUsed(encid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select distinct(flditem) from tblpatdosing where fldencounterval=&1 and fldid in(select flddoseno from tblnurdosing where fldencounterval=&1)", encid)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function UniProcedureMedString(encid As String, itemid As Long, sType As String) As String

  Dim rs As Result
  Dim xx As String

  xx = ""
  rs = modDatabase.$myConn.Exec("select fldid,fldroute,flditem,flddose,(fldqtydisp-fldqtyret) as qty,flditemtype from tblpatdosing where fldencounterval=&1 and flddispmode=&2 and fldsave_order=&3", encid, sType & ":" & CStr(itemid), True)
  If rs.Available = True Then
    For Each rs
      If rs!flditemtype = "Medicines" Then
        If rs!fldroute = "fluid" Then
          xx = xx & GetMedFormatForMedReport(rs!flditem, rs!fldroute) & Space(1) & rs!fldroute & Space(1) & rs!flddose & " mL [" & rs!qty & "]" & gb.NewLine
        Else
          xx = xx & GetMedFormatForMedReport(rs!flditem, rs!fldroute) & Space(1) & rs!fldroute & Space(1) & rs!flddose & " mg [" & rs!qty & "]" & gb.NewLine     ''
        Endif
      Endif
    Next
  Endif

  Return xx

End

Public Function GetALLReportDrugSelString(encid As String, doseno As Long, sDate As Date) As String[]

  Dim sql As String
  Dim res As Result
  Dim xList As String[]

  xList = New String[]
  sql = "select fldvalue,fldunit,fldtime from tblnurdosing where fldencounterval=&1 and flddoseno=&2 and fldtime>=&3 and fldtime<=&4"
  res = modDatabase.$syConn.Exec(sql, encid, doseno, modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate))
  If res.Available = True Then
    For Each res
      If res!fldvalue Then
        xList.Add("[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime) & " ] " & " : " & CStr(res!fldvalue) & Space(1) & res!fldunit)
      Endif
    Next
  Endif
  Return xList

End

''------------------------------- Med calculation --------------------------------
Public Function GetTotalFluidMedicine(nurid As Long) As Float

  Dim res As Result
  Dim txtroute As String
  Dim totfld As Float
  Dim xdura As Float

  res = modDatabase.$myConn.Exec("select flddoseno,fldvalue,fldunit,fldfromtime,fldtotime from tblnurdosing where fldid=&1", nurid)
  If res.Available Then
    txtroute = GetRouteFromDosing(res!flddoseno)
    If txtroute = "CIV" Or txtroute = "IIV" Then
      '     totfld = (res!flddose * modPharmLabel.ConvertFrequencyToNumber(res!fldfreq)) / modMedConstant.GetDrugFinalStrength(res!flditem, txtroute)
      totfld = 0
    Else If txtroute = "fluid" Then
      If res!fldtotime Then
        xdura = Round(DateDiff(res!fldfromtime, res!fldtotime, gb.Minute) / 60)
      Else
        xdura = 0
      Endif
      totfld = xdura * res!fldvalue
    Else
      totfld = 0
    Endif
    totfld = Round(totfld, -2)
  Endif
  Return totfld

End

Public Function GetTotalEnergyMedicine(id As Long) As Float

  Dim res As Result
  Dim txtroute As String
  Dim totenr As Float

  res = modDatabase.$myConn.Exec("select fldroute,flditem,flddose,fldfreq,flddays,fldtime from tblpatdosing where fldid=&1", id)
  If res.Available Then
    txtroute = res!fldroute
    If txtroute = "CIV" Or txtroute = "IIV" Then
      totenr = (res!flddose * modPharmLabel.ConvertFrequencyToNumber(res!fldfreq)) * modMedConstant.GetDrugEnergyContent(res!flditem, txtroute)
    Else If txtroute = "fluid" Then
    Else
      totenr = 0
    Endif
    totenr = Round(totenr, -2)
  Endif
  Return totenr

End
