' Gambas module file

Public Sub PatMedicalItemRequest(sCategory As String, encid As String, sItem As String, sPatInfo As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatmeditem")
  res["fldencounterval"] = encid
  res["fldcategory"] = sCategory
  res["fldcode"] = ""
  res["flditem"] = sItem
  res["fldpatinfo"] = sPatInfo
  res["fldcomment"] = ""

  res["flduserid_order"] = modGeneralMain.$lbluser
  res["fldtime_order"] = Now()
  res["fldcomp_order"] = modGeneralMain.compID
  res["fldsave_order"] = True
  res["fldorder"] = "Requested"

  res["flduserid"] = ""
  res["fldtime"] = ""
  res["fldcomp"] = ""
  res["fldsave"] = ""
  res["fldstatus"] = ""

  res["fldbillno"] = ""
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update

End

Public Sub PatMedicalItemDirectUse(sCategory As String, encid As String, sItem As String, sPatInfo As String, sItemCode As String, sComment As String)                         ''

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatmeditem")
  res["fldencounterval"] = encid
  res["fldcategory"] = sCategory
  res["fldcode"] = sItemCode
  res["flditem"] = sItem
  res["fldpatinfo"] = sPatInfo
  res["fldcomment"] = sComment

  res["flduserid_order"] = ""
  res["fldtime_order"] = ""
  res["fldcomp_order"] = ""
  res["fldsave_order"] = ""
  res["fldorder"] = "Done"

  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["fldstatus"] = ""

  res["fldbillno"] = ""
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update

End
