' Gambas module file

Public Sub InsertRadioTestOrder(encid As String, strTest As String, strType As String, strMethod As String, grpid As Long, sRefer As String, sBillNo As String, sComment As String, plandate As Date)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpatradiotest")
  res["fldencounterval"] = encid
  res["fldtestid"] = strTest
  res["fldmethod"] = strMethod
  res["fldgroupid"] = grpid
  res["fldsampletype"] = ""
  res["fldreportquali"] = ""
  res["fldreportquanti"] = 0
  res["fldfilepath"] = ""
  res["fldstatus"] = "Sampled"
  res["fldprint"] = False
  res["fldabnormal"] = False
  res["fldrefername"] = sRefer
  res["fldcondition"] = ""
  res["fldcomment"] = sComment
  res["fldbillno"] = sBillNo
  res["flvisible"] = "Visible"
  res["fldnewdate"] = plandate
  res["fldpacstudy"] = ""

  res["fldtest_type"] = strType
  res["fldchk"] = False
  res["fldorder"] = 0

  res["flduserid_report"] = ""
  res["fldtime_report"] = ""
  res["fldcomp_report"] = modGeneralMain.compID
  res["fldsave_report"] = False
  res["flduptime_report"] = ""

  res["flduserid_verify"] = ""
  res["fldtime_verify"] = ""
  res["fldcomp_verify"] = ""
  res["fldsave_verify"] = False
  res["flduptime_verify"] = ""
  res["xyz"] = False

  res.Update()
  'don't catch error

End

Public Sub InsertRadioSubTest(encid As String, pttestid As Long, subtestList As String[])

  Dim xx As String
  Dim res2 As Result

  For Each xx In subtestList
    res2 = modDatabase.$myConn.Create("tblpatradiosubtest")
    res2["fldencounterval"] = encid
    res2["fldtestid"] = pttestid
    res2["fldsubtest"] = xx
    res2["fldtanswertype"] = modFixRadio.GetSubRadioOption(GetRadionameFromTestID(pttestid), xx)
    res2["fldreport"] = ""
    res2["fldsave"] = False
    res2["fldabnormal"] = False
    res2["fldchk"] = False
    res2["fldorder"] = 0
    res2["fldfilepath"] = ""
    res2["xyz"] = False
    res2.Update()
  Next
  'don't catch error

End

Public Sub UpdateRadioTestReportQuali(id As Long, strReport As String, abn As Boolean, Optional KeyList As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldreportquali"] = strReport
  If IsFloat(strReport) = True Then
    res["fldreportquanti"] = CFloat(strReport)
  Else
    res["fldreportquanti"] = 0
  Endif
  If KeyList Then
    res["fldfilepath"] = KeyList
  Endif
  res["fldstatus"] = "Reported"
  res["flduserid_report"] = modGeneralMain.$lbluser
  If res!fldtime_report Then
    res["flduptime_report"] = Now()
  Else
    res["fldtime_report"] = Now()
  Endif
  res["fldcomp_report"] = modGeneralMain.compID
  res["fldsave_report"] = True
  res["fldabnormal"] = abn
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateRadioTestReportQuanti(id As Long, strReport As Float, abn As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldreportquali"] = CStr(strReport)
  res["fldreportquanti"] = strReport
  res["fldstatus"] = "Reported"
  res["flduserid_report"] = modGeneralMain.$lbluser
  If res!fldtime_report Then
    res["flduptime_report"] = Now()
  Else
    res["fldtime_report"] = Now()
  Endif
  res["fldcomp_report"] = modGeneralMain.compID
  res["fldsave_report"] = True
  res["fldabnormal"] = abn
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateRadioTestOrder(id As Long, sOrder As Integer)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldorder"] = sOrder
  res["xyz"] = False
  res.Update

End

Public Sub UpdateRadioSubTestOrder(id As Long, sOrder As Integer)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiosubtest", "fldid=&1", id)
  res["fldorder"] = sOrder
  res["xyz"] = False
  res.Update

End

Public Sub UpdateEquipmenRadiotMethod(id As Long, sMethod As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldmethod"] = sMethod
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub UpdateConditionRadio(id As Long, condition As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatradiotest", "fldid=&1", id)
  res["fldcondition"] = condition
  res["xyz"] = False
  res.Update()
  'don't catch error

End

''--------------------------------- patient procedures ---------------------------
Public Function GetEncounterFromRadioSerial(txtserial As Long) As String

  Dim encid As String

  encid = modPatient.GetPatientEncFromID("tblpatradiotest", txtserial)
  Return encid

End

Public Function GetRadionameFromTestID(id As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldtestid from tblpatradiotest where fldid=&1", id)
  If res.Available Then
    If res!fldtestid Then
      xx = res!fldtestid
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetRadioSelFieldType(sField As String) As String[]

  Dim res As Result
  Dim sql As String
  Dim xx As String[]

  sql = Subst("select distinct(&1) as col from tblpatradiotest", sField)
  res = modDatabase.$myConn.Exec(sql)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function PaientAllRadioNameArray(encid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select distinct(fldtestid) as col from tblpatradiotest where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3)", encid, "Reported", "Verified")
  xx = modFillContainer.GetListFromResult(res)

  Return xx.Sort()

End

Public Sub GetQualiRadioListByPatient(encid As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xxx As String[]

  sql = "select distinct(fldtestid) as col from tblpatradiotest where fldencounterval=&1 and fldtest_type=&2 and flvisible=&3 and (fldstatus=&4 or fldstatus=&5)"
  res = modDatabase.$myConn.Exec(sql, encid, "Qualitative", "Visible", "Reported", "Verified")
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx

End

Public Sub GetQuantiRadioListByPatient(encid As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xxx As String[]

  sql = "select distinct(fldtestid) as col from tblpatradiotest where fldencounterval=&1 and fldtest_type=&2 and flvisible=&3 and (fldstatus=&4 or fldstatus=&5)"
  res = modDatabase.$myConn.Exec(sql, encid, "Quantitative", "Visible", "Reported", "Verified")
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx

End

''-----------------------------------------unit----------------------
Public Function RadioTestUnit(strTest As String, encid As String, Optional sMethod As String) As String

  Dim ssl As String
  Dim rs As Result
  Dim LabUnit As String
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  ssl = "select fldunit as unit from tblradiolimit where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  rs = modDatabase.$medConn.Exec(ssl, strTest, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)
  If rs.Available = True Then
    rs.MoveFirst
    If rs!unit Then
      LabUnit = rs!unit
    Else
      LabUnit = ""
    Endif
  Else
    LabUnit = ""
  Endif

  Return LabUnit

End

Public Function GetTestRadioUnit(encid As String, id As Long) As String

  Dim res As Result
  Dim sql As String
  Dim LabUnit As String

  sql = "select fldencounterval,fldtestid,fldreportquanti,fldmethod from tblpatradiotest where fldid=&1 and fldtest_type=&2 and fldencounterval=&3"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative", encid)
  If res.Available = True Then
    If res!fldmethod Then
      LabUnit = RadioTestUnit(res!fldtestid, res!fldencounterval, res!fldmethod)
    Else
      LabUnit = RadioTestUnit(res!fldtestid, res!fldencounterval)
    Endif
  Else
    LabUnit = ""
  Endif

  Return LabUnit

End

''---------------------------- limits---------------------------------------------------
Public Function RadioNormalValue(strTest As String, encid As String, Optional sMethod As String) As Float

  Dim ssl As String
  Dim rs As Result
  Dim NormalLimit As Float
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  ssl = "select fldnormal as normal from tblradiolimit where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr
  rs = modDatabase.$medConn.Exec(ssl, strTest, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)
  If rs.Available = True Then
    rs.MoveFirst
    If rs!normal Then
      NormalLimit = rs!normal
    Else
      NormalLimit = 0
    Endif
  Else
    NormalLimit = 0
  Endif

  Return NormalLimit

End

Public Function GetMaxQuantiRadioVal(txtexam As String, encid As String, Optional sMethod As String) As Float

  Dim res As Result
  Dim xx As Float
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  res = modDatabase.$medConn.Exec("select fldhigh from tblradiolimit where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr, txtexam, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)                                                               ''
  If res.Available = True Then
    res.MoveFirst
    If res!fldhigh Then
      xx = res!fldhigh
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End

Public Function GetMinQuantiRadioVal(txtexam As String, encid As String, Optional sMethod As String) As Float

  Dim res As Result
  Dim xx As Float
  Dim sqstr As String

  If Not sMethod Or If sMethod = "Regular" Then
    sqstr = ""
  Else
    sqstr = " and fldmethod=&6"
  Endif

  res = modDatabase.$medConn.Exec("select fldlow from tblradiolimit where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)" & sqstr, txtexam, modPatient.GetPatientSex(encid), "Both Sex", modPatient.GetAgeGroupFIxed(encid, Now()), "All Age", sMethod)                                                               ''
  If res.Available = True Then
    res.MoveFirst
    If res!fldlow Then
      xx = res!fldlow
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End

Public Function GetRadioTestUpperLimits(id As Long) As Float

  Dim res As Result
  Dim sql As String
  Dim UpLimit As Float

  sql = "select fldencounterval,fldtestid,fldreportquanti,fldmethod from tblpatradiotest where fldid=&1 and fldtest_type=&2"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative")
  If res.Available = True Then
    If res!fldmethod Then
      UpLimit = GetMaxQuantiRadioVal(res!fldtestid, res!fldencounterval, res!fldmethod)
    Else
      UpLimit = GetMaxQuantiRadioVal(res!fldtestid, res!fldencounterval)
    Endif
  Else
    UpLimit = 0
  Endif

  Return UpLimit

End

Public Function GettRadioTestLowerLimits(id As Long) As Float

  Dim res As Result
  Dim sql As String
  Dim LwLimit As Float

  sql = "select fldencounterval,fldtestid,fldreportquanti,fldmethod from tblpatradiotest where fldid=&1 and fldtest_type=&2"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative")
  If res.Available = True Then
    If res!fldmethod Then
      LwLimit = GetMinQuantiRadioVal(res!fldtestid, res!fldencounterval, res!fldmethod)
    Else
      LwLimit = GetMinQuantiRadioVal(res!fldtestid, res!fldencounterval)
    Endif
  Else
    LwLimit = 0
  Endif

  Return LwLimit

End

Public Function GetRadioQualiTestTextReference(txttest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldanswer from tblradiooption where fldexamid=&1 and fldanswertype=&2 ORDER BY fldindex", txttest, "Text Reference")
  If res.Available = True Then
    If res!fldanswer Then
      xx = res!fldanswer
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetRadioTestLimitSrting(id As Long) As String

  Dim xx As String
  Dim res As Result
  Dim sql As String
  Dim xmax As Float
  Dim xmin As Float

  sql = "select fldencounterval,fldtest_type from tblpatradiotest where fldid=&1"
  res = modDatabase.$myConn.Exec(sql, id)
  If res!fldtest_type = "Quantitative" Then
    xmax = GetRadioTestUpperLimits(id)
    xmin = GettRadioTestLowerLimits(id)
    If xmin < xmax Then
      xx = CStr(xmin) & "  -  " & CStr(xmax) & Space(1) & GetTestRadioUnit(res!fldencounterval, id)
    Else
      xx = ""
    Endif
  Else
    xx = GetRadioQualiTestTextReference(GetRadionameFromTestID(id))   ''only for text reference
  Endif

  Return xx

End

''------------------------------------------- value ------------------------------
Public Function GetRadioTestValue(id As Long) As Float

  Dim res As Result
  Dim sql As String
  Dim LabVal As Float

  sql = "select fldencounterval,fldtestid,fldreportquanti from tblpatradiotest where fldid=&1 and fldtest_type=&2"
  res = modDatabase.$myConn.Exec(sql, id, "Quantitative")
  If res.Available = True Then
    If res!fldreportquanti Then
      LabVal = res!fldreportquanti
    Else
      LabVal = 0
    Endif
  Else
    LabVal = 0
  Endif

  Return LabVal

End

Public Function RadioTestInterpretByTestID(labid As Long) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String

  sql = "select fldcomment,fldmax,fldmin from tblradiocomment where fldexamid=&1 and (fldptsex=&2 or fldptsex=&3) and (fldagegroup=&4 or fldagegroup=&5)"
  res = modDatabase.$medConn.Exec(sql, GetRadionameFromTestID(labid), modPatient.GetPatientSex(GetEncounterFromRadioSerial(labid)), "Both Sex", modPatient.GetAgeGroupFIxed(GetEncounterFromRadioSerial(labid), Now()), "All Age")
  If res.Available = True Then
    For Each res
      If res!fldcomment Then
        If GetRadioTestValue(labid) >= res!fldmin And If GetRadioTestValue(labid) <= res!fldmax Then
          xx = res!fldcomment
          Break
        Endif
      Else
        xx = ""
      Endif
    Next
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetRadiobTestValueSubString(id As Variant) As Variant

  Dim res As Result
  Dim res1 As Result
  Dim sql As String
  Dim xx As Variant
  Dim xquali As String

  sql = "select fldid,fldencounterval,fldreportquali,fldreportquanti,fldtest_type,fldabnormal from tblpatradiotest where fldid=&1"

  res = modDatabase.$myConn.Exec(sql, id)
  If res.Available = True Then
    If res!fldtest_type = "Quantitative" Then
      xx = GetRadioTestValue(id)
    Else
      If res!fldreportquali Then
        xx = res!fldreportquali
      Else
        xx = ""
      Endif

      res1 = modDatabase.$myConn.Exec("select fldsubtest,fldreport,fldid,fldtestid,fldtanswertype from tblpatradiosubtest where fldtestid=&1 and fldencounterval=&2", res!fldid, res!fldencounterval)
      If res1.Available = True Then
        xquali = ""
        For Each res1
          If res1!fldtanswertype = "Multiple Selection" Or If res1!fldtanswertype = "Single Column" Then
            xquali = xquali & res1!fldsubtest & " : " & gb.NewLine & GetSubRadioTableReportString(res1!fldtestid, res1!fldid, False) & gb.NewLine & gb.NewLine
          Else If res1!fldtanswertype = "Text Table" Then
            xquali = xquali & res1!fldsubtest & " : " & gb.NewLine & GetSubRadioTableReportString(res1!fldtestid, res1!fldid, False) & gb.NewLine & gb.NewLine
          Else If res1!fldtanswertype = "Dual Columns" Then
            xquali = xquali & res1!fldsubtest & " : " & gb.NewLine & GetSubRadioDualTableString(res1!fldtestid, res1!fldid, False) & gb.NewLine & gb.NewLine
          Else
            If res1!fldreport Then
              xquali = xquali & res1!fldsubtest & " : " & res1!fldreport & gb.NewLine
            Endif
          Endif
        Next
        xx = xx & gb.NewLine & xquali
      Endif

    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetRadioTestValueString(encid As String, id As Long, flag As Boolean) As String

  Dim xx As String
  Dim res As Result
  Dim sql As String
  Dim xval As String

  sql = "select fldreportquali,fldreportquanti,fldtest_type,fldabnormal from tblpatradiotest where fldid=&1 and fldencounterval=&2"
  res = modDatabase.$myConn.Exec(sql, id)
  If res.Available = True Then
    If res!fldtest_type = "Quantitative" Then
      If res!fldreportquanti Then
        xval = modReportVar.GetLocaleNumberFormat(res!fldreportquanti, 0) & Space(1) & GetTestRadioUnit(encid, id)
      Else
        xval = ""
      Endif
    Else
      If res!fldreportquali Then
        xval = Trim(res!fldreportquali)
      Else
        xval = ""
      Endif
    Endif

    If xval And If flag = True Then
      xx = modReportVar.GetReportWithAbnormalStatus(xval, res!fldabnormal)
    Else
      xx = xval
    Endif

  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetRadioTestValueGridString(id As Long, flag As Boolean) As String

  Dim xx As String
  Dim res As Result
  Dim sql As String
  Dim xval As String

  sql = "select fldencounterval,fldreportquali,fldreportquanti,fldtest_type,fldabnormal from tblpatradiotest where fldid=&1"
  res = modDatabase.$myConn.Exec(sql, id)
  If res.Available = True Then
    If res!fldtest_type = "Quantitative" Then
      If res!fldreportquanti Then
        xx = modReportVar.GetLocaleNumberFormat(res!fldreportquanti, 0) & Space(1) & GetTestRadioUnit(res!fldencounterval, id)
      Else
        xx = ""
      Endif
    Else
      If res!fldreportquali Then
        xx = Trim(res!fldreportquali)
      Else
        xx = ""
      Endif
    Endif

    If xx And If flag = True Then
      xval = modReportVar.GetReportWithAbnormalStatus(xx, res!fldabnormal)
    Else
      xval = xx
    Endif

  Else
    xval = ""
  Endif
  Return xval

End

Public Function GetRadioSubTestQuali(encid As String, pttestid As Long) As String[]

  Dim res As Result
  Dim xx As String[]
  Dim xquali As String

  xx = New String[]
  res = modDatabase.$myConn.Exec("select fldsubtest,fldreport,fldid,fldtestid,fldtanswertype from tblpatradiosubtest where fldtestid=&1 and fldsave=&2 and fldencounterval=&3", pttestid, True, encid)
  If res.Available = True Then
    For Each res
      If res!fldtanswertype = "Multiple Selection" Or If res!fldtanswertype = "Single Column" Then
        xquali = gb.NewLine & GetSubRadioTableReportString(res!fldtestid, res!fldid, False)
      Else If res!fldtanswertype = "Text Table" Then
        xquali = gb.NewLine & GetSubRadioTableReportString(res!fldtestid, res!fldid, False)
      Else If res!fldtanswertype = "Dual Columns" Then
        xquali = gb.NewLine & GetSubRadioDualTableString(res!fldtestid, res!fldid, False)
      Else
        xquali = Trim(res!fldreport)
      Endif
      If res!fldsubtest Then
        xx.Add(res!fldsubtest & " : " & xquali)
      Endif
    Next
  Endif

  Return xx

End

Public Function GetSubRadioTableReportString(testid As Long, subtestid As Long, sTable As Boolean, Optional sHospCode As String) As String

  Dim res As Result
  Dim xx As String[]
  Dim xstr As String[]
  Dim xval As String

  If sHospCode Then
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2,fldcolm3,fldcolm4 from tblpatradiosubtable where fldexamid=&1 and fldsubexamid=&2 and fldvalue<>&3 and fldhospcode=&4", testid, subtestid, "Cancelled", sHospCode)
  Else
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2,fldcolm3,fldcolm4 from tblpatradiosubtable where fldexamid=&1 and fldsubexamid=&2 and fldvalue<>&3", testid, subtestid, "Cancelled")
  Endif
  If res.Available Then
    If sTable = True
      xval = modRepoTemplete.HTMLTableSyntax()
      For Each res
        xval = xval & "<tr>" & gb.NewLine

        xstr = New String[]
        xstr.Add("<td>" & res!fldvariable & "</td>" & gb.NewLine)
        If res!fldvalue Then
          xstr.Add("<td>" & res!fldvalue & "</td>" & gb.NewLine)
        Else
          xstr.Add("<td>" & "</td>" & gb.NewLine)
        Endif
        If res!fldcolm2 Then
          xstr.Add("<td>" & res!fldcolm2 & "</td>" & gb.NewLine)
        Else
          xstr.Add("<td>" & "</td>" & gb.NewLine)
        Endif
        If res!fldcolm3 Then
          xstr.Add("<td>" & res!fldcolm3 & "</td>" & gb.NewLine)
        Else
          xstr.Add("<td>" & "</td>" & gb.NewLine)
        Endif
        If res!fldcolm4 Then
          xstr.Add("<td>" & res!fldcolm4 & "</td>" & gb.NewLine)
        Else
          xstr.Add("<td>" & "</td>" & gb.NewLine)
        Endif
        xval = xval & xstr.Join(gb.NewLine)

        xval = xval & "</tr>" & gb.NewLine
      Next
      xval = xval & "</table>" & gb.NewLine

    Else
      xx = New String[]
      For Each res
        xstr = New String[]
        xstr.Add(res!fldvariable)
        If res!fldvalue Then
          xstr.Add(res!fldvalue)
        Endif
        If res!fldcolm2 Then
          xstr.Add(res!fldcolm2)
        Endif
        If res!fldcolm3 Then
          xstr.Add(res!fldcolm3)
        Endif
        If res!fldcolm4 Then
          xstr.Add(res!fldcolm4)
        Endif
        xx.Add(xstr.Join(" : "))
      Next
      xval = xx.Join(gb.NewLine)

    Endif
  Else
    xval = ""
  Endif
  Return xval

End

Public Function GetSubRadioDualTableString(testid As Long, subtestid As Long, sTable As Boolean, Optional sHospCode As String) As String

  Dim res As Result
  Dim xx As String
  Dim aa As String
  Dim bb As String

  If sHospCode Then
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2 from tblpatradiosubtable where fldexamid=&1 and fldsubexamid=&2 and fldvalue<>&3 and fldhospcode=&4", testid, subtestid, "Cancelled", sHospCode)
  Else
    res = modDatabase.$myConn.Exec("select fldvariable,fldvalue,fldcolm2 from tblpatradiosubtable where fldexamid=&1 and fldsubexamid=&2 and fldvalue<>&3", testid, subtestid, "Cancelled")
  Endif
  If res.Available Then
    If sTable = True Then
      xx = modRepoTemplete.HTMLTableSyntax()
      xx = xx & "<tr>" & gb.NewLine
      xx = xx & "<td class='report_table_h'>PARAMETER</td>" & gb.NewLine
      xx = xx & "<td class='report_table_h'>LEFT</td>" & gb.NewLine
      xx = xx & "<td class='report_table_h'>RIGHT</td>" & gb.NewLine
      xx = xx & "</tr>" & gb.NewLine
      For Each res
        If res!fldvalue Then
          aa = res!fldvalue
        Else
          aa = ""
        Endif
        If res!fldcolm2 Then
          bb = res!fldcolm2
        Else
          bb = ""
        Endif
        xx = xx & "<tr>" & gb.NewLine
        xx = xx & "<td>" & res!fldvariable & "</td>" & gb.NewLine
        xx = xx & "<td>" & aa & "</td>" & gb.NewLine
        xx = xx & "<td>" & bb & "</td>" & gb.NewLine
        xx = xx & "</tr>" & gb.NewLine
      Next
      xx = xx & "</table>" & gb.NewLine

    Else
      xx = ""
      For Each res
        If res!fldvalue Then
          aa = res!fldvalue
        Else
          aa = ""
        Endif
        If res!fldcolm2 Then
          bb = res!fldcolm2
        Else
          bb = ""
        Endif
        xx = xx & res!fldvariable & " [LEFT: " & aa & "][RIGHT: " & bb & "]" & gb.NewLine
      Next

    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''only for last quantitative test (used for calculation)
Public Function GetCurrRadioValueSysConst(encid As String, xSysConst As String, sPos As String) As String

  Dim xx As String
  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldtest_type,fldreportquali,fldreportquanti from tblpatradiotest where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3) and fldtestid in(select fldexamid from tblradio where fldsysconst=&4) and fldreportquali IS NOT &5", encid, "Reported", "Verified", xSysConst, Null)
  If res.Available Then
    If sPos = "First" Then
      res.MoveFirst
    Else
      res.MoveLast
    Endif
    If res!fldreportquanti Then
      xx = CStr(res!fldreportquanti)
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End
