' Gambas module file

''------------------------------------------ General calculation --------------------------------------------------
Public Function GetConstantValue(syscons As String, encid As String) As Float

  Dim xcalc As String
  Dim patsex As String
  Dim xval As String
  Dim xcon As Float

  patsex = modPatient.GetPatientSex(encid)
  xcalc = modSettings.ShowEqnSettingFromFIle(syscons & "/" & patsex)
  If Not xcalc Then
    xcalc = modSettings.ShowEqnSettingFromFIle(syscons & "/BothSex")
  Endif

  xval = modReportVar.GetCalcValue(xcalc, encid)
  If xval Then
    xcon = CFloat(xval)
  Else
    Message.Warning(("Unable to Calculate" & gb.NewLine & modBasic.$ErrorLastString), ("OK"))
  Endif

  Return xcon

End

''--------------------------------------- custom sys constant -------------------------------------
Public Function GetSysconstList(sType As String) As String[]

  Dim res As Result
  Dim xxx As String[]

  res = modDatabase.$medConn.Exec("select fldsysconst from tblsysconst where fldcategory like &1", sType)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx

End

''-----------------------------------------SYSTEM CONSTANT LIST ------------------------------------------------------------------
Public Function GetCalculationForSetA(strParameter As String, sex As String, age As Integer, weight As Float, height As Float, serumcreat As String) As Float

  Dim xx As Float
  Dim seta As String
  Dim eqn As String
  Dim sPath As String
  Dim arcmd As String[]

  sPath = modHelpVariable.AppDirectory &/ "/calculators/SetA"
  eqn = modSettings.ShowSettingFromFIle(strParameter & "/Equation")
  If Not eqn Then
    eqn = modSettings.ShowCalcSettingFromFIle(strParameter & "/Equation1")
  Endif
  arcmd = ["gbs3", sPath, strParameter, eqn, sex, CStr(weight), CStr(height), CStr(age), CStr(serumcreat)]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To seta
  If seta Then
    xx = Round(Val(seta), -3)
  Else
    xx = 0
  Endif

  Return xx

End

Public Function GetCalculationAValue(strParameter As String, encid As String) As Float

  Dim xx As Float
  Dim xage As Integer
  Dim xwt As Float
  Dim xht As Float

  xage = DateDiff(modPatient.GetPatientBirthDay(encid), Now(), gb.Year)
  xwt = modClinic.GetBodyWeight(encid)
  xht = modClinic.GetPatientHeightinCm(encid)
  If xage And If xwt And If xht Then
    xx = GetCalculationForSetA(strParameter, modPatient.GetPatientSex(encid), xage, xwt, xht, 0)                      ''
  Else
    Message.Optional(("One or more from Age, Weight and Height are missing"), ("OK"), ("Disable Warning"))
  Endif
  Return xx

End

Public Function GetCreatinineClearance(encid As String) As Float

  Dim xx As Float
  Dim xage As Integer
  Dim xwt As Float
  Dim xht As Float
  Dim xcreat As String

  xage = DateDiff(modPatient.GetPatientBirthDay(encid), Now(), gb.Year)
  xwt = modClinic.GetBodyWeight(encid)
  xht = modClinic.GetPatientHeightinCm(encid)
  xcreat = modLabTest.GetCurrTesValueMetric(encid, "Creatinine_Serum", "Last")
  If xage And If xwt Then
    xx = GetCalculationForSetA("Creatinine_Clearance", modPatient.GetPatientSex(encid), xage, xwt, xht, xcreat)                      ''
  Else
    Message.Optional(("One or more from Age, Weight and Height are missing"), ("OK"), ("Disable Warning"))
  Endif
  Return xx

End

Public Function GetFormulaText(strParam As String) As String

  Dim hFile As File
  Dim sLine As String
  Dim recrd As Boolean
  Dim xx As String

  hFile = Open modHelpVariable.AppDirectory &/ "/calculators/SetA"
  modBasic.DebugString("Open File " & modHelpVariable.AppDirectory &/ "/calculators/SetA")
  xx = ""
  While Not Eof(hFile)
    Line Input #hFile, sLine
    If sLine = "Function Calculate_" & strParam & "() As Float" Then
      recrd = True
    Else If sLine = "End" Then
      recrd = False
    Endif
    If recrd = True Then
      xx = xx & sLine & gb.NewLine
    Endif
  Wend

  Return xx

Catch
  modHelpVariable.CreateErrorReport()

End

''---------------------------------- calculation constants --------------------------------------------------------
Private Function GetParameterListFromCalc() As String[]

  Dim xx As String[]

  xx = New String[]
  xx.Add("Body_Surface_Area")
  xx.Add("Ideal_Body_Weight")
  xx.Add("Body_Mass_Index")
  xx.Add("Creatinine_Clearance")
  xx.Sort(gb.Ascent)
  Return xx

End

Public Function SysParamList() As String[]

  Dim xx As String[]

  xx = New String[]
  xx.Insert(GetParameterListFromCalc())
  xx.Insert(modBasic.$sysCustomList)
  ' xx.Insert(modBasic.GetSysconstList("Custom"))
  Return xx

End

''---------------------------------- Test constants --------------------------------
Private Function SysLabTestConstant() As String[]

  Dim cmb As String[]

  cmb = New String[]
  cmb.Add("Sodium_Serum")
  cmb.Add("Creatinine_Serum")
  cmb.Add("Potassium_Serum")
  cmb.Add("Calcium_Total_Serum")
  cmb.Add("Calcium_Ionized_Serum")
  cmb.Add("Albumin_Serum")
  cmb.Add("Glucose_Serum")
  cmb.Add("Bicarbonate_Serum")
  cmb.Add("Chloride_Serum")
  cmb.Add("Urea_Nitrogen_Blood")
  cmb.Add("pH_Blood")
  cmb.Add("Hemoglobin_Blood")
  Return cmb

End

Public Function SysLabTestList() As String[]

  Dim xx As String[]

  xx = New String[]
  xx.Insert(SysLabTestConstant())
  xx.Insert(modBasic.$sysTestList)
  ' xx.Insert(modSysCons.GetSysconstList("Test"))
  Return xx

End

''---------------------------------------- Examination constants ------------------------------
Private Function SysExamConstant() As String[]

  Dim cmb As String[]

  cmb = New String[]
  cmb.Add("Body_Weight")
  cmb.Add("Body_Height")
  cmb.Add("BloodPressure_Systolic")
  cmb.Add("BloodPressure_Diastolic")
  cmb.Add("Pulse_Rate")
  cmb.Add("Pulse_Rhythm")
  cmb.Add("Heart_Rate")
  cmb.Add("Respiration_Rate")
  cmb.Add("Temperature_System")
  cmb.Add("Oxygen_Saturation")
  cmb.Add("Glasgow_Coma_Scale")

  Return cmb

End

Public Function SysExaminationList() As String[]

  Dim xx As String[]

  xx = New String[]
  xx.Insert(SysExamConstant())
  xx.Insert(modBasic.$sysExamList)
  ' xx.Insert(modSysCons.GetSysconstList("Exam"))
  Return xx

End

''------------ All constants ------------------
Public Function GetAllSysConstantsList() As String[]

  Dim xxx As String[]

  xxx = New String[]
  xxx.Insert(SysParamList())
  xxx.Insert(SysLabTestList())
  xxx.Insert(SysExaminationList())
  xxx.Insert(modBasic.$sysRadioList)
  xxx.Insert(modBasic.$DemogList)

  Return xxx

End
