' Gambas module file

Private $ShowCategory As String
Private $ShowBatch As String
Private $ShowExpiry As String
Private $ShowQuantity As String
Private $TextTaxDiscount As String
Private $ShowTaxDiscount As String
Private $EnableExtraLabel As String
Private $ShowSumDisc As String
Private $ShowTaxSum As String
Private $GroupItem As String
Private $PartiSuffix As String
Private $InvDateFormat As String

Private $NoteI_Font As String
Private $Note2_Font As String
Private $Note1_Text As String
Private $Note2_Text As String

'NOTE: -------------------------------------HTML Invoice -----------------------------------------
Public Sub BillingInvoice(BillNo As String, txTitle As String, ShowTax As Boolean, ShowDisc As Boolean)

  Dim res As Result

  SetInvoiceSettings()
  If modBasic.$BillInvReprintForm = "Aggregate" Then
    res = modDatabase.$myConn.Exec("select fldid from tblpatbilling where fldretbill=&1", BillNo)
    If res.Available Then
      InvoiceReturnReport(BillNo)
    Else
      modBillings.InsertBillViewCount(BillNo)
      If modSettings.ShowSettingFromFIle("Invoice/TextFile_Source") = "Text" Then
        BillingLINEInvoice(BillNo, txTitle, ShowTax, ShowDisc)
      Else
        BillingHTMLInvoice(BillNo, txTitle, ShowTax, ShowDisc)
      Endif
    Endif

  Else
    modBillings.InsertBillViewCount(BillNo)
    If modSettings.ShowSettingFromFIle("Invoice/TextFile_Source") = "Text" Then
      BillingLINEInvoice(BillNo, txTitle, ShowTax, ShowDisc)
    Else
      BillingHTMLInvoice(BillNo, txTitle, ShowTax, ShowDisc)
    Endif
  Endif

End

Public Sub PrintSelectedInvoice(sBillNo As String)

  Dim ShowTax As Boolean
  Dim ShowDisc As Boolean

  ShowTax = True
  ShowDisc = False
  BillingInvoice(sBillNo, modBillings.GetCopyBillTypeFromBillNo(sBillNo), ShowTax, ShowDisc)

End

Private Sub SetInvoiceSettings()

  $ShowCategory = modSettings.ShowSettingFromFIle("Invoice/ShowCategory")
  $ShowBatch = modSettings.ShowSettingFromFIle("Invoice/ShowBatch")
  $ShowExpiry = modBasic.$BillExpiryFormat
  $ShowQuantity = modSettings.ShowSettingFromFIle("Invoice/ShowQuantity")
  $TextTaxDiscount = modSettings.ShowSettingFromFIle("Invoice/TaxDiscount_Text")
  $ShowTaxDiscount = modSettings.ShowSettingFromFIle("Invoice/ShowTaxDisc")

  $EnableExtraLabel = modSettings.ShowSettingFromFIle("Invoice/EnableExtraLabel")
  $ShowSumDisc = modSettings.ShowSettingFromFIle("Invoice/ShowSumDiscount")
  $ShowTaxSum = modSettings.ShowSettingFromFIle("Invoice/ShowSumTax")
  $GroupItem = modSettings.ShowSettingFromFIle("Invoice/GroupItem")
  $PartiSuffix = modSettings.ShowSettingFromFIle("Invoice/ParticularSuffix")
  $InvDateFormat = modSettings.ShowSettingFromFIle("Invoice/DateFormat")

  $NoteI_Font = modSettings.ShowSettingFromFIle("Invoice/EndNoteI_Font")
  $Note2_Font = modSettings.ShowSettingFromFIle("Invoice/EndNoteII_Font")
  $Note1_Text = modSettings.ShowSettingFromFIle("Invoice/EndNoteI_Text")
  $Note2_Text = modSettings.ShowSettingFromFIle("Invoice/EndNoteII_Text")

End

Private Sub BillingHTMLInvoice(BillNo As String, txTitle As String, ShowTax As Boolean, ShowDisc As Boolean)

  Dim $BillingReport As CReportBILL
  Dim hClas As CBillDataPlus
  Dim sql As String
  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result
  Dim rcv As Float
  Dim rsunit As String
  Dim asx As New String[0]
  Dim i As Integer
  Dim hdr As String[]

  Dim qty As Float
  Dim rte As Float
  Dim tax As Float
  Dim disc As Float
  Dim tot As Float
  Dim xitem As String

  Dim taxdisc As String
  Dim tdamt As String
  Dim xdisc As Float
  Dim xtax As Float

  Dim sTime As Date
  Dim sUser As String
  Dim sComp As String
  Dim txtmode As String

  Inc Application.Busy
  'Query for header and footer content
  sql = "select fldencounterval,fldprevdeposit,flditemamt,fldtaxamt,flddiscountamt,fldchargedamt,fldreceivedamt,fldcurdeposit,fldbilltype,fldtaxgroup,flddiscountgroup,flduserid,fldtime,fldcomp,fldchequeno,fldbankname from tblpatbilldetail where fldbillno=&1"                                                                    '''
  res = modDatabase.$myConn.Exec(sql, BillNo)                                                                                       ''
  rcv = res!fldreceivedamt
  sTime = res!fldtime
  sUser = res!flduserid
  sComp = res!fldcomp
  txtmode = res!fldbilltype
  If modBasic.$currency Then
    rsunit = modBasic.$currency
  Else
    rsunit = modString.CurrencySymbol()
  Endif

  'create table structure
  hdr = New String[]
  hdr.Add(Space(1))
  If $ShowCategory = "Yes" Then
    hdr.Add("CATEGORY")
  Endif
  hdr.Add("PARTICULARS")
  'show batch
  If $ShowBatch = "Yes" Then
    hdr.Add("BATCH")
  Endif
  'show expiry
  If $ShowExpiry And If $ShowExpiry <> "No" Then
    hdr.Add("EXPIRY")
  Endif
  'show qty
  If $ShowQuantity = "No" Then
  Else
    hdr.Add("QTY")
  Endif
  hdr.Add("RATE")
  'show tax/disc
  If $TextTaxDiscount Then
    'get column label
    If $TextTaxDiscount = "TaxPer/DiscPer" Then
      taxdisc = "Tax%/Disc%"
    Else If $TextTaxDiscount = "TaxPerOnly" Then
      taxdisc = "Tax%"
    Else If $TextTaxDiscount = "DiscPerOnly" Then
      taxdisc = "Disc%"
    Else If $TextTaxDiscount = "TaxAmt/DiscAmt" Then
      taxdisc = "Tax/Disc"
    Else If $TextTaxDiscount = "TaxAmtOnly" Then
      taxdisc = "TaxAmt"
    Else If $TextTaxDiscount = "DiscAmtOnly" Then
      taxdisc = "DiscAmt"
    Endif
    'show column
    If $ShowTaxDiscount Then
      If $ShowTaxDiscount = "Always" Then
        hdr.Add(taxdisc)
      Else If $ShowTaxDiscount = "NotNull" Then
        If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Tax%" Or If taxdisc = "TaxAmt" Then
          If ShowTax = True Then
            hdr.Add(taxdisc)
          Endif
        Else If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Disc%" Or If taxdisc = "DiscAmt" Then
          If ShowDisc = True Then
            hdr.Add(taxdisc)
          Endif
        Endif
      Endif
    Endif
  Endif
  hdr.Add("TOTAL")
  $BillingReport = New CReportBILL(hdr, modHelpVariable.$htmlDirectory, "Invoice", res!fldencounterval, txtmode)

  'Header content
  $BillingReport.UserData.Add(txTitle, "InvoiceType")
  $BillingReport.UserData.Add(BillNo, "InvoiceNumber")
  $BillingReport.UserData.Add(modBillings.GetInvoicePrintCount(BillNo), "BillPrintCount")
  If $EnableExtraLabel = "Yes" Then
    hClas = New CBillDataPlus(BillNo)
    $BillingReport.UserData.Add(hClas.ReferName(), "ReferLabel")
    $BillingReport.UserData.Add(hClas.PayableName(), "PayableLabel")
    $BillingReport.UserData.Add(hClas.ReturnBillNo(), "ReturnBillNo")
    $BillingReport.UserData.Add(hClas.ReturnReason(), "ReturnReason")
  Endif

  'Cash or Credit invoice summary
  $BillingReport.UserData.Add(res!fldtaxgroup, "TaxGroup")
  $BillingReport.UserData.Add(res!flddiscountgroup, "DiscountGroup")
  $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldprevdeposit, gb.Fixed), "PrevDeposit")
  $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!flditemamt, gb.Fixed), "SubTotal")

  If $ShowSumDisc = "No" Then
    $BillingReport.UserData.Add("", "Discount")
  Else If $ShowSumDisc = "NotNull" Then
    If res!flddiscountamt Then
      $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!flddiscountamt, gb.Fixed), "Discount")
    Else
      $BillingReport.UserData.Add("", "Discount")
      If GetDiscSettingString(txtmode) Then
        $BillingReport.SPecData.Add("", GetDiscSettingString(txtmode))
      Endif
    Endif
  Else
    $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!flddiscountamt, gb.Fixed), "Discount")
  Endif

  $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldchargedamt, gb.Fixed), "TotalAmount")

  If $ShowTaxSum = "No" Then
    $BillingReport.UserData.Add("", "TotalTax")
  Else If $ShowTaxSum = "NotNull" Then
    If res!fldtaxamt Then
      $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldtaxamt, gb.Fixed), "TotalTax")
    Else
      $BillingReport.UserData.Add("", "TotalTax")
      If GetTaxSettingString(txtmode) Then
        $BillingReport.SPecData.Add("", GetTaxSettingString(txtmode))
      Endif
    Endif
  Else
    $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldtaxamt, gb.Fixed), "TotalTax")
  Endif

  $BillingReport.UserData.Add(rsunit & Space(1) & Format(rcv, gb.Fixed), "ReceAmount")
  $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldcurdeposit, gb.Fixed), "CurrDeposit")

  'Amount in words and User info
  $BillingReport.UserData.Add(modString.ConvertMoneyToText(rcv), "AmtWord")
  $BillingReport.UserData.Add(sUser & "@" & GetUserLocationForBill(sComp), "BillUser")
  $BillingReport.UserData.Add(modDate.GetDateTimeInFormatForAll(sTime, $InvDateFormat, ""), "BillDateTime")
  $BillingReport.UserData.Add(rsunit & Space(1) & Format((res!flditemamt - res!flddiscountamt), gb.Fixed), "TaxableAmt")

  'Footer notes
  $BillingReport.UserData.Add(res!fldbankname, "BankName")
  $BillingReport.UserData.Add(res!fldchequeno, "ChequeNumber")
  $BillingReport.UserData.Add(modString.GetFormatTextFontString($Note1_Text, $NoteI_Font), "Note1")
  $BillingReport.UserData.Add(modString.GetFormatTextFontString($Note2_Text, $Note2_Font), "NoteII")

  'Fill columns (with/without item grouping)
  If $GroupItem = "Yes" Then
    res1 = modDatabase.$myConn.Exec("select distinct(flditemtype) from tblpatbilling where fldbillno=&1", BillNo)
    For Each res1

      res2 = modDatabase.$myConn.Exec("select distinct(flditemno) from tblpatbilling where fldbillno=&1 and flditemtype=&2", BillNo, res1!flditemtype)                                 ''
      i = 1
      For Each res2

        res3 = modDatabase.$myConn.Exec("select flditemname,flditemqty,flditemrate,fldtaxper,flddiscper from tblpatbilling where fldbillno=&1 and flditemtype=&2 and flditemno=&3", BillNo, res1!flditemtype, res2!flditemno)
        qty = 0
        rte = 0
        tax = 0
        disc = 0
        xdisc = 0
        xtax = 0
        tot = 0
        For Each res3
          qty = qty + res3!flditemqty
          rte = rte + res3!flditemrate
          tax = tax + res3!fldtaxper
          disc = disc + res3!flddiscper
          xdisc = xdisc + res3!flditemqty * res3!flditemrate * (res3!flddiscper / 100)
          xtax = xtax + res3!flditemqty * res3!flditemrate * (1 - res3!flddiscper / 100) * (res3!fldtaxper / 100)
          tot = tot + res3!flditemqty * res3!flditemrate
        Next
        res3.MoveFirst

        With asx
          .Add(CStr(i))
          'show categ
          If $ShowCategory = "Yes" Then
            .Add(res1!flditemtype)
          Endif
          .Add(modBillings.GetIteminFormatForBill(res3!flditemname, res1!flditemtype))
          'show batch
          If $ShowBatch = "Yes" Then
            .Add(modBillings.GetBatchForBillFromCategory(res2!flditemno, res1!flditemtype))
          Endif
          'show expiry
          If $ShowExpiry And If $ShowExpiry <> "No" Then
            .Add(modBillings.GetExpiryForBillFromCategory(res2!flditemno, res1!flditemtype))
          Endif
          'show qty
          If $ShowQuantity = "No" Then
          Else
            .Add(qty)
          Endif
          .Add(Format(rte / res3.Count, gb.Fixed))
          'show tax/disc
          If $TextTaxDiscount Then
            If $TextTaxDiscount = "TaxPer/DiscPer" Then
              tdamt = CStr(Round(tax / res3.Count, -2)) & "/" & CStr(Round(disc / res3.Count, -2)) & "%"
            Else If $TextTaxDiscount = "TaxPerOnly" Then
              tdamt = CStr(Round(tax / res3.Count, -2)) & "%"
            Else If $TextTaxDiscount = "DiscPerOnly" Then
              tdamt = CStr(Round(disc / res3.Count, -2)) & "%"
            Else If $TextTaxDiscount = "TaxAmt/DiscAmt" Then
              tdamt = Format(xtax / res3.Count, gb.Fixed) & "/" & Format(xdisc / res3.Count, gb.Fixed)
            Else If $TextTaxDiscount = "TaxAmtOnly" Then
              tdamt = Format(xtax / res3.Count, gb.Fixed)
            Else If $TextTaxDiscount = "DiscAmtOnly" Then
              tdamt = Format(xdisc / res3.Count, gb.Fixed)
            Endif

            If $ShowTaxDiscount Then
              If $ShowTaxDiscount = "Always" Then
                .Add(tdamt)
              Else If $ShowTaxDiscount = "NotNull" Then
                If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Tax%" Or If taxdisc = "TaxAmt" Then
                  If ShowTax = True Then
                    .Add(tdamt)
                  Endif
                Else If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Disc%" Or If taxdisc = "DiscAmt" Then
                  If ShowDisc = True Then
                    .Add(tdamt)
                  Endif
                Endif
              Endif
            Endif

          Endif
          .Add(Format(tot, gb.Fixed))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
        i = i + 1

      Next 'ends res2

    Next 'ends res1

  Else
    i = 1
    res1 = modDatabase.$myConn.Exec("select flditemno,flditemname,flditemrate,flditemqty,fldtaxper,flddiscper,flditemtype,fldpayto,fldrefer from tblpatbilling where fldbillno=&1 ORDER BY flditemtype", BillNo)
    For Each res1

      If $PartiSuffix = "Payable" Then
        If res1!fldpayto Then
          xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype) & " (" & modGeneral.GetUserFullNamePrint(res1!fldpayto) & ")"
        Else
          xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype)
        Endif
      Else If $PartiSuffix = "Referral" Then
        If res1!fldrefer Then
          xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype) & " (" & modGeneral.GetUserFullNamePrint(res1!fldrefer) & ")"
        Else
          xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype)
        Endif
      Else
        xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype)
      Endif

      With asx
        .Add(CStr(i))
        'show categ
        If $ShowCategory = "Yes" Then
          .Add(res1!flditemtype)
        Endif
        .Add(xitem)
        'show batch
        If $ShowBatch = "Yes" Then
          .Add(modBillings.GetBatchForBillFromCategory(res1!flditemno, res1!flditemtype))
        Endif
        'show expiry
        If $ShowExpiry And If $ShowExpiry <> "No" Then
          .Add(modBillings.GetExpiryForBillFromCategory(res1!flditemno, res1!flditemtype))
        Endif
        'show qty
        If $ShowQuantity = "No" Then
        Else
          .Add(res1!flditemqty)
        Endif
        .Add(Format(res1!flditemrate, gb.Fixed))
        'show tax/disc
        If $TextTaxDiscount Then
          If $TextTaxDiscount = "TaxPer/DiscPer" Then
            tdamt = CStr(Round(res1!fldtaxper, -2)) & "/" & CStr(Round(res1!flddiscper, -2)) & "%"
          Else If $TextTaxDiscount = "TaxPerOnly" Then
            tdamt = CStr(Round(res1!fldtaxper, -2)) & "%"
          Else If $TextTaxDiscount = "DiscPerOnly" Then
            tdamt = CStr(Round(res1!flddiscper, -2)) & "%"
          Else If $TextTaxDiscount = "TaxAmt/DiscAmt" Then
            tdamt = Format(res1!flditemqty * res1!flditemrate * (1 - res1!flddiscper / 100) * (res1!fldtaxper / 100), gb.Fixed) & "/" & Format(res1!flditemqty * res1!flditemrate * (res1!flddiscper / 100), gb.Fixed)
          Else If $TextTaxDiscount = "TaxAmtOnly" Then
            tdamt = Format(res1!flditemqty * res1!flditemrate * (1 - res1!flddiscper / 100) * (res1!fldtaxper / 100), gb.Fixed)
          Else If $TextTaxDiscount = "DiscAmtOnly" Then
            tdamt = Format(res1!flditemqty * res1!flditemrate * (res1!flddiscper / 100), gb.Fixed)
          Endif

          If $ShowTaxDiscount Then
            If $ShowTaxDiscount = "Always" Then
              .Add(tdamt)
            Else If $ShowTaxDiscount = "NotNull" Then
              If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Tax%" Or If taxdisc = "TaxAmt" Then
                If ShowTax = True Then
                  .Add(tdamt)
                Endif
              Else If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Disc%" Or If taxdisc = "DiscAmt" Then
                If ShowDisc = True Then
                  .Add(tdamt)
                Endif
              Endif
            Endif
          Endif

        Endif
        .Add(Format(res1!flditemqty * res1!flditemrate, gb.Fixed))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1

    Next 'ends res1

  Endif
  Dec Application.Busy

  'Finally make report
  $BillingReport.Preview("InvoiceSize")

End

Private Sub BillingLINEInvoice(BillNo As String, txTitle As String, ShowTax As Boolean, ShowDisc As Boolean)

  Dim $BillingReport As CTextBIll
  Dim hClas As CBillDataPlus
  Dim sql As String
  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result
  Dim rcv As Float
  Dim rsunit As String
  Dim asx As New String[0]
  Dim i As Integer
  Dim hdr As String[]

  Dim qty As Float
  Dim rte As Float
  Dim tax As Float
  Dim disc As Float
  Dim tot As Float
  Dim xitem As String

  Dim taxdisc As String
  Dim tdamt As String
  Dim xdisc As Float
  Dim xtax As Float

  Dim sTime As Date
  Dim sUser As String
  Dim sComp As String
  Dim txtmode As String

  Inc Application.Busy
  'Query for header and footer content
  sql = "select fldencounterval,fldprevdeposit,flditemamt,fldtaxamt,flddiscountamt,fldchargedamt,fldreceivedamt,fldcurdeposit,fldbilltype,fldtaxgroup,flddiscountgroup,flduserid,fldtime,fldcomp,fldchequeno,fldbankname from tblpatbilldetail where fldbillno=&1"                                                                    '''
  res = modDatabase.$myConn.Exec(sql, BillNo)                                                                                       ''
  rcv = res!fldreceivedamt
  sTime = res!fldtime
  sUser = res!flduserid
  sComp = res!fldcomp
  txtmode = res!fldbilltype
  If modBasic.$currency Then
    rsunit = modBasic.$currency
  Else
    rsunit = modString.CurrencySymbol()
  Endif

  'create table structure
  hdr = New String[]
  hdr.Add(".")
  'show categ
  If $ShowCategory = "Yes" Then
    hdr.Add("CATEGORY")
  Endif
  hdr.Add("PARTICULARS")
  'show batch
  If $ShowBatch = "Yes" Then
    hdr.Add("BATCH")
  Endif
  'show expiry
  If $ShowExpiry And If $ShowExpiry <> "No" Then
    hdr.Add("EXPIRY")
  Endif
  'show qty
  If $ShowQuantity = "No" Then
  Else
    hdr.Add("QTY")
  Endif
  hdr.Add("RATE")
  'show tax/disc
  If $TextTaxDiscount Then
    'column label
    If $TextTaxDiscount = "TaxPer/DiscPer" Then
      taxdisc = "Tax%/Disc%"
    Else If $TextTaxDiscount = "TaxPerOnly" Then
      taxdisc = "Tax%"
    Else If $TextTaxDiscount = "DiscPerOnly" Then
      taxdisc = "Disc%"
    Else If $TextTaxDiscount = "TaxAmt/DiscAmt" Then
      taxdisc = "Tax/Disc"
    Else If $TextTaxDiscount = "TaxAmtOnly" Then
      taxdisc = "TaxAmt"
    Else If $TextTaxDiscount = "DiscAmtOnly" Then
      taxdisc = "DiscAmt"
    Endif
    'show column
    If $ShowTaxDiscount Then
      If $ShowTaxDiscount = "Always" Then
        hdr.Add(taxdisc)
      Else If $ShowTaxDiscount = "NotNull" Then
        If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Tax%" Or If taxdisc = "TaxAmt" Then
          If ShowTax = True Then
            hdr.Add(taxdisc)
          Endif
        Else If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Disc%" Or If taxdisc = "DiscAmt" Then
          If ShowDisc = True Then
            hdr.Add(taxdisc)
          Endif
        Endif
      Endif
    Endif
  Endif
  hdr.Add("TOTAL")
  $BillingReport = New CTextBIll(hdr, modHelpVariable.$textDirectory, "Invoice", res!fldencounterval, txtmode)

  'Header content
  $BillingReport.UserData.Add(txTitle, "InvoiceType")
  $BillingReport.UserData.Add(BillNo, "InvoiceNumber")
  $BillingReport.UserData.Add(modBillings.GetInvoicePrintCount(BillNo), "BillPrintCount")
  If $EnableExtraLabel = "Yes" Then
    hClas = New CBillDataPlus(BillNo)
    $BillingReport.UserData.Add(hClas.ReferName(), "ReferLabel")
    $BillingReport.UserData.Add(hClas.PayableName(), "PayableLabel")
    $BillingReport.UserData.Add(hClas.ReturnBillNo(), "ReturnBillNo")
    $BillingReport.UserData.Add(hClas.ReturnReason(), "ReturnReason")
  Endif

  'Cash or Credit invoice summary
  $BillingReport.UserData.Add(res!fldtaxgroup, "TaxGroup")
  $BillingReport.UserData.Add(res!flddiscountgroup, "DiscountGroup")
  $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldprevdeposit, gb.Fixed), "PrevDeposit")
  $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!flditemamt, gb.Fixed), "SubTotal")

  If $ShowSumDisc = "No" Then
    $BillingReport.UserData.Add("", "Discount")
  Else If $ShowSumDisc = "NotNull" Then
    If res!flddiscountamt Then
      $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!flddiscountamt, gb.Fixed), "Discount")
    Else
      $BillingReport.UserData.Add("", "Discount")
      If GetDiscSettingString(txtmode) Then
        $BillingReport.SPecData.Add("", GetDiscSettingString(txtmode))
      Endif
    Endif
  Else
    $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!flddiscountamt, gb.Fixed), "Discount")
  Endif

  $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldchargedamt, gb.Fixed), "TotalAmount")

  If $ShowTaxSum = "No" Then
    $BillingReport.UserData.Add("", "TotalTax")
  Else If $ShowTaxSum = "NotNull" Then
    If res!fldtaxamt Then
      $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldtaxamt, gb.Fixed), "TotalTax")
    Else
      $BillingReport.UserData.Add("", "TotalTax")
      If GetTaxSettingString(txtmode) Then
        $BillingReport.SPecData.Add("", GetTaxSettingString(txtmode))
      Endif
    Endif
  Else
    $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldtaxamt, gb.Fixed), "TotalTax")
  Endif

  $BillingReport.UserData.Add(rsunit & Space(1) & Format(rcv, gb.Fixed), "ReceAmount")
  $BillingReport.UserData.Add(rsunit & Space(1) & Format(res!fldcurdeposit, gb.Fixed), "CurrDeposit")

  'Amount in words and User info
  $BillingReport.UserData.Add(modString.ConvertMoneyToText(rcv), "AmtWord")
  $BillingReport.UserData.Add(sUser & "@" & GetUserLocationForBill(sComp), "BillUser")
  $BillingReport.UserData.Add(modDate.GetDateTimeInFormatForAll(sTime, $InvDateFormat, ""), "BillDateTime")
  $BillingReport.UserData.Add(rsunit & Space(1) & Format((res!flditemamt - res!flddiscountamt), gb.Fixed), "TaxableAmt")

  'Footer notes
  $BillingReport.UserData.Add(res!fldbankname, "BankName")
  $BillingReport.UserData.Add(res!fldchequeno, "ChequeNumber")
  $BillingReport.UserData.Add(Font[$NoteI_Font].Name, "Fnt1")
  $BillingReport.UserData.Add(Font[$Note2_Font].Name, "Fnt2")
  $BillingReport.UserData.Add($Note1_Text, "Note1")
  $BillingReport.UserData.Add($Note2_Text, "NoteII")

  'Fill columns (with/without item grouping)
  If $GroupItem = "Yes" Then
    res1 = modDatabase.$myConn.Exec("select distinct(flditemtype) from tblpatbilling where fldbillno=&1", BillNo)
    For Each res1

      res2 = modDatabase.$myConn.Exec("select distinct(flditemno) from tblpatbilling where fldbillno=&1 and flditemtype=&2", BillNo, res1!flditemtype)                                 ''
      i = 1
      For Each res2

        res3 = modDatabase.$myConn.Exec("select flditemname,flditemqty,flditemrate,fldtaxper,flddiscper from tblpatbilling where fldbillno=&1 and flditemtype=&2 and flditemno=&3", BillNo, res1!flditemtype, res2!flditemno)
        qty = 0
        rte = 0
        tax = 0
        disc = 0
        xdisc = 0
        xtax = 0
        tot = 0
        For Each res3
          qty = qty + res3!flditemqty
          rte = rte + res3!flditemrate
          tax = tax + res3!fldtaxper
          disc = disc + res3!flddiscper
          xdisc = xdisc + res3!flditemqty * res3!flditemrate * (res3!flddiscper / 100)
          xtax = xtax + res3!flditemqty * res3!flditemrate * (1 - res3!flddiscper / 100) * (res3!fldtaxper / 100)
          tot = tot + res3!flditemqty * res3!flditemrate
        Next
        res3.MoveFirst

        With asx
          .Add(CStr(i))
          'show categ
          If $ShowCategory = "Yes" Then
            .Add(res1!flditemtype)
          Endif
          .Add(modBillings.GetIteminFormatForBill(res3!flditemname, res1!flditemtype))
          'show batch
          If $ShowBatch = "Yes" Then
            .Add(modBillings.GetBatchForBillFromCategory(res2!flditemno, res1!flditemtype))
          Endif
          'show expiry
          If $ShowExpiry And If $ShowExpiry <> "No" Then
            .Add(modBillings.GetExpiryForBillFromCategory(res2!flditemno, res1!flditemtype))
          Endif
          'show qty
          If $ShowQuantity = "No" Then
          Else
            .Add(qty)
          Endif
          .Add(Format(rte / res3.Count, gb.Fixed))
          'show tax/disc
          If $TextTaxDiscount Then
            If $TextTaxDiscount = "TaxPer/DiscPer" Then
              tdamt = CStr(Round(tax / res3.Count, -2)) & "/" & CStr(Round(disc / res3.Count, -2)) & "%"
            Else If $TextTaxDiscount = "TaxPerOnly" Then
              tdamt = CStr(Round(tax / res3.Count, -2)) & "%"
            Else If $TextTaxDiscount = "DiscPerOnly" Then
              tdamt = CStr(Round(disc / res3.Count, -2)) & "%"
            Else If $TextTaxDiscount = "TaxAmt/DiscAmt" Then
              tdamt = Format(xtax / res3.Count, gb.Fixed) & "/" & Format(xdisc / res3.Count, gb.Fixed)
            Else If $TextTaxDiscount = "TaxAmtOnly" Then
              tdamt = Format(xtax / res3.Count, gb.Fixed)
            Else If $TextTaxDiscount = "DiscAmtOnly" Then
              tdamt = Format(xdisc / res3.Count, gb.Fixed)
            Endif

            If $ShowTaxDiscount Then
              If $ShowTaxDiscount = "Always" Then
                .Add(tdamt)
              Else If $ShowTaxDiscount = "NotNull" Then
                If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Tax%" Or If taxdisc = "TaxAmt" Then
                  If ShowTax = True Then
                    .Add(tdamt)
                  Endif
                Else If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Disc%" Or If taxdisc = "DiscAmt" Then
                  If ShowDisc = True Then
                    .Add(tdamt)
                  Endif
                Endif
              Endif
            Endif

          Endif
          .Add(Format(tot, gb.Fixed))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
        i = i + 1

      Next 'ends res2

    Next 'ends res1

  Else
    i = 1
    res1 = modDatabase.$myConn.Exec("select flditemno,flditemname,flditemrate,flditemqty,fldtaxper,flddiscper,flditemtype,fldpayto,fldrefer from tblpatbilling where fldbillno=&1 ORDER BY flditemtype", BillNo)
    For Each res1

      If $PartiSuffix = "Payable" Then
        If res1!fldpayto Then
          xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype) & " (" & modGeneral.GetUserFullNamePrint(res1!fldpayto) & ")"
        Else
          xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype)
        Endif
      Else If $PartiSuffix = "Referral" Then
        If res1!fldrefer Then
          xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype) & " (" & modGeneral.GetUserFullNamePrint(res1!fldrefer) & ")"
        Else
          xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype)
        Endif
      Else
        xitem = modBillings.GetIteminFormatForBill(res1!flditemname, res1!flditemtype)
      Endif

      With asx
        .Add(CStr(i))
        'show categ
        If $ShowCategory = "Yes" Then
          .Add(res1!flditemtype)
        Endif
        .Add(xitem)
        'show batch
        If $ShowBatch = "Yes" Then
          .Add(modBillings.GetBatchForBillFromCategory(res1!flditemno, res1!flditemtype))
        Endif
        'show expiry
        If $ShowExpiry And If $ShowExpiry <> "No" Then
          .Add(modBillings.GetExpiryForBillFromCategory(res1!flditemno, res1!flditemtype))
        Endif
        'show qty
        If $ShowQuantity = "No" Then
        Else
          .Add(res1!flditemqty)
        Endif
        .Add(Format(res1!flditemrate, gb.Fixed))
        'show tax/disc
        If $TextTaxDiscount Then
          If $TextTaxDiscount = "TaxPer/DiscPer" Then
            tdamt = CStr(Round(res1!fldtaxper, -2)) & "/" & CStr(Round(res1!flddiscper, -2)) & "%"
          Else If $TextTaxDiscount = "TaxPerOnly" Then
            tdamt = CStr(Round(res1!fldtaxper, -2)) & "%"
          Else If $TextTaxDiscount = "DiscPerOnly" Then
            tdamt = CStr(Round(res1!flddiscper, -2)) & "%"
          Else If $TextTaxDiscount = "TaxAmt/DiscAmt" Then
            tdamt = Format(res1!flditemqty * res1!flditemrate * (1 - res1!flddiscper / 100) * (res1!fldtaxper / 100), gb.Fixed) & "/" & Format(res1!flditemqty * res1!flditemrate * (res1!flddiscper / 100), gb.Fixed)
          Else If $TextTaxDiscount = "TaxAmtOnly" Then
            tdamt = Format(res1!flditemqty * res1!flditemrate * (1 - res1!flddiscper / 100) * (res1!fldtaxper / 100), gb.Fixed)
          Else If $TextTaxDiscount = "DiscAmtOnly" Then
            tdamt = Format(res1!flditemqty * res1!flditemrate * (res1!flddiscper / 100), gb.Fixed)
          Endif

          If $ShowTaxDiscount Then
            If $ShowTaxDiscount = "Always" Then
              .Add(tdamt)
            Else If $ShowTaxDiscount = "NotNull" Then
              If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Tax%" Or If taxdisc = "TaxAmt" Then
                If ShowTax = True Then
                  .Add(tdamt)
                Endif
              Else If taxdisc = "Tax%/Disc%" Or If taxdisc = "Tax/Disc" Or If taxdisc = "Disc%" Or If taxdisc = "DiscAmt" Then
                If ShowDisc = True Then
                  .Add(tdamt)
                Endif
              Endif
            Endif
          Endif

        Endif
        .Add(Format(res1!flditemqty * res1!flditemrate, gb.Fixed))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1

    Next 'ends res1

  Endif
  Dec Application.Busy

  'Finally make report
  $BillingReport.Preview("InvoiceSize")

End

''-------------------------------------------------General Functions ---------------------------------------
Private Function GetUserLocationForBill(sComp As String) As String

  Dim xx As String
  Dim xdept As String

  xdept = modSettings.ShowSettingFromFIle("Invoice/BillingLocation")
  If xdept = "Department" Then
    xx = modGeneral.GetCompNameFromCompID(sComp)
  Else
    xx = sComp
  Endif

  Return xx

End

Public Function GetTaxSettingString(sType As String) As String

  Dim slst As String[] = ["11", "12", "21", "22", "31", "32", "41", "42"]
  Dim xx As String
  Dim tax As String

  For Each xx In slst
    If modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col" & xx & "_" & sType) = "{TotalTax}" Then
      tax = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col" & xx & "_" & sType)
    Endif
  Next
  Return tax

End

Public Function GetDiscSettingString(sType As String) As String

  Dim slst As String[] = ["11", "12", "21", "22", "31", "32", "41", "42"]
  Dim xx As String
  Dim disc As String

  For Each xx In slst
    If modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterText_Col" & xx & "_" & sType) = "{Discount}" Then
      disc = modSettings.ShowSettingFromFIle("Invoice/BuiltIn_FooterLabel_Col" & xx & "_" & sType)
    Endif
  Next
  Return disc

End

Public Sub InvoiceReturnReport(sBillno As String)

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim xtot As Float
  Dim i As Integer
  Dim encid As String

  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result

  Inc Application.Busy
  encid = modBillings.GetEncounterFromBillNo(sBillno)
  $BillingReport = New CReportHTML([(""), ("PARTICULARS"), ("QTY"), ("RATE"), ("TOTAL")], modHelpVariable.$htmlDirectory, "PatientReport", encid)

  $BillingReport.UserData.Add("INVOICE REPORT", "Report")
  $BillingReport.UserData.Add(sBillno, "PARAM1")

  xtot = 0
  i = 1                                                 ''
  res = modDatabase.$myConn.Exec("select flditemname,flditemrate,flditemqty,fldtaxper,flddiscper,fldditemamt as tot,fldid from tblpatbilling where fldbillno=&1 and fldencounterval=&2", sBillno, encid)
  If res.Available Then
    $BillingReport.AddChapter(sBillno)

    For Each res
      xtot = xtot + res!tot
      With asx
        .Add(modReportVar.GetLocaleNumberFormat(i, 0))
        .Add(res!flditemname)
        .Add(modReportVar.GetLocaleNumberFormat(res!flditemqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(res!flditemrate, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(res!tot, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1
    Next

  Endif

  res1 = modDatabase.$myConn.Exec("select distinct(fldbillno) as billno from tblpatbilling where fldretbill=&1 and fldencounterval=&2", sBillno, encid)
  If res1.Available Then
    For Each res1
      $BillingReport.AddChapter(res1!billno)

      i = 1
      res2 = modDatabase.$myConn.Exec("select flditemname,flditemrate,flditemqty,fldtaxper,flddiscper,fldditemamt as tot,fldid from tblpatbilling where fldretbill=&1 and fldencounterval=&2 and fldbillno=&3", sBillno, encid, res1!billno)
      If res2.Available Then
        For Each res2
          xtot = xtot + res2!tot
          With asx
            .Add(modReportVar.GetLocaleNumberFormat(i, 0))
            .Add(res2!flditemname)
            .Add(modReportVar.GetLocaleNumberFormat(res2!flditemqty, -2))
            .Add(modReportVar.GetLocaleNumberFormat(res2!flditemrate, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(res2!tot, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
          i = i + 1
        Next
      Endif

    Next
  Endif

  With asx
    .Add("....")
    .Add("....")
    .Add("....")
    .Add("....")
    .Add("....")
  End With
  $BillingReport.Add(asx)

  asx.Clear()
  With asx
    .Add("....")
    .Add("TOTAL")
    .Add("....")
    .Add("....")
    .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  Dec Application.Busy

  modPrint.OpenHTMLPreview(encid, $BillingReport.NewHTMLPath(), "InvoiceSize")

End
