' Gambas module file

Public $EncColumn As Integer
Private $ProgressBar1 As ProgressBar

'''==================================== EXPORT =======================================================
Public Function HideColumnExport() As Integer[]

  Dim xcuscol As String
  Dim xcolmns As String[]
  Dim xcol As String
  Dim noCols As Integer[]

  xcuscol = modSettings.ShowSettingFromFIle("ReportColumnVisibility/ExcludeColumns")
  noCols = New Integer[]
  If xcuscol Then
    xcolmns = Split(xcuscol, ",")
    For Each xcol In xcolmns
      noCols.Add(CInt(xcol) - 1)
    Next
  Endif
  Return noCols

End

Public Sub ExportGridToHTML(GridView1 As GridView, param1 As String, param2 As String, Optional summary As String[], Optional encid As String)

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim Column As Integer
  Dim Row As Integer
  Dim hdr As String[]

  Dim TotalCol As String[]
  Dim i As Integer
  Dim xpic As String

  Dim xvismode As String
  Dim noCols As Integer[]

  If MMain.$IsGUIApp = True Then
    $ProgressBar1 = modHelpVariable.FindWorkProgressBar(modHelpVariable.$LogInCategory)
    $ProgressBar1.Tag = "Const"
  Endif

  xvismode = modSettings.ShowSettingFromFIle("ReportColumnVisibility/VisibilityMode")
  noCols = HideColumnExport()

  If GridView1.Columns.Count = 0 Then Return
  Inc Application.Busy
  hdr = New String[]
  hdr.Add("SNo")

  If xvismode = "Yes" Then
    For Column = 0 To GridView1.Columns.Count - 1
      If noCols.Exist(Column) = False Then
        hdr.Add(GridView1.Columns[Column].Text)
      Endif
    Next

  Else
    For Column = 0 To GridView1.Columns.Count - 1
      If GridView1.Columns[Column].Width > 5 Then
        hdr.Add(GridView1.Columns[Column].Text)
      Endif
    Next
  Endif

  If encid Then
    $BillingReport = New CReportHTML(hdr, modHelpVariable.$htmlDirectory, "PatientReport", encid)
    $BillingReport.UserData.Add(param1, "PARAM1")
    $BillingReport.UserData.Add(param2, "Report")
  Else
    $BillingReport = New CReportHTML(hdr, modHelpVariable.$htmlDirectory, "", "")
    $BillingReport.UserData.Add(param1, "PARAM1")
    $BillingReport.UserData.Add(param2, "PARAM2")
  Endif

  If xvismode = "Yes" Then
    For Row = 0 To GridView1.Rows.Count - 1
      With asx
        .Add(Row + 1)
        For Column = 0 To GridView1.Columns.Count - 1
          If noCols.Exist(Column) = False Then
            If GridView1[Row, Column].Picture Then
              xpic = Temp() & ".png"
              GridView1[Row, Column].Picture.Save(xpic)
              .Add("<img src=" & xpic & ">")
            Else
              If GridView1[Row, Column].RichText Then
                .Add(GridView1[Row, Column].RichText)
              Else
                .Add(GridView1[Row, Column].Text)
              Endif
            Endif
          Endif
        Next
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      If MMain.$IsGUIApp = True Then
        $ProgressBar1.Value = (Row + 1) / GridView1.Rows.Count
        Wait
      Endif
    Next

  Else
    For Row = 0 To GridView1.Rows.Count - 1
      With asx
        .Add(Row + 1)
        For Column = 0 To GridView1.Columns.Count - 1
          If GridView1.Columns[Column].Width > 5 Then
            If GridView1[Row, Column].Picture Then
              xpic = Temp() & ".png"
              GridView1[Row, Column].Picture.Save(xpic)
              .Add("<img src=" & xpic & ">")
            Else
              If GridView1[Row, Column].RichText Then
                .Add(GridView1[Row, Column].RichText)
              Else
                .Add(GridView1[Row, Column].Text)
              Endif
            Endif
          Endif
        Next
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      If MMain.$IsGUIApp = True Then
        $ProgressBar1.Value = (Row + 1) / GridView1.Rows.Count
        Wait
      Endif
    Next

  Endif

  If xvismode = "Yes" Then
  Else
    TotalCol = New String[]
    If summary Then
      TotalCol = summary
    Endif
    If TotalCol.Count > 0 Then
      With asx
        .Add("")
        For i = 0 To TotalCol.Count - 1
          .Add(TotalCol[i])
        Next
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif
  Endif

  Dec Application.Busy
  modExternal.$ExecValueColl.Clear()
  modPrint.DisplayReportExport($BillingReport.NewHTMLPath())

End
