' Gambas module file

''-----------------------------------------PATIENT WISE CLINICAL --------------------------------------------------------------------------
Public Function PatientMedicationForReturn(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result

  Dim regimen As String
  Dim xdose As Float
  Dim xpck As Float
  Dim i As Integer

  $BillingReport = New CReportHTML([("SNo"), ("Particulars"), ("Regimen"), ("Status"), ("DispQTY"), ("AdminQTY"), ("UnusedQTY")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("UNUSED MEDICATION", "Report")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM1")

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldid,fldroute,flditem,flddose,fldfreq,flddays,fldqtydisp,fldqtyret,fldcurval from tblpatdosing where fldencounterval=&1 and fldsave_order=&2 and flditemtype=&3 ORDER BY flditem", encid, True, "Medicines")
  If res.Available Then
    i = 1
    For Each res
      If res["fldroute"] = "fluid" Then
        regimen = res["fldroute"] & Space(2) & res["flddose"] & " mL X " & res["fldfreq"] & " X " & res["flddays"]
      Else
        regimen = res["fldroute"] & Space(2) & res["flddose"] & " mg X " & res["fldfreq"] & " X " & res["flddays"]
      Endif
      res1 = modDatabase.$syConn.Exec("select SUM(fldvalue) as col from tblnurdosing where fldencounterval=&1 and flddoseno=&2", encid, res["fldid"])
      xdose = 0
      If res1.Available Then
        xpck = modPharmLabel.GetPackVolValue(res["flditem"])
        If res1["col"] And If xpck Then
          xdose = Round(res1["col"] / xpck, -2)
        Endif
      Endif
      With asx
        .Add(CStr(i))
        .Add(res["flditem"])
        .Add(regimen)
        .Add(res["fldcurval"])
        .Add((res["fldqtydisp"] - res["fldqtyret"]))
        .Add(xdose)
        .Add((res["fldqtydisp"] - res["fldqtyret"] - xdose))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1
    Next
  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function NursingCheckReport(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res1 As Result
  Dim i As Integer

  Dim res2 As Result
  Dim j As Integer

  Dim res3 As Result
  Dim k As Integer

  Inc Application.Busy
  $BillingReport = New CReportHTML([("SNo"), ("Particulars"), ("Regimen"), ("Today")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("NURSING CHECK REPORT", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res1 = modDatabase.$syConn.Exec("select flditem,fldevery,fldunit from tblmonitor where fldencounterval=&1 and fldstatus=&2 and fldcategory=&3", encid, "Continue", "Exam")
  If res1.Available Then
    $BillingReport.AddSection("Monitoring")
    i = 1

    For Each res1
      With asx
        .Add(CStr(i))
        .Add(res1["flditem"])
        .Add(res1["fldevery"] & " " & res1["fldunit"])
        .Add(modString.TextToHTML(modClinic.GetALLReportExamSelString(encid, res1["flditem"], Now()).Join(gb.NewLine)))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1
    Next
    With asx
      .Add("")
      .Add("****")
      .Add("****")
      .Add("****")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Endif

  res2 = modDatabase.$syConn.Exec("select fldid,fldroute,flditem,flddose,fldfreq,flddays from tblpatdosing where fldencounterval=&1 and fldsave_order=&2 and fldstarttime<=&3 and fldendtime>=&4 and flditemtype=&5 and fldcurval=&6", encid, True, modDate.EndSqlDate(Now()), modDate.StartSqlDate(Now()), "Medicines", "Continue")
  If res2.Available Then
    $BillingReport.AddSection("Medication")
    j = 1

    For Each res2
      With asx
        .Add(CStr(j))
        .Add(res2["flditem"])
        .Add(res2!fldroute & Space(2) & res2!flddose & " X " & res2!fldfreq)
        .Add(modString.TextToHTML(modPharmacy.GetALLReportDrugSelString(encid, res2["fldid"], Now()).Join(gb.NewLine)))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      j = j + 1
    Next
    With asx
      .Add("")
      .Add("****")
      .Add("****")
      .Add("****")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Endif

  res3 = modDatabase.$syConn.Exec("select fldid,fldcategory,flditem,flddose,fldfreq from tblextradosing where fldencounterval=&1 and fldstatus=&2 and fldsave=&3", encid, "Continue", True)
  If res3.Available Then
    $BillingReport.AddSection("PO Intake")
    k = 1

    For Each res3
      With asx
        .Add(CStr(k))
        .Add(res3["flditem"])
        .Add(res3["flddose"] & " Grams " & res3["fldfreq"])
        .Add(modString.TextToHTML(modPatientGeneral.GetALLReportFoodSelString(encid, res3["flditem"], Now()).Join(gb.NewLine)))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      k = k + 1
    Next
    With asx
      .Add("")
      .Add("****")
      .Add("****")
      .Add("****")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowBedTransitionReport(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Department"), ("BedNo"), ("InDate"), ("InBY"), ("OutDate"), ("OutBY"), ("Duration")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("BED TRANSITION", "PARAM1")

  res = modDatabase.$syConn.Exec("select fldid,flditem,fldsecondreport,fldfirsttime,fldfirstuserid,fldsecondtime,fldseconduserid,fldcomment from tblpattiming where fldencounterval=&1 and fldtype=&2 and fldfirstreport=&3 and fldsecondsave=&4", encid, "General Services", "Bed", True)
  If res.Available Then
    For Each res
      With asx
        .Add(res!flditem)
        .Add(res!fldsecondreport)
        .Add(modReportVar.GetDateTimeReport(res!fldfirsttime, gb.GeneralDate))
        .Add(res!fldfirstuserid)
        .Add(modReportVar.GetDateTimeReport(res!fldsecondtime, gb.GeneralDate))
        .Add(res!fldseconduserid)
        .Add(modPatientGeneral.GetBedTransitionInterval(res!fldid))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatientPlanningReport(encid As String, sType As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Dim zzz As Date[]
  Dim red1 As Result
  Dim $dt As Date

  Inc Application.Busy
  If sType = "Clinician Plan" Then
    $BillingReport = New CReportHTML([("Time"), ("Problem"), ("Subjective"), ("Objective"), ("Assessment"), ("Clinician Plan")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Else If sType = "IP Monitoring" Then
    $BillingReport = New CReportHTML([("Time"), ("Problem"), ("On Examination"), ("Treatment"), ("I/O Assessment"), ("Impression"), ("Nursing Plan")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add(sType, "PARAM1")

  zzz = New Date[]
  red1 = modDatabase.$syConn.Exec("select fldtime from tblpatplanning where fldencounterval=&1 and fldplancategory=&2", encid, sType)
  For Each red1

    If zzz.Count = 0 Then
      zzz.Add(modDate.StartSqlDate(red1!fldtime))
    Else
      If zzz.Exist(modDate.StartSqlDate(red1!fldtime)) = False Then
        zzz.Add(modDate.StartSqlDate(red1!fldtime))
      Endif
    Endif

  Next

  zzz.Sort()
  For Each $dt In zzz
    $BillingReport.AddSection(modReportVar.GetDateTimeReport($dt, gb.MediumDate), True)

    res = modDatabase.$syConn.Exec("select fldid,fldtime,fldproblem,fldsubjective,fldobjective,fldassess,fldplan from tblpatplanning where fldencounterval=&1 and fldplancategory=&2 and fldtime>=&3 and fldtime<=&4", encid, sType, modDate.StartSqlDate($dt), modDate.EndSqlDate($dt))
    For Each res
      With asx
        If sType = "Clinician Plan" Then
          .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime))
          .Add(res!fldproblem)
          .Add(res!fldsubjective)
          .Add(res!fldobjective)
          .Add(res!fldassess)
          .Add(res!fldplan)
        Else If sType = "IP Monitoring" Then
          .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime))
          .Add(res!fldsubjective)
          .Add(modPatReports.UniProcedureExamination(encid, res!fldid, "IP Monitoring").Join("<br>"))
          .Add(res!fldobjective)
          .Add(res!fldassess)
          .Add(res!fldproblem)
          .Add(res!fldplan)
        Endif
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatientNoteReport(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Dim zzz As Date[]
  Dim red1 As Result
  Dim $dt As Date

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Category"), ("Note"), ("Impression")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("CLINICAL NOTES", "PARAM1")

  zzz = New Date[]
  red1 = modDatabase.$syConn.Exec("select fldtime from tblexamgeneral where fldencounterval=&1 and fldinput=&2", encid, "Notes")
  For Each red1

    If zzz.Count = 0 Then
      zzz.Add(modDate.StartSqlDate(red1!fldtime))
    Else
      If zzz.Exist(modDate.StartSqlDate(red1!fldtime)) = False Then
        zzz.Add(modDate.StartSqlDate(red1!fldtime))
      Endif
    Endif

  Next

  zzz.Sort()
  For Each $dt In zzz
    $BillingReport.AddSection(modReportVar.GetDateTimeReport($dt, gb.MediumDate), True)

    res = modDatabase.$syConn.Exec("select fldtime,flditem,fldreportquali,flddetail from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldtime>=&3 and fldtime<=&4", encid, "Notes", modDate.StartSqlDate($dt), modDate.EndSqlDate($dt))
    For Each res
      With asx
        .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime))
        .Add(res!flditem)
        .Add(res!flddetail)
        .Add(res!fldreportquali)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''
Public Function ShowRecomExaminationpatient(encid As String, sCategory As String, subCategory As String, sDepart As String, sref As String) As String

  Dim $BillingReport As CReportHTML
  Dim res1 As Result
  Dim res As Result
  Dim res2 As Result
  Dim asx As New String[0]
  Dim xType As String

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Examination"), ("Observation")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add(subCategory, "PARAM1")

  res1 = modDatabase.$syConn.Exec("select distinct(flditem) from tblstructexam where fldclass=&1 and fldsubclass=&2 and fldcategory=&3 and fldreferencee=&4", sDepart, sCategory, subCategory, sref)
  For Each res1
    $BillingReport.AddSection(res1!flditem, True)

    res = modDatabase.$syConn.Exec("select distinct(fldhead) as col from tblpatientexam where fldinput=&1 and fldencounterval=&2 and fldsave=&3 and fldserialval in(select fldheadcode from tblstructexam where fldsubclass=&4 and fldcategory=&5 and fldreferencee=&6 and flditem=&7 and fldclass=&8)", "Rec Examination", encid, True, sCategory, subCategory, sref, res1!flditem, sDepart)
    If res.Available Then
      For Each res

        res2 = modDatabase.$syConn.Exec("select fldid,fldtime,fldhead,fldabnormal,fldrepquali,fldrepquanti,fldoption from tblpatientexam where fldinput=&1 and fldencounterval=&2 and fldsave=&3 and fldhead=&4 and fldserialval in(select fldheadcode from tblstructexam where fldsubclass=&5 and fldcategory=&6 and fldreferencee=&7 and flditem=&8 and fldclass=&9)", "Rec Examination", encid, True, res!col, sCategory, subCategory, sref, res1!flditem, sDepart)
        If res2.Available Then
          res2.MoveLast
          xType = res2["fldoption"]
          With asx
            .Add(modString.HTMLBlankSpace(5) & modReportVar.GetDateTimeReport(res2!fldtime, gb.GeneralDate))
            .Add(res!col)
            If xType = "Clinical Scale" Then
              If modBasic.$ShowScaleMedFormat = "GroupWise" Then
                .Add(modString.GetJSONToDualHTMLTable(res2!fldrepquali))
              Else
                .Add(CStr(res2!fldrepquanti))
              Endif
            Else If xType = "Left and Right" Then
              .Add(modString.GetJSONToDualHTMLTable(res2!fldrepquali))
            Else
              .Add(Trim(res2!fldrepquali))
            Endif
          End With
          $BillingReport.Add(asx)
          asx.Clear()
        Endif

      Next
    Endif
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatientExaminationReportAll(encid As String, sType As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim res1 As Result

  Dim zzz As Date[]
  Dim red2 As Result
  Dim $dt As Date
  Dim xstr As String

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Examination"), ("Observation")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("EXAMINATION", "PARAM1")

  zzz = New Date[]
  red2 = modDatabase.$syConn.Exec("select fldtime from tblpatientexam where fldencounterval=&1 and fldsave=&2", encid, True)
  For Each red2

    If zzz.Count = 0 Then
      zzz.Add(modDate.StartSqlDate(red2!fldtime))
    Else
      If zzz.Exist(modDate.StartSqlDate(red2!fldtime)) = False Then
        zzz.Add(modDate.StartSqlDate(red2!fldtime))
      Endif
    Endif

  Next

  zzz.Sort()
  For Each $dt In zzz
    $BillingReport.AddSection(modReportVar.GetDateTimeReport($dt, gb.MediumDate), True)

    res = modDatabase.$syConn.Exec("select fldid,fldtype,fldtime from tblpatientexam where fldencounterval=&1 and fldtime>=&2 and fldtime<=&3 and fldsave=&4 and fldinput like &5", encid, modDate.StartSqlDate($dt), modDate.EndSqlDate($dt), True, sType)
    For Each res
      With asx
        .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime))
        .Add(modClinic.GetExamNameFromExamID(res!fldid))
        If res!fldtype = "Quantitative" Then
          xstr = modClinic.GetExamLimitSrtings(res!fldid)
          If xstr Then
            .Add(modClinic.GetExamValueString(encid, res!fldid, True) & " [" & xstr & "]")
          Else
            .Add(modClinic.GetExamValueString(encid, res!fldid, True))
          Endif
        Else If res!fldtype = "Qualitative" Then
          xstr = modClinic.GetExamLimitSrtings(res!fldid)
          If xstr Then
            .Add(modClinic.GetExamValueString(encid, res!fldid, True) & " [" & modString.TextToHTML(xstr) & "]")
          Else
            .Add(modClinic.GetExamValueString(encid, res!fldid, True))
          Endif
        Endif
      End With
      $BillingReport.Add(asx)
      asx.Clear()

      If res!fldtype = "Qualitative" Then
        res1 = modDatabase.$syConn.Exec("select fldsubtexam,fldreport,fldid from tblpatientsubexam where fldheadid=&1 and fldsave=&2", res!fldid, True)
        If res1.Available Then
          For Each res1
            With asx
              .Add("")
              .Add(modString.TextToHTML(modString.HTMLBlankSpace(3) & res1!fldsubtexam))
              .Add(modString.TextToHTML(res1!fldreport))
            End With
            $BillingReport.Add(asx)
            asx.Clear()
          Next
        Endif
      Endif

    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatientExaminationgReport(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Dim zzz As Date[]
  Dim red2 As Result
  Dim $dt As Date
  Dim xtable As String[]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Depart"), ("Category"), ("Examination"), ("Observation"), ("Comment")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("EXAMINATION", "PARAM1")

  zzz = New Date[]
  red2 = modDatabase.$syConn.Exec("select fldtime from tblpatientexam where fldencounterval=&1 and fldsave=&2", encid, True)
  For Each red2

    If zzz.Count = 0 Then
      zzz.Add(modDate.StartSqlDate(red2!fldtime))
    Else
      If zzz.Exist(modDate.StartSqlDate(red2!fldtime)) = False Then
        zzz.Add(modDate.StartSqlDate(red2!fldtime))
      Endif
    Endif

  Next

  zzz.Sort()
  For Each $dt In zzz
    $BillingReport.AddSection(modReportVar.GetDateTimeReport($dt, gb.MediumDate), True)

    res = modDatabase.$syConn.Exec("select fldid,fldtype,fldtime,fldinput,fldhead,fldcomp,fldmethod from tblpatientexam where fldencounterval=&1 and fldtime>=&2 and fldtime<=&3 and fldsave=&4", encid, modDate.StartSqlDate($dt), modDate.EndSqlDate($dt), True)
    For Each res
      With asx
        .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime))
        .Add(modGeneral.GetCompNameFromCompID(res!fldcomp))
        .Add(modMisc.GetStringWithoutIndex(res!fldinput))
        If res!fldmethod = "Regular" Then
          .Add(res!fldhead)
        Else
          .Add(res!fldhead & "<br>" & "[" & res!fldmethod & "]")
        Endif
        If res!fldtype = "Quantitative" Then
          .Add(modClinic.GetExamValueString(encid, res!fldid, True))
        Else If res!fldtype = "Qualitative" Then
          xtable = modClinic.GetSubExamQualiList(encid, res!fldid)
          If xtable Then
            .Add(modString.TextToHTML(modClinic.GetExamValueString(encid, res!fldid, True) & modString.GetHTMLListFormat(xtable)))
          Else
            .Add(modString.TextToHTML(modClinic.GetExamValueString(encid, res!fldid, True)))
          Endif
        Endif
        .Add("")
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatRadioReportbyEncID(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]

  Dim res1 As Result
  Dim res2 As Result
  Dim xx As String
  Dim xtable As String[]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Date"), ("Examination"), ("Evaluation"), ("Observation"), ("Comment")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("EncounterID", "Report")
  $BillingReport.UserData.Add(encid, "PARAM1")

  res1 = modDatabase.$syConn.Exec("select distinct(fldcategory) from tblradio where fldexamid in(select fldtestid from tblpatradiotest where fldsave_report=&1 and fldencounterval=&2 and flvisible=&3)", True, encid, "Visible")
  For Each res1
    $BillingReport.AddSection(res1!fldcategory, True)
    res2 = modDatabase.$syConn.Exec("select fldid,fldtest_type,fldtestid,fldtime_report,fldabnormal,fldstatus,fldmethod,fldsampletype from tblpatradiotest where fldsave_report=&1 and fldencounterval=&2 and flvisible=&3 and fldtestid in(select fldexamid from tblradio where fldcategory=&4)", True, encid, "Visible", res1!fldcategory)
    For Each res2
      With asx
        .Add(modReportVar.GetDateTimeReport(res2!fldtime_report, gb.GeneralDate))
        .Add(res2!fldtestid)
        .Add(res2!fldsampletype)

        If res2!fldtest_type = "Quantitative" Then
          .Add(modRadioTest.GetRadioTestValueString(encid, res2!fldid, True))
        Else If res2!fldtest_type = "Qualitative" Then
          xx = modRadioTest.GetRadioTestValueString(encid, res2!fldid, True)
          xtable = modRadioTest.GetRadioSubTestQuali(encid, res2!fldid)
          If xtable Then
            .Add(modString.TextToHTML(xx & modString.GetHTMLListFormat(xtable)))
          Else
            .Add(modString.TextToHTML(xx))
          Endif
        Endif
        .Add(modString.TextToHTML(modRadioTest.GetRadioTestLimitSrting(res2!fldid)))

      End With
      $BillingReport.Add(asx)
      asx.Clear()

    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatRadioReportAllEnc(encno As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim encid As String
  Dim encList As String[]

  Dim res2 As Result
  Dim xx As String
  Dim xtable As String

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Date"), ("Examination"), ("Evaluation"), ("Observation"), ("Comment")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("RADIOLOGY", "PARAM1")

  encList = modPatient.GetEncListFromPatNo(modPatient.GetPatientNoByEnc(encno))
  For Each encid In encList
    $BillingReport.AddSection(encid, True)

    res2 = modDatabase.$syConn.Exec("select fldid,fldtest_type,fldtestid,fldtime_report,fldabnormal,fldstatus,fldmethod,fldsampletype from tblpatradiotest where fldsave_report=&1 and fldencounterval=&2 and flvisible=&3", True, encid, "Visible")
    For Each res2
      With asx
        .Add(modReportVar.GetDateTimeReport(res2!fldtime_report, gb.GeneralDate))
        If res2!fldmethod Then
          .Add(res2!fldtestid & "<br>" & "[" & res2!fldmethod & "]")
        Else
          .Add(res2!fldtestid)
        Endif
        .Add(res2!fldsampletype)

        If res2!fldtest_type = "Quantitative" Then
          .Add(modRadioTest.GetRadioTestValueString(encid, res2!fldid, True))
        Else If res2!fldtest_type = "Qualitative" Then
          xx = modRadioTest.GetRadioTestValueString(encid, res2!fldid, True)
          xtable = modString.GetHTMLListFormat(modRadioTest.GetRadioSubTestQuali(encid, res2!fldid))
          If xtable Then
            .Add(modString.TextToHTML(xx & xtable))
          Else
            .Add(modString.TextToHTML(xx))
          Endif
        Endif
        .Add(modString.TextToHTML(modRadioTest.GetRadioTestLimitSrting(res2!fldid)))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatLabReportbySampleID(encid As String, sampleid As String, unt As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res2 As Result
  Dim xquali As String[]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Examination"), ("Observation"), ("Comment")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("SampleID", "Report")
  $BillingReport.UserData.Add(sampleid, "PARAM1")

  res2 = modDatabase.$syConn.Exec("select fldid,fldtest_type,fldtestid,fldsampleid,fldtime_sample,fldabnormal,fldstatus from tblpatlabtest where fldsave_report=&1 and fldsampleid=&2 and fldencounterval=&3 and flvisible=&4", True, sampleid, encid, "Visible")
  For Each res2
    With asx
      .Add(res2!fldtestid)
      If res2!fldtest_type = "Quantitative" Then
        .Add(modLabTest.GetLabTestValueString(encid, res2!fldid, unt, True))
      Else
        xquali = modLabTest.GetLabSubTestQuali(encid, res2!fldid)
        If xquali Then
          .Add(modLabTest.GetLabTestValueString(encid, res2!fldid, unt, True) & modString.GetHTMLListFormat(xquali))
        Else
          .Add(modLabTest.GetLabTestValueString(encid, res2!fldid, unt, True))
        Endif
      Endif

      .Add("")

    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatientAllLaboratoryReport(encno As String, unt As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim encList As String[]
  Dim encid As String

  Dim xx As String
  Dim xtable As String

  Inc Application.Busy
  $BillingReport = New CReportHTML([("DateTime"), ("Specimen"), ("Examination"), ("Observation"), ("Comment")], modHelpVariable.$htmlDirectory, "PatientReport", encno)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("INVESTIGATIONS", "PARAM1")

  encList = modPatient.GetEncListFromPatNo(modPatient.GetPatientNoByEnc(encno))
  For Each encid In encList
    $BillingReport.AddSection(encid, True)

    res = modDatabase.$syConn.Exec("select fldid,fldsampletype,fldtest_type,fldtime_sample,fldmethod,fldtestid from tblpatlabtest where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3) and flvisible=&4", encid, "Reported", "Verified", "Visible")
    For Each res
      With asx
        .Add(modReportVar.GetDateTimeReport(res!fldtime_sample, gb.GeneralDate))
        .Add(res!fldsampletype)
        .Add(res!fldtestid & "<br>" & "[" & res!fldmethod & "]")
        If res!fldtest_type = "Quantitative" Then
          .Add(modLabTest.GetLabTestValueString(encid, res!fldid, unt, True))
        Else If res!fldtest_type = "Qualitative" Then
          xx = modLabTest.GetLabTestValueString(encid, res!fldid, unt, True)
          xtable = modString.GetHTMLListFormat(modLabTest.GetLabSubTestQuali(encid, res!fldid))
          If xtable Then
            .Add(modString.TextToHTML(xx & xtable))
          Else
            .Add(modString.TextToHTML(xx))
          Endif
        Endif
        .Add("")

      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatientLaboratoryReport(encid As String, unt As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Dim zzz As Date[]
  Dim red3 As Result
  Dim $dt As Date
  Dim xx As String
  Dim xtable As String

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Specimen"), ("Examination"), ("Observation"), ("Comment")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("INVESTIGATIONS", "PARAM1")

  zzz = New Date[]
  red3 = modDatabase.$syConn.Exec("select fldtime_sample from tblpatlabtest where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3) and flvisible=&4", encid, "Reported", "Verified", "Visible")
  For Each red3

    If zzz.Count = 0 Then
      zzz.Add(modDate.StartSqlDate(red3!fldtime_sample))
    Else
      If zzz.Exist(modDate.StartSqlDate(red3!fldtime_sample)) = False Then
        zzz.Add(modDate.StartSqlDate(red3!fldtime_sample))
      Endif
    Endif

  Next

  zzz.Sort()
  For Each $dt In zzz
    $BillingReport.AddSection(modReportVar.GetDateTimeReport($dt, gb.MediumDate), True)

    res = modDatabase.$syConn.Exec("select fldid,fldsampletype,fldtest_type,fldtime_sample,fldmethod,fldtestid from tblpatlabtest where fldencounterval=&1 and fldtime_sample>=&2 and fldtime_sample<=&3 and (fldstatus=&4 or fldstatus=&5) and flvisible=&6", encid, modDate.StartSqlDate($dt), modDate.EndSqlDate($dt), "Reported", "Verified", "Visible")
    For Each res
      With asx
        .Add(modReportVar.GetDateTimeReport(res!fldtime_sample, gb.MediumTime))
        .Add(res!fldsampletype)
        .Add(res!fldtestid & "<br>" & "[" & res!fldmethod & "]")
        If res!fldtest_type = "Quantitative" Then
          .Add(modLabTest.GetLabTestValueString(encid, res!fldid, unt, True))
        Else If res!fldtest_type = "Qualitative" Then
          xx = modLabTest.GetLabTestValueString(encid, res!fldid, unt, True)
          xtable = modString.GetHTMLListFormat(modLabTest.GetLabSubTestQuali(encid, res!fldid))
          If xtable Then
            .Add(modString.TextToHTML(xx & xtable))
          Else
            .Add(modString.TextToHTML(xx))
          Endif
        Endif
        .Add("")
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatientLaboratoryImage(fldid As Long, encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim tempFile As String
  Dim hFile As Blob

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Particulars"), ("Description"), ("Image")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add(modLabTest.GetTestnameFromTestID(fldid), "PARAM1")

  res = modDatabase.$syConn.Exec("select fldtime,fldpic,fldtitle,flddetail,fldlink from tblpatientimage where fldtestid=&1 and fldencounterval=&2", fldid, encid)
  For Each res
    If res!fldlink Then
      Inc Application.Busy
      tempFile = modDevice.GetFileFromLocalFTP(res!fldlink)
      Dec Application.Busy
    Else
      hFile = res["fldpic"]
      If hFile.Length Then
        tempFile = Temp() & ".jpg"
        File.Save(tempFile, hFile.Data)
      Endif
    Endif

    With asx
      .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate))
      .Add(res!fldtitle)
      .Add(res!flddetail)
      .Add(modString.GetImageForHTML(tempFile))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPatientSymptomReport(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Dim zzz As Date[]
  Dim red1 As Result
  Dim $dt As Date

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Symptom"), ("Description"), ("Comment")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("CLINICAL SYMPTOMS", "PARAM1")

  zzz = New Date[]
  red1 = modDatabase.$syConn.Exec("select fldtime from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldsave=&3", encid, "Patient Symptoms", True)
  For Each red1

    If zzz.Count = 0 Then
      zzz.Add(modDate.StartSqlDate(red1!fldtime))
    Else
      If zzz.Exist(modDate.StartSqlDate(red1!fldtime)) = False Then
        zzz.Add(modDate.StartSqlDate(red1!fldtime))
      Endif
    Endif

  Next

  zzz.Sort()
  For Each $dt In zzz
    $BillingReport.AddSection(modReportVar.GetDateTimeReport($dt, gb.MediumDate), True)

    res = modDatabase.$syConn.Exec("select fldid,flditem,fldreportquali,flddetail,fldtime from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldsave=&3 and fldtime>=&4 and fldtime<=&5", encid, "Patient Symptoms", True, modDate.StartSqlDate($dt), modDate.EndSqlDate($dt))
    For Each res
      With asx
        .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime))
        .Add(res!flditem & "(" & res!fldreportquali & ")")
        .Add(res!flddetail)
        .Add(modPatientGeneral.GetPatientDrugSymptom(res!fldid) & "<br>" & modPatientGeneral.GetPatientDiseaseSymptom(res!fldid))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowNursingDosing(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim rs As Result
  Dim asx As New String[0]

  Dim zzz As Date[]
  Dim red1 As Result
  Dim $dt As Date

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Medicine"), ("Regimen"), ("Dose")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("Dosing Report", "PARAM1")

  zzz = New Date[]
  red1 = modDatabase.$syConn.Exec("select fldtime from tblnurdosing where fldencounterval=&1", encid)
  For Each red1

    If zzz.Count = 0 Then
      zzz.Add(modDate.StartSqlDate(red1!fldtime))
    Else
      If zzz.Exist(modDate.StartSqlDate(red1!fldtime)) = False Then
        zzz.Add(modDate.StartSqlDate(red1!fldtime))
      Endif
    Endif

  Next

  zzz.Sort()
  For Each $dt In zzz
    $BillingReport.AddSection(modReportVar.GetDateTimeReport($dt, gb.MediumDate), True)

    res = modDatabase.$syConn.Exec("select fldtime,flddoseno,fldvalue,fldunit from tblnurdosing where fldencounterval=&1 and fldtime>=&2 and fldtime<=&3", encid, modDate.StartSqlDate($dt), modDate.EndSqlDate($dt))
    For Each res
      rs = modDatabase.$syConn.Exec("select fldid,fldroute,flditem,flddose,fldfreq,flddays,flditemtype from tblpatdosing where fldid=&1", res!flddoseno)
      If rs!flditemtype = "Medicines" Then
        With asx
          .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumTime))
          .Add(modPharmacy.GetMedFormatForMedReport(rs!flditem, rs!fldroute))
          .Add(modPharmacy.GetDoseRegimenString(rs!fldid, True))
          .Add(res!fldvalue & Space(1) & res!fldunit)
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ExportQuantiClinToHTML(encid As String, strType As String, strItem As String[], unt As String, frm As Form) As String

  Dim $BillingReport As CReportHTML
  Dim drwNewCht As PictureBox
  Dim sPath As String
  Dim asx As New String[0]
  Dim xx As String

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Parameters"), ("Chart View")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add(strType, "PARAM1")

  For Each xx In strItem
    sPath = Temp() & ".png"
    drwNewCht = New PictureBox(frm)
    drwNewCht.Height = 150 * modBasic.$AppScaleFactor
    If strType = "Exam" Then
      modClinic.FillQuantiExamChart(drwNewCht, encid, xx)
    Else If strType = "Test" Then
      modLabTest.FillQuantiTestChart(drwNewCht, encid, xx, unt)
    Else If strType = "SetA" Then
      modClinic.DrawClinicalCharts_SetA(drwNewCht, encid, xx)
    Endif
    drwNewCht.Picture.Save(sPath)
    drwNewCht.Delete()

    With asx
      .Add(xx)
      .Add(modString.GetImageForHTML(sPath))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ExportMultiExamTestToHTML(encid As String, examlist As String[], testlist As String[], unt As String, frm As Form) As String

  Dim $BillingReport As CReportHTML
  Dim drwNewCht As PictureBox
  Dim sPath As String
  Dim asx As New String[0]
  Dim xx As String
  Dim yy As String

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Parameters"), ("Chart View")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("ChartView", "PARAM1")

  For Each xx In examlist
    If modFixClinic.GetExaminationType(xx) = "Quantitative" Then
      sPath = Temp() & ".png"
      drwNewCht = New PictureBox(frm)
      drwNewCht.Height = 150 * modBasic.$AppScaleFactor
      modClinic.FillQuantiExamChart(drwNewCht, encid, xx)
      drwNewCht.Picture.Save(sPath)
      drwNewCht.Delete()
      With asx
        .Add(xx)
        .Add(modString.GetImageForHTML(sPath))
      End With
      $BillingReport.Add(asx)
      asx.Clear()

    Else
      With asx
        .Add(xx)
        .Add(modClinic.UniExamValueList(encid, xx).Join("<br>"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()

    Endif
  Next

  For Each yy In testlist
    If modFixLab.GetLabTestType(yy) = "Quantitative" Then
      sPath = Temp() & ".png"
      drwNewCht = New PictureBox(frm)
      drwNewCht.Height = 150 * modBasic.$AppScaleFactor
      modLabTest.FillQuantiTestChart(drwNewCht, encid, yy, unt)
      drwNewCht.Picture.Save(sPath)
      drwNewCht.Delete()
      With asx
        .Add(yy)
        .Add("<div style='height:200px;width:800px;overflow:auto;'><img src=" & sPath & "></div>")
      End With
      $BillingReport.Add(asx)
      asx.Clear()

    Else
      With asx
        .Add(yy)
        .Add(modLabTest.UniLabValueList(encid, yy).Join("<br>"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()

    Endif
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''--------------------------------- Medication order -----------------------------------------------------------------------------
Public Function ShowMedicationOrder(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  $BillingReport = New CReportHTML([("SNo"), ("StartDate"), ("Medicine"), ("Route"), ("Regimen")], modHelpVariable.$htmlDirectory, "LaboratoryReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("Medication Order", "PARAM1")

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldid,fldstarttime,fldroute,flditem,flddose,fldfreq,flddays from tblpatdosing where fldencounterval=&1 and fldsave_order=&2 and flduserid_order=&3 and flditemtype=&4", encid, False, modGeneralMain.$lbluser, "Medicines")
  For Each res
    With asx
      .Add(CStr(res.Index + 1))
      .Add(modReportVar.GetDateTimeReport(res!fldstarttime, gb.GeneralDate))
      .Add(modPharmacy.GetMedFormatForMedReport(res!flditem, res!fldroute))
      .Add(res!fldroute)
      .Add(modPharmacy.GetDoseRegimenString(res!fldid, False))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowMedicationLabelReport(encid As String, dosid As Long[], LabelMode As String) As String

  Dim $BillingReport As CReportHTML
  Dim xx As Long
  Dim res As Result
  Dim asx As New String[0]
  Dim hCls As CLabelFreq

  Inc Application.Busy
  $BillingReport = New CReportHTML([("StartDate"), ("Medicine"), ("Regimen"), ("Direction"), ("Advice")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("Medication Labels", "PARAM1")

  For Each xx In dosid
    res = modDatabase.$syConn.Exec("select fldid,fldstarttime,fldroute,flditem,flddose,fldfreq,flddays,flditemtype from tblpatdosing where fldencounterval=&1 and fldid=&2 and (fldstatus=&3 or fldstatus=&4)", encid, xx, "Registered", "Admitted") '"Ordered"
    For Each res
      If res!flditemtype = "Medicines" Then
        hCls = New CLabelFreq(res!fldfreq, LabelMode)

        With asx
          .Add(modReportVar.GetDateTimeReport(res!fldstarttime, gb.GeneralDate))
          .Add(modPharmacy.GetMedFormatForMedReport(res!flditem, res!fldroute))
          .Add(modPharmLabel.GetQuantityLabel(res!flddose, res!flditem, LabelMode) & Space(1) & modPharmLabel.GetDosageFormForLabel(res!flditem, LabelMode) & Space(1) & modPharmLabel.GetLabelWordsFromDB("Every", LabelMode) & Space(1) & hCls.HourValue() & Space(1) & hCls.HourLabelText() & Space(1) & modPharmLabel.GetLabelWordsFromDB("Difference", LabelMode) & Space(1) & res!flddays & Space(1) & modPharmLabel.GetLabelWordsFromDB("Day", LabelMode))
          .Add(hCls.PrecaytionText())
          .Add(modPharmLabel.GetDirectionForLabel(res!fldroute, res!flditem, LabelMode))
        End With
        $BillingReport.Add(asx)
        asx.Clear()

      Endif
    Next
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowCounselingReport(encid As String, doslst As Long[]) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim did As Long

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Medicine"), ("Regimen"), ("Comment")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("COUNSELING", "PARAM1")

  For Each did In doslst
    With asx
      .Add(modPharmacy.GetMedFormatForMedReport(modPharmacy.GetStockIDFromDosing(did), modPharmacy.GetRouteFromDosing(did)))
      .Add(modPharmacy.GetDoseRegimenString(did, True))
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    $BillingReport.AddSummary(modPharmLabel.GetCounselingInfo(modPharmacy.GetRouteFromDosing(did), modPharmacy.GetStockIDFromDosing(did)))

    With asx
      .Add("***")
      .Add("***")
      .Add("***")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowSingleCounselingReport(dosid As Long) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Drug Information")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add(modPharmacy.GetMedFormatForMedReport(modPharmacy.GetStockIDFromDosing(dosid), modPharmacy.GetRouteFromDosing(dosid)), "PARAM1")
  $BillingReport.UserData.Add(modPharmacy.GetDoseRegimenString(dosid, True), "PARAM2")

  With asx
    .Add(modPharmLabel.GetCounselingInfo(modPharmacy.GetRouteFromDosing(dosid), modPharmacy.GetStockIDFromDosing(dosid)))
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''------------------------------------------------- procedure ---------------------------------------
Public Function ShowUniProcedureReport(itemid As Long, encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim abc As String[] = ["General:Status", "General:Personnel", "General:Summary", "Pre-Operative:Indication", "Pre-Operative:Discussion", "Pre-Operative:Discussion Panel", "Pre-Operative:Examination", "Pre-Operative:Medications", "Pre-Operative:Note", "Procedure:Components", "Procedure:Parameters", "Procedure:Medications", "Procedure:Incision", "Procedure:Findings", "Procedure:Proedures", "Procedure:Closure", "Procedure:Note", "Anaesthesia:Technique", "Anaesthesia:Parameters", "Anaesthesia:Medications", "Anaesthesia:Medications", "Anaesthesia:Note", "Post-Operative:Indication", "Post-Operative:Examination", "Post-Operative:Medications", "Post-Operative:Note"]
  Dim xxx As String[]

  xxx = SelectListView("Select Procedure Components", abc, False)
  If xxx Then
    Inc Application.Busy
    res = modDatabase.$syConn.Exec("select fldencounterval,fldinput,flditem,fldreportquali,flddetail,fldnewdate from tblpatgeneral where fldid=&1 and fldencounterval=&2", itemid, encid)
    $BillingReport = New CReportHTML([("Category"), ("Observation")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
    $BillingReport.UserData.Add("PROCEDURE NAME:  ", "Report")
    $BillingReport.UserData.Add(res!flditem, "PARAM1")

    'General
    $BillingReport.AddSection("General", True)
    If xxx.Exist("General:Status") Then
      With asx
        .Add("Status")
        .Add(modReportVar.GetDateTimeReport(res!fldnewdate, gb.GeneralDate) & " : " & res!fldreportquali)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("General:Personnel") Then
      With asx
        .Add("Personnel")
        .Add(modPatientGeneral.GetUserAllUniProcedure(res!fldencounterval, itemid))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("General:Summary") Then
      With asx
        .Add("Summary")
        .Add(res!flddetail)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    'preoperative
    $BillingReport.AddSection("Pre-Operative", True)
    If xxx.Exist("Pre-Operative:Indication") Then
      With asx
        .Add("Indication")
        .Add(modPatientGeneral.GetProcedureItemValue(res!fldencounterval, itemid, "Pre-Operative Indication"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Pre-Operative:Discussion") Then
      With asx
        .Add("Discussion")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Pre-Operative Discussion"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Pre-Operative:Discussion Panel") Then
      With asx
        .Add("Discussion Panel")
        .Add(modPatientGeneral.GetDiscusPanels(res!fldencounterval, itemid).Join(gb.NewLine))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Pre-Operative:Examination") Then
      With asx
        .Add("Examination")
        .Add(modPatReports.UniProcedureExamination(res!fldencounterval, itemid, "Pre-Operative Exam").Join("<br>"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Pre-Operative:Medications") Then
      With asx
        .Add("Medications")
        .Add(modPharmacy.UniProcedureMedString(res!fldencounterval, itemid, "Pre-Operative"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Pre-Operative:Note") Then
      With asx
        .Add("Note")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Pre-Operative Note"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    'procedure
    $BillingReport.AddSection("Procedure", True)
    If xxx.Exist("Procedure:Components") Then
      With asx
        .Add("Components")
        .Add(modPatientGeneral.GetComponentProcedure(res!fldencounterval, itemid).Join(gb.NewLine))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Procedure:Parameters") Then
      With asx
        .Add("Parameters")
        .Add(modPatReports.UniProcedureExamination(res!fldencounterval, itemid, "Operative Exam").Join("<br>"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Procedure:Medications") Then
      With asx
        .Add("Medications")
        .Add(modPharmacy.UniProcedureMedString(res!fldencounterval, itemid, "Procedure"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Procedure:Incision") Then
      With asx
        .Add("Incision")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Incision"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Procedure:Findings") Then
      With asx
        .Add("Findings")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Findings"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Procedure:Proedures") Then
      With asx
        .Add("Proedures")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Proedures"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Procedure:Closure") Then
      With asx
        .Add("Closure")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Closure"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Procedure:Note") Then
      With asx
        .Add("Note")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Operation Note"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    'anesthesia
    $BillingReport.AddSection("Anaesthesia", True)
    If xxx.Exist("Anaesthesia:Technique") Then
      With asx
        .Add("Technique")
        .Add(modPatientGeneral.GetProcedureItemValue(res!fldencounterval, itemid, "Anaesthesia Technique"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Anaesthesia:Parameters") Then
      With asx
        .Add("Parameters")
        .Add(modPatReports.UniProcedureExamination(res!fldencounterval, itemid, "Anaesthesia").Join("<br>"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Anaesthesia:Medications") Then
      With asx
        .Add("Medications")
        .Add(modPharmacy.UniProcedureMedString(res!fldencounterval, itemid, "Anaesthesia"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Anaesthesia:Note") Then
      With asx
        .Add("Note")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Anaesthesia Note"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    'post operative
    $BillingReport.AddSection("Post-Operative", True)
    If xxx.Exist("Post-Operative:Indication") Then
      With asx
        .Add("Indication")
        .Add(modPatientGeneral.GetProcedureItemValue(res!fldencounterval, itemid, "Post-Operative Indication"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Post-Operative:Examination") Then
      With asx
        .Add("Examination")
        .Add(modPatReports.UniProcedureExamination(res!fldencounterval, itemid, "Post-Operative Exam").Join("<br>"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Post-Operative:Medications") Then
      With asx
        .Add("Medications")
        .Add(modPharmacy.UniProcedureMedString(res!fldencounterval, itemid, "Post-Operative"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    If xxx.Exist("Post-Operative:Note") Then
      With asx
        .Add("Note")
        .Add(modPatientGeneral.GetUniProcedureDetail(res!fldencounterval, itemid, "Post-Operative Note"))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif

    Dec Application.Busy
    Return $BillingReport.NewHTMLPath()

  Endif

End

''------------------------------- Extra Procedure ----------------------------
Public Function GetExtProcedureExamReport(xid As Long, encid As String, sProcName As String, sSummary As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result

  $BillingReport = New CReportHTML([("Examination"), ("Pre-Procedure"), ("On-Procedure"), ("Post-Procedure")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add(sProcName, "PARAM1")

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select distinct(fldhead) as col from tblpatientexam where fldencounterval=&1 and fldinput like &2 and fldsave=&3", encid, "%:" & sProcName & ":" & CStr(xid), True)
  If res.Available Then
    For Each res
      With asx
        .Add(res!col)
        .Add(modClinic.GetExamValueSubString(modPatientGeneral.GetExtProcId(encid, "Pre:" & sProcName & ":" & CStr(xid), res!col)))
        .Add(modClinic.GetExamValueSubString(modPatientGeneral.GetExtProcId(encid, "On:" & sProcName & ":" & CStr(xid), res!col)))
        .Add(modClinic.GetExamValueSubString(modPatientGeneral.GetExtProcId(encid, "Post:" & sProcName & ":" & CStr(xid), res!col)))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    $BillingReport.AddSummary(sSummary)
  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''------------------ Delivery -----------------------------
Public Function ShowDeliveryReportFull(encid As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result
  Dim res4 As Result

  $BillingReport = New CReportHTML([("Time"), ("Examination"), ("Observation")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("Delivery", "PARAM1")

  Inc Application.Busy
  $BillingReport.AddSection("PRE DELIVERY", True)
  res1 = modDatabase.$syConn.Exec("select fldid,fldhead,fldtime from tblpatientexam where fldencounterval=&1 and fldinput=&2 and fldsave=&3", encid, "Pre Delivery Exam", True)
  For Each res1
    With asx
      .Add(modString.HTMLBlankSpace(5) & modReportVar.GetDateTimeReport(res1!fldtime, gb.GeneralDate))
      .Add(res1!fldhead)
      .Add(modClinic.GetExamValueString(encid, res1!fldid, True))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  $BillingReport.AddSection("ON DELIVERY", True)
  res2 = modDatabase.$syConn.Exec("select fldid,fldhead,fldtime from tblpatientexam where fldencounterval=&1 and fldinput=&2 and fldsave=&3", encid, "On Delivery Exam", True)
  For Each res2
    With asx
      .Add(modString.HTMLBlankSpace(5) & modReportVar.GetDateTimeReport(res2!fldtime, gb.GeneralDate))
      .Add(res2!fldhead)
      .Add(modClinic.GetExamValueString(encid, res2!fldid, True))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  $BillingReport.AddSection("POST DELIVERY", True)
  res3 = modDatabase.$syConn.Exec("select fldid,fldhead,fldtime from tblpatientexam where fldencounterval=&1 and fldinput=&2 and fldsave=&3", encid, "Post Delivery Exam", True)
  For Each res3
    With asx
      .Add(modString.HTMLBlankSpace(5) & modReportVar.GetDateTimeReport(res3!fldtime, gb.GeneralDate))
      .Add(res3!fldhead)
      .Add(modClinic.GetExamValueString(encid, res3!fldid, True))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  $BillingReport.AddSection("DELIVERY RESULT", True)
  res4 = modDatabase.$syConn.Exec("select fldid,flddelresult,flddeltype,fldbabypatno,flddeltime,flddelwt,fldcomment from tblconfinement where fldencounterval=&1", encid)
  For Each res4
    With asx
      .Add(modString.HTMLBlankSpace(5) & modReportVar.GetDateTimeReport(res4!flddeltime, gb.GeneralDate))
      .Add(res4!flddelresult & "<br>" & "Mode: " & res4!flddeltype)
      .Add("Patient No: " & res4!fldbabypatno & " <br> " & " Gender: " & modPatient.PatientGenderByPatNo(res4!fldbabypatno) & "<br>" & "Birth Weight: " & res4!flddelwt & " grams")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    $BillingReport.AddSummary(res4!fldcomment)

    With asx
      .Add("***")
      .Add("***")
      .Add("***")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End
