' Gambas module file

Public Function GetHandOverReport(encList As String[], sDept As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim enc As String
  Dim ximpres As String
  Dim xplan As String
  Dim xdate As Date
  Dim xuser As String

  $BillingReport = New CReportHTML([("BedNo"), ("EncID"), ("Name"), ("Age/Sex"), ("Date"), ("Impression"), ("Nursing Plan"), ("User")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("PROGRESS REPORT : " & sDept, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(xDate, gb.MediumDate), "PARAM2")

  Inc Application.Busy
  For Each enc In encList
    res = modDatabase.$myConn.Exec("select fldtime,fldproblem,fldplan,flduserid from tblpatplanning where fldencounterval=&1 and fldplancategory=&2", enc, "IP Monitoring")
    If res.Available Then
      res.MoveLast
      ximpres = res["fldproblem"]
      xplan = res["fldplan"]
      xdate = res["fldtime"]
      xuser = modGeneral.GetUserFullName(res["flduserid"])
    Else
      ximpres = ""
      xplan = ""
      xdate = ""
      xuser = ""
    Endif

    With asx
      .Add(modPatient.GetLocationSetting(enc))
      .Add(enc)
      .Add(modPatient.GetPatientNameByEnc(enc, modDatabase.$syConn))
      .Add(modPatient.GetPatientAgeString(enc, Now()) & "/" & modPatient.GetPatientSex(enc))
      .Add(modReportVar.GetDateTimeReport(xdate, gb.GeneralDate))
      .Add(ximpres)
      .Add(xplan)
      .Add(xuser)
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function GetPlannedFoodReport(xDate As Date, encList As String[], sDept As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim enc As String

  $BillingReport = New CReportHTML([("Timing"), ("Category"), ("Particulars"), ("Dose"), ("Label")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("NUTRITION PLANNING : " & sDept, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(xDate, gb.MediumDate), "PARAM2")

  Inc Application.Busy
  For Each enc In encList
    res = modDatabase.$myConn.Exec("select fldid,fldcategory,flditem,flddose,flddosetime,flddosecode from tblextradosing where fldencounterval=&1 and fldstatus=&2 and flddosetime>=&3 and flddosetime<=&4 and fldsave=&5 ORDER BY flddosetime", enc, "Continue", modDate.StartSqlDate(xDate), modDate.EndSqlDate(xDate), True)
    If res.Available Then

      $BillingReport.AddChapter("NAME: " & modPatient.GetPatientNameByEnc(enc, modDatabase.$syConn) & " (" & enc & ")          LOCATION: " & modPatient.GetLocationSetting(enc))
      For Each res
        With asx
          .Add(modReportVar.GetDateTimeReport(res["flddosetime"], gb.GeneralDate))
          .Add(res["fldcategory"])
          .Add(res["flditem"])
          .Add(res["flddose"])
          .Add(res["flddosecode"])
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next
      With asx
        .Add("****")
        .Add("****")
        .Add("****")
        .Add("****")
        .Add("****")
      End With
      $BillingReport.Add(asx)
      asx.Clear()

    Endif
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowFollowMedicineReport($dt As Date) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim xx As Long

  Inc Application.Busy
  $BillingReport = New CReportHTML([("StartDate"), ("Regimen"), ("DispQTY"), ("ReqQTY")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("FOLLOW UP MEDICINES", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport($dt, gb.MediumDate), "PARAM2")

  For Each xx In modPharmacy.GetMedicineFollowPatient($dt)
    $BillingReport.AddChapter("ENCOUNTER: " & xx & "<br>" & "NAME: " & modPatient.GetPatientNameByEnc(xx, modDatabase.$syConn) & "<br>" & "ADDRESS: " & modPatient.GetPatientAddressByEnc(xx, modDatabase.$syConn) & "<br>" & "CONTACT: " & modPatient.GetPatientContactByEnc(xx))
    res = modDatabase.$syConn.Exec("select fldid,fldstarttime,fldroute,flditem,flddose,fldfreq,flddays,fldqtydisp from tblpatdosing where fldsave_order=&1 and fldendtime>&2 and fldencounterval=&3", True, $dt, xx)
    For Each res
      If Ceil(modMedConstant.GetQuantityDosing(res!flditem, res!flddose, res!fldfreq, res!flddays)) > res!fldqtydisp And If DateDiff(res!fldstarttime, $dt, gb.Day) > modMedConstant.GetDrugUseDurationDosing(res!flditem, res!flddose, res!fldfreq, res!fldqtydisp) Then
        With asx
          .Add(modReportVar.GetDateTimeReport(res!fldstarttime, gb.GeneralDate))
          .Add(modPharmacy.GetMedFormatForMedReport(res!flditem, res!fldroute) & Space(1) & modPharmacy.GetDoseRegimenString(res!fldid, True))
          .Add(res!fldqtydisp)
          .Add(Ceil(modMedConstant.GetQuantityDosing(res!flditem, res!flddose, res!fldfreq, res!flddays)))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''------------------------------------------ Bed management ----------------------------------------------------
Public Function ShowBedOccupancyReport() As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim dept As String[]
  Dim xx As String
  Dim res As Result
  Dim res1 As Result

  Inc Application.Busy
  $BillingReport = New CReportHTML([("BedNo"), ("EncID"), ("Name"), ("Age/Sex"), ("Consult"), ("DOA")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("BED OCCUPANCY", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  dept = modMisc.GetDepartmentWithBedList()
  For Each xx In dept
    $BillingReport.AddSection(xx, True)

    res = modDatabase.$syConn.Exec("select fldbed from tbldepartmentbed where flddept=&1", xx)
    For Each res
      res1 = modDatabase.$syConn.Exec("select fldencounterval,fldadmission,flduserid,flddoa from tblencounter where fldcurrlocat=&1 and fldadmission=&2", res!fldbed, "Admitted")
      If res1.Available Then
        With asx
          .Add(res!fldbed)
          .Add(res1!fldencounterval)
          .Add(modPatient.GetPatientNameByEnc(res1!fldencounterval, modDatabase.$syConn))
          .Add(modPatient.GetPatientAgeString(res1!fldencounterval, Now()) & "/" & modPatient.GetPatientSex(res1!fldencounterval, modDatabase.$syConn))
          .Add(modGeneral.GetUserFullName(res1!flduserid))
          .Add(modReportVar.GetDateTimeReport(res1!flddoa, gb.MediumDate))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next

    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowBedOccupConsultReport() As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result

  Inc Application.Busy
  $BillingReport = New CReportHTML([("BedNo"), ("EncID"), ("Name"), ("Age/Sex"), ("Department"), ("DOA")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("BED OCCUPANCY", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(flduserid) as col from tblencounter where fldadmission=&1 and fldcurrlocat in(select fldbed from tbldepartmentbed)", "Admitted")
  For Each res
    $BillingReport.AddSection(modGeneral.GetUserFullName(res!col), True)

    res1 = modDatabase.$syConn.Exec("select fldcurrlocat,fldencounterval,fldadmission,flduserid,flddoa from tblencounter where flduserid=&1 and fldadmission=&2 and fldcurrlocat in(select fldbed from tbldepartmentbed)", res!col, "Admitted")
    If res1.Available Then
      For Each res1
        With asx
          .Add(res1!fldcurrlocat)
          .Add(res1!fldencounterval)
          .Add(modPatient.GetPatientNameByEnc(res1!fldencounterval, modDatabase.$syConn))
          .Add(modPatient.GetPatientAgeString(res1!fldencounterval, Now()) & "/" & modPatient.GetPatientSex(res1!fldencounterval, modDatabase.$syConn))
          .Add(modMisc.GetDepartmentNameFromBed(res1!fldcurrlocat))
          .Add(modReportVar.GetDateTimeReport(res1!flddoa, gb.MediumDate))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next
    Endif

    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''============================== Registration/Booking List ----------------------------------------
Public Function ShowBookingReport(dtfir As Date, dtlast As Date, sDept As String, sBillMode As String, sStatus As String, sComp As String, Optional sUser As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result

  Dim xdate As Date[]
  Dim datlist As Date[]
  Dim xx As Date
  Dim xdoc As String

  If sUser Then
    xdoc = sUser
  Else
    xdoc = "%"
  Endif

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Mode"), ("Department"), ("Consultant"), ("BookID"), ("Name"), ("Age/Sex"), ("Contact")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("BOOKING REPORT", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(dtfir, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dtlast, gb.MediumDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select fldconsultdate from tblpatientbook where fldadmitlocat like &1 and flduserid like &2 and fldbillingmode like &3 and fldstate=&4 and fldconsultdate>=&5 and fldconsultdate<=&6 and fldcomp like &7", sDept, xdoc, sBillMode, sStatus, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sComp)                                                                            ''
  xdate = New Date[]
  If res.Available Then
    For Each res

      If xdate.Count = 0 Then
        xdate.Add(modDate.StartSqlDate(res!fldconsultdate))
      Else
        If xdate.Exist(modDate.StartSqlDate(res!fldconsultdate)) = False Then
          xdate.Add(modDate.StartSqlDate(res!fldconsultdate))
        Endif
      Endif

    Next
  Endif
  xdate.Sort()
  datlist = xdate

  For Each xx In datlist
    $BillingReport.AddSection(modReportVar.GetDateTimeReport(xx, gb.MediumDate), True)
    res1 = modDatabase.$syConn.Exec("select fldbookingval,fldconsultdate,fldadmitlocat,fldid,fldptsex,fldptcontact,flduserid,fldcomment,fldbillingmode from tblpatientbook where fldadmitlocat like &1 and flduserid like &2 and fldbillingmode like &3 and fldstate=&4 and fldconsultdate>=&5 and fldconsultdate<=&6 and fldcomp like &7", sDept, xdoc, sBillMode, sStatus, modDate.StartSqlDate(xx), modDate.EndSqlDate(xx), sComp)                                                                            ''
    For Each res1
      With asx
        .Add(modReportVar.GetDateTimeReport(res1!fldconsultdate, gb.MediumTime))
        .Add(res1!fldbillingmode)
        .Add(res1!fldadmitlocat)
        If res1!flduserid Then
          .Add(modGeneral.GetUserFullName(res1!flduserid))
        Else
          .Add("")
        Endif
        .Add(res1!fldbookingval)
        .Add(modPatient.GetPatFullNameBooking(res1!fldbookingval))
        .Add(res1!fldptsex)
        .Add(res1!fldptcontact)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowRegisterConsultReport(dtfir As Date, dtlast As Date, sDept As String, sBillMode As String, sBilled As String, sStatus As String, sComp As String, Optional sUser As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result

  Dim xdate As Date[]
  Dim datlist As Date[]
  Dim xx As Date
  Dim xdoc As String

  If sUser Then
    xdoc = sUser
  Else
    xdoc = "%"
  Endif

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Mode"), ("Department"), ("Consultant"), ("EncID"), ("Name"), ("Age/Sex"), ("Contact")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("CONSULTATION REPORT", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(dtfir, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dtlast, gb.MediumDate), "PARAM2")

  If sBilled = "Billed" Then
    res = modDatabase.$syConn.Exec("select fldconsulttime from tblconsult where fldconsultname like &1 and flduserid like &2 and fldbillingmode like &3 and fldstatus=&4 and fldconsulttime>=&5 and fldconsulttime<=&6 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&7 and fldsave=&8) and fldcomp like &9", sDept, xdoc, sBillMode, sStatus, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "General Services", True, sComp)                                                                            ''
  Else
    res = modDatabase.$syConn.Exec("select fldconsulttime from tblconsult where fldconsultname like &1 and flduserid like &2 and fldbillingmode like &3 and fldstatus=&4 and fldconsulttime>=&5 and fldconsulttime<=&6 and fldcomp like &7", sDept, xdoc, sBillMode, sStatus, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sComp)                                                                            ''
  Endif
  xdate = New Date[]
  If res.Available Then
    For Each res

      If xdate.Count = 0 Then
        xdate.Add(modDate.StartSqlDate(res!fldconsulttime))
      Else
        If xdate.Exist(modDate.StartSqlDate(res!fldconsulttime)) = False Then
          xdate.Add(modDate.StartSqlDate(res!fldconsulttime))
        Endif
      Endif

    Next
  Endif
  xdate.Sort()
  datlist = xdate

  For Each xx In datlist
    $BillingReport.AddSection(modReportVar.GetDateTimeReport(xx, gb.MediumDate), True)
    If sBilled = "Billed" Then
      res1 = modDatabase.$syConn.Exec("select fldid,fldconsulttime,fldconsultname,fldencounterval,flduserid,fldbillingmode from tblconsult where fldconsultname like &1 and flduserid like &2 and fldbillingmode like &3 and fldstatus=&4 and fldconsulttime>=&5 and fldconsulttime<=&6 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&7 and fldsave=&8) and fldcomp like &9", sDept, xdoc, sBillMode, sStatus, modDate.StartSqlDate(xx), modDate.EndSqlDate(xx), "General Services", True, sComp)                                                                            ''
    Else
      res1 = modDatabase.$syConn.Exec("select fldid,fldconsulttime,fldconsultname,fldencounterval,flduserid,fldbillingmode from tblconsult where fldconsultname like &1 and flduserid like &2 and fldbillingmode like &3 and fldstatus=&4 and fldconsulttime>=&5 and fldconsulttime<=&6 and fldcomp like &7", sDept, xdoc, sBillMode, sStatus, modDate.StartSqlDate(xx), modDate.EndSqlDate(xx), sComp)                                                                            ''
    Endif
    For Each res1
      With asx
        .Add(modReportVar.GetDateTimeReport(res1!fldconsulttime, gb.MediumTime))
        .Add(res1!fldbillingmode)
        .Add(res1!fldconsultname)
        If res1!flduserid Then
          .Add(modGeneral.GetUserFullName(res1!flduserid))
        Else
          .Add("")
        Endif
        .Add(res1!fldencounterval)
        .Add(modPatient.GetPatientNameByEnc(res1!fldencounterval, modDatabase.$syConn))
        .Add(modPatient.GetPatientSex(res1!fldencounterval, modDatabase.$syConn))
        .Add(modPatient.GetPatientContactByEnc(res1!fldencounterval))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("Count")
      .Add("....")
      .Add("....")
      .Add("....")
      .Add(modReportVar.GetLocaleNumberFormat(res1.Count, 0))
      .Add("....")
      .Add("....")
      .Add("....")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    With asx
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
      .Add("****")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowRegisterConsultantwiseReport(dtfir As Date, dtlast As Date, sDept As String, sBillMode As String, sBilled As String, sComp As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result

  Dim xdate As Date[]
  Dim datlist As Date[]
  Dim xx As Date
  Dim xvalid As Integer
  Dim xcanx As Integer
  Dim totvalid As Integer
  Dim totcan As Integer

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Date"), ("Consultant"), ("Valid"), ("Cancelled")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("CONSULTATION REPORT", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(dtfir, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dtlast, gb.MediumDate) & " Mode: " & sBillMode & "     Department: " & sDept & "   Billing: " & sBilled, "PARAM2")

  If sBilled = "Billed" Then
    res1 = modDatabase.$syConn.Exec("select distinct(flduserid) as col from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&5 and fldsave=&6) and fldcomp like &7", sDept, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "General Services", True, sComp)
  Else
    res1 = modDatabase.$syConn.Exec("select distinct(flduserid) as col from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and fldcomp like &5", sDept, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sComp)
  Endif
  For Each res1
    If res1!col Then
      $BillingReport.AddSection(modGeneral.GetUserFullName(res1!col), True)

      totvalid = 0
      totcan = 0
      If sBilled = "Billed" Then
        res = modDatabase.$syConn.Exec("select fldconsulttime from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&6 and fldsave=&7) and fldcomp like &8", sDept, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), res1!col, "General Services", True, sComp)                                                                            ''
      Else
        res = modDatabase.$syConn.Exec("select fldconsulttime from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldcomp like &6", sDept, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), res1!col, sComp)                                                                            ''
      Endif
      xdate = New Date[]
      If res.Available Then
        For Each res

          If xdate.Count = 0 Then
            xdate.Add(modDate.StartSqlDate(res!fldconsulttime))
          Else
            If xdate.Exist(modDate.StartSqlDate(res!fldconsulttime)) = False
              xdate.Add(modDate.StartSqlDate(res!fldconsulttime))
            Endif
          Endif

        Next
      Endif
      xdate.Sort()
      datlist = xdate

      For Each xx In datlist

        xvalid = 0
        xcanx = 0
        If sBilled = "Billed" Then
          res2 = modDatabase.$syConn.Exec("select COUNT(fldid) as cnt from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldstatus<>&6 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&7 and fldsave=&8) and fldcomp like &9", sDept, sBillMode, modDate.StartSqlDate(xx), modDate.EndSqlDate(xx), res1!col, "Cancelled", "General Services", True, sComp)
        Else
          res2 = modDatabase.$syConn.Exec("select COUNT(fldid) as cnt from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldstatus<>&6 and fldcomp like &7", sDept, sBillMode, modDate.StartSqlDate(xx), modDate.EndSqlDate(xx), res1!col, "Cancelled", sComp)
        Endif
        If res2!cnt Then
          xvalid = xvalid + res2!cnt
        Endif
        If sBilled = "Billed" Then
          res3 = modDatabase.$syConn.Exec("select COUNT(fldid) as cnt from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldstatus=&6 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&7 and fldsave=&8) and fldcomp like &9", sDept, sBillMode, modDate.StartSqlDate(xx), modDate.EndSqlDate(xx), res1!col, "Cancelled", "General Services", True, sComp)
        Else
          res3 = modDatabase.$syConn.Exec("select COUNT(fldid) as cnt from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldstatus=&6 and fldcomp like &7", sDept, sBillMode, modDate.StartSqlDate(xx), modDate.EndSqlDate(xx), res1!col, "Cancelled", sComp)
        Endif
        If res3!cnt Then
          xcanx = xcanx + res3!cnt
        Endif
        totvalid = totvalid + xvalid
        totcan = totcan + xcanx
        With asx
          .Add(modReportVar.GetDateTimeReport(xx, gb.MediumDate))
          .Add(modGeneral.GetUserFullName(res1!col))
          .Add(modReportVar.GetLocaleNumberFormat(xvalid, 0))
          .Add(modReportVar.GetLocaleNumberFormat(xcanx, 0))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next

      With asx
        .Add("")
        .Add("")
        .Add(modReportVar.GetLocaleNumberFormat(totvalid, 0))
        .Add(modReportVar.GetLocaleNumberFormat(totcan, 0))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      With asx
        .Add("****")
        .Add("****")
        .Add("****")
        .Add("****")
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowRegisterConsultDeptReport(dtfir As Date, dtlast As Date, sDept As String, sBillMode As String, sBilled As String, sComp As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result

  Dim xvalid As Integer
  Dim xcanx As Integer
  Dim totvalid As Integer
  Dim totcan As Integer

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Department"), ("Consultant"), ("Valid"), ("Cancelled")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("CONSULTATION REPORT", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(dtfir, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dtlast, gb.MediumDate) & " Mode: " & sBillMode & "     Department: " & sDept & "   Billing: " & sBilled, "PARAM2")

  If sBilled = "Billed" Then
    res1 = modDatabase.$syConn.Exec("select distinct(flduserid) as col from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&5 and fldsave=&6) and fldcomp like &7", sDept, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), "General Services", True, sComp)
  Else
    res1 = modDatabase.$syConn.Exec("select distinct(flduserid) as col from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and fldcomp like &5", sDept, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), sComp)
  Endif
  For Each res1
    If res1!col Then
      $BillingReport.AddSection(modGeneral.GetUserFullName(res1!col), True)

      totvalid = 0
      totcan = 0
      If sBilled = "Billed" Then
        res = modDatabase.$syConn.Exec("select distinct(fldconsultname) as col from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&6 and fldsave=&7) and fldcomp like &8", sDept, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), res1!col, "General Services", True, sComp)                                                                            ''
      Else
        res = modDatabase.$syConn.Exec("select distinct(fldconsultname) as col from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldcomp like &6", sDept, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), res1!col, sComp)                                                                            ''
      Endif
      For Each res

        xvalid = 0
        xcanx = 0
        If sBilled = "Billed" Then
          res2 = modDatabase.$syConn.Exec("select COUNT(fldid) as cnt from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldstatus<>&6 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&7 and fldsave=&8) and fldcomp like &9", res!col, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), res1!col, "Cancelled", "General Services", True, sComp)
        Else
          res2 = modDatabase.$syConn.Exec("select COUNT(fldid) as cnt from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldstatus<>&6 and fldcomp like &7", res!col, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), res1!col, "Cancelled", sComp)
        Endif
        If res2!cnt Then
          xvalid = xvalid + res2!cnt
        Endif
        If sBilled = "Billed" Then
          res3 = modDatabase.$syConn.Exec("select COUNT(fldid) as cnt from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldstatus=&6 and fldencounterval in(select fldencounterval from tblpatbilling where flditemtype=&7 and fldsave=&8) and fldcomp like &9", res!col, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), res1!col, "Cancelled", "General Services", True, sComp)
        Else
          res3 = modDatabase.$syConn.Exec("select COUNT(fldid) as cnt from tblconsult where fldconsultname like &1 and fldbillingmode like &2 and fldconsulttime>=&3 and fldconsulttime<=&4 and flduserid=&5 and fldstatus=&6 and fldcomp like &7", res!col, sBillMode, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast), res1!col, "Cancelled", sComp)
        Endif
        If res3!cnt Then
          xcanx = xcanx + res3!cnt
        Endif
        totvalid = totvalid + xvalid
        totcan = totcan + xcanx
        With asx
          .Add(res!col)
          .Add(modGeneral.GetUserFullName(res1!col))
          .Add(modReportVar.GetLocaleNumberFormat(xvalid, 0))
          .Add(modReportVar.GetLocaleNumberFormat(xcanx, 0))
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next

      With asx
        .Add("")
        .Add("")
        .Add(modReportVar.GetLocaleNumberFormat(totvalid, 0))
        .Add(modReportVar.GetLocaleNumberFormat(totcan, 0))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      With asx
        .Add("****")
        .Add("****")
        .Add("****")
        .Add("****")
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Endif
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End
