' Gambas module file

Public Function ShowDocwiseConsultReport(sDate As Date, sBillMode As String, sUser As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res1 As Result

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Time"), ("Mode"), ("Department"), ("EncID"), ("Name"), ("Age/Sex"), ("Contact")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("CONSULATNAT: " & modGeneral.GetUserFullName(sUser) & "[" & sUser & "]", "PARAM1")
  $BillingReport.UserData.Add("Date: " & modReportVar.GetDateTimeReport(sDate, gb.MediumDate) & "  Mode: " & sBillMode, "PARAM2")

  res1 = modDatabase.$syConn.Exec("select fldid,fldconsulttime,fldconsultname,fldencounterval,flduserid,fldbillingmode from tblconsult where flduserid=&1 and fldbillingmode like &2 and fldstatus<>&3 and fldconsulttime>=&4 and fldconsulttime<=&5", sUser, sBillMode, "Cancelled", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate))                                                                            ''
  For Each res1
    With asx
      .Add(modReportVar.GetDateTimeReport(res1!fldconsulttime, gb.MediumTime))
      .Add(res1!fldbillingmode)
      .Add(res1!fldconsultname)
      .Add(res1!fldencounterval)
      .Add(modPatient.GetPatientNameByEnc(res1!fldencounterval, modDatabase.$syConn))
      .Add(modPatient.GetPatientSex(res1!fldencounterval, modDatabase.$syConn))
      .Add(modPatient.GetPatientContactByEnc(res1!fldencounterval))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowConsultQuota(sDate As Date, sDept As String, sBillMode As String, sComp As String, Optional sUserid As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim res1 As Result
  Dim res2 As Result

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Method"), ("Mode"), ("Department"), ("User Name"), ("Timimg"), ("Date"), ("Limit"), ("Booking"), ("Registered"), ("Comment")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("CONSULTANT TIMINGS", "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(sDate, gb.MediumDate) & Space(2) & modDate.GetWeekDay(sDate), "PARAM2")

  If sUserid Then
    res2 = modDatabase.$syConn.Exec("select fldid,fldmethod,fldbillingmode,flddept,flduserid,fldselect,flddate,fldquota,fldreason from tbldepconsult where flddate>=&1 and flddate<=&2 and flddept like &3 and fldselect=&4 and fldbillingmode like &5 and flduserid=&6 and fldcomp like &7", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, sUserid, sComp)             ''
  Else
    res2 = modDatabase.$syConn.Exec("select fldid,fldmethod,fldbillingmode,flddept,flduserid,fldselect,flddate,fldquota,fldreason from tbldepconsult where flddate>=&1 and flddate<=&2 and flddept like &3 and fldselect=&4 and fldbillingmode like &5 and fldcomp like &6", modDate.StartSqlDate(sDate), modDate.EndSqlDate(sDate), sDept, "Specific", sBillMode, sComp)
  Endif
  If res2.Available Then
    For Each res2
      With asx
        .Add(res2!fldmethod)
        .Add(res2!fldbillingmode)
        .Add(res2!flddept)
        .Add(modGeneral.GetUserFullName(res2!flduserid))
        .Add(res2!fldselect)
        .Add(modReportVar.GetDateTimeReport(res2!flddate, gb.MediumDate))
        .Add(res2!fldquota)
        If res2!flduserid Then
          .Add(modPatient.GetPatientBooked("Planned", res2!flddept, sDate, res2!fldbillingmode, res2!flduserid))
          .Add(modPatient.GetPatientRegisteredValid(res2!flddept, sDate, res2!fldbillingmode, res2!flduserid))
        Else
          .Add(modPatient.GetPatientBooked("Planned", res2!flddept, sDate, res2!fldbillingmode, ""))
          .Add(modPatient.GetPatientRegisteredValid(res2!flddept, sDate, res2!fldbillingmode, ""))
        Endif
        .Add(res2!fldreason)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Endif

  If sUserid Then
    res1 = modDatabase.$syConn.Exec("select fldid,fldmethod,fldbillingmode,flddept,flduserid,fldselect,flddate,fldquota,fldreason from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and flduserid=&4 and fldcomp like &5", sDept, modDate.GetWeekDay(sDate), sBillMode, sUserid, sComp)
  Else
    res1 = modDatabase.$syConn.Exec("select fldid,fldmethod,fldbillingmode,flddept,flduserid,fldselect,flddate,fldquota,fldreason from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4", sDept, modDate.GetWeekDay(sDate), sBillMode, sComp)
  Endif
  If res1.Available Then
    For Each res1
      With asx
        .Add(res1!fldmethod)
        .Add(res1!fldbillingmode)
        .Add(res1!flddept)
        .Add(modGeneral.GetUserFullName(res1!flduserid))
        .Add(res1!fldselect)
        .Add("")
        .Add(res1!fldquota)
        If res1!flduserid Then
          .Add(modPatient.GetPatientBooked("Planned", res1!flddept, sDate, res1!fldbillingmode, res1!flduserid))
          .Add(modPatient.GetPatientRegisteredValid(res1!flddept, sDate, res1!fldbillingmode, res1!flduserid))
        Else
          .Add(modPatient.GetPatientBooked("Planned", res1!flddept, sDate, res1!fldbillingmode, ""))
          .Add(modPatient.GetPatientRegisteredValid(res1!flddept, sDate, res1!fldbillingmode, ""))
        Endif
        .Add(res1!fldreason)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Endif

  If sUserid Then
    res = modDatabase.$syConn.Exec("select fldid,fldmethod,fldbillingmode,flddept,flduserid,fldselect,flddate,fldquota,fldreason from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and flduserid=&4 and fldcomp like &5", sDept, "AllDays", sBillMode, sUserid, sComp)
  Else
    res = modDatabase.$syConn.Exec("select fldid,fldmethod,fldbillingmode,flddept,flduserid,fldselect,flddate,fldquota,fldreason from tbldepconsult where flddept like &1 and fldselect=&2 and fldbillingmode like &3 and fldcomp like &4", sDept, "AllDays", sBillMode, sComp)
  Endif
  If res.Available Then
    For Each res
      With asx
        .Add(res!fldmethod)
        .Add(res!fldbillingmode)
        .Add(res!flddept)
        .Add(modGeneral.GetUserFullName(res!flduserid))
        .Add(res!fldselect)
        .Add("")
        .Add(res!fldquota)
        If res!flduserid Then
          .Add(modPatient.GetPatientBooked("Planned", res!flddept, sDate, res!fldbillingmode, res!flduserid))
          .Add(modPatient.GetPatientRegisteredValid(res!flddept, sDate, res!fldbillingmode, res!flduserid))
        Else
          .Add(modPatient.GetPatientBooked("Planned", res!flddept, sDate, res!fldbillingmode, ""))
          .Add(modPatient.GetPatientRegisteredValid(res!flddept, sDate, res!fldbillingmode, ""))
        Endif
        .Add(res!fldreason)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Endif

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowUserListHTML(sCategory As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim complist As String[]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("User Profile"), ("Photo"), ("Access"), ("Location")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("USER LIST", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select flduserid,fldusername,fldfromdate,fldtodate,fldcategory,fldcode from tbluser where fldcategory like &1", sCategory)                                                                                        ''
  If res.Available Then
    For Each res
      complist = modFillContainer.GetListFromResult(modDatabase.$syConn.Exec("select fldcomp as col from tblcompaccess where flduserid=&1", res!flduserid))
      complist.Sort()
      With asx
        .Add("<b>" & "UserID : " & "</b>" & res!flduserid & "<br>" & "<b>" & "Name : " & "</b>" & res!fldusername & "<br>" & "<b>" & "FROM: " & "</b>" & modReportVar.GetDateTimeReport(res!fldfromdate, gb.MediumDate) & "<br>" & "<b>" & "TO: " & "</b>" & modReportVar.GetDateTimeReport(res!fldtodate, gb.MediumDate))
        .Add(modString.GetImageForHTML(modImage.DisplayPersonImageData("Staff", CStr(res!fldcode))))
        .Add(modGeneral.GetUserAccessList(res!flduserid).Join("<br>"))
        .Add(complist.Join(", "))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowDBSettingsList(sMode As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim res1 As Result
  Dim xfld As String
  Dim xcateg As String

  Inc Application.Busy                                                                                     ''
  $BillingReport = New CReportHTML([("Category"), ("Value"), ("DateTime"), ("User")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("DB SETTINGS LIST", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  If sMode = "Location" Then
    xfld = "fldcomp"
    xcateg = "fldcategory"
  Else If sMode = "Setting" Then
    xfld = "fldcategory"
    xcateg = "fldcomp"
  Endif

  res1 = modDatabase.$syConn.Exec(Subst("select distinct(&1) as comp from tblsettings", xfld))
  If res1.Available Then
    For Each res1
      $BillingReport.AddSection(res1!comp, True)
      res = modDatabase.$syConn.Exec(Subst("select &1 as categ,fldvalue,fldtime,flduserid from tblsettings where &2", xcateg, xfld) & "=&1 ORDER BY fldcategory ASC", res1!comp)

      If res.Available Then
        For Each res
          With asx
            .Add(res!categ)
            .Add(res!fldvalue)
            .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate))
            .Add(res!flduserid)
          End With
          $BillingReport.Add(asx)
          asx.Clear()
        Next
      Endif

    Next
  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowSelectSetting(sSettings As String[]) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim xval As String

  $BillingReport = New CReportHTML([("Category"), ("Value"), ("DateTime"), ("User")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("DB SETTINGS LIST", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  Inc Application.Busy
  For Each xval In sSettings
    $BillingReport.AddSection(xval, True)
    res = modDatabase.$syConn.Exec("select fldcomp,fldvalue,fldtime,flduserid from tblsettings where fldcategory=&1 ORDER BY fldcomp", xval)

    If res.Available Then
      For Each res
        With asx
          .Add(res!fldcomp)
          .Add(res!fldvalue)
          .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate))
          .Add(res!flduserid)
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Next
    Endif

  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End
