' Gambas module file

Private $ProgressBar1 As ProgressBar

''---------------------------------------- STOCK RELATED --------------------------------------------------------------
Public Function ShowSupplierInnvoices(suppname As String, dtfir As Date, dtlast As Date) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim tax As Float
  Dim disc As Float
  Dim debit As Float
  Dim credit As Float

  $BillingReport = New CReportHTML([("Date"), ("Reference"), ("Bill No"), ("PayMode"), ("Discount"), ("TotalTax"), ("Debit"), ("Credit")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("PURCHASE INVOICES : " & suppname, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dtfir, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dtlast, gb.MediumDate), "PARAM2")

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldpurdate,fldbillno,fldpurtype,fldtotaltax,fldlastdisc,flddebit,fldcredit,fldreference from tblpurchasebill where fldsuppname=&1 and fldcategory=&2 and fldpurdate>=&3 and fldpurdate<=&4", suppname, "PurEntry", modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast))                                                   ''
  tax = 0
  disc = 0
  debit = 0
  credit = 0

  For Each res
    tax = tax + res!fldtotaltax
    disc = disc + res!fldlastdisc
    debit = debit + res!flddebit
    credit = credit + res!fldcredit
    With asx
      .Add(modReportVar.GetDateTimeReport(res!fldpurdate, gb.MediumDate))
      .Add(res!fldreference)
      .Add(res!fldbillno)
      .Add(res!fldpurtype)
      .Add(modReportVar.GetLocaleNumberFormat(res!fldlastdisc, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldtotaltax, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!flddebit, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldcredit, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  With asx
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add(modReportVar.GetLocaleNumberFormat(disc, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(tax, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(debit, gb.Currency))
    .Add(modReportVar.GetLocaleNumberFormat(credit, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowSupplierItemList(suppname As String, dtfir As Date, dtlast As Date) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  If MMain.$IsGUIApp = True Then
    $ProgressBar1 = modHelpVariable.FindWorkProgressBar(modHelpVariable.$LogInCategory)
    $ProgressBar1.Tag = "Const"
  Endif

  $BillingReport = New CReportHTML([("Date"), ("Category"), ("Particulars"), ("Batch/Expiry"), ("QTY"), ("MRP"), ("Cost"), ("Net"), ("PayMode"), ("Invoice")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("PURCHASE ITEMS : " & suppname, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dtfir, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dtlast, gb.MediumDate), "PARAM2")

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldtime,fldcategory,fldstockid,fldstockno,fldtotalqty,fldmrp,flsuppcost,fldnetcost,fldpurtype,fldbillno from tblpurchase where fldsuppname=&1 and fldpurdate>=&2 and fldpurdate<=&3 ORDER BY fldstockid ASC", suppname, modDate.StartSqlDate(dtfir), modDate.EndSqlDate(dtlast))                                                                                        ''
  For Each res
    With asx
      .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumDate))
      .Add(res!fldcategory)
      .Add(res!fldstockid)
      .Add(modStock.GetBatchFromStockNo(res!fldstockno) & " [" & modReportVar.GetDateTimeReport(modStock.GetExpiryFromStockNo(res!fldstockno), gb.MediumDate) & "]")
      .Add(modReportVar.GetLocaleNumberFormat(res!fldtotalqty, -2))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldmrp, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!flsuppcost, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldnetcost, gb.Currency))
      .Add(res!fldpurtype)
      .Add(res!fldbillno)
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    If MMain.$IsGUIApp = True Then
      $ProgressBar1.Value = (res.Index + 1) / res.Count
      Wait
    Endif
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowTotalInventory(sType As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]
  Dim subtot As Float
  Dim tot As Float
  Dim i As Integer

  Inc Application.Busy
  $BillingReport = New CReportHTML([("SNo"), ("Particulars"), ("Batch"), ("Expiry"), ("Order"), ("QTY"), ("Sell"), ("Amt")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("CURRENT INVENTORY : " & sType, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  tot = 0
  res1 = modDatabase.$syConn.Exec("select distinct(fldcomp) as fldcomp from tblentry where fldcategory=&1", sType)
  For Each res1
    $BillingReport.AddSection(res1!fldcomp, True)

    subtot = 0
    i = 1
    res = modDatabase.$syConn.Exec("select fldcomp,fldcategory,fldstockid,fldbatch,fldexpiry,fldstatus,fldqty,fldsellpr from tblentry where fldcomp=&1 and fldqty>&2 and fldcategory=&3 ORDER BY fldstockid ASC", res1!fldcomp, 0, sType)
    For Each res
      subtot = subtot + res!fldqty * res!fldsellpr
      With asx
        .Add(modReportVar.GetLocaleNumberFormat(i, 0))
        .Add(res!fldstockid)
        .Add(res!fldbatch)
        .Add(modReportVar.GetDateTimeReport(res!fldexpiry, gb.MediumDate))
        .Add(res!fldstatus)
        .Add(modReportVar.GetLocaleNumberFormat(res!fldqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(res!fldsellpr, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(res!fldqty * res!fldsellpr, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1
    Next
    tot = tot + subtot

    With asx
      .Add("..")
      .Add(res1!fldcomp)
      .Add("..")
      .Add("..")
      .Add("..")
      .Add("..")
      .Add("..")
      .Add(modReportVar.GetLocaleNumberFormat(subtot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Next

  With asx
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add("***")
    .Add(modReportVar.GetLocaleNumberFormat(tot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  Dec Application.Busy

  Return $BillingReport.NewHTMLPath()

End

Public Function PurchaseEntryReport(ReferenceNo As String, txtcategory As String, txtdisc As Float, txttax As Float) As String

  Dim $BillingReport As CReportHTML
  Dim sql1 As String
  Dim sql2 As String
  Dim rs As Result
  Dim res As Result
  Dim asx As New String[0]
  Dim tot As Float

  Inc Application.Busy
  sql1 = "select fldsuppname,fldpurtype,fldbillno,flddebit,fldcredit,fldtotaltax,fldlastdisc,fldpurdate,fldreference from tblpurchasebill where fldreference=&1 and fldcategory=&2"                           '''''''
  rs = modDatabase.$syConn.Exec(sql1, ReferenceNo, txtcategory)
  sql2 = "select fldid,fldpurtype,fldpurdate,fldbillno,fldsuppname,fldcategory,fldstockid,fldstockno,flsuppcost,fldtotalqty,fldnetcost,fldtotalcost from tblpurchase where fldreference=&1"                                                      ''
  res = modDatabase.$syConn.Exec(sql2, ReferenceNo)                                                                                       ''
  $BillingReport = New CReportHTML([("SNo"), ("Date"), ("Category"), ("Particulars"), ("Batch"), ("Expiry"), ("DistCost"), ("QTY"), ("NetCost"), ("Total")], modHelpVariable.$htmlDirectory, "PurchaseReport", "")

  $BillingReport.UserData.Add(rs!fldsuppname, "SupplierName")
  $BillingReport.UserData.Add(rs!fldpurtype, "PaymentType")
  $BillingReport.UserData.Add(rs!fldbillno, "InvoiceNumber")
  $BillingReport.UserData.Add(rs!fldreference, "ReferenceNo")

  tot = 0
  For Each res
    tot = tot + res!fldtotalcost
    With asx
      .Add(CStr(res.Index + 1))
      .Add(modReportVar.GetDateTimeReport(res!fldpurdate, gb.MediumDate))
      .Add(res!fldcategory)
      .Add(res!fldstockid)
      .Add(modStock.GetBatchFromStockNo(res!fldstockno))
      .Add(modReportVar.GetDateTimeReport(modStock.GetExpiryFromStockNo(res!fldstockno), gb.MediumDate))
      .Add(modReportVar.GetLocaleNumberFormat(res!flsuppcost, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldtotalqty, -2))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldnetcost, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldtotalcost, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("SubTotal")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(tot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("Extra Charge/Discount")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(0 - txtdisc, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("Tax")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(txttax, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()

  With asx
    .Add("")
    .Add("")
    .Add("")
    .Add("Grand Total")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add("")
    .Add(modReportVar.GetLocaleNumberFormat(modBillings.GetRoundupAccToSetting(tot + txttax - txtdisc), gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowTotalExpiry(dt As Date) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim tot As Float

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldcomp,fldcategory,fldstockid,fldbatch,fldexpiry,fldstatus,fldqty,fldsellpr from tblentry where fldexpiry<&1 and fldqty>&2 ORDER BY fldstockid ASC", dt, 0)                                                                                        ''
  $BillingReport = New CReportHTML([("Location"), ("Category"), ("Particulars"), ("Batch"), ("Expiry"), ("Order"), ("QTY"), ("Sell"), ("Amt")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("EXPIRY LIST", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(dt, gb.GeneralDate), "PARAM2")

  tot = 0
  For Each res
    tot = tot + res!fldqty * res!fldsellpr
    With asx
      .Add(res!fldcomp)
      .Add(res!fldcategory)
      .Add(res!fldstockid)
      .Add(res!fldbatch)
      .Add(modReportVar.GetDateTimeReport(res!fldexpiry, gb.MediumDate))
      .Add(res!fldstatus)
      .Add(modReportVar.GetLocaleNumberFormat(res!fldqty, -2))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldsellpr, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldqty * res!fldsellpr, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  With asx
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add(modReportVar.GetLocaleNumberFormat(tot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  Dec Application.Busy

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowUnderStockItemReport() As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res1 As Result
  Dim res2 As Result
  Dim res3 As Result
  Dim xval As Float

  $BillingReport = New CReportHTML([("Particulars"), ("Manufacturer"), ("Standard"), ("MinQTY"), ("CurrentQTY"), ("Comment")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("UNDER STOCK LIST", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  Inc Application.Busy
  $BillingReport.AddSection("Medicines")
  res1 = modDatabase.$syConn.Exec("select fldbrandid,fldmanufacturer,fldstandard,fldmaxqty,fldminqty,fldleadtime from tblmedbrand where fldactive=&1", "Active")
  If res1.Available Then
    For Each res1
      xval = modStock.TotalQTYbyBrand(res1!fldbrandid, "%")
      If xval < res1!fldminqty Then
        With asx
          .Add(res1!fldbrandid)
          .Add(res1!fldmanufacturer)
          .Add(res1!fldstandard)
          .Add(modReportVar.GetLocaleNumberFormat(res1!fldminqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xval, -2))
          .Add("")
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next
  Endif

  $BillingReport.AddSection("Surgicals")
  res2 = modDatabase.$syConn.Exec("select fldbrandid,fldmanufacturer,fldstandard,fldmaxqty,fldminqty,fldleadtime from tblsurgbrand where fldactive=&1", "Active")
  If res2.Available Then
    For Each res2
      xval = modStock.TotalQTYbyBrand(res2!fldbrandid, "%")
      If xval < res2!fldminqty Then
        With asx
          .Add(res2!fldbrandid)
          .Add(res2!fldmanufacturer)
          .Add(res2!fldstandard)
          .Add(modReportVar.GetLocaleNumberFormat(res2!fldminqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xval, -2))
          .Add("")
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next
  Endif

  $BillingReport.AddSection("Extra Items")
  res3 = modDatabase.$syConn.Exec("select fldbrandid,fldmanufacturer,fldstandard,fldmaxqty,fldminqty,fldleadtime from tblextrabrand where fldactive=&1", "Active")
  If res3.Available Then
    For Each res3
      xval = modStock.TotalQTYbyBrand(res3!fldbrandid, "%")
      If xval < res3!fldminqty Then
        With asx
          .Add(res3!fldbrandid)
          .Add(res3!fldmanufacturer)
          .Add(res3!fldstandard)
          .Add(modReportVar.GetLocaleNumberFormat(res3!fldminqty, -2))
          .Add(modReportVar.GetLocaleNumberFormat(xval, -2))
          .Add("")
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif
    Next
  Endif

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowStockReturnReport(refno As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim tot As Float

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldcomp,fldcategory,fldstockno,fldstockid,fldqty,fldcost,fldsuppname,fldreference from tblstockreturn where fldnewreference=&1 and fldsave=&2", refno, True)
  $BillingReport = New CReportHTML([("Location"), ("Category"), ("Reference"), ("Supplier"), ("Particulars"), ("Batch"), ("Expiry"), ("QTY"), ("Cost"), ("Amt")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("REFERENCE NO: " & refno, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.MediumDate), "PARAM2")

  tot = 0
  For Each res
    tot = tot + res!fldqty * res!fldcost
    With asx
      .Add(res!fldcomp)
      .Add(res!fldcategory)
      .Add(res!fldreference)
      .Add(res!fldsuppname)
      .Add(res!fldstockid)
      .Add(modStock.GetBatchFromStockNo(res!fldstockno))
      .Add(modReportVar.GetDateTimeReport(modStock.GetExpiryFromStockNo(res!fldstockno), gb.MediumDate))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldqty, -2))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldcost, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldqty * res!fldcost, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  With asx
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add(modReportVar.GetLocaleNumberFormat(tot, gb.Currency))
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowTotalPaymentSupplier(txtsupp As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]
  Dim tot As Float

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldid,fldtime,fldcategory,fldreference,fldpayamount,fldpaytype,fldpaidby,fldrecvby from tblpayment where fldsuppname=&1", txtsupp)                                                                                        ''
  $BillingReport = New CReportHTML([("No"), ("Date"), ("Category"), ("Reference"), ("AMT"), ("Mode"), ("Paid By"), ("Recv By")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("PAYMENT TO " & txtsupp, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  tot = 0
  For Each res
    tot = tot + res!fldpayamount
    With asx
      .Add(res!fldid)
      .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.MediumDate))
      .Add(res!fldcategory)
      .Add(res!fldreference)
      .Add(modReportVar.GetLocaleNumberFormat(res!fldpayamount, gb.Currency))
      .Add(res!fldpaytype)
      .Add(res!fldpaidby)
      .Add(res!fldrecvby)
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next

  With asx
    .Add("..")
    .Add("..")
    .Add("..")
    .Add("..")
    .Add(modReportVar.GetLocaleNumberFormat(tot, gb.Currency))
    .Add("..")
    .Add("..")
    .Add("..")
  End With
  $BillingReport.Add(asx)
  asx.Clear()
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowStockTransferReport(refno As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldid,fldtoentrytime,fldstockid,fldstockno,fldstockno,fldcategory,fldqty,fldnetcost,fldfromcomp,fldtocomp from tbltransfer where fldreference=&1 and fldtosav=&2", refno, True)
  $BillingReport = New CReportHTML([("ID"), ("Date"), ("Particulars"), ("Batch"), ("Expiry"), ("Category"), ("QTY"), ("Cost"), ("From"), ("To")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("REFERENCE NO: " & refno, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  For Each res
    With asx
      .Add(res!fldid)
      .Add(modReportVar.GetDateTimeReport(res!fldtoentrytime, gb.GeneralDate))
      .Add(res!fldstockid)
      .Add(modStock.GetBatchFromStockNo(res!fldstockno))
      .Add(modReportVar.GetDateTimeReport(modStock.GetExpiryFromStockNo(res!fldstockno), gb.MediumDate))
      .Add(res!fldcategory)
      .Add(modReportVar.GetLocaleNumberFormat(res!fldqty, -2))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldnetcost, gb.Currency))
      .Add(res!fldfromcomp)
      .Add(res!fldtocomp)
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowStockConsumeReport(refno As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldid,fldtime,fldtarget,fldcategory,fldstockid,fldstockno,fldstockno,fldqtydisp from tblbulksale where fldreference=&1 and fldsave=&2", refno, True)
  $BillingReport = New CReportHTML([("ID"), ("Date"), ("Target"), ("Category"), ("Particulars"), ("Batch"), ("Expiry"), ("QTY")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("REFERENCE NO: " & refno, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  For Each res
    With asx
      .Add(res!fldid)
      .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate))
      .Add(res!fldtarget)
      .Add(res!fldcategory)
      .Add(res!fldstockid)
      .Add(modStock.GetBatchFromStockNo(res!fldstockno))
      .Add(modReportVar.GetDateTimeReport(modStock.GetExpiryFromStockNo(res!fldstockno), gb.MediumDate))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldqtydisp, -2))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowStockAdjustmentReport(refno As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Inc Application.Busy
  res = modDatabase.$syConn.Exec("select fldid,fldtime,fldstockid,fldstockno,fldstockno,fldnetcost,fldcompqty,fldcurrqty,fldreason,fldcomp from tbladjustment where fldreference=&1", refno)
  $BillingReport = New CReportHTML([("ID"), ("Date"), ("Particulars"), ("Batch"), ("Expiry"), ("Cost"), ("Change"), ("Reason"), ("Comp")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("REFERENCE NO: " & refno, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  For Each res
    With asx
      .Add(res!fldid)
      .Add(modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate))
      .Add(res!fldstockid)
      .Add(modStock.GetBatchFromStockNo(res!fldstockno))
      .Add(modReportVar.GetDateTimeReport(modStock.GetExpiryFromStockNo(res!fldstockno), gb.MediumDate))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldnetcost, gb.Currency))
      .Add(modReportVar.GetLocaleNumberFormat(res!fldcompqty - res!fldcurrqty, -2))
      .Add(res!fldreason)
      .Add(res!fldcomp)
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function GetPurchaseSummaryReport(sType As String, dt1 As Date, dt2 As Date) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result
  Dim i As Integer
  Dim xtot As Float
  Dim stot As Float

  $BillingReport = New CReportHTML([("SNo"), ("Particulars"), ("QTY"), ("NetCost"), ("Total")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("PURCHASE SUMMARY : " & sType, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  Inc Application.Busy
  stot = 0
  res = modDatabase.$syConn.Exec("select distinct(fldsuppname) as suppl from tblpurchase where fldtime>=&1 and fldtime<=&2 and fldcategory=&3 and fldsav=&4", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, False)
  If res.Available Then
    For Each res

      $BillingReport.AddChapter(res!suppl)
      i = 1
      xtot = 0
      res1 = modDatabase.$syConn.Exec("select fldstockid,AVG(fldnetcost) as netcost,SUM(fldtotalqty-fldreturnqty) as qty,SUM((fldtotalqty-fldreturnqty)*fldnetcost) as totamt from tblpurchase where fldsuppname=&1 and fldtime>=&2 and fldtime<=&3 and fldcategory=&4 and fldsav=&5 GROUP BY fldstockid", res!suppl, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, False)
      If res1.Available Then

        For Each res1
          xtot = xtot + res1!totamt
          With asx
            .Add(modReportVar.GetLocaleNumberFormat(i, 0))
            .Add(res1!fldstockid)
            .Add(modReportVar.GetLocaleNumberFormat(res1!qty, -2))
            .Add(modReportVar.GetLocaleNumberFormat(res1!netcost, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(res1!totamt, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
          i = i + 1
        Next

        stot = stot + xtot
        With asx
          .Add("")
          .Add("****")
          .Add("")
          .Add("")
          .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()

        With asx
          .Add("")
          .Add("")
          .Add("")
          .Add("")
          .Add("")
        End With
        $BillingReport.Add(asx)
        asx.Clear()

      Endif

    Next

    With asx
      .Add("")
      .Add("****")
      .Add("")
      .Add("")
      .Add(modReportVar.GetLocaleNumberFormat(stot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Endif

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function GetConsumeSummaryReport(sType As String, dt1 As Date, dt2 As Date) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result
  Dim i As Integer
  Dim xtot As Float
  Dim stot As Float

  $BillingReport = New CReportHTML([("SNo"), ("Particulars"), ("QTY"), ("NetCost"), ("Total")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("CONSUME SUMMARY : " & sType, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  Inc Application.Busy
  stot = 0
  res = modDatabase.$syConn.Exec("select distinct(fldtarget) as suppl from tblbulksale where fldtime>=&1 and fldtime<=&2 and fldcategory=&3 and fldsave=&4", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True)
  If res.Available Then
    For Each res

      $BillingReport.AddChapter(res!suppl)
      i = 1
      xtot = 0
      res1 = modDatabase.$syConn.Exec("select fldstockid,AVG(fldnetcost) as netcost,SUM(fldqtydisp-fldqtyret) as qty,SUM(fldnetcost*(fldqtydisp-fldqtyret)) as totamt from tblbulksale where fldtarget=&1 and fldtime>=&2 and fldtime<=&3 and fldcategory=&4 and fldsave=&5 GROUP BY fldstockid", res!suppl, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), sType, True)
      If res1.Available Then

        For Each res1
          xtot = xtot + res1!totamt
          With asx
            .Add(modReportVar.GetLocaleNumberFormat(i, 0))
            .Add(res1!fldstockid)
            .Add(modReportVar.GetLocaleNumberFormat(res1!qty, -2))
            .Add(modReportVar.GetLocaleNumberFormat(res1!netcost, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(res1!totamt, gb.Currency))
          End With
          $BillingReport.Add(asx)
          asx.Clear()
          i = i + 1
        Next

        stot = stot + xtot
        With asx
          .Add("")
          .Add("****")
          .Add("")
          .Add("")
          .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
        End With
        $BillingReport.Add(asx)
        asx.Clear()

        With asx
          .Add("")
          .Add("")
          .Add("")
          .Add("")
          .Add("")
        End With
        $BillingReport.Add(asx)
        asx.Clear()

      Endif

    Next

    With asx
      .Add("")
      .Add("****")
      .Add("")
      .Add("")
      .Add(modReportVar.GetLocaleNumberFormat(stot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

  Endif

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function GetDispenseSummaryReport(sType As String, dt1 As Date, dt2 As Date) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res1 As Result
  Dim i As Integer
  Dim xtot As Float

  $BillingReport = New CReportHTML([("SNo"), ("Particulars"), ("QTY"), ("Rate"), ("Total")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("DISPENSE SUMMARY : " & sType, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")

  Inc Application.Busy
  i = 1
  xtot = 0
  res1 = modDatabase.$syConn.Exec("select flditemname,AVG(flditemrate) as netcost,SUM(flditemqty) as qty,SUM(fldditemamt) as totamt from tblpatbilling where flditemtype=&1 and fldtime>=&2 and fldtime<=&3 and fldsave=&4 GROUP BY flditemname", sType, modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2), True)
  If res1.Available Then
    For Each res1
      xtot = xtot + res1!totamt
      With asx
        .Add(modReportVar.GetLocaleNumberFormat(i, 0))
        .Add(res1!flditemname)
        .Add(modReportVar.GetLocaleNumberFormat(res1!qty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(res1!netcost, gb.Currency))
        .Add(modReportVar.GetLocaleNumberFormat(res1!totamt, gb.Currency))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
      i = i + 1
    Next

    With asx
      .Add("")
      .Add("****")
      .Add("")
      .Add("")
      .Add(modReportVar.GetLocaleNumberFormat(xtot, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''------------- Fixed Assets -----------------
Public Function FixedAssetsReport(sType As String, Optional sText As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result
  Dim i As Integer
  Dim xfld As String
  Dim yfld As String

  $BillingReport = New CReportHTML([("SNo"), ("Ledger"), ("Particulars"), ("Code"), ("Specs"), ("Mfg"), ("Model"), ("Serial"), ("PurDate"), ("Condition"), ("QTY"), ("Rate"), ("Total"), ("Remarks")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("FIXED ASSETS REPORT :" & sType, "PARAM1")
  $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(Now(), gb.MediumDate), "PARAM2")

  Inc Application.Busy
  If Not sText Then
    sText = "%"
  Endif
  If sType = "Category" Then
    xfld = "fldgroup"
    yfld = "fldcomp"
  Else If sType = "Location" Then
    xfld = "fldcomp"
    yfld = "fldgroup"
  Else If sType = "Invoice" Then
    xfld = "fldbillno"
    yfld = "fldgroup"
  Endif
  res = modDatabase.$syConn.Exec(Subst("select distinct(&1) as col from tblassetsentry", xfld))
  If res.Available Then
    For Each res
      $BillingReport.AddSection(res["col"])

      i = 1
      res1 = modDatabase.$syConn.Exec(Subst("select fldledger,fldcode,flditemname,fldspecs,fldmanufacturer,fldmodel,fldserial,fldpurdate,fldcondition,fldqty,fldunit,flditemrate,fldditemamt,&1 as col2 from tblassetsentry where &2", yfld, xfld) & "=&1", res["col"])
      If res1.Available Then
        For Each res1
          With asx
            .Add(modReportVar.GetLocaleNumberFormat(i, 0))
            .Add(res1!fldledger)
            .Add(res1!flditemname)
            .Add(res1!fldcode)
            .Add(res1!fldspecs)
            .Add(res1!fldmanufacturer)
            .Add(res1!fldmodel)
            .Add(res1!fldserial)
            .Add(modReportVar.GetDateTimeReport(res1!fldpurdate, gb.MediumDate))
            .Add(res1!fldcondition)
            .Add(modReportVar.GetLocaleNumberFormat(res1!fldqty, -2) & Space(1) & res1!fldunit)
            .Add(modReportVar.GetLocaleNumberFormat(res1!flditemrate, gb.Currency))
            .Add(modReportVar.GetLocaleNumberFormat(res1!fldditemamt, gb.Currency))
            .Add(res1!col2)
          End With
          $BillingReport.Add(asx)
          asx.Clear()
          i = i + 1
        Next
        With asx
          .Add("")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
          .Add("****")
        End With
        $BillingReport.Add(asx)
        asx.Clear()
      Endif

    Next
  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''-------------------- Inpatient Returns --------------------------
Public Function PatientMedicationForReturn(dt1 As Date, dt2 As Date) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim res As Result
  Dim res1 As Result
  Dim rsx As Result

  Dim regimen As String
  Dim xdose As Float
  Dim xpck As Float
  Dim xretqty As Float
  Dim i As Integer

  $BillingReport = New CReportHTML([("SNo"), ("Particulars"), ("Regimen"), ("Status"), ("DispQTY"), ("AdminQTY"), ("UnusedQTY")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("UNUSED MEDICATION", "Report")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM1")

  Inc Application.Busy
  rsx = modDatabase.$syConn.Exec("select fldencounterval,fldcurrlocat from tblencounter where flddod>=&1 and flddod<=&2", modDate.StartSqlDate(dt1), modDate.EndSqlDate(dt2))
  If rsx.Available Then
    For Each rsx

      res = modDatabase.$syConn.Exec("select fldid,fldroute,flditem,flddose,fldfreq,flddays,fldqtydisp,fldqtyret,fldcurval from tblpatdosing where fldencounterval=&1 and fldsave_order=&2 and flditemtype=&3 ORDER BY flditem", rsx["fldencounterval"], True, "Medicines")
      If res.Available Then
        $BillingReport.AddChapter(modPatient.GetPatientNameByEnc(rsx["fldencounterval"], modDatabase.$syConn) & " EncID: " & rsx["fldencounterval"] & " [" & rsx["fldcurrlocat"] & "]")
        i = 1
        For Each res
          If res["fldroute"] = "fluid" Then
            regimen = res["fldroute"] & Space(2) & res["flddose"] & " mL X " & res["fldfreq"] & " X " & res["flddays"]
          Else
            regimen = res["fldroute"] & Space(2) & res["flddose"] & " mg X " & res["fldfreq"] & " X " & res["flddays"]
          Endif
          res1 = modDatabase.$syConn.Exec("select SUM(fldvalue) as col from tblnurdosing where fldencounterval=&1 and flddoseno=&2", rsx["fldencounterval"], res["fldid"])
          xdose = 0
          If res1.Available Then
            xpck = modPharmLabel.GetPackVolValue(res["flditem"])
            If res1["col"] And If xpck Then
              xdose = Round(res1["col"] / xpck, -2)
            Endif
          Endif
          xretqty = res["fldqtydisp"] - res["fldqtyret"] - xdose
          If xretqty Then
            With asx
              .Add(CStr(i))
              .Add(res["flditem"])
              .Add(regimen)
              .Add(res["fldcurval"])
              .Add(res["fldqtydisp"] - res["fldqtyret"])
              .Add(xdose)
              .Add(xretqty)
            End With
            $BillingReport.Add(asx)
            asx.Clear()
            i = i + 1
          Endif
        Next
      Endif

    Next
  Endif
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End
