' Gambas module file

''------------------------------------- variables ---------------------------------------

Public Sub AgeGroupGeneralList() As String[]

  Dim xxx As String[]

  xxx = New String[]

  xxx.Add("Neonate;0;30")
  xxx.Add("Infant;30;365")
  xxx.Add("Toddler;365;730")
  xxx.Add("Children;730;4380")
  xxx.Add("Adolescent;4380;7300")
  xxx.Add("Adult;7300;21900")
  xxx.Add("Elderly;21900;43800")

  Return xxx

End

Public Sub AgeGroupNameList() As String[]

  Dim hFile As File
  Dim sline As String
  Dim agegrp As String[]
  Dim xxx As String[]

  xxx = New String[]
  If Exist(modHelpVariable.AppDirectory &/ "agegrouping") Then
    hFile = Open modHelpVariable.AppDirectory &/ "agegrouping"
    modBasic.DebugString("Open File " & modHelpVariable.AppDirectory &/ "agegrouping")
    For Each sline In hFile.Lines
      If Len(sline) Then
        agegrp = Split(sline, ";")
        xxx.Add(agegrp[0])
      Endif
    Next
    hFile.Close()

  Else
    xxx.Add("Neonate")
    xxx.Add("Infant")
    xxx.Add("Toddler")
    xxx.Add("Children")
    xxx.Add("Adolescent")
    xxx.Add("Adult")
    xxx.Add("Elderly")
  Endif

  Return xxx

End

Public Sub AgeGroupGenderList() As String[]

  Dim xxx As String[]

  xxx = New String[]

  xxx.Add("Neonate" & ":Male")
  xxx.Add("Neonate" & ":Female")
  xxx.Add("Infant" & ":Male")
  xxx.Add("Infant" & ":Female")
  xxx.Add("Toddler" & ":Male")
  xxx.Add("Toddler" & ":Female")
  xxx.Add("Children" & ":Male")
  xxx.Add("Children" & ":Female")
  xxx.Add("Adolescent" & ":Male")
  xxx.Add("Adolescent" & ":Female")
  xxx.Add("Adult" & ":Male")
  xxx.Add("Adult" & ":Female")
  xxx.Add("Elderly" & ":Male")
  xxx.Add("Elderly" & ":Female")

  Return xxx

End

Public Function GetAgeValuefromgroup(agegroup As String) As String

  Dim xx As String

  If agegroup = "Neonate" Then
    xx = "0" & ";" & "30"
  Else If agegroup = "Infant" Then
    xx = "30" & ";" & "365"
  Else If agegroup = "Toddler" Then
    xx = "365" & ";" & "730"
  Else If agegroup = "Children" Then
    xx = "730" & ";" & "4380"
  Else If agegroup = "Adolescent" Then
    xx = "4380" & ";" & "7300"
  Else If agegroup = "Adult" Then
    xx = "7300" & ";" & "21900"
  Else If agegroup = "Elderly" Then
    xx = "21900" & ";" & "43800"
  Endif

  Return xx

End

Public Function GetAgeStringByTable(sTable As String, $con As Connection) As String

  Dim dbType As String
  Dim xdtstr As String

  dbType = $con.Type

  If sTable = "tblpatfindings" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpatfindings.fldtime, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpatfindings.fldtime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpatfindings.fldtime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpatlabtest" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpatlabtest.fldtime_sample,tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpatlabtest.fldtime_sample - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpatlabtest.fldtime_sample) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpatradiotest" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpatradiotest.fldtime_report, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpatradiotest.fldtime_report - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpatradiotest.fldtime_report) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpatientexam" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpatientexam.fldtime, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpatientexam.fldtime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpatientexam.fldtime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpatdosing" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpatdosing.fldtime, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpatdosing.fldtime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpatdosing.fldtime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpatsubgeneral" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpatsubgeneral.fldtime,tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpatsubgeneral.fldtime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpatsubgeneral.fldtime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpatgeneral" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpatgeneral.fldtime,tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpatgeneral.fldtime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpatgeneral.fldtime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblexamgeneral" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblexamgeneral.fldtime,tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblexamgeneral.fldtime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblexamgeneral.fldtime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpataccgeneral" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpataccgeneral.fldtime,tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpataccgeneral.fldtime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpataccgeneral.fldtime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpattiming" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpattiming.fldfirsttime, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpattiming.fldfirsttime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpattiming.fldfirsttime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblencounter" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblencounter.fldregdate, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblencounter.fldregdate - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblencounter.fldregdate) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblconsult" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblconsult.fldconsulttime, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblconsult.fldconsulttime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblconsult.fldconsulttime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblconfinement" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblconfinement.flddeltime, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblconfinement.flddeltime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblconfinement.flddeltime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Else If sTable = "tblpatientdate" Then
    If dbType = "mysql" Then
      xdtstr = "DATEDIFF(tblpatientdate.fldtime, tblpatientinfo.fldptbirday)"
    Else If dbType = "postgresql" Then
      xdtstr = "DATE_PART('day',tblpatientdate.fldtime - tblpatientinfo.fldptbirday)"
    Else If dbType = "sqlite3" Then
      xdtstr = "(julianday(tblpatientdate.fldtime) - julianday(tblpatientinfo.fldptbirday))"
    Endif

  Endif
  Return xdtstr

End
