' Gambas module file

Public Function ShowFoodGroupListHTML() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim res2 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Particulars"), ("Type"), ("Source"), ("Amount<br>(gm)")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("REPORT GROUPS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroup) from tblfoodgroup ORDER BY fldgroup ASC")                                                                                        ''
  For Each res
    $BillingReport.AddSection(res!fldgroup, True)

    res1 = modDatabase.$syConn.Exec("select fldid,flditemname,flditemamt from tblfoodgroup where fldgroup=&1 ORDER BY flditemname ASC", res!fldgroup)
    For Each res1
      res2 = modDatabase.$syConn.Exec("select fldfood,fldsource,fldformat from tblfoodcontent where fldfoodid=&1", res1!flditemname)
      With asx
        .Add(res2!fldfood)
        .Add(res2!fldformat)
        .Add(res2!fldsource)
        .Add(res1!flditemamt)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End
