' Gambas module file

'NOTE: ----------------------------- Medical Report --------------------------------------------
Public Function AddCustomReport(stChapter As String, stObservation As String) As String[]

  Dim asx As New String[0]

  With asx
    If modBasic.$MedRepoBody = "Paragraph" Then
      .Add("<b>" & stChapter & "</b><br>" & modString.TextToHTML(stObservation))
    Else
      .Add(stChapter)
      .Add(modString.TextToHTML(stObservation))
    Endif
  End With
  Return asx

End

Public Function AddCustomParam(sParam As String) As String[]

  Dim asx As New String[0]
  Dim xx As String

  Dim stChapter As String
  Dim stObservation As String

  xx = GetRichTextArea(sParam, "")

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & sParam & "</b><br>" & xx)
  '   Else
  '     .Add(sParam)
  '     .Add(xx)
  '   Endif
  ' End With

  stChapter = sParam
  stObservation = xx
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddCourseOfTreatment(encid As String) As String[]

  Dim asx As New String[0]
  Dim res As Result
  Dim xx As String
  Dim xcom As String
  Dim folDate As Date

  Dim stChapter As String
  Dim stObservation As String

  res = modDatabase.$syConn.Exec("select fldhead,fldtime,fldcomment from tblpatientdate where fldencounterval=&1", encid)
  xx = ""
  If res.Available Then
    For Each res
      xcom = ""
      If res!fldcomment Then
        xcom = " (" & res!fldcomment & ")"
      Endif
      xx = xx & " Date: " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & "::" & res!fldhead & xcom & gb.NewLine
    Next
  Endif

  folDate = modPatient.GetFollowUpDate(encid)
  If folDate Then
    xx = xx & "Follow-up: " & modReportVar.GetDateTimeReport(folDate, gb.GeneralDate)
  Endif

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Course of Treatment" & "</b><br>" & modString.TextToHTML(xx))
  '   Else
  '     .Add("Course of Treatment")
  '     .Add(modString.TextToHTML(xx))
  '   Endif '
  ' End With

  stChapter = "Course of Treatment"
  stObservation = xx
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddPresentingComplaints(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Presenting Complaints" & "</b><br>" & modString.TextToHTML(GetPatientPresentingSymptomReport(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Presenting Complaints")
  '     .Add(modString.TextToHTML(GetPatientPresentingSymptomReport(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Presenting Complaints"
  stObservation = GetPatientPresentingSymptomReport(encid).Join(gb.NewLine)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddOPDFindings(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "OPD Examinations" & "</b><br>" & modString.TextToHTML(GetSelectFindingReport(encid, "OPD Examination").Join(gb.NewLine)))
  '   Else
  '     .Add("OPD Examinations")
  '     .Add(modString.TextToHTML(GetSelectFindingReport(encid, "OPD Examination").Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "OPD Examinations"
  stObservation = GetSelectFindingReport(encid, "OPD Examination").Join(gb.NewLine)
  asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddTriageFindings(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Triage Examinations" & "</b><br>" & modString.TextToHTML(GetSelectFindingReport(encid, "Triage Examinations").Join(gb.NewLine)))
  '   Else
  '     .Add("Triage Examinations")
  '     .Add(modString.TextToHTML(GetSelectFindingReport(encid, "Triage Examinations").Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Triage Examinations"
    stObservation = GetSelectFindingReport(encid, "Triage Examinations").Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddDischargeFindings(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Discharge Examinations" & "</b><br>" & modString.TextToHTML(GetSelectFindingReport(encid, "Discharge Examinations").Join(gb.NewLine)))
  '   Else
  '     .Add("Discharge Examinations")
  '     .Add(modString.TextToHTML(GetSelectFindingReport(encid, "Discharge Examinations").Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Discharge Examinations"
    stObservation = GetSelectFindingReport(encid, "Discharge Examinations").Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddGenComplaints(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "General Complaints" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "General Complaints")))
  '   Else
  '     .Add("General Complaints")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "General Complaints")))
  '   Endif
  ' End With

  stChapter = "General Complaints"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "General Complaints")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddCauseofAdmission(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Cause of Admission" & "</b><br>" & modPatientGeneral.ShowSelectedHistory(encid, "Cause of Admission"))
  '   Else
  '     .Add("Cause of Admission")
  '     .Add(modPatientGeneral.ShowSelectedHistory(encid, "Cause of Admission"))
  '   Endif
  ' End With

  stChapter = "Cause of Admission"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Cause of Admission")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddHistoryOfIllness(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "History of Illness" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "History of Illness")))
  '   Else
  '     .Add("History of Illness")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "History of Illness")))
  '   Endif
  ' End With

  stChapter = "History of Illness"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "History of Illness")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddPastHistory(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Past History" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Past History")))
  '   Else
  '     .Add("Past History")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Past History")))
  '   Endif
  ' End With

  stChapter = "Past History"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Past History")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddTreatmentHistory(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Treatment History" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Treatment History")))
  '   Else
  '     .Add("Treatment History")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Treatment History")))
  '   Endif
  ' End With

  stChapter = "Treatment History"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Treatment History")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddMedicatHistory(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Medication History" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Medication History")))
  '   Else
  '     .Add("Medication History")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Medication History")))
  '   Endif
  ' End With

  stChapter = "Medication History"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Medication History")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddPersonalHistory(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Personal History" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Personal History")))
  '   Else
  '     .Add("Personal History")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Personal History")))
  '   Endif
  ' End With

  stChapter = "Personal History"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Personal History")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddSurgicalHistory(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Surgical History" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Surgical History")))
  '   Else
  '     .Add("Surgical History")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Surgical History")))
  '   Endif
  ' End With

  stChapter = "Surgical History"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Surgical History")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddOccupationalHistory(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Occupational History" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Occupational History")))
  '   Else
  '     .Add("Occupational History")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Occupational History")))
  '   Endif
  ' End With

  stChapter = "Occupational History"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Occupational History")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddSocialHistory(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Social History" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Social History")))
  '   Else
  '     .Add("Social History")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Social History")))
  '   Endif
  ' End With

  stChapter = "Social History"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Social History")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddFamilyHistory(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Family History" & "</b><br>" & modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Family History")))
  '   Else
  '     .Add("Family History")
  '     .Add(modString.TextToHTML(modPatientGeneral.ShowSelectedHistory(encid, "Family History")))
  '   Endif
  ' End With

  stChapter = "Family History"
    stObservation = modPatientGeneral.ShowSelectedHistory(encid, "Family History")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddProvisionalDiagnosis(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Provisional Diagnosis" & "</b><br>" & modString.TextToHTML(modPatient.PatientFindingList(encid, "Provisional Diagnosis").Join(gb.newline)))
  '   Else
  '     .Add("Provisional Diagnosis")
  '     .Add(modString.TextToHTML(modPatient.PatientFindingList(encid, "Provisional Diagnosis").Join(gb.newline)))
  '   Endif
  ' End With

  stChapter = "Provisional Diagnosis"
    stObservation = modPatient.PatientFindingList(encid, "Provisional Diagnosis").Join(gb.newline)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddFinalDiagnosis(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Final Diagnosis" & "</b><br>" & modString.TextToHTML(modPatient.PatientFindingList(encid, "Final Diagnosis").Join(gb.newline)))
  '   Else
  '     .Add("Final Diagnosis")
  '     .Add(modString.TextToHTML(modPatient.PatientFindingList(encid, "Final Diagnosis").Join(gb.newline)))
  '   Endif
  ' End With

  stChapter = "Final Diagnosis"
    stObservation = modPatient.PatientFindingList(encid, "Final Diagnosis").Join(gb.newline)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddClinicalFindingsNonVital(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Clinical Findings" & "</b><br>" & modString.TextToHTML(GetNonVitalClinicalFinding(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Clinical Findings")
  '     .Add(modString.TextToHTML(GetNonVitalClinicalFinding(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Clinical Findings"
    stObservation = GetNonVitalClinicalFinding(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddClinicalFindingsVital(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Essential Examinations" & "</b><br>" & modString.TextToHTML(GetVitalClinicalFinding(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Essential Examinations")
  '     .Add(modString.TextToHTML(GetVitalClinicalFinding(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Essential Examinations"
    stObservation = GetVitalClinicalFinding(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddClinicalFindingsStructured(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Structured Examinations" & "</b><br>" & modString.TextToHTML(GetRecommendedExam(encid)))
  '   Else
  '     .Add("Structured Examinations")
  '     .Add(modString.TextToHTML(GetRecommendedExam(encid)))
  '   Endif
  ' End With

  stChapter = "Structured Examinations"
    stObservation = GetRecommendedExam(encid)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddInvestigationAdvised(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Investigation Advised" & "</b><br>" & modString.TextToHTML(WardOrderLabRequest(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Investigation Advised")
  '     .Add(modString.TextToHTML(WardOrderLabRequest(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Investigation Advised"
    stObservation = WardOrderLabRequest(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddTreatmentAdvised(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Treatment Advised" & "</b><br>" & modString.TextToHTML(OPDMedString(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Treatment Advised")
  '     .Add(modString.TextToHTML(OPDMedString(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Treatment Advised"
    stObservation = OPDMedString(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddConsultationAll(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Consultations" & "</b><br>" & modString.TextToHTML(modPatient.GetPatientCOnsultList(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Consultations")
  '     .Add(modString.TextToHTML(modPatient.GetPatientCOnsultList(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Consultations"
    stObservation = modPatient.GetPatientCOnsultList(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddBedTransition(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Bed Transitions" & "</b><br>" & modString.TextToHTML(modPatientGeneral.GetPatientTransition(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Bed Transitions")
  '     .Add(modString.TextToHTML(modPatientGeneral.GetPatientTransition(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Bed Transitions"
    stObservation = modPatientGeneral.GetPatientTransition(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddEquipmentsUsed(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Equipments Used" & "</b><br>" & modString.TextToHTML(modPatientGeneral.GetPatientEquipmentUse(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Equipments Used")
  '     .Add(modString.TextToHTML(modPatientGeneral.GetPatientEquipmentUse(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Equipments Used"
    stObservation = modPatientGeneral.GetPatientEquipmentUse(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddDrugAllergy(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Drug Allergy" & "</b><br>" & modString.TextToHTML(modPatient.PatientFindingList(encid, "Allergic Drugs").Join(gb.NewLine)))
  '   Else
  '     .Add("Drug Allergy")
  '     .Add(modString.TextToHTML(modPatient.PatientFindingList(encid, "Allergic Drugs").Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Drug Allergy"
    stObservation = modPatient.PatientFindingList(encid, "Allergic Drugs").Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddProminientSymptoms(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Prominent Symptoms" & "</b><br>" & modString.TextToHTML(GetPatientSymptomReport(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Prominent Symptoms")
  '     .Add(modString.TextToHTML(GetPatientSymptomReport(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Prominent Symptoms"
    stObservation = GetPatientSymptomReport(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddPatDemographics(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Demographics" & "</b><br>" & modString.TextToHTML(GetPatientDemographicReport(encid).Join(gb.NewLine)))
  '   Else
  '     .Add("Demographics")
  '     .Add(modString.TextToHTML(GetPatientDemographicReport(encid).Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Demographics"
    stObservation = GetPatientDemographicReport(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddMajorProcedures(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Major Procedures" & "</b><br>" & modString.TextToHTML(modPatientGeneral.PatSelectProcedureString(encid, "Procedures", "Done")))
  '   Else
  '     .Add("Major Procedures")
  '     .Add(modString.TextToHTML(modPatientGeneral.PatSelectProcedureString(encid, "Procedures", "Done")))
  '   Endif
  ' End With

  stChapter = "Major Procedures"
    stObservation = modPatientGeneral.PatSelectProcedureString(encid, "Procedures", "Done")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddPlannedProcedures(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Planned Procedures" & "</b><br>" & modString.TextToHTML(GetPatProcedureList(encid, "Procedures", "Planned").Join(gb.NewLine)))
  '   Else
  '     .Add("Planned Procedures")
  '     .Add(modString.TextToHTML(GetPatProcedureList(encid, "Procedures", "Planned").Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Planned Procedures"
    stObservation = GetPatProcedureList(encid, "Procedures", "Planned").Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddMinorProcedures(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Minor Procedures" & "</b><br>" & modString.TextToHTML(GetPatProcedureList(encid, "Minor Procedures", "Done").Join(gb.NewLine)))
  '   Else
  '     .Add("Minor Procedures")
  '     .Add(modString.TextToHTML(GetPatProcedureList(encid, "Minor Procedures", "Done").Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Minor Procedures"
    stObservation = GetPatProcedureList(encid, "Minor Procedures", "Done").Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddExtraProcedures(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Extra Procedures" & "</b><br>" & modString.TextToHTML(GetPatExtProcedureList(encid, "Planned").Join(gb.NewLine)))
  '   Else
  '     .Add("Extra Procedures")
  '     .Add(modString.TextToHTML(GetPatExtProcedureList(encid, "Planned").Join(gb.NewLine)))
  '   Endif
  ' End With

  stChapter = "Extra Procedures"
    stObservation = GetPatExtProcedureList(encid, "Planned").Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddMedicationUsed(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Medication Used" & "</b><br>" & modString.TextToHTML(modPharmacy.NurDosingString(encid)))
  '   Else
  '     .Add("Medication Used")
  '     .Add(modString.TextToHTML(modPharmacy.NurDosingString(encid)))
  '   Endif
  ' End With

  stChapter = "Medication Used"
    stObservation = modPharmacy.NurDosingString(encid)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddConditionAtDischarge(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Condition at Discharge" & "</b><br>" & modString.TextToHTML(GetPatientNoteReport(encid, "Condition of Discharge")))
  '   Else
  '     .Add("Condition at Discharge")
  '     .Add(modString.TextToHTML(GetPatientNoteReport(encid, "Condition of Discharge")))
  '   Endif
  ' End With

  stChapter = "Condition at Discharge"
    stObservation = GetPatientNoteReport(encid, "Condition of Discharge")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddDischargeMedication(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Discharge Medication" & "</b><br>" & modString.TextToHTML(modPharmacy.DischargeMedString(encid)))
  '   Else
  '     .Add("Discharge Medication")
  '     .Add(modString.TextToHTML(modPharmacy.DischargeMedString(encid)))
  '   Endif
  ' End With

  stChapter = "Discharge Medication"
    stObservation = modPharmacy.DischargeMedString(encid)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddAdviceDischarge(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Advice on Discharge" & "</b><br>" & modString.TextToHTML(GetPatientNoteReport(encid, "Advice on Discharge")))
  '   Else
  '     .Add("Advice on Discharge")
  '     .Add(modString.TextToHTML(GetPatientNoteReport(encid, "Advice on Discharge")))
  '   Endif
  ' End With

  stChapter = "Advice on Discharge"
    stObservation = GetPatientNoteReport(encid, "Advice on Discharge")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

''opd
Public Function AddOPDAdvice(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Initial Planning" & "</b><br>" & modString.TextToHTML(GetPatientNoteReport(encid, "Initial Planning")))
  '   Else
  '     .Add("Initial Planning")
  '     .Add(modString.TextToHTML(GetPatientNoteReport(encid, "Initial Planning")))
  '   Endif
  ' End With

  stChapter = "Initial Planning"
    stObservation = GetPatientNoteReport(encid, "Initial Planning")
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddDeliveryProfile(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Delivery Profile" & "</b><br>" & DeliveryReportbyMother(encid).Join(gb.NewLine))
  '   Else
  '     .Add("Delivery Profile")
  '     .Add(DeliveryReportbyMother(encid).Join(gb.NewLine))
  '   Endif
  ' End With

  stChapter = "Delivery Profile"
    stObservation = DeliveryReportbyMother(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddClinicalNotes(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Clinical Notes" & "</b><br>" & GetClinNotesReport(encid).Join(gb.NewLine))
  '   Else
  '     .Add("Clinical Notes")
  '     .Add(GetClinNotesReport(encid).Join(gb.NewLine))
  '   Endif
  ' End With

  stChapter = "Clinical Notes"
    stObservation = GetClinNotesReport(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddTherapeuticPlanning(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Therapeutic Planning" & "</b><br>" & GetPatientPlanningReport(encid).Join(gb.NewLine))
  '   Else
  '     .Add("Therapeutic Planning")
  '     .Add(GetPatientPlanningReport(encid).Join(gb.NewLine))
  '   Endif
  ' End With

  stChapter = "Therapeutic Planning"
    stObservation = GetPatientPlanningReport(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddIPMonitoring(encid As String) As String[]

  Dim asx As New String[0]

  Dim stChapter As String
  Dim stObservation As String

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "IP Monitoring" & "</b><br>" & GetPatientMonitorReport(encid).Join(gb.NewLine))
  '   Else
  '     .Add("IP Monitoring")
  '     .Add(GetPatientMonitorReport(encid).Join(gb.NewLine))
  '   Endif
  ' End With

  stChapter = "IP Monitoring"
    stObservation = GetPatientMonitorReport(encid).Join(gb.NewLine)
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddSelectedExamination(encid As String, exam As String[]) As String[]

  Dim asx As New String[0]
  Dim xx As String
  Dim yy As String
  Dim sType As String

  Dim stChapter As String
  Dim stObservation As String

  yy = ""
  For Each xx In exam
    sType = modFixClinic.GetExaminationType(xx)
    If sType = "Quantitative" Then
      yy = yy & modString.TextToHTML(GetQuantiExaminationForReport(encid, xx) & gb.NewLine & "<br>")
    Else If sType = "Qualitative" Then
      yy = yy & modString.TextToHTML(GetQualiExaminationForReport(encid, xx) & gb.NewLine & "<br>")
    Endif
  Next

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Examinations" & "</b><br>" & yy)
  '   Else
  '     .Add("Examinations")
  '     .Add(yy)
  '   Endif
  ' End With

  stChapter = "Examinations"
    stObservation = yy
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddSelectedTest(encid As String, test As String[], sUnit As String) As String[]

  Dim asx As New String[0]
  Dim xx As String
  Dim yy As String
  Dim sType As String

  Dim stChapter As String
  Dim stObservation As String

  yy = ""
  For Each xx In test
    sType = modFixLab.GetLabTestType(xx)
    If sType = "Quantitative" Then
      yy = yy & modString.TextToHTML(GetQuantiLaboratoryForReport(encid, xx, sUnit) & gb.NewLine & "<br>")
    Else If sType = "Qualitative" Then
      yy = yy & modString.TextToHTML(GetQualiLaboratoryForReport(encid, xx) & gb.NewLine & "<br>")
    Endif
  Next

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Laboratory" & "</b><br>" & yy)
  '   Else
  '     .Add("Laboratory")
  '     .Add(yy)
  '   Endif
  ' End With

  stChapter = "Laboratory"
    stObservation = yy
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

Public Function AddSelectedRadio(encid As String, test As String[]) As String[]

  Dim asx As New String[0]
  Dim xx As String
  Dim yy As String

  Dim stChapter As String
  Dim stObservation As String

  yy = ""
  For Each xx In test
    If modFixRadio.GetRadioTestType(xx) = "Quantitative" Then
      yy = yy & modString.TextToHTML(GetQuantiRadioForReport(encid, xx) & gb.NewLine & "<br>")
    Else If modFixRadio.GetRadioTestType(xx) = "Qualitative" Then
      yy = yy & modString.TextToHTML(GetQualiRadioForReport(encid, xx) & gb.NewLine & "<br>")
    Endif
  Next

  ' With asx
  '   If modBasic.$MedRepoBody = "Paragraph" Then
  '     .Add("<b>" & "Radio Diagnostics" & "</b><br>" & yy)
  '   Else
  '     .Add("Radio Diagnostics")
  '     .Add(yy)
  '   Endif
  ' End With

  stChapter = "Radio Diagnostics"
    stObservation = yy
    asx = AddCustomReport(stChapter, stObservation)
  Return asx

End

'''------------------------------------Admission Sheet------------------------------------------------
Public Function ShowAdmissionSheet(encid As String) As String

  Dim $BillingReport As CReportHTML

  Inc Application.Busy
  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("ADMISSION REPORT", "PARAM1")

  $BillingReport.Add(AddPresentingComplaints(encid))
  $BillingReport.Add(AddOPDFindings(encid))
  $BillingReport.Add(AddClinicalFindingsVital(encid))
  $BillingReport.Add(AddHistoryOfIllness(encid))
  $BillingReport.Add(AddProvisionalDiagnosis(encid))
  $BillingReport.Add(AddOPDAdvice(encid))
  Dec Application.Busy

  Return $BillingReport.NewHTMLPath()

End

Public Function ShowOPatSummary(encid As String) As String

  Dim $BillingReport As CReportHTML

  Inc Application.Busy
  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("OUTPATIENT REPORT", "PARAM1")

  $BillingReport.Add(AddPresentingComplaints(encid))
  $BillingReport.Add(AddOPDFindings(encid))
  $BillingReport.Add(AddClinicalFindingsVital(encid))
  $BillingReport.Add(AddProvisionalDiagnosis(encid))
  $BillingReport.Add(AddInvestigationAdvised(encid))
  $BillingReport.Add(AddTreatmentAdvised(encid))
  $BillingReport.Add(AddOPDAdvice(encid))
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowDischargeReport(encid As String, exam As String[], radio As String[], test As String[], strUnit As String) As String

  Dim $BillingReport As CReportHTML
  Dim xdelivery As String[]

  Inc Application.Busy
  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("DISCHARGE REPORT", "PARAM1")

  $BillingReport.AddSection("General", True)
  $BillingReport.Add(AddCourseOfTreatment(encid))
  $BillingReport.Add(AddTriageFindings(encid))
  $BillingReport.Add(AddPresentingComplaints(encid))
  $BillingReport.Add(AddOPDFindings(encid))
  $BillingReport.Add(AddGenComplaints(encid))
  $BillingReport.Add(AddHistoryOfIllness(encid))
  $BillingReport.Add(AddPastHistory(encid))
  $BillingReport.Add(AddTreatmentHistory(encid))
  $BillingReport.Add(AddMedicatHistory(encid))
  $BillingReport.Add(AddFamilyHistory(encid))
  $BillingReport.Add(AddPersonalHistory(encid))
  $BillingReport.Add(AddPatDemographics(encid))
  $BillingReport.Add(AddDrugAllergy(encid))
  $BillingReport.Add(AddProvisionalDiagnosis(encid))
  $BillingReport.Add(AddOPDAdvice(encid))

  $BillingReport.Add(AddFinalDiagnosis(encid))
  $BillingReport.Add(AddProminientSymptoms(encid))
  $BillingReport.Add(AddMajorProcedures(encid))
  $BillingReport.Add(AddExtraProcedures(encid))
  $BillingReport.Add(AddMedicationUsed(encid))

  xdelivery = DeliveryReportbyMother(encid)
  If xdelivery Then
    $BillingReport.Add(AddCustomReport("Delivery Profile", xdelivery.Join(gb.NewLine)))
  Endif

  $BillingReport.AddSection("Investigations", True)
  $BillingReport.Add(AddSelectedExamination(encid, exam))
  $BillingReport.Add(AddSelectedTest(encid, test, strUnit))
  $BillingReport.Add(AddSelectedRadio(encid, radio))

  $BillingReport.AddSection("Discharge", True)
  $BillingReport.Add(AddPlannedProcedures(encid))
  $BillingReport.Add(AddDischargeFindings(encid))
  $BillingReport.Add(AddConditionAtDischarge(encid))
  $BillingReport.Add(AddDischargeMedication(encid))
  $BillingReport.Add(AddAdviceDischarge(encid))
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowAllCompleteReport(encid As String, strUnit As String) As String

  Dim $BillingReport As CReportHTML
  Dim xdelivery As String[]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Category"), ("Observations")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("COMPLETE REPORT", "PARAM1")

  $BillingReport.AddSection("General", True)
  $BillingReport.Add(AddCourseOfTreatment(encid))
  $BillingReport.Add(AddBedTransition(encid))
  $BillingReport.Add(AddPatDemographics(encid))
  $BillingReport.Add(AddTriageFindings(encid))
  $BillingReport.Add(AddCauseofAdmission(encid))
  $BillingReport.Add(AddPresentingComplaints(encid))
  $BillingReport.Add(AddOPDFindings(encid))
  $BillingReport.Add(AddGenComplaints(encid))
  $BillingReport.Add(AddHistoryOfIllness(encid))
  $BillingReport.Add(AddPastHistory(encid))
  $BillingReport.Add(AddTreatmentHistory(encid))
  $BillingReport.Add(AddMedicatHistory(encid))
  $BillingReport.Add(AddFamilyHistory(encid))
  $BillingReport.Add(AddPersonalHistory(encid))
  $BillingReport.Add(AddDrugAllergy(encid))
  $BillingReport.Add(AddProvisionalDiagnosis(encid))
  $BillingReport.Add(AddOPDAdvice(encid))

  $BillingReport.Add(AddFinalDiagnosis(encid))
  $BillingReport.Add(AddProminientSymptoms(encid))
  $BillingReport.Add(AddMajorProcedures(encid))
  $BillingReport.Add(AddMinorProcedures(encid))
  $BillingReport.Add(AddConsultationAll(encid))
  $BillingReport.Add(AddEquipmentsUsed(encid))
  $BillingReport.Add(AddExtraProcedures(encid))
  $BillingReport.Add(AddMedicationUsed(encid))
  $BillingReport.Add(AddTreatmentAdvised(encid))

  xdelivery = DeliveryReportbyMother(encid)
  If xdelivery Then
    $BillingReport.Add(AddCustomReport("Delivery Profile", xdelivery.Join(gb.NewLine)))
  Endif

  $BillingReport.AddSection("Investigations & Planning", True)
  $BillingReport.Add(AddClinicalFindingsVital(encid))
  $BillingReport.Add(AddClinicalFindingsStructured(encid))
  $BillingReport.Add(AddClinicalFindingsNonVital(encid))
  $BillingReport.Add(AddSelectedTest(encid, modLabTest.PaientAllTestNameArray(encid), strUnit))
  $BillingReport.Add(AddSelectedRadio(encid, modRadioTest.PaientAllRadioNameArray(encid)))
  $BillingReport.Add(AddClinicalNotes(encid))
  $BillingReport.Add(AddIPMonitoring(encid))
  $BillingReport.Add(AddTherapeuticPlanning(encid))

  If modPatient.CurrentAdmissionStatus(encid) = "Discharged" Then
    $BillingReport.AddSection("Discharge", True)
    $BillingReport.Add(AddPlannedProcedures(encid))
    $BillingReport.Add(AddDischargeFindings(encid))
    $BillingReport.Add(AddConditionAtDischarge(encid))
    $BillingReport.Add(AddDischargeMedication(encid))
    $BillingReport.Add(AddAdviceDischarge(encid))
  Endif

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowCompleteReport(encid As String, strUnit As String) As String

  Dim $BillingReport As CReportHTML
  Dim xdelivery As String[]
  Dim xList As String[]
  Dim xvarList As Variant[]

  Dim examlist As String[]
  Dim lablist As String[]
  Dim radiolist As String[]

  xList = SelectMedBody("")
  Wait
  If xList Then
    If xList.Exist("Selected Investigations") Then
      xvarList = ListViewMulti(encid)
      If xvarList Then
        examlist = xvarList[0]
        lablist = xvarList[1]
        radiolist = xvarList[2]
      Endif
    Endif
  Endif

  Inc Application.Busy
  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], modHelpVariable.$htmlDirectory, "PatientReport", encid)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("SELECTED PARAMETERS", "PARAM1")

  $BillingReport.AddSection("General", True)
  If xList Then

    If xList.Exist("Course of Treatment") Then
      $BillingReport.Add(AddCourseOfTreatment(encid))
    Endif
    If xList.Exist("Bed Transitions") Then
      $BillingReport.Add(AddBedTransition(encid))
    Endif
    If xList.Exist("Demographics") Then
      $BillingReport.Add(AddPatDemographics(encid))
    Endif
    If xList.Exist("Triage Examinations") Then
      $BillingReport.Add(AddTriageFindings(encid))
    Endif
    If xList.Exist("Cause of Admission") Then
      $BillingReport.Add(AddCauseofAdmission(encid))
    Endif
    If xList.Exist("Presenting Complaints") Then
      $BillingReport.Add(AddPresentingComplaints(encid))
    Endif
    If xList.Exist("OPD Examinations") Then
      $BillingReport.Add(AddOPDFindings(encid))
    Endif
    If xList.Exist("General Complaints") Then
      $BillingReport.Add(AddGenComplaints(encid))
    Endif
    If xList.Exist("History of Illness") Then
      $BillingReport.Add(AddHistoryOfIllness(encid))
    Endif
    If xList.Exist("Past History") Then
      $BillingReport.Add(AddPastHistory(encid))
    Endif
    If xList.Exist("Treatment History") Then
      $BillingReport.Add(AddTreatmentHistory(encid))
    Endif
    If xList.Exist("Medication History") Then
      $BillingReport.Add(AddMedicatHistory(encid))
    Endif
    If xList.Exist("Family History") Then
      $BillingReport.Add(AddFamilyHistory(encid))
    Endif
    If xList.Exist("Personal History") Then
      $BillingReport.Add(AddPersonalHistory(encid))
    Endif
    If xList.Exist("Surgical History") Then
      $BillingReport.Add(AddSurgicalHistory(encid))
    Endif
    If xList.Exist("Occupational History") Then
      $BillingReport.Add(AddOccupationalHistory(encid))
    Endif
    If xList.Exist("Social History") Then
      $BillingReport.Add(AddSocialHistory(encid))
    Endif
    If xList.Exist("Drug Allergy") Then
      $BillingReport.Add(AddDrugAllergy(encid))
    Endif
    If xList.Exist("Provisional Diagnosis") Then
      $BillingReport.Add(AddProvisionalDiagnosis(encid))
    Endif
    If xList.Exist("Initial Planning") Then
      $BillingReport.Add(AddOPDAdvice(encid))
    Endif

    If xList.Exist("Final Diagnosis") Then
      $BillingReport.Add(AddFinalDiagnosis(encid))
    Endif
    If xList.Exist("Prominent Symptoms") Then
      $BillingReport.Add(AddProminientSymptoms(encid))
    Endif
    If xList.Exist("Major Procedures") Then
      $BillingReport.Add(AddMajorProcedures(encid))
    Endif
    If xList.Exist("Minor Procedures") Then
      $BillingReport.Add(AddMinorProcedures(encid))
    Endif
    If xList.Exist("Consultations") Then
      $BillingReport.Add(AddConsultationAll(encid))
    Endif
    If xList.Exist("Equipments Used") Then
      $BillingReport.Add(AddEquipmentsUsed(encid))
    Endif
    If xList.Exist("Extra Procedures") Then
      $BillingReport.Add(AddExtraProcedures(encid))
    Endif
    If xList.Exist("Medication Used") Then
      $BillingReport.Add(AddMedicationUsed(encid))
    Endif
    If xList.Exist("Treatment Advised") Then
      $BillingReport.Add(AddTreatmentAdvised(encid))
    Endif

    If xList.Exist("Delivery Profile") Then
      xdelivery = DeliveryReportbyMother(encid)
      If xdelivery Then
        $BillingReport.Add(AddCustomReport("Delivery Profile", xdelivery.Join(gb.NewLine)))
      Endif
    Endif

    $BillingReport.AddSection("Investigations", True)
    If xList.Exist("Selected Investigations") Then
      If examlist Then
        If examlist.Count Then
          $BillingReport.Add(AddSelectedExamination(encid, examlist))
        Endif
      Endif
      If lablist Then
        If lablist.Count Then
          $BillingReport.Add(AddSelectedTest(encid, lablist, strUnit))
        Endif
      Endif
      If radiolist Then
        If radiolist.Count Then
          $BillingReport.Add(AddSelectedRadio(encid, radiolist))
        Endif
      Endif
    Endif

    If xList.Exist("Essential Examinations") Then
      $BillingReport.Add(AddClinicalFindingsVital(encid))
    Endif
    If xList.Exist("Structured Examinations") Then
      $BillingReport.Add(AddClinicalFindingsStructured(encid))
    Endif
    If xList.Exist("Clinical Findings") Then
      $BillingReport.Add(AddClinicalFindingsNonVital(encid))
    Endif
    If xList.Exist("Laboratory Tests") Then
      $BillingReport.Add(AddSelectedTest(encid, modLabTest.PaientAllTestNameArray(encid), strUnit))
    Endif
    If xList.Exist("Radiological Findings") Then
      $BillingReport.Add(AddSelectedRadio(encid, modRadioTest.PaientAllRadioNameArray(encid)))
    Endif
    If xList.Exist("Clinical Notes") Then
      $BillingReport.Add(AddClinicalNotes(encid))
    Endif
    If xList.Exist("IP Monitoring") Then
      $BillingReport.Add(AddIPMonitoring(encid))
    Endif
    If xList.Exist("Therapeutic Planning") Then
      $BillingReport.Add(AddTherapeuticPlanning(encid))
    Endif

    If modPatient.CurrentAdmissionStatus(encid) = "Discharged" Then
      $BillingReport.AddSection("Discharge", True)
      If xList.Exist("Planned Procedures") Then
        $BillingReport.Add(AddPlannedProcedures(encid))
      Endif
      If xList.Exist("Discharge Examinations") Then
        $BillingReport.Add(AddDischargeFindings(encid))
      Endif
      If xList.Exist("Condition at Discharge") Then
        $BillingReport.Add(AddConditionAtDischarge(encid))
      Endif
      If xList.Exist("Discharge Medication") Then
        $BillingReport.Add(AddDischargeMedication(encid))
      Endif
      If xList.Exist("Advice on Discharge") Then
        $BillingReport.Add(AddAdviceDischarge(encid))
      Endif
    Endif

  Endif

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowAllEncounterSpecific(patno As String, strUnit As String, sType As String) As String

  Dim $BillingReport As CReportHTML
  Dim encounter As String
  Dim encid As String
  Dim encList As String[]

  Inc Application.Busy
  encounter = modPatient.GetLastEncoutnerFromPatNo(patno)
  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], modHelpVariable.$htmlDirectory, "PatientReport", encounter)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], modHelpVariable.$htmlDirectory, "PatientReport", encounter)
  Endif
  $BillingReport.UserData.Add("REPORT: " & sType, "Report")
  $BillingReport.UserData.Add("ALL ENCOUNTERS REPORT", "PARAM1")

  encList = modPatient.GetEncListFromPatNo(patno)
  For Each encid In encList
    $BillingReport.AddChapter("Encounter : " & encid)

    If sType = "Medicines" Then
      $BillingReport.Add(AddMedicationUsed(encid))
      $BillingReport.Add(AddTreatmentAdvised(encid))
    Else If sType = "Laboratory" Then
      $BillingReport.Add(AddSelectedTest(encid, modLabTest.PaientAllTestNameArray(encid), strUnit))
    Else If sType = "Radiology" Then
      $BillingReport.Add(AddSelectedRadio(encid, modRadioTest.PaientAllRadioNameArray(encid)))
    Endif

  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowAllEncounterReport(patno As String, strUnit As String) As String

  Dim $BillingReport As CReportHTML
  Dim encounter As String
  Dim encid As String
  Dim encList As String[]
  Dim xdelivery As String[]
  Dim xList As String[]
  Dim xvarList As Variant[]

  Dim examlist As String[]
  Dim lablist As String[]
  Dim radiolist As String[]

  encounter = modPatient.GetLastEncoutnerFromPatNo(patno)
  xList = SelectMedBody("")
  Wait
  If xList Then
    If xList.Exist("Selected Investigations") Then
      xvarList = ListViewMulti(encounter)
      If xvarList Then
        examlist = xvarList[0]
        lablist = xvarList[1]
        radiolist = xvarList[2]
      Endif
    Endif
  Endif

  Inc Application.Busy
  If modBasic.$MedRepoBody = "Paragraph" Then
    $BillingReport = New CReportHTML([("Description")], modHelpVariable.$htmlDirectory, "PatientReport", encounter)
  Else
    $BillingReport = New CReportHTML([("Category"), ("Observations")], modHelpVariable.$htmlDirectory, "PatientReport", encounter)
  Endif
  $BillingReport.UserData.Add("REPORT", "Report")
  $BillingReport.UserData.Add("ALL ENCOUNTERS REPORT", "PARAM1")

  encList = modPatient.GetEncListFromPatNo(patno)
  For Each encid In encList
    $BillingReport.AddChapter("Encounter : " & encid)

    If xList Then
      If xList.Exist("Course of Treatment") Then
        $BillingReport.Add(AddCourseOfTreatment(encid))
      Endif
      If xList.Exist("Bed Transitions") Then
        $BillingReport.Add(AddBedTransition(encid))
      Endif
      If xList.Exist("Demographics") Then
        $BillingReport.Add(AddPatDemographics(encid))
      Endif
      If xList.Exist("Triage Examinations") Then
        $BillingReport.Add(AddTriageFindings(encid))
      Endif
      If xList.Exist("Cause of Admission") Then
        $BillingReport.Add(AddCauseofAdmission(encid))
      Endif
      If xList.Exist("Presenting Complaints") Then
        $BillingReport.Add(AddPresentingComplaints(encid))
      Endif
      If xList.Exist("OPD Examinations") Then
        $BillingReport.Add(AddOPDFindings(encid))
      Endif
      If xList.Exist("General Complaints") Then
        $BillingReport.Add(AddGenComplaints(encid))
      Endif
      If xList.Exist("History of Illness") Then
        $BillingReport.Add(AddHistoryOfIllness(encid))
      Endif
      If xList.Exist("Past History") Then
        $BillingReport.Add(AddPastHistory(encid))
      Endif
      If xList.Exist("Treatment History") Then
        $BillingReport.Add(AddTreatmentHistory(encid))
      Endif
      If xList.Exist("Medication History") Then
        $BillingReport.Add(AddMedicatHistory(encid))
      Endif
      If xList.Exist("Family History") Then
        $BillingReport.Add(AddFamilyHistory(encid))
      Endif
      If xList.Exist("Personal History") Then
        $BillingReport.Add(AddPersonalHistory(encid))
      Endif
      If xList.Exist("Surgical History") Then
        $BillingReport.Add(AddSurgicalHistory(encid))
      Endif
      If xList.Exist("Occupational History") Then
        $BillingReport.Add(AddOccupationalHistory(encid))
      Endif
      If xList.Exist("Social History") Then
        $BillingReport.Add(AddSocialHistory(encid))
      Endif
      If xList.Exist("Drug Allergy") Then
        $BillingReport.Add(AddDrugAllergy(encid))
      Endif
      If xList.Exist("Provisional Diagnosis") Then
        $BillingReport.Add(AddProvisionalDiagnosis(encid))
      Endif
      If xList.Exist("Initial Planning") Then
        $BillingReport.Add(AddOPDAdvice(encid))
      Endif

      If xList.Exist("Final Diagnosis") Then
        $BillingReport.Add(AddFinalDiagnosis(encid))
      Endif
      If xList.Exist("Prominent Symptoms") Then
        $BillingReport.Add(AddProminientSymptoms(encid))
      Endif
      If xList.Exist("Major Procedures") Then
        $BillingReport.Add(AddMajorProcedures(encid))
      Endif
      If xList.Exist("Minor Procedures") Then
        $BillingReport.Add(AddMinorProcedures(encid))
      Endif
      If xList.Exist("Consultations") Then
        $BillingReport.Add(AddConsultationAll(encid))
      Endif
      If xList.Exist("Equipments Used") Then
        $BillingReport.Add(AddEquipmentsUsed(encid))
      Endif
      If xList.Exist("Extra Procedures") Then
        $BillingReport.Add(AddExtraProcedures(encid))
      Endif
      If xList.Exist("Medication Used") Then
        $BillingReport.Add(AddMedicationUsed(encid))
      Endif
      If xList.Exist("Treatment Advised") Then
        $BillingReport.Add(AddTreatmentAdvised(encid))
      Endif

      If xList.Exist("Delivery Profile") Then
        xdelivery = DeliveryReportbyMother(encid)
        If xdelivery Then
          $BillingReport.Add(AddCustomReport("Delivery Profile", xdelivery.Join(gb.NewLine)))
        Endif
      Endif

      If xList.Exist("Selected Investigations") Then
        If examlist Then
          If examlist.Count Then
            $BillingReport.Add(AddSelectedExamination(encid, examlist))
          Endif
        Endif
        If lablist Then
          If lablist.Count Then
            $BillingReport.Add(AddSelectedTest(encid, lablist, strUnit))
          Endif
        Endif
        If radiolist Then
          If radiolist.Count Then
            $BillingReport.Add(AddSelectedRadio(encid, radiolist))
          Endif
        Endif
      Endif

      If xList.Exist("Essential Examinations") Then
        $BillingReport.Add(AddClinicalFindingsVital(encid))
      Endif
      If xList.Exist("Structured Examinations") Then
        $BillingReport.Add(AddClinicalFindingsStructured(encid))
      Endif
      If xList.Exist("Clinical Findings") Then
        $BillingReport.Add(AddClinicalFindingsNonVital(encid))
      Endif
      If xList.Exist("Laboratory Tests") Then
        $BillingReport.Add(AddSelectedTest(encid, modLabTest.PaientAllTestNameArray(encid), strUnit))
      Endif
      If xList.Exist("Radiological Findings") Then
        $BillingReport.Add(AddSelectedRadio(encid, modRadioTest.PaientAllRadioNameArray(encid)))
      Endif
      If xList.Exist("Clinical Notes") Then
        $BillingReport.Add(AddClinicalNotes(encid))
      Endif
      If xList.Exist("IP Monitoring") Then
        $BillingReport.Add(AddIPMonitoring(encid))
      Endif
      If xList.Exist("Therapeutic Planning") Then
        $BillingReport.Add(AddTherapeuticPlanning(encid))
      Endif

      If xList.Exist("Planned Procedures") Then
        $BillingReport.Add(AddPlannedProcedures(encid))
      Endif
      If xList.Exist("Discharge Examinations") Then
        $BillingReport.Add(AddDischargeFindings(encid))
      Endif
      If xList.Exist("Condition at Discharge") Then
        $BillingReport.Add(AddConditionAtDischarge(encid))
      Endif
      If xList.Exist("Discharge Medication") Then
        $BillingReport.Add(AddDischargeMedication(encid))
      Endif
      If xList.Exist("Advice on Discharge") Then
        $BillingReport.Add(AddAdviceDischarge(encid))
      Endif

    Endif
  Next

  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

''------------------------ General ------------------------------------------------------
Public Function GetPatientSymptomReport(encid As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]

  sql = "select fldtime,flditem,fldreportquali,flddetail from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldsave=&3"
  res = modDatabase.$syConn.Exec(sql, encid, "Patient Symptoms", True)
  xx = New String[]
  If res.Available = True Then
    For Each res
      If res!fldreportquali Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx.Add("[" & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & "] " & res!flditem & " (" & res!fldreportquali & ")" & " [" & res!flddetail & " ]")
        Else
          xx.Add(res!flditem & " (" & res!fldreportquali & ")" & " [" & res!flddetail & " ]")
        Endif
      Else
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx.Add("[" & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & "] " & res!flditem & " [" & res!flddetail & " ]")
        Else
          xx.Add(res!flditem & " [" & res!flddetail & " ]")
        Endif
      Endif
    Next
  Endif

  Return xx

End

Public Function GetPatientPresentingSymptomReport(encid As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]
  Dim xqty As String

  sql = "select fldtime,flditem,fldreportquali,fldreportquanti,flddetail from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and fldsave=&3"
  res = modDatabase.$syConn.Exec(sql, encid, "Presenting Symptoms", True)
  xx = New String[]
  If res.Available = True Then
    For Each res

      If res!fldreportquanti Then
        xqty = modDate.ConvertHoursToString(res!fldreportquanti)
      Else
        xqty = ""
      Endif

      If res!flddetail Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx.Add("[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & res!flditem & " : " & xqty & Space(1) & res!fldreportquali & " [" & res!flddetail & "]")
        Else
          xx.Add(res!flditem & " : " & xqty & Space(1) & res!fldreportquali & " [" & res!flddetail & "]")
        Endif
      Else
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx.Add("[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & res!flditem & " : " & xqty & Space(1) & res!fldreportquali)
        Else
          xx.Add(res!flditem & " : " & xqty & Space(1) & res!fldreportquali)
        Endif
      Endif

    Next
  Endif

  Return xx

End

Public Function GetPatientDemographicReport(encid As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]

  sql = "select fldtime,flditem,fldreportquali,flddetail from tblexamgeneral where fldencounterval=&1 and fldinput=&2"
  res = modDatabase.$syConn.Exec(sql, encid, "Demographics")
  xx = New String[]
  If res.Available = True Then
    For Each res
      If res!fldreportquali Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx.Add("[" & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & "] " & res!flditem & " : " & res!fldreportquali)
        Else
          xx.Add(res!flditem & " : " & res!fldreportquali)
        Endif
      Endif
    Next
  Endif

  Return xx

End

Public Function GetPatProcedureList(encid As String, strType As String, sCondi As String) As String[]

  Dim res As Result
  Dim xlst As String[]
  Dim xx As String
  Dim xval As String

  xlst = New String[]
  res = modDatabase.$syConn.Exec("select fldid,fldnewdate,flditem,flddetail from tblpatgeneral where fldencounterval=&1 and fldinput=&2 and fldreportquali=&3", encid, strType, sCondi)
  If res.Available = True Then
    For Each res
      If res!flddetail Then
        xval = " : " & res!flddetail & gb.NewLine
      Else
        xval = ""
      Endif
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx = "[ " & modReportVar.GetDateTimeReport(res!fldnewdate, gb.GeneralDate) & " ] " & res!flditem & xval
      Else
        xx = "[ " & modReportVar.GetDateTimeReport(res!fldnewdate, gb.GeneralDate) & " ] " & res!flditem & xval
      Endif
      xlst.Add(xx)
    Next
  Endif
  Return xlst

End

Public Function GetPatExtProcedureList(encid As String, sCondi As String) As String[]

  Dim res As Result
  Dim xlst As String[]
  Dim xx As String
  Dim xval As String

  xlst = New String[]
  res = modDatabase.$syConn.Exec("select fldid,fldnewdate,flditem,flddetail from tblpatgeneral where fldencounterval=&1 and fldinput=&2 and fldreportquali=&3", encid, "Extra Procedures", sCondi)
  If res.Available = True Then
    For Each res
      xval = modPatientGeneral.GetExtProcedTable(res!fldid, encid, res!flditem)
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx = "[ " & modReportVar.GetDateTimeReport(res!fldnewdate, gb.GeneralDate) & " ] " & res!flditem & xval
      Else
        xx = "[ " & modReportVar.GetDateTimeReport(res!fldnewdate, gb.GeneralDate) & " ] " & res!flditem & xval
      Endif
      xlst.Add(xx)
    Next
  Endif
  Return xlst

End

''-------------Notes -----------------------------
Public Function GetPatientNoteReport(encid As String, sType As String) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String

  sql = "select flddetail,fldtime from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and flditem=&3"
  res = modDatabase.$syConn.Exec(sql, encid, "Notes", sType)
  If res.Available = True Then
    res.MoveLast
    If modBasic.$ShowDayMedReport = "Yes" Then
      xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ]" & " : " & res!flddetail
    Else
      xx = res!flddetail
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetClinNotesReport(encid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$syConn.Exec("select fldtime,flditem,fldreportquali,flddetail from tblexamgeneral where fldencounterval=&1 and fldinput=&2 and (flditem=&3 or flditem=&4 or flditem=&5)", encid, "Notes", "Progress Note", "Clinicians Note", "Nurses Note")
  xx = New String[]
  If res.Available = True Then
    For Each res
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx.Add("<p>" & "[" & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & "] Category: " & res!flditem & "<br>" & modString.TextToHTML(res!flddetail) & "<br>" & "IMPRESSION: " & res!fldreportquali & "</p>")
      Else
        xx.Add("<p>" & "Category: " & res!flditem & "<br>" & modString.TextToHTML(res!flddetail) & "<br>" & "IMPRESSION: " & res!fldreportquali & "</p>")
      Endif
    Next
  Endif
  Return xx

End

''-------------------------- Daily -------------------------------------------------------
Public Function OPDMedString(encid As String) As String[]

  Dim rs As Result
  Dim xx As String[]

  xx = New String[]
  rs = modDatabase.$syConn.Exec("select fldid,fldstarttime,fldroute,flditem,flddose,fldfreq,flddays,flditemtype from tblpatdosing where fldencounterval=&1 and flditemtype=&2 and (fldstatus=&3 or fldstatus=&4 or fldstatus=&5)", encid, "Medicines", "Registered", "Admitted", "Recorded")
  If rs.Available = True Then
    For Each rs
      If rs!flditemtype = "Medicines" Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx.Add("[ " & modReportVar.GetDateTimeReport(rs!fldstarttime, gb.GeneralDate) & " ] " & modPharmacy.GetMedFormatForMedReport(rs!flditem, rs!fldroute) & Space(1) & modPharmacy.GetDoseRegimenString(rs!fldid, True))
        Else
          xx.Add(modPharmacy.GetMedFormatForMedReport(rs!flditem, rs!fldroute) & Space(1) & modPharmacy.GetDoseRegimenString(rs!fldid, True))
        Endif
      Endif
    Next
  Endif

  Return xx

End

Public Function GetPatientPlanningReport(encid As String) As String[]

  Dim res As Result
  Dim xx As String
  Dim xlst As String[]

  xlst = New String[]
  res = modDatabase.$syConn.Exec("select fldtime,fldproblem,fldsubjective,fldobjective,fldassess,fldplan from tblpatplanning where fldencounterval=&1 and fldplancategory=&2", encid, "Clinician Plan")
  If res.Available = True Then
    For Each res
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx = "<p>" & "[" & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & "]" & "<br>" & " Problem: " & res!fldproblem
      Else
        xx = "<p>" & " Problem: " & res!fldproblem
      Endif
      If res!fldsubjective Then
        xx = xx & "<br>" & "Subjective: " & modString.TextToHTML(res!fldsubjective)
      Endif
      If res!fldobjective Then
        xx = xx & "<br>" & "Objective: " & modString.TextToHTML(res!fldobjective)
      Endif
      If res!fldassess Then
        xx = xx & "<br>" & "Assessment: " & modString.TextToHTML(res!fldassess)
      Endif
      If res!fldplan Then
        xx = xx & "<br>" & "Planning: " & modString.TextToHTML(res!fldplan)
      Endif
      xx = xx & "</p>"                       ''
      xlst.Add(xx)
      xx = ""
    Next
  Endif
  Return xlst

End

Public Function GetPatientMonitorReport(encid As String) As String[]

  Dim res As Result
  Dim xx As String
  Dim xlst As String[]

  res = modDatabase.$syConn.Exec("select fldid,fldtime,fldproblem,fldsubjective,fldobjective,fldassess,fldplan from tblpatplanning where fldencounterval=&1 and fldplancategory=&2", encid, "IP Monitoring")
  xlst = New String[]
  If res.Available = True Then
    For Each res
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx = "<p>" & "[" & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & "]"
      Else
        xx = "<p>"
      Endif
      If res!fldsubjective Then
        xx = xx & "<br>" & "Problems: " & modString.TextToHTML(res!fldsubjective)
      Endif
      If res!fldobjective Then
        xx = xx & "<br>" & "Treatment: " & modString.TextToHTML(res!fldobjective)
      Endif
      If res!fldassess Then
        xx = xx & "<br>" & "I/O Assessment: " & modString.TextToHTML(res!fldassess)
      Endif
      xx = xx & "<br>" & "On Examination" & "<br>" & UniProcedureExamination(encid, res!fldid, "IP Monitoring").Join("<br>")
      If res!fldproblem Then
        xx = xx & "<br>" & "Impression: " & modString.TextToHTML(res!fldproblem)
      Endif
      If res!fldplan Then
        xx = xx & "<br>" & "Planning: " & modString.TextToHTML(res!fldplan)
      Endif
      xx = xx & "</p>"             ''
      xlst.Add(xx)
      xx = ""
    Next
  Endif
  Return xlst

End

''-------------------------- exam/test ----------------------------------------------
Public Function WardOrderLabRequest(encid As String) As String[]

  Dim res As Result
  Dim sql As String
  Dim xx As String[]

  sql = "select flditemname,flditemqty,fldtime from tblpatbilling where fldencounterval= &1 and flditemtype=&2 and fldsave=&3 and fldstatus=&4"
  res = modDatabase.$syConn.Exec(sql, encid, "Diagnostic Tests", True, "Done")
  xx = New String[]
  If res.Available = True Then
    For Each res
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx.Add("[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & res!flditemname & " (" & res!flditemqty & ")")
      Else
        xx.Add(res!flditemname & " (" & res!flditemqty & ")")
      Endif
    Next
  Endif
  Return xx

End

Public Function GetVitalClinicalFinding(encid As String) As String[]

  Dim xx As String
  Dim exam As String[]
  Dim xlist As String[]

  exam = New String[]
  xlist = modClinic.PaientSelExamNameArray(encid, "Vital")
  For Each xx In xlist
    exam.Add(GetReportExamSelString("Last", encid, xx))
  Next
  Return exam

End

Public Function GetNonVitalClinicalFinding(encid As String) As String[]

  Dim xx As String
  Dim exam As String[]
  Dim xlist As String[]

  exam = New String[]
  xlist = modClinic.PaientSelExamNameArray(encid, "Non-Vital")
  For Each xx In xlist
    exam.Add(GetReportExamSelString("Last", encid, xx))
  Next
  Return exam

End

'''-------------------------- Test and Examination Functions --------------------------------
Public Function GetChartImageExam(encid As String, exam As String) As String

  Dim sql As String
  Dim res As Result
  Dim maxval As Float
  Dim minval As Float
  Dim normval As Float
  Dim pointsArr_x As Float[]
  Dim pointsArr_y As Float[]
  Dim xx As String
  Dim xlimit As Float[]

  pointsArr_x = New Float[]
  pointsArr_y = New Float[]
  xlimit = modClinic.GetBothQuantiExamVal(exam, encid)
  minval = xlimit[0]
  maxval = xlimit[1]
  normval = modClinic.GetNormalQuantiExamVal(exam, encid)
  sql = "select fldrepquanti,fldtime from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldtype=&3 and fldsave=&4"
  res = modDatabase.$syConn.Exec(sql, encid, exam, "Quantitative", True)
  If res.Count Then
    For Each res
      pointsArr_x.Add(res!fldtime)
      pointsArr_y.Add(res!fldrepquanti)
    Next
  Endif

  xx = modChart.ClinicalChart(100, encid, pointsArr_x, pointsArr_y, maxval, minval, normval)
  Return xx

End

Public Function GetChartImageTest(encid As String, test As String, strUnit As String) As String

  Dim sql As String
  Dim res As Result
  Dim maxval As Float
  Dim minval As Float
  Dim normval As Float
  Dim pointsArr_x As Float[]
  Dim pointsArr_y As Float[]
  Dim xx As String
  Dim xlimit As Float[]

  pointsArr_x = New Float[]
  pointsArr_y = New Float[]

  xlimit = modLabTest.LabBothLimitValue(test, encid, strUnit)
  minval = xlimit[0]
  maxval = xlimit[1]
  normval = modLabTest.LabNormalValue(test, encid, strUnit)

  sql = "select fldid,fldencounterval,fldtime_sample from tblpatlabtest where fldencounterval=&1 and fldtestid=&2 and fldtest_type=&3 and (fldstatus=&4 or fldstatus=&5)"
  res = modDatabase.$syConn.Exec(sql, encid, test, "Quantitative", "Reported", "Verified")
  If res.Count Then
    For Each res
      pointsArr_x.Add(res!fldtime_sample)
      pointsArr_y.Add(modLabTest.GetTestQuantiValue(res!fldencounterval, res!fldid, strUnit))
    Next
  Endif

  xx = modChart.ClinicalChart(100, encid, pointsArr_x, pointsArr_y, maxval, minval, normval)
  Return xx

End

Public Function GetChartImageRadio(encid As String, test As String) As String

  Dim sql As String
  Dim res As Result
  Dim maxval As Float
  Dim minval As Float
  Dim normval As Float
  Dim pointsArr_x As Float[]
  Dim pointsArr_y As Float[]
  Dim xx As String

  pointsArr_x = New Float[]
  pointsArr_y = New Float[]
  maxval = modRadioTest.GetMaxQuantiRadioVal(test, encid)
  minval = modRadioTest.GetMinQuantiRadioVal(test, encid)
  normval = modRadioTest.RadioNormalValue(test, encid)
  sql = "select fldid,fldtime_report from tblpatlabtest where fldencounterval=&1 and fldtestid=&2 and fldtest_type=&3 and (fldstatus=&4 or fldstatus=&5)"
  res = modDatabase.$syConn.Exec(sql, encid, test, "Quantitative", "Reported", "Verified")
  If res.Count Then
    For Each res
      pointsArr_x.Add(res!fldtime_report)
      pointsArr_y.Add(modRadioTest.GetRadioTestValue(res!fldid))
    Next
  Endif

  xx = modChart.ClinicalChart(100, encid, pointsArr_x, pointsArr_y, maxval, minval, normval)
  Return xx

End

Public Function UniProcedureExamination(encid As String, itemid As Long, sType As String) As String[]

  Dim res As Result
  Dim xx As String[]
  Dim xType As String
  Dim xval As String

  res = modDatabase.$syConn.Exec("select fldtime,fldhead,fldrepquali,fldrepquanti,fldoption from tblpatientexam where fldencounterval=&1 and fldinput=&2 and fldsave=&3", encid, sType & ":" & CStr(itemid), True)
  xx = New String[]
  If res.Available Then
    For Each res
      xType = res["fldoption"]
      If xType = "Clinical Scale" Then
        If modBasic.$ShowScaleMedFormat = "GroupWise" Then
          xval = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
        Else
          xval = CStr(res!fldrepquanti)
        Endif
      Else If xType = "Left and Right" Then
        xval = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
      Else
        xval = Trim(res!fldrepquali)
      Endif
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx.Add("[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & res!fldhead & ": " & modString.TextToHTML(xval))
      Else
        xx.Add(res!fldhead & " : " & modString.TextToHTML(xval))
      Endif
    Next
  Endif
  Return xx

End

Public Function DeliveryReportbyMother(encid As String) As String[]

  Dim res As Result
  Dim xx As String
  Dim xlst As String[]

  xlst = New String[]
  res = modDatabase.$syConn.Exec("select fldid,flddelresult,flddeltype,fldbabypatno,flddeltime,flddelwt from tblconfinement where fldencounterval=&1", encid)
  If res.Available Then
    For Each res
      xx = "<p>"
      xx = xx & "Delivery Date: " & modReportVar.GetDateTimeReport(res!flddeltime, gb.GeneralDate) & "<br>"
      xx = xx & "Delivery Type: " & res!flddeltype & "<br>"
      xx = xx & "Delivery Result: " & res!flddelresult & "<br>"
      If res!fldbabypatno Then
        xx = xx & "Baby Patient No: " & res!fldbabypatno & "<br>"
        xx = xx & "Baby Gender: " & modPatient.PatientGenderByPatNo(res!fldbabypatno) & "<br>"
        xx = xx & "Birth Weight: " & res!flddelwt & " grams" & "<br>"
      Endif
      xx = xx & "</p>"
      xlst.Add(xx)
      xx = ""
    Next
  Endif
  Return xlst

End

''-------------------------Laboratory -------------------------------
Private Function GetReportTestSelString(sPos As String, encid As String, test As String, strUnit As String) As String

  Dim sql As String
  Dim res As Result
  Dim metr As Float
  Dim xx As String
  Dim yy As String[]

  xx = ""
  sql = "select fldid,fldencounterval,fldsampletype,fldtime_sample,fldreportquali,fldreportquanti,fldtestunit,fldtest_type from tblpatlabtest where fldencounterval=&1 and fldtestid=&2 and (fldstatus=&3 or fldstatus=&4)"
  res = modDatabase.$syConn.Exec(sql, encid, test, "Reported", "Verified")
  If res.Available = True Then
    If sPos = "First" Then
      res.MoveFirst
    Else
      res.MoveLast
    Endif

    If res!fldtest_type = "Quantitative" Then
      If res!fldreportquanti Then
        If strUnit = "Metric" Then
          If res!fldtestunit = "Metric" Then
            metr = res!fldreportquanti
          Else If res!fldtestunit = "SI" Then
            metr = Round(res!fldreportquanti / modLabTest.GetConvFactorTest(encid, test), -3)
          Endif
        Else If strUnit = "SI" Then
          If res!fldtestunit = "Metric" Then
            metr = Round(res!fldreportquanti * modLabTest.GetConvFactorTest(encid, test), -3)
          Else If res!fldtestunit = "SI" Then
            metr = res!fldreportquanti
          Endif
        Endif
      Else
        metr = 0
      Endif

      If metr Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime_sample, gb.GeneralDate) & " ] " & test & " [Spec: " & res["fldsampletype"] & "]" & " : " & CStr(metr) & Space(1) & modLabTest.LabTestUnit(test, encid, strUnit)
        Else
          xx = test & " [Spec: " & res["fldsampletype"] & "]" & " : " & CStr(metr) & Space(1) & modLabTest.LabTestUnit(test, encid, strUnit)
        Endif
      Else
        xx = ""
      Endif

    Else
      If res!fldreportquali Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime_sample, gb.GeneralDate) & " ] " & test & " [Spec: " & res["fldsampletype"] & "]" & " : " & Trim(res!fldreportquali)
        Else
          xx = test & " [Spec: " & res["fldsampletype"] & "]" & " : " & Trim(res!fldreportquali)
        Endif
      Else
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime_sample, gb.GeneralDate) & " ] " & test & " [Spec: " & res["fldsampletype"] & "]" & " : "
        Else
          xx = test & " [Spec: " & res["fldsampletype"] & "]" & " : "
        Endif

      Endif

      yy = modLabTest.GetLabSubTestQuali(res!fldencounterval, res!fldid)
      If yy.Count Then
        xx = xx & modString.GetHTMLListFormat(yy)
      Endif

    Endif
  Endif
  Return xx

End

Private Function GetCompleteTestByEnc(encid As String, strTest As String, sUnit As String) As String[]

  Dim xx As String[]
  Dim res As Result
  Dim xval As String
  Dim i As Integer
  Dim xtable As String

  i = 1
  res = modDatabase.$syConn.Exec("select fldid,fldencounterval,fldtime_sample,fldsampletype,fldreportquali,fldtest_type from tblpatlabtest where fldencounterval=&1 and fldtestid=&2 and (fldstatus=&3 or fldstatus=&4)", encid, strTest, "Reported", "Verified")
  xx = New String[]
  If res.Available Then
    xx.Add(strTest & " [Spec: " & res["fldsampletype"] & "]")
    For Each res

      If res!fldtest_type = "Quantitative" Then
        xval = CStr(modLabTest.GetTestQuantiValue(res!fldencounterval, res!fldid, sUnit))
      Else
        If res!fldreportquali Then
          xval = Trim(res!fldreportquali)
        Else
          xval = ""
        Endif
        xtable = modString.GetHTMLListFormat(modLabTest.GetLabSubTestQuali(res!fldencounterval, res!fldid))
        If xtable Then
          xval = xval & xtable
        Endif
      Endif

      If modBasic.$ShowDayMedReport = "Yes" Then
        xval = CStr(i) & ".. " & modString.HTMLBlankSpace(3) & "[ " & modReportVar.GetDateTimeReport(res!fldtime_sample, gb.GeneralDate) & " ] " & " : " & xval
      Else
        xval = CStr(i) & ".. " & modString.HTMLBlankSpace(3) & xval
      Endif
      xx.Add(xval)

      i = i + 1
    Next
  Endif
  Return xx

End

Public Function GetQuantiLaboratoryForReport(encid As String, xexam As String, strUnit As String) As String

  Dim xrep As String

  If modBasic.$ShowQuantiMedReport = "Chart" Then
    xrep = xexam & gb.NewLine & modString.GetImageForHTML(GetChartImageTest(encid, xexam, strUnit))
  Else If modBasic.$ShowQuantiMedReport = "FitsrVal" Then
    xrep = GetReportTestSelString("First", encid, xexam, strUnit)
  Else If modBasic.$ShowQuantiMedReport = "First-LastVal" Then
    xrep = GetReportTestSelString("First", encid, xexam, strUnit) & gb.NewLine & GetReportTestSelString("Last", encid, xexam, strUnit)
  Else If modBasic.$ShowQuantiMedReport = "LastVal" Then
    xrep = GetReportTestSelString("Last", encid, xexam, strUnit)
  Else
    xrep = GetCompleteTestByEnc(encid, xexam, strUnit).Join(gb.NewLine)
  Endif

  Return xrep

End

Public Function GetQualiLaboratoryForReport(encid As String, xexam As String) As String

  Dim xrep As String

  If modBasic.$ShowQualiMedReport = "FitsrVal" Then
    xrep = GetReportTestSelString("First", encid, xexam, "Metric")
  Else If modBasic.$ShowQualiMedReport = "First-LastVal" Then
    xrep = GetReportTestSelString("First", encid, xexam, "Metric") & gb.NewLine & GetReportTestSelString("Last", encid, xexam, "Metric")
  Else If modBasic.$ShowQualiMedReport = "LastVal" Then
    xrep = GetReportTestSelString("Last", encid, xexam, "Metric")
  Else
    xrep = GetCompleteTestByEnc(encid, xexam, "Metric").Join(gb.NewLine)
  Endif

  Return xrep

End

''----------------------- Examination ---------------------------------------------
Private Function GetReportExamSelString(sPos As String, encid As String, exam As String) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String
  Dim yy As String[]
  Dim xType As String
  Dim xval As String

  xx = ""
  sql = "select fldid,fldtime,fldhead,fldrepquali,fldrepquanti,fldtype,fldoption from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldsave=&3 and fldinput=&4"
  res = modDatabase.$syConn.Exec(sql, encid, exam, True, "Examination")
  If res.Available = True Then
    If sPos = "First" Then
      res.MoveFirst
    Else
      res.MoveLast
    Endif

    If res!fldtype = "Quantitative" Then
      If res!fldrepquanti Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & exam & " : " & CStr(res!fldrepquanti) & Space(1) & modClinic.GetExamUnit(exam, encid)
        Else
          xx = exam & " : " & CStr(res!fldrepquanti) & Space(1) & modClinic.GetExamUnit(exam, encid)
        Endif
      Else
        xx = ""
      Endif

    Else
      xType = res["fldoption"]
      If xType = "Clinical Scale" Then
        If modBasic.$ShowScaleMedFormat = "GroupWise" Then
          xval = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
        Else
          xval = CStr(res!fldrepquanti)
        Endif
      Else If xType = "Left and Right" Then
        xval = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
      Else
        xval = Trim(res!fldrepquali)
      Endif
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & exam & " : " & xval
      Else
        xx = exam & " : " & xval
      Endif

      yy = modClinic.GetSubExamQualiList(encid, res!fldid)
      If yy.Count Then
        xx = xx & modString.GetHTMLListFormat(yy)
      Endif

    Endif
  Endif
  Return xx

End

Private Function GetCompleteExamByEnc(encid As String, strTest As String) As String[]

  Dim xx As String[]
  Dim sql As String
  Dim res As Result
  Dim i As Integer
  Dim xtable As String
  Dim xType As String
  Dim xval As String

  i = 1
  sql = "select fldid,fldtime,fldhead,fldrepquali,fldrepquanti,fldtype,fldcomp,fldoption from tblpatientexam where fldencounterval=&1 and fldhead=&2 and fldsave=&3 and fldinput=&4"
  res = modDatabase.$syConn.Exec(sql, encid, strTest, True, "Examination")
  xx = New String[]
  If res.Available Then
    xx.Add(strTest & " [Dept: " & res["fldcomp"] & "]")
    For Each res

      If res!fldtype = "Quantitative" Then
        xval = CStr(res!fldrepquanti)
      Else
        If res!fldrepquali Then

          xType = res["fldoption"]
          If xType = "Clinical Scale" Then
            If modBasic.$ShowScaleMedFormat = "GroupWise" Then
              xval = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
            Else
              xval = CStr(res!fldrepquanti)
            Endif
          Else If xType = "Left and Right" Then
            xval = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
          Else
            xval = Trim(res!fldrepquali)
          Endif
        Else
          xval = ""
        Endif
        xtable = modString.GetHTMLListFormat(modClinic.GetSubExamQualiList(encid, res!fldid))
        If xtable Then
          xval = xval & xtable
        Endif
      Endif

      If modBasic.$ShowDayMedReport = "Yes" Then
        xval = CStr(i) & ".. " & modString.HTMLBlankSpace(3) & "[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & " : " & xval
      Else
        xval = CStr(i) & ".. " & modString.HTMLBlankSpace(3) & xval
      Endif
      xx.Add(xval)

      i = i + 1
    Next
  Endif
  Return xx

End

Public Function GetQuantiExaminationForReport(encid As String, xexam As String) As String

  Dim xrep As String

  If modBasic.$ShowQuantiMedReport = "Chart" Then
    xrep = xexam & gb.NewLine & modString.GetImageForHTML(GetChartImageExam(encid, xexam))
  Else If modBasic.$ShowQuantiMedReport = "FitsrVal" Then
    xrep = GetReportExamSelString("First", encid, xexam)
  Else If modBasic.$ShowQuantiMedReport = "First-LastVal" Then
    xrep = GetReportExamSelString("First", encid, xexam) & gb.NewLine & GetReportExamSelString("Last", encid, xexam)
  Else If modBasic.$ShowQuantiMedReport = "LastVal" Then
    xrep = GetReportExamSelString("Last", encid, xexam)
  Else
    xrep = GetCompleteExamByEnc(encid, xexam).Join(gb.NewLine)
  Endif

  Return xrep

End

Public Function GetQualiExaminationForReport(encid As String, xexam As String) As String

  Dim xrep As String

  If modBasic.$ShowQualiMedReport = "FitsrVal" Then
    xrep = GetReportExamSelString("First", encid, xexam)
  Else If modBasic.$ShowQualiMedReport = "First-LastVal" Then
    xrep = GetReportExamSelString("First", encid, xexam) & gb.NewLine & GetReportExamSelString("Last", encid, xexam)
  Else If modBasic.$ShowQualiMedReport = "LastVal" Then
    xrep = GetReportExamSelString("Last", encid, xexam)
  Else
    xrep = GetCompleteExamByEnc(encid, xexam).Join(gb.NewLine)
  Endif

  Return xrep

End

''------------------------------------- Radiology ---------------------------------------------
Private Function GetReportRadioSelString(sPos As String, encid As String, test As String) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String
  Dim yy As String[]

  xx = ""
  sql = "select fldid,fldencounterval,fldtime_report,fldreportquanti,fldreportquali,fldtest_type from tblpatradiotest where fldencounterval=&1 and fldtestid=&2 and (fldstatus=&3 or fldstatus=&4)"
  res = modDatabase.$syConn.Exec(sql, encid, test, "Reported", "Verified")
  If res.Available = True Then
    If sPos = "First" Then
      res.MoveFirst
    Else
      res.MoveLast
    Endif

    If res!fldtest_type = "Quantitative" Then
      If res!fldreportquanti Then
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime_report, gb.GeneralDate) & " ] " & test & " : " & Trim(res!fldreportquanti) & Space(1) & modRadioTest.RadioTestUnit(test, encid)
        Else
          xx = test & " : " & CStr(res!fldreportquanti) & Space(1) & modRadioTest.RadioTestUnit(test, encid)
        Endif
      Else
        xx = ""
      Endif

    Else
      If modBasic.$ShowDayMedReport = "Yes" Then
        xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime_report, gb.GeneralDate) & " ] " & test & " : " & Trim(res!fldreportquali)
      Else
        xx = test & " : " & Trim(res!fldreportquali)
      Endif

      yy = modRadioTest.GetRadioSubTestQuali(res!fldencounterval, res!fldid)
      If yy.Count Then
        xx = xx & modString.GetHTMLListFormat(yy)
      Endif

    Endif
  Endif
  Return xx

End

Private Function GetCompleteRadioByEnc(encid As String, strTest As String) As String[]

  Dim xx As String[]
  Dim sql As String
  Dim res As Result
  Dim xval As String
  Dim i As Integer
  Dim xtable As String

  i = 1
  sql = "select fldid,fldtime_report,fldreportquanti,fldreportquali,fldtest_type from tblpatradiotest where fldencounterval=&1 and fldtestid=&2 and (fldstatus=&3 or fldstatus=&4)"
  res = modDatabase.$syConn.Exec(sql, encid, strTest, "Reported", "Verified")
  xx = New String[]
  If res.Available Then
    ' xx.Add(strTest & " [Dept: " & res["fldcomp"] & "]")
    For Each res

      If res!fldtest_type = "Quantitative" Then
        xval = CStr(res!fldreportquanti)
      Else
        If res!fldrepquali Then
          xval = Trim(res!fldreportquali)
        Else
          xval = ""
        Endif
        xtable = modString.GetHTMLListFormat(modRadioTest.GetRadioSubTestQuali(res!fldid))
        If xtable Then
          xval = xval & xtable
        Endif
      Endif

      If modBasic.$ShowDayMedReport = "Yes" Then
        xval = CStr(i) & ".. " & modString.HTMLBlankSpace(3) & "[ " & modReportVar.GetDateTimeReport(res!fldtime_report, gb.GeneralDate) & " ] " & " : " & xval
      Else
        xval = CStr(i) & ".. " & modString.HTMLBlankSpace(3) & xval
      Endif
      xx.Add(xval)

      i = i + 1
    Next
  Endif
  Return xx

End

Public Function GetQuantiRadioForReport(encid As String, xexam As String) As String

  Dim xrep As String

  If modBasic.$ShowQuantiMedReport = "Chart" Then
    xrep = xexam & gb.NewLine & modString.GetImageForHTML(GetChartImageRadio(encid, xexam))
  Else If modBasic.$ShowQuantiMedReport = "FitsrVal" Then
    xrep = GetReportRadioSelString("First", encid, xexam)
  Else If modBasic.$ShowQuantiMedReport = "First-LastVal" Then
    xrep = GetReportRadioSelString("First", encid, xexam) & gb.NewLine & GetReportRadioSelString("Last", encid, xexam)
  Else If modBasic.$ShowQuantiMedReport = "LastVal" Then
    xrep = GetReportRadioSelString("Last", encid, xexam)
  Else
    xrep = GetCompleteRadioByEnc(encid, xexam).Join(gb.NewLine)
  Endif

  Return xrep

End

Public Function GetQualiRadioForReport(encid As String, xexam As String) As String

  Dim xrep As String

  If modBasic.$ShowQualiMedReport = "FitsrVal" Then
    xrep = GetReportRadioSelString("First", encid, xexam)
  Else If modBasic.$ShowQualiMedReport = "First-LastVal" Then
    xrep = GetReportRadioSelString("First", encid, xexam) & gb.NewLine & GetReportRadioSelString("Last", encid, xexam)
  Else If modBasic.$ShowQualiMedReport = "LastVal" Then
    xrep = GetReportRadioSelString("Last", encid, xexam)
  Else
    xrep = GetCompleteRadioByEnc(encid, xexam).Join(gb.NewLine)
  Endif

  Return xrep

End

''-------------------------- Recommended Examinations -----------------------------
Public Function GetRecommendedExam(encid As String) As String

  Dim res As Result
  Dim catlst As String[]
  Dim itmlst As String[]
  Dim xval As String[]
  Dim xcateg As String
  Dim xitem As String

  Dim res1 As Result
  Dim xfinal As String
  Dim xfull As String
  Dim xType As String
  Dim xquali As String

  xfull = ""
  res = modDatabase.$syConn.Exec("select distinct(fldserialval) as col from tblpatientexam where fldserialval like &1 and fldencounterval=&2 and fldinput=&3 and fldsave=&4", "%", encid, "Rec Examination", True)
  If res.Available Then
    catlst = New String[]
    itmlst = New String[]
    For Each res
      xval = Split(modFixClinic.GetChapterFromRecommendedID(res!col), "@")

      If catlst.Count = 0 Then
        catlst.Add(xval[0])
      Else
        If catlst.Exist(xval[0]) = False Then
          catlst.Add(xval[0])
        Endif
      Endif

      If itmlst.Count = 0 Then
        itmlst.Add(xval[1])
      Else
        If itmlst.Exist(xval[1]) = False Then
          itmlst.Add(xval[1])
        Endif
      Endif

    Next

    For Each xcateg In catlst
      xfull = xfull & xcateg
      xfull = xfull & "<ul>"
      For Each xitem In itmlst
        xfull = xfull & xitem
        xfull = xfull & "<ul>"

        res1 = modDatabase.$syConn.Exec("select fldid,fldtime,fldhead,fldrepquali,fldrepquanti,fldtype,fldoption from tblpatientexam where fldencounterval=&1 and fldinput=&2 and fldsave=&3 and fldserialval in(select fldheadcode from tblstructexam where fldcategory=&4 and flditem=&5)", encid, "Rec Examination", True, xcateg, xitem)                                            ''
        If res1.Available Then
          For Each res1
            If res1!fldtype = "Quantitative" Then
              xfinal = res1!fldhead & " : " & CStr(res1!fldrepquanti) & Space(1) & modClinic.GetExamUnit(res1!fldhead, encid)
            Else

              xType = res1["fldoption"]
              If xType = "Clinical Scale" Then
                If modBasic.$ShowScaleMedFormat = "GroupWise" Then
                  xquali = modString.GetJSONToDualHTMLTable(Trim(res1!fldrepquali))
                Else
                  xquali = CStr(res1!fldrepquanti)
                Endif
              Else If xType = "Left and Right" Then
                xquali = modString.GetJSONToDualHTMLTable(Trim(res1!fldrepquali))
              Else
                xquali = Trim(res1!fldrepquali)
              Endif
              xfinal = res1!fldhead & " : " & xquali
            Endif
            If modBasic.$ShowDayMedReport = "Yes" Then
              xfull = xfull & "<li>" & "[ " & modReportVar.GetDateTimeReport(res1!fldtime, gb.GeneralDate) & " ] " & xfinal & "</li>"
            Else
              xfull = xfull & "<li>" & xfinal & "</li>"
            Endif
          Next
        Endif

        xfull = xfull & "</ul>" & gb.NewLine
      Next
      xfull = xfull & "</ul>" & gb.NewLine
    Next

  Endif

  Return xfull

End

''---------------------------- OPD Findings -----------------------------
Public Function GetSelectFindingReport(encid As String, sType As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String
  Dim yy As String[]
  Dim xList As String[]
  Dim xType As String
  Dim xquali As String

  xlist = New String[]
  sql = "select fldid,fldtime,fldhead,fldrepquali,fldrepquanti,fldtype,fldoption from tblpatientexam where fldencounterval=&1 and fldsave=&2 and fldinput=&3"
  res = modDatabase.$syConn.Exec(sql, encid, True, sType)
  If res.Available = True Then
    For Each res

      xx = ""
      If res!fldtype = "Quantitative" Then
        If res!fldrepquanti Then
          If modBasic.$ShowDayMedReport = "Yes" Then
            xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & res["fldhead"] & " : " & CStr(res!fldrepquanti) & Space(1) & modClinic.GetExamUnit(res["fldhead"], encid)
          Else
            xx = res["fldhead"] & " : " & CStr(res!fldrepquanti) & Space(1) & modClinic.GetExamUnit(res["fldhead"], encid)
          Endif
        Else
          xx = ""
        Endif

      Else

        xType = res["fldoption"]
        If xType = "Clinical Scale" Then
          If modBasic.$ShowScaleMedFormat = "GroupWise" Then
            xquali = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
          Else
            xquali = CStr(res!fldrepquanti)
          Endif
        Else If xType = "Left and Right" Then
          xquali = modString.GetJSONToDualHTMLTable(Trim(res!fldrepquali))
        Else
          xquali = Trim(res!fldrepquali)
        Endif
        If modBasic.$ShowDayMedReport = "Yes" Then
          xx = "[ " & modReportVar.GetDateTimeReport(res!fldtime, gb.GeneralDate) & " ] " & res["fldhead"] & " : " & xquali
        Else
          xx = res["fldhead"] & " : " & xquali
        Endif

        yy = modClinic.GetSubExamQualiList(encid, res!fldid)
        If yy.Count Then
          xx = xx & modString.GetHTMLListFormat(yy)
        Endif

      Endif
      xList.Add(xx)

    Next
  Endif
  Return xList

End
