' Gambas module file

''--------------------------------------------- GENERAL --------------------------------------------------------------------
'##DATE FUNCTION##
Public Function RegistAutoBillingList() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Billing Mode"), ("Particulars"), ("Type"), ("Rate"), ("QTY"), ("Timing"), ("CutOff")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("REGISTRATION AUTOBILLING", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroup) from tblautogroup")
  For Each res
    $BillingReport.AddSection(res!fldgroup, True)
    res1 = modDatabase.$syConn.Exec("select fldid,fldbillingmode,flditemtype,flditemname,flditemqty,fldexitemtype,fldcutoff from tblautogroup where fldgroup=&1", res!fldgroup)
    For Each res1
      With asx
        .Add(res1!fldbillingmode)
        .Add(res1!flditemname)
        .Add(res1!flditemtype)
        .Add(modReportVar.GetLocaleNumberFormat(modNonMedical.GetCashBillItemCost(res1!flditemname, "%"), gb.Currency))
        .Add(res1!flditemqty)
        .Add(res1!fldexitemtype)
        If res1!fldcutoff Then
          .Add(Format(res1!fldcutoff, gb.ShortTime))
        Else
          .Add("")
        Endif
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowBillingListReport(smode As String) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Particulars"), ("Charge"), ("Target/Rate"), ("Status")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("MEDICAL CHARGES : " & smode, "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(flditemtype) from tblservicecost where fldgroup=&1 or fldgroup like &2", "%", smode)
  For Each res
    $BillingReport.AddSection(res!flditemtype, True)
    res1 = modDatabase.$syConn.Exec("select flditemname,flditemcost,flditemunit,fldstatus,fldtarget from tblservicecost where flditemtype=&1 and (fldgroup=&2 or fldgroup like &3) ORDER BY flditemname ASC", res!flditemtype, "%", smode)
    For Each res1
      With asx
        .Add(res1!flditemname)
        If res1!flditemunit Then
          .Add(res1!flditemunit & Space(1) & modReportVar.GetLocaleNumberFormat(res1!flditemcost, gb.Fixed))
        Else
          .Add(modReportVar.GetLocaleNumberFormat(res1!flditemcost, gb.Currency))
        Endif
        .Add(res1!fldtarget)
        .Add(res1!fldstatus)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowLabGroupingListReport() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Particulars"), ("Type"), ("Method")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("LABORATORY TEST GROUPING", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroupname) from tblgrouptest ORDER BY fldgroupname ASC")
  For Each res
    $BillingReport.AddSection(res!fldgroupname, True)
    res1 = modDatabase.$syConn.Exec("select fldtestid,fldtesttype,fldactive from tblgrouptest where fldgroupname=&1 ORDER BY fldtestid ASC", res!fldgroupname)
    For Each res1
      With asx
        .Add(modString.HTMLBlankSpace(3) & res1!fldtestid)
        .Add(res1!fldtesttype)
        .Add(res1!fldactive)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowRadioGroupingListReport() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Particulars"), ("Type"), ("Method")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("RADIOLOGY TEST GROUPING", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroupname) from tblgroupradio ORDER BY fldgroupname ASC")
  For Each res
    $BillingReport.AddSection(res!fldgroupname, True)
    res1 = modDatabase.$syConn.Exec("select fldtestid,fldtesttype,fldactive from tblgroupradio where fldgroupname=&1 ORDER BY fldtestid ASC", res!fldgroupname)
    For Each res1
      With asx
        .Add(modString.HTMLBlankSpace(3) & res1!fldtestid)
        .Add(res1!fldtesttype)
        .Add(res1!fldactive)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowComBillingListReport() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Particulars"), ("Disc%"), ("PatType")], modHelpVariable.$htmlDirectory, " ", "")
  $BillingReport.UserData.Add("TAX AND DISCOUNT SETTINGS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldcomp) from tblextrasetting")
  For Each res
    $BillingReport.AddSection(res!fldcomp, True)
    res1 = modDatabase.$syConn.Exec("select fldid,fldcateg,flddiscpercent,fldcashmode from tblextrasetting where fldcomp=&1", res!fldcomp)
    For Each res1
      With asx
        .Add(res1!fldcateg)
        .Add(modReportVar.GetLocaleNumberFormat(res1!flddiscpercent, -2))
        .Add(res1!fldcashmode)
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPaybleUserListHTML() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Category"), ("Particulars"), ("Share %"), ("Tax %")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("USER SHARES", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(flduserid) from tbluserpay ORDER BY flduserid ASC")                                                                                        ''
  For Each res
    $BillingReport.AddSection(modGeneral.GetUserFullName(res!flduserid) & "[" & res!flduserid & "]", True)

    res1 = modDatabase.$syConn.Exec("select fldid,flditemtype,flditemname,flditemshare,flditemtax from tbluserpay where flduserid=&1 ORDER BY flditemname ASC", res!flduserid)
    For Each res1
      With asx
        .Add(res1!flditemtype)
        .Add(res1!flditemname)
        .Add(modReportVar.GetLocaleNumberFormat(res1!flditemshare, -2))
        .Add(modReportVar.GetLocaleNumberFormat(res1!flditemtax, -2))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowServiceGroupListHTML() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Category"), ("Particulars"), ("QTY")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("SERVICE GROUPS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroup) from tblservicegroup ORDER BY fldgroup ASC")                                                                                        ''
  For Each res
    $BillingReport.AddSection(res!fldgroup, True)

    res1 = modDatabase.$syConn.Exec("select fldid,flditemtype,flditemname,flditemqty from tblservicegroup where fldgroup=&1 ORDER BY flditemname ASC", res!fldgroup)
    For Each res1
      With asx
        .Add(res1!flditemtype)
        .Add(res1!flditemname)
        .Add(modReportVar.GetLocaleNumberFormat(res1!flditemqty, -2))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowPharmacyGroupListHTML() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Category"), ("Particulars"), ("Dose"), ("Freq"), ("Day"), ("QTY"), ("StartHour")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("PHARMACY GROUPS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldmedgroup) from tblproductgroup ORDER BY fldmedgroup ASC")                                                                                        ''
  For Each res
    $BillingReport.AddSection(res!fldmedgroup, True)

    res1 = modDatabase.$syConn.Exec("select fldid,fldroute,flditem,flddose,flddoseunit,fldfreq,fldday,fldqty,fldstart from tblproductgroup where fldmedgroup=&1 ORDER BY flditem ASC", res!fldmedgroup)
    For Each res1
      With asx
        .Add(res1!fldroute)
        .Add(res1!flditem)
        .Add(modReportVar.GetLocaleNumberFormat(res1!flddose, -2) & Space(1) & res1!flddoseunit)
        .Add(res1!fldfreq)
        .Add(modReportVar.GetLocaleNumberFormat(res1!fldday, -2))
        .Add(modReportVar.GetLocaleNumberFormat(res1!fldqty, -2))
        .Add(modReportVar.GetLocaleNumberFormat(res1!fldstart, 0))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowReportGroupListHTML() As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim res1 As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("Category"), ("Particulars"), ("Rate")], modHelpVariable.$htmlDirectory, "", "")

  $BillingReport.UserData.Add("REPORT GROUPS", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select distinct(fldgroup) from tblreportgroup ORDER BY fldgroup ASC")                                                                                        ''
  For Each res
    $BillingReport.AddSection(res!fldgroup, True)

    res1 = modDatabase.$syConn.Exec("select fldid,flditemtype,flditemname from tblreportgroup where fldgroup=&1 ORDER BY flditemname ASC", res!fldgroup)
    For Each res1
      With asx
        .Add(res1!flditemtype)
        .Add(res1!flditemname)
        .Add(modNonMedical.GetCashBillItemCost(res1!flditemname, res1!flditemtype))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next
    With asx
      .Add("")
      .Add("")
      .Add("")
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End

Public Function ShowUserCollection(sid As Long) As String

  Dim $BillingReport As CReportHTML
  Dim res As Result
  Dim asx As New String[0]

  Inc Application.Busy
  $BillingReport = New CReportHTML([("CATEGORY"), ("VALUES")], modHelpVariable.$htmlDirectory, "", "")
  $BillingReport.UserData.Add("USER COLLECTION", "PARAM1")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM2")

  res = modDatabase.$syConn.Exec("select fldcashier,fldfrominvoice,fldtoinvoice,fldbillamt,fldretinvoice,fldretamt,fldrecvamt from tblusercollection where fldid=&1", sid)                                                                                        ''
  For Each res
    With asx
      .Add("User ID")
      .Add(res!fldcashier & " [" & modGeneral.GetUserFullName(res!fldcashier) & "]")
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("From Invoice")
      .Add(res!fldfrominvoice)
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("To Invoice")
      .Add(res!fldtoinvoice)
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("Invoice AMT")
      .Add(modReportVar.GetLocaleNumberFormat(res!fldbillamt, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("Returns")
      .Add(res!fldretinvoice & " TOT AMT: " & modReportVar.GetLocaleNumberFormat(res!fldretamt, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()

    With asx
      .Add("Received AMT")
      .Add(modReportVar.GetLocaleNumberFormat(res!fldrecvamt, gb.Currency))
    End With
    $BillingReport.Add(asx)
    asx.Clear()
  Next
  Dec Application.Busy
  Return $BillingReport.NewHTMLPath()

End
