' Gambas module file

Public Sub VoucherReceipt(BillNo As String, txTitle As String, sPayer As String, sDate As Date, sUser As String)

  ' If modSettings.ShowSettingFromFIle("Invoice/TextFile_Source") And If modSettings.ShowSettingFromFIle("Invoice/TextFile_Source") = "Text" Then
  '   VoucherLINEInvoice(BillNo, txTitle, sTime)
  ' Else
  VoucherHTMLInvoice(BillNo, txTitle, sPayer, sDate, sUser)
  '   Endif

End

Public Sub VoucherHTMLInvoice(BillNo As String, txTitle As String, sPayer As String, sDate As Date, sUser As String)

  Dim $BillingReport As CReportVoucher
  Dim sql As String
  Dim res As Result
  Dim tot As Float

  Dim rsunit As String
  Dim asx As New String[0]

  Inc Application.Busy
  sql = "select fldtime,fldpayername,fldreference,flditemname,fldpayamount,fldpaytype,fldusername,fldtime from tblextrareceipt where fldreference=&1 and fldpayername=&2"                          '''
  res = modDatabase.$myConn.Exec(sql, BillNo, sPayer)                                                                                       ''
  If modBasic.$currency Then
    rsunit = modBasic.$currency
  Else
    rsunit = modString.CurrencySymbol()
  Endif

  If res.Available Then
    $BillingReport = New CReportVoucher([("SNO"), ("PARTICULARS"), ("AMOUNT")], modHelpVariable.$htmlDirectory)

    'Header content
    $BillingReport.UserData.Add(txTitle, "InvoiceType")
    $BillingReport.UserData.Add("VoucherNo: " & BillNo, "PARAM1")
    $BillingReport.UserData.Add("PartyName: " & sPayer, "PARAM2")

    tot = 0
    For Each res
      tot = tot + res!fldpayamount
      With asx
        .Add(CStr(1))
        .Add(res!flditemname)
        .Add(Format(res!fldpayamount, gb.Fixed))
      End With
      $BillingReport.Add(asx)
      asx.Clear()
    Next

    'Footer content
    $BillingReport.UserData.Add(rsunit & Space(1) & Format(tot, gb.Fixed), "TotalAmount")
    $BillingReport.UserData.Add(rsunit & Space(1) & Format(tot, gb.Fixed), "ReceAmount")

    'Amount in words and User info
    $BillingReport.UserData.Add(modString.ConvertMoneyToText(tot), "AmtWord")
    $BillingReport.UserData.Add(sUser, "BillUser")
    $BillingReport.UserData.Add(modDate.GetDateTimeInFormatForAll(sDate, modSettings.ShowSettingFromFIle("Invoice/DateFormat"), ""), "BillDateTime")

  Endif
  Dec Application.Busy

  'Finally make report
  $BillingReport.Preview("InvoiceSize")

End
