' Gambas module file

Public Function DHISBooleanVal(sVal As Boolean) As String

  Dim xx As String

  If sVal = True Then
    xx = "Y"
  Else
    xx = ""
  Endif
  Return xx

End

''====================== Patient related =====================
Public Function DHISPatientrefer(encid As String, sHospCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldrefered from tblamismaster where fldencounterval=&1 and fldhospcode=&2", encid, sHospCode)
  If res.Available Then
    If res!fldrefered Then
      xx = res!fldrefered
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function DHISPatientIDByEnc(encid As String, sHospCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldpatientval from tblamismaster where fldencounterval=&1 and fldhospcode=&2", encid, sHospCode)
  If res.Available Then
    If res!fldpatientval Then
      xx = res!fldpatientval
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function DHISPatientHMISStattus(sPatNo As String, sHospCode As String) As String

  Dim xval As String
  Dim res As Result
  Dim xDate As Date

  If sPatNo Then
    xDate = modDate.GetNepaliFiscalYarStart(Now())
    If xDate Then
      res = modDatabase.$myConn.Limit(1).Exec("select fldencounterval from tblamismaster where fldpatientval=&1 and fldtime>=&2 and fldhospcode=&3", sPatNo, xDate, sHospCode)       '
      If res.Available Then
        xval = "OLD"
      Else
        xval = "NEW"
      Endif
    Else
      res = modDatabase.$myConn.Limit(1).Exec("select fldencounterval from tblamismaster where fldpatientval=&1 and fldhospcode=&2", sPatNo, sHospCode)
      If res.Available Then
        xval = "OLD"
      Else
        xval = "NEW"
      Endif
    Endif
  Else
    xval = "NEW"
  Endif
  Return xval

End
