' Gambas module file

Public Sub CreateDadaBaseDHIS($con As Connection)

  modDBTables.CREATEtblpatientinfo($con)
  CREATEtblamismaster($con)
  CREATEtblamisopd($con)
  CREATEtblamismedicine($con)

  CREATEtblamispanchakarma($con)
  CREATEtblamisksharsutra($con)
  CREATEtblamisyoga($con)
  CREATEtblamismother($con)
  CREATEtblamisgeriatric($con)

  CREATEtblamisoutgeneral($con)
  CREATEtblamisoutgeriatric($con)
  CREATEtblamisoutmother($con)
  CREATEtblamisoutmedicine($con)

  CREATEtblamisadmission($con)
  CREATEtblamisdischarge($con)
  CREATEtblamisemergency($con)

End

Public Sub CREATEtblamismaster($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamismaster") Then
    hTable = $con.Tables.Add("tblamismaster")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldvisit", db.String, 50)

    hTable.Fields.Add("fldrefered", db.String, 150)
    hTable.Fields.Add("flddepart", db.String, 150)
    hTable.Fields.Add("fldexpense", db.Float)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisopd($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisopd") Then
    hTable = $con.Tables.Add("tblamisopd")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldopdnumber", db.String, 150)

    hTable.Fields.Add("fldrefered", db.String, 150)
    hTable.Fields.Add("fldexam", db.String, 250)
    hTable.Fields.Add("fldtreatment", db.String, 250)
    hTable.Fields.Add("flddiagnosis", db.String, 250)
    hTable.Fields.Add("flddiagnocode", db.String, 50)
    hTable.Fields.Add("fldtherapy", db.String, 150)
    hTable.Fields.Add("fldviolence", db.Boolean)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamismedicine($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamismedicine") Then
    hTable = $con.Tables.Add("tblamismedicine")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamispanchakarma($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamispanchakarma") Then
    hTable = $con.Tables.Add("tblamispanchakarma")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisksharsutra($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisksharsutra") Then
    hTable = $con.Tables.Add("tblamisksharsutra")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisyoga($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisyoga") Then
    hTable = $con.Tables.Add("tblamisyoga")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamismother($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamismother") Then
    hTable = $con.Tables.Add("tblamismother")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisgeriatric($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisgeriatric") Then
    hTable = $con.Tables.Add("tblamisgeriatric")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisoutgeneral($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisoutgeneral") Then
    hTable = $con.Tables.Add("tblamisoutgeneral")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisoutgeriatric($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisoutgeriatric") Then
    hTable = $con.Tables.Add("tblamisoutgeriatric")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisoutmother($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisoutmother") Then
    hTable = $con.Tables.Add("tblamisoutmother")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisoutmedicine($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisoutmedicine") Then
    hTable = $con.Tables.Add("tblamisoutmedicine")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldserviceno", db.String, 150)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldpatientval", ["fldpatientval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisadmission($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisadmission") Then
    hTable = $con.Tables.Add("tblamisadmission")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldinpatno", db.String, 150)

    hTable.Fields.Add("fldsource", db.String, 150)
    hTable.Fields.Add("fldward", db.String, 150)
    hTable.Fields.Add("fldexam", db.String, 250)
    hTable.Fields.Add("fldtreatment", db.String, 250)
    hTable.Fields.Add("flddiagnosis", db.String, 250)
    hTable.Fields.Add("flddiagnocode", db.String, 50)
    hTable.Fields.Add("fldtherapy", db.String, 150)
    hTable.Fields.Add("fldpolice", db.Boolean)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisdischarge($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisdischarge") Then
    hTable = $con.Tables.Add("tblamisdischarge")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)
    hTable.Fields.Add("fldinpatno", db.String, 150)

    hTable.Fields.Add("flddoa", db.Date)
    hTable.Fields.Add("flddod", db.Date)
    hTable.Fields.Add("fldward", db.String, 150)
    hTable.Fields.Add("fldtreatment", db.String, 250)
    hTable.Fields.Add("fldtherapy", db.String, 150)
    hTable.Fields.Add("fldcomplication", db.String, 250)
    hTable.Fields.Add("flddiagnosis", db.String, 250)
    hTable.Fields.Add("flddiagnocode", db.String, 50)
    hTable.Fields.Add("fldoutcome", db.String, 150)
    hTable.Fields.Add("flddeathtime", db.String, 150)
    hTable.Fields.Add("flddeathcause", db.String, 250)
    hTable.Fields.Add("fldexemption", db.String, 150)
    hTable.Fields.Add("fldpolice", db.Boolean)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End

Public Sub CREATEtblamisemergency($con As Connection)

  Dim hTable As Table

  If Not $con.Tables.Exist("tblamisemergency") Then
    hTable = $con.Tables.Add("tblamisemergency")
    hTable.Fields.Add("fldid", db.Serial)
    hTable.Fields.Add("fldencounterval", db.String, 150)
    hTable.Fields.Add("fldpatientval", db.String, 150)

    hTable.Fields.Add("fldsource", db.String, 150)
    hTable.Fields.Add("fldbroughtdead", db.Boolean)
    hTable.Fields.Add("fldcomplaints", db.String, 250)
    hTable.Fields.Add("fldexam", db.String, 250)
    hTable.Fields.Add("fldtreatment", db.String, 250)
    hTable.Fields.Add("flddiagnosis", db.String, 250)
    hTable.Fields.Add("flddiagnocode", db.String, 50)
    hTable.Fields.Add("fldobservation", db.String, 250)
    hTable.Fields.Add("flddod", db.Date)
    hTable.Fields.Add("fldoutcome", db.String, 150)
    hTable.Fields.Add("flddeathtime", db.String, 150)
    hTable.Fields.Add("flddeathcause", db.String, 250)
    hTable.Fields.Add("fldexemption", db.String, 150)
    hTable.Fields.Add("fldpolice", db.Boolean)
    hTable.Fields.Add("fldviolence", db.Boolean)

    hTable.Fields.Add("flduserid", db.String, 25)
    hTable.Fields.Add("fldtime", db.Date)
    hTable.Fields.Add("fldsave", db.Boolean)
    hTable.Fields.Add("flduptime", db.Date)
    hTable.Fields.Add("fldhospcode", db.String, 25)
    hTable.Fields.Add("xyz", db.Boolean)
    hTable.PrimaryKey = ["fldid"]
    hTable.Update
    hTable.Indexes.Add(hTable.Name & "_fldencounterval", ["fldencounterval"], False)
    hTable.Indexes.Add(hTable.Name & "_fldtime", ["fldtime"], False)
    modDBApp.AlterMySQLSpecCollationTable($con, hTable.Name)
  Endif

End
