' Gambas module file

Public $ExamItemQualiQuanti As Collection
Public $ExamIDFromSysConst As Collection
Public $ExamCritValue As Collection
Public $ExamItemCategory As Collection
Public $ExamOptionType As Collection
Public $ExamSysOptionType As Collection

Public $ExamDrugHypo As Collection
Public $ExamdrugHyper As Collection
Public $ExamSyndroBrady As Collection
Public $ExamSyndroTachy As Collection

''NOTE: ---------------------- Clinical Scale ----------------------------------------
Public Function SelectExamOptionList(sType As String, sExam As String) As String[]

  Dim res As Result
  Dim opt As String[]

  If sType = "Test" Then
    res = modDatabase.$medConn.Exec("select fldanswer from tbltestoption where fldtestid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Radio" Then
    res = modDatabase.$medConn.Exec("select fldanswer from tblradiooption where fldexamid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Exam" Then
    res = modDatabase.$medConn.Exec("select fldanswer from tblexamoption where fldexamid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Demog" Then
    res = modDatabase.$medConn.Exec("select fldanswer from tbldemogoption where flddemoid=&1 ORDER BY fldindex", sExam)
  Endif
  opt = modFillContainer.GetListFromResult(res)

  Return opt

End

Public Function GetCLinicalScaleOptions(sType As String, sExam As String) As String[]

  Dim res As Result
  Dim opt As String[]

  If sType = "Test" Then
    res = modDatabase.$medConn.Exec("select fldanswertype,fldanswer,fldscale,fldscalegroup from tbltestoption where fldtestid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Radio" Then
    res = modDatabase.$medConn.Exec("select fldanswertype,fldanswer,fldscale,fldscalegroup from tblradiooption where fldexamid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Exam" Then
    res = modDatabase.$medConn.Exec("select fldanswertype,fldanswer,fldscale,fldscalegroup from tblexamoption where fldexamid=&1 ORDER BY fldindex", sExam)
  Endif
  opt = New String[]
  If res.Available Then
    For Each res
      opt.Add(res!fldanswer & "@" & res!fldscale & "@" & res!fldscalegroup)
    Next
  Endif
  Return opt

End

Public Function GetCLinicalScaleGroups(sType As String, sExam As String) As String[]

  Dim res As Result
  Dim opt As String[]

  If sType = "Test" Then
    res = modDatabase.$medConn.Exec("select distinct(fldscalegroup) as col from tbltestoption where fldtestid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Radio" Then
    res = modDatabase.$medConn.Exec("select distinct(fldscalegroup) as col from tblradiooption where fldexamid=&1 ORDER BY fldindex", sExam)
  Else If sType = "Exam" Then
    res = modDatabase.$medConn.Exec("select distinct(fldscalegroup) as col from tblexamoption where fldexamid=&1 ORDER BY fldindex", sExam)
  Endif
  opt = modFillContainer.GetListFromResult(res)
  Return opt

End

'NOTE: -------------------------------------- EXAM Procedure ---------------------------------------
Public Function GetChapterFromRecommendedID(sCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldcategory,flditem from tblstructexam where fldheadcode=&1", sCode)
  If res.Available Then
    If res!flditem Then
      xx = res!fldcategory & "@" & res!flditem
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetSubExamArray(examid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select fldsubexam from tblexamquali where fldexamid=&1", examid)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function GetSubExamOption(headid As String, subheadid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldtanswertype from tblexamquali where fldexamid=&1 and fldsubexam=&2", headid, subheadid)
  If res.Available Then
    If res!fldtanswertype Then
      xx = res!fldtanswertype
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function SysConstFromGetExamID(sExam As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldsysconst from tblexam where fldexamid=&1", sExam)
  If res.Available = True Then
    If res!fldsysconst Then
      xx = res!fldsysconst
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetExamSysOptionType(strSys As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($ExamSysOptionType, strSys)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldoption from tblexam where fldsysconst=&1", strSys)
    If res.Available Then
      If res!fldoption Then
        xx = res!fldoption
        If modBasic.$LocalCache = "Yes" Then
          $ExamSysOptionType.Add(xx, strSys)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetExamtOptionType(strTest As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($ExamOptionType, strTest)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldoption from tblexam where fldexamid=&1", strTest)
    If res.Available Then
      If res!fldoption Then
        xx = res!fldoption
        If modBasic.$LocalCache = "Yes" Then
          $ExamOptionType.Add(xx, strTest)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetExamIDFromSysConst(syscons As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($ExamIDFromSysConst, syscons)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldexamid from tblexam where fldsysconst=&1", syscons)
    If res.Available = True Then
      res.MoveFirst
      If res!fldexamid Then
        xx = res!fldexamid
        If modBasic.$LocalCache = "Yes" Then
          $ExamIDFromSysConst.Add(xx, syscons)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetExamOptionFromSysConst(syscons As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldoption from tblexam where fldsysconst=&1", syscons)
  If res.Available Then
    If res!fldoption Then
      xx = res!fldoption
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetExaminationCategory(test As String) As String

  Dim xx As String
  Dim res As Result

  xx = modHelpVariable.GetCollectionValue($ExamItemCategory, test)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldcategory from tblexam where fldexamid=&1", test)
    If res.Available Then
      If res!fldcategory Then
        xx = res!fldcategory
        If modBasic.$LocalCache = "Yes" Then
          $ExamItemCategory.Add(xx, test)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetExamWithCategory(sExamList As String[]) As String[]

  Dim xx As String
  Dim xval As String[]

  xval = New String[]
  For Each xx In sExamList
    xval.Add(GetExaminationCategory(xx) & "@" & xx)
  Next
  Return xval

End

Public Function MethodsForClinExam(sTestName As String) As String[]

  Dim xx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select distinct(fldmethod) as col from tblexamlimit where fldexamid=&1", sTestName)
  xx = modFillContainer.GetListFromResult(res)
  Return xx

End

Public Function GetExaminationType(strTest As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($ExamItemQualiQuanti, strTest)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldtype from tblexam where fldexamid=&1", strTest)
    If res.Available = True Then
      If res!fldtype Then
        xx = res!fldtype
        If modBasic.$LocalCache = "Yes" Then
          $ExamItemQualiQuanti.Add(xx, strTest)
        Endif
      Else
        xx = "Qualitative"
      Endif
    Else
      xx = "Qualitative"
    Endif
  Endif
  Return xx

End

Public Function GetExamSysName(sExam As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldsysconst from tblexam where fldexamid=&1", sExam)
  If res.Available Then
    If res!fldsysconst Then
      xx = res!fldsysconst
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetCritValueExam(strTest As String) As Float

  Dim res As Result
  Dim xval As Float
  Dim yy As Variant

  yy = modHelpVariable.GetCollectionValue($ExamCritValue, strTest)
  If yy Then
    xval = CFloat(yy)
  Else
    xval = 0
  Endif

  If Not xval Then
    res = modDatabase.$medConn.Exec("select fldcritical from tblexam where fldexamid=&1", strTest)
    If res.Available Then
      If res!fldcritical Then
        xval = res!fldcritical
        If modBasic.$LocalCache = "Yes" Then
          $ExamCritValue.Add(xval, strTest)
        Endif
      Else
        xval = 0
      Endif
    Else
      xval = 0
    Endif
  Endif

  Return xval

End

Public Function GetExamQualiTextReference(txttest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldanswer from tblexamoption where fldexamid=&1 and fldanswertype=&2 ORDER BY fldindex", txttest, "Text Reference")
  If res.Available = True Then
    res.MoveFirst
    If res!fldanswer Then
      xx = res!fldanswer
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetExamUnitWithOutAgeSex(txtexam As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldunit from tblexamlimit where fldexamid=&1", txtexam)                                                              ''
  If res.Available = True Then
    res.MoveFirst
    If res!fldunit Then
      xx = res!fldunit
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function ExamTableValue(sField As String, txtexam As String) As Float

  Dim res1 As Result
  Dim xx As Float

  res1 = modDatabase.$medConn.Exec(Subst("select &1 as fld from tblexam", sField) & " where fldexamid=&1", txtexam)
  If res1.Available Then
    If res1!fld Then
      xx = res1!fld
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End
