' Gambas module file

Public $TestItemQualiQuanti As Collection
Public $TestItemCategory As Collection
Public $TestIDFromSysConst As Collection
Public $TestSpecimen As Collection
Public $TestCritValue As Collection
Public $TestOptionType As Collection

Public $TestDrugHypo As Collection
Public $TestdrugHyper As Collection
Public $TestSyndroBrady As Collection
Public $TestSyndroTachy As Collection

'NOTE:------------------------------- TEST Procedures ------------------------------------------
Public Function GetTestExamEquipments(sType As String) As String[]

  Dim res As Result
  Dim xxx As String[]

  res = modDatabase.$medConn.Exec("select fldmethod from tbltestmethod where fldcateg like &1", sType)
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx

End

Public Function MethodsForLabTest(sTestName As String) As String[]

  Dim xx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select distinct(fldmethod) as col from tbltestlimit where fldtestid=&1", sTestName)
  xx = modFillContainer.GetListFromResult(res)
  Return xx

End

Public Function GetLabTestCategory(test As String) As String

  Dim xx As String
  Dim res As Result

  xx = modHelpVariable.GetCollectionValue($TestItemCategory, test)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldcategory from tbltest where fldtestid=&1", test)
    If res.Available Then
      If res!fldcategory Then
        xx = res!fldcategory
        If modBasic.$LocalCache = "Yes" Then
          $TestItemCategory.Add(xx, test)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetLabTestType(strTest As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($TestItemQualiQuanti, strTest)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldtype from tbltest where fldtestid=&1", strTest)
    If res.Available Then
      If res!fldtype Then
        xx = res!fldtype
        If modBasic.$LocalCache = "Yes" Then
          $TestItemQualiQuanti.Add(xx, strTest)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetLabTestIDFromSysConst(sysCons As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($TestIDFromSysConst, sysCons)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldtestid from tbltest where fldsysconst=&1", sysCons)
    If res.Available = True Then
      res.MoveFirst
      If res!fldtestid Then
        xx = res!fldtestid
        If modBasic.$LocalCache = "Yes" Then
          $TestIDFromSysConst.Add(xx, sysCons)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetLabTestOptionType(strTest As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($TestOptionType, strTest)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldoption from tbltest where fldtestid=&1", strTest)
    If res.Available Then
      If res!fldoption Then
        xx = res!fldoption
        If modBasic.$LocalCache = "Yes" Then
          $TestOptionType.Add(xx, strTest)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetTestSysName(sTest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldsysconst from tbltest where fldtestid=&1", sTest)
  If res.Available Then
    If res!fldsysconst Then
      xx = res!fldsysconst
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetTestSpecimen(testid As String) As String

  Dim xx As String
  Dim res As Result

  xx = modHelpVariable.GetCollectionValue($TestSpecimen, testid)
  If Not xx Then
    res = modDatabase.$medConn.Exec("select fldspecimen from tbltest where fldtestid=&1", testid)
    If res.Available Then
      If res!fldspecimen Then
        xx = res!fldspecimen
        If modBasic.$LocalCache = "Yes" Then
          $TestSpecimen.Add(xx, testid)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetCritValueTest(strTest As String) As Float

  Dim res As Result
  Dim xval As Float
  Dim yy As Variant

  yy = modHelpVariable.GetCollectionValue($TestCritValue, strTest)
  If yy Then
    xval = CFloat(yy)
  Else
    xval = 0
  Endif

  If Not xval Then
    res = modDatabase.$medConn.Exec("select fldcritical from tbltest where fldtestid=&1", strTest)
    If res.Available Then
      If res!fldcritical Then
        xval = res!fldcritical
        If modBasic.$LocalCache = "Yes" Then
          $TestCritValue.Add(xval, strTest)
        Endif
      Else
        xval = 0
      Endif
    Else
      xval = 0
    Endif
  Endif
  Return xval

End

Public Function GetTestWithCategory(sTestList As String[]) As String[]

  Dim xx As String
  Dim xval As String[]

  xval = New String[]
  For Each xx In sTestList
    xval.Add(GetLabTestCategory(xx) & "@" & xx)
  Next
  Return xval

End

Public Function GetSubTestArray(testid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select distinct(fldsubtest) from tbltestquali where fldtestid=&1", testid)
  xx = modFillContainer.GetListFromResult(res)

  Return xx

End

Public Function GetSubTestOption(testid As String, subtest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldtanswertype from tbltestquali where fldtestid=&1 and fldsubtest=&2", testid, subtest)
  If res.Available Then
    If res!fldtanswertype Then
      xx = res!fldtanswertype
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetLabToolTip(txtexam As String) As String

  Dim xx As String
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldcomment from tbltest where fldtestid=&1", txtexam)
  If res.Available Then
    If res!fldcomment Then
      xx = res!fldcomment
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetLabQualiTestTextReference(txttest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldanswer from tbltestoption where fldtestid=&1 and fldanswertype=&2 ORDER BY fldindex", txttest, "Text Reference")
  If res.Available = True Then
    If res!fldanswer Then
      xx = res!fldanswer
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetSubLatTestQualiReference(txttest As String, txtsubtest As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$medConn.Exec("select fldreference from tbltestquali where fldtestid=&1 and fldsubtest=&2", txttest, txtsubtest)
  If res.Available = True Then
    If res!fldreference Then
      xx = res!fldreference
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetTestUnitWithOutAgeSex(strTest As String, strUnit As String) As String

  Dim unt As String
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldsiunit,fldmetunit from tbltestlimit where fldtestid=&1", strTest)
  res.MoveFirst
  If strUnit = "Metric" Then
    If res!fldmetunit Then
      unt = res!fldmetunit
    Else
      unt = ""
    Endif
  Else If strUnit = "SI" Then
    If res!fldsiunit Then
      unt = res!fldsiunit
    Else
      unt = ""
    Endif
  Endif

  Return unt

End

Public Function LabFieldValue(sField As String, strTest As String) As Float

  Dim res As Result
  Dim svalue As Float

  res = modDatabase.$medConn.Exec(Subst("select &1 as fld from tbltest", sField) & " where fldtestid=&1", strTest)
  If res.Available Then
    If res!fld Then
      svalue = res!fld
    Else
      svalue = 0
    Endif
  Else
    svalue = 0
  Endif
  Return svalue

End
