' Gambas module file

'NOTE:------------------------------------- Dose calculation -----------------------------------------
Public Function GetDoseInMg(dos As Float, unt As String, encid As String) As Float

  Dim dosval As Float
  Dim wt As Float
  Dim bsa As Float

  If unt = "mg" Then
    dosval = dos
  Else If unt = "mg/Kg" Then
    wt = modClinic.GetBodyWeight(encid)
    If wt Then
      dosval = dos * wt
    Else
      dosval = 0
    Endif
  Else If unt = "mg/sqm" Then
    bsa = modSysCons.GetCalculationAValue("Body_Surface_Area", encid)
    If bsa Then
      dosval = dos * bsa
    Else
      dosval = 0
    Endif
  Endif

  If dosval Then
    dosval = Round(dosval, -2)
  Endif

  Return dosval

End

Public Function GetDoseInMgFoFromRegID(id As Long, encid As String) As Float

  Dim res As Result
  Dim dose As Float
  Dim xval As Float

  res = modDatabase.$medConn.Exec("select flddose,flddoseunit from tblregimen where fldid=&1", id)
  If res.Available = True Then
    If res!flddose Then
      xval = GetDoseInMg(res!flddose, res!flddoseunit, encid)
      If xval Then
        dose = xval
      Else
        dose = 0
      Endif
    Else
      dose = 0
    Endif
  Else
    dose = 0
  Endif

  Return dose

End

''------------------------------- use tblcode -----------------------------------------
Private Function GetDoseValue(strDose As String, encid As String, stockid As String) As Float

  Dim res As Result
  Dim dos As Float
  Dim dosval As Float
  Dim sql As String
  Dim xval As Float

  sql = strDose & " where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
  res = modDatabase.$medConn.Exec(sql, stockid)
  If res.Available Then
    res.MoveLast
    If res!dose Then
      dos = res!dose
    Else
      dos = 0
    Endif
  Else
    dos = 0
  Endif

  If dos Then
    xval = GetDoseInMg(dos, res!unit, encid)
    If xval Then
      dosval = xval
    Else
      dosval = 0
    Endif
  Endif

  Return dosval

End

Public Function RecommendedDoseDrug(encid As String, stockid As String) As Float

  Dim sql As String
  Dim recdose As Float

  recdose = 0

  If DateDiff(modPatient.GetPatientBirthDay(encid), Now(), gb.Year) <= 12 Then
    sql = "select fldrecpeddose as dose,fldrecpeddoseunit as unit from tblcode"
  Else If DateDiff(modPatient.GetPatientBirthDay(encid), Now(), gb.Year) > 12 Then
    sql = "select fldrecaddose as dose,fldrecaddoseunit as unit from tblcode"
  Endif
  recdose = GetDoseValue(sql, encid, stockid)

  If recdose = 0 Then
    recdose = modMedConstant.GetDrugInitialStrength(stockid)
  Endif

  Return recdose

End

Public Function RecommendedFrequencyDrug(encid As String, stockid As String) As Integer

  Dim sql As String
  Dim res As Result
  Dim recfreq As Integer

  If DateDiff(modPatient.GetPatientBirthDay(encid), Now(), gb.Year) <= 12 Then
    sql = "select fldrecpedfreq as freq from tblcode where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
  Else If DateDiff(modPatient.GetPatientBirthDay(encid), Now(), gb.Year) > 12 Then
    sql = "select fldrecadfreq as freq from tblcode where fldcodename in(select fldcodename from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1))"
  Endif
  res = modDatabase.$medConn.Exec(sql, stockid)
  If res.Available Then
    If res!freq Then
      recfreq = res!freq
    Else
      recfreq = 0
    Endif
  Else
    recfreq = 0
  Endif

  If recfreq = 0 Then
    recfreq = 1
  Endif

  Return recfreq

End
