' Gambas module file

'NOTE:-------------------------Basic Item Treeviews ----------------------------------------
Public Sub CompleteGenericTree(TreeView1 As TreeView, stint As Integer, Optional txtsearch As String)

  Dim sstr1 As String

  Inc Application.Busy
  If txtsearch Then
    sstr1 = "select distinct(fldcodename) as fldparent from tblcode where lower(fldcodename) like &1"
    modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", "", "", "", "", "", LCase(txtsearch) & "%", "", "", "")
  Else
    sstr1 = Subst("select distinct(fldcodename) as fldparent from tblcode ORDER BY fldcodename LIMIT 100 OFFSET &1", stint)
    modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", "", "", "", "", "", "", "", "", "")
  Endif

  Dec Application.Busy

End

Public Sub CompleteMedicineTree(TreeView1 As TreeView, stint As Integer, Optional txtsearch As String)

  Dim sstr1 As String
  Dim sstr2 As String
  Dim sstr3 As String

  Inc Application.Busy
  If txtsearch Then
    sstr1 = "select distinct(fldcodename) as fldparent from tblcode where lower(fldcodename) like &1"
  Else
    sstr1 = Subst("select distinct(fldcodename) as fldparent from tbldrug ORDER BY fldcodename LIMIT 100 OFFSET &1", stint)
  Endif
  sstr2 = "select distinct(flddrug) as fldparent from tbldrug where fldcodename=&1"
  sstr3 = "select distinct(fldbrandid) as fldparent from tblmedbrand where flddrug=&1"
  If txtsearch Then
    modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", sstr2, "", sstr3, "", "", LCase(txtsearch) & "%", "", "", "")
  Else
    modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", sstr2, "", sstr3, "", "", "", "", "", "")
  Endif
  Dec Application.Busy

End

Public Sub CompleteSurgicalTree(TreeView1 As TreeView, stint As Integer, Optional txtsearch As String)

  Dim sstr1 As String
  Dim sstr2 As String
  Dim sstr3 As String

  Inc Application.Busy
  If txtsearch Then
    sstr1 = "select distinct(fldsurgname) as fldparent from tblsurgicalname where lower(fldsurgname) like &1"
  Else
    sstr1 = Subst("select distinct(fldsurgname) as fldparent from tblsurgicalname ORDER BY fldsurgname LIMIT 100 OFFSET &1", stint)
  Endif
  sstr2 = "select distinct(fldsurgid) as fldparent from tblsurgicals where fldsurgname=&1"
  sstr3 = "select distinct(fldbrandid) as fldparent from tblsurgbrand where fldsurgid=&1"
  If txtsearch Then
    modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", sstr2, "", sstr3, "", "", LCase(txtsearch) & "%", "", "", "")
  Else
    modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", sstr2, "", sstr3, "", "", "", "", "", "")
  Endif
  Dec Application.Busy

End

Public Sub CompleteExtraTree(TreeView1 As TreeView, stint As Integer, Optional txtsearch As String)

  Dim sstr1 As String
  Dim sstr2 As String

  Inc Application.Busy
  If txtsearch Then
    sstr1 = "select distinct(fldextraid) as fldparent from tblextra where lower(fldextraid) like &1"
  Else
    sstr1 = Subst("select distinct(fldextraid) as fldparent from tblextra ORDER BY fldextraid LIMIT 100 OFFSET &1", stint)
  Endif
  sstr2 = "select distinct(fldbrandid) as fldparent from tblextrabrand where fldextraid=&1"
  If txtsearch Then
    modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", sstr2, "", "", "", "", LCase(txtsearch) & "%", "", "", "")
  Else
    modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", sstr2, "", "", "", "", "", "", "", "")
  Endif
  Dec Application.Busy

End

Public Sub CompleteFoodTree(TreeView1 As TreeView, stint As Integer)

  Dim sstr1 As String
  Dim sstr2 As String

  Inc Application.Busy
  sstr1 = Subst("select distinct(fldfood) as fldparent from tblfoodlist LIMIT 100 OFFSET &1", stint)
  sstr2 = "select distinct(fldfoodid) as fldparent from tblfoodcontent where fldfood=&1"
  modFillContainer.FillTreeView(modDatabase.$medConn, TreeView1, "", sstr1, "", sstr2, "", "", "", "", "", "", "", "")
  Dec Application.Busy

End

'NOTE: -------------------------Medicines ---------------------------------------
Public Function GetFoodAllList() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldfood from tblfoodlist")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function GetFoodSelectedType(sType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldfoodid from tblfoodcontent where fldfoodtype like &1 and fldfoodcode like &2", sType, "Active")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function GetGenericMedList() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select fldcodename from tblcode")
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function GetBrandList(drugid As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select fldbrand from tblmedbrand where flddrug=&1", drugid)
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function GetIVFluidList() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select flddrug from tbldrug where fldroute=&1", "fluid")
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function GetMedCategoryList() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select flclass from tblmedcategory")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function GetChemicalClassList() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select flclass from tblchemclass")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function GetDosageFormsList() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select flforms from tbldosageforms")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

'NOTE: -------------------------Diagnostics and exam ---------------------------------
Public Function GetEssentialExamList() As String[]

  Dim res As Result
  Dim xxx As String[]

  res = modDatabase.$medConn.Exec("select fldexamid from tblcompexam where fldcomp=&1 and fldcategory=&2", modGeneralMain.compID, "Essential Examinations")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

''Exam
Public Function FillExamQualiOrQuantiCombo(sType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldexamid from tblexam where fldtype like &1 and fldstatus=&2", sType, "Active")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

'''Test
Public Function FillLabTestCombo(txttype As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldtestid from tbltest where fldtype like &1", txttype)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function FillQualQuantiTestNameCombo(strCategory As String, strType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldtestid from tbltest where fldcategory like &1 and fldtype like &2", strCategory, strType)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

''radio
Public Function FillRadioTestCombo(txttype As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldexamid from tblradio where fldtype like &1", txttype)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function FillQualQuantiRadioNameCombo(strCategory As String, strType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldexamid from tblradio where fldcategory like &1 and fldtype like &2", strCategory, strType)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

'other exams/lab
Public Function FillExamCategoryCombo(strType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select distinct(fldcategory) as col from tblexam where fldtype like &1", strType)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function FillTestCategoryCombo(strType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select distinct(fldcategory) as col from tbltest where fldtype like &1", strType)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function GetLabSampleTypeList() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldsampletype from tblsampletype")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function GetTestConditionList() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldtestcondition from tbltestcondition")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function FillClinicalSubClass(sDept As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select distinct(fldsubclass) as col from tblstructexam where fldclass like &1", sDept)
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function FillClinicalReference(subClass As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select distinct(fldreferencee) as col from tblstructexam where fldsubclass=&1", subClass)
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

'NOTE: -------------------------Pathology ------------------------------------------
Public Function GetSymptomAllTypeList() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select fldsymptom from tblsymptoms")
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function GetSymptomSelectedList(sType As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select fldsymptom as col from tblsymptoms where fldcategory like &1", sType)
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function GetAllSYndomeList() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select fldsyndrome from tblsyndromes")
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

''syndromes
Public Function FillSyndromeList(txtCategory As String) As String[]

  Dim xx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldsyndrome from tblsyndromes where fldcategory like &1", txtCategory)
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function GetPathoCategoryList(sType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$medConn.Exec("select flclass from tblpathocategory where fldcategory like &1", sType)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function GetBodyFluidList() As String[]

  Dim res As Result
  Dim xxx As String[]

  res = modDatabase.$medConn.Exec("select fldfluid from tblbodyfluid")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

'Note: --------------------------- Patient Profile------------------
Public Function GetSurNameListFromDB() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select distinct(flditem) as col from tblsurname")
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function GetDistrictListFromDB() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select distinct(flddistrict) as col from tblmunicipals")
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function GetRelationListFromDB() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$medConn.Exec("select distinct(flditem) as col from tblrelations")
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

'NOTE: -------------------------------- Key Release Procedures For ComboBox ----------------------------------
''medicine on key release
Public Sub GenericMedicineList(ComboBox1 As ComboBox)

  Dim res As Result
  Dim sql As String
  Dim textToCursor As String
  Dim textPosition As Integer

  textPosition = ComboBox1.Pos
  textToCursor = Mid(ComboBox1.Text, 1, textPosition)

  If Key.Code = Key.BackSpace Then
    ComboBox1.Clear
  Else
    If Key.Code = Key.Down Then
      sql = "select fldcodename as col from tblcode where lower(fldcodename) like &1"
      res = modDatabase.$medConn.Exec(sql, LCase(textToCursor) & "%")
      modFillContainer.FillComboBox(ComboBox1, res)
      ComboBox1.Popup
    Endif
  Endif

End

''surgicals on key release
Public Sub FillSurgicalListCombo(ComboBox1 As ComboBox, categ As String)

  Dim sql As String
  Dim res As Result
  Dim textToCursor As String
  Dim textPosition As Integer

  textPosition = ComboBox1.Pos
  textToCursor = Mid(ComboBox1.Text, 1, textPosition)

  If Key.Code = Key.BackSpace Then
    ComboBox1.Clear
  Else
    If Key.Code = Key.Down Then
      sql = "select fldsurgname as col from tblsurgicalname where fldsurgcateg=&1 and lower(fldsurgname) like &2"
      res = modDatabase.$medConn.Exec(sql, categ, LCase(textToCursor) & "%")
      modFillContainer.FillComboBox(ComboBox1, res)
      ComboBox1.Popup
    Endif
  Endif

End

'''------------------------------------Variables added manually -----------------------------------------------------------------
Public Function RouteMedicine() As String[]

  Dim xxx As String[]

  xxx = ["oral", "liquid", "fluid", "injection", "resp", "topical", "eye/ear", "anal/vaginal"]
  Return xxx

End

Public Function RouteNonMedicine() As String[]

  Dim xxx As String[]

  xxx = ["suture", "msurg", "ortho", "extra"]
  Return xxx

End

Public Function InjSubRouteList() As String[]

  Dim xxx As String[]

  xxx = ["IVpush", "CIV", "IIV", "SC", "IM", "IT", "IDer", "ICar", "ISyn"]
  Return xxx

End

Public Function ComboRoute() As String[]

  Dim xxx As String[]

  xxx = New String[]
  xxx.Insert(RouteMedicine())
  xxx.Insert(RouteNonMedicine())
  Return xxx

End

Public Function InpatientRoute() As String[]

  Dim xxx As String[]

  xxx = New String[]
  xxx.Insert(RouteMedicine())
  xxx.Insert(RouteNonMedicine())
  xxx.Insert(InjSubRouteList())
  Return xxx

End

Public Function ClinicalRoute() As String[]

  Dim xxx As String[]

  xxx = New String[]
  xxx.Insert(RouteMedicine())
  xxx.Insert(InjSubRouteList())
  Return xxx

End

Public Function FrequencyCombo() As String[]

  Dim xxx As String[]

  xxx = ["1", "2", "3", "4", "6", "stat", "PRN", "SOS", "AM", "HS", "Pre", "Post", "Hourly", "Alt day", "Weekly", "Biweekly", "Triweekly", "Monthly", "Yearly", "Tapering"]                                                    ''
  Return xxx

End

Public Function FillCLinicalOptionCombo() As String[]

  Dim xxx As String[]

  xxx = ["No Selection", "Single Selection", "Dichotomous", "Multiple Selection", "Clinical Scale", "Text Addition", "Visual Input", "Drug Sensitivity", "Text Table", "Single Column", "Dual Columns", "Left and Right", "Date Time", "Qualitative", "Quantitative", "Percent Sum"]                               ''
  Return xxx

End

Public Function FillCLinicalLessOptionCombo() As String[]

  Dim xxx As String[]

  xxx = ["No Selection", "Single Selection", "Dichotomous", "Clinical Scale", "Text Addition", "Text Reference", "Visual Input", "Custom Components", "Fixed Components", "Left and Right", "Date Time"]                               ''
  Return xxx

End

Public Function FillClinSepOptionCombo() As String[]

  Dim xxx As String[]

  xxx = ["No Selection", "Single Selection", "Dichotomous", "Multiple Selection", "Left and Right", "Date Time", "Text Table", "Qualitative", "Sys Constant"]                               ''
  Return xxx

End

Public Function AgeGroupListShortAll() As String[]

  Dim xx As String[]

  xx = ["Neonate", "Infant", "Toddler", "Children", "Adolescent", "Adult", "Elderly", "All Age"]
  Return xx

End

'''-------------------------------------- Functions -------------------------------------------------------------------------------
Public Function KidneyCondiToGFRFirst(condi As String) As Float

  Dim xx As Float

  If condi = "severely impaired" Then
    xx = 0
  Else If condi = "moderately impaired" Then
    xx = 10
  Else If condi = "mildly impaired" Then
    xx = 20
  Endif
  Return xx

End

Public Function KidneyCondiToGFRLast(condi As String) As Float

  Dim xx As Float

  If condi = "severely impaired" Then
    xx = 9.9
  Else If condi = "moderately impaired" Then
    xx = 19.9
  Else If condi = "mildly impaired" Then
    xx = 49.9
  Endif
  Return xx

End

Public Function GetSurgicalCategory(surgid As String) As String

  Dim categ As String
  Dim res As Result

  res = modDatabase.$medConn.Exec("select fldsurgcateg from tblsurgicals where fldsurgid=&1", surgid)
  If res.Available Then
    If res!fldsurgcateg Then
      categ = res!fldsurgcateg
    Else
      categ = ""
    Endif
  Else
    categ = ""
  Endif
  Return categ

End

Public Function GetRouteFromItem(flditem As String, strType As String) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String

  If strType = "Extra Items" Then
    xx = "extra"
  Else If strType = "Medicines" Then
    sql = "select fldroute from tbldrug where flddrug in(select flddrug from tblmedbrand where fldbrandid=&1)"
    res = modDatabase.$medConn.Exec(sql, flditem)
    If res.Available Then
      If res!fldroute Then
        xx = res!fldroute
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Else If strType = "Surgicals" Then
    sql = "select fldsurgcateg from tblsurgicals where fldsurgid in(select fldsurgid from tblsurgbrand where fldbrandid=&1)"
    res = modDatabase.$medConn.Exec(sql, flditem)
    If res.Available Then
      If res!fldsurgcateg Then
        xx = res!fldsurgcateg
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif                   ''
  Endif

  Return xx

End

'NOTE: ----------------------- System related variables ------------------------------
Public Function FillExportType() As String[]

  Dim xxx As String[]

  xxx = New String[]
  xxx.Add("Text File")
  If System.Exist("gnumeric") = True Then
    xxx.Add("Gnumeric")
  Endif
  If System.Exist("localc") = True Then
    xxx.Add("LibreOffice Calc")
  Endif
  If System.Exist("lowriter") = True Then
    xxx.Add("LibreOffice Writer")
  Endif
  If System.Exist("abiword") = True Then
    xxx.Add("Abiword")
  Endif

  Return xxx

End

''=========================== Clinical Access List =================================
Public Function CompleteAccessList() As String[]

  Dim xx As String[]

  xx = New String[]
  xx.Add("Presenting Complaints")
  xx.Add("Cause of Admission")
  xx.Add("Patient History")
  xx.Add("Clinical Findings")
  xx.Add("Body Weight")
  xx.Add("Body Height")
  xx.Add("Input Output")
  xx.Add("Progress Notes")
  xx.Add("Clinical Notes")
  xx.Add("Therapeutic Planning")
  xx.Add("Symptoms Addition")

  xx.Add("Provisional Diagnosis")
  xx.Add("Final Diagnosis")
  xx.Add("Drug Allergy")
  xx.Add("Hepatic Status")
  xx.Add("Pregnancy Status")

  xx.Add("Laboratory Request")
  xx.Add("Radiology Request")
  xx.Add("Pharmacy Request")
  xx.Add("Products Request")

  xx.Add("Equipments Used")
  xx.Add("Procedure Plan")
  xx.Add("Minor Procedure")
  xx.Add("Consultation Plan")
  xx.Add("PO Intake Plan")
  xx.Add("Monitoring Plan")
  xx.Add("Extra Procedure Plan")

  xx.Add("Demographics")
  xx.Add("General Images")
  xx.Add("DICOM Images")
  xx.Add("PACS Images")
  xx.Add("Medicine Dosing")
  xx.Add("Event Timing")
  xx.Add("Vaccination Form")

  xx.Add("Triage Examinations")
  xx.Add("Essential Examinations")
  xx.Add("Structured Examination")
  xx.Add("Complete Examination")

  xx.Add("Change Status")
  xx.Add("Bed Assignment")

  xx.Add("Procedure Addition")
  xx.Add("Procedure Components")
  xx.Add("Procedure Summary")

  xx.Add("PreOperative Discussion")
  xx.Add("Preoperative Examination")
  xx.Add("Preoperative Note")
  xx.Add("Preoperative Item Used")

  xx.Add("Procedure Parameters")
  xx.Add("Procedure Note")
  xx.Add("Procedure Item Used")
  xx.Add("Procedure Personnel")
  xx.Add("Procedure Instruments")

  xx.Add("Anesthesia Parameters")
  xx.Add("Anesthesia Note")
  xx.Add("Anesthesia Item Used")

  xx.Add("Postoperative Examination")
  xx.Add("Postoperative Note")
  xx.Add("Postoperative Item Used")

  xx.Add("Delivery Addition")
  xx.Add("Pre Delivery Examination")
  xx.Add("On Delivery Examination")
  xx.Add("Post Delivery Examination")
  xx.Add("Newborn Examination")
  xx.Add("Delivery Item Used")

  Return xx

End
