' Gambas module file

Public $APIMonth As String

Public Function GetDHISJson(xFixVar As Variant[], xTableVar As Variant[]) As Variant[]

  Dim xVar As Variant[]
  Dim aColl As Collection

  Dim xFixArry As String[]
  Dim xLabel As String
  Dim xColm As String

  Dim rowColl As Collection
  Dim xval As Variant

  xVar = New Variant[]

  For Each xFixArry In xFixVar
    xLabel = xFixArry[0]
    xColm = xFixArry[1]
    For Each rowColl In xTableVar
      If rowColl["0"] = xLabel Then
        xval = rowColl[xColm]

        If xFixArry[3] And If xFixArry[2] Then
          aColl = New Collection
          aColl.Add(xLabel & "-" & xColm, "_comment")
          aColl.Add(xFixArry[3], "categoryOptionCombo")
          aColl.Add(xFixArry[2], "dataElement")
          aColl.Add(CStr(xval), "value")
          xVar.Add(aColl)
        Endif

      Endif
    Next
  Next

  Return xVar

End

''for IP morbidity and mortality
Public Function GetDHISJsonDiagno(xFixVar As Variant[], xTableVar As Variant[]) As Variant[]

  Dim xVar As Variant[]
  Dim aColl As Collection

  Dim xFixArry As String[]
  Dim xLabel As String
  Dim xColm As String

  Dim rowColl As Collection
  Dim xval As Variant

  xVar = New Variant[]

  For Each xFixArry In xFixVar
    xLabel = xFixArry[0]
    xColm = xFixArry[1]
    For Each rowColl In xTableVar
      xval = rowColl[xColm]

      If xFixArry[3] And If xFixArry[2] Then
        aColl = New Collection
        aColl.Add(xLabel & "-" & xColm, "_comment")
        aColl.Add(xFixArry[3], "categoryOptionCombo")
        aColl.Add(xFixArry[2], "dataElement")
        aColl.Add(CStr(xval), "value")
        xVar.Add(aColl)
      Endif

    Next
  Next

  Return xVar

End

''only for safe motherhood complications
Public Function GetDHISJsonSecond(xFixVar As Variant[], xTableVar As Variant[]) As Variant[]

  Dim xVar As Variant[]
  Dim aColl As Collection

  Dim xFixArry As String[]
  Dim xLabel As String
  Dim xColm As String

  Dim rowColl As Collection
  Dim xval As Variant

  xVar = New Variant[]

  For Each xFixArry In xFixVar
    xLabel = xFixArry[0]
    xColm = xFixArry[1]
    For Each rowColl In xTableVar
      If rowColl["1"] = xLabel Then
        xval = rowColl[xColm]

        If xFixArry[3] And If xFixArry[2] Then
          aColl = New Collection
          aColl.Add(xLabel & "-" & xColm, "_comment")
          aColl.Add(xFixArry[3], "categoryOptionCombo")
          aColl.Add(xFixArry[2], "dataElement")
          aColl.Add(CStr(xval), "value")
          xVar.Add(aColl)
        Endif

      Endif
    Next
  Next

  Return xVar

End

''======================== DHIS TAGS ==========================
''dataelement,optioncombo
Public Function SetTableCellTags(sChapter As String, Optional sCategory As String) As Variant[]

  Dim aVar As Variant[]
  Dim xArr As String[]

  aVar = New Variant[]

  Return aVar

End
