' Gambas module file

Public $AppHeightRatio As Float
Public $AppWidthRatio As Float
Public $AppScaleFactor As Float

Public LocalJan As String
Public LocalFeb As String
Public LocalMar As String
Public LocalApr As String
Public LocalMay As String
Public LocalJun As String
Public LocalJul As String
Public LocalAug As String
Public LocalSep As String
Public LocalOct As String
Public LocalNov As String
Public LocalDec As String

Public Local0 As String
Public Local1 As String
Public Local2 As String
Public Local3 As String
Public Local4 As String
Public Local5 As String
Public Local6 As String
Public Local7 As String
Public Local8 As String
Public Local9 As String

Public $GlobalUserID As String
Public $PatientImageSplash As Integer
Public $PatientEncLock As String
Public $PatInfoEncrypt As Boolean
Public $InfoMusic As String
Public $InfoMusicVol As Integer
Public $dictPathList As String[]
Public $dictadvPath As String
Public $currency As String
Public $centUnit As String
Public $NumFormat As String '
Public $NumFont As String '
Public $DateFormat As String
Public $DateContent As String
Public $PatNameFormat As String
Public $PatAddressFormat As String
Public $PatAgeFormat As String
Public $AbnFormat As String
Public $CommentColumn As String
Public $SearchBothSide As Boolean
Public $ErrorLastString As String

Public $RegistrationEncLock As Integer
Public $DischargeEncLock As Integer

Public $ItemListFormat As String
Public $browserFormat As String
Public $MultiMediaFormat As String
Public $LockInTime As String
Public $SamplingYear As Integer
Public $ShowDayMedReport As String
Public $SignaPopUp As String
Public $ShowQuantiMedReport As String
Public $ShowQualiMedReport As String
Public $ShowScaleMedFormat As String

Public $FormPicture As String
Public $FormBackColor As String
Public $FormForeColor As String
Public $FormLeftAdv As String
Public $FormRightAdv As String
Public $FormLeftWidth As Integer

Public $DataOddBackColor As Integer
Public $DataOddForeColor As Integer
Public $DataEvenBackColor As Integer
Public $DataEvenForeColor As Integer

Public $LabelForeColor As Integer
Public $LabelTextFont As String

Public $DebugMode As Boolean
Public $HelpMode As String
Public $LocalCache As String
Public $DumpCache As String
Public $BalloonDelay As Integer
Public $MedRepoBody As String
Public $HighLightColor As Integer
Public $AutoEncPrefix As String
Public $AutoEncSuffix As String
Public $AutoReadNotice As String
Public $ScannerList As String[]

''barcode settings
Public $BarCodeFormatString As String
Public $BarCodeDisplayText As String
Public $BarCodeWidth As Float
Public $BarCodeWhiteSpace As Integer
Public $BarCodeForeGround As Integer
Public $BarCodeBackGround As Integer
Public $BarCodePixelSize As Integer
Public $BarCodeImageDPI As Integer
Public $BarCodeMarginWidth As Integer

''Patient Prefixes
Public $HospCode As String
Public $PatNoPrefix As String
Public $EncIdPrefix As String
Public $BookNoPrefix As String
Public $PatNoLen As Integer
Public $EncIdLen As Integer
Public $BookNoLen As Integer

''patient data entry
Public $regF1Dispensing As String
Public $regF1Sampling As String
Public $regF1Clinic As String

Public $WardAdmission As String
Public $TriageMode As String
Public $SymptomScale As String

''for registration
Public $regF1Cashier As String
Public $RegistEssAddress As String
Public $RegistEssDistrict As String
Public $RegistEssAge As String
Public $RegistEssGuardian As String
Public $RegistEssRelation As String
Public $RegistEssContact As String
Public $RegistEssEMail As String
Public $RegistEssCode As String

Public $RegistDataRepo As String
Public $RegistGridFormat As String
Public $RegistAutoWebcam As String
Public $RegistAutoDemograph As String
Public $RegistAutoBarcode As String
Public $RegistAutoSticker As String
Public $RegistAutoPrescription As String

Public $AutoDiaryNo As String
Public $AutoConsultation As String
Public $AutoConsultLock As String
Public $AutoRegistBilling As String
Public $AutoRegistNoBillDay As String
Public $RegistQuotaQueMode As String
Public $AllowPatNoEntry As String
Public $RegistScheduleMode As String
Public $RegistDefaultMode As String
Public $RegistFixMode As String
Public $RegistDiscountType As String
Public $RegistDiscountMode As String
Public $RegistDiscountFix As String
Public $RegistLockToQuota As String

Public $LockSurName As String
Public $LockDistrict As String
Public $LockAddress As String
Public $LockRelation As String
Public $LockConsultant As String

Public $SurNameList As String[]
Public $AddressList As String[]
Public $DistrictList As String[]
Public $RelationList As String[]

Public $RegGender As String
Public $RegDistrict As String
Public $RegRelation As String

Public $RegStartTime As Date
Public $ResEndTime As Date

Public $ClinChartDataCurve As String
Public $ClinChartShowPoint As String
Public $ClinChartShowLabel As String
Public $ClinChartShowUpper As String
Public $ClinChartShowLower As String
Public $ClinChartShowNormal As String
Public $ClinChartShowHourGrid As String
Public $ClinChartShowGridLabel As String

Public $ClinColorData As Integer
Public $ClinColorPoints As Integer
Public $ClinColorLabel As Integer
Public $ClinColorUpper As Integer
Public $ClinColorLower As Integer
Public $ClinColorNormal As Integer
Public $ClinColorHourGrid As Integer
Public $ClinColorDayGrid As Integer
Public $ClinColorGridLabel As Integer
Public $ClinChartHourDiff As Integer

''inventory chart
Public $InvChShowTitle As String
Public $InvChShowXLabel As String
Public $InvChShowYLabel As String
Public $InvChDataGrouping As String
Public $InvChQTYGrouping As String
Public $InvChAMTGrouping As String
Public $InvChartLeft As Integer
Public $InvChartTop As Integer
Public $InvChartRight As Integer
Public $InvChartBottom As Integer

Public $ChartExecStat As String
Public $StatConfInterval As Float

''billing setting
Public $BillFixBilling As String
Public $BillDiscMethod As String
Public $BillTaxMethod As String
Public $BillTaxFixedValue As Float
Public $BillDiscFixedValue As Float
Public $BillFixTax As String
Public $BillFixDisc As String
Public $BillFixTaxSaved As String
Public $BillFixDiscSaved As String
Public $BillFixSumTax As String
Public $BillFixSumDisc As String
Public $BillDefaultBilling As String
Public $BillInvReprintForm As String
Public $BillPunchItems As String
Public $BillReturnByEnc As String
Public $BillItemMode As String
Public $BillCashOption As String
Public $BillReturnOption As String
Public $BillAutoReturn As String
Public $BillLockAdmitted As String
Public $BillIsolateCashBilling As String
Public $BillEditPayable As String

Public $BillServiceSection As String
Public $BillTestSection As String
Public $BillEquipSection As String
Public $BillRadioSection As String
Public $BillProcSection As String
Public $BillOtherSection As String

Public $AutoBillTest As String
Public $AutoBillService As String
Public $AutoBillProcedure As String
Public $AutoBillEquipment As String
Public $AutoBillRadio As String
Public $AutoBillPharmacy As String
Public $AutoBillOthers As String
Public $AutoBillSaveZero As String

''invoicing
Public $BillEditRate As String
Public $BillEditRateSaved As String
Public $BillAmtRounding As String
Public $BillRestrictOwn As String
Public $BillTargetPharmacy As String
Public $BillPrintTime As String
Public $BillAfterPrintDisplay As String
Public $BillWithInvoicePrint As String
Public $BillMedicineFormat As String
Public $BillExpiryFormat As String

''Lists for General Billings
Public $BillDiscountType As String[]
Public $BillBillingMode As String[]
Public $BillBankList As String[]
Public $ReferenceSubs As Collection

''medicine setting
Public $MedErrorEnable As String
Public $MedErrorPopUp As String
Public $MedDoseRecommend As String
Public $MedDiseaseDose As String
Public $MedLogRecommend As String

''inventory
Public $SkipExpiry As String
Public $OutOrder As String
Public $SurgProfit As Float
Public $MedProfit As Float

''Serial Port
Public $SerialPort As String
Public $SerialClear As String
Public $ShowStorage As String
Public $HideStorage As String

''Global Clinic
Public $ClinicDisableCompo As String[]
Public $FixedDepartment As String
Public $LockToOwnDepart As String
Public $LockToOwnProcedure As String
Public $LockExamList As String
Public $LockSymptomList As String
Public $LockDiagnosisList As String
Public $LockDelTypeInput As String
Public $LockProcedCompInput As String
Public $LockAnesTechnInput As String
Public $DisplayExamOption As String
Public $DisplayQualiArea As String

Public $DefaultTestList As String
Public $DefaultRadioList As String
Public $ProvDiagnosisRule As String
Public $FinalDiagnosisRule As String
Public $DefaultDiagnoGroup As String

Public $CommRefRange As String
Public $CommSensSpec As String
Public $CommMedEffect As String
Public $CommCauseSyndro As String
Public $CommInterpret As String

Public $EBMAge As String
Public $EBMAgeRange As Integer
Public $EBMGender As String
Public $EBMDistrict As String
Public $EBMMethod As String
Public $EBMDiagno As String
Public $EBMEthnic As String

''custom report sources
Public $CustomImage As String
Public $CustomDataQR As String
Public $CustomUser As String
Public $CustomDemog As String
Public $CustomTest As String
Public $CustomExam As String
Public $CustomRadio As String
Public $CustomCalc As String
Public $CustomSQLQuery As String
Public $CustomScript As String
Public $CustomExec As String

Public $CustomConsult As String
Public $CustomBirth As String
Public $CustomHistory As String
Public $CustomSelExam As String
Public $CustomProcedure As String

''General values
Public $UploadMaxSize As String
Public $UploadEncryptPDF As String

''Print Log
Public $ReportLogPrint As String
Public $ReportLogHTML As String
Public $ReportLogPDF As String
Public $ReportLogExport As String
Public $ReportLogSend As String
Public $ReportLogSave As String
Public $ReportLogFTP As String

''Pictures
Public $PictureChecked As Picture
Public $PictureUnchecked As Picture
Public $PictureWarning As Picture

''Alerts
Public $AlertRadioList As String
Public $AlertTestList As String

''Laboratory/Radiology
Public $LabWorkSheet As String
Public $LabBarCode As String
Public $LabBarPrint As String
Public $LabBarPath As String
Public $LabSamplingFrom As String
Public $LabSamplingComp As String
Public $LabReportingFrom As String
Public $LabReportingComp As String
Public $LabAutoSampNo As String
Public $LabSamplePrefix As String

''Dispensing Label settings
Public $DispLabelAutoEnable As String
Public $DispLabelRegimen As String

''FTP Setting for manual Report Saving
Public $RepoManHost As String
Public $RepoManFolder As String
Public $RepoManUser As String
Public $RepoManPass As String

''SMTP setting for e mail
Public $emailSMTPHost As String
Public $emailSMTPUser As String
Public $emailSMTPPass As String
Public $emailSMTPFrom As String

''Sys Constants
Public $sysCustomList As String[]
Public $sysExamList As String[]
Public $sysTestList As String[]
Public $sysRadioList As String[]
Public $DemogList As String[]

''Lists for Clinical Desks
Public $GenericMedName As String[]   'modmedicine GetGenericMedList()
Public $ClinBodyFluidAll As String[]  'modmedicine  GetBodyFluidList()
Public $IPDDepartmentsAll As String[]  ' modMisc.GetDepartmentWithBedList()
Public $ClinComplaintComp As String[]
Public $ClinFindingComp As String[]
Public $ClinEssentialComp As String[]
Public $ClinNursingComp As String[]
Public $ClinTriageComp As String[]
Public $ClinDischargeComp As String[]

Public $ClinComplaintCompGrouped As String[]
Public $ClinFindingCompGrouped As String[]
Public $ClinDiagnoChapterGrouped As String[]

''General List
Public $PayUserList As String[]
Public $ReferUserList As String[]
Public $OPConsulUserList As String[]
Public $IPConsultUserList As String[]
Public $SignaUserList As String[]
Public $ExpoRepoUser As Boolean
Public $SuperUser As Boolean

Public $AllCompList As String[]
Public $DemogAccList As String[]
Public $RepQuerytable As String[]
Public $RepoOptionList As String[]

''General variables
Public Sub LoadGeneralVariables()

  Dim xbaloon As String
  Dim xsplash As String
  Dim highcolor As String
  Dim xscale As String
  Dim xleft As String
  Dim xpatencrp As String
  Dim fnRatio As Float
  Dim xkeyaval As Boolean

  DebugString("Loading Application variables")
  ''general
  xscale = modSettings.ShowSettingFromFIle("Application/DesktopScale")
  If xscale Then
    $AppScaleFactor = CInt(xscale) / 8
  Else
    $AppScaleFactor = Desktop.Scale / 8
  Endif
  fnRatio = (Application.Font.TextWidth("a") / Font["Ubuntu,11"].TextWidth("a"))
  $AppWidthRatio = fnRatio * (Desktop.Resolution / 96)
  $AppHeightRatio = fnRatio * (Desktop.Resolution / 96)

  $PictureChecked = Picture["icons/checked.png"]
  $PictureUnchecked = Picture["icons/unchecked.png"]
  $PictureWarning = Picture["icon:/small/warning"]

  $GlobalUserID = modSettings.ShowSettingFromFIle("GeneralSettings/GlobalUser")
  $NumFormat = modSettings.ShowSettingFromFIle("ReportFormat/NumberFormat")
  $NumFont = modSettings.ShowSettingFromFIle("ReportFormat/NumberFont")
  $currency = modString.GetCurrency()
  $centUnit = modString.GetCentUnit()
  $DateFormat = modSettings.ShowSettingFromFIle("ReportFormat/DateFormat")
  $DateContent = modSettings.ShowSettingFromFIle("ReportFormat/DateContent")
  LoadLocalMonths()
  LoadLocalNumbers()
  GetReferenceCodeColl()

  ''for reports
  $PatNameFormat = modSettings.ShowSettingFromFIle("ReportFormat/NameFormat")
  $PatAddressFormat = modSettings.ShowSettingFromFIle("ReportFormat/AddressFormat")
  $CommentColumn = modSettings.ShowSettingFromFIle("ReportFormat/CommentColumn")
  $PatAgeFormat = modSettings.ShowSettingFromFIle("ReportFormat/ReportBody_AgeFormat")
  $AbnFormat = modSettings.ShowSettingFromFIle("ReportFormat/ReportBody_AbnormalMark")
  $MedRepoBody = modSettings.ShowSettingFromFIle("ClinicalReport/BodyFormat")
  $ShowDayMedReport = modSettings.ShowSettingFromFIle("ClinicalReport/ShowDay_Report")
  $SignaPopUp = modSettings.ShowSettingFromFIle("ReportFormat/FooterPopUp")
  $ShowQuantiMedReport = modSettings.ShowSettingFromFIle("ClinicalReport/QuantiValue_Format")
  $ShowQualiMedReport = modSettings.ShowSettingFromFIle("ClinicalReport/QualiValue_Format")
  $ShowScaleMedFormat = modSettings.ShowSettingFromFIle("ClinicalReport/ScaleValue_Format")
  UploadDataSetting()
  LoadCustomReportSource()
  LoadManualFTPSett()
  LoadSMTPEmailSetting()
  ReportLogSetting()

  ''user wise
  $FormPicture = modSettings.ShowUserWiseSettingFromFIle("AppSetting_FormPicture")
  $FormBackColor = modSettings.ShowUserWiseSettingFromFIle("AppSetting_FormBackColor")
  $FormForeColor = modSettings.ShowUserWiseSettingFromFIle("AppSetting_FormForeColor")
  $LockInTime = modSettings.ShowUserWiseSettingFromFIle("AppSetting_LockTime")
  $ItemListFormat = modSettings.ShowUserWiseSettingFromFIle("AppSetting_ItemView")
  $browserFormat = modSettings.ShowUserWiseSettingFromFIle("AppSetting_ReportBrowser")
  $MultiMediaFormat = modSettings.ShowUserWiseSettingFromFIle("AppSetting_MediaPlayerFormat")
  LoadInfoMusic()
  GetDictionaryPathAll()

  $PatientEncLock = modGlobalSetting.ShowSettingFromDB("TableLock/EncounterLock")
  xpatencrp = modGlobalSetting.ShowSettingFromDB("PatientInfo/Encryption")
  If xpatencrp = "Yes" Then
    $PatInfoEncrypt = True
  Else
    $PatInfoEncrypt = False
  Endif
  GetEncounterLockParam()
  $AutoEncPrefix = modSettings.ShowSettingFromFIle("GeneralSettings/AutoEncounterPrefix")
  $AutoEncSuffix = modSettings.ShowSettingFromFIle("GeneralSettings/AutoEncounterSuffix")
  $AutoReadNotice = modSettings.ShowSettingFromFIle("GeneralSettings/ReadNotification")
  xsplash = modSettings.ShowUserWiseSettingFromFIle("AppSetting_ImageSplash")
  If xsplash Then
    $PatientImageSplash = CInt(xsplash)
  Else
    $PatientImageSplash = 0
  Endif

  xbaloon = modSettings.ShowSettingFromFIle("GeneralSettings/BalloonDelay")
  If xbaloon Then
    $BalloonDelay = CInt(xbaloon)
  Else
    $BalloonDelay = 200
  Endif

  highcolor = modSettings.ShowSettingFromFIle("GeneralSettings/HighLightColor")
  If highcolor Then
    $HighLightColor = CInt(highcolor)
  Else
    $HighLightColor = Color.DarkRed
  Endif

  DataViewRowCOlor()
  LoadBarCodeSettingAll()
  LabelDesignSetting()
  $LocalCache = modSettings.ShowSettingFromFIle("GeneralSettings/LocalDataCaching_Enable")
  $DumpCache = modSettings.ShowSettingFromFIle("GeneralSettings/LocalDataCaching_Dump")
  EnableCollectionCache()
  $HelpMode = modSettings.ShowSettingFromFIle("GeneralSettings/HelpMode")
  xleft = modSettings.ShowSettingFromFIle("Application/LeftPanel_Width")
  If xleft Then
    $FormLeftWidth = CInt(xleft)
  Endif

  $PayUserList = modGeneral.CategoricalUserList("fldpayable")
  $ReferUserList = modGeneral.CategoricalUserList("fldreferral")
  $OPConsulUserList = modGeneral.CategoricalUserList("fldopconsult")
  $IPConsultUserList = modGeneral.CategoricalUserList("fldipconsult")
  $SignaUserList = modGeneral.CategoricalUserList("fldsigna")
  $ExpoRepoUser = modGeneral.GetExpoReportUser(modGeneralMain.$lbluser)
  $SuperUser = modGeneral.GetSuperUser(modGeneralMain.$lbluser)

  $AllCompList = modGeneral.CompList()
  $RepQuerytable = modReportVar.SQLAllowTableList()
  $RepoOptionList = modMisc.GetReportOptionList()
  modPatient.GetPatientNoPrefixes()

End

Private Sub GetEncounterLockParam()

  Dim xregist As String
  Dim regisday As Integer
  Dim xdisch As String
  Dim discday As Integer

  xregist = modGlobalSetting.ShowSettingFromDB("EncounterLock/Registration_" & modHelpVariable.$LogInCategory)
  If xregist = "Yes" Then
    regisday = modGlobalSetting.ShowSettingFromDB("EncounterLock/Registration_Days")
    If regisday Then
      $RegistrationEncLock = CInt(regisday)
    Else
      $RegistrationEncLock = 0
    Endif
  Else
    $RegistrationEncLock = 0
  Endif

  xdisch = modGlobalSetting.ShowSettingFromDB("EncounterLock/DischargeExit_" & modHelpVariable.$LogInCategory)
  If xdisch = "Yes" Then
    discday = modGlobalSetting.ShowSettingFromDB("EncounterLock/DischargeExit_Days")
    If discday Then
      $DischargeEncLock = CInt(discday)
    Else
      $DischargeEncLock = 0
    Endif
  Else
    $DischargeEncLock = 0
  Endif

End

Private Sub LoadBarCodeSettingAll()

  Dim xwid As String
  Dim xwhite As String
  Dim xfore As String
  Dim xback As String

  Dim xpixel As String
  Dim xdpi As String
  Dim xmargin As String

  $BarCodeFormatString = modSettings.ShowSettingFromFIle("BarCodeFormat/FormatString")
  $BarCodeDisplayText = modSettings.ShowSettingFromFIle("BarCodeFormat/DisplayText")

  xwid = modSettings.ShowSettingFromFIle("BarCodeFormat/Width")
  If xwid Then
    $BarCodeWidth = CFloat(xwid)
  Endif
  xwhite = modSettings.ShowSettingFromFIle("BarCodeFormat/WhiteSpace")
  If xwhite Then
    $BarCodeWhiteSpace = CInt(xwhite)
  Endif
  xfore = modSettings.ShowSettingFromFIle("BarCodeFormat/ForeGround")
  If xfore Then
    $BarCodeForeGround = CInt(xfore)
  Endif
  xback = modSettings.ShowSettingFromFIle("BarCodeFormat/BackGround")
  If xback Then
    $BarCodeBackGround = CInt(xback)
  Endif

  xpixel = modSettings.ShowSettingFromFIle("BarCodeFormat/PixelSize")
  If xpixel Then
    $BarCodePixelSize = CInt(xpixel)
  Endif
  xdpi = modSettings.ShowSettingFromFIle("BarCodeFormat/ImageDPI")
  If xdpi Then
    $BarCodeImageDPI = CInt(xdpi)
  Endif
  xmargin = modSettings.ShowSettingFromFIle("BarCodeFormat/MarginWidth")
  If xmargin Then
    $BarCodeMarginWidth = CInt(xmargin)
  Endif

End

Private Sub LoadManualFTPSett()

  $RepoManHost = modSettings.ShowSettingFromFIle("RemoteFTP/HostName")
  $RepoManFolder = modSettings.ShowSettingFromFIle("RemoteFTP/FTPFolder")
  $RepoManUser = UnBase64(modSettings.ShowSettingFromFIle("RemoteFTP/UserName"))
  $RepoManPass = UnBase64(modSettings.ShowSettingFromFIle("RemoteFTP/PassWord"))

End

Public Sub LoadSMTPEmailSetting()

  $emailSMTPHost = modSettings.ShowSettingFromFIle("SMTPEmail/HostName")
  $emailSMTPUser = modSettings.ShowSettingFromFIle("SMTPEmail/UserName")
  $emailSMTPPass = UnBase64(modSettings.ShowSettingFromFIle("SMTPEmail/PassWord"))
  $emailSMTPFrom = modSettings.ShowSettingFromFIle("SMTPEmail/SenderName")

End

Private Sub LoadInfoMusic()

  Dim xmusic As String
  Dim xmusicvol As String

  xmusic = modSettings.ShowUserWiseSettingFromFIle("AppSetting_InformMusic")
  If xmusic Then
    If Exist(xmusic) Then
      $InfoMusic = xmusic
    Else
      $InfoMusic = ""
    Endif
  Else
    $InfoMusic = ""
  Endif

  xmusicvol = modSettings.ShowUserWiseSettingFromFIle("AppSetting_VolumeMusic")
  If xmusicvol Then
    $InfoMusicVol = CInt(xmusicvol)
  Endif

End

Private Sub GetDictionaryPathAll()

  Dim xdict As String

  $dictadvPath = modSettings.ShowSettingFromFIle("AdvancedDictionary/Path")
  xdict = modSettings.ShowUserWiseSettingFromFIle("AppSetting_Dictionary")
  If xdict And If Exist(xdict) Then
    $dictPathList = modString.GetStringArrayFromFile(xdict)
  Else
    $dictPathList = New String[]
  Endif

End

Public Sub LoadLocalMonths()

  Dim sForm As String
  Dim sFile As String

  Dim hFile As File
  Dim sLine As String
  Dim linWord As String[]

  If $DateFormat Then
    If $DateFormat = "BS Date" Then
      sForm = "BikramSambat"
    Endif
  Endif
  If sForm Then
    sFile = modHelpVariable.$localesDirectory &/ sForm
    If Exist(sFile) Then
      hFile = Open sFile
      DebugString("Open File " & sFile)
      For Each sLine In hFile.Lines
        linWord = Split(sLine, ",")
        If linWord[0] = "01" Then
          LocalJan = linWord[1]
        Else If linWord[0] = "02" Then
          LocalFeb = linWord[1]
        Else If linWord[0] = "03" Then
          LocalMar = linWord[1]
        Else If linWord[0] = "04" Then
          LocalApr = linWord[1]
        Else If linWord[0] = "05" Then
          LocalMay = linWord[1]
        Else If linWord[0] = "06" Then
          LocalJun = linWord[1]
        Else If linWord[0] = "07" Then
          LocalJul = linWord[1]
        Else If linWord[0] = "08" Then
          LocalAug = linWord[1]
        Else If linWord[0] = "09" Then
          LocalSep = linWord[1]
        Else If linWord[0] = "10" Then
          LocalOct = linWord[1]
        Else If linWord[0] = "11" Then
          LocalNov = linWord[1]
        Else If linWord[0] = "12" Then
          LocalDec = linWord[1]
        Endif
      Next
      hFile.Close()
    Endif

  Endif

End

Public Sub LoadLocalNumbers()

  If $NumFont Then
    Local0 = modApplication.ConvertToLocalNumber("0", $NumFont)
    Local1 = modApplication.ConvertToLocalNumber("1", $NumFont)
    Local2 = modApplication.ConvertToLocalNumber("2", $NumFont)
    Local3 = modApplication.ConvertToLocalNumber("3", $NumFont)
    Local4 = modApplication.ConvertToLocalNumber("4", $NumFont)
    Local5 = modApplication.ConvertToLocalNumber("5", $NumFont)
    Local6 = modApplication.ConvertToLocalNumber("6", $NumFont)
    Local7 = modApplication.ConvertToLocalNumber("7", $NumFont)
    Local8 = modApplication.ConvertToLocalNumber("8", $NumFont)
    Local9 = modApplication.ConvertToLocalNumber("9", $NumFont)
  Endif

End

Private Sub LabelDesignSetting()

  Dim xback As String

  xback = modSettings.ShowUserWiseSettingFromFIle("AppSetting_TextLabelForeColor")
  If xback Then
    $LabelForeColor = CInt(xback)
  Endif
  $LabelTextFont = modSettings.ShowUserWiseSettingFromFIle("AppSetting_TextLabelFont")

End

Private Sub DataViewRowCOlor()

  Dim xevenback As String
  Dim xevenfore As String
  Dim xoddback As String
  Dim xoddfore As String

  xevenback = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DataViewEvenRowBackColor")
  If xevenback Then
    $DataEvenBackColor = CInt(xevenback)
  Else
    $DataEvenBackColor = Color.White
  Endif

  xevenfore = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DataViewEvenRowForeColor")
  If xevenfore Then
    $DataEvenForeColor = CInt(xevenfore)
  Else
    $DataEvenForeColor = Color.Black
  Endif

  xoddback = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DataViewOddRowBackColor")
  If xoddback Then
    $DataOddBackColor = CInt(xoddback)
  Else
    $DataOddBackColor = Color.White
  Endif

  xoddfore = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DataViewOddRowForeColor")
  If xoddfore Then
    $DataOddForeColor = CInt(xoddfore)
  Else
    $DataOddForeColor = Color.Black
  Endif

End

Private Sub EnableCollectionCache()

  DebugString("Activating Local Cache")
  modPatient.$PatNumData = New Collection
  modPatient.$PatNameData = New Collection
  modPatient.$PatGenderData = New Collection
  modPatient.$PatDOBData = New Collection
  modPatient.$PatContactData = New Collection
  modPatient.$PatAddressData = New Collection
  modPatient.$PatDistrictData = New Collection
  modPatient.$PatCodeData = New Collection
  modPatient.$PatRelationData = New Collection
  modPatient.$PatGuardData = New Collection
  modPatient.$PatEMailData = New Collection

  modPatient.$PatVisType = New Collection
  modPatient.$PatBillMode = New Collection
  modPatient.$PatDORegData = New Collection
  modPatient.$PatDOAData = New Collection
  modPatient.$PatRegDepartData = New Collection
  modPatient.$PatDODData = New Collection
  modPatient.$PatDOFollData = New Collection

  modFixLab.$TestItemQualiQuanti = New Collection
  modFixLab.$TestItemCategory = New Collection
  modFixLab.$TestIDFromSysConst = New Collection
  modFixLab.$TestSpecimen = New Collection
  modFixLab.$TestCritValue = New Collection
  modFixLab.$TestOptionType = New Collection

  modFixLab.$TestDrugHypo = New Collection
  modFixLab.$TestdrugHyper = New Collection
  modFixLab.$TestSyndroBrady = New Collection
  modFixLab.$TestSyndroTachy = New Collection

  modFixClinic.$ExamItemQualiQuanti = New Collection
  modFixClinic.$ExamIDFromSysConst = New Collection
  modFixClinic.$ExamCritValue = New Collection
  modFixClinic.$ExamItemCategory = New Collection
  modFixClinic.$ExamOptionType = New Collection
  modFixClinic.$ExamSysOptionType = New Collection

  modFixClinic.$ExamDrugHypo = New Collection
  modFixClinic.$ExamdrugHyper = New Collection
  modFixClinic.$ExamSyndroBrady = New Collection
  modFixClinic.$ExamSyndroTachy = New Collection

  modFixRadio.$RadioItemCategory = New Collection
  modFixRadio.$RadioIDFromSysConst = New Collection
  modFixRadio.$RadioOptionType = New Collection

  modGeneral.$UserNameData = New Collection
  modGeneral.$UserCodeData = New Collection
  modGeneral.$EthnicCodeData = New Collection
  modDate.$LocalDateData = New Collection
  modExternal.$ExecValueColl = New Collection

  modFixPatho.$SymptomCategory = New Collection

  modNonMedical.$CashItemTarget = New Collection
  modNonMedical.$CashItemID = New Collection
  modNonMedical.$CashItemGroup = New Collection

  modMedConstant.$MedBrandToGeneric = New Collection
  modMedConstant.$MedCodeFromStock = New Collection
  modMedConstant.$MedDrugFromStock = New Collection
  modMedConstant.$MedCodeFromDrug = New Collection
  modMedConstant.$MedSensiFromStock = New Collection
  modMedConstant.$MedCategFromStock = New Collection
  modMedConstant.$MedRiskFromStock = New Collection
  modMedConstant.$MedStrengthStock = New Collection
  modMedConstant.$MedNarcoticStock = New Collection

  modPharmLabel.$PharmPackVolume = New Collection
  modPharmLabel.$PharmPackVolUnit = New Collection

  modStock.$ItemStorageCodeData = New Collection
  modStock.$ItemStockNameData = New Collection
  modStock.$ItemStockBatchData = New Collection
  modStock.$ItemStockExpData = New Collection
  modStock.$SurgiNameFromStock = New Collection
  modStock.$ExtraNameFromStock = New Collection

End

''--------------------- General functions ----------------------------------------
Public Sub DebugString(sText As String)

  If $DebugMode = True Then
    If MMain.$IsGUIApp = True Then
      Error Application.Name & ": " & Format(Now(), gb.GeneralDate) & " : " & sText
    Else
      Print Application.Name & ": " & Format(Now(), gb.GeneralDate) & " : " & sText
    Endif
  Endif

End

''---------------------------  Variables used outside of this module ----------------------------
''for cashier billing
Public Sub LoadCashierBillingSettings()

  Dim xtaxval As String
  Dim xdiscval As String

  $BillFixBilling = modGlobalSetting.ShowSettingFromDB("CashBilling/FixBilling")
  $BillDiscMethod = modGlobalSetting.ShowSettingFromDB("CashBilling/DiscMode")
  $BillTaxMethod = modGlobalSetting.ShowSettingFromDB("CashBilling/TaxMode")

  xtaxval = modGlobalSetting.ShowSettingFromDB("CashBilling/FixedTaxValue")
  If xtaxval Then
    $BillTaxFixedValue = CFloat(xtaxval)
  Else
    $BillTaxFixedValue = 0
  Endif
  xdiscval = modGlobalSetting.ShowSettingFromDB("CashBilling/FixedDiscValue")
  If xdiscval Then
    $BillDiscFixedValue = CFloat(xdiscval)
  Else
    $BillDiscFixedValue = 0
  Endif

  $BillFixTax = modGlobalSetting.ShowSettingFromDB("CashBilling/FixTax")
  $BillFixDisc = modGlobalSetting.ShowSettingFromDB("CashBilling/FixDisc")
  $BillFixTaxSaved = modGlobalSetting.ShowSettingFromDB("CashBilling/FixTaxSaved")
  $BillFixDiscSaved = modGlobalSetting.ShowSettingFromDB("CashBilling/FixDiscSaved")
  $BillFixSumTax = modGlobalSetting.ShowSettingFromDB("CashBilling/FixSumTax")
  $BillFixSumDisc = modGlobalSetting.ShowSettingFromDB("CashBilling/FixSumDisc")
  $BillDefaultBilling = modSettings.ShowSettingFromFIle("BillingSettings/DefaultMode")
  $BillInvReprintForm = modGlobalSetting.ShowSettingFromDB("CashBilling/InvoiceReprintFormat")
  $BillPunchItems = modGlobalSetting.ShowSettingFromDB("CashBilling/GroupPunchingItems")
  $BillReturnByEnc = modGlobalSetting.ShowSettingFromDB("CashBilling/ReturnByEncID")
  $BillItemMode = modSettings.ShowSettingFromFIle("CashBilling/ItemMode")
  $BillAutoReturn = modGlobalSetting.ShowSettingFromDB("CashBilling/AutoReturn")

  $BillCashOption = modGlobalSetting.ShowSettingFromDB("BillingOption/CashierBilling")
  $BillReturnOption = modGlobalSetting.ShowSettingFromDB("BillingOption/CashierReturn")
  $BillLockAdmitted = modGlobalSetting.ShowSettingFromDB("BillingOption/LockAdmitted")
  $BillIsolateCashBilling = modGlobalSetting.ShowSettingFromDB("BillingOption/IsolateCashBilling")
  $BillEditPayable = modGlobalSetting.ShowSettingFromDB("SavedBillingEntry/EditPayable")

  $BillServiceSection = modGlobalSetting.ShowSettingFromDB("CashBilling/Section_Service")
  $BillEquipSection = modGlobalSetting.ShowSettingFromDB("CashBilling/Section_Equipment")
  $BillRadioSection = modGlobalSetting.ShowSettingFromDB("CashBilling/Section_Radio")
  $BillTestSection = modGlobalSetting.ShowSettingFromDB("CashBilling/Section_Test")
  $BillProcSection = modGlobalSetting.ShowSettingFromDB("CashBilling/Section_Procedure")
  $BillOtherSection = modGlobalSetting.ShowSettingFromDB("CashBilling/Section_Others")

End

Public Sub LoadAutoBillingOptions()

  $AutoBillTest = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/Test")
  $AutoBillService = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/Service")
  $AutoBillProcedure = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/Procedure")
  $AutoBillEquipment = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/Equipment")
  $AutoBillRadio = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/Radio")
  $AutoBillPharmacy = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/Pharmacy")
  $AutoBillOthers = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/Others")
  $AutoBillSaveZero = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/AutoSaveZero")

End

Public Sub LoadInvoicingSetting()

  $BillEditRate = modGlobalSetting.ShowSettingFromDB("CashBilling/EditRate")
  $BillEditRateSaved = modGlobalSetting.ShowSettingFromDB("CashBilling/EditRateSaved")
  $BillAmtRounding = modGlobalSetting.ShowSettingFromDB("CashBilling/AmountRounding")
  $BillRestrictOwn = modGlobalSetting.ShowSettingFromDB("CashBilling/RestrictToOwnItems")
  $BillTargetPharmacy = modGlobalSetting.ShowSettingFromDB("CashBilling/TargetPharmacyStock")
  $BillPrintTime = modGlobalSetting.ShowSettingFromDB("CashBilling/BillPrintTime")
  $BillAfterPrintDisplay = modSettings.ShowSettingFromFIle("BillingSettings/AfterPrintAutoDisplay")

  $BillWithInvoicePrint = modSettings.ShowSettingFromFIle("Invoice/PostInvoicePrint")

  $BillMedicineFormat = modSettings.ShowSettingFromFIle("Invoice/MedicineName")
  $BillExpiryFormat = modSettings.ShowSettingFromFIle("Invoice/ShowExpiry")

End

Public Sub LoadBillingLists()

  $BillDiscountType = modNonMedical.FillDiscountCombo()
  $BillBillingMode = modNonMedical.FillCashModeCombo()
  $BillBankList = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select fldbankname as col from tblbanks"))

End

''collection for reference subscript
Private Sub GetReferenceCodeColl()

  Dim res As Result

  $ReferenceSubs = New Collection
  res = modDatabase.$myConn.Exec("select fldinvcode,fldinvsub from tblinvid")
  If res.Available Then
    For Each res
      $ReferenceSubs.Add(res!fldinvsub, res!fldinvcode & ":" & CStr(Date()))
    Next
  Endif

End

''For Registration
Public Sub LoadRegistrationSetting()

  $regF1Cashier = modGlobalSetting.ShowSettingFromDB("GeneralSettings/RegistrationAccess_CashierForm")

  $RegistEssAddress = modGlobalSetting.ShowSettingFromDB("RegistrationEssential/Address")
  $RegistEssDistrict = modGlobalSetting.ShowSettingFromDB("RegistrationEssential/District")
  $RegistEssAge = modGlobalSetting.ShowSettingFromDB("RegistrationEssential/Age")
  $RegistEssGuardian = modGlobalSetting.ShowSettingFromDB("RegistrationEssential/Guardian")
  $RegistEssRelation = modGlobalSetting.ShowSettingFromDB("RegistrationEssential/Relation")
  $RegistEssContact = modGlobalSetting.ShowSettingFromDB("RegistrationEssential/Contact")
  $RegistEssEMail = modGlobalSetting.ShowSettingFromDB("RegistrationEssential/EMail")
  $RegistEssCode = modGlobalSetting.ShowSettingFromDB("RegistrationEssential/ExtCode")

  $AutoDiaryNo = modGlobalSetting.ShowSettingFromDB("Admission/AutoDiaryNo")
  $AutoConsultation = modGlobalSetting.ShowSettingFromDB("AutoConsultation/Registration")
  $AutoConsultLock = modGlobalSetting.ShowSettingFromDB("AutoConsultation/Registration_Lock")
  $AutoRegistBilling = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/Registration")
  $AutoRegistNoBillDay = modGlobalSetting.ShowSettingFromDB("AutoIPBilling/NoBillHours")
  $RegistQuotaQueMode = modGlobalSetting.ShowSettingFromDB("ConsultationQuotaQue/Mode")
  $AllowPatNoEntry = modGlobalSetting.ShowSettingFromDB("GeneralSettings/Registration_AllowPatNoInput")

  $RegistScheduleMode = modGlobalSetting.ShowSettingFromDB("RegBillingGroup/ScheduleMode")
  $RegistDefaultMode = modGlobalSetting.ShowSettingFromDB("RegBillingGroup/DefaultMode")
  $RegistFixMode = modGlobalSetting.ShowSettingFromDB("RegBillingGroup/FixMode")

  $RegistDiscountType = modGlobalSetting.ShowSettingFromDB("CashRegistration/DiscountMode_Type")
  $RegistDiscountMode = modGlobalSetting.ShowSettingFromDB("CashRegistration/Default_DiscountMode")
  $RegistDiscountFix = modGlobalSetting.ShowSettingFromDB("CashRegistration/FixDiscountMode")
  $RegistLockToQuota = modSettings.ShowSettingFromFIle("CashRegistration/LimitRegistration")

  $RegistDataRepo = modSettings.ShowSettingFromFIle("RegistrationData/UseRepository")
  $RegistGridFormat = modSettings.ShowSettingFromFIle("RegistrationForm/GridViewFormat")
  $RegistAutoWebcam = modSettings.ShowSettingFromFIle("RegistrationWebCam/AutoStart")
  $RegistAutoDemograph = modSettings.ShowSettingFromFIle("RegistrationForm/Auto_Demographics")
  $RegistAutoBarcode = modSettings.ShowSettingFromFIle("RegistrationPrint/Barcode")
  $RegistAutoSticker = modSettings.ShowSettingFromFIle("RegistrationPrint/Sticker")
  $RegistAutoPrescription = modSettings.ShowSettingFromFIle("RegistrationForm/AutoPrint")
  $LockSurName = modSettings.ShowSettingFromFIle("RegistrationForm/SurnameList_Lock")
  $LockDistrict = modSettings.ShowSettingFromFIle("RegistrationForm/DistrictList_Lock")
  $LockAddress = modSettings.ShowSettingFromFIle("RegistrationForm/AddressList_Lock")
  $LockRelation = modSettings.ShowSettingFromFIle("RegistrationForm/RelationList_Lock")
  $LockConsultant = modSettings.ShowSettingFromFIle("RegistrationForm/ConsultantList_Mode")

  $RegGender = modSettings.ShowSettingFromFIle("RegistrationForm/DefaultGender")
  $RegDistrict = modSettings.ShowSettingFromFIle("RegistrationForm/DefaultDistrict")
  $RegRelation = modSettings.ShowSettingFromFIle("RegistrationForm/DefaultRelation")
  $DemogAccList = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select flddemoid as col from tblaccdemograp"))

  FillSurnameList()
  FillAddressList()
  FillDistrictList()
  FillRelationList()

End

Public Sub FillSurnameList()

  Dim xsurnamelist As String

  xsurnamelist = modSettings.ShowSettingFromFIle("RegistrationForm/SurnameList")
  If xsurnamelist Then
    If Exist(xsurnamelist) Then
      $SurNameList = modString.GetStringArrayFromFile(xsurnamelist)
    Endif
  Else
    $SurNameList = modMedicine.GetSurNameListFromDB()
  Endif

End

Public Sub FillAddressList()

  Dim xaddlist As String

  xaddlist = modSettings.ShowSettingFromFIle("RegistrationForm/AddressList")
  If xaddlist Then
    If Exist(xaddlist) Then
      $AddressList = modString.GetStringArrayFromFile(xaddlist)
    Endif
  Endif

End

Public Sub FillDistrictList()

  Dim xdistlist As String

  xdistlist = modSettings.ShowSettingFromFIle("RegistrationForm/DistrictList")
  If xdistlist Then
    If Exist(xdistlist) Then
      $DistrictList = modString.GetStringArrayFromFile(xdistlist, True)
    Endif
  Else
    $DistrictList = modMedicine.GetDistrictListFromDB()
  Endif

End

Public Sub FillRelationList()

  Dim xrelationlist As String

  xrelationlist = modSettings.ShowSettingFromFIle("RegistrationForm/RelationList")
  If xrelationlist Then
    If Exist(xrelationlist) Then
      $RelationList = modString.GetStringArrayFromFile(xrelationlist, True)
    Endif
  Else
    $RelationList = modMedicine.GetRelationListFromDB()
  Endif

End

Public Sub RegistrationFormTime()

  Dim xsta As String
  Dim xend As String

  xsta = modGlobalSetting.ShowSettingFromDB("EnableRegistrationForm/StartTime")
  If xsta
    If Val(xsta) Then
      $RegStartTime = Val(xsta)
    Else
      $RegStartTime = ""
    Endif
  Else
    $RegStartTime = ""
  Endif

  xend = modGlobalSetting.ShowSettingFromDB("EnableRegistrationForm/EndTime")
  If xend Then
    If Val(xend) Then
      $ResEndTime = Val(xend)
    Else
      $ResEndTime = ""
    Endif
  Else
    $ResEndTime = ""
  Endif

End

''for patient data entry (except cashier)
Public Sub DisplayPatientSettings()

  $regF1Dispensing = modGlobalSetting.ShowSettingFromDB("GeneralSettings/RegistrationAccess_DispensingForm")
  $regF1Sampling = modGlobalSetting.ShowSettingFromDB("GeneralSettings/RegistrationAccess_SamplingForm")
  $regF1Clinic = modGlobalSetting.ShowSettingFromDB("GeneralSettings/RegistrationAccess_ClinicForm")

  $WardAdmission = modGlobalSetting.ShowSettingFromDB("Admission/WardAdmission")
  $TriageMode = modGlobalSetting.ShowSettingFromDB("IPClinic/TriageColorValue")
  $SymptomScale = modGlobalSetting.ShowSettingFromDB("IPClinic/SymptomCauseScale")

  modFixPatho.LoadTriageValues()

End

''for Clinical charts
Public Sub LoadClinicalChartSetting()

  Dim xshdata As String
  Dim xshpoint As String
  Dim xshlabel As String
  Dim xuprange As String
  Dim xlowrange As String
  Dim xnormrange As String
  Dim xhourgrid As String
  Dim xdaygrid As String
  Dim xlabelgrid As String
  Dim xhourdiff As String

  $ClinChartDataCurve = modSettings.ShowSettingFromFIle("ClinicalChart/DataCurve")
  $ClinChartShowPoint = modSettings.ShowSettingFromFIle("ClinicalChart/ShowPoints")
  $ClinChartShowLabel = modSettings.ShowSettingFromFIle("ClinicalChart/ShowLabels")
  $ClinChartShowUpper = modSettings.ShowSettingFromFIle("ClinicalChart/ShowUpperRange")
  $ClinChartShowLower = modSettings.ShowSettingFromFIle("ClinicalChart/ShowLowerRange")
  $ClinChartShowNormal = modSettings.ShowSettingFromFIle("ClinicalChart/ShowNormalRange")
  $ClinChartShowHourGrid = modSettings.ShowSettingFromFIle("ClinicalChart/ShowHourGrid")
  $ClinChartShowGridLabel = modSettings.ShowSettingFromFIle("ClinicalChart/ShowGridLabel")

  xshdata = modSettings.ShowSettingFromFIle("ClinicalChart/ShowData_Color")
  If xshdata Then
    $ClinColorData = CInt(xshdata)
  Endif

  xshpoint = modSettings.ShowSettingFromFIle("ClinicalChart/ShowPoints_Color")
  If xshpoint Then
    $ClinColorPoints = CInt(xshpoint)
  Endif

  xshlabel = modSettings.ShowSettingFromFIle("ClinicalChart/ShowLabels_Color")
  If xshlabel Then
    $ClinColorLabel = CInt(xshlabel)
  Endif

  xuprange = modSettings.ShowSettingFromFIle("ClinicalChart/ShowUpperRange_Color")
  If xuprange Then
    $ClinColorUpper = CInt(xuprange)
  Endif

  xlowrange = modSettings.ShowSettingFromFIle("ClinicalChart/ShowLowerRange_Color")
  If xlowrange Then
    $ClinColorLower = CInt(xlowrange)
  Endif

  xnormrange = modSettings.ShowSettingFromFIle("ClinicalChart/ShowNormalRange_Color")
  If xnormrange Then
    $ClinColorNormal = CInt(xnormrange)
  Endif

  xhourgrid = modSettings.ShowSettingFromFIle("ClinicalChart/ShowHourGrid_Color")
  If xhourgrid Then
    $ClinColorHourGrid = CInt(xhourgrid)
  Endif

  xdaygrid = modSettings.ShowSettingFromFIle("ClinicalChart/ShowDayGrid_Color")
  If xdaygrid Then
    $ClinColorDayGrid = CInt(xdaygrid)
  Endif

  xlabelgrid = modSettings.ShowSettingFromFIle("ClinicalChart/ShowGridLabel_Color")
  If xlabelgrid Then
    $ClinColorGridLabel = CInt(xlabelgrid)
  Endif

  ''hour diff
  xhourdiff = modSettings.ShowSettingFromFIle("ClinicalChart/HourDifference")
  If xhourdiff Then
    $ClinChartHourDiff = CInt(xhourdiff)
  Endif

End

''for medicine review and dose recommendation
Public Sub MedicineDoseSetting()

End

''for inventory
Public Sub InventorySettings()

  Dim xmed As String
  Dim xsurg As String

  $SerialPort = modSettings.ShowSettingFromFIle("SerialPort/Device")
  $SerialClear = modSettings.ShowSettingFromFIle("SerialPort/ClearString")
  $ShowStorage = modSettings.ShowSettingFromFIle("InventorySetting/ShowStorageLocation")
  $HideStorage = modSettings.ShowSettingFromFIle("InventorySetting/HideStorageLocation")

  $SkipExpiry = modSettings.ShowSettingFromFIle("InventorySetting/SkipExpiry")
  $OutOrder = modSettings.ShowSettingFromFIle("InventorySetting/OutOrder")

  xsurg = modSettings.ShowSettingFromFIle("DefaultProfit/Surgicals")
  If xsurg Then
    $SurgProfit = CFloat(xsurg)
  Endif

  xmed = modSettings.ShowSettingFromFIle("DefaultProfit/Medicines")
  If xmed Then
    $MedProfit = CFloat(xmed)
  Endif

End

Public Sub InventoryChartSettings()

  $InvChShowTitle = modSettings.ShowSettingFromFIle("InventoryChart/ShowTitle")
  $InvChShowXLabel = modSettings.ShowSettingFromFIle("InventoryChart/ShowXLabel")
  $InvChShowYLabel = modSettings.ShowSettingFromFIle("InventoryChart/ShowYLabel")
  $InvChDataGrouping = modSettings.ShowSettingFromFIle("InventoryChart/DataGrouping")
  $InvChQTYGrouping = modSettings.ShowSettingFromFIle("InventoryChart/QTYGrouping")
  $InvChAMTGrouping = modSettings.ShowSettingFromFIle("InventoryChart/AMTGrouping")
  $ChartExecStat = modSettings.ShowSettingFromFIle("InventoryChart/Statistics")
  ResizeInventoryChartSet()

End

Public Sub ResizeInventoryChartSet()

  If modSettings.ShowSettingFromFIle("InventoryChart/ChartLeft") Then
    $InvChartLeft = CInt(modSettings.ShowSettingFromFIle("InventoryChart/ChartLeft"))
  Endif
  If modSettings.ShowSettingFromFIle("InventoryChart/ChartTop") Then
    $InvChartTop = CInt(modSettings.ShowSettingFromFIle("InventoryChart/ChartTop"))
  Endif
  If modSettings.ShowSettingFromFIle("InventoryChart/ChartRight") Then
    $InvChartRight = CInt(modSettings.ShowSettingFromFIle("InventoryChart/ChartRight"))
  Endif
  If modSettings.ShowSettingFromFIle("InventoryChart/ChartBottom") Then
    $InvChartBottom = CInt(modSettings.ShowSettingFromFIle("InventoryChart/ChartBottom"))
  Endif

End

Public Sub StatisticalParameters()

  Dim xconf As String

  xconf = modSettings.ShowSettingFromFIle("StatisticsSetting/ConfidenceInterval")
  If xconf Then
    $StatConfInterval = CFloat(xconf)
  Else
    $StatConfInterval = 0.95
  Endif

End

''for clinics
Public Sub GlobalClinicSettings()

  $ClinicDisableCompo = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select fldaccess as col from tblclinicentry where flduserid=&1 and fldstatus=&2 and (fldcomp=&3 or fldcomp=&4)", modGeneralMain.$lbluser, "Inactive", modGeneralMain.compID, "%"))                                            ''
  $FixedDepartment = modGlobalSetting.ShowSettingFromDB("IPClinic/FixedDepartment")
  $LockToOwnDepart = modGlobalSetting.ShowSettingFromDB("IPClinic/LockToOwnDepartment")
  $LockToOwnProcedure = modGlobalSetting.ShowSettingFromDB("IPClinic/LockToOwnProcedures")
  $LockExamList = modGlobalSetting.ShowSettingFromDB("ClinicForms/ExamList_Lock")
  $LockSymptomList = modGlobalSetting.ShowSettingFromDB("ClinicForms/SymptomList_Lock")
  $LockDiagnosisList = modGlobalSetting.ShowSettingFromDB("ClinicForms/Diagnosis_Lock")
  $LockDelTypeInput = modGlobalSetting.ShowSettingFromDB("ClinicForms/DeliveryType_InputLock")
  $LockProcedCompInput = modGlobalSetting.ShowSettingFromDB("ClinicForms/ProcedureComp_InputLock")
  $LockAnesTechnInput = modGlobalSetting.ShowSettingFromDB("ClinicForms/AnesTechnique_InputLock")

  $DisplayExamOption = modSettings.ShowSettingFromFIle("ClinicForms/Display_Options")
  $DisplayQualiArea = modSettings.ShowSettingFromFIle("ClinicForms/DisplayTextArea")
  $DefaultTestList = modSettings.ShowSettingFromFIle("ClinicForms/Default_TestGroup")
  $DefaultRadioList = modSettings.ShowSettingFromFIle("ClinicForms/Default_RadioGroup")
  $ProvDiagnosisRule = modSettings.ShowSettingFromFIle("ClinicalList/ProvDiagnosis_Rule")
  $FinalDiagnosisRule = modSettings.ShowSettingFromFIle("ClinicalList/FinalDiagnosis_Rule")
  $DefaultDiagnoGroup = modSettings.ShowSettingFromFIle("ClinicalList/DefaultDiagnosisGroup")

End

Public Sub ClinicalCommentSett()

  $CommRefRange = modSettings.ShowSettingFromFIle("ClinicalComment/ReferenceRange")
  $CommSensSpec = modSettings.ShowSettingFromFIle("ClinicalComment/Sensitivity_Specificity")
  $CommMedEffect = modSettings.ShowSettingFromFIle("ClinicalComment/MedicineEffect")
  $CommCauseSyndro = modSettings.ShowSettingFromFIle("ClinicalComment/CausitiveSyndrome")
  $CommInterpret = modSettings.ShowSettingFromFIle("ClinicalComment/Interpretation")

End

''custom report source
Public Sub LoadCustomReportSource()

  $CustomConsult = modSettings.ShowSettingFromFIle("CustomVariable/Consultation")
  $CustomBirth = modSettings.ShowSettingFromFIle("CustomVariable/BirthDetail")
  $CustomHistory = modSettings.ShowSettingFromFIle("CustomVariable/SelectedHistory")
  $CustomSelExam = modSettings.ShowSettingFromFIle("CustomVariable/SelectedExam")
  $CustomProcedure = modSettings.ShowSettingFromFIle("CustomVariable/ProcedureDetail")

  $CustomImage = modSettings.ShowSettingFromFIle("CustomVariable/CustomImages")
  $CustomDataQR = modSettings.ShowSettingFromFIle("CustomVariable/CustomReportQR")
  $CustomUser = modSettings.ShowSettingFromFIle("CustomVariable/CustomUser")
  $CustomTest = modSettings.ShowSettingFromFIle("CustomVariable/CustomTest")
  $CustomExam = modSettings.ShowSettingFromFIle("CustomVariable/CustomExam")
  $CustomRadio = modSettings.ShowSettingFromFIle("CustomVariable/CustomRadio")
  $CustomDemog = modSettings.ShowSettingFromFIle("CustomVariable/CustomDemographics")
  $CustomCalc = modSettings.ShowSettingFromFIle("CustomVariable/CustomCalculation")
  $CustomSQLQuery = modSettings.ShowSettingFromFIle("CustomVariable/CustomSQLQuery")
  $CustomScript = modSettings.ShowSettingFromFIle("CustomVariable/CustomScripts")
  $CustomExec = modSettings.ShowSettingFromFIle("CustomVariable/CustomExecs")

End

Public Sub ReportLogSetting()

  $ReportLogPrint = modGlobalSetting.ShowSettingFromDB("ReportLog/Print")
  $ReportLogHTML = modGlobalSetting.ShowSettingFromDB("ReportLog/HTML")
  $ReportLogPDF = modGlobalSetting.ShowSettingFromDB("ReportLog/PDF")
  $ReportLogExport = modGlobalSetting.ShowSettingFromDB("ReportLog/Export")
  $ReportLogSend = modGlobalSetting.ShowSettingFromDB("ReportLog/Send")
  $ReportLogSave = modGlobalSetting.ShowSettingFromDB("ReportLog/Save")
  $ReportLogFTP = modGlobalSetting.ShowSettingFromDB("ReportLog/FTP")

End

Public Sub UploadDataSetting()

  $UploadMaxSize = modGlobalSetting.ShowSettingFromDB("GeneralSettings/MaxFileSize")
  $UploadEncryptPDF = modGlobalSetting.ShowSettingFromDB("GeneralSettings/PDFEncrypt")

End

Public Sub LabRadiologySeting()

  ''alerts
  $AlertRadioList = modSettings.ShowSettingFromFIle("Laboratory/RadioAlertList")
  $AlertTestList = modSettings.ShowSettingFromFIle("Laboratory/TestAlertList")

  ''reports
  $LabWorkSheet = modSettings.ShowSettingFromFIle("LabWorksheet/PrintMode")
  $LabBarCode = modSettings.ShowSettingFromFIle("SampleBarcode/DataContent")
  $LabBarPrint = modSettings.ShowSettingFromFIle("SampleBarcode/Separation")
  $LabBarPath = modSettings.ShowSettingFromFIle("SampleBarcode/Templete")

  ''target restriction
  $LabSamplingFrom = modSettings.ShowSettingFromFIle("Laboratory/SenderType_Sampling")
  $LabSamplingComp = modSettings.ShowSettingFromFIle("Laboratory/FixSender_Sampling")
  $LabReportingFrom = modSettings.ShowSettingFromFIle("Laboratory/SenderType_Reporting")
  $LabReportingComp = modSettings.ShowSettingFromFIle("Laboratory/FixSender_Reporting")

  $LabAutoSampNo = modSettings.ShowSettingFromFIle("Laboratory/SampleNoAutoincrement")
  $LabSamplePrefix = modSettings.ShowSettingFromFIle("Laboratory/SampleNoPrefix")

End

Public Sub LoadClinicalLists()

  Dim aa As String[]
  Dim bb As String[]
  Dim cc As String[]

  $GenericMedName = modMedicine.GetGenericMedList()
  $ClinBodyFluidAll = modmedicine.GetBodyFluidList()
  $IPDDepartmentsAll = modMisc.GetDepartmentWithBedList()

  aa = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select distinct(fldsymptom) as col from tblcomplaints where (fldcomp=&1 or fldcomp=&2)", modGeneralMain.compID, "%"))                           ''
  $ClinComplaintComp = aa.Sort()
  $ClinComplaintCompGrouped = modFixPatho.GetSymptomWithCategory(modBasic.$ClinComplaintComp)

  bb = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select distinct(fldexamid) as col from tblcompexam where (fldcomp=&1 or fldcomp=&2) and fldcategory=&3", modGeneralMain.compID, "%", "Physician Examinations"))
  $ClinFindingComp = bb.Sort()
  $ClinFindingCompGrouped = modFixClinic.GetExamWithCategory(modBasic.$ClinFindingComp)

  cc = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select distinct(fldexamid) as col from tblcompexam where (fldcomp=&1 or fldcomp=&2) and fldcategory=&3", modGeneralMain.compID, "%", "Nursing Examinations"))
  $ClinNursingComp = cc.Sort()

  $ClinDiagnoChapterGrouped = modICD.GetICDCapterList(modPathology.ICDChapterPath(), modPathology.ICDBlockPath())
  $ClinDiagnoChapterGrouped.Sort()

  $DemogList = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select distinct(flddemoid) as col from tbldemographic where (fldcomp=&1 or fldcomp=&2)", modGeneralMain.compID, "%"))
  $ClinEssentialComp = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select distinct(fldexamid) as col from tblcompexam where (fldcomp=&1 or fldcomp=&2) and fldcategory=&3", modGeneralMain.compID, "%", "Essential Examinations"))
  $ClinTriageComp = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select distinct(fldexamid) as col from tblcompexam where (fldcomp=&1 or fldcomp=&2) and fldcategory=&3", modGeneralMain.compID, "%", "Triage Examinations"))
  $ClinDischargeComp = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select distinct(fldexamid) as col from tblcompexam where (fldcomp=&1 or fldcomp=&2) and fldcategory=&3", modGeneralMain.compID, "%", "Discharge Examinations"))

  $sysExamList = modSysCons.GetSysconstList("Exam")
  $sysTestList = modSysCons.GetSysconstList("Test")
  $sysRadioList = modSysCons.GetSysconstList("Radio")
  $sysCustomList = modSysCons.GetSysconstList("Custom")

End

Public Sub DispLabelSettings()

  $DispLabelRegimen = modSettings.ShowSettingFromFIle("DispensingLabel/ShowRegimen")
  $DispLabelAutoEnable = modSettings.ShowSettingFromFIle("DispensingLabel/AutoEnable")

End
