' Gambas module file

Public $UserNameData As Collection
Public $UserCodeData As Collection
Public $EthnicCodeData As Collection

'NOTE: ------------------------------------- Payable User ----------------------------------
'types: Test/Service/Procedure/Equipment
Public Sub FixPayableUser(sType As String, sButtonBox As ButtonBox, encid As String)

  Dim xx As String
  Dim xauto As String

  xauto = modGlobalSetting.ShowSettingFromDB("FixPayableUser/" & sType)
  If xauto = "User" Then
    sButtonBox.Tag = modGeneralMain.$lbluser
    sButtonBox.Text = GetUserFullName(modGeneralMain.$lbluser)
    sButtonBox.Enabled = False
  Else If xauto = "Consult" Then
    xx = modPatient.GetAttendingConsultant(encid)
    sButtonBox.Tag = xx
    sButtonBox.Text = GetUserFullName(xx)
    sButtonBox.Enabled = False
  Else If xauto = "Null" Then
    sButtonBox.Tag = ""
    sButtonBox.Text = ""
    sButtonBox.Enabled = False
  Else
    xx = modPatient.GetAttendingConsultant(encid)
    sButtonBox.Tag = xx
    sButtonBox.Text = GetUserFullName(xx)
    sButtonBox.Enabled = True
  Endif

End

'NOTE: --------------------------- Computers -----------------------------------------
Public Function CompIDList() As String[]

  Dim xx As String[]
  Dim xcom As String
  Dim i As Integer

  xx = New String[]
  For i = 1 To 50
    xcom = CStr(i)
    If Len(xcom) = 1 Then
      xcom = "0" & xcom
    Endif
    xx.Add("comp" & xcom)
  Next
  Return xx

End

Public Function FillCompFromLabReport() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select distinct(fldcomp_report) as col from tblpatlabtest")
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx

End

Public Function CompList() As String[]

  Dim xx As String[]
  Dim sql As String
  Dim res As Result

  sql = "select distinct(fldcomp) as col from tblmacaccess"
  res = modDatabase.$myConn.Exec(sql)
  xx = modFillContainer.GetListFromResult(res)

  Return xx.Sort()

End

Public Function GetCompFromCompName(txtcompname As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldcomp from tblmacaccess where fldcompname=&1", txtcompname)
  If res.Available = True Then
    res.MoveFirst
    If res!fldcomp Then
      xx = res!fldcomp
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetCompNameFromCompID(txtcompid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldcompname from tblmacaccess where fldcomp=&1", txtcompid)
  If res.Available = True Then
    res.MoveFirst
    If res!fldcompname Then
      xx = res!fldcompname
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetIPTypeFromMAC(txtmac As String) As String

  Dim res As Result
  Dim typ As String

  res = modDatabase.$myConn.Exec("select fldiptype from tblmacaccess where fldhostmac=&1", txtmac)
  If res.Available Then
    If res!fldiptype Then
      typ = res!fldiptype
    Else
      typ = ""
    Endif
  Else
    typ = ""
  Endif
  Return typ

End

Public Function GetMacCodeFromMacAdd(mac As String) As Integer

  Dim res As Result
  Dim xx As Integer

  res = modDatabase.$myConn.Exec("select fldcode from tblmacaccess where fldhostmac=&1", mac)
  If res!fldcode Then
    xx = res!fldcode
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetMaxMacAddCode() As Integer

  Dim xx As Integer
  Dim rs As Result

  rs = modDatabase.$myConn.Exec("select MAX(fldcode) as fldid from tblmacaccess")
  If rs!fldid Then
    xx = rs!fldid + 1
  Else
    xx = 1
  Endif
  Return xx

End

''---------------------------------------- user for payble, sms, report ------------------------------------------------
Public Sub GetUserIDAll() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select flduserid from tbluser")
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx

End

Public Function CategoricalUserList(sType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  If sType = "%" Then
    res = modDatabase.$myConn.Exec("select flduserid from tbluser")
  Else
    res = modDatabase.$myConn.Exec(Subst("select flduserid from tbluser where &1", sType) & "=&1", True)
  Endif
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx

End

Public Function GetExpoReportUser(sUser As String) As Boolean

  Dim res As Result
  Dim xx As Boolean

  res = modDatabase.$myConn.Exec("select fldreport from tbluser where flduserid=&1", sUser)
  If res.Available Then
    If res!fldreport Then
      xx = res!fldreport
    Else
      xx = False
    Endif
  Else
    xx = False
  Endif
  Return xx

End

Public Function GetSuperUser(sUser As String) As Boolean

  Dim res As Result
  Dim xx As Boolean

  res = modDatabase.$myConn.Exec("select fldfaculty from tbluser where flduserid=&1", sUser)
  If res.Available Then
    If res!fldfaculty Then
      xx = res!fldfaculty
    Else
      xx = False
    Endif
  Else
    xx = False
  Endif
  Return xx

End

Public Function AllowClinicalEdit(sUser As String) As Boolean

  Dim xbool As Boolean

  If sUser = modGeneralMain.$lbluser Then
    xbool = True
  Else If modBasic.$SuperUser = True Then
    xbool = True
  Else
    xbool = False
  Endif
  Return xbool

End

Public Function GetUserFullName(userid As String) As String

  Dim res As Result
  Dim xx As String

  If userid Then

    xx = modHelpVariable.GetCollectionValue($UserNameData, userid)
    If Not xx Then
      res = modDatabase.$myConn.Exec("select fldusername from tbluser where flduserid=&1", userid)
      If res.Available Then
        If res!fldusername Then
          xx = res!fldusername
          If modBasic.$LocalCache = "Yes" Then
            $UserNameData.Add(xx, userid)
          Endif
        Else
          xx = ""
        Endif
      Else
        xx = ""
      Endif
    Endif

  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetPrescriberCodeFromName(docname As String) As String

  Dim xx As String
  Dim res As Result

  xx = modHelpVariable.GetCollectionValue($UserCodeData, docname)
  If Not xx Then
    res = modDatabase.$myConn.Exec("select fldusercode from tbluser where flduserid=&1", docname)
    If res.Available = True Then
      res.MoveFirst
      If res!fldusercode Then
        xx = res!fldusercode
        If modBasic.$LocalCache = "Yes" Then
          $UserCodeData.Add(xx, docname)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

Public Function GetUserFullNamePrint(userid As String) As String

  Dim res As Result
  Dim xx As String

  If userid Then
    res = modDatabase.$myConn.Exec("select fldname from tblreportuser where flduserid=&1", userid)
    If res.Available = True Then
      If res!fldname Then
        xx = res!fldname
      Else
        xx = GetUserFullName(userid)
      Endif
    Else
      xx = GetUserFullName(userid)
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

'user for dept incharge
Private Sub GetInchargeFromDepartment(sDept As String) As String

  Dim res1 As Result
  Dim xx As String

  res1 = modDatabase.$myConn.Exec("select fldactive from tbldepartment where flddept=&1", sDept)
  If res1.Available
    res1.MoveFirst
    If res1!fldactive Then
      xx = res1!fldactive
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

'user for dept posting (if not available it takes incharge)
Public Function GetUserIDFromDepartment(sDept As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flduserid from tbldepconsult where flddept=&1", sDept)
  If res.Available Then
    res.MoveFirst
    If res!fldcontact Then
      xx = res!fldcontact
    Else
      xx = GetInchargeFromDepartment(sDept)
    Endif
  Else
    xx = GetInchargeFromDepartment(sDept)
  Endif
  Return xx

End

Public Function GetUserContact(userid As String) As String

  Dim sql As String
  Dim res As Result
  Dim xx As String

  sql = "select fldptcontact from tblstafflist where flduserid=&1"
  res = modDatabase.$myConn.Exec(sql, userid)
  If res.Available Then
    If res!fldptcontact Then
      xx = res!fldptcontact
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetMainUserCode(userid As String) As Long

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select fldcode from tbluser where flduserid=&1", userid)
  If res.Available Then
    If res!fldcode Then
      xx = res!fldcode
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetEthnicCode(surName As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($EthnicCodeData, surName)
  If Not xx Then
    res = modDatabase.$myConn.Exec("select fldgroupname from tblethnicgroup where flditemname=&1", surName)
    If res.Available Then
      If res!fldgroupname Then
        xx = res!fldgroupname
        If modBasic.$LocalCache = "Yes" Then
          $EthnicCodeData.Add(xx, surName)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

''----------------------------- user by log in ------------------------------------
Public Function FillCurrentUseronJob(sComp As String) As String[]

  Dim res As Result
  Dim xxx As String[]

  res = modDatabase.$myConn.Exec("select distinct(flduser) as col from tblsystemlog where fldcomp like &1", sComp)
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx

End

Public Function GetCurrentUseronMac(mac As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flduser from tblsystemlog where fldhostmac=&1", mac)
  If res.Available = True Then
    res.MoveLast
    If res!flduser Then
      xx = res!flduser
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetCurrentUserFromIP(lbip As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flduser from tblsystemlog where fldhostip=&1", lbip)
  If res.Available = True Then
    res.MoveLast
    If res!flduser Then
      xx = res!flduser
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetCurrentCompOnSys() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select distinct(fldcomp) as col from tblsystemlog")
  If res.Available Then
    xx = modFillContainer.GetListFromResult(res)
  Endif
  Return xx

End

Public Function GetCurrentLocationFromIP(lbip As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldcomp from tblsystemlog where fldhostip=&1", lbip)
  If res.Available = True Then
    res.MoveLast
    If res!fldcomp Then
      xx = res!fldcomp
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetCurrentIPFromUser(lbuser As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldhostip from tblsystemlog where flduser=&1", lbuser)
  If res.Available = True Then
    res.MoveLast
    If res!fldhostip Then
      xx = res!fldhostip
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetCurrentIPonMac(mac As String) As String

  Dim res As Result
  Dim res1 As Result
  Dim xx As String
  Dim iptype As String

  iptype = GetIPTypeFromMAC(mac)
  If iptype = "Fixed" Then
    res = modDatabase.$myConn.Exec("select fldhostip from tblmacaccess where fldhostmac=&1", mac)
    xx = res!fldhostip
  Else
    res = modDatabase.$myConn.Exec("select fldhostip from tblsystemlog where fldhostmac=&1", mac)
    If res.Available = True Then
      res.MoveLast
      xx = res!fldhostip
    Else
      res1 = modDatabase.$myConn.Exec("select fldhostip from tbljobrecord where fldhostmac=&1", mac)
      If res1.Available = True Then
        res1.MoveLast
        xx = res1!fldhostip
      Else
        xx = ""
      Endif
    Endif
  Endif
  Return xx

End

Public Function GetVersiononMac(mac As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldversion from tblsystemlog where fldhostmac=&1", mac)
  If res.Available = True Then
    res.MoveLast
    If res!fldversion Then
      xx = res!fldversion
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End
'
''
'''
'''

Public Function GetRoomNoFromDept(sDept As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldroom from tbldepartment where flddept=&1", sDept)
  If res.Available Then
    xx = res!fldroom
  Else
    xx = ""
  Endif
  Return xx

End

'
''
'''
''''

Public Function GetUserAccessList(sUser As String) As String[]

  Dim res1 As Result
  Dim xxx As String[]
  Dim yyy As String[]

  yyy = New String[]
  res1 = modDatabase.$syConn.Exec("select distinct(fldcategory) as col from tbluserformaccess where flduserid=&1", sUser)
  If res1.Available Then
    For Each res1
      xxx = modFillContainer.GetListFromResult(modDatabase.$syConn.Exec("select fldformname from tbluserformaccess where flduserid=&1 and fldcategory=&2", sUser, res1!col))                     ''                                                  ''
      yyy.Add(res1!col & " : " & xxx.Join(", "))
    Next
  Endif
  yyy.Sort()
  Return yyy

End

''----------------------------- Hospitals Repository ------------------------------
Public Function GetHospitaltName(sHospCode As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldhospname from tblhospitals where fldhospcode=&1", sHospCode)
  If res.Available Then
    If res!fldhospname Then
      xx = res!fldhospname
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End
