' Gambas module file

Private Sub AddSettingToDB(strSetting As String, strVal As String, compid As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblsettings")
  res["fldindex"] = compid & ":" & strSetting
  res["fldcomp"] = compid
  res["fldcategory"] = strSetting
  res["fldvalue"] = Trim(strVal)
  res["fldtime"] = Now()
  res["flduserid"] = modGeneralMain.$lbluser
  res.Update

End

Private Sub EditSettingToDB(strSetting As String, strVal As String, compid As String)

  Dim res As Result

  If compid Then
    res = modDatabase.$myConn.Edit("tblsettings", "fldindex=&1", compid & ":" & strSetting)
    res["fldvalue"] = Trim(strVal)
    res["fldtime"] = Now()
    res["flduserid"] = modGeneralMain.$lbluser
    res.Update
  Endif

End

Public Sub SaveSettingToDB(strSetting As String, strVal As String, compid As String)

  Dim res As Result

  If compid Then
    res = modDatabase.$myConn.Exec("select fldvalue from tblsettings where fldindex=&1", compid & ":" & strSetting)                      ''
    If res.Available = False Then
      AddSettingToDB(strSetting, strVal, compid)
    Else If res.Available = True Then
      EditSettingToDB(strSetting, strVal, compid)
    Endif
  Endif

End

Public Function ShowSettingFromDBAny(strSetting As String, compid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldvalue from tblsettings where fldindex=&1", compid & ":" & strSetting)
  If res.Available Then
    If res!fldvalue Then
      xx = Trim(res!fldvalue)
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Function ShowSettingFromDB(strSetting As String) As String

  Dim xx As String

  xx = ShowSettingFromDBAny(strSetting, modGeneralMain.compID)
  Return xx

End

''--- for checkbox
Public Sub EnterSettingFromDB(chkvar As CheckBox, strTitle As String, compid As String)

  If compid Then
    If chkvar.Value = True Then
      SaveSettingToDB(strTitle, "Yes", compid)
    Else If chkvar.Value = False Then
      SaveSettingToDB(strTitle, "No", compid)
    Endif
  Endif

End

Public Sub ShowCheckBoxFromDBAny(chkvar As CheckBox, StrTitle As String, compid As String)

  Dim xval As String

  xval = ShowSettingFromDBAny(StrTitle, compid)
  If xval Then
    If xval = "Yes" Then
      chkvar.Value = True
    Else
      chkvar.Value = False
    Endif
  Else
    chkvar.Value = False
  Endif

End

Public Sub ShowCheckBoxFromDB(chkvar As CheckBox, StrTitle As String)

  ShowCheckBoxFromDBAny(chkvar, StrTitle, modGeneralMain.compID)

End

''-----------------------Table List --------------------------------
Public Sub ShowTableSettingDB(lstbox As ListBox, compid As String, sType As String)

  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldvalue as col from tbltabsettings where fldcomp=&1 and fldcategory=&2", compid, sType & "/TableList")
  modFillContainer.FillListBox(lstbox, res, False)

End

Public Sub AddTableListDB(compid As String, sType As String, TableList As String[], xListbox As ListBox)

  Dim xx As String[]
  Dim sitem As String
  Dim res As Result
  Dim tablist As String[]

  tablist = modString.GetRemainingArray(TableList, xListbox.List)
  xx = SelectListView("Insert Table Name", tablist, False)
  If xx Then
    Inc Application.Busy
    For Each sitem In xx
      res = modDatabase.$myConn.Create("tbltabsettings")
      res["fldcomp"] = compid
      res["fldcategory"] = sType & "/TableList"
      res["fldvalue"] = sitem
      res["fldtime"] = Now()
      res["flduserid"] = modGeneralMain.$lbluser
      res.Update
    Next
    Dec Application.Busy
  Endif

End

Public Function GetDBTableList(sSetting As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select fldvalue from tbltabsettings where fldcomp=&1 and fldcategory=&2", modGeneralMain.compID, sSetting)
  xx = modFillContainer.GetListFromResult(res)
  Return xx

End
