' Gambas module file

Public $CryptValue As String
Public $CryptRepo As String
Public $CryptPDF As String
Public $CryptZip As String
Public $SaltValue As String
Public $SysConfigPath As String

Public $HospitalName As String
Public $HospitalAddress As String
Public $Department As String
Public compID As String
Public $HospLogo As String
Public $IRDLevel As String

Public $SysDataBase As String
Public $SysDisableDate As String
Public $SysDisableCharset As String
Public $SysCollation As String
Public $SysInterface As String
Public $SysUseSSL As Boolean

Public $SysMainService As String
Public $SysMainHost As String
Public $SysMainUser As String
Public $SysMainPassword As String
Public $SysMainPort As String

Public $SysExtService As String
Public $SysExtHost As String
Public $SysExtUser As String
Public $SysExtPass As String
Public $SysExtPort As String

Public $SysFallService As String
Public $SysFallHost As String
Public $SysFallUser As String
Public $SysFallPass As String
Public $SysFallPort As String

Public $SysFTPHost As String
Public $SysFTPFolder As String
Public $SysFTPUser As String
Public $SysFTPPass As String
''------------------ END ------------------

Private $DBType As String
Private $DBHost As String
Private $DBName As String
Private $UserName As String
Private $UserPassword As String
Private $sPort As String

Private picleft As WebView
Private picright As WebView
Private WrkspaceHt As Integer

''Public Variables
Public $conTarget As String
Public $MACAddress As String
Public $localIP As String
Public $LogInTime As Date
Public $lbluser As String
Public $macCode As Integer
Public $HideFormList As String[]

Public $ApplKey As Integer
Public Const $strLogo As String = "icon:/small/file"
Public $DeskHeight As Integer
Public $DeskWidth As Integer
Private $advPanel As Panel

Public $virtualTerminal As String

'NOTE: -------------------------------- General Connection -------------------------------
Public Sub ReadConfigFile()

  Dim xlogo As String
  Dim xfile As String
  Dim xssl As String

  xfile = GetConfigSettingFIle()
  $HospitalName = modSettings.ShowSettingValue(xfile, "Hospital/Hospital")
  $HospitalAddress = modSettings.ShowSettingValue(xfile, "Hospital/Address")
  $Department = modSettings.ShowSettingValue(xfile, "Hospital/Department")
  compID = modSettings.ShowSettingValue(xfile, "Hospital/ComputerID")
  $IRDLevel = modSettings.ShowSettingValue(xfile, "Hospital/IRDCompliance")
  xlogo = modSettings.ShowSettingValue(xfile, "Hospital/Logo")
  If xlogo Then
    $HospLogo = xlogo
  Else
    $HospLogo = modHelpVariable.AppDirectory & "/Logo.JPG"
  Endif

  $SysDataBase = modSettings.ShowSettingValue(xfile, "System/Database")
  $SysCollation = modSettings.ShowSettingValue(xfile, "System/DBCollation")
  $SysInterface = modSettings.ShowSettingValue(xfile, "System/NetInterface")
  $SysDisableDate = modSettings.ShowSettingValue(xfile, "System/DisableDateCheck")
  $SysDisableCharset = modSettings.ShowSettingValue(xfile, "System/DisableCharSet")
  xssl = modSettings.ShowSettingValue(xfile, "System/UseOpenSSL")
  If xssl = "Yes" Then
    $SysUseSSL = True
  Else
    $SysUseSSL = False
  Endif

  $SysMainService = modSettings.ShowSettingValue(xfile, "System/Service")
  $SysMainHost = modSettings.ShowSettingValue(xfile, "System/Host")
  $SysMainUser = modSettings.ShowSettingValue(xfile, "System/User")
  $SysMainPassword = modPassword.DecryptDBPass(modSettings.ShowSettingValue(xfile, "System/Password"), $SysUseSSL)
  $SysMainPort = modSettings.ShowSettingValue(xfile, "System/Port")

  $SysExtService = modSettings.ShowSettingValue(xfile, "SystemExtra/Service")
  $SysExtHost = modSettings.ShowSettingValue(xfile, "SystemExtra/Host")
  $SysExtUser = modSettings.ShowSettingValue(xfile, "SystemExtra/User")
  $SysExtPass = modPassword.DecryptDBPass(modSettings.ShowSettingValue(xfile, "SystemExtra/Password"), $SysUseSSL)
  $SysExtPort = modSettings.ShowSettingValue(xfile, "SystemExtra/Port")

  $SysFallService = modSettings.ShowSettingValue(xfile, "SystemFallback/Service")
  $SysFallHost = modSettings.ShowSettingValue(xfile, "SystemFallback/Host")
  $SysFallUser = modSettings.ShowSettingValue(xfile, "SystemFallback/User")
  $SysFallPass = modPassword.DecryptDBPass(modSettings.ShowSettingValue(xfile, "SystemFallback/Password"), $SysUseSSL)
  $SysFallPort = modSettings.ShowSettingValue(xfile, "SystemFallback/Port")

  $SysFTPHost = modSettings.ShowSettingValue(xfile, "LocalFTP/Host")
  $SysFTPFolder = modSettings.ShowSettingValue(xfile, "LocalFTP/Folder")
  $SysFTPUser = modSettings.ShowSettingValue(xfile, "LocalFTP/User")
  $SysFTPPass = modPassword.DecryptDBPass(modSettings.ShowSettingValue(xfile, "LocalFTP/Password"), $SysUseSSL)

  Try Kill xfile

End

Public Sub ConnectionMain()

  ReadConfigFile()
  $conTarget = modSettings.ShowSettingFromFIle("SISH_Connection/ConnectionType")
  If $conTarget = "Remote" Then
    $DBType = modSettings.ShowSettingFromFIle("SISH_Connection/RemoteService")
    $DBHost = modSettings.ShowSettingFromFIle("SISH_Connection/RemoteHost")
    $DBName = modSettings.ShowSettingFromFIle("SISH_Connection/RemoteDatabase")
    $UserName = UnBase64(modSettings.ShowSettingFromFIle("SISH_Connection/RemoteUser"))
    $UserPassword = UnBase64(modSettings.ShowSettingFromFIle("SISH_Connection/RemotePass"))
    $sPort = modSettings.ShowSettingFromFIle("SISH_Connection/RemotePort")
  Else
    $DBType = $SysMainService
    $DBHost = $SysMainHost
    $DBName = $SysDataBase
    $UserName = $SysMainUser
    $UserPassword = $SysMainPassword
    $sPort = $SysMainPort
  Endif

  If $sPort Then
    modDatabase.$myConn = modDatabase.OpenConnection($DBType, $DBHost, $DBName, $UserName, $UserPassword, $sPort)
  Else
    modDatabase.$myConn = modDatabase.OpenConnection($DBType, $DBHost, $DBName, $UserName, $UserPassword)
  Endif

  If modDatabase.$myConn.Opened = True Then
    modBasic.DebugString("App connected to " & $DBName & " on Main Server at " & $DBHost & " . Database Driver: " & CStr(modDatabase.$myConn.Version))
    ConnectionExtra()
  Else
    If $conTarget = "Remote" Then
    Else
      modBasic.DebugString("Unable to connect " & $DBName & " on Main Server at " & $DBHost & " . Attempting to connect Fallback Server.")
      ConnectionFallBack()
    Endif
  Endif
  ''medical connection
  modDatabase.$medConn = modDatabase.$myConn

End

Private Sub ConnectionFallBack()

  Dim UserName As String
  Dim UserPassword As String
  Dim DBName As String
  Dim DBType As String
  Dim DBHost As String
  Dim sPort As String

  DBName = $SysDataBase
  DBType = $SysFallService
  DBHost = $SysFallHost
  UserName = $SysFallUser
  UserPassword = $SysFallPass
  sPort = $SysFallPort

  If sPort Then
    modDatabase.$myConn = modDatabase.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword, sPort)
  Else
    modDatabase.$myConn = modDatabase.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword)
  Endif

  If modDatabase.$myConn.Opened = True Then
    modBasic.DebugString("App connected to " & DBName & " on Fallback Server at " & DBHost & " . Database Driver: " & CStr(modDatabase.$myConn.Version))
    ConnectionExtra()
  Else
    ErrorConnection()
  Endif

End

Private Sub ErrorConnection()

  fmLogIn.Close
  If Message.Warning(("Please check network connections") & "<br>" & ("1. Please check network cables.") & "<br>" & ("2. Ping To Server " & $DBHost), ("OK"), ("No")) = 1 Then
    Shell modApplication.GetDeskopTerminal() & " -e \"" & "ping " & $DBHost & "\""
  Endif

End

Private Sub ConnectionExtra()

  Dim UserName As String
  Dim UserPassword As String
  Dim DBName As String
  Dim DBType As String
  Dim DBHost As String
  Dim sPort As String

  If $conTarget = "Remote" Then
    DBName = $DBName
    DBType = $DBType
    DBHost = $DBHost
    UserName = $UserName
    UserPassword = $UserPassword
    sPort = $sPort
  Else
    DBName = $SysDataBase
    DBType = $SysExtService
    DBHost = $SysExtHost
    UserName = $SysExtUser
    UserPassword = $SysExtPass
    sPort = $SysExtPort
  Endif

  If sPort Then
    modDatabase.$syConn = modDatabase.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword, sPort)
  Else
    modDatabase.$syConn = modDatabase.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword)
  Endif
  If modDatabase.$syConn.Opened = False Then
    modDatabase.$syConn = modDatabase.$myConn
    modBasic.DebugString("Main/Fallback Server used as Read Server")
  Else
    modBasic.DebugString("App connected to " & DBName & " on Read Server at " & DBHost & " . Database Driver: " & CStr(modDatabase.$syConn.Version))
  Endif

End

Public Sub CalenderConnection()

  modDatabase.$calConn = modDatabase.OpenConnection("sqlite3", modHelpVariable.$docsDirectory, modHelpVariable.$docsDirectory &/ "calender", "", "")
  If modDatabase.$calConn.Opened = True Then
    modBasic.DebugString("App connected to calendar sqlite database. Database Driver: " & CStr(modDatabase.$calConn.Version))
  Endif

End

Public Function GetConfigSettingFIle() As String

  Dim xpath As String
  Dim xdir As String
  Dim xfile As String

  If $SysConfigPath = modHelpVariable.$appetcConfFile Then
    xpath = modHelpVariable.$appetcConfFile
  Else
    xdir = modHelpVariable.AppCacheDir
    xfile = xdir &/ modHelpVariable.AppName & ".conf"
    If Exist(xfile) Then
      Kill xfile
    Endif
    If Not Exist(xdir) Then
      Mkdir xdir
    Endif
    modDevice.Get7ZExtraction(modHelpVariable.$appetc7zFile, $CryptZip, xfile)
    xpath = xfile
  Endif
  Return xpath

End

''
'''
''''

'NOTE: ---------------------------- FOR APPLICATION Log --------------------------------------
''ONLY FOR IRD COMPLIANCE
Public Sub RecordIRDActivity(sCon As Connection, sCategory As String, frm As String, sActivity As String, sComment As String)

  Dim res As Result
  Dim macc As String
  Dim xusr As String

  If $MACAddress Then
    Try macc = $MACAddress
  Else
    macc = ""
  Endif
  If $lbluser Then
    Try xusr = $lbluser
  Else
    xusr = ""
  Endif

  res = sCon.Create("tblirdactivity")
  res["fldfrmname"] = frm
  res["fldcategory"] = sCategory
  res["fldactivity"] = sActivity
  res["fldcomment"] = sComment
  res["flduserid"] = xusr
  res["fldtime"] = Now()
  res["fldcomp"] = compID
  res["fldsave"] = True
  res["fldhostmac"] = macc
  res.Update

End

Public Sub RecordPatientActivity(sCategory As String, frm As String, sActivity As String, sComment As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblactivity")
  res["fldfrmname"] = frm
  res["fldcategory"] = sCategory
  res["fldactivity"] = sActivity
  res["fldcomment"] = sComment
  res["flduserid"] = $lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = compID
  res["fldsave"] = True
  res["fldhostmac"] = $MACAddress
  res.Update

End

Public Sub RecordSystemLog()

  Dim res As Result

  modBasic.DebugString("Inserting Application usage log")
  modDatabase.$myConn.Delete("tblsystemlog", "fldindex=&1", $MACAddress)
  res = modDatabase.$myConn.Create("tblsystemlog")
  res["fldindex"] = $MACAddress
  res["flduser"] = $lbluser
  res["fldcomp"] = compID
  res["fldlogin"] = modHelpVariable.$LogInCategory
  res["fldentrytime"] = $LogInTime
  res["fldhostuser"] = System.User.Name
  res["fldhostip"] = $localIP
  res["fldhostname"] = System.Host
  res["fldhostmac"] = $MACAddress
  res["flddevicepath"] = modDevice.WebCamDevice()
  res["fldversion"] = Application.Version
  res["fldmainserver"] = $SysMainHost
  res["fldreadserver"] = $SysExtHost
  res["fldfallserver"] = $SysFallHost
  res["fldftpserver"] = $SysFTPHost
  res.Update()

End

Public Sub LockPatientActivity(frm As String, encid As String)

  Dim res As Result
  Dim res1 As Result

  res1 = modDatabase.$myConn.Edit("tblactivity", "fldcategory=&1 and fldactivity=&2 and fldcomment=&3", "Patient Lock", "EncounterID", encid)
  If res1.Available = False Then
    res = modDatabase.$myConn.Create("tblactivity")
    res["fldfrmname"] = frm
    res["fldcategory"] = "Patient Lock"
    res["fldactivity"] = "EncounterID"
    res["fldcomment"] = encid
    res["flduserid"] = $lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = compID
    res["fldsave"] = True
    res["fldhostmac"] = $MACAddress
    res.Update
  Else
    res["fldfrmname"] = frm
    res["flduserid"] = $lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = compID
    res["fldsave"] = True
    res["fldhostmac"] = $MACAddress
    res.Update
  Endif

End

Public Sub RecordFormUse(frm As Form)

  Dim res As Result
  Dim xx As String

  modBasic.DebugString("Inserting user log on " & frm.Text & " entry")
  xx = modString.GetDateString($LogInTime) & ":" & CStr($macCode) & ":" & CStr(frm.Handle)
  res = modDatabase.$myConn.Create("tbljobrecord")
  res["fldindex"] = xx
  res["fldfrmname"] = frm.Name
  res["fldfrmlabel"] = frm.Text
  res["flduser"] = $lbluser
  res["fldcomp"] = compID
  res["fldentrytime"] = Now()
  res["fldexittime"] = ""
  res["fldpresent"] = True
  res["fldhostuser"] = System.User.Name
  res["fldhostip"] = $localIP
  res["fldhostname"] = System.Host
  res["fldhostmac"] = $MACAddress
  res.Update()

End

Public Sub RecordFormExit(frm As Form)

  Dim res As Result
  Dim xx As String

  modBasic.DebugString("Inserting user log on " & frm.Text & " exit")
  xx = modString.GetDateString($LogInTime) & ":" & CStr($macCode) & ":" & CStr(frm.Handle)
  res = modDatabase.$myConn.Edit("tbljobrecord", "fldindex=&1 and fldpresent=&2", xx, True)                                                                               ''"
  If res.Available = True Then
    For Each res
      res["fldexittime"] = Now()
      res["fldpresent"] = False
      res.Update()
    Next
  Endif

End

Public Sub GetFirstValues(SvrSock As ServerSocket, SvrTrans As ServerSocket)

  If modBasic.$DebugMode = True Then
    db.Debug = True
  Endif
  CalenderConnection()
  modBasic.LoadGeneralVariables()
  $macCode = modGeneral.GetMacCodeFromMacAdd($MACAddress)
  'procedures on load
  modHelpVariable.OpenPortForListening(SvrSock)
  modHelpVariable.GetMessaging(SvrTrans)
  RecordSystemLog()
  SetActiveForms()
  modDevice.CamOnStart()

  ''cache side settings
  modHelpVariable.RestoreCacheDump()
  modSettings.SaveValuesToLog("LogIn/User", $lbluser)
  modSettings.SaveValuesToLog("Handle/" & Application.Name, CStr(Application.Handle))
  modSettings.SaveValuesToLog("Handle/Status", "Active")
  LogLoginFrequency()
  modExternal.StartAdvertise()

End

'
''
'''
''''

'NOTE: --------------------------------- Form Arrangements --------------------------------------
Public Sub LoadMainForms(frm As Form, wrkofficer As Workspace)

  Dim xpanel As Panel
  Dim head As Integer
  Dim sPict As PictureBox
  Dim sText As TextLabel
  Dim xhead As String

  Dim headht As String
  Dim headpic As String
  Dim headtext As String
  Dim headback As String
  Dim headfore As String
  Dim headfont As String

  Dim xmenu As Menu
  Dim ymenu As Menu

  modBasic.DebugString("Setting Desk for " & frm.Text)
  $DeskHeight = Screen.AvailableHeight
  $DeskWidth = Screen.AvailableWidth

  headht = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DeskHeaderHeight")
  headpic = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DeskHeaderPicture")
  headtext = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DeskHeaderText")
  headfore = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DeskHeaderForeColor")
  headback = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DeskHeaderBackColor")
  headfont = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DeskHeaderFont")

  'workspace
  modBasic.DebugString("Setting Workspace in " & frm.Text)
  frm.Height = $DeskHeight
  frm.Width = $DeskWidth
  frm.Left = 0
  frm.Top = 0
  frm.Center

  'form header
  If headht Then
    modBasic.DebugString("Setting Desk Header in " & frm.Text)
    head = CInt(headht)
    xpanel = New Panel(frm)
    xpanel.Width = frm.Width
    xpanel.Height = head
    xpanel.Left = 0
    xpanel.Top = 0

    If headpic And If Exist(headpic) Then
      sPict = New PictureBox(xpanel)
      sPict.Left = 0
      sPict.Top = 0
      sPict.Width = xpanel.Width
      sPict.Height = xpanel.Height
      Try sPict.Picture = Image.Load(headpic).Stretch(sPict.Width, sPict.Height).Picture
    Else If Not headpic And If headtext Then
      sText = New TextLabel(xpanel)
      sText.Left = 0
      sText.Top = 0
      sText.Width = xpanel.Width
      sText.Height = xpanel.Height
      xhead = modReportVar.GetReportVarTitle(headtext)

      If headback Then
        sText.Background = headback
      Else
        sText.Background = Color.White
      Endif

      If headfore Then
        sText.Foreground = headfore
      Endif

      If headfont Then
        sText.Text = "<div align=center>" & modString.GetFormatTextFontString(xhead, headfont) & "</div>"
      Else
        sText.Text = "<div align=center>" & modString.TextToHTML(xhead,,, True) & "</div>"
      Endif
    Endif

  Else
    head = 0
  Endif

  'advertise embedder
  modBasic.DebugString("Setting Advertisement Panel in " & frm.Text)
  If $advPanel Then
    $advPanel.Delete()
  Endif
  $advPanel = New Panel(frm)
  $advPanel.Left = 0
  $advPanel.Top = frm.Height - (50 * modBasic.$AppScaleFactor)
  $advPanel.Width = frm.Width
  $advPanel.Height = 30 * modBasic.$AppScaleFactor
  $advPanel.Border = Border.None

  'adjust progressbar
  modBasic.DebugString("Setting Progressbar in " & frm.Text)
  With modHelpVariable.FindWorkProgressBar(modHelpVariable.$LogInCategory)
    .Top = frm.Height - (65 * modBasic.$AppScaleFactor)
    .Height = 15 * modBasic.$AppScaleFactor
    .Left = 0
    .Width = frm.Width
    .Background = Color.White
  End With

  'main form
  modBasic.DebugString("Setting Desk Workspace in " & frm.Text)
  wrkofficer.Width = frm.Width
  wrkofficer.Height = frm.Height - (head + (50 * modBasic.$AppScaleFactor))
  wrkofficer.Left = 0
  wrkofficer.Top = head
  WrkspaceHt = wrkofficer.Height

  'create menu for forms
  For Each xmenu In frm.Menus
    For Each ymenu In xmenu.Children
      If Not ymenu.Picture Then
        ymenu.Picture = Picture["icon:/small/new-window"]
      Endif
    Next
  Next

  modHelpVariable.SetWorkSpaceImage()
  modHelpVariable.SetWorkSpaceTabbing()

End

Public Sub ArrangeEmbedForms(frm As Form, pnl As Panel, Optional sArrange As String)

  Dim xpic As String
  Dim xback As String
  Dim xfore As String
  Dim xadleft As String
  Dim xadright As String
  Dim xpanel As Panel
  Dim xwork As Workspace

  modBasic.DebugString("Setting tabbed form for " & frm.Text)
  frm.Expand = True
  pnl.Top = 0
  pnl.Width = 960 * modBasic.$AppScaleFactor
  If modBasic.$FormLeftWidth Then
    pnl.Left = modBasic.$FormLeftWidth
  Else
    pnl.Left = 0.5 * ($DeskWidth - pnl.Width)
  Endif
  pnl.Height = WrkspaceHt - (60 * modBasic.$AppScaleFactor)
  If sArrange = "Vertical" Then
    pnl.Arrangement = Arrange.Vertical
  Else If sArrange = "Horizontal" Then
    pnl.Arrangement = Arrange.Horizontal
  Else If sArrange = "Column" Then
    pnl.Arrangement = Arrange.Column
  Endif

  xpic = modBasic.$FormPicture
  xback = modBasic.$FormBackColor
  xfore = modBasic.$FormForeColor
  If xpic And If Exist(xpic) Then
    Try frm.Picture = Image.Load(xpic).Stretch(frm.Width, frm.Height).Picture
  Endif
  If xback Then
    frm.Background = CInt(xback)
  Endif
  If xfore Then
    frm.Foreground = CInt(xfore)
  Endif
  DesignTextLabel(frm)
  RecordFormUse(frm)

  If modBasic.$MultiMediaFormat = "Embedded" Then
    xpanel = New Panel(frm)
    xpanel.Left = 5 * modBasic.$AppScaleFactor
    xpanel.Top = (pnl.Height - (5 * modBasic.$AppScaleFactor)) - (pnl.Left + (10 * modBasic.$AppScaleFactor))
    xpanel.Width = pnl.Left - (5 * modBasic.$AppScaleFactor)
    xpanel.Height = pnl.Left + (10 * modBasic.$AppScaleFactor)
    xpanel.Background = Color.LightGray

    xwork = New Workspace(xpanel)
    xwork.Orientation = Align.Bottom
    xwork.Width = xpanel.Width
    xwork.Height = xpanel.Height + (30 * modBasic.$AppScaleFactor)
    xwork.Top = 0
    xwork.Left = 0
    xwork.Add(fmMediaPlay)
  Endif

End

Public Sub ArrangeFormCentre(frm As Form, Optional LogFmRecord As String, Optional MaxHeight As Boolean)

  Dim xpic As String
  Dim xback As String
  Dim xfore As String
  Dim xfmlog As String
  Dim xval As String
  Dim yval As String

  If LogFmRecord Then
    xfmlog = LogFmRecord
  Else
    xfmlog = "True"
  Endif

  modBasic.DebugString("Setting non-tabbed form for " & frm.Text)
  xpic = modBasic.$FormPicture
  xback = modBasic.$FormBackColor
  xfore = modBasic.$FormForeColor

  frm.Center
  If MaxHeight = True Then
    frm.Height = $DeskHeight - (75 * modBasic.$AppScaleFactor)
    frm.Arrangement = Arrange.Vertical
  Endif
  xval = modSettings.ShowLogValues(frm.Name & "/Left")
  If xval Then
    frm.X = CInt(xval)
  Endif
  yval = modSettings.ShowLogValues(frm.Name & "/Top")
  If yval Then
    frm.Y = CInt(yval)
  Endif

  If xpic And If Exist(xpic) Then
    Try frm.Picture = Image.Load(xpic).Stretch(frm.Width, frm.Height).Picture
  Endif
  If xback Then
    frm.Background = CInt(xback)
  Endif
  If xfore Then
    frm.Foreground = CInt(xfore)
  Endif
  DesignTextLabel(frm)
  If xfmlog = "True" Then
    RecordFormUse(frm)
  Endif

End

Public Sub SaveFormArrangement(frm As Form)

  modSettings.SaveValuesToLog(frm.Name & "/Top", CStr(frm.Y))
  modSettings.SaveValuesToLog(frm.Name & "/Left", CStr(frm.X))

End

Public Sub DesignTextLabel(frm As Form)

  Dim xcont As Control
  Dim xlabel As Label
  Dim xcheckbox As CheckBox
  Dim xtabpanel As TabPanel

  If modBasic.$LabelTextFont Or If modBasic.$LabelForeColor Then
    For Each xcont In frm.Controls

      If xcont Is Label Then
        xlabel = xcont
        If modBasic.$LabelForeColor Then
          xlabel.Foreground = modBasic.$LabelForeColor
        Endif
        If modBasic.$LabelTextFont Then
          xlabel.Font = Font[modBasic.$LabelTextFont]
        Endif

      Else If xcont Is CheckBox Then
        xcheckbox = xcont
        If modBasic.$LabelForeColor Then
          xcheckbox.Foreground = modBasic.$LabelForeColor
        Endif
        If modBasic.$LabelTextFont Then
          xcheckbox.Font = Font[modBasic.$LabelTextFont]
        Endif

      Else If xcont Is TabPanel Then
        xtabpanel = xcont
        If modBasic.$LabelTextFont Then
          xtabpanel.TextFont = Font[modBasic.$LabelTextFont]
        Endif

      Endif

    Next
  Endif

End

Public Sub SetActiveForms()

  $HideFormList = New String[]

End

Public Sub ExitAllWindows()

  Dim frm As Window

  modBasic.DebugString("Closing all windows and exiting Application")

  modSettings.SaveValuesToLog("Handle/Status", "Closed")
  For Each frm In modHelpVariable.FindWorSpace(modHelpVariable.$LogInCategory).Windows
    frm.Close
  Next
  modDatabase.$myConn.Delete("tblsystemlog", "fldindex=&1", $MACAddress)
  modExternal.ExecClosingScript()
  modDevice.CamOnClose()
  modHelpVariable.FindServerSocket(modHelpVariable.$LogInCategory).Close()
  modHelpVariable.FindTransferSocket(modHelpVariable.$LogInCategory).Close()
  modExternal.CloseAdvertise()
  modDatabase.CloseDatabase()
  Dec Application.Busy

End

Public Sub CloseAllWindows()

  Dim mnt As Float

  mnt = Round(Timer() / 60, -2)
  If Message.Question(("Log out application after " & CStr(mnt) & " minutes." & gb.NewLine & "Are you sure?"), ("Yes"), ("No")) = 1 Then
    modHelpVariable.FindWorSpace(modHelpVariable.$LogInCategory).Window.Delete()
  Else
    Stop Event
  Endif

End

Public Sub ShowSelectedFormMenu(frm As Form)

  If $HideFormList.Exist(frm.Tag) = True Then
    frm.Enabled = False
  Endif

End

Public Sub GridViewDecoration(GridView1 As GridView, Row As Integer)

  If Frac(Row / 2) = 0 Then 'odd row
    If modBasic.$DataOddBackColor Then
      GridView1.Data.Background = modBasic.$DataOddBackColor
    Endif
    If modBasic.$DataOddForeColor Then
      GridView1.Data.Foreground = modBasic.$DataOddForeColor
    Endif
  Else
    If modBasic.$DataEvenBackColor Then
      GridView1.Data.Background = modBasic.$DataEvenBackColor
    Endif
    If modBasic.$DataEvenForeColor Then
      GridView1.Data.Foreground = modBasic.$DataEvenForeColor
    Endif
  Endif

End

Public Sub GridExplicitDecoration(GridView1 As GridView, Row As Integer, Column As Integer)

  If Frac(Row / 2) = 0 Then 'odd row
    If modBasic.$DataOddBackColor Then
      GridView1[Row, Column].Background = modBasic.$DataOddBackColor
    Endif
    If modBasic.$DataOddForeColor Then
      GridView1[Row, Column].Foreground = modBasic.$DataOddForeColor
    Endif
  Else
    If modBasic.$DataEvenBackColor Then
      GridView1[Row, Column].Background = modBasic.$DataEvenBackColor
    Endif
    If modBasic.$DataEvenForeColor Then
      GridView1[Row, Column].Foreground = modBasic.$DataEvenForeColor
    Endif
  Endif

End

'
''
'''
''''

'NOTE: ----------------------------- CONTROLS BEHAVIOR --------------------------------
Public Sub GoToNextControlTab()

  If Key.Code = Key.Return Or If Key.Code = Key.Enter Or If Key.Code = Key.AltKey Then
    If Application.ActiveControl
      If Application.ActiveControl.Tag = "Auto" Then
      Else
        Desktop.SendKeys("\t")
      Endif
    Endif
  Endif

End

Public Sub InputUpCaseOnly()

  Select Key.Code
    Case Key.BackSpace, Key.Tab, Key.Delete, Key.Enter, Key.Return, Key.AltKey, Key.Escape
    Default
      If Key.Text And If InStr("ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-/()", Key.Text) = 0 Then Stop Event
  End Select

End

''put on _KeyPress() event
Public Sub InputTextKeyOnly()

  Select Key.Code
    Case Key.BackSpace, Key.Tab, Key.Delete, Key.Enter, Key.Return, Key.AltKey, Key.Escape
    Default
      If Key.Text And If InStr("`~!@#$^*;:{}|'", Key.Text) > 0 Then Stop Event
  End Select

End

Public Sub InputTextSearchKeyOnly()

  Select Key.Code
    Case Key.BackSpace, Key.Tab, Key.Delete, Key.Enter, Key.Return, Key.AltKey, Key.Escape
    Default
      If Key.Text And If InStr("`~!@#$^;:{}|'", Key.Text) > 0 Then Stop Event
  End Select

End

Public Sub SetEncIDPrefix(txtbox As TextBox)

  If modBasic.$AutoEncPrefix = "Yes" Then
    txtbox.Text = modBasic.$EncIdPrefix
    txtbox.Pos = Len(modBasic.$EncIdPrefix)
  Endif

End

'
''
'''
''''

'NOTE: --------------------------- General functions ------------------------------------------
Public Function GetToolTipFromDB(tbl As String, fldtarget As String, fldsource As String, txtsource As String) As String

  Dim xx As String
  Dim res As Result
  Dim sql As String

  sql = Subst("select &1 as col from &2 where &3", fldtarget, tbl, fldsource)
  res = modDatabase.$myConn.Exec(sql & "=&1", txtsource)
  If res.Available = False Then
    xx = ""
  Else If res.Available = True Then
    If res!col Then
      xx = res!col
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

'
''
'''
''''

'NOTE: ------------------------------------- Report Log ---------------------------------
Public Sub SaveMessageLog(sTarget As String, sText As String, sType As String)

  Dim res As Result

  modBasic.DebugString("Inserting Message Log")
  res = modDatabase.$myConn.Create("tblmessagelog")
  res["fldwindow"] = sType
  res["fldtarget"] = sTarget
  res["fldmesstext"] = sText
  res["flduserid"] = $lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = compID
  res["fldhostmac"] = $MACAddress
  res["fldhostuser"] = System.User.Name
  res["fldhostip"] = $localIP
  res["fldhostname"] = System.Host
  res.Update

End

Public Sub SaveSMSEntry(sTarget As String, sText As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblsmslog")
  res["fldwindow"] = modHelpVariable.$LogInCategory
  res["fldtarget"] = sTarget
  res["fldsmstext"] = sText
  res["fldcomment"] = ""
  res["flduserid"] = $lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = compID
  res["fldstatus"] = "Waiting"
  res["fldsmsdate"] = ""

  res["fldhostmac"] = $MACAddress
  res["fldhostuser"] = System.User.Name
  res["fldhostip"] = $localIP
  res["fldhostname"] = System.Host
  res.Update

End

'''------------------------- LogIn Frequency ---------------------------------------
Public Sub LogLoginFrequency()

  Dim xx As Integer
  Dim xver As String

  xver = modSettings.ShowLogValues("LogIn_Frequency/" & Application.Version)
  If xver Then
    xx = CInt(xver)
  Else
    xx = 0
  Endif
  modSettings.SaveValuesToLog("LogIn_Frequency/" & Application.Version, xx + 1)

  If xx = 0 Then
    fmAppUpdate.ShowModal
  Endif

End

''----------------------------------  Send SMS --------------------------------
Public Sub SendSMSData()

  Dim xx As String
  Dim mesStr As String
  Dim sLine As String[]
  Dim sSms As String[]
  Dim arcmd As String[]
  Dim brcmd As String[]
  Dim xout As String

  Dim xpath As String
  Dim xexc As String
  Dim xapi As String
  Dim xstr As String
  Dim apipath As String

  Dim res As Result

  xapi = modSettings.ShowSettingFromFIle("SMSMethod/Default")
  xpath = modSettings.ShowSettingFromFIle("SMS_API/DefaultPath")
  xexc = modSettings.ShowSettingFromFIle("SMS_API/DefaultExec")

  Inc Application.Busy
  res = modDatabase.$myConn.Edit("tblsmslog", "fldstatus=&1", "Waiting")
  If res.Available Then
    For Each res

      If xapi = "SMS API" Then
        If Exist(xpath) Then
          xstr = File.Load(xpath)
          xstr = Replace(xstr, "{SMSPhoneNumber}", res!fldtarget)
          xstr = Replace(xstr, "{SMSMessage}", res!fldsmstext)
          apipath = Temp()
          File.Save(apipath, xstr)

          arcmd = New String[]
          If xexc Then
            arcmd.Add(xexc)
          Endif
          arcmd.Add(apipath)
          modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
          Exec arcmd To xout
          res["fldcomment"] = xout
          res["fldstatus"] = "Sent"
          res["fldsmsdate"] = Now()
          res.Update
        Endif

      Else
        If System.Exist("mmcli") = True Then
          If modDevice.$ModemEnabled = True Then

            mesStr = "--messaging-create-sms=text='" & res!fldsmstext & "',number='" & res!fldtarget & "',delivery-report-request='yes'"
            arcmd = ["mmcli", "-m", modDevice.$ModemIndex, mesStr]
            modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
            Exec arcmd To xx

            sLine = Split(xx, gb.NewLine)
            If Trim(sLine[0]) = "Successfully created new SMS:" Then
              sSms = Split(Trim(sLine[1]), Space(1))
            Endif
            brcmd = ["mmcli", "-s", sSms[0], "--send"]
            modBasic.DebugString("Execute " & brcmd.Join(Space(1)))
            Exec brcmd To xout
            res["fldcomment"] = xout
            res["fldstatus"] = "Sent"
            res["fldsmsdate"] = Now()
            res.Update

          Endif
        Endif
      Endif

    Next
  Endif
  Dec Application.Busy

End

'NOTE: -------------------------------------- GNUPG KEY ---------------------------------------------------
Public Sub SignGnuPgKey(sInFile As String, sigfile As String)

  Dim res As Result
  Dim keyid As String
  Dim prikey As String
  Dim delkey As String
  Dim hFile As Blob

  Dim arcmd As String[]
  Dim brcmd As String[]

  If Exist("/tmp/.gnupg") Then
    modHelpVariable.DeleteFolderRecursive("/tmp/.gnupg")
  Endif

  keyid = modSettings.ShowSettingFromFIle("GeneralSettings/GnuPG_KeyID")
  If keyid Then
    Inc Application.Busy
    res = modDatabase.$myConn.Exec("select fldkeyname,fldfingerprint,fldprivate,fldprilink from tblgnupg where fldkeyid=&1", keyid)
    If res.Available Then
      Mkdir "/tmp/.gnupg"
      If res!fldprilink Then
        Inc Application.Busy
        prikey = modDevice.GetFileFromLocalFTP(res!fldprilink)
        Dec Application.Busy
      Else
        hFile = res["fldprivate"]
        If hFile.Length Then
          prikey = Temp() & ".gpg"
          File.Save(prikey, hFile.Data)
        Endif
      Endif

      arcmd = ["gpg", "--homedir", "/tmp/.gnupg", "--import", prikey]
      modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
      Exec arcmd Wait

      brcmd = ["gpg", "-u", keyid, "--homedir", "/tmp/.gnupg", "-o", sigfile, "--clearsign", sInFile]
      modBasic.DebugString("Execute " & brcmd.Join(Space(1)))
      Exec brcmd Wait

      delkey = "\"" & res!fldfingerprint & "\""
      modBasic.DebugString("Deleting GnuPG Key")
      Shell "gpg --homedir /tmp/.gnupg --batch --yes --quiet --delete-secret-and-public-key " & delkey Wait
      modHelpVariable.DeleteFolderRecursive("/tmp/.gnupg")

    Else
      Message.Warning(("GnuPG Key not found in database"), ("OK"))
      Move sInFile To sigfile
    Endif
    Dec Application.Busy
  Endif

Catch
  Dec Application.Busy
  modHelpVariable.CreateErrorReport()

End

Public Sub VerifyGnuPgKey(sInFile As String, sType As String)

  Dim res As Result
  Dim prikey As String
  Dim keyname As String
  Dim keyid As String
  Dim delkey As String
  Dim hFile As Blob

  Dim arcmd As String[]
  Dim brcmd As String[]
  Dim xcmd As String[]
  Dim ycmd As String

  $virtualTerminal = ""
  If Exist("/tmp/.gnupg") Then
    modHelpVariable.DeleteFolderRecursive("/tmp/.gnupg")
  Endif

  If sType = "Remote" Then

    keyid = modSettings.ShowSettingFromFIle("Report" & "/PDF_GnuPGLink")
    If keyid Then
      keyname = modSettings.ShowSettingFromFIle("Report" & "/PDF_GnuPGName")
      Mkdir "/tmp/.gnupg"
      xcmd = ["wget", keyid, "-P", "/tmp/.gnupg"]
      modBasic.DebugString("Execute " & xcmd.Join(Space(1)))
      Exec xcmd Wait
      prikey = "/tmp/.gnupg" &/ File.Name(keyid)
    Endif

  Else

    keyid = modSettings.ShowSettingFromFIle("GeneralSettings/GnuPG_KeyID")
    If keyid Then
      res = modDatabase.$myConn.Exec("select fldkeyname,fldpublic,fldpublink from tblgnupg where fldkeyid=&1", keyid)
      If res.Available Then
        keyname = res!fldkeyname
        Mkdir "/tmp/.gnupg"
        res.MoveFirst
        If res!fldpublink Then
          Inc Application.Busy
          prikey = modDevice.GetFileFromLocalFTP(res!fldpublink)
          Dec Application.Busy
        Else
          hFile = res["fldpublic"]
          If hFile.Length Then
            prikey = Temp() & ".gpg"
            File.Save(prikey, hFile.Data)
          Endif
        Endif
      Endif
    Endif

  Endif

  If Exist(prikey) Then
    arcmd = ["gpg", "--homedir", "/tmp/.gnupg", "--import", prikey]
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd Wait

    brcmd = ["gpg", "--homedir", "/tmp/.gnupg", "--verify", sInFile]
    modBasic.DebugString("Execute " & brcmd.Join(Space(1)))
    Exec brcmd Wait For Input As "VirtOutput"

    delkey = "\"" & keyname & "\""
    ycmd = "gpg --homedir /tmp/.gnupg --batch --yes --quiet --delete-keys " & delkey
    modBasic.DebugString("Execute " & ycmd)
    Shell ycmd Wait

    modHelpVariable.DeleteFolderRecursive("/tmp/.gnupg")
  Endif

End

Public Sub VirtOutput_Read()

  Dim sLine As String

  Read #Last, sLine, -256
  $virtualTerminal = $virtualTerminal & sLine

End
