' Gambas module file

'NOTE: -----------------------------------------OTHER PARAMETERS -------------------------------
Public Function GetDepartmentAllList(sType As String) As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select flddept from tbldepartment where fldcateg like &1", sType)
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function GetDepartmentWithBedList() As String[]

  Dim res As Result
  Dim xxx As String[]

  res = modDatabase.$myConn.Exec("select distinct(flddept) as col from tbldepartmentbed")
  xxx = modFillContainer.GetListFromResult(res)
  Return xxx.Sort()

End

Public Function RegistrationDeptList() As String[]

  Dim xx As String[]
  Dim xgroup As String

  xgroup = modSettings.ShowSettingFromFIle("RegistrationForm/DefaultDeptGroup")
  If xgroup Then
    xx = modFillContainer.GetListFromResult(modDatabase.$myConn.Exec("select flditemname as col from tbldeptgroup where fldgroupname=&1", xgroup))                                                  ''
  Else
    xx = modMisc.GetDepartmentAllList("%")
  Endif
  Return xx

End

''------------------------------------Bed Transition ------------------------------------------------
Public Function GetDepartmentNameFromBed(sBed As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flddept from tbldepartmentbed where fldbed=&1", sBed)
  If res.Available Then
    If res!flddept Then
      xx = res!flddept
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''----------------------------------- Refer Hosp Code --------------------------------------
Public Function GetHospReferFromCode(sHosp As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldcode from tblreferlist where fldlocation=&1", sHosp)
  If res.Available Then
    If res!fldcode Then
      xx = res!fldcode
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''--------------- GNUPG Key ------------------------------
Public Function GetGNUPGKeyList() As String[]

  Dim xx As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldkeyid from tblgnupg")
  xx = modFillContainer.GetListFromResult(res)
  Return xx

End

'NOTE: -------------------------------- SPINBOX RECORD ---------------------------------------------
Public Function RecordNumberLabel(startno As Long, diffno As Integer, totno As Long) As String

  Dim xx As String

  If totno = 0 Then
    xx = "0 out of 0"
  Else If totno > startno + diffno Then
    xx = CStr(startno + 1) & " - " & CStr(startno + diffno) & " out of " & CStr(totno)
  Else If totno <= startno + diffno Then
    xx = CStr(startno + 1) & " - " & CStr(totno) & " out of " & CStr(totno)
  Endif
  Return xx

Catch
  modHelpVariable.CreateErrorReport()

End

Public Function BlobTarget(sType As String) As String

  Dim xx As String
  Dim xauto As String

  xauto = modGlobalSetting.ShowSettingFromDB("GeneralSettings/Upload_" & sType)
  If xauto Then
    xx = xauto
  Else
    xx = "DB"
  Endif
  Return xx

End

Public Function CustomReportList() As String[]

  Dim xx As String[]

  xx = New String[]
  If modSettings.ShowSettingFromFIle("ExtraReport1/Name") Then
    xx.Add("ExtraReport1")
  Endif

  If modSettings.ShowSettingFromFIle("ExtraReport2/Name") Then
    xx.Add("ExtraReport2")
  Endif

  If modSettings.ShowSettingFromFIle("ExtraReport3/Name") Then
    xx.Add("ExtraReport3")
  Endif

  If modSettings.ShowSettingFromFIle("ExtraReport4/Name") Then
    xx.Add("ExtraReport4")
  Endif

  If modSettings.ShowSettingFromFIle("CustomReport5/Name") Then
    xx.Add("ExtraReport5")
  Endif

  Return xx

End

Public Sub LockReportOutput(rbReported As RadioButton, rbVerified As RadioButton, xPanel As Panel)

  Dim xval As String

  xval = modSettings.ShowSettingFromFIle("Laboratory/OutputLock")
  If xval = "Reported" Then
    rbReported.Value = True
    xPanel.Enabled = False
  Else If xval = "Verified" Then
    rbVerified.Value = True
    xPanel.Enabled = False
  Else
    rbReported.Value = True
    xPanel.Enabled = True
  Endif

End

''For Departmental string containing ..:1234
Public Function GetStringWithoutIndex(sExam As String) As String

  Dim asx As String[]
  Dim xx As String

  asx = Split(sExam, ":")
  xx = Trim(asx[0])
  Return xx

End

Public Function GetReportOptionList() As String[]

  Dim xx As String[]
  Dim i As Integer

  xx = New String[]
  For i = 10 To 99
    xx.Add("&" & CStr(i))
  Next
  Return xx

End

Public Function GetColorValSymbol(sColor As Integer) As String

  Dim xx As String

  If sColor = Color.Red Then
    xx = "R"
  Else If sColor = Color.Blue Then
    xx = "B"
  Else If sColor = Color.Green Then
    xx = "G"
  Else If sColor = Color.Yellow Then
    xx = "Y"
  Else If sColor = Color.Black Then
    xx = "#"
  Else
    xx = ""
  Endif
  Return xx

End

Public Function GetColorCode(sColor As String) As Integer

  Dim xx As Integer

  If sColor = "Red" Then
    xx = Color.Red
  Else If sColor = "Yellow" Then
    xx = Color.Yellow
  Else If sColor = "Green" Then
    xx = Color.Green
  Else If sColor = "Blue" Then
    xx = Color.Blue
  Else If sColor = "Black" Then
    xx = Color.Black
  Endif
  Return xx

End

Public Function HospField(Optional sTable As String) As String

  Dim xx As String

  xx = ""
  Return xx

End

Public Function LockBoolean(sText As String) As Boolean

  Dim xx As Boolean

  If sText = "No" Then
    xx = True
  Else
    xx = False
  Endif
  Return xx

End
