' Gambas module file

Public $HostLoginPassword As String

'NOTE: ----------------------------------- Simple Encryption/Decryption ------------------------------------
Public Function EncryptSimple(txtinput As String) As String

  Dim xx As String

  ''encrypt password
  If txtinput Then
    xx = Base64(txtinput)
  Else
    xx = ""
  Endif

  Return xx

End

Public Function DecryptSimple(txtoutput As String) As String

  Dim xx As String

  ''decrypt password
  If txtoutput Then
    xx = UnBase64(txtoutput)
  Else
    xx = ""
  Endif

  Return xx

End

'NOTE: ------------------------------ SSL Encryption/Decryption -----------------------
Public Function EncryptSSL(txtinput As String) As String

  Dim xx As String

  ''encrypt password
  If txtinput Then
    xx = Base64(txtinput)
  Else
    xx = ""
  Endif

  Return xx

End

Public Function DecryptSSL(txtoutput As String) As String

  Dim xx As String

  ''decrypt password
  If txtoutput Then
    xx = UnBase64(txtoutput)
  Else
    xx = ""
  Endif

  Return xx

End

''--------------------------- Patient Profile Encryption --------------------------------
Public Function EncryptPatSimple(txtinput As String) As String

  Dim xx As String

  If txtinput Then
    xx = EncryptSSL(txtinput)
  Else
    xx = ""
  Endif
  Return xx

End

Public Function EncryptPatData(sText As String) As String

  Dim xx As String

  If modBasic.$PatInfoEncrypt = True Then
    xx = EncryptPatSimple(sText)
  Else
    xx = sText
  Endif
  Return xx

End

Public Function DecryptPatSimple(txtoutput As String) As String

  Dim xx As String

  If txtoutput Then
    xx = DecryptSSL(txtoutput)
  Else
    xx = ""
  Endif
  Return xx

End

Public Function DecryptPatData(sText As String, sEncrypt As Boolean) As String

  Dim xx As String

  If sEncrypt = True Then
    xx = DecryptPatSimple(sText)
  Else
    xx = sText
  Endif
  Return xx

End

''------------------------------ DB Password Encryption/Decryption ----------------------------
Public Function EncryptDBPass(txtinput As String, UseSSL As Boolean) As String

  Dim xval As String

  If txtinput Then
    If UseSSL = True Then
      xval = EncryptSSL(txtinput)
    Else
      xval = EncryptSimple(txtinput)
    Endif
  Else
    xval = ""
  Endif
  Return xval

End

Public Function DecryptDBPass(txtoutput As String, UseSSL As Boolean) As String

  Dim xval As String

  If UseSSL = True Then
    xval = DecryptSSL(txtoutput)
  Else
    xval = DecryptSimple(txtoutput)
  Endif
  Return xval

End

'NOTE:------------------------------ LogIn Parameter --------------------------------
Public Function LogInActiveDuration(usr As String) As Boolean

  Dim sql As String
  Dim res As Result
  Dim xx As Boolean

  sql = "select fldfromdate,fldtodate from tbluser where flduserid=&1"
  res = modDatabase.$myConn.Exec(sql, usr)
  If res.Available = True Then
    If res!fldfromdate <= Date() And If res!fldtodate >= Date() Then
      xx = True
    Else
      xx = False
    Endif
  Else
    xx = False
  Endif
  Return xx

End
