' Gambas module file

''28-Oct-2016: version 0.3.12: Removing Journal Lock as it is not so (?) important and locks table several times during one procedure

Public Sub FillJournalRecord(dCateg As String, dLfno As String, cCateg As String, cLfno As String, jAmt As Float, jref As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tbljournal")
  res["flddebitcateg"] = dCateg
  res["flddebitlfno"] = dLfno
  res["fldcreditcateg"] = cCateg
  res["fldcreditlfno"] = cLfno
  res["flddate"] = Now()
  res["fldamt"] = jAmt
  res["flduser"] = modGeneralMain.$lbluser
  res["fldcomp"] = modGeneralMain.compID
  res["fldreference"] = jref
  res["xyz"] = False
  res.Update()
  'dont catch error. error will roll back

End
