' Gambas module file

'NOTE: ----------------- INSERT for tblpatbilling and tblpatbilldetail --------------------------------------
''ONLY FOR IRD REQUIREMENT
Public Sub InsertBillLog(encid As String, billno As String, itemAmt As Float, taxAmt As Float, discountAmt As Float)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblfiscal")
  res["fldfiscal"] = modDate.GetNepaliFiscalYear(Now())
  res["fldbillno"] = billno
  res["fldpatname"] = modPatient.GetPatientNameByEnc(encid)
  res["fldpan"] = modPatient.GetPatientExtCOdebyEnc(encid)
  res["flddate"] = Date()
  res["flditemamt"] = itemAmt
  res["flddiscountamt"] = discountAmt
  res["fldtaxable"] = itemAmt - discountAmt
  res["fldtaxamt"] = taxAmt
  res["fldtotamt"] = (itemAmt + taxAmt) - discountAmt
  res["fldsync"] = "No"
  res["fldprinted"] = "Printed"
  res["fldactive"] = "Active"
  res["fldtime"] = Time()
  res["fldpunch"] = modGeneralMain.$lbluser
  res["fldprint"] = modGeneralMain.$lbluser
  res["xyz"] = False
  res.Update

End

''"Done" at saving lab order from clinic, saving pharmacy items, saving cash items, saving return items so requirement fldsave=0 and fldprint=0
''"Cleared after billing so used after "Done" and "Sampled" so requirement is only fldsave=1 and fldprint=0 so allowed at any step after fldsave=1
''Sampling allowed for "Done" from clinic,cash and "Cleared" from cash and lead to "Sampled"
Public Sub InsertBillDetail(encid As String, billno As String, biltyp As String, prevdeposit As Float, itemAmt As Float, taxAmt As Float, discountAmt As Float, chargedAmt As Float, receivedAmt As Float, curdeposit As Float, sCheq As String, sBank As String, Optional taxgroup As String, Optional discgroup As String)

  Dim res As Result
  Dim taxcateg As String
  Dim dsccateg As String

  If taxgroup Then
    taxcateg = taxgroup
  Else
    taxcateg = ""
  Endif
  If discgroup Then
    dsccateg = discgroup
  Else
    dsccateg = ""
  Endif

  res = modDatabase.$myConn.Create("tblpatbilldetail")
  res["fldbillno"] = billno
  res["fldencounterval"] = encid
  res["fldprevdeposit"] = prevdeposit
  res["flditemamt"] = itemAmt
  res["fldtaxamt"] = taxAmt
  res["fldtaxgroup"] = taxcateg
  res["flddiscountamt"] = discountAmt
  res["flddiscountgroup"] = dsccateg
  res["fldchargedamt"] = chargedAmt
  res["fldreceivedamt"] = receivedAmt
  res["fldcurdeposit"] = curdeposit
  res["fldbilltype"] = biltyp
  res["fldchequeno"] = sCheq
  res["fldbankname"] = sBank
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = True
  res["fldhostmac"] = modGeneralMain.$MACAddress
  res["xyz"] = False
  res.Update()
  'dont catch error. Error will rollback

End

Public Sub InsertBillViewCount(billno As String)

  Dim res1 As Result

  res1 = modDatabase.$myConn.Create("tblpatbillcount")
  res1["fldbillno"] = billno
  res1["fldcount"] = 1
  res1.Update

  'dont catch error. Error will rollback

End

'''for two step entry for billing at last '''''Use General Services etc for Type
Public Sub InsertBlankBillItem(encid As String, sBillMode As String, itemtyp As String, itemNo As Integer, itemname As String, rte As Float, qty As Float, tax As Float, disc As Float, status As String, parentNo As Long, sav As Boolean, prt As Boolean, Optional target As String, Optional sPayable As String, Optional sRefer As String, Optional sReason As String, Optional ReturnBill As String)                                       ''

  Dim res As Result
  Dim sPay As String
  Dim sRef As String
  Dim sTarg As String
  Dim sReas As String
  Dim sRetBill As String

  Dim xtaxamt As Float
  Dim xdscamt As Float
  Dim xtotamt As Float
  Dim xdue As Float

  If sPayable Then
    sPay = sPayable
  Else
    sPay = ""
  Endif
  If sRefer Then
    sRef = sRefer
  Else
    sRef = ""
  Endif
  If target Then
    sTarg = target
  Else
    sTarg = ""
  Endif
  If sReason Then
    sReas = sReason
  Else
    sReas = ""
  Endif
  If ReturnBill Then
    sRetBill = ReturnBill
  Else
    sRetBill = ""
  Endif

  xdue = rte * qty
  xdscamt = xdue * (disc / 100)
  xtaxamt = xdue * (1 - disc / 100) * (tax / 100)
  xtotamt = xdue * (1 - disc / 100) * (1 + tax / 100)

  res = modDatabase.$myConn.Create("tblpatbilling")
  res["fldencounterval"] = encid
  res["fldbillingmode"] = sBillMode
  res["flditemtype"] = itemtyp
  res["flditemno"] = itemNo
  res["flditemname"] = itemname
  res["flditemrate"] = rte
  res["flditemqty"] = qty
  res["fldtaxper"] = tax
  res["flddiscper"] = disc
  res["fldtaxamt"] = xtaxamt
  res["flddiscamt"] = xdscamt
  res["fldditemamt"] = xtotamt
  res["fldbillno"] = ""
  res["fldstatus"] = status

  res["fldorduserid"] = modGeneralMain.$lbluser
  res["fldordtime"] = Now()
  res["fldordcomp"] = modGeneralMain.compID

  If sav = True Then
    res["flduserid"] = modGeneralMain.$lbluser
    res["fldtime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
  Else
    res["flduserid"] = ""
    res["fldtime"] = ""
    res["fldcomp"] = ""
  Endif

  res["fldsave"] = sav
  res["fldprint"] = prt
  res["fldalert"] = True
  res["fldtarget"] = sTarg
  res["fldparent"] = parentNo
  res["fldpayto"] = sPay
  res["fldrefer"] = sRef
  res["fldreason"] = sReas
  res["fldretbill"] = sRetBill
  res["fldretqty"] = 0
  res["fldsample"] = "Waiting"
  res["xyz"] = False
  res.Update()
  'dont catch error. Error will rollback

End

'used in cash billing
Public Sub ServiceBillBlank(encid As String, sBillingMode As String, sRoute As String, itemname As String, qty As Float, tax As Float, disc As Float, status As String, parentNo As Long, sav As Boolean, prt As Boolean, Optional sPayable As String, Optional sRefer As String)

  Dim itemtyp As String
  Dim itemNo As Integer
  Dim rte As Float

  Dim sRef As String
  Dim sPay As String
  Dim target As String

  If sRefer Then
    sRef = sRefer
  Else
    sRef = ""
  Endif
  If sPayable Then
    sPay = sPayable
  Else
    sPay = ""
  Endif

  itemtyp = modNonMedical.GetBillItemCategoryFromCombo(sRoute)
  itemNo = modNonMedical.GetCashBillItemID(itemname, sRoute)
  rte = modNonMedical.GetCashBillItemCost(itemname, itemtyp)
  target = modNonMedical.GetBillingTargeDept(itemname, itemtyp)
  InsertBlankBillItem(encid, sBillingMode, itemtyp, itemNo, itemname, rte, qty, tax, disc, status, parentNo, sav, prt, target, sPay, sRef)
  'dont catch error. Error will rollback

End

''used for autobilling
Public Sub ServiceBillBlankTaxDisc(encid As String, sBillingMode As String, sRoute As String, itemname As String, qty As Float, status As String, parentNo As Long, sav As Boolean, prt As Boolean, Optional sPayable As String, Optional sRefer As String, Optional sTarget As String)

  Dim itemtyp As String
  Dim itemNo As Integer

  Dim rte As Float
  Dim tax As Float
  Dim disc As Float

  Dim sPay As String
  Dim sRef As String
  Dim target As String

  itemtyp = modNonMedical.GetBillItemCategoryFromCombo(sRoute)
  itemNo = modNonMedical.GetCashBillItemID(itemname, sRoute)

  If sPayable Then
    sPay = sPayable
  Else
    sPay = ""
  Endif
  If sRefer Then
    sRef = sRefer
  Else
    sRef = ""
  Endif
  If sTarget Then
    target = sTarget
  Else
    target = modNonMedical.GetBillingTargeDept(itemname, itemtyp)
  Endif

  rte = modNonMedical.GetCashBillItemCost(itemname, itemtyp)
  tax = modNonMedical.ShowTaxValues(itemtyp, itemname)
  disc = modNonMedical.DiscPercentForItem(encid, itemtyp, itemname)

  If modBasic.$AutoBillSaveZero = "Yes" Then
    If rte = 0 Or If disc = 100 Then
      InsertBlankBillItem(encid, sBillingMode, itemtyp, itemNo, itemname, rte, qty, tax, disc, "Done", parentNo, True, prt, target, sPay, sRef)
    Else
      InsertBlankBillItem(encid, sBillingMode, itemtyp, itemNo, itemname, rte, qty, tax, disc, status, parentNo, sav, prt, target, sPay, sRef)
    Endif
  Else
    InsertBlankBillItem(encid, sBillingMode, itemtyp, itemNo, itemname, rte, qty, tax, disc, status, parentNo, sav, prt, target, sPay, sRef)
  Endif
  'dont catch error. Error will rollback

End

Public Sub UpdateGroupBillQTY(sParent As Long, encid As String, itemname As String, sQty As Float)

  Dim res1 As Result
  Dim xval As Float

  ''update main bill
  res1 = modDatabase.$myConn.Edit("tblpatbilling", "fldid=&1 and fldencounterval=&2 and flditemname=&3", sParent, encid, itemname)
  If res1.Available Then
    xval = res1["flditemqty"] + sQty
    res1["flditemqty"] = xval
    res1["fldtaxamt"] = res1!flditemrate * xval * (1 - res1!flddiscper / 100) * (res1!fldtaxper / 100)
    res1["flddiscamt"] = res1!flditemrate * xval * (res1!flddiscper / 100)
    res1["fldditemamt"] = res1!flditemrate * xval * (1 - res1!flddiscper / 100) * (1 + res1!fldtaxper / 100)
    res1["xyz"] = False
    res1.Update
  Endif
  'dont catch error. Error will rollback

End

Public Sub UpdateReturnBillQTY(sParent As Long, encid As String, itemname As String, RetQty As Float)

  Dim res1 As Result

  ''update main bill
  res1 = modDatabase.$myConn.Edit("tblpatbilling", "fldid=&1 and fldencounterval=&2 and flditemname=&3", sParent, encid, itemname)
  If res1["fldretqty"] Then
    res1["fldretqty"] = res1["fldretqty"] - RetQty
  Else
    res1["fldretqty"] = 0 - RetQty
  Endif
  res1["xyz"] = False
  res1.Update
  'dont catch error. Error will rollback

End

Public Sub UpdatewithBillNo(did As Long, billno As String, status As String)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpatbilling", "fldid=&1", did)
  res["fldbillno"] = billno
  res["fldprint"] = True
  res["fldstatus"] = status
  res["xyz"] = False
  res.Update()
  'dont catch error. Error will rollback

End

'Registration autobilling
Public Function InsertRegistrationBilling(encid As String, sDept As String, sBillMode As String, Optional sPayable As String) As Boolean

  Dim xx As Boolean
  Dim res As Result
  Dim sPay As String
  Dim xset As String

  If sPayable Then
    sPay = sPayable
  Else
    sPay = ""
  Endif
  xset = modBasic.$AutoRegistBilling

  xx = False
  If xset Then
    res = modDatabase.$myConn.Exec("select flditemtype,flditemname,flditemqty,fldexitemtype,fldcutoff from tblautogroup where fldgroup=&1 and fldbillingmode=&2", sDept, sBillMode)
    If res.Available Then
      For Each res
        If res!fldexitemtype Then

          If res!fldexitemtype = "Before" Then
            If Time(res!fldcutoff) > Time() Then
              If xset = "Yes" Then
                ServiceBillBlankTaxDisc(encid, sBillMode, res!flditemtype, res!flditemname, res!flditemqty, "Done", 0, True, False, sPay)
              Else If xset = "Partial" Then
                ServiceBillBlankTaxDisc(encid, sBillMode, res!flditemtype, res!flditemname, res!flditemqty, "Punched", 0, False, False, sPay)
              Endif
            Endif
          Else If res!fldexitemtype = "After" Then
            If Time(res!fldcutoff) < Time() Then
              If xset = "Yes" Then
                ServiceBillBlankTaxDisc(encid, sBillMode, res!flditemtype, res!flditemname, res!flditemqty, "Done", 0, True, False, sPay)
              Else If xset = "Partial" Then
                ServiceBillBlankTaxDisc(encid, sBillMode, res!flditemtype, res!flditemname, res!flditemqty, "Punched", 0, False, False, sPay)
              Endif
            Endif
          Else
            If xset = "Yes" Then
              ServiceBillBlankTaxDisc(encid, sBillMode, res!flditemtype, res!flditemname, res!flditemqty, "Done", 0, True, False, sPay)
            Else If xset = "Partial" Then
              ServiceBillBlankTaxDisc(encid, sBillMode, res!flditemtype, res!flditemname, res!flditemqty, "Punched", 0, False, False, sPay)
            Endif
          Endif

        Else
          If xset = "Yes" Then
            ServiceBillBlankTaxDisc(encid, sBillMode, res!flditemtype, res!flditemname, res!flditemqty, "Done", 0, True, False, sPay)
          Else If xset = "Partial" Then
            ServiceBillBlankTaxDisc(encid, sBillMode, res!flditemtype, res!flditemname, res!flditemqty, "Punched", 0, False, False, sPay)
          Endif

        Endif
      Next
      xx = True
    Else
      xx = True
    Endif

  Else
    xx = True
  Endif

  Return xx
  ''dont catch error. allow rollback

End

'' all to do when a person discharge/LAMA/Death/Refer
Public Sub ExitPatientWithBillingOfService(encid As String)

  Dim res As Result
  Dim hr As Float
  Dim bedno As String
  Dim xitem As String
  Dim autobil As String
  Dim unitrate As String

  bedno = modPatient.GetPatientLocation(encid)
  res = modDatabase.$myConn.Exec("select fldid,flditem,fldfirsttime,fldfirstreport from tblpattiming where fldencounterval=&1 and fldtype=&2 and fldfirstsave=&3 and fldsecondsave=&4 and fldfirstreport=&5", encid, "General Services", True, False, "Bed")                                                                   ''
  If res.Available = True Then
    res.MoveLast

    Inc Application.Busy
    modDatabase.$myConn.Begin
    autobil = modBasic.$AutoBillService
    xitem = modNonMedical.GetDepartmentChargeMode(res!flditem)
    modPatientGeneral.UpdatePatientTableSecondTime(res!fldid, bedno)

    unitrate = modNonMedical.GetBillingTargeDept(xitem, "General Services")
    hr = modPatientGeneral.GetServiceUseDuration(encid, "General Services", res!flditem, unitrate, res!fldfirsttime, Now())

    If autobil = "Yes" Or If autobil = "Full" Or If autobil = "Partial" Then
      If xitem Then
        modBillings.EnterBillingForInterval(autobil, "Service", encid, xitem, hr, 0)
      Endif
    Endif
    modDatabase.$myConn.Commit
    Dec Application.Busy
  Endif

Catch
  modDatabase.$myConn.Rollback
  Dec Application.Busy
  modHelpVariable.CreateErrorReport()

End

'insert auto billing for equipment and service
Public Sub EnterBillingForInterval(autoBilling As String, sType As String, encid As String, txtitem As String, txthr As Float, id As Long, Optional sPayable As String)

  Dim rte As Float
  Dim xx As String

  If sPayable Then
    xx = sPayable
  Else
    xx = ""
  Endif

  rte = modNonMedical.GetCashBillItemCost(txtitem, modNonMedical.GetBillItemCategoryFromCombo(sType))
  If rte Then
    If autoBilling = "Yes" Or If autoBilling = "Full" Then
      ServiceBillBlankTaxDisc(encid, modBillings.GetDefaultIPCashMode(sType, encid), sType, txtitem, txthr, "Done", id, True, False, xx)
    Else If autoBilling = "Partial" Then
      ServiceBillBlankTaxDisc(encid, modBillings.GetDefaultIPCashMode(sType, encid), sType, txtitem, txthr, "Punched", id, False, False, xx)
    Endif
  Endif
  'don't catch error. ALWAYS USED WITH TRABSACTION SAFE MODE

End
'
''
'''
''''

'NOTE: -------------------------- Invoice Functions -------------------------------------------
Public Function GetBillingItemFromID(xid As Long) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flditemname from tblpatbilling where fldid=&1", xid)
  If res.Available Then
    xx = res!flditemname
  Else
    xx = ""
  Endif
  Return xx

End

''Get encounter from bill no
Public Function GetEncounterFromBillNo(billno As String) As String

  Dim enc As String
  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldencounterval from tblpatbilldetail where fldbillno=&1", billno)
  If res.Available Then
    If res!fldencounterval Then
      enc = res!fldencounterval
    Else
      enc = ""
    Endif
  Else
    enc = ""
  Endif
  Return enc

End

Public Function GetVOucherIDFromBillNo(voucherno As String) As Long

  Dim res As Result
  Dim xx As Long

  res = modDatabase.$myConn.Exec("select fldid from tblextrareceipt where fldreference=&1", voucherno)
  If res.Available Then
    xx = res!fldid
  Else
    xx = 0
    Message.Warning(voucherno & (" not correct"), ("OK"))
  Endif
  Return xx

End

Public Function GetBillIDFromBillNo(billno As String) As Long

  Dim res As Result
  Dim xx As Long

  res = modDatabase.$myConn.Exec("select fldid from tblpatbilldetail where fldbillno=&1", billno)
  If res.Available Then
    xx = res!fldid
  Else
    xx = 0
    Message.Warning(billno & (" not correct"), ("OK"))
  Endif
  Return xx

End

Public Function GetInvoicePrintCount(billno As String) As Integer

  Dim res As Result
  Dim xcount As Integer

  res = modDatabase.$myConn.Exec("select SUM(fldcount) as cnt from tblpatbillcount where fldbillno=&1", billno)
  If res.Available Then
    If res!cnt Then
      xcount = res["cnt"]
    Else
      xcount = 1
    Endif
  Else
    xcount = 1
  Endif
  Return xcount

End

Public Function GetCopyBillTypeFromBillNo(billno As String) As String

  Dim xx As String
  Dim xcnt As String

  xcnt = CStr(GetInvoicePrintCount(billno))
  xx = "COPY OF ORIGINAL (Print: " & xcnt & ")"
  Return xx

End

'
''
'''
''''

'NOTE: ------------------------- Components of Invoice  -----------------------------------------
Public Function GetBatchForBillFromCategory(txtitemno As Long, txtcateg As String) As String

  Dim bch As String

  If txtcateg = "Medicines" Or txtcateg = "Surgicals" Or txtcateg = "Extra Items" Then
    bch = modStock.GetBatchFromStockNo(txtitemno)
  Else
    bch = ""
  Endif
  Return bch

End

Public Function GetExpiryForBillFromCategory(txtitemno As Long, txtcateg As String) As String

  Dim bch As String

  If txtcateg = "Medicines" Or txtcateg = "Surgicals" Or txtcateg = "Extra Items" Then
    If modBasic.$BillExpiryFormat Then
      bch = Format(modStock.GetExpiryFromStockNo(txtitemno), modBasic.$BillExpiryFormat)
    Else
      bch = Format(modStock.GetExpiryFromStockNo(txtitemno), gb.MediumDate)
    Endif
  Else
    bch = ""
  Endif
  Return bch

End

Public Function GetIteminFormatForBill(txtitemname As String, txtcateg As String) As String

  Dim bch As String

  If txtcateg = "Medicines" Then
    If modBasic.$BillMedicineFormat Then
      bch = modPharmLabel.GetMedicineNameOptionType(txtitemname, modBasic.$BillMedicineFormat)
    Else
      bch = txtitemname
    Endif
  Else
    bch = txtitemname
  Endif

  Return bch

End

Public Function GetReceivedAMTinBill(bill As String) As Float

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select fldreceivedamt from tblpatbilldetail where fldbillno=&1", bill)
  If res.Available Then
    If res!fldreceivedamt Then
      xx = res!fldreceivedamt
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetInvoiceAmountBetweenBills(sUser As String, bill1 As String, bill2 As String, sComp As String) As Float

  Dim bilid1 As Long
  Dim bilid2 As Long
  Dim res As Result
  Dim xtot As Float

  bilid1 = modBillings.GetBillIDFromBillNo(bill1)
  bilid2 = modBillings.GetBillIDFromBillNo(bill2)
  If bilid1 And If bilid2 Then
    res = modDatabase.$myConn.Exec("select SUM(fldreceivedamt) as tot from tblpatbilldetail where fldid>=&1 and fldid<=&2 and flduserid like &3 and fldcomp like &4", bilid1, bilid2, sUser, sComp)
    If res.Available Then
      If res!tot Then
        xtot = res!tot
      Else
        xtot = 0
      Endif
    Else
      xtot = 0
    Endif
  Else
    xtot = 0
  Endif
  Return xtot

End

'NOTE: ----------------------------------- Billing Rules ---------------------------------------------

'sub total for tblpatbilling as (flditemrate*flditemqty*(1-flddiscper/100)*(1+fldtaxper/100)) as tot
Public Function GetRoundupAccToSetting(txtfir As Float) As Float

  Dim rcv As Float

  If modBasic.$BillAmtRounding = "Yes" Then
    rcv = Round(txtfir, 0)
  Else
    rcv = txtfir
  Endif
  Return rcv
  'dont catch error. Error will rollback

End
'
''
'''
''''

'NOTE: ------------------------------ SET User Change Tax/Disc ---------------------------------------------
'while punching
Public Sub SetCashBillingTaxDiscountText(txttax As ValueBox, txtdisc As ValueBox)

  Dim tax As String
  Dim disc As String

  tax = modBasic.$BillFixTax
  If tax = "Yes" Then
    txttax.ReadOnly = True
  Else If tax = "No" Then
    txttax.ReadOnly = False
  Else If tax = "Zero" Then
    txttax.Value = 0
    txttax.ReadOnly = True
  Endif

  disc = modBasic.$BillFixDisc
  If disc = "Yes" Then
    txtdisc.ReadOnly = True
  Else If disc = "No" Then
    txtdisc.ReadOnly = False
  Else If disc = "Zero" Then
    txtdisc.Value = 0
    txtdisc.ReadOnly = True
  Endif

End

'for fmBillentry
Public Sub SetCashBillingTaxDiscountTextTwo(txttax As ValueBox, txttaxamt As ValueBox, txtdisc As ValueBox, txtdiscamt As ValueBox)

  If modBasic.$BillFixSumTax = "No" Then
    txttax.ReadOnly = False
    txttaxamt.ReadOnly = False
  Else
    txttax.ReadOnly = True
    txttaxamt.ReadOnly = True
  Endif

  If modBasic.$BillFixSumDisc = "No" Then
    txtdisc.ReadOnly = False
    txtdiscamt.ReadOnly = False
  Else
    txtdisc.ReadOnly = True
    txtdiscamt.ReadOnly = True
  Endif

End
'
''
'''
''''

'NOTE: ------------------------------------ Registration Discount Mode ----------------------------
Public Function GetPatientFixDisc(patno As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flddiscount from tblpatientinfo where fldpatientval=&1", patno)
  If res.Available Then
    res.MoveFirst
    If res!flddiscount Then
      xx = res!flddiscount
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

Public Sub GetDefaultDiscountCombo(patno As String, cmbdisc As ComboBox)

  If modBasic.$RegistDiscountType = "Planned" Then
    cmbdisc.Text = GetPatientFixDisc(patno)
  Else
    cmbdisc.Text = ""
  Endif

  If Not cmbdisc.Text Then
    If modBasic.$RegistDiscountMode Then
      cmbdisc.Text = modBasic.$RegistDiscountMode
    Endif
  Endif

  If cmbdisc.Text Then
    If modBasic.$RegistDiscountFix = "Yes" Then
      cmbdisc.Enabled = False
    Else
      cmbdisc.Enabled = True
    Endif
  Endif

End

'NOTE: ------------------------------------- billing mode/schedule  ------------------------------------------
Public Function GetDefaultIPCashMode(sType As String, encid As String) As String

  Dim modLst As String[]
  Dim xx As String
  Dim xauto As String

  modLst = modNonMedical.FillCashModeCombo()
  If modLst.Count = 1 Then
    xx = modLst[0]
  Else

    If modGlobalSetting.ShowSettingFromDB("IPBillingMode_Input/" & sType) = "Custom" Then
      xauto = modGlobalSetting.ShowSettingFromDB("IPBillingMode/" & sType)
      If xauto Then
        xx = xauto
      Else
        xx = modPatient.GetPatBillingMode(encid)
      Endif
    Else
      xx = modPatient.GetPatBillingMode(encid)
    Endif

  Endif
  Return xx

End

Public Function DefaultOpBillingMode(encid As String, compid As String) As String

  Dim modLst As String[]
  Dim xx As String
  Dim encmode As String
  Dim smode As String
  Dim xauto As String
  Dim yauto As String

  modLst = modNonMedical.FillCashModeCombo()
  If modLst.Count = 1 Then
    smode = modLst[0]
  Else

    xauto = modGlobalSetting.ShowSettingFromDB("BillingGroup/DefaultMode")
    If xauto Then
      xx = xauto
    Else
      xx = modPatient.GetPatBillingMode(encid)
    Endif

    yauto = modGlobalSetting.ShowSettingFromDB("BillingGroup/ScheduleMode")
    If yauto Then
      If yauto = "Scheduled" Then
        smode = GetScheduledBillingMode(compid)
        If smode = "" Then
          smode = xx
        Endif
      Else If yauto = "Encounter" Then
        encmode = modPatient.GetPatBillingMode(encid)
        If encmode Then
          smode = encmode
        Else
          smode = xx
        Endif
      Else
        smode = xx
      Endif
    Else
      smode = xx
    Endif

  Endif
  Return smode

End

Public Sub GetBillingComboDefaultMode(cmb As ComboBox, encid As String, compid As String)

  cmb.Text = DefaultOpBillingMode(encid, compid)
  If modGlobalSetting.ShowSettingFromDB("BillingGroup/FixMode") = "Yes" Then
    cmb.Enabled = False
  Else
    cmb.Enabled = True
  Endif

End

Private Function GetScheduledBillingMode(compid As String) As String

  Dim bilmode As String
  Dim sday As String
  Dim smonth As String
  Dim aSday As String[]
  Dim aSmonth As String[]

  Dim res As Result
  Dim xx As String
  Dim yy As String

  Dim dayval As Boolean
  Dim monval As Boolean
  Dim timval As Boolean

  sday = Left(modDate.GetWeekDay(Now()), 3)
  smonth = modDate.GetMonthName(Now())
  bilmode = ""

  res = modDatabase.$myConn.Exec("select fldbillingmode,fldtime,fldfromtime,fldtotime,fldday,flddaysvalue,fldmonth,fldmonthsvalue from tblschedule where fldcomp=&1", compid)
  For Each res

    dayval = False
    If res!fldday = "All" Then
      dayval = True
    Else
      aSday = Split(res!flddaysvalue, "*;*")
      For Each xx In aSday
        If xx = sday Then
          dayval = True
          Break
        Endif
      Next
    Endif

    monval = False
    If res!fldmonth = "All" Then
      monval = True
    Else
      aSmonth = Split(res!fldmonthsvalue, "*;*")
      For Each yy In aSmonth
        If yy = smonth
          monval = True
          Break
        Endif
      Next
    Endif

    timval = False
    If res!fldtime = "All" Then
      timval = True
    Else
      If Time(res!fldfromtime) <= Time() And If Time(res!fldtotime) >= Time() Then
        timval = True
      Endif
    Endif

    If dayval = True And If monval = True And If timval = True Then
      bilmode = res!fldbillingmode
      Break
    Endif
  Next

  Return bilmode

End

Public Function DefaultRegistBillingMode(compid As String) As String

  Dim modLst As String[]
  Dim xx As String
  Dim smode As String

  modLst = modNonMedical.FillCashModeCombo()
  If modLst.Count = 1 Then
    smode = modLst[0]
  Else

    If modBasic.$RegistDefaultMode Then
      xx = modBasic.$RegistDefaultMode
    Else
      xx = ""
    Endif

    If modBasic.$RegistScheduleMode Then
      If modBasic.$RegistScheduleMode = "Scheduled" Then
        smode = GetScheduledBillingMode(compid)
        If smode = "" Then
          smode = xx
        Endif
      Else
        smode = xx
      Endif
    Else
      smode = xx
    Endif

  Endif
  Return smode

End

Public Sub GetBillingRegistDefaultMode(cmb As ComboBox, compid As String)

  cmb.Text = DefaultRegistBillingMode(compid)
  If cmb.Text Then
    If modBasic.$RegistFixMode Then
      If modBasic.$RegistFixMode = "Yes" Then
        cmb.Enabled = False
      Else
        cmb.Enabled = True
      Endif
    Else
      cmb.Enabled = True
    Endif
  Else
    cmb.Enabled = True
  Endif

End

''---------------------------------- Billing icon picture ----------------------------
Public Function GetBillingStatusIconConsult(sID As Long) As String

  Dim res As Result
  Dim xx As String
  Dim rs As Result

  rs = modDatabase.$myConn.Exec("select fldencounterval,fldconsultname from tblconsult where fldid=&1", sID)
  res = modDatabase.$myConn.Exec("select fldid from tblpatbilling where fldencounterval=&1 and (fldstatus=&2 or fldstatus=&3) and flditemname=&4", rs!fldencounterval, "Done", "Cleared", modNonMedical.GetDepartmentChargeMode(rs!fldconsultname))
  If res.Count = 0 Then
    xx = "icons/unchecked.png"
  Else
    xx = "icons/checked.png"
  Endif

  Return xx

End

Public Function GetSelectedBillNo(encid As String, sType As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldbillno from tblpatbilldetail where fldencounterval=&1", encid)
  If res.Available Then
    If sType = "First" Then
      res.MoveFirst
    Else If sType = "Last" Then
      res.MoveFirst
    Endif

    If res!fldbillno Then
      xx = res!fldbillno
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End

''================ Autobilling of bed charges ===================
Public Sub GetAutoBillingBedCharges(sType As String)

  Dim res As Result
  Dim res1 As Result
  Dim rsn As Result
  Dim xitem As String
  Dim rte As Float
  Dim tax As Float
  Dim disc As Float
  Dim itemNo As Integer

  Inc Application.Busy
  modDatabase.$myConn.Begin
  res = modDatabase.$myConn.Exec("select fldencounterval,fldcurrlocat,fldbillingmode,flddisctype from tblencounter where fldadmission=&1", "Admitted")
  If res.Available Then
    For Each res
      res1 = modDatabase.$myConn.Exec("select flddept from tbldepartmentbed where fldencounterval=&1", res["fldencounterval"])
      If res1.Available Then
        If sType = "Bed Charge" Then
          xitem = modNonMedical.GetDepartmentChargeMode(res1!flddept)
        Else If sType = "Round Charge" Then
          xitem = modNonMedical.GetDepartmentMornRoundCharge(res1!flddept)
        Endif

        itemNo = modNonMedical.GetCashBillItemID(xitem, "Service")
        rte = modNonMedical.GetCashBillItemCost(xitem, "General Services")
        tax = modNonMedical.ShowTaxValues("General Services", xitem)
        disc = modNonMedical.DiscPercentForItem(res["fldencounterval"], "General Services", xitem)
        InsertBlankBillItem(res["fldencounterval"], res["fldbillingmode"], "General Services", itemNo, xitem, rte, 1, tax, disc, "Done", 0, True, False)
      Endif
    Next

    rsn = modDatabase.$myConn.Create("tblcronjob")
    rsn["fldcategory"] = sType
    rsn["fldhostmac"] = modGeneralMain.$MACAddress
    rsn["fldscript"] = ""
    rsn["fldtime"] = Now()
    rsn["fldstatus"] = False
    rsn.Update
  Else
    Message.Warning("No Admitted Patients", "OK")
  Endif
  modDatabase.$myConn.Commit
  Dec Application.Busy
  Message.Info("Transaction completed", "OK")

Catch
  modDatabase.$myConn.Rollback
  Message.Warning("Transaction Rolled Back", "OK")

End
