' Gambas module file

Public $CashItemTarget As Collection
Public $CashItemID As Collection
Public $CashItemGroup As Collection

Public $DiscLaboratory As Float
Public $DiscRadiology As Float
Public $DiscProcedure As Float
Public $DiscEquipment As Float
Public $DiscServices As Float
Public $DiscOthers As Float
Public $DiscMedicine As Float
Public $DiscSurgical As Float
Public $DiscExtraItem As Float

'NOTE: ----------------------------------- Variable List for Transection----------------------------
Public Sub CompleteServiceTree(TreeView1 As TreeView, sType As String, stint As Integer, Optional txtsearch As String)

  Dim sstr1 As String
  Dim sstr2 As String
  Dim pic2 As Picture
  Dim pic3 As Picture
  Dim res1 As Result
  Dim res2 As Result

  pic2 = Picture["icons/coll2.png"]
  pic3 = Picture["icons/coll3.png"]
  TreeView1.Clear()
  If txtsearch Then
    sstr1 = "select fldbillitem as fldparent from tblbillitem where flditemcateg=&1 and lower(fldbillitem) like &2 ORDER BY fldbillitem ASC"
    res1 = modDatabase.$myConn.Exec(sstr1, sType, Lower(txtsearch) & "%")
  Else
    sstr1 = "select fldbillitem as fldparent from tblbillitem where flditemcateg=&1 ORDER BY fldbillitem ASC LIMIT 100 OFFSET &2"
    res1 = modDatabase.$myConn.Exec(sstr1, sType, stint)
  Endif
  If res1.Available Then
    For Each res1
      TreeView1.Add(res1!fldparent, res1!fldparent, pic2)

      sstr2 = "select flditemname as fldparent from tblservicecost where flditemtype=&1 and fldbillitem=&2"
      res2 = modDatabase.$myConn.Exec(sstr2, sType, res1!fldparent)
      If res2.Available Then
        For Each res2
          TreeView1.Add(res2!fldparent, res2!fldparent, pic3, res1!fldparent)
        Next
      Endif

    Next
  Endif

End

Public Function GetControlServCombo(txtitem As String) As Boolean

  Dim xx As Boolean
  Dim res As Result

  res = modDatabase.$myConn.Exec("select flditemname from tblservicecost where flditemname=&1", txtitem)
  xx = res.Available
  Return xx

End

Public Sub NonStockGroupItem(ComboBox1 As ComboBox)

  Dim sql As String
  Dim res As Result
  Dim textToCursor As String
  Dim textPosition As Integer

  textPosition = ComboBox1.Pos
  textToCursor = Mid(ComboBox1.Text, 1, textPosition)

  If Key.Code = Key.BackSpace Then
    ComboBox1.Clear
  Else
    If Key.Code = Key.Down Then
      ComboBox1.Clear
      If Not ComboBox1.Count Then
        sql = "select distinct(fldgroup) as col from tblservicegroup where lower(fldgroup) like &1 ORDER BY fldgroup ASC"
        res = modDatabase.$myConn.Exec(sql, LCase(textToCursor) & "%")
        modFillContainer.FillComboBox(ComboBox1, res)
      Endif
      ComboBox1.Popup
    Endif
  Endif

End

Public Function NonSTockGroupList() As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select distinct(fldgroup) as col from tblservicegroup")
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

''
Public Function NonSTockCostingGroupList(sType As String) As String[]

  Dim res As Result
  Dim xx As String[]

  res = modDatabase.$myConn.Exec("select distinct(fldgroup) as col from tblcostgroup where flditemtype=&1", sType)
  xx = modFillContainer.GetListFromResult(res)
  Return xx.Sort()

End

Public Function NonStockBillingItemArray(sType As String, txtmode As String, Optional sTarget As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]

  If sTarget Then
    sql = "select flditemname as col from tblservicecost where flditemtype=&1 and (fldgroup like &2 or fldgroup=&3) and fldtarget like &4"
    res = modDatabase.$myConn.Exec(sql, sType, txtmode, "%", sTarget)
  Else
    sql = "select flditemname as col from tblservicecost where flditemtype=&1 and (fldgroup like &2 or fldgroup=&3)"
    res = modDatabase.$myConn.Exec(sql, sType, txtmode, "%")
  Endif
  xx = modFillContainer.GetListFromResult(res)

  Return xx.Sort()

End

Public Function NonStockBillActiveItemArray(sType As String, txtmode As String, Optional sTarget As String) As String[]

  Dim sql As String
  Dim res As Result
  Dim xx As String[]

  If sTarget Then
    sql = "select flditemname as col from tblservicecost where flditemtype=&1 and (fldgroup like &2 or fldgroup=&4) and fldstatus=&3 and fldtarget like &5"
    res = modDatabase.$myConn.Exec(sql, sType, txtmode, "Active", "%", sTarget)
  Else
    sql = "select flditemname as col from tblservicecost where flditemtype=&1 and (fldgroup like &2 or fldgroup=&4) and fldstatus=&3"
    res = modDatabase.$myConn.Exec(sql, sType, txtmode, "Active", "%")
  Endif
  xx = modFillContainer.GetListFromResult(res)

  Return xx.Sort()

End

Public Function BillItemCategory() As String[]

  Dim xxx As String[]

  xxx = New String[]
  xxx.Add("Medicines")
  xxx.Add("Surgicals")
  xxx.Add("Extra Items")

  xxx.Add("Diagnostic Tests")
  xxx.Add("Radio Diagnostics")
  xxx.Add("General Services")
  xxx.Add("Procedures")
  xxx.Add("Equipment")
  xxx.Add("Other Items")
  xxx.Sort(gb.Ascent)
  Return xxx

End

''Get Category from route combo (used in tblpatbilling)
Public Sub GetBillItemCategoryFromCombo(txtitem As String) As String

  Dim txt As String

  If txtitem = "Test" Then
    txt = "Diagnostic Tests"
  Else If txtitem = "Radio" Then
    txt = "Radio Diagnostics"
  Else If txtitem = "Service" Then
    txt = "General Services"
  Else If txtitem = "Procedure" Then
    txt = "Procedures"
  Else If txtitem = "Equipment" Then
    txt = "Equipment"
  Else If txtitem = "Others" Then
    txt = "Other Items"

  Else If txtitem = "oral" Or txtitem = "liquid" Or txtitem = "fluid" Or txtitem = "injection" Or txtitem = "resp" Or txtitem = "topical" Or txtitem = "eye/ear" Or txtitem = "anal/vaginal" Or txtitem = "IVpush" Or txtitem = "CIV" Or txtitem = "IIV" Or txtitem = "SC" Or txtitem = "IM" Or txtitem = "IT" Or txtitem = "IDer" Or txtitem = "ICar" Or txtitem = "ISyn" Then                                                   '''''
    txt = "Medicines"
  Else If txtitem = "suture" Or txtitem = "msurg" Or txtitem = "ortho" Then
    txt = "Surgicals"
  Else If txtitem = "extra" Then
    txt = "Extra Items"
  Endif

  Return txt

End

'NOTE:------------------------------------ List for billing---------------------------------
Public Function FillCashModeCombo() As String[]

  Dim res As Result
  Dim xxx As String[]

  res = modDatabase.$myConn.Exec("select fldsetname from tblbillingset")
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx.Sort()

End

Public Function FillDiscountCombo() As String[]

  Dim xxx As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select fldtype from tbldiscount")
  xxx = modFillContainer.GetListFromResult(res)

  Return xxx.Sort()

End

Public Function GetGroupNameAccount() As String[]

  Dim xx As String[]
  Dim res As Result

  res = modDatabase.$myConn.Exec("select distinct(fldgroup) as col from tblreportgroup")
  xx = modFillContainer.GetListFromResult(res)

  Return xx.Sort()

End

Public Function GetReportGroupName(billitem As String) As String

  Dim res As Result
  Dim xx As String[]
  Dim xval As String

  xx = New String[]
  res = modDatabase.$myConn.Exec("select fldgroup from tblreportgroup where flditemname=&1", billitem)
  If res.Available Then
    For Each res
      xx.Add(res!fldgroup)
    Next
    xval = xx.Join(gb.NewLine)
  Else
    xval = ""
  Endif
  Return xval

End

'NOTE: ---------------------------- data from tblservicecost ----------------------------------------
Public Function GetBillingCategory(strItem As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flditemtype from tblservicecost where flditemname=&1", strItem)
  If res.Available = True Then
    If res!flditemtype Then
      xx = res!flditemtype
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetBillingTargeDept(strItem As String, strType As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($CashItemTarget, strItem)
  If Not xx Then
    res = modDatabase.$myConn.Exec("select fldtarget from tblservicecost where flditemname=&1 and flditemtype=&2", strItem, strType)
    If res.Available = True Then
      If res!fldtarget Then
        xx = res!fldtarget
        If modBasic.$LocalCache = "Yes" Then
          $CashItemTarget.Add(xx, strItem)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif

  Return xx

End

Public Function GetCashBillItemID(txtitem As String, txtype As String) As Integer

  Dim sql As String
  Dim res As Result
  Dim xx As Integer
  Dim yy As Variant

  yy = modHelpVariable.GetCollectionValue($CashItemID, txtitem)
  If yy Then
    xx = CInt(yy)
  Else
    xx = 0
  Endif

  If Not xx Then
    sql = "select fldid from tblservicecost where flditemname=&1 and flditemtype like &2"
    res = modDatabase.$myConn.Exec(sql, txtitem, GetBillItemCategoryFromCombo(txtype))
    If res.Available = True Then
      xx = res!fldid
      If modBasic.$LocalCache = "Yes" Then
        $CashItemID.Add(xx, txtitem)
      Endif
    Else
      xx = 0
    Endif
  Endif

  Return xx

End

Public Function GetBillingModeFromItemName(sItem As String) As String

  Dim res As Result
  Dim xx As String

  xx = modHelpVariable.GetCollectionValue($CashItemGroup, sItem)
  If Not xx Then
    res = modDatabase.$myConn.Exec("select fldgroup from tblservicecost where flditemname=&1", sItem)
    If res.Available = True Then
      If res!fldgroup Then
        xx = res!fldgroup
        If modBasic.$LocalCache = "Yes" Then
          $CashItemGroup.Add(xx, sItem)
        Endif
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif

  Return xx

End

'
'''
'''''

'NOTE: ------------------------------------Pre Billing Functions --------------------------------------------
Public Function GetDeptNameFromChargingItem(sItem As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flddept from tbldepartment where fldbedcharge=&1", sItem)
  If res.Available = True Then
    res.MoveFirst
    If res!flddept Then
      xx = res!flddept
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

'get IP billing rate
Public Function GetDepartmentChargeMode(sDept As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldbedcharge from tbldepartment where flddept=&1", sDept)
  If res.Available = True Then
    res.MoveFirst
    If res!fldbedcharge Then
      xx = res!fldbedcharge
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

Public Function GetDepartmentMornRoundCharge(sDept As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select fldround from tbldepartment where flddept=&1", sDept)
  If res.Available = True Then
    res.MoveFirst
    If res!fldround Then
      xx = res!fldround
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

''credit value
Public Function ShowCreditVAlues(DiscType As String) As Float

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select fldcredit from tbldiscount where fldtype=&1", DiscType)
  If res.Available = True Then
    res.MoveFirst
    If res!fldcredit Then
      xx = res!fldcredit
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End

Public Function GetSumCarryOnDeposit(bilid As Long) As Float

  Dim res As Result
  Dim res1 As Result
  Dim encdepo As Float

  encdepo = 0
  res = modDatabase.$myConn.Exec("select distinct(fldencounterval) from tblpatbilldetail where fldid<&1 and fldbilltype=&2", bilid, "Credit")
  If res.Available Then
    For Each res
      res1 = modDatabase.$myConn.Exec("select fldcurdeposit from tblpatbilldetail where fldencounterval=&1 and fldbilltype=&2 and fldid<&3", res!fldencounterval, "Credit", bilid)
      res1.MoveLast
      encdepo = encdepo + res1!fldcurdeposit
    Next
  Endif

  Return encdepo

End

Public Function GetSumCarryOnDepositByTime(sLast As Date) As Float

  Dim res As Result
  Dim res1 As Result
  Dim encdepo As Float

  encdepo = 0
  res = modDatabase.$myConn.Exec("select distinct(fldencounterval) from tblpatbilldetail where fldtime<&1 and fldbilltype=&2", sLast, "Credit")
  If res.Available Then
    For Each res
      res1 = modDatabase.$myConn.Exec("select fldcurdeposit from tblpatbilldetail where fldencounterval=&1 and fldbilltype=&2 and fldtime<&3", res!fldencounterval, "Credit", sLast)
      res1.MoveLast
      encdepo = encdepo + res1!fldcurdeposit
    Next
  Endif

  Return encdepo

End

''--------------------------------- for patient --------------------------------------------------------------
Public Function ShowDiscountCategEnc(encid As String) As String

  Dim res As Result
  Dim xx As String

  res = modDatabase.$myConn.Exec("select flddisctype from tblencounter where fldencounterval=&1", encid)
  If res.Available Then
    If res!flddisctype Then
      xx = res!flddisctype
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif

  Return xx

End

'for any type
Public Function ShowTaxValues(BillCateg As String, sItem As String) As Float

  Dim res As Result
  Dim taxval As Float

  If modBasic.$BillTaxMethod = "Department" Or If modBasic.$BillTaxMethod = "ItemWise" Then
    If BillCateg = "Medicines" Then
      res = modDatabase.$myConn.Exec("select fldtaxcode from tblmedbrand where fldbrandid=&1", sItem)
    Else If BillCateg = "Surgicals" Then
      res = modDatabase.$myConn.Exec("select fldtaxcode from tblsurgbrand where fldbrandid=&1", sItem)
    Else If BillCateg = "Extra Items" Then
      res = modDatabase.$myConn.Exec("select fldtaxcode from tblextrabrand where fldbrandid=&1", sItem)
    Else
      res = modDatabase.$myConn.Exec("select fldtaxcode from tblservicecost where flditemname=&1", sItem)
    Endif
    If res.Available Then
      If res["fldtaxcode"] Then
        taxval = GetTaxPerFromCode(res["fldtaxcode"])
      Else
        taxval = 0
      Endif
    Else
      taxval = 0
    Endif

  Else
    taxval = modBasic.$BillTaxFixedValue
  Endif

  Return taxval

End

Private Function GetTaxPerFromCode(xCode As String) As Float

  Dim res As Result
  Dim xval As Float

  res = modDatabase.$myConn.Exec("select fldtaxper from tbltaxgroup where fldgroup=&1", xCode)
  If res.Available Then
    If res["fldtaxper"] Then
      xval = res["fldtaxper"]
    Else
      xval = 0
    Endif
  Else
    xval = 0
  Endif
  Return xval

End

'for any type
Public Function ShowCreditVAlEnc(encid As String) As Float

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select fldcashcredit from tblencounter where fldencounterval=&1", encid)
  If res.Available Then
    If res!fldcashcredit Then
      xx = res!fldcashcredit
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End

''-------------------------------------- bill items id and rate -----------------------------------
''get item cost
Public Function GetCashBillItemCost(txtitem As String, txtype As String) As Float

  Dim sql As String
  Dim res As Result
  Dim xx As Float

  sql = "select flditemcost,flditemunit from tblservicecost where flditemname=&1 and flditemtype like &2"
  res = modDatabase.$myConn.Exec(sql, txtitem, txtype)
  If res.Available = True Then
    res.MoveFirst
    If res!flditemcost Then
      xx = modNonMedical.GetCurrConvertAmount(res!flditemcost, res!flditemunit)
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif

  Return xx

End

''get default department charge
Public Function GetDeptDefaultCharge(sDept As String) As Float

  Dim xx As Float
  Dim xitem As String

  xitem = GetDepartmentChargeMode(sDept)
  If xitem Then
    xx = GetCashBillItemCost(xitem, "General Services")
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetAllowDiscEdit(strItem As String, strType As String) As Boolean

  Dim res As Result
  Dim xx As Boolean

  res = modDatabase.$myConn.Exec("select fldeditdisc from tblservicecost where flditemname=&1 and flditemtype=&2", strItem, strType)
  If res.Available = True Then
    If res!fldeditdisc Then
      xx = res!fldeditdisc
    Else
      xx = False
    Endif
  Else
    xx = False
  Endif
  Return xx

End

Public Function GetAllowRateEdit(strItem As String, strType As String) As Boolean

  Dim res As Result
  Dim xx As Boolean

  res = modDatabase.$myConn.Exec("select fldeditrate from tblservicecost where flditemname=&1 and flditemtype=&2", strItem, strType)
  If res.Available = True Then
    If res!fldeditrate Then
      xx = res!fldeditrate
    Else
      xx = False
    Endif
  Else
    xx = False
  Endif
  Return xx

End

' 'NOTE: ----------------------- Generate ID for from tblid  ------------------------------------
' Public Function CurrentEncounter() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblid")
'   res.MoveFirst
'   xx = res!fldencounterid
'   res["fldencounterid"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End
'
' Public Function CurrentPatientNo() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblid")
'   res.MoveFirst
'   xx = res!fldpatientdno
'   res["fldpatientdno"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End
'
' Public Function CurrentStockNo() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblid")
'   res.MoveFirst
'   xx = res!fldstockno
'   res["fldstockno"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End
'
' Public Function CurrentJournalNo() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblid")
'   res.MoveFirst
'   xx = res!fldjournalno
'   res["fldjournalno"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End
'
' Public Function CurrentReferenceNo() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblid")
'   res.MoveFirst
'   xx = res!fldreferenceno
'   res["fldreferenceno"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End
'
' Public Function CurrentInnvoiceNo() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblid")
'   res.MoveFirst
'   xx = res!fldinvoiceno
'   res["fldinvoiceno"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End
'
' Public Function CurrentVoucherNo() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblid")
'   res.MoveFirst
'   xx = res!fldevoucherno
'   res["fldevoucherno"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End
'
' ''----------------------------------- Extra ID -----------------------------------------
' Public Function CurrentLabNo() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblextid")
'   res.MoveFirst
'   xx = res["fldsampleid"]
'   res["fldsampleid"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End
'
' Public Function CurrentAdmitFile() As Long
'
'   Dim res As Result
'   Dim xx As Long
'
'   res = modDatabase.$myConn.Edit("tblextid")
'   res.MoveFirst
'   xx = res["fldadmitfile"]
'   res["fldadmitfile"] = xx + 1
'   res.Update()
'   Return xx
'   'donot catch error. Error will rollback
'
' End

'NOTE: ----------------------- Generate ID for from tblautoid  ------------------------------------
Private Function GetAutoID(sType As String) As Long

  Dim res As Result
  Dim xx As Long

  res = modDatabase.$myConn.Edit("tblautoid", "fldtype=&1", sType)
  xx = res!fldvalue
  res["fldvalue"] = xx + 1
  res.Update()
  Return xx
  'donot catch error. Error will rollback

End

Public Function CurrentEncounter() As Long

  Dim xx As Long

  xx = GetAutoID("EncounterID")
  Return xx

End

Public Function CurrentPatientNo() As Long

  Dim xx As Long

  xx = GetAutoID("PatientNo")
  Return xx

End

Public Function CurrentStockNo() As Long

  Dim xx As Long

  xx = GetAutoID("StockNo")
  Return xx

End

Public Function CurrentJournalNo() As Long

  Dim xx As Long

  xx = GetAutoID("JournalNo")
  Return xx

End

Public Function CurrentReferenceNo() As Long

  Dim xx As Long

  xx = GetAutoID("ReferenceNo")
  Return xx

End

Public Function CurrentInnvoiceNo() As Long

  Dim xx As Long

  xx = GetAutoID("InvoiceNo")
  Return xx

End

Public Function CurrentVoucherNo() As Long

  Dim xx As Long

  xx = GetAutoID("VoucherNo")
  Return xx

End

Public Function CurrentLabNo() As Long

  Dim xx As Long

  xx = GetAutoID("LabSampleNo")
  Return xx

End

Public Function CurrentAdmitFile() As Long

  Dim xx As Long

  xx = GetAutoID("AdmitFileNo")
  Return xx

End

Public Function CurrentPurchaseRefNO() As Long

  Dim xx As Long

  xx = GetAutoID("PurchaseRefNo")
  Return xx

End

'NOTE: ------------------------------- Reference/Invoice Subscript -----------------------------
Private Function RefSubscript(sCode As String) As String

  Dim xx As String
  Dim rs As Result

  xx = modBasic.$ReferenceSubs[sCode & ":" & CStr(Date())]
  If Not xx Then
    rs = modDatabase.$myConn.Exec("select fldinvsub from tblinvid where fldinvcode=&1", sCode)
    If rs.Available Then
      If rs!fldinvsub Then
        xx = rs!fldinvsub
      Else
        xx = ""
      Endif
    Else
      xx = ""
    Endif
  Endif
  Return xx

End

'NOTE: --------------------------- Generate ID for reference -----------------------------------
Private Function ReferSign(BilType As String) As String

  Dim Bll As String

  If BilType = "Stock Transfer" Then
    Bll = "TRN"
  Else If BilType = "Bulk Dispensing" Then
    Bll = "BUL"
  Else If BilType = "Stock Return" Then
    Bll = "SRE"
  Else If BilType = "Stock Adjustment" Then
    Bll = "SAJ"
  Endif
  Return Bll
  'donot catch error. Error will rollback

End

Public Function ReferenceString(BilType As String) As String

  Dim inv As String
  Dim sCode As String

  sCode = ReferSign(BilType)
  inv = sCode & RefSubscript(sCode) & "-" & CStr(CurrentReferenceNo()) & modBasic.$HospCode
  Return inv
  'donot catch error. Error will rollback

End

Public Function PurchaseReference() As String

  Dim inv As String

  inv = "PUR" & RefSubscript("PUR") & "-" & CStr(CurrentPurchaseRefNO()) & modBasic.$HospCode
  Return inv

End

'NOTE: -----------------------------Generate ID for billing------------------------------------
Public Function InvSign(BilType As String) As String

  Dim Bll As String

  If BilType = "Cash Deposit" Then
    Bll = "DEP"
  Else If BilType = "Cash Billing" Then
    Bll = "CAS"
  Else If BilType = "Cash Return" Then
    Bll = "CRE"
  Else If BilType = "Pharmacy Sales" Then
    Bll = "PHM"
  Else If BilType = "Pharmacy Return" Then
    Bll = "RET"
  Endif
  Return Bll
  'donot catch error. Error will rollback

End

Public Function InvoiceString(BilType As String) As String

  Dim inv As String
  Dim sCode As String

  sCode = InvSign(BilType)
  inv = sCode & RefSubscript(sCode) & "-" & CStr(CurrentInnvoiceNo()) & modBasic.$HospCode
  Return inv
  'donot catch error. Error will rollback

End

Public Function VoucherNumber() As String

  Dim inv As String

  inv = "VNO-" & CStr(CurrentVoucherNo()) & modBasic.$HospCode
  Return inv
  'donot catch error. Error will rollback

End

Public Function EncounterIDValue() As String

  Dim xx As String

  xx = modBasic.$EncIdPrefix & modString.GetZeroStringText(CStr(CurrentEncounter()), modBasic.$EncIdLen) & modBasic.$HospCode
  Return xx

End

Public Function PatientNoValue() As String

  Dim xx As String

  xx = modBasic.$PatNoPrefix & modString.GetZeroStringText(CStr(CurrentPatientNo()), modBasic.$PatNoLen) & modBasic.$HospCode
  Return xx

End

Public Function BookingNoValue() As String

  Dim xx As String

  xx = modBasic.$BookNoPrefix & modString.GetZeroStringText(CStr(GetAutoID("BookingNo")), modBasic.$BookNoLen) & modBasic.$HospCode
  Return xx

End

''------------------------------------ Transection lock ---------------------------------
Public Function LockTableForID(sType As String) As Boolean

  Dim res As Result
  Dim xx As Boolean

  res = modDatabase.$myConn.Create("tbllock")
  res["fldlock"] = sType
  res.Update
  xx = True
  modBasic.DebugString("Process Locked for " & sType)
  Return xx

Catch
  xx = False
  If MMain.$IsGUIApp = True Then
    Message.Warning(("Transaction Locked. Type: ") & sType, ("OK"))
  Else
    Print "Transaction Locked. Type: " & sType
  Endif
  Return xx

End

Public Sub ReleaseLockTable(sType As String)

  modDatabase.$myConn.Delete("tbllock", "fldlock=&1", sType)
  modBasic.DebugString("Lock Released for " & sType)

End

'NOTE: ------------------------------------- Patient Transections ------------------------------------------
Public Function GetPatientDeposit(encid As String) As Float

  Dim res As Result
  Dim depo As Float

  res = modDatabase.$myConn.Exec("select fldcashdeposit from tblencounter where fldencounterval=&1", encid)
  If res.Available Then
    If res!fldcashdeposit Then
      depo = res!fldcashdeposit
    Else
      depo = 0
    Endif
  Else
    depo = 0
  Endif
  Return depo
  'donot catch error. Error will rollback

End

Public Sub UpdatePatientDeposit(encid As String, deposit As Float)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldcashdeposit"] = deposit
  res["xyz"] = False
  res.Update
  'donot catch error. Error will rollback

End

Public Function AllowEntryWithDeposit(encid As String, sType As String) As Boolean

  Dim allow As Boolean
  Dim expenseamt As Float
  Dim paidamt As Float
  Dim xauto As String

  xauto = modGlobalSetting.ShowSettingFromDB("LowDeposit/" & sType)
  If xauto Then
    If xauto = "Warn" Then
      paidamt = TotalPaidAmountbyPatient(modDatabase.$myConn, encid) + ShowCreditVAlEnc(encid)
      expenseamt = TotalExpenseAmountbyPatient(modDatabase.$myConn, encid)
      If expenseamt > paidamt Then
        allow = True
        Message.Warning(("Deposit lower than payments"), ("OK"))
      Else If expenseamt > 0.85 * paidamt Then
        allow = True
        Message.Warning(("85% of Deposit used. Ask for refill"), ("OK"))
      Else
        allow = True
      Endif

    Else If xauto = "Disable" Then
      paidamt = TotalPaidAmountbyPatient(modDatabase.$myConn, encid) + ShowCreditVAlEnc(encid)
      expenseamt = TotalExpenseAmountbyPatient(modDatabase.$myConn, encid)
      If expenseamt > paidamt Then
        allow = False
        Message.Warning(("Deposit lower than payments"), ("OK"))
      Else If expenseamt > 0.85 * paidamt Then
        allow = True
        Message.Warning(("85% of Deposit used. Ask for refill"), ("OK"))
      Else
        allow = True
      Endif

    Else
      allow = True
    Endif
  Else
    allow = True
  Endif

  Return allow

End

Public Function PaymentIconDeposit(encid As String) As String

  Dim expenseamt As Float
  Dim paidamt As Float
  Dim xx As String

  paidamt = TotalPaidAmountbyPatient(modDatabase.$myConn, encid) + ShowCreditVAlEnc(encid)
  expenseamt = TotalExpenseAmountbyPatient(modDatabase.$myConn, encid)

  If expenseamt > 0.85 * paidamt Then
    xx = "icons/true.svg"
  Else
    xx = "icons/false.svg"
  Endif
  Return xx

End

Public Function GetPatCurrentCharity(encid As String) As Float

  Dim res As Result
  Dim xx As Float

  res = modDatabase.$myConn.Exec("select fldcharity from tblencounter where fldencounterval=&1", encid)
  If res.Available Then
    If res!fldcharity Then
      xx = res!fldcharity
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

Public Sub UpdatePatientCharity(encid As String, amt As Float)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblencounter", "fldencounterval=&1", encid)
  res["fldadmitfile"] = amt
  res["xyz"] = False
  res.Update
  'donot catch error. Error will rollback

End

Public Sub CurrentPayStatusMsg(encid As String)

  Dim xx As String

  xx = "<b> CURRENT DEPOSIT: </b>" & modReportVar.GetLocaleNumberFormat(GetPatientDeposit(encid), gb.Currency)
  xx = xx & "<br>" & "<b> TOTAL EXPENSES: </b>" & modReportVar.GetLocaleNumberFormat(TotalExpenseAmountbyPatient(modDatabase.$myConn, encid), gb.Currency)
  xx = xx & "<br>" & "<b> TOTAL PAYMENTS: </b>" & modReportVar.GetLocaleNumberFormat(TotalPaidAmountbyPatient(modDatabase.$myConn, encid), gb.Currency)
  xx = xx & "<br>" & "<b> CREDIT ALLOWED: </b>" & modReportVar.GetLocaleNumberFormat(ShowCreditVAlEnc(encid), gb.Currency)
  xx = xx & "<br>" & "<b> UNUSED CHARITY: </b>" & modReportVar.GetLocaleNumberFormat(GetPatCurrentCharity(encid), gb.Currency)
  Message.Info(xx, ("OK"))

End

''NOTE: --------------------------------- CONNECTION DEPENDENT PROCEDURES ----------------------------------------------
''---------------------------------------- Patient Expenses --------------------------------------------------------
Public Function TotalExpenseAmountbyPatient($conn As Connection, encid As String) As Float

  Dim amt As Float
  Dim res As Result

  res = $conn.Exec("select SUM(fldditemamt) as tot from tblpatbilling where fldencounterval=&1 and fldsave=&2", encid, True)
  If res.Available Then
    If res!tot Then
      amt = res!tot
    Else
      amt = 0
    Endif
  Else
    amt = 0
  Endif

  Return amt

End

Public Function TotalPaidAmountbyPatient($conn As Connection, encid As String) As Float

  Dim amt As Float
  Dim res As Result

  res = $conn.Exec("select SUM(fldreceivedamt) as tot from tblpatbilldetail where fldencounterval=&1", encid)
  If res.Available Then
    If res!tot Then
      amt = res!tot
    Else
      amt = 0
    Endif
  Else
    amt = 0
  Endif

  Return amt

End

Public Function TotalUnpaidAmountyPatient($conn As Connection, encid As String) As Float

  Dim amt As Float
  Dim res As Result

  res = $conn.Exec("select SUM(flditemrate*flditemqty) as tot from tblpatbilling where fldencounterval=&1 and fldsave=&2 and fldprint=&3", encid, True, False)
  If res.Available Then
    If res!tot Then
      amt = res!tot
    Else
      amt = 0
    Endif
  Else
    amt = 0
  Endif

  Return amt

End

''---------------------------------------- User share calculation ------------------------------------
Public Function GetUserPayPercent($conn As Connection, userid As String, itemname As String, sCategory As String) As Float

  Dim res As Result
  Dim xx As Float

  res = $conn.Exec("select flditemshare from tbluserpay where flduserid=&1 and flditemname=&2 and flditemtype=&3", userid, itemname, sCategory)
  If res.Available Then
    res.MoveFirst
    If res!flditemshare Then
      xx = res!flditemshare
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetUserPayTaxReduction($conn As Connection, userid As String, itemname As String, sCategory As String) As Float

  Dim res As Result
  Dim xx As Float

  res = $conn.Exec("select flditemtax from tbluserpay where flduserid=&1 and flditemname=&2 and flditemtype=&3", userid, itemname, sCategory)
  If res.Available Then
    res.MoveFirst
    If res!flditemtax Then
      xx = res!flditemtax
    Else
      xx = 0
    Endif
  Else
    xx = 0
  Endif
  Return xx

End

Public Function GetUserShareAmt($conn As Connection, id As Long, sType As String) As Float

  Dim ushare As Float
  Dim res1 As Result

  res1 = modDatabase.$syConn.Exec("select flditemname,(flditemrate*flditemqty*(1-flddiscper/100)) as totl,fldpayto,fldrefer from tblpatbilling where fldid=&1", id)

  If sType = "Payable" Then
    If res1!fldpayto Then
      ushare = res1!totl * GetUserPayPercent($conn, res1!fldpayto, res1!flditemname, sType) / 100
    Else
      ushare = 0
    Endif
  Else If sType = "Referral" Then
    If res1!fldrefer Then
      ushare = res1!totl * GetUserPayPercent($conn, res1!fldrefer, res1!flditemname, sType) / 100
    Else
      ushare = 0
    Endif
  Endif

  Return ushare

End

Public Function GetUserTaxReduction($conn As Connection, id As Long, sType As String) As Float

  Dim ushare As Float
  Dim utax As Float
  Dim res1 As Result

  res1 = modDatabase.$syConn.Exec("select flditemname,(flditemrate*flditemqty*(1-flddiscper/100)) as totl,fldpayto,fldrefer from tblpatbilling where fldid=&1", id)

  If sType = "Payable" Then
    If res1!fldpayto Then
      ushare = res1!totl * GetUserPayPercent($conn, res1!fldpayto, res1!flditemname, sType) / 100
      utax = ushare * GetUserPayTaxReduction($conn, res1!fldpayto, res1!flditemname, sType) / 100
    Else
      utax = 0
    Endif
  Else If sType = "Referral" Then
    If res1!fldrefer Then
      ushare = res1!totl * GetUserPayPercent($conn, res1!fldrefer, res1!flditemname, sType) / 100
      utax = ushare * GetUserPayTaxReduction($conn, res1!fldrefer, res1!flditemname, sType) / 100
    Else
      utax = 0
    Endif
  Endif

  Return utax

End

Public Function GetUserPayOrReferAmt($conn As Connection, id As Long, sType As String) As Float

  Dim ushare As Float
  Dim utax As Float
  Dim netot As Float
  Dim res1 As Result

  res1 = modDatabase.$syConn.Exec("select flditemname,(flditemrate*flditemqty*(1-flddiscper/100)) as totl,fldpayto,fldrefer from tblpatbilling where fldid=&1", id)

  If sType = "Payable" Then
    If res1!fldpayto Then
      ushare = res1!totl * GetUserPayPercent($conn, res1!fldpayto, res1!flditemname, sType) / 100
      utax = ushare * GetUserPayTaxReduction($conn, res1!fldpayto, res1!flditemname, sType) / 100
    Else
      ushare = 0
      utax = 0
    Endif
  Else If sType = "Referral" Then
    If res1!fldrefer Then
      ushare = res1!totl * GetUserPayPercent($conn, res1!fldrefer, res1!flditemname, sType) / 100
      utax = ushare * GetUserPayTaxReduction($conn, res1!fldrefer, res1!flditemname, sType) / 100
    Else
      ushare = 0
      utax = 0
    Endif
  Endif
  netot = ushare - utax

  Return netot

End

''-------------------------------- Acc Demographic ----------------------------------
Public Sub AddAccGeneralQualiData(encid As String, strInput As String, strItem As String, strReport As String, strDetail As String, dt As Date, sav As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpataccgeneral")
  res["fldencounterval"] = encid
  res["fldinput"] = strInput
  res["fldtype"] = "Qualitative"
  res["flditem"] = strItem
  res["fldreportquali"] = strReport
  res["fldreportquanti"] = 0
  res["flddetail"] = strDetail
  res["fldnewdate"] = dt
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = sav
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update()
  'don't catch error

End

Public Sub AddAccGeneralQuantiData(encid As String, strInput As String, strItem As String, strReport As Float, strDetail As String, dt As Date, sav As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblpataccgeneral")
  res["fldencounterval"] = encid
  res["fldinput"] = strInput
  res["fldtype"] = "Quantitative"
  res["flditem"] = strItem
  res["fldreportquali"] = CStr(strReport)
  res["fldreportquanti"] = strReport
  res["flddetail"] = strDetail
  res["fldnewdate"] = dt
  res["flduserid"] = modGeneralMain.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modGeneralMain.compID
  res["fldsave"] = sav
  res["flduptime"] = ""
  res["xyz"] = False
  res.Update()
  'don't catch error

End

''Update
Public Sub UpdateAccGeneralQualiData(id As Long, strItem As String, strReport As String, strDetail As String, dt As Date, sav As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpataccgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["flditem"] = strItem
    res["fldreportquali"] = strReport
    res["flddetail"] = strDetail
    res["fldnewdate"] = dt
    res["flduserid"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["fldsave"] = sav
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

Public Sub UpdateAccGeneralQuantiData(id As Long, strItem As String, strReport As Float, strDetail As String, dt As Date, sav As Boolean)

  Dim res As Result

  res = modDatabase.$myConn.Edit("tblpataccgeneral", "fldid=&1", id)
  If modGeneral.AllowClinicalEdit(res["flduserid"]) = True Then
    res["flditem"] = strItem
    res["fldreportquali"] = CStr(strReport)
    res["fldreportquanti"] = strReport
    res["flddetail"] = strDetail
    res["fldnewdate"] = dt
    res["flduserid"] = modGeneralMain.$lbluser
    res["flduptime"] = Now()
    res["fldcomp"] = modGeneralMain.compID
    res["fldsave"] = sav
    res["xyz"] = False
    res.Update()
  Else
    Message.Warning("Authorization with " & res["flduserid"], ("OK"))
  Endif
  'don't catch error

End

''----------------------------------- Discount Settings -------------------------------
''discount by setting(patient or service mode)  '''Use General Services etc
Public Function DiscPercentForItem(encid As String, sType As String, sItem As String) As Float

  Dim disc As Float

  If modBasic.$BillDiscMethod = "Department" Then
    disc = DiscPercentServiceMode(sType, encid)
  Else If modBasic.$BillDiscMethod = "Encounter" Then
    disc = DiscPercentPatientMode(sType, encid, sItem)
  Else
    disc = modBasic.$BillDiscFixedValue
  Endif

  Return disc

End

'discount by service mode
Private Function DiscPercentServiceMode(BillCateg As String, encid As String) As Float

  Dim res As Result
  Dim taxval As Float

  res = modDatabase.$myConn.Exec("select flddiscpercent from tblextrasetting where fldcomp=&1 and fldcateg=&2 and fldcashmode=&3", modGeneralMain.compID, BillCateg, ShowDiscountCategEnc(encid))
  If res.Available = True Then
    res.MoveFirst
    If res!flddiscpercent Then
      taxval = res!flddiscpercent
    Else
      taxval = 0
    Endif
  Else
    taxval = 0
  Endif
  Return taxval

End

''discount by patient mode
Private Function DiscPercentPatientMode(sType As String, encid As String, sItem As String) As Float

  Dim xPack As String
  Dim xx As Float

  xPack = ShowDiscountCategEnc(encid)
  xx = DiscPercentForCategoryValue(xPack, sType, sItem)
  Return xx

End

Public Function DiscPercentForCategoryValue(DiscPackage As String, sType As String, sItem As String) As Float

  Dim xx As Float
  Dim res As Result
  Dim res1 As Result
  Dim rsx As Result

  rsx = modDatabase.$myConn.Exec("select flditemname from tblnodiscount where flditemname=&1", sItem)
  If rsx.Available Then  ''if item included in nodiscount table
    xx = 0
  Else

    res = modDatabase.$myConn.Exec("select fldmode,fldpercent,fldlab,fldradio,fldproc,fldequip,fldservice,fldother,fldmedicine,fldsurgical,fldextra from tbldiscount where fldtype=&1", DiscPackage)
    If res.Available Then
      If res!fldmode = "Fixed Percent" Then
        If res!fldpercent Then
          xx = res!fldpercent
        Endif
      Else If res!fldmode = "Custom Values" Then
        res1 = modDatabase.$myConn.Exec("select fldpercent from tblcustdiscount where fldtype=&1 and flditemname=&2 and flditemtype=&3", DiscPackage, sItem, sType)
        If res1.Available Then
          If res1!fldpercent Then
            xx = res1!fldpercent
          Endif
        Else
          If sType = "Medicines" Then
            If res!fldmedicine Then
              xx = res!fldmedicine
            Endif
          Else If sType = "Surgicals" Then
            If res!fldsurgical Then
              xx = res!fldsurgical
            Endif
          Else If sType = "Extra Items" Then
            If res!fldextra Then
              xx = res!fldextra
            Endif
          Else If sType = "Diagnostic Tests" Then
            If res!fldlab Then
              xx = res!fldlab
            Endif
          Else If sType = "Radio Diagnostics" Then
            If res!fldradio Then
              xx = res!fldradio
            Endif
          Else If sType = "General Services" Then
            If res!fldservice Then
              xx = res!fldservice
            Endif
          Else If sType = "Procedures" Then
            If res!fldproc Then
              xx = res!fldproc
            Endif
          Else If sType = "Equipment" Then
            If res!fldequip Then
              xx = res!fldequip
            Endif
          Else If sType = "Other Items" Then
            If res!fldother Then
              xx = res!fldother
            Endif
          Endif
        Endif
      Endif
    Endif

  Endif

  Return xx

End

''---------------- yearly fixed amount as discount ----------------------
Private Function GetDiscountStartDate(DiscType As String) As Date

  Dim res As Result
  Dim xval As Date

  res = modDatabase.$myConn.Exec("select fldyear from tbldiscount where fldtype=&1", DiscType)
  If res.Available Then
    If res!fldyear Then
      xval = res!fldyear
    Else
      xval = ""
    Endif
  Else
    xval = ""
  Endif
  Return xval

End

Private Function GetTotalDiscountYearly(DiscType As String) As Float

  Dim res1 As Result
  Dim xval As Float

  res1 = modDatabase.$myConn.Exec("select fldyear,fldamount from tbldiscount where fldtype=&1 and fldyear<=&2", DiscType, Date())
  If res1.Available Then
    If res1!fldamount Then
      xval = res1!fldamount
    Else
      xval = 0
    Endif
  Else
    xval = 0
  Endif
  Return xval

End

Public Function GetDiscUsedCurYear(patno As String, DiscType As String) As Float

  Dim res As Result
  Dim xdate As Date
  Dim xfrom As Date
  Dim xval As Float

  xdate = GetDiscountStartDate(DiscType)
  If xdate Then
    xfrom = Date(Year(Date()), Month(xdate), Day(xdate))
    res = modDatabase.$myConn.Exec("select SUM(flddiscamt) as tot from tblpatbilling where fldtime>=&1 and fldtime>=&2 and fldsave=&3 and fldencounterval in(select fldencounterval from tblencounter where fldpatientval=&4)", modDate.StartSqlDate(xdate), modDate.StartSqlDate(xfrom), True, patno)
    If res.Available Then
      If res!tot Then
        xval = res!tot
      Else
        xval = 0
      Endif
    Else
      xval = 0
    Endif
  Endif
  Return xval

End

Public Function AllowedDiscountCurrYear(patno As String, DiscType As String) As Float

  Dim xval As Float
  Dim xused As Float
  Dim xrem As Float

  xval = GetTotalDiscountYearly(DiscType)
  If xval Then
    xused = GetDiscUsedCurYear(patno, DiscType)
    xrem = xval - xused
  Endif

  Return xrem

End

Public Function AllowFixDiscount(patno As String, DiscType As String, sAmt As Float) As Boolean

  Dim xx As Boolean
  Dim xval As Float

  If GetTotalDiscountYearly(DiscType) Then
    If GetDiscountStartDate(DiscType) Then
      xval = AllowedDiscountCurrYear(patno, DiscType)
      If xval > sAmt Then
        xx = True
      Else
        xx = False
      Endif
    Else
      xx = True
    Endif
  Else
    xx = True
  Endif
  Return xx

End

Public Function GetCurrConvertAmount(sAmt As Float, sUnit As String) As Float

  Dim res As Result
  Dim xrate As Float
  Dim xamt As Float

  If sUnit Then
    res = modDatabase.$myConn.Exec("select fldconversion from tblcurrency where flditemunit=&1", sUnit)
    If res.Available Then
      If res["fldconversion"] Then
        xrate = res["fldconversion"]
      Else
        xrate = 0
      Endif
    Else
      xrate = 0
    Endif

  Else
    xrate = 1
  Endif
  xamt = Round(xrate * sAmt, -2)
  Return xamt

End
