' Gambas module file

'NOTE: ------------------------------- INSTALLED PACKAGES -----------------------------------------
Public Sub InstallSelectedApplication(AppList As String[])

  Dim xlist As String[]
  Dim hForm As FmTerminal

  If AppList Then
    If AppList.Count Then
      If UCase(DistributionOSName()) = "UBUNTU" Then
        xlist = ["sudo", "apt-get", "install"]
        xlist.Insert(AppList)

        hForm = New FmTerminal("Exec", xlist)
        hForm.ShowModal
      Endif
    Endif
  Endif

End

Private Function EssenAppList() As String[]

  Dim xx As String[]

  xx = New String[]

  'system binaries
  If System.Exist("facter") = False Then
    xx.Add("facter")
  Endif
  If System.Exist("ifconfig") = False Then
    xx.Add("net-tools")
  Endif
  If System.Exist("numconv") = False Then
    xx.Add("numconv")
  Endif
  If System.Exist("locale") = False Then
    xx.Add("locales")
  Endif

  'calculation
  If System.Exist("number") = False Then
    xx.Add("bsdgames")
  Endif
  If System.Exist("gbs3") = False Then
    xx.Add("gambas3-scripter")
  Endif

  ''ftp
  If System.Exist("wput") = False Or If System.Exist("wdel") = False Then
    xx.Add("wput")
  Endif
  If System.Exist("wget") = False Then
    xx.Add("wget")
  Endif

  'printing
  If System.Exist("wkhtmltopdf") = False Or If System.Exist("wkhtmltoimage") = False Then
    xx.Add("wkhtmltopdf")
  Endif
  If System.Exist("lp") = False Then
    xx.Add("cups-client")
  Endif

  Return xx

End

Private Function OptionalAppList() As String[]

  Dim xx As String[]

  xx = New String[]
  ''printing
  If System.Exist("links") = False Then
    xx.Add("links")
  Endif
  If System.Exist("txt2html") = False Then
    xx.Add("txt2html")
  Endif
  If System.Exist("pdftotext") = False Or If System.Exist("pdftocairo") = False Or If System.Exist("pdfunite") = False Then
    xx.Add("poppler-utils")
  Endif
  If System.Exist("html2text") = False Then
    xx.Add("html2text")
  Endif
  ' If System.Exist("html2ps") = False Then
  '   xx.Add("html2ps")
  ' Endif
  'compression
  If System.Exist("tar") = False Then
    xx.Add("tar")
  Endif
  If System.Exist("gzip") = False Then
    xx.Add("gzip")
  Endif
  If System.Exist("7z") = False Then
    xx.Add("p7zip-full")
  Endif
  'system binaries
  If System.Exist("xprintidle") = False Then
    xx.Add("xprintidle")
  Endif
  If System.Exist("socat") = False Then
    xx.Add("socat")
  Endif
  If System.Exist("sqlite3") = False Then
    xx.Add("sqlite3")
  Endif
  If System.Exist("curl") = False Then
    xx.Add("curl")
  Endif
  'barcode and webcam
  If System.Exist("zbarimg") = False Then
    xx.Add("zbar-tools")
  Endif
  If System.Exist("zint") = False Then
    xx.Add("zint")
  Endif
  If System.Exist("qrencode") = False Then
    xx.Add("qrencode")
  Endif
  If System.Exist("streamer") = False Then
    xx.Add("streamer")
  Endif
  If System.Exist("gst-launch-1.0") = False Then
    xx.Add("gstreamer1.0-tools")
  Endif
  'ssh remote login
  If System.Exist("openssl") = False Then
    xx.Add("openssl")
  Endif
  If System.Exist("ssh") = False Then
    xx.Add("openssh-client")
  Endif
  If System.Exist("sshd") = False Then
    xx.Add("openssh-server")
  Endif
  If System.Exist("sshpass") = False Then
    xx.Add("sshpass")
  Endif
  If System.Exist("sshfs") = False Then
    xx.Add("sshfs")
  Endif
  If System.Exist("xwd") = False Then
    xx.Add("x11-apps")
  Endif
  If System.Exist("convert") = False Then
    xx.Add("imagemagick")
  Endif
  'connect to remote mssql
  If System.Exist("sqsh") = False Then
    xx.Add("sqsh")
  Endif

  'plot
  If System.Exist("gnuplot") = False Then
    xx.Add("gnuplot-x11")
  Endif
  'notify
  If System.Exist("notify-send") = False Then
    xx.Add("libnotify-bin")
  Endif
  If System.Exist("espeak") = False Then
    xx.Add("espeak")
  Endif
  'compare pdf
  If System.Exist("comparepdf") = False Then
    xx.Add("comparepdf")
  Endif
  If System.Exist("meld") = False Then
    xx.Add("meld")
  Endif
  If System.Exist("qpdf") = False Then
    xx.Add("qpdf")
  Endif
  'translate
  If System.Exist("trans") = False Then
    xx.Add("translate-shell")
  Endif
  ''install
  If System.Exist("gdebi") = False Then
    xx.Add("gdebi-core")
  Endif
  If System.Exist("onboard") = False Then
    xx.Add("onboard")
  Endif

  Return xx

End

Public Function EssentialAppText() As String[]

  Dim xlist As String[]
  Dim xsel As String[]

  xsel = EssenAppList()
  If xsel.Count Then
    xlist = SelectListView("Select Application to install", xsel, True)
  Endif
  Return xlist

End

Public Function OptionalAppText() As String[]

  Dim xlist As String[]
  Dim xsel As String[]

  xsel = OptionalAppList()
  If xsel.Count Then
    xlist = SelectListView("Select Application to install", xsel, True)
  Endif
  Return xlist

End

'
''
'''
''''

'NOTE: -------------------------- SYSTEM PARAMATERS ------------------------------
Public Function GetDeskopTerminal() As String

  Dim aProg As String
  Dim sDesktop As String

  sDesktop = UCase(Desktop.Type)
  Select Case sDesktop
    Case "KDE", "KDE4", "KDE5"
      aProg = "konsole"
    Case "GNOME", "UNITY", "UBUNTU:GNOME"
      aProg = "gnome-terminal"
    Case "MATE", "CINNAMON"
      aProg = "mate-terminal"
    Case "XFCE"
      aProg = "xfce4-terminal"
    Case "LXDE"
      aProg = "lxterminal"
    Case "CYGWIN"
      aProg = "mintty.exe"
  End Select

  Return aProg

End

Public Function GetFacterValue(cmd As String) As String

  Dim yy As String
  Dim xx As String
  Dim arcmd As String[]

  arcmd = ["facter", cmd]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xx
  If xx Then
    yy = Trim(xx)
  Else
    yy = ""
  Endif
  Return yy

End

Public Function GetMACAddress() As String

  Dim xx As String
  Dim xcmd As String

  If modGeneralMain.$SysInterface Then
    xcmd = Subst("ifconfig &1 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'", modGeneralMain.$SysInterface)
    modBasic.DebugString("Execute " & xcmd)
    Shell xcmd To xx
    xx = Trim(xx)
    If Not xx Then
      xx = GetFacterValue("macaddress_" & modGeneralMain.$SysInterface)
    Endif

  Else
    xx = GetFacterValue("macaddress")
  Endif
  Return xx

End

Public Function GetLocalIP() As String

  Dim xx As String
  Dim xcmd As String

  If modGeneralMain.$SysInterface Then
    xcmd = Subst("ifconfig &1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'", modGeneralMain.$SysInterface)
    modBasic.DebugString("Execute " & xcmd)
    Shell xcmd To xx
    xx = Trim(xx)
  Else
    xx = GetFacterValue("ipaddress")
  Endif
  Return xx

End

Public Function GetNetworkInterfaceList() As String[]

  Dim sNetList As String[]
  Dim xx As String
  Dim arcmd As String[]

  arcmd = ["ls", "-1", "/sys/class/net"]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xx
  sNetList = Split(Trim(xx), gb.NewLine)
  Return sNetList

End

Public Function GetExternalIP() As String

  Dim xx As String
  Dim xcmd As String

  xcmd = "dig +short myip.opendns.com @resolver1.opendns.com"
  modBasic.DebugString("Execute " & xcmd)
  Shell xcmd To xx
  xx = Trim(xx)
  Return xx

End

Public Function DistributionOSName() As String

  Return GetFacterValue("operatingsystem")

End

Public Function GetKernelDistribution() As String

  Return GetFacterValue("kernelrelease")

End

Public Function DistributionVendor() As String

  Dim xx As String
  Dim yy As String
  Dim zz As String

  xx = DistributionOSName()
  yy = GetFacterValue("operatingsystemrelease")

  zz = xx & yy
  Return zz

End

Public Function GetApplicationPID(cmd As String) As Long

  Dim xx As String
  Dim yy As Long
  Dim arcmd As String[]

  arcmd = ["pidof", cmd]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xx
  yy = Val(xx)
  Return yy

End

Public Function GetPercentCPUUsage(pid As Long) As String

  Dim xx As String
  Dim yy As String
  Dim arcmd As String[]

  arcmd = ["ps", "-p", pid, "-o", "%cpu"]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xx
  yy = Replace(xx, "%CPU", "")
  Return Trim(yy)

End

Public Function GetMD5SumFile(sFile As String) As String

  Dim xx As String
  Dim smd As String[]
  Dim arcmd As String[]

  arcmd = ["md5sum", sFile]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xx
  smd = Split(xx, Space(1))
  Return Trim(smd[0])

End

Public Function GetSha1SumValue(sText As String) As String

  Dim arcmd As String
  Dim xx As String

  arcmd = "echo -n " & Quote(sText) & " | sha1sum | awk '{print $1}'"
  modBasic.DebugString("Execute " & arcmd)
  Shell arcmd To xx
  Return Trim(xx)

End

'NOTE: ----------------------------- SYSTEM ITEM LIST ----------------------------------------------
Public Function GetFontsAllList() As String[]

  Dim xx As String
  Dim xxx As String[]

  xxx = New String[]
  For Each xx In Fonts
    xxx.Add(xx)
  Next
  Return xxx

End

Public Function GetLocaleList() As String[]

  Dim xx As String
  Dim yy As String[]
  Dim zz As String
  Dim xlocal As String[]
  Dim arcmd As String[]

  xlocal = New String[]
  arcmd = ["locale", "-a"]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd To xx

  yy = Split(xx, gb.NewLine)
  For Each zz In yy
    If Len(zz) = 10 And If Right(zz, 4) = "utf8" Then
      xlocal.Add(Mid(zz, 1, -4) & "UTF-8")
    Endif
  Next

  Return xlocal

End

Public Function GetEnvironmentList() As String[]

  Dim xx As String
  Dim xenv As String[]

  xenv = New String[]
  For Each xx In Application.Env
    xenv.Add(xx & " : " & Env[xx])
  Next
  Return xenv

End

Public Function GetGambasComponets() As String[]

  Dim sComp As Component
  Dim xx As String[]

  xx = New String[]
  For Each sComp In Components
    xx.Add(sComp.Name)
  Next
  Return xx

End

'NOTE: ------------------------------ SYSTEM FUNCTIONS --------------------------------------
Public Function ConvertToLocalNumber(sNum As String, sToLang As String) As String

  Dim cmd As String
  Dim xx As String

  cmd = "echo " & sNum & " | numconv -f Western_Lower -t " & sToLang
  modBasic.DebugString("Execute " & cmd)
  Shell cmd To xx

  Return Trim(xx)

End

Public Sub ConfigureDateTime()

  Dim hForm As FmTerminal

  If UCase(DistributionOSName()) = "UBUNTU" Then
    hForm = New FmTerminal("Exec", ["sudo", "dpkg-reconfigure", "tzdata"])
    hForm.ShowModal
  Endif

End
