' Gambas module file

Private hAdvertiseExe As Process
Public $ExecValueColl As Collection

'NOTE: -------------------------- SHELL FUNCTION --------------------------
Public Sub RunRootCmdAsRoot(sCommand As String)

  Dim sPass As String
  Dim sEPass As String

  sPass = InputPassword(("Enter Password for Super User"), ("Super User"), "")
  sEPass = "echo \"" & sPass & "\" | "
  Shell sEPass & "sudo -S " & sCommand Wait

End

Public Function GerScriptValue(ScriptPath As String, ShellName As String, sArgument As Variant) As Variant

  Dim xfinal As Variant
  Dim arcmd As String[]
  Dim xexc As String

  If Exist(ScriptPath) Then
    xfinal = modHelpVariable.GetCollectionValue($ExecValueColl, ShellName & "@" & ScriptPath & "@" & CStr(sArgument))
    If Not xfinal Then
      If ShellName Then
        arcmd = [ShellName, ScriptPath, sArgument]
      Else
        arcmd = [ScriptPath, sArgument]
      Endif
      modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
      Exec arcmd To xexc
      xfinal = Trim(xexc)
      If modBasic.$LocalCache = "Yes" Then
        $ExecValueColl.Add(xfinal, ShellName & "@" & ScriptPath & "@" & CStr(sArgument))
      Endif
    Endif

  Else
    If TypeOf(sArgument) = gb.String Then
      xfinal = Trim(sArgument)
    Else
      xfinal = sArgument
    Endif
  Endif

  Return xfinal

End

Public Function GerScriptValueNoCache(ScriptPath As String, ShellName As String, sArgument As Variant) As Variant

  Dim xfinal As Variant
  Dim arcmd As String[]
  Dim xexc As String

  If Exist(ScriptPath) Then
    If ShellName Then
      arcmd = [ShellName, ScriptPath, sArgument]
    Else
      arcmd = [ScriptPath, sArgument]
    Endif
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd To xexc
    xfinal = Trim(xexc)

  Else
    If TypeOf(sArgument) = gb.String Then
      xfinal = Trim(sArgument)
    Else
      xfinal = sArgument
    Endif
  Endif

  Return xfinal

End

'
''
'''
''''

'NOTE: --------------------------- EXTERNAL APPLICATION --------------------------------------
Public Sub StartAdvertise()

  If System.Exist("sishadvertise") = True Then
    hAdvertiseExe = Exec ["gbr3", "/usr/bin/sishadvertise"]
    modSettings.SaveValuesToLog("Handle/sishadvertise", CStr(hAdvertiseExe.Handle))
  Endif

End

Public Sub CloseAdvertise()

  If System.Exist("sishadvertise") = True Then
    hAdvertiseExe.Kill()
  Endif

End

'
''
'''
''''
'NOTE: ---------------------------- SPECIAL SCRIPTS -------------------------------------------
Public Sub ExecStartUpScript()

  Dim arcmd As String[]
  Dim xscript As String
  Dim xexec As String

  arcmd = New String[]
  xscript = modSettings.ShowSettingFromFIle("GeneralSettings/StartupScript")
  If xscript Then
    If Exist(xscript) Then

      xexec = modSettings.ShowSettingFromFIle("GeneralSettings/StartupShell")
      If xexec Then
        arcmd.Add(xexec)
      Endif
      arcmd.Add(xscript)
      modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
      Exec arcmd Wait

    Endif
  Endif

End

Public Sub ExecClosingScript()

  Dim arcmd As String[]
  Dim xscript As String
  Dim xexec As String

  arcmd = New String[]
  xscript = modSettings.ShowSettingFromFIle("GeneralSettings/ClosingScript")
  If xscript Then
    If Exist(xscript) Then

      xexec = modSettings.ShowSettingFromFIle("GeneralSettings/ClosingShell")
      If xexec Then
        arcmd.Add(xexec)
      Endif
      arcmd.Add(xscript)
      modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
      Exec arcmd Wait

    Endif
  Endif

End

Public Sub ExecBeforePrint()

  Dim arcmd As String[]
  Dim xscript As String
  Dim xexec As String

  arcmd = New String[]
  xscript = modSettings.ShowSettingFromFIle("GeneralSettings/BeforePrintScript")
  If xscript Then
    If Exist(xscript) Then

      xexec = modSettings.ShowSettingFromFIle("GeneralSettings/BeforePrintShell")
      If xexec Then
        arcmd.Add(xexec)
      Endif
      arcmd.Add(xscript)
      modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
      Exec arcmd Wait

    Endif
  Endif

End

Public Sub ExecAfterPrint()

  Dim arcmd As String[]
  Dim xscript As String
  Dim xexec As String

  arcmd = New String[]
  xscript = modSettings.ShowSettingFromFIle("GeneralSettings/AfterPrintScript")
  If xscript Then
    If Exist(xscript) Then

      xexec = modSettings.ShowSettingFromFIle("GeneralSettings/AfterPrintShell")
      If xexec Then
        arcmd.Add(xexec)
      Endif
      arcmd.Add(xscript)
      modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
      Exec arcmd Wait

    Endif
  Endif

End

''-------------------------- Extrenal App ------------------------------
Public Sub RunKeyBoardScript()

  Dim xscript As String
  Dim xexec As String
  Dim arcmd As String[]

  xscript = modSettings.ShowSettingFromFIle("GeneralSettings/KeyBoard_Path")
  If xscript Then
    xexec = modSettings.ShowSettingFromFIle("GeneralSettings/KeyBoard_Shell")
    If xexec Then
      arcmd = [xexec, xscript]
    Else
      arcmd = [xscript]
    Endif
  Else
    arcmd = ["onboard"]
  Endif
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd

End

Public Sub RunExternalFixScript()

  Dim xscript As String
  Dim xexec As String
  Dim arcmd As String[]

  xscript = modSettings.ShowSettingFromFIle("GeneralSettings/ExtApp_Path")
  If xscript Then
    xexec = modSettings.ShowSettingFromFIle("GeneralSettings/ExtApp_Shell")
    If xexec Then
      arcmd = [xexec, xscript]
    Else
      arcmd = [xscript]
    Endif
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd
  Endif

End

Public Function RunTextHelpScript(sRead As String) As String

  Dim xscript As String
  Dim xexec As String
  Dim xx As String
  Dim arcmd As String[]

  xscript = modSettings.ShowSettingFromFIle("GeneralSettings/TextHelpScript")
  If xscript Then
    xexec = modSettings.ShowSettingFromFIle("GeneralSettings/TextHelpShell")
    If xexec Then
      arcmd = [xexec, xscript, sRead]
    Else
      arcmd = [xscript, sRead]
    Endif
    modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
    Exec arcmd To xx
  Endif
  Return Trim(xx)

End
