' Gambas module file

'''---------------------------------  COMBOBOX   -------------------------------------------------------------------------
' Public Function GetListFromResult(res As Result) As String[]
'
'   Dim xx As String[]
'   Dim ref As String
'
'   xx = New String[]
'   If res.Available Then
'     ref = modDatabase.FirstResultField(res)
'     For Each res
'       If res[ref] Then
'         xx.Add(res[ref])
'       Endif
'     Next
'   Endif
'   Return xx
'
' End

''From gambas 3.11 only
Public Function GetListFromResult(res As Result) As String[]

  Dim xx As String[]
  Dim ref As String
  Dim xval As String[]

  xx = New String[]
  If res.Available Then
    ref = modDatabase.FirstResultField(res)
    xval = res.All(ref)
    If xval Then
      xx = xval
    Endif
  Endif
  Return xx

End

Public Sub FillComboBox(ComboBox1 As ComboBox, res As Result)

  Dim xlist As String[]

  xlist = GetListFromResult(res)
  If xlist Then
    ComboBox1.List = xlist
  Endif

End

Public Sub RestrictCombo(cmb As ComboBox)

  Dim xlist As String[]

  If Len(Trim(cmb.Text)) Then
    xlist = cmb.List
    If xlist.Exist(cmb.Text) = False Then
      cmb.SetFocus
    Endif
  Endif

End

''Use on comboBox_KeyRelease()
Public Sub AutoFillComboBox(ComboBoxItems As ComboBox)

  Dim i As Integer
  Dim textToCursor As String
  Dim textPosition As Integer

  Inc Application.Busy
  If Key.Code = Key.Down Then
    textPosition = ComboBoxItems.Pos
    textToCursor = Mid(ComboBoxItems.Text, 1, textPosition)
    ComboBoxItems.Popup
    For i = 0 To ComboBoxItems.Count - 1
      If LCase(ComboBoxItems[i].Text) Like LCase(textToCursor) & "*" Then
        ComboBoxItems.Index = i
        Break
      Endif
    Next

  Else If Key.Code = Key.BackSpace Then
    If ComboBoxItems.Pos = 0 Then
    Else
      textPosition = ComboBoxItems.Pos - 1
      textToCursor = Mid(ComboBoxItems.Text, 1, textPosition)
      For i = 0 To ComboBoxItems.Count - 1
        If LCase(ComboBoxItems[i].Text) Like LCase(textToCursor) & "*" Then
          ComboBoxItems.Text = ComboBoxItems[i].Text
          ComboBoxItems.Pos = textPosition
          ComboBoxItems.Select(textPosition, Len(ComboBoxItems.Text) - textPosition)
          Break
        Endif
      Next
    Endif

  Else
    If ComboBoxItems.Pos = 0 Then
    Else
      textPosition = ComboBoxItems.Pos
      textToCursor = Mid(ComboBoxItems.Text, 1, textPosition)
      For i = 0 To ComboBoxItems.Count - 1
        If LCase(ComboBoxItems[i].Text) Like LCase(textToCursor) & "*" Then
          ComboBoxItems.Text = ComboBoxItems[i].Text
          ComboBoxItems.Pos = textPosition
          ComboBoxItems.Select(textPosition, Len(ComboBoxItems.Text) - textPosition)
          Break
        Endif
      Next
    Endif

  Endif
  Dec Application.Busy

End

'use on key release
Public Sub RestrictComboToContent(ComboBoxItems As ComboBox)

  Dim i As Integer
  Dim m As Integer
  Dim n As Integer
  Dim txt As String

  If Key.Code = Key.Space Then
    ComboBoxItems.Text = ""
  Else
    n = 0
    txt = Mid(ComboBoxItems.Text, 1, ComboBoxItems.Pos)
    m = Len(txt)
    If m > 0 Then
      For i = 0 To ComboBoxItems.Count - 1
        If Left(ComboBoxItems[i].Text, m) = txt Then
          n = n + 1
        Endif
      Next
      If n = 0 Then
        ComboBoxItems.Text = Left(txt, m - 1)
        AutoFillComboBox(ComboBoxItems)
      Endif
    Endif
  Endif

End

'''--------------------------------- LISTBOX   -------------------------------------------------
Public Sub FillListBox(ListBox1 As ListBox, res As Result, index As Boolean)

  If res.Available Then
    ListBox1.List = GetListFromResult(res)
    If index = True Then
      ListBox1.Index = 0
    Endif
  Endif

End

Public Function GetItemIndexListBox(ListBox1 As ListBox, sItem As String) As Integer

  Dim xx As Integer
  Dim i As Integer

  For i = 0 To ListBox1.List.Count - 1
    If ListBox1[i].Text = sItem Then
      xx = i
      Break
    Endif
  Next
  Return xx

End

'''------------------------------------ List View --------------------------------------------------------------------------------
Public Sub FillListViewFromArray(ListBox1 As ListView, sArry As String[])

  Dim pic1 As Picture
  Dim i As Integer
  Dim xx As String

  pic1 = Picture["icons/unchecked.png"]
  ListBox1.Clear()
  i = 1
  For Each xx In sArry
    If Len(xx) Then
      ListBox1.Add(CStr(i), xx, pic1)
      i = i + 1
    Endif
  Next

End

Public Sub FillCheckListViewFromArray(ListBox1 As ListView, sArry As String[])

  Dim pic1 As Picture
  Dim i As Integer
  Dim xx As String

  pic1 = Picture["icons/checked.png"]
  ListBox1.Clear()
  i = 1
  For Each xx In sArry
    If Len(xx) Then
      ListBox1.Add(CStr(i), xx, pic1)
      i = i + 1
    Endif
  Next

End

Public Sub FillListView(ListBox1 As ListView, res As Result)

  Dim pic1 As Picture
  Dim i As Integer

  pic1 = Picture["icons/unchecked.png"]
  ListBox1.Clear
  i = 1
  If res.Available Then
    For Each res
      If Len(res!col) Then
        ListBox1.Add(CStr(i), res!col, pic1)
        i = i + 1
      Endif
    Next
  Endif

End

Public Sub ShowCheckedListView(ListBox1 As ListView)

  Dim pic1 As Picture
  Dim pic2 As Picture

  pic1 = Picture["icons/unchecked.png"]
  pic2 = Picture["icons/checked.png"]

  If ListBox1.Current.Picture = pic1 Then
    ListBox1.Current.Picture = pic2
  Else If ListBox1.Current.Picture = pic2 Then
    ListBox1.Current.Picture = pic1
  Endif

End

'''------------------------------------------ TREEVIEW  -------------------------------------------------------------------------
Public Sub ExpandClickTreeView(TreeView1 As TreeView)

  If TreeView1.Current.Expanded = True Then
    TreeView1.Current.Expanded = False
  Else
    TreeView1.Current.Expanded = True
  Endif

End

Public Sub ExpandAllTreeView(TreeView1 As TreeView)

  With TreeView1
    .MoveFirst
    While .Available
      .Item.Expanded = True
      .MoveNext
    Wend
  End With

End

Public Sub ExpandClickColumnView(TreeView1 As ColumnView)

  If TreeView1.Current.Expanded = True Then
    TreeView1.Current.Expanded = False
  Else
    TreeView1.Current.Expanded = True
  Endif

End

Public Sub FillTreeView(sCon As Connection, TreeView1 As TreeView, key1 As String, str1 As String, key2 As String, str2 As String, key3 As String, str3 As String, key4 As String, str4 As String, txt1 As String, txt2 As String, txt3 As String, txt4 As String)                           ''

  Dim res1 As Result
  Dim i As Integer
  Dim sKey1 As String

  Dim res2 As Result
  Dim j As Integer
  Dim sKey2 As String

  Dim res3 As Result
  Dim k As Integer
  Dim sKey3 As String

  Dim res4 As Result
  Dim l As Integer
  Dim sKey4 As String

  Dim pic1 As Picture
  Dim pic2 As Picture
  Dim pic3 As Picture
  Dim pic4 As Picture

  pic1 = Picture["icons/coll1.png"]
  pic2 = Picture["icons/coll2.png"]
  pic3 = Picture["icons/coll3.png"]
  pic4 = Picture["icons/coll4.png"]

  TreeView1.Clear
  If txt1 = "" Then
    res1 = sCon.Exec(str1)
  Else If txt1 Then
    res1 = sCon.Exec(str1, txt1)
  Endif
  If res1.Available = True Then
    res1.MoveFirst
    For i = 1 To res1.Count
      If key1 = "" Then
        sKey1 = CStr(i) & "@" & res1!fldparent
      Else
        sKey1 = key1
      Endif
      TreeView1.Add(sKey1, res1!fldparent, pic1)

      If str2 Then
        If txt2 = "" Then
          res2 = sCon.Exec(str2, res1!fldparent)
        Else If txt2 Then
          res2 = sCon.Exec(str2, res1!fldparent, txt2)
        Endif
        If res2.Count > 0 Then
          res2.MoveFirst
          For j = 1 To res2.Count
            If key2 = "" Then
              sKey2 = CStr(i) & "@" & CStr(j) & "@" & res2!fldparent
            Else
              sKey2 = key2
            Endif
            TreeView1.Add(sKey2, res2!fldparent, pic2, sKey1)

            If str3 Then
              If txt3 = "" Then
                res3 = sCon.Exec(str3, res2!fldparent)
              Else If txt3 Then
                res3 = sCon.Exec(str3, res2!fldparent, txt3)
              Endif
              If res3.Count > 0 Then
                res3.MoveFirst
                For k = 1 To res3.Count
                  If key3 = "" Then
                    sKey3 = CStr(i) & "@" & CStr(j) & "@" & CStr(k) & "@" & res3!fldparent
                  Else
                    sKey3 = key3
                  Endif
                  TreeView1.Add(sKey3, res3!fldparent, pic3, sKey2)

                  If str4 Then
                    If txt4 = "" Then
                      res4 = sCon.Exec(str4, res3!fldparent)
                    Else If txt4 Then
                      res4 = sCon.Exec(str4, res3!fldparent, txt4)
                    Endif
                    If res4.Count > 0 Then
                      res4.MoveFirst
                      For l = 1 To res4.Count
                        If key4 = "" Then
                          sKey4 = CStr(i) & "@" & CStr(j) & "@" & CStr(k) & "@" & CStr(l) & "@" & res4!fldparent
                        Else
                          sKey4 = key4
                        Endif
                        TreeView1.Add(sKey4, res4!fldparent, pic4, sKey3)
                        res4.MoveNext
                      Next
                    Endif
                  Endif

                  res3.MoveNext
                Next
              Endif
            Endif

            res2.MoveNext
          Next
        Endif
      Endif

      res1.MoveNext
    Next
  Endif

End

'get key of above treeview
Public Function GetTextFromTreeKey(strKey As String) As String

  Dim xx As String
  Dim ss As Integer

  ss = RInStr(strKey, "@") + 1
  xx = Mid(strKey, ss, Len(strKey) - 1)

  Return xx

End
