' Gambas module file

''------------------------------------------- FOR SMALL DATA ---------------------------------------------------------------------
' Private $rData As Result
' Private $aMyFields As String[]
' on filling grid
' $rData = modDatabase.$myConn.Exec(sql)
' $aMyFields = New String[]
' modGridView.ReadSmallData(GridView1, $rData,$aMyFields)
' GridView1.Columns[0].Width = 100 * modBasic.$AppWidthRatio
' use as on data
' $rData.MoveTo(Row)
' modGeneralMain.GridViewDecoration(GridView1, Row)
' GridView1.Data.Text = $rData[$aMyFields[Column]]
Public Sub ReadSmallData(GridView1 As GridView, $hres As Result, $aMyFields As String[], Optional {index} As Integer)

  Dim $rf As ResultField

  GridView1.Clear
  GridView1.Columns.Count = $hres.Fields.Count
  GridView1.Rows.Count = $hres.Count
  For Each $rf In $hres.Fields
    $aMyFields.Add($rf.Name)
  Next
  GridView1.Rows.Height = 25 * modBasic.$AppHeightRatio

  If {index} Then
    GridView1.Row = {index}
  Else
    GridView1.Row = 0
  Endif

End

Public Sub ReadExplicitData(GridView1 As GridView, $hres As Result, Optional {index} As Integer)

  Dim j As Integer
  Dim fld As ResultField

  GridView1.Clear
  GridView1.Columns.Count = $hres.Fields.Count
  GridView1.Rows.Count = $hres.Count

  For Each $hres
    j = 0
    For Each fld In $hres.Fields
      modGeneralMain.GridExplicitDecoration(GridView1, $hres.Index, j)
      GridView1[$hres.Index, j].Text = $hres[fld.Name]
      j = j + 1
    Next
  Next
  GridView1.Rows.Height = 25 * modBasic.$AppHeightRatio

  If {index} Then
    GridView1.Row = {index}
  Else
    GridView1.Row = 0
  Endif

End

Public Sub LoadArrayToGridView(sList As Variant[], GridView1 As GridView)

  Dim idx As Integer

  GridView1.Columns.Count = 1
  GridView1.Rows.Count = sList.Count
  For idx = 0 To sList.Count - 1
    modGeneralMain.GridExplicitDecoration(GridView1, idx, 0)
    GridView1[idx, 0].Text = sList[idx]
  Next

End

'first row is grid column titles
Public Sub LoadCSVToGrid(sPath As String, sMark As String, GridView1 As GridView)

  Dim idx As Integer
  Dim xcoll As Collection
  Dim i As Integer
  Dim j As Integer

  Dim hCSV As CsvFile

  hCSV = New CsvFile(sPath, sMark)
  GridView1.Columns.Count = hCSV.Fields.Count
  GridView1.Rows.Count = modString.GetLineInTextFile(sPath) - 1
  GridView1.Rows.Height = 25 * modBasic.$AppHeightRatio
  For idx = 0 To hCSV.Fields.Count - 1
    GridView1.Columns[idx].Title = hCSV.Fields[idx]
    GridView1.Columns[idx].Width = CInt(Floor(GridView1.Width / GridView1.Columns.Count))
  Next

  i = 0
  While hCSV.Eof = False
    xcoll = hCSV.Read()
    For j = 0 To hCSV.Fields.Count - 1
      GridView1[i, j].Text = xcoll[hCSV.Fields[j]]
    Next
    i = i + 1
  Wend

End

'''------------------------------------------- ICON IN GRID ---------------------------------------------------------------
Public Function SetGridCheckIcon(abn As Boolean) As String

  Dim xx As String

  If abn = True Then
    xx = "icons/checked.png"
  Else
    xx = "icons/unchecked.png"
  Endif
  Return xx

End

'use this on grid_click
Public Sub CheckUncheckGrid(sCon As Connection, GridView1 As GridView, Col As Integer, fldCheck As String, fldid As String, tblCheck As String, serial As Long)

  Dim res As Result

  If fldCheck And If fldid And If tblCheck Then
    If GridView1[GridView1.Row, Col].Picture = modBasic.$PictureUnchecked Then
      res = sCon.Edit(tblCheck, fldid & "=&1", serial)
      res[fldCheck] = True
      res.Update()
      GridView1[GridView1.Row, Col].Picture = modBasic.$PictureChecked
    Else If GridView1[GridView1.Row, Col].Picture = modBasic.$PictureChecked Then
      res = sCon.Edit(tblCheck, fldid & "=&1", serial)
      res[fldCheck] = False
      res.Update()
      GridView1[GridView1.Row, Col].Picture = modBasic.$PictureUnchecked
    Endif
  Endif

End

Public Sub CheckUncheckGridNoDB(GridView1 As GridView, Col As Integer)

  If GridView1[GridView1.Row, Col].Picture = modBasic.$PictureUnchecked Then
    GridView1[GridView1.Row, Col].Picture = modBasic.$PictureChecked
  Else If GridView1[GridView1.Row, Col].Picture = modBasic.$PictureChecked Then
    GridView1[GridView1.Row, Col].Picture = modBasic.$PictureUnchecked
  Endif

End

Public Function GetGridIcon(txtboolean As Boolean) As String

  Dim xx As String

  If txtboolean = True Then
    xx = "icons/true.svg"
  Else
    xx = "icons/false.svg"
  Endif

  Return xx

End

Public Function GetIconValue(sPicture As Picture) As String

  Dim xbool As String

  If sPicture = Picture["icons/true.svg"] Then
    xbool = "Abnormal"
  Else If sPicture = Picture["icons/false.svg"] Then
    xbool = "Normal"
  Else
    xbool = ""
  Endif
  Return xbool

End

Public Sub SetLabReportIcon(TableView1 As GridView, col1 As Integer, col2 As Integer, colx As Integer)

  Dim Row As Integer

  For Row = 0 To TableView1.Rows.Count - 1
    If TableView1[Row, col1].Text = "Reported" Or TableView1[Row, col1].Text = "Verified" Then
      TableView1[Row, colx].Picture = Picture[GetGridIcon(TableView1[Row, col2].Text)]
    Else If TableView1[Row, col1].Text = "Sampled" Then
      TableView1[Row, colx].Picture = Picture["icons/null.svg"]
    Endif
  Next

End

''------------------------------ To change font of column -------------------------------------------------------------------
Public Sub SetAccordingToFontCol(GridView1 As GridView, colFont As Integer, colWord As Integer)

  Dim Row As Integer

  For Row = 0 To GridView1.Rows.Count - 1
    GridView1[row, colWord].Text = GridView1[row, colWord].Text
    GridView1[Row, colWord].Font = Font[GridView1[Row, colFont].Text]
  Next

End

''------------------------------- Search Text ---------------------------------
Public Function SearchTextinGrid(GridView1 As GridView, Column As Integer, SearchText As String) As Integer

  Dim i As Integer
  Dim p As Integer

  p = 0
  For i = 0 To GridView1.Rows.Count - 1
    If LCase(GridView1[i, Column].Text) Like "*" & LCase(SearchText) & "*" Then
      p = p + 1
    Else
      GridView1.Rows[i].Height = 1
    Endif
  Next
  Return p

End

''----------------------------- add total --------------------------------------
Public Function SumGridAmountt(GridView1 As GridView, col As Integer) As Float

  Dim xx As Float
  Dim i As Integer

  xx = 0
  For i = 0 To GridView1.Rows.Count - 1
    xx = xx + GridView1[i, col].Text
  Next

  Return xx

End

Public Function SumGridAmountDoublet(GridView1 As GridView, col1 As Integer, col2 As Integer) As Float

  Dim xx As Float
  Dim i As Integer

  xx = 0
  For i = 0 To GridView1.Rows.Count - 1
    xx = xx + GridView1[i, col1].Text * GridView1[i, col2].Text
  Next

  Return xx

End

Public Function GetItemPresentGrid(GridView1 As GridView, sCol As Integer, sItem As String) As Boolean

  Dim i As Integer
  Dim xx As Boolean

  xx = False
  For i = 0 To GridView1.Rows.Count - 1
    If GridView1[i, sCol].Text = sItem Then
      xx = True
      Break
    Endif
  Next

  Return xx

End

Public Function GetGridColValFromColText(xGridView As GridView, TestName As String, TestCol As Integer, valCol As Integer) As String

  Dim i As Integer
  Dim xx As String

  For i = 0 To xGridView.Rows.Count - 1
    If xGridView[i, TestCol].Text = TestName Then
      xx = xGridView[i, valCol].Text
      Break
    Endif
  Next
  Return xx

End

Public Function GetItemNameIndexGrid(GridView1 As GridView, indexcol As Integer, sItem As String) As Integer

  Dim xx As Integer
  Dim i As Integer

  For i = 0 To GridView1.Rows.Count - 1
    If GridView1[i, indexcol].Text = sItem Then
      xx = i
      Break
    Endif
  Next
  Return xx

End
