' Gambas module file

Public $appetcFolder As String
Public $appusrFolder As String
Public $appetcConfFile As String
Public $appetc7zFile As String
Public $appWebconfFile As String

Public AppName As String
Public AppDirectory As String
Public AppCacheDir As String
Public $htmlDirectory As String
Public $textDirectory As String
Public $docsDirectory As String
Public $localesDirectory As String
Public $mediaDirectory As String
Public $gnuDirectory As String
Public $templeteDirectory As String

Public $FIrstTimeSetting As Boolean
Public $ExistFixSetting As Boolean
Public $LogInCategory As String
Public $LogInGroup As String

Public $ImagePort As Integer = 5555
Public $alphabetAll As String[] = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

'NOTE: ------------------------------ File and Directory Functions -----------------------------
Public Sub MakeWorkingDir()

  AppName = Application.Name
  $appetcFolder = "/etc" &/ AppName
  $appetcConfFile = $appetcFolder &/ AppName & ".conf"
  $appetc7zFile = $appetcFolder &/ AppName & ".conf.7z"

  $appusrFolder = "/usr/share" &/ AppName
  $appWebconfFile = $appusrFolder &/ "web.conf"

  AppDirectory = Desktop.ConfigDir &/ AppName
  AppCacheDir = Desktop.CacheDir &/ AppName

  If Exist($appetcFolder &/ "html") Then
    $htmlDirectory = $appetcFolder &/ "html"
  Else
    $htmlDirectory = AppDirectory &/ "html"
  Endif
  If Exist($appetcFolder &/ "text") Then
    $textDirectory = $appetcFolder &/ "text"
  Else
    $textDirectory = AppDirectory &/ "text"
  Endif
  If Exist($appetcFolder &/ "docs") Then
    $docsDirectory = $appetcFolder &/ "docs"
  Else
    $docsDirectory = AppDirectory &/ "docs"
  Endif
  If Exist($appetcFolder &/ "locales") Then
    $localesDirectory = $appetcFolder &/ "locales"
  Else
    $localesDirectory = AppDirectory &/ "locales"
  Endif
  If Exist($appetcFolder &/ "media") Then
    $mediaDirectory = $appetcFolder &/ "media"
  Else
    $mediaDirectory = AppDirectory &/ "media"
  Endif
  If Exist($appetcFolder &/ "gnu") Then
    $gnuDirectory = $appetcFolder &/ "gnu"
  Else
    $gnuDirectory = AppDirectory &/ "gnu"
  Endif

  $templeteDirectory = AppDirectory &/ "templates"

  If Exist($appetcFolder &/ "appsettings.conf") Then
    $ExistFixSetting = True
  Else
    $ExistFixSetting = False
  Endif

  If Not Exist(AppDirectory) Then
    Mkdir AppDirectory
  Endif
  If Not Exist(AppCacheDir) Then
    Mkdir AppCacheDir
  Endif

  CopyFromFolderToFolder($appusrFolder, AppDirectory)
  MakeLocalSettingFile()

End

Private Sub MakeLocalSettingFile()

  If Not Exist(AppDirectory &/ "appsettings.conf") Then
    File.Save(AppDirectory &/ "appsettings.conf", "")
  Endif

End

Public Sub MakeSystemSettingFile()

  If Not Exist(AppDirectory &/ AppName & ".conf") Then
    File.Save(AppDirectory &/ AppName & ".conf", "")
  Endif

End

Public Sub CopyFromFolderToFolder(fromDir As String, toDir As String)

  Dim Directory As String
  Dim DirectoryList As String[]
  Dim sFile As String
  Dim FileList As String[]

  modBasic.DebugString("Copying files from " & fromDir & " to " & toDir)
  DirectoryList = Dir(fromDir, Null, gb.Directory)
  For Each Directory In DirectoryList
    If Not Exist(toDir &/ Directory) Then
      Mkdir toDir &/ Directory
      FileList = Dir(fromDir &/ Directory, Null, gb.File)
      For Each sFile In FileList
        If Not Exist(toDir &/ Directory &/ sFile) Then
          Copy fromDir &/ Directory &/ sFile To toDir &/ Directory &/ sFile
        Endif
      Next
      FileList.Clear
    Endif
  Next

  FileList = Dir(fromDir, Null, gb.File)
  For Each sFile In FileList
    If Not Exist(toDir &/ sFile) Then
      Copy fromDir &/ sFile To toDir &/ sFile
    Endif
  Next
  FileList.Clear

End

Public Sub ReplaceFileAsRoot(sPath1 As String, sFolder2 As String, sPass As String)

  Dim sEPass As String

  If sPass Then
    sEPass = "echo \"" & sPass & "\" | "
    If Not Exist(sFolder2) Then
      Shell sEPass & "sudo -S " & "mkdir " & sFolder2 Wait
    Endif
    If Exist(sFolder2 &/ File.Name(sPath1)) Then
      Shell sEPass & "sudo -S " & "rm " & sFolder2 &/ File.Name(sPath1) Wait
    Endif
    If Not Exist(sFolder2 &/ File.Name(sPath1)) Then
      Shell sEPass & "sudo -S " & "mv " & sPath1 & Space(1) & sFolder2 &/ File.Name(sPath1) Wait
    Endif
  Endif

End

Public Sub CopyAsRoot(sFromFile As String, sToFolder As String, sPass As String)

  Dim sEPass As String
  Dim xcmd As String

  If sPass Then
    sEPass = "echo \"" & sPass & "\" | "
    xcmd = sEPass & "sudo -S " & "cp " & sFromFile & Space(1) & sToFolder
    Shell xcmd Wait
  Endif

End

Public Sub DeleteFolderRecursive(sFolder As String)

  Dim arcmd As String

  arcmd = "rm -r " & sFolder
  modBasic.DebugString("Execute " & arcmd)
  Shell arcmd Wait

End

Public Function RestoreConfigSettings()

  Dim arcmd As String[]

  arcmd = ["tar", "xf", modHelpVariable.$appetcFolder &/ modHelpVariable.AppName & ".tmp.tar", "-C", Desktop.ConfigDir]
  modBasic.DebugString("Execute " & arcmd.Join(Space(1)))
  Exec arcmd Wait

End

'
''
'''
'''

'NOTE: ------------------------------- SOCKET PROGRAMMING ----------------------------
Public Function GetSelectedPort(userid As String) As Integer

  Dim xx As Integer

  xx = 35900 + modGeneral.GetMainUserCode(userid)
  Return xx

End

Public Function GetTransferPort(userid As String) As Integer

  Dim xx As Integer

  xx = 45900 + modGeneral.GetMainUserCode(userid)
  Return xx

End

Public Sub OpenPortForListening(SvrSock As ServerSocket)

  SvrSock.Type = Net.Internet
  SvrSock.Port = GetSelectedPort(modGeneralMain.$lbluser)
  modBasic.DebugString("Open Port " & CStr(SvrSock.Port) & " and Listen to it")
  SvrSock.Listen()

Catch
  CreateErrorReport()

End

Public Sub GetMessaging(SvrSock As ServerSocket)

  SvrSock.Type = Net.Internet
  SvrSock.Port = GetTransferPort(modGeneralMain.$lbluser)
  modBasic.DebugString("Open Port " & CStr(SvrSock.Port) & " and Listen to it")
  SvrSock.Listen()

Catch
  CreateErrorReport()

End

Public Function FindServerSocket(LoginType As String) As ServerSocket

  Dim xx As ServerSocket

  If LoginType = "Account" Then
    xx = fmAccount.ServerSocket1
  Else If LoginType = "Cashier" Then
    xx = fmCashier.ServerSocket1
  Else If LoginType = "Record" Then
    xx = fmRecord.ServerSocket1
  Else If LoginType = "Medical" Then
    xx = fmMedical.ServerSocket1
  Else If LoginType = "Technologist" Then
    xx = fmTechnologist.ServerSocket1
  Else If LoginType = "Technician" Then
    xx = fmTechnician.ServerSocket1
  Else If LoginType = "Consultant" Then
    xx = fmConsultant.ServerSocket1
  Else If LoginType = "Clinician" Then
    xx = fmOfficer.ServerSocket1
  Else If LoginType = "Purchase" Then
    xx = fmPurchase.ServerSocket1
  Else If LoginType = "Store" Then
    xx = fmStore.ServerSocket1
  Else If LoginType = "Pharmacist" Then
    xx = fmPharmacist.ServerSocket1
  Else If LoginType = "Dispensar" Then
    xx = fmDispensar.ServerSocket1
  Endif

  Return xx

End

Public Function FindTransferSocket(LoginType As String) As ServerSocket

  Dim xx As ServerSocket

  If LoginType = "Account" Then
    xx = fmAccount.ServerSocket2
  Else If LoginType = "Cashier" Then
    xx = fmCashier.ServerSocket2
  Else If LoginType = "Record" Then
    xx = fmRecord.ServerSocket2
  Else If LoginType = "Medical" Then
    xx = fmMedical.ServerSocket2
  Else If LoginType = "Technologist" Then
    xx = fmTechnologist.ServerSocket2
  Else If LoginType = "Technician" Then
    xx = fmTechnician.ServerSocket2
  Else If LoginType = "Consultant" Then
    xx = fmConsultant.ServerSocket2
  Else If LoginType = "Clinician" Then
    xx = fmOfficer.ServerSocket2
  Else If LoginType = "Purchase" Then
    xx = fmPurchase.ServerSocket2
  Else If LoginType = "Store" Then
    xx = fmStore.ServerSocket2
  Else If LoginType = "Pharmacist" Then
    xx = fmPharmacist.ServerSocket2
  Else If LoginType = "Dispensar" Then
    xx = fmDispensar.ServerSocket2
  Endif

  Return xx

End

'NOTE: ----------------------------  Workspace function -------------------------------------------
Public Function FindWorkProgressBar(LogInType As String) As ProgressBar

  Dim xx As ProgressBar

  If LoginType = "Account" Then
    xx = fmAccount.ProgressBar1
  Else If LoginType = "Cashier" Then
    xx = fmCashier.ProgressBar1
  Else If LoginType = "Record" Then
    xx = fmRecord.ProgressBar1
  Else If LoginType = "Medical" Then
    xx = fmMedical.ProgressBar1
  Else If LoginType = "Technologist" Then
    xx = fmTechnologist.ProgressBar1
  Else If LoginType = "Technician" Then
    xx = fmTechnician.ProgressBar1
  Else If LoginType = "Consultant" Then
    xx = fmConsultant.ProgressBar1
  Else If LoginType = "Clinician" Then
    xx = fmOfficer.ProgressBar1
  Else If LoginType = "Purchase" Then
    xx = fmPurchase.ProgressBar1
  Else If LoginType = "Store" Then
    xx = fmStore.ProgressBar1
  Else If LoginType = "Pharmacist" Then
    xx = fmPharmacist.ProgressBar1
  Else If LoginType = "Dispensar" Then
    xx = fmDispensar.ProgressBar1
  Endif

  Return xx

End

Public Function FindWorSpace(LoginType As String) As Workspace

  Dim xx As Workspace

  If LoginType = "Account" Then
    xx = fmAccount.Workspace1
  Else If LoginType = "Cashier" Then
    xx = fmCashier.Workspace1
  Else If LoginType = "Record" Then
    xx = fmRecord.Workspace1
  Else If LoginType = "Medical" Then
    xx = fmMedical.Workspace1
  Else If LoginType = "Technologist" Then
    xx = fmTechnologist.Workspace1
  Else If LoginType = "Technician" Then
    xx = fmTechnician.Workspace1
  Else If LoginType = "Consultant" Then
    xx = fmConsultant.Workspace1
  Else If LoginType = "Clinician" Then
    xx = fmOfficer.Workspace1
  Else If LoginType = "Purchase" Then
    xx = fmPurchase.Workspace1
  Else If LoginType = "Store" Then
    xx = fmStore.Workspace1
  Else If LoginType = "Pharmacist" Then
    xx = fmPharmacist.Workspace1
  Else If LoginType = "Dispensar" Then
    xx = fmDispensar.Workspace1
  Endif

  Return xx

End

Public Sub AddNewFormToWorkspace(hForm As Window)

  FindWorSpace($LogInCategory).Add(hForm)

End

Public Sub SetWorkSpaceImage()

  Dim sFile As String
  Dim img As Image
  Dim stimg As Image
  Dim xback As String

  sFile = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DeskPicture")
  If sFile And If Exist(sFile) Then
    Try img = Image.Load(sFile)
    If img Then
      stimg = img.Stretch(FindWorSpace($LogInCategory).Width, FindWorSpace($LogInCategory).Height)
      FindWorSpace($LogInCategory).Image = stimg
    Endif
  Else
    xback = modSettings.ShowUserWiseSettingFromFIle("AppSetting_DeskBackColor")
    If xback Then
      FindWorSpace($LogInCategory).Background = CInt(xback)
    Endif
  Endif

End

Public Sub SetWorkSpaceTabbing()

  Dim sTab As String

  sTab = modSettings.ShowUserWiseSettingFromFIle("AppSetting_TabPosition")
  If sTab Then
    If sTab = "Top" Then
      FindWorSpace($LogInCategory).Orientation = Align.Top
    Else If sTab = "Bottom" Then
      FindWorSpace($LogInCategory).Orientation = Align.Bottom
    Endif
  Endif

End

Public Sub PlayMediaFile()

  If Dialog.OpenFile() Then Return
  If modBasic.$MultiMediaFormat = "Embedded" Then
    fmMediaPlay.MediaView1.URL = Dialog.Path
    fmMediaPlay.Enabled = True
  Else
    Desktop.Open(Dialog.Path)
  Endif

End

'
''
'''
''''

Private Sub SaveSettingsToTransferFile(strSetting As String, strVal As String)

  Dim ConfFile As Settings

  ConfFile = New Settings(modHelpVariable.AppCacheDir &/ "/send.conf")
  ConfFile[strSetting] = Trim(strVal)

End

Public Sub SendMessageTo(ToUser As String, ToUserIP As String, txtsubject As String, txtcontent As String, sAttchment As String, sReply As Boolean, sImportant As Boolean)

  Dim MySock As Socket
  Dim sPath As String
  Dim xx As String
  Dim yy As String
  Dim hFile As File
  Dim sLine As String
  Dim hMsg As String

  Inc Application.Busy

  sPath = AppCacheDir &/ "send.conf"
  If sReply = True Then
    xx = "Yes"
  Else If sReply = False Then
    xx = "No"
  Endif
  If sImportant = True Then
    yy = "Yes"
  Else If sImportant = False Then
    yy = "No"
  Endif

  If Exist(sPath) Then Kill sPath
  File.Save(sPath, "")
  MySock = New Socket As "MySock"
  MySock.Host = ToUserIP
  MySock.Port = GetTransferPort(ToUser)
  modBasic.DebugString("Connect to Port " & CStr(MySock.Port) & " on Host " & MySock.Host)
  MySock.Connect()

  SaveSettingsToTransferFile("Message/To", ToUser)
  SaveSettingsToTransferFile("Message/From", modGeneralMain.$lbluser)
  SaveSettingsToTransferFile("Message/Subject", txtsubject)
  SaveSettingsToTransferFile("Message/Content", txtcontent)
  SaveSettingsToTransferFile("Message/Attachment", File.Name(sAttchment))
  SaveSettingsToTransferFile("Message/Reply", xx)
  SaveSettingsToTransferFile("Message/Important", yy)

  hFile = Open sPath For Input
  modBasic.DebugString("Open File " & sPath)
  hMsg = ""
  While Not Eof(hFile)
    Line Input #hFile, sLine
    hMsg = hMsg & sLine & gb.NewLine
  Wend

  While (MySock.Status <> 7) And (MySock.Status > 0)
    Wait 0.1
  Wend

  If MySock.Status = Net.Connected Then
    Write #MySock, hMsg, Len(hMsg)
    Close #MySock
  Endif

  If Exist(sPath) Then Kill sPath
  Dec Application.Busy

End
'
''
'''
''''

'NOTE: ------------------------------------- Create error file -----------------------------------
Public Sub CreateErrorReport()

  Dim ProgressBar1 As ProgressBar

  ProgressBar1 = FindWorkProgressBar($LogInCategory)
  If ProgressBar1 Then
    ProgressBar1.Tag = ""
    ProgressBar1.Pulse = False
    ProgressBar1.Visible = False
  Endif

  If Error.Text Then
    modBasic.DebugString("Error Text: " & Error.Text & " [" & Error.Where & "]")
  Endif
  If db.Current Then
    If db.Error Then
      modBasic.DebugString("Error Text: " & db.Error)
    Endif
  Endif

End

'
''
'''
''''

''--------------------------------- Local Cache ------------------------------------
Public Function GetCollectionValue(sColl As Collection, sKey As String) As Variant

  Dim xx As Variant

  If modGeneralMain.$conTarget = "Remote" Then
  Else

    If modBasic.$LocalCache = "Yes" Then
      If sColl Then
        If sColl.Count > 0 Then
          xx = sColl[sKey]
        Endif
      Endif
    Endif

  Endif
  Return xx

End

Public Sub CLearUserCollection()

  Dim xx As String[] = ["PatientData", "Diagnostic", "UserData", "DateData", "Medicine", "Inventory", "Account", "DrugProblems", "ExecValue"]
  Dim sItem As String

  sItem = InputCombo(("Select Cache Type"), ("Clear Cache"), xx, "", True)
  If sItem Then
    If sItem = "PatientData" Then
      modPatient.$PatNumData.Clear()
      modPatient.$PatNameData.Clear()
      modPatient.$PatGenderData.Clear()
      modPatient.$PatDOBData.Clear()
      modPatient.$PatContactData.Clear()
      modPatient.$PatAddressData.Clear()
      modPatient.$PatDistrictData.Clear()
      modPatient.$PatCodeData.Clear()
      modPatient.$PatRelationData.Clear()
      modPatient.$PatGuardData.Clear()
      modPatient.$PatEMailData.Clear()

      modPatient.$PatVisType.Clear()
      modPatient.$PatBillMode.Clear()
      modPatient.$PatDORegData.Clear()
      modPatient.$PatDOAData.Clear()
      modPatient.$PatRegDepartData.Clear()
      modPatient.$PatDODData.Clear()
      modPatient.$PatDOFollData.Clear()

    Else If sItem = "Diagnostic" Then
      modFixLab.$TestItemQualiQuanti.Clear()
      modFixLab.$TestItemCategory.Clear()
      modFixLab.$TestIDFromSysConst.Clear()
      modFixLab.$TestSpecimen.Clear()
      modFixLab.$TestCritValue.Clear()
      modFixLab.$TestOptionType.Clear()

      modFixLab.$TestDrugHypo.Clear()
      modFixLab.$TestdrugHyper.Clear()
      modFixLab.$TestSyndroBrady.Clear()
      modFixLab.$TestSyndroTachy.Clear()

      modFixClinic.$ExamItemQualiQuanti.Clear()
      modFixClinic.$ExamIDFromSysConst.Clear()
      modFixClinic.$ExamCritValue.Clear()
      modFixClinic.$ExamItemCategory.Clear()
      modFixClinic.$ExamOptionType.Clear()
      modFixClinic.$ExamSysOptionType.Clear()

      modFixClinic.$ExamDrugHypo.Clear()
      modFixClinic.$ExamdrugHyper.Clear()
      modFixClinic.$ExamSyndroBrady.Clear()
      modFixClinic.$ExamSyndroTachy.Clear()

      modFixRadio.$RadioItemCategory.Clear()
      modFixRadio.$RadioIDFromSysConst.Clear()
      modFixRadio.$RadioOptionType.Clear()
      modFixPatho.$SymptomCategory.Clear()

    Else If sItem = "UserData" Then
      modGeneral.$UserNameData.Clear()
      modGeneral.$UserCodeData.Clear()
      modGeneral.$EthnicCodeData.Clear()

    Else If sItem = "DateData" Then
      modDate.$LocalDateData.Clear()

    Else If sItem = "ExecValue" Then
      modExternal.$ExecValueColl.Clear()

    Else If sItem = "Medicine" Then
      modMedConstant.$MedBrandToGeneric.Clear()
      modMedConstant.$MedCodeFromStock.Clear()
      modMedConstant.$MedDrugFromStock.Clear()
      modMedConstant.$MedCodeFromDrug.Clear()
      modMedConstant.$MedSensiFromStock.Clear()
      modMedConstant.$MedRiskFromStock.Clear()
      modMedConstant.$MedStrengthStock.Clear()
      modMedConstant.$MedNarcoticStock.Clear()
      modMedConstant.$MedCategFromStock.Clear()

      modPharmLabel.$PharmPackVolume.Clear()
      modPharmLabel.$PharmPackVolUnit.Clear()

    Else If sItem = "Inventory" Then
      modStock.$ItemStorageCodeData.Clear()
      modStock.$ItemStockNameData.Clear()
      modStock.$ItemStockBatchData.Clear()
      modStock.$ItemStockExpData.Clear()
      modStock.$SurgiNameFromStock.Clear()
      modStock.$ExtraNameFromStock.Clear()

    Else If sItem = "Account" Then
      modNonMedical.$CashItemTarget.Clear()
      modNonMedical.$CashItemID.Clear()
      modNonMedical.$CashItemGroup.Clear()

    Endif
  Endif

End

Private Sub DumpCollection(sPath As String, sColl As Collection)

  Dim xFile As File
  Dim xx As String
  Dim xstr As String

  If sColl.Count Then
    If Exist(sPath) Then
      Kill sPath
    Endif

    xFile = Open sPath For Write Create
    For Each xx In sColl
      xstr = xx & ";" & sColl.Key
      Write #xFile, xstr & gb.NewLine, Len(xstr) + 1
    Next
    xFile.Close()
  Endif

End

Private Sub LoadDumpCollection(sPath As String, sColl As Collection)

  Dim xx As String
  Dim xFile As File
  Dim xval As String[]

  If Exist(sPath) Then
    xFile = Open sPath
    For Each xx In xFile.Lines
      xval = Split(xx, ";")
      sColl.Add(xval[0], xval[1])
    Next
    xFile.Close()
  Endif

End

Public Sub RestoreCacheDump()

  ' Dim res As Result
  Dim xdir As String

  xdir = AppCacheDir &/ "Data"

  If modBasic.$DumpCache = "Yes" And If modBasic.$LocalCache = "Yes" Then
    modBasic.DebugString("Restoring Local Cache")
    ' res = modDatabase.$calConn.Exec("select AD_DATE,BS_DATE from tblbsdate")
    ' For Each res
    '   modDate.$LocalDateData.Add(res!BS_DATE, CStr(Date(res!AD_DATE)))
    ' Next

    LoadDumpCollection(xdir &/ "TestType", modFixLab.$TestItemQualiQuanti)
    LoadDumpCollection(xdir &/ "TestCategory", modFixLab.$TestItemCategory)
    LoadDumpCollection(xdir &/ "TestIDSys", modFixLab.$TestIDFromSysConst)
    LoadDumpCollection(xdir &/ "TestSpecimen", modFixLab.$TestSpecimen)
    LoadDumpCollection(xdir &/ "TestCritical", modFixLab.$TestCritValue)
    LoadDumpCollection(xdir &/ "TestOptionType", modFixLab.$TestOptionType)

    LoadDumpCollection(xdir &/ "ExamType", modFixClinic.$ExamItemQualiQuanti)
    LoadDumpCollection(xdir &/ "ExamIDSys", modFixClinic.$ExamIDFromSysConst)
    LoadDumpCollection(xdir &/ "ExamCategory", modFixClinic.$ExamItemCategory)
    LoadDumpCollection(xdir &/ "ExamCritical", modFixClinic.$ExamCritValue)
    LoadDumpCollection(xdir &/ "ExamOptionType", modFixClinic.$ExamOptionType)
    LoadDumpCollection(xdir &/ "ExamSysOptionType", modFixClinic.$ExamSysOptionType)

    LoadDumpCollection(xdir &/ "RadioCategory", modFixRadio.$RadioItemCategory)
    LoadDumpCollection(xdir &/ "RadioIDSys", modFixRadio.$RadioIDFromSysConst)
    LoadDumpCollection(xdir &/ "RadioOptionType", modFixRadio.$RadioOptionType)

    LoadDumpCollection(xdir &/ "SymptomCategory", modFixPatho.$SymptomCategory)

    LoadDumpCollection(xdir &/ "UserName", modGeneral.$UserNameData)
    LoadDumpCollection(xdir &/ "UserCode", modGeneral.$UserCodeData)
    LoadDumpCollection(xdir &/ "EthnicCode", modGeneral.$EthnicCodeData)

    LoadDumpCollection(xdir &/ "BrandToGeneric", modMedConstant.$MedBrandToGeneric)
    LoadDumpCollection(xdir &/ "StockToCode", modMedConstant.$MedCodeFromStock)
    LoadDumpCollection(xdir &/ "StockToDrug", modMedConstant.$MedDrugFromStock)
    LoadDumpCollection(xdir &/ "DrugToCode", modMedConstant.$MedCodeFromDrug)
    LoadDumpCollection(xdir &/ "StockToSensi", modMedConstant.$MedSensiFromStock)
    LoadDumpCollection(xdir &/ "STockToCategory", modMedConstant.$MedCategFromStock)
    LoadDumpCollection(xdir &/ "StockToRisk", modMedConstant.$MedRiskFromStock)
    LoadDumpCollection(xdir &/ "StockStrength", modMedConstant.$MedStrengthStock)
    LoadDumpCollection(xdir &/ "StockNarco", modMedConstant.$MedNarcoticStock)

    LoadDumpCollection(xdir &/ "PackVolume", modPharmLabel.$PharmPackVolume)
    LoadDumpCollection(xdir &/ "PackVolUnit", modPharmLabel.$PharmPackVolUnit)

    LoadDumpCollection(xdir &/ "StorageCode", modStock.$ItemStorageCodeData)
    LoadDumpCollection(xdir &/ "StockNoName", modStock.$ItemStockNameData)
    LoadDumpCollection(xdir &/ "StockNoBatch", modStock.$ItemStockBatchData)
    LoadDumpCollection(xdir &/ "StockNoExpiry", modStock.$ItemStockExpData)
    LoadDumpCollection(xdir &/ "SurgicalToStock", modStock.$SurgiNameFromStock)
    LoadDumpCollection(xdir &/ "ExtraToStock", modStock.$ExtraNameFromStock)

    LoadDumpCollection(xdir &/ "CashItemTarget", modNonMedical.$CashItemTarget)
    LoadDumpCollection(xdir &/ "CashItemID", modNonMedical.$CashItemID)
    LoadDumpCollection(xdir &/ "CashItemGroup", modNonMedical.$CashItemGroup)

    modBasic.DebugString("Restoring Local Cache completed")
  Endif

End
