' Gambas module file

Public Sub ConvertHTMLtoPDF(stInput As String, stOutput As String, strType As String)

  Inc Application.Busy
  WkHTMLtoPDF(stInput, stOutput, strType)
  Dec Application.Busy

End

Public Sub WkHTMLtoPDF(stInput As String, stOutput As String, strType As String)

  Dim sPrt As String
  Dim xx As String[]

  If strType = "LabelSize" Then
    sPrt = "Label"
  Else If strType = "InvoiceSize" Then
    sPrt = "Invoice"
  Else If strType = "ReportSize" Then
    sPrt = "Report"
  Endif

  xx = New String[]
  xx.Add("wkhtmltopdf")
  xx.Add("-q")

  xx.Add(stInput)

  xx.Add(stOutput)

  modBasic.DebugString("Execute " & xx.Join(Space(1)))
  Exec xx Wait

End

'