' Gambas module file

''--------------------------------------- General setting file ---------------------------------
Public Function ShowSettingValue(sFile As String, strSetting As String) As String

  Dim ConfFile As Settings
  Dim strVal As String
  Dim xx As String

  ConfFile = New Settings(sFile)
  strVal = ConfFile[strSetting, Null]
  If strVal Then
    modBasic.DebugString("Reading Value for " & strSetting & " From " & sFile & " . . . Done")
    xx = Trim(strVal)
  Else
    modBasic.DebugString("Reading Value for " & strSetting & " From " & sFile)
    xx = ""
  Endif
  Return xx

End

'NOTE: CONFIG DIR ===========================================================================
'''-------------------------------------- appsettings.conf
Public Sub SaveSettingsToFile(strSetting As String, strVal As String)

  Dim ConfFile As Settings

  ConfFile = New Settings(modHelpVariable.AppDirectory &/ "appsettings.conf")
  ConfFile[strSetting] = Trim(strVal)

End

Public Function ShowSettingFromFIle(strSetting As String) As String

  Dim strVal As String

  If modHelpVariable.$ExistFixSetting = True Then
    strVal = ShowSettingValue(modHelpVariable.$appetcFolder &/ "appsettings.conf", strSetting)
    If Not strVal Then
      strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appsettings.conf", strSetting)
    Endif
  Else
    strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appsettings.conf", strSetting)
  Endif
  Return strVal

End

''checkbox ---
Public Sub EnterCheckSetting(chkvar As CheckBox, strTitle As String)

  If chkvar.Value = True Then
    SaveSettingsToFile(strTitle, "Yes")
  Else If chkvar.Value = False Then
    SaveSettingsToFile(strTitle, "No")
  Endif

End

Public Sub ShowCheckBox(chkvar As CheckBox, StrTitle As String)

  If ShowSettingFromFIle(StrTitle) = "Yes" Then
    chkvar.Value = True
  Else
    chkvar.Value = False
  Endif

End

Public Sub EnterButtonSetting(btnvar As YesNoButton, strTitle As String)

  If btnvar.Value = True Then
    SaveSettingsToFile(strTitle, "Yes")
  Else If btnvar.Value = False Then
    SaveSettingsToFile(strTitle, "No")
  Endif

End

Public Sub ShowButtonSetting(chkvar As YesNoButton, StrTitle As String)

  If ShowSettingFromFIle(StrTitle) = "Yes" Then
    chkvar.Value = True
  Else
    chkvar.Value = False
  Endif

End

'''-------------------------------------- appreporting.conf
Public Sub SaveSettingsToReport(strSetting As String, strVal As String)

  Dim ConfFile As Settings

  ConfFile = New Settings(modHelpVariable.AppDirectory &/ "appreporting.conf")
  ConfFile[strSetting] = Trim(strVal)

End

Public Function ShowSettingForReport(strSetting As String) As String

  Dim strVal As String

  If modHelpVariable.$ExistFixSetting = True Then
    strVal = ShowSettingValue(modHelpVariable.$appetcFolder &/ "appreporting.conf", strSetting)
    If Not strVal Then
      strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appreporting.conf", strSetting)
      If Not strVal Then
        strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appsettings.conf", strSetting)
      Endif
    Endif
  Else
    strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appreporting.conf", strSetting)
    If Not strVal Then
      strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appsettings.conf", strSetting)
    Endif
  Endif
  Return strVal

End

''checkbox ---
Public Sub EnterCheckReport(chkvar As CheckBox, strTitle As String)

  If chkvar.Value = True Then
    SaveSettingsToReport(strTitle, "Yes")
  Else If chkvar.Value = False Then
    SaveSettingsToReport(strTitle, "No")
  Endif

End

Public Sub ShowCheckReport(chkvar As CheckBox, StrTitle As String)

  If ShowSettingForReport(StrTitle) = "Yes" Then
    chkvar.Value = True
  Else
    chkvar.Value = False
  Endif

End

''----------------------------- for appvariable.conf ---------------------------------
Public Sub SaveSettingsToVar(strSetting As String, strVal As String)

  Dim ConfFile As Settings

  ConfFile = New Settings(modHelpVariable.AppDirectory &/ "appvariable.conf")
  ConfFile[strSetting] = Trim(strVal)

End

Public Function ShowSettingFromVar(strSetting As String) As String

  Dim strVal As String

  If modHelpVariable.$ExistFixSetting = True Then
    strVal = ShowSettingValue(modHelpVariable.$appetcFolder &/ "appvariable.conf", strSetting)
    If Not strVal Then
      strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appvariable.conf", strSetting)
    Endif
  Else
    strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appvariable.conf", strSetting)
  Endif
  Return strVal

End

''checkbox ---
Public Sub EnterCheckSettingVar(chkvar As CheckBox, strTitle As String)

  If chkvar.Value = True Then
    SaveSettingsToVar(strTitle, "Yes")
  Else If chkvar.Value = False Then
    SaveSettingsToVar(strTitle, "No")
  Endif

End

Public Sub ShowCheckBoxVar(chkvar As CheckBox, StrTitle As String)

  If ShowSettingFromVar(StrTitle) = "Yes" Then
    chkvar.Value = True
  Else
    chkvar.Value = False
  Endif

End

''-----------User specific---
Public Function ShowUserWiseSettingFromFIle(sTitle As String) As String

  Dim strVal As String

  If modHelpVariable.$ExistFixSetting = True Then
    ''get values from fixed settings
    strVal = ShowSettingValue(modHelpVariable.$appetcFolder &/ "appvariable.conf", sTitle & "/" & modGeneralMain.$lbluser)
    If Not strVal Then
      If modBasic.$GlobalUserID Then
        strVal = ShowSettingValue(modHelpVariable.$appetcFolder &/ "appvariable.conf", sTitle & "/" & modBasic.$GlobalUserID)
      Endif
    Endif

    ''get values from user setting
    If Not strVal Then
      strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appvariable.conf", sTitle & "/" & modGeneralMain.$lbluser)
    Endif
    If Not strVal Then
      If modBasic.$GlobalUserID Then
        strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appvariable.conf", sTitle & "/" & modBasic.$GlobalUserID)
      Endif
    Endif

  Else
    strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appvariable.conf", sTitle & "/" & modGeneralMain.$lbluser)
    If Not strVal Then
      If modBasic.$GlobalUserID Then
        strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "appvariable.conf", sTitle & "/" & modBasic.$GlobalUserID)
      Endif
    Endif
  Endif
  Return strVal

End

'''-------------------------------------------- calculation.conf
Public Sub SaveCalcSettingsToFile(strSetting As String, strVal As String)

  Dim ConfFile As Settings

  ConfFile = New Settings(modHelpVariable.AppDirectory &/ "calculation.conf")
  ConfFile[strSetting] = Trim(strVal)

End

Public Function ShowCalcSettingFromFIle(strSetting As String) As String

  Dim strVal As String

  strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "calculation.conf", strSetting)
  Return strVal

End

'''-------------------------------------------- equations.conf
Public Sub SaveEqnSettingsToFile(strSetting As String, strVal As String)

  Dim ConfFile As Settings

  ConfFile = New Settings(modHelpVariable.AppDirectory &/ "/calculators/equations.conf")
  ConfFile[strSetting] = Trim(strVal)

End

Public Function ShowEqnSettingFromFIle(strSetting As String) As String

  Dim strVal As String

  strVal = ShowSettingValue(modHelpVariable.AppDirectory &/ "/calculators/equations.conf", strSetting)
  Return strVal

End

'NOTE: /etc/hospinepal directory ========================================================
''----------------------------------------------- appextdb.conf
Public Function ShowExtSettingFromFIle(strSetting As String) As String

  Dim strVal As String

  strVal = ShowSettingValue(modHelpVariable.$appetcFolder &/ "appextdb.conf", strSetting)
  Return strVal

End

'NOTE: CACHE DIR ===========================================================================
'''-------------------------------------- applog.conf
Public Sub SaveValuesToLog(strSetting As String, strVal As String)

  Dim ConfFile As Settings

  ConfFile = New Settings(modHelpVariable.AppCacheDir &/ "applog.conf")
  ConfFile[strSetting] = Trim(strVal)

End

Public Function ShowLogValues(strSetting As String) As String

  Dim strVal As String

  strVal = ShowSettingValue(modHelpVariable.AppCacheDir &/ "applog.conf", strSetting)
  Return strVal

End
