' Gambas module file

Public $SISHAppMode As String
Public $IsGUIApp As Boolean
Private $isdebug As Boolean

Public Sub Main()

  $IsGUIApp = True
  $isdebug = True
  GUIMode()

End

Private Sub GUIMode()

  Dim xfont As String
  Dim xfirday As String
  Dim xdebug As String
  Dim xtooltip As String
  Dim xtheme As String
  Dim xshel As String

  InitialProcedures()
  Print Application.Name & ": Reading Application settings"

  'display both unity and local menu
  Application.Env["APPMENU_DISPLAY_BOTH"] = "1"

  'choose debug mode
  xdebug = modSettings.ShowSettingFromFIle("GeneralSettings/DebuggingMode_Enable")
  If xdebug = "Yes" Then
    modBasic.$DebugMode = True
  Endif

  'set shell to use
  xshel = modSettings.ShowSettingFromFIle("Application/ShellPath")
  If xshel Then
    System.Shell = xshel
  Endif

  'choose first day of week
  xfirday = modSettings.ShowSettingFromFIle("Application/WeekFirstDay")
  If xfirday Then
    System.FirstDayOfWeek = modDate.GetDayCode(xfirday)
  Else
    System.FirstDayOfWeek = gb.Sunday
  Endif

  'choose font for application
  xfont = modSettings.ShowSettingFromFIle("Application/ApplicationFont")
  If xfont Then
    Application.Font = Font[xfont]
  Endif

  'choose icon theme
  xtheme = modSettings.ShowSettingFromFIle("Application/IconTheme")
  If xtheme Then
    Application.Theme = xtheme
  Endif

  'disable tooltip
  xtooltip = modSettings.ShowSettingFromFIle("GeneralSettings/DisableToolTip")
  If xtooltip = "Yes" Then
    Application.ShowTooltips = False
  Endif

  '----------------------choose HIS or Pharmacy or Laboratoryb-----------------------------------
  GetApplicationType()

  If modSettings.ShowSettingFromFIle("TermsOfUse/Accept") = "Yes" Then
    modBasic.DebugString("User has accepted Terms and Conditions for using " & Application.Name & " version " & Application.Version)
    If $SISHAppMode = "HIS" Then
      fmLogIn.Show
    Endif
  Else
    fmAccept.Show
  Endif

End

''------------------------------------------ Procedures ----------------------------------------------
Private Sub InitialProcedures()

  Dim xlocal As String

  If $IsGUIApp = True Then
    Print Application.Name & ": Copy required Files and setting Directories"
  Endif
  'creating/setting directories
  modHelpVariable.MakeWorkingDir()
  'find out config file
  SetConfigurationFile()

  ''set localization
  'choose localization
  xlocal = modSettings.ShowSettingFromFIle("Application/Localization")
  If xlocal Then
    System.Language = xlocal
  Else
    System.Language = "en_US.UTF-8"
  Endif

End

Public Sub SetConfigurationFile()

  If Exist(modHelpVariable.$appetcConfFile) Then
    modGeneralMain.$SysConfigPath = modHelpVariable.$appetcConfFile
  Else
    modGeneralMain.$SysConfigPath = modHelpVariable.$appetc7zFile
  Endif
  If $IsGUIApp = True Then
    Print Application.Name & ": Configuration File is " & modGeneralMain.$SysConfigPath
  Endif

End

Private Sub GetApplicationType()

  $SISHAppMode = "HIS"

End

Public Sub Application_Error()

  Try modExternal.CloseAdvertise()
  If Error.Text Then
    If MMain.$IsGUIApp = True Then
      Error Application.Name & ": " & Format(Now(), gb.GeneralDate) & " : " & "Error Text: " & Error.Text & " [" & Error.Where & "]"
    Else
      Print Application.Name & ": " & Format(Now(), gb.GeneralDate) & " : " & "Error Text: " & Error.Text & " [" & Error.Where & "]"
    Endif
    modSettings.SaveValuesToLog(Format(Now(), gb.GeneralDate) & "/Application Error", Error.Text & " [" & Error.Where & "]")
    Message.Warning(("Application Error") & gb.NewLine & ("Please restart your application."), ("OK"))
  Endif
  If db.Current Then
    If db.Error Then
      If MMain.$IsGUIApp = True Then
        Error Application.Name & ": " & Format(Now(), gb.GeneralDate) & " : " & "Error Text: " & db.Error
      Else
        Print Application.Name & ": " & Format(Now(), gb.GeneralDate) & " : " & "Error Text: " & db.Error
      Endif
      modSettings.SaveValuesToLog(Format(Now(), gb.GeneralDate) & "/Database Error", db.Error)
      Message.Warning(("Database Error") & gb.NewLine & ("Please restart your application."), ("OK"))
    Endif
  Endif

End
